### ISSUE TITLE
Widget actions in jupyterlab

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter-widgets/ipywidgets#1005]
We need the same actions as in the widgetsnbextension for the labextension.

 - Save notebook with widget state
 - Download widget state
 - Embed widgets

**Comment by jasongrout** [comment]
This is an item for the JupyterLab plugin, which is not on the same release cycle as ipywidgets/jupyter-js-widgets/widgetsnbextension because it is still alpha. Therefore I'm removing it from the 6.0 milestone.

**Comment by vidartf** [comment]
Note: Adding logic for loading saved widgets can be done as a distinct step for this issue, as it should be unrelated to any actions/UI needs.

**Comment by SylvainCorlay** [comment]
This is now fixed in 7.5.0.
