### ISSUE TITLE
Phosphor dropdown: wrong placement on window resize

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter-widgets/ipywidgets#1030]
The dropdown is badly positioned when the window is resized. We should probably recompute its position on window resize.

**Comment by jasongrout** [comment]
Or close it on window resize. We already close if there is a scroll event.

**Comment by SylvainCorlay** [comment]
Yes indeed.

**Comment by jasongrout** [comment]
This is 'fixed' for now since we reverted back to a native select. So putting this back in backlog.
