### ISSUE TITLE
Document individual widget model schemas

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#1032]
We should set an example of how to clearly communicate widget models by documenting the state for each widget that we provide in ipywidgets.

CC @rgbkrk

**Comment by SylvainCorlay** [comment]
Note: I guess we want to specify a schema for a patch to the state rather than the full state.

**Comment by SylvainCorlay** [comment]
@jasongrout I don't think that having individual schemas for widget model patches is in scope for 6.0.

**Comment by jasongrout** [comment]
This is done in #1207.
