### ISSUE TITLE
Embed Widgets: does not work with 3rd party widget (e.g: nglview)

### ISSUE THREAD

**Issue by hainm** [jupyter-widgets/ipywidgets#1038]
Hi,

I am trying `6.0.0.beta6` version for embedding widget. This works fine with `ipydigets` Widgets (Text, ...) but did not work with our `nglview`:

- nothing shows up if hitting `Embed Widgets`
- console error: 
```bash
Uncaught (in promise) TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at :8795/nbextensions/jupyter-js-widgets/extension.js?v=20170113130756:34960
```

```bash
widgetsnbextension.__version__
Out[4]:
'2.0.0.beta9'
```

cheers. Hai

**Comment by SylvainCorlay** [comment]
Hi, I think that you have a model attribute that is not json-serializable.

**Comment by hainm** [comment]
thanks. 

- should `ipywidgets` be more aggressive in error report? 
- is it possible to report which attribute that is not json-ized?

**Comment by jasongrout** [comment]
It looks like that's the browser javascript function giving the error, and the error message indicates that there is a circular reference in the structure. We could use a replacer to try to narrow this down (see http://stackoverflow.com/questions/11616630/json-stringify-avoid-typeerror-converting-circular-structure-to-json for many solutions), but I'm not sure what performance cost we'd pay. Regardless, you could use a replacer or inspector directly in your code like in several of those answers to detect where your cycle is.

**Comment by hainm** [comment]
thanks for you debug info. 

Hai

**Comment by jasongrout** [comment]
@hainm, is this fixed in #1044? (https://github.com/jupyter-widgets/ipywidgets/issues/1044#issuecomment-293777646).

**Comment by hainm** [comment]
@jasongrout I have not tried this yet. Do we need to wait for https://github.com/jupyter-widgets/ipywidgets/issues/1283?

**Comment by jasongrout** [comment]
> Do we need to wait for #1283?

Okay, yes, let's wait for the beta coming out soon.

**Comment by jasongrout** [comment]
@hainm - I just released an alpha of all of the packages. Can you test to see if this is fixed now?

**Comment by hainm** [comment]
I will do tonight. thanks Jason.

**Comment by hainm** [comment]
hi,

I just tried.

> nothing shows up if hitting Embed Widgets

This issue is fixed but there is still no-show in web browser.

*Notebook*
```python
import nglview
nglview.demo()
```

Console after open html file having embedded code:
<img width="549" alt="screen shot 2017-04-28 at 4 55 23 pm" src="https://cloud.githubusercontent.com/assets/4451957/25547054/8584856e-2c33-11e7-84ee-ff904a10fab9.png">

Attach file is the html file

[test.txt](https://github.com/jupyter-widgets/ipywidgets/files/965559/test.txt)

**Comment by hainm** [comment]
I guess I need to publish "nglview-js-widgets" (the _view_module) in unpkg.com too, right?

**Comment by jasongrout** [comment]
> I guess I need to publish "nglview-js-widgets" (the _view_module) in unpkg.com too, right?

Or write your own embedded widget manager that slips in your own copy instead of going to unpkg.com.

**Comment by hainm** [comment]
> Or write your own embedded widget manager that slips in your own copy instead of going to unpkg.com.

ah, is there any tutorial for dummy regarding this? If I remember correctly, previous `ipywidgets` version handle that.

**Comment by hainm** [comment]
I guess I need to read `ipyvolume` here. Seems closely related.
https://ipyvolume.readthedocs.io/en/latest/animation.html

**Comment by hainm** [comment]
Sounds like this is what you meant about "slips"

https://github.com/maartenbreddels/ipyvolume/blob/master/ipyvolume/embed.py

**Comment by maartenbreddels** [comment]
Hi @hainm, ipyvolume doesn't use it's own widget manager (I only have some custom code to generate the html, which will hopefully go upstream one day), that would be some js code.
However, it's odd that when I open your html file, I don't see an attempt get fetch 'nglview-js-widgets.js', which ipywidgets 6 did. Is this something you changed @jasongrout? Since that is ideal for testing.

**Comment by SylvainCorlay** [comment]
The current embed manager already checks whether a version of the custom widget is vendored locally.

**Comment by maartenbreddels** [comment]
I'm not sure what you mean, for the above test.txt file (it's html), you'd expect to see a request to nglview-js-widgets.js before the last 403 right?
![screen shot 2017-04-29 at 20 54 37](https://cloud.githubusercontent.com/assets/1765949/25558007/1b1f5244-2d1e-11e7-8a1c-ce161dba69c0.png)

**Comment by SylvainCorlay** [comment]
Unless @jasongrout removed it for the beta, If you go to e.g. http://jupyter.org/widgets, you see failed requests to locally served static resources for custom widgets:

![screenshot from 2017-04-29 21-00-15](https://cloud.githubusercontent.com/assets/2397974/25558037/e50050a4-2d1e-11e7-81d4-e2bb6527ff73.png)

**Comment by maartenbreddels** [comment]
indeed, but that is `https://unpkg.com/jupyter-js-widgets@2.1.4/dist/embed.js`, not `https://unpkg.com/jupyter-js-widgets@3.0.0/dist/embed.js`, so I guess it's removed.

**Comment by SylvainCorlay** [comment]
We should add it back before the final.

**Comment by jasongrout** [comment]
The embed manager doesn't assume require is on the page anymore. Is that what you are talking about?

**Comment by maartenbreddels** [comment]
I don't think so. 
For example when [opening this page](https://www.astro.rug.nl/~breddels/test/stream-short/) you see that it first tries to load `ipyvolume.js`, only when that fails, it should go to `https://unpkg.com/....`, that feature disappeared in `jupyter-js-widget@3.0.0`, it now directly goes to `https://unpkg.com/....`

**Comment by maartenbreddels** [comment]
Now i cannot test the dev version of ipyvolume anymore, any idea where this feature disappeared@SylvainCorlay  or @jasongrout, then maybe I can take a look at it?

**Comment by jasongrout** [comment]
> any idea where this feature disappeared@SylvainCorlay or @jasongrout, then maybe I can take a look at it?

Probably this PR: https://github.com/jupyter-widgets/ipywidgets/pull/1313

Basically I deleted the base loadClass method and made each widget manager completely in charge of implementing loadClass. We'd just have to add back in the require-based loading to the embed manager.

**Comment by maartenbreddels** [comment]
thx, should I take a shot at it?

**Comment by jasongrout** [comment]
Go for it if you want. I won't be able to work on it for a few days.

**Comment by jasongrout** [comment]
Should be fixed by #1336.

**Comment by jasongrout** [comment]
Reopening so you can test it.

**Comment by jasongrout** [comment]
@hainm - this should hopefully be fixed by #1336. I'll close it, but please reopen if you find it still doesn't work.

**Comment by hainm** [comment]
Thanks. I will test.

Hai

**Comment by hainm** [comment]
hi @jasongrout, unfortunately there is no good news yet. Please see error below + the attached html file (need to rename it)
<img width="1277" alt="screen shot 2017-05-18 at 8 11 32 pm" src="https://cloud.githubusercontent.com/assets/4451957/26228312/bba4a1a0-3c06-11e7-90c9-1e541bce2ea0.png">



[try.txt](https://github.com/jupyter-widgets/ipywidgets/files/1012749/try.txt)

**Comment by hainm** [comment]
btw, there is no reopen button in this issue.

**Comment by jasongrout** [comment]
Are you *sure* you're setting the `_view_module` and `_view_name` attributes in that particular model you are trying to display?

**Comment by hainm** [comment]
I don't know anything about that. I thought displaying is just as easy as display it?

![1](https://cloud.githubusercontent.com/assets/4451957/26229178/b3ad5e4a-3c0d-11e7-8445-bfa3acd02233.png)

**Comment by jasongrout** [comment]
This is the model that you're trying to display in the example above with the error? https://github.com/arose/nglview/blob/master/nglview/widget.py#L85

It looks like it indeed does have a _view_module and _view_name defined. 

Looking at your try.txt file, here's what I see as the widget state for the nglview widget:

`{"state": {"22e65513d02547ce807baf6ad763f296": {"model_name": "DOMWidgetModel", "model_module": "jupyter-js-widgets", "state": {"_dom_classes": [], "_scene_position": {}, "_original_stage_parameters": {}, "_scene_rotation": {}, "picked": {}, "layout": "IPY_MODEL_f020583843da4929997ae33d498ccc2a", "orientation": [], "_full_stage_parameters": {}}, "model_module_version": "3.0.0"}`

There is no _view_module or _view_name, so it relies on the defaults for that particular model. That model has a default view name set to null, though. I think that is where the error is coming from.

The code that saves the widget state is here: https://github.com/jupyter-widgets/ipywidgets/blob/3ae4d117d086c2c02ce5d8fdfb0c45230a46d1db/jupyter-js-widgets/src/widget.ts#L228. Can you try setting a breakpoint there and seeing what happens if you choose the Widgets | Embed Widgets menu item?

Also, it looks like in your screenshot that it is running jupyter-js-widgets 2.1.4, instead of some 3.0 alpha, which would be current master.

**Comment by hainm** [comment]
> It looks like it indeed does have a _view_module and _view_name defined.

Yes, you helped that. https://github.com/jupyter-widgets/ipywidgets/issues/1044#issuecomment-293776680

Per debugging, I will follow your guide.

> Also, it looks like in your screenshot that it is running jupyter-js-widgets 2.1.4, instead of some 3.0 alpha, which would be current master.

I guess I need to update this https://github.com/arose/nglview/blob/master/js/package.json#L32-L47, right?

Is there (or will be) any script to update version info about core libraries? Following this repo for a while but I still feel get trapped in scattering info. 

cheers
Hai

**Comment by hainm** [comment]
and native question: How can I check the versions in notebook? Sometimes web-browser caching is evil.

**Comment by hainm** [comment]
uhm, this simple code (example.html) does not show anything

```bash

<html>
<script src="https://unpkg.com/jupyter-js-widgets@~3.0.0-alpha.6/dist/embed.js"></script>
<script type="application/vnd.jupyter.widget-state+json">
{
    "version_major": 2,
    "version_minor": 0,
    "state": {
        "cd151d618c364fccbe336abf1c6960f1": {
            "model_name": "LayoutModel",
            "model_module": "jupyter-js-widgets",
            "model_module_version": "3.0.0",
            "state": {}
        },
        "f44bf9592480492bbd74a5a5ea7599ee": {
            "model_name": "TextModel",
            "model_module": "jupyter-js-widgets",
            "model_module_version": "3.0.0",
            "state": {
                "value": "hello",
                "layout": "IPY_MODEL_cd151d618c364fccbe336abf1c6960f1"
            }
        }
    }
}
</script>
<script type="application/vnd.jupyter.widget-view+json">
{
    "version_major": "2",
    "model_id": "f44bf9592480492bbd74a5a5ea7599ee",
    "version_minor": "0"
}
</script>
</html>

```

<img width="561" alt="screen shot 2017-05-19 at 7 59 09 pm" src="https://cloud.githubusercontent.com/assets/4451957/26270934/ae6c2b58-3ccd-11e7-901a-4efe71f2da12.png">

**Comment by jasongrout** [comment]
Thanks. I'll look into this Monday.

**Comment by jasongrout** [comment]
> uhm, this simple code (example.html) does not show anything

You need to put the widget-view into a `<body>` tag:

```html
<html>
<script src="https://unpkg.com/jupyter-js-widgets@~3.0.0-alpha.6/dist/embed.js"></script>
<script type="application/vnd.jupyter.widget-state+json">
{
    "version_major": 2,
    "version_minor": 0,
    "state": {
        "cd151d618c364fccbe336abf1c6960f1": {
            "model_name": "LayoutModel",
            "model_module": "jupyter-js-widgets",
            "model_module_version": "3.0.0",
            "state": {}
        },
        "f44bf9592480492bbd74a5a5ea7599ee": {
            "model_name": "TextModel",
            "model_module": "jupyter-js-widgets",
            "model_module_version": "3.0.0",
            "state": {
                "value": "hello",
                "layout": "IPY_MODEL_cd151d618c364fccbe336abf1c6960f1"
            }
        }
    }
}
</script>
<body>
<script type="application/vnd.jupyter.widget-view+json">
{
    "version_major": "2",
    "model_id": "f44bf9592480492bbd74a5a5ea7599ee",
    "version_minor": "0"
}
</script>
</body>
</html>
```

**Comment by hainm** [comment]
ah yes, sorry for the noise.

**Comment by jasongrout** [comment]
@hainm - where are we on this?

**Comment by hainm** [comment]
it's likely `NGL` needs to work on its serialization.
buzz @arose so you can prioritize this.

Close now.
