### ISSUE TITLE
ToggleButtons / _Selection .value in Python side != .value on js side

### ISSUE THREAD

**Issue by maartenbreddels** [jupyter-widgets/ipywidgets#1091]
Say we have
```
toggle = ipywidgets.ToggleButtons(options=[("One", 1), ("Two", 2)])
```
Then clicking on 'One' will reflect that toggle.value == 1.
However, on the js side, value is actually "One", which messes things up if you use jslink.
The problem is I think in SelectView._updateOptions (https://github.com/ipython/ipywidgets/blob/master/jupyter-js-widgets/src/widget_selection.ts#L90)
Which uses _options_labels for both the label and the data.
My guess is that on the Python side, both _options_labels and _options_values in ipywidgets._Selection need sync=True as well.
I unfortunately cannot get the dev-install.sh to work, otherwise I might attempt a PR.

Snippet to reproduce the bug:
```
import ipywidgets
toggle = ipywidgets.ToggleButtons(options=[("One", 1), ("Two", 2)])
label = ipywidgets.Label()
ipywidgets.jslink((label, 'value'), (toggle, 'value'))
ipywidgets.VBox([toggle, label])
```

version info: Python3 / ipywidgets (6, 0, 0, 'beta9')

**Comment by jasongrout** [comment]
In order to have something we can sync across JSON, we encode the python .value attribute as its label. All communication happens back and forth with the label - the value never goes over the wire to javascript. Thus, the 'value' in Javascript is the label. That's the current design.

I agree it's confusing and not really ideal. What are you suggesting the value attribute should be on the javascript side?

**Comment by maartenbreddels** [comment]
But the Python's side value is 1, not 'One', so it it not consistent. If toggle.value == 1, I expect the js side to also have 1 as its value, not 'One'.

**Comment by jasongrout** [comment]
So here are several options:

1. we *don't* sync the python value over, we just sync the label, and deal with label on the JS side.
2. we make `.value` the label everywhere, and you just have to deal with the inconvenience of using a new `.value_object` or something in python, which is the actual object corresponding to the selected label.

**Comment by maartenbreddels** [comment]
Why not:
- sync over _options_labels and _options_values
- have a `.value` and `.label`

It does make sense from the point of view of embedding widgets using jslink. You want to have labels visible in the gui, and have them control values in other widgets, not deal with the labels.

**Comment by jasongrout** [comment]
Option 2 seems like a reasonable compromise. We could also open things up so that the labels could be any primitive JSON value (i.e., could be an int). That way it's still trivial to use `Select([1,2,3])` without having to do `.value_object`.

**Comment by jasongrout** [comment]
The crucial thing here is that we can't sync over the _options_values since they are arbitrary python objects - no guarantee that they are JSONable.

**Comment by maartenbreddels** [comment]
Ah ok, I didn't know that. I assumed they were. I mean, that would even be more useful right, you can have the values be widgets, and control for instance which widget .
And as it is now, _options_labels is also synced, so whatever issue there is with syncing _options_values, it will already exist.

**Comment by jasongrout** [comment]
> And as it is now, _options_labels is also synced, so whatever issue there is with syncing _options_values, it will already exist.

Not sure what you mean by this. The labels are strings, so they are able to be synced.

**Comment by maartenbreddels** [comment]
https://github.com/ipython/ipywidgets/blob/master/ipywidgets/widgets/widget_selection.py#L80 just a Tuple right?

**Comment by jasongrout** [comment]
Yes, but only because we can't say that it is a Tuple of strings (traitlets limitation). The docs clearly say: "The labels are the strings that will be
    displayed in the UI, representing the actual Python choices, and should be
    unique. If labels are not specified, they are generated from the values."

**Comment by maartenbreddels** [comment]
Ok, but do you see the potential benefit of having _options_values being for instance a list of widgets? Is there any limitation that would hamper implementing something like that. Even if that is not possible, having int's and string's is already really useful.

**Comment by SylvainCorlay** [comment]
> Yes, but only because we can't say that it is a Tuple of strings (traitlets limitation).

I think that we can force the trait of the contained element.

**Comment by jasongrout** [comment]
_options_values already can be anything, including a list of widgets.

For option 2 above, we could open up labels to be any value that can be converted to a primitive JSON value. Then you could directly use `.value` if the labels are actually a list of ints, which technically is the label, but would be the actual value in this case too.

**Comment by jasongrout** [comment]
>> Yes, but only because we can't say that it is a Tuple of strings (traitlets limitation).

> I think that we can force the trait of the contained element.

For variable-size tuples? Last I checked, giving types for tuple elements is done to make the tuple a fixed-sized typed record structure.

**Comment by SylvainCorlay** [comment]
> For variable-size tuples? Last I checked, giving types for tuple elements is done to make the tuple a fixed-sized typed record structure.

Yeah you are right. This is because semantically tuples are meant to be unpacked and list accessed. The only reason why we use tuples here is because of the immutability.

**Comment by jasongrout** [comment]
> Yeah you are right. This is because semantically tuples are meant to be unpacked and list accessed. The only reason why we use tuples here is because of the immutability.

Yep. We're abusing the Tuple type because Lists have even stronger limitations.

**Comment by SylvainCorlay** [comment]
I prefer to have a very strong typing of what gets through the network for the selection widgets. `strings` are all the js needs. 

This allows to have actual values that are not serializable, or just really big and there is no reason to send them through the wire. Besides, as new backends are being implemented, it is nice to be able to expect certain types :)

**Comment by maartenbreddels** [comment]
I understand, option 2 would be the simplest and more consistent method. However, I strongly believe that having a widget that that i describe (and kind of expect), would make things a lot more flexible. Having a toggle button that would allow setting what kind of pythreejs geometry to display for instance, with jslink, would be really nice.

**Comment by jasongrout** [comment]
Help me understand exactly what you're describing. You're describing a select widget where the values are serialized with the ipywidget model serializer, or are primitive JSON values? And then those values are synced with the javascript side?

**Comment by maartenbreddels** [comment]
Yes, I'd say use `ipywidgets.widgets.widget_serialization`, that would solve 95% of the use cases I'd think. I'll give you some examples.
I'm working on doing some 3d plotting in ipyvolume, and I'd like to have a gui for controlling some things, like marker sizes, type, color. I don't want those to be visible always, so a select widget that would display the proper control widgets for the plot could be implemented like this:
```
control_contains = VBox(...)
scatter1control = VBox(...)
scatter2control = VBox(...)
camera_control = VBox(...)
toggle = ToggleButtons(options=[('Camera', camera_control),('Scatter1', scatter1control), ('Scatter2', scatter2control), ....])
jslink((toggle, 'value'), (control_contains, 'children'))
```

And say in scatter1control, I could set the geometry of the markers
```
scatter = ....
sphere = pythreejs.SphereGeometry(...)
box = pythreejs.BoxGeometry(...)
marker_toggle = ToggleButtons(options=[('Sphere', sphere),('Box', box))
jslink((marker_toggle, 'value'), (scatter, 'marker_geometry'))

```

A futher remark about option 2, I don't think it's a good solution if you consider translations. You'd like to be able to change the labels, and keep your JS code the same, you don't wanna deal with labels, but the values. For instance.
```
food_toggle  = ToggleButtons(options=[('Fromage', 'cheese'),('Pain', 'bread'))
```

Hope this makes it clear what I expect from a user point of view, and I expect that it is technically possible. That using `ipywidgets.widgets.widget_serialization` doesn't cover all uses cases (say by having numpy arrays of dataframes as values can possible be solved later, having primitives and widgets as options would already be a *huge* gain.

**Comment by jasongrout** [comment]
Thanks for the clarification. If we are always syncing values, that means that values are primitives or widgets with the above plan. However, that means that we can no longer use selection widgets for arbitrary python objects, which would be a huge regression in functionality. Thoughts?

**Comment by maartenbreddels** [comment]
Ok, I would have to be an opt-in thing then. Sth along this line?
```
ToggleButtons(... sync_values=True, serialize_values=ipywidgets.widgets.widget_serialization)
```
Would that be technically possible?
I'd say, selection widgets would have a `.value`, which would be (by default) python side only, a `.label` which would always be a string and would have sync=True. This would break existing code that would use jslink on `.value`, but it would be more consistent.
Serializing values would have to be explicit then, there would possibly be a limitation, in that the js side would go no further than deserializing the equivalent of widget_serialization, since you cannot change that at runtime I'd assume.
I understand it's not gonna be a perfect solution, but I hope you understand how powerful even this limited funtionality would be.

**Comment by jasongrout** [comment]
I think once we start changing the fields that are serialized, or the serializer being used, we're talking a different widget. We want to think about the widget as being defined by the sync protocol messages so multiple frontends and backends can implement the widgets by just implementing the right sync messages.

I think your proposal of having a `.label` attribute that is synced, and a `.value` attribute that is python-only, might work well. @SylvainCorlay, what do you think of that? It breaks assumptions on the javascript side of having a `.value`, but I don't think that is used much.

**Comment by maartenbreddels** [comment]
Maybe there is a way around what I want. The problem is that I consider `.label` meaningless in the js code (see my translation example). But having a new  `.index` (from 0 to len(options)-1), would really help. Having this, I can see a new jslink-like helper method:
```
jslink_list((marker_toggle, 'index'), (scatter, 'marker_geometry'), [sphere, box, ...])
```
This would listen to the marker_toggle.index on the JS side, and on change take that item from the last list argument, and assign it to scatter.marker_geometry

I can try to implement sth like that, but having a `.index` gives option!

**Comment by jasongrout** [comment]
Yes, index is how we implemented a similar thing in Sage as well. That crossed my mind as well, but that means things are a bit ambiguous if the options are specified as a dictionary. But since the options are normalized anyway, maybe it's not so bad.

**Comment by maartenbreddels** [comment]
Yeah, if you use a dict you probably don't care about the order, or you are using Python 3.6

So to summarize, would this be the proper solution:

- `.value` should disappear on the js side (since it is not consistent with the py side)
  - it should be replace by `.label` on the js side
- `.value` on the Python side stays the same (we cannot sync it since it should be able to hold any py object)
- `.index` will be a synced property/trait. (this could (by 3rd party code) enable selecting widgets, geometries etc..)

**Comment by jasongrout** [comment]
One other thing nice about using index instead of label is that you could then have two identical labels, if you wanted.

Another thing is that it will simplify the code, since we have to do some logic to convert things to an index anyway.

Do you think .label should be synced as well? If you want to use the triggering mechanism based on label on the js side, we'll need to put it in the model and sync it.

**Comment by jasongrout** [comment]
This does break with other value traits, where value is synced. I don't think there will be drastic consequences, but it will be confusing.

**Comment by maartenbreddels** [comment]
Yes, it was confusing to me, since `.value` is quite common, so maybe `.value` needs a new name, `.object`? But I'd say sync the labels, you can imaging putting the label text somewhere in the gui.

**Comment by jasongrout** [comment]
Should we also make the toggle buttons, radio buttons, and other selection widgets have the same behavior? A .value attribute that is python-only, and an index and label attribute that are synced? It would be nice if all of the selection widgets were consistent.

**Comment by jasongrout** [comment]
Oh, that was a dumb question, since the way the code is structured, that would automatically be true.

**Comment by maartenbreddels** [comment]
glad I could be of help :wink:

**Comment by jasongrout** [comment]
@SylvainCorlay and I talked about this, and we realized it wasn't going to substantially change the API for the end-user, so we're going to bump this to 6.1.

**Comment by maartenbreddels** [comment]
Ok, whatever gets 6.0 out sooner i'm on favor of. But maybe just changing .value on the js side to .label would mean you introduce a breaking change in a major version change which is ok, otherwise in a minor one, which would break semver rules I think.

**Comment by SylvainCorlay** [comment]
I am also in favor of pushing 6.0 out as soon as possible.

**Comment by jasongrout** [comment]
@maartenbreddels - time to get back to this. I think we settled on this from the above comments?

- `.value` should disappear on the js side (since it is not consistent with the py side)
  - it should be replace by `.label` on the js side
- `.value` on the Python side stays the same (we cannot sync it since it should be able to hold any py object)
- `.index` will be a synced property/trait. (this could (by 3rd party code) enable selecting widgets, geometries etc..)

**Comment by SylvainCorlay** [comment]
Sounds good

**Comment by maartenbreddels** [comment]
:+1:
