### ISSUE TITLE
Saved widgets (with 'Save Notebook with Widget') do not seem to be removable from ipynb file

### ISSUE THREAD

**Issue by cornhundred** [jupyter-widgets/ipywidgets#1104]
I do not seem to be able to delete widgets from the ipynb JSON file (under metadata, widgets). Removing widgets from the interactive notebook and resaving does not seem to clear out old widgets.

**Comment by jasongrout** [comment]
Thanks. We're changing how widgets are stored in the upcoming release, which should solve this. @SylvainCorlay - will the current changes in master also remove widget data if it already exists in the notebook metadata?

**Comment by SylvainCorlay** [comment]
@jasongrout I think that @cornhundred's report concerns the current beta.

**Comment by cornhundred** [comment]
Thanks, yes I have 6.0.0.beta6 installed. Should I be using a different version of 6.0?

**Comment by SylvainCorlay** [comment]
No, that is fine. We probably need to discuss the semantic if removing the widgets of the notebook.

Saving from a fresh kernel should remove them.

**Comment by cornhundred** [comment]
Thanks, restarting the kernel and resaving worked.
