### ISSUE TITLE
date picker may empty the value using keyboard navigation

### ISSUE THREAD

**Issue by akhmerov** [jupyter-widgets/ipywidgets#1115]
Steps to reproduce:

* open a date picker widget or use one from the [docs](http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#Date-picker)
* set the date to 01/31/2017
* Increment the month by 1 using keyboard (arrow up)

Expected behavior: the date changes  to 02/31/2017 and the widget border becomes red because the value is invalid or the day gets reset or the day becomes 28.

Observed behavior: the date changes to mm/dd/yyyy (blank).

**Comment by jasongrout** [comment]
Looks like we need to trap the case where `.valueAsDate` returns null for an invalid date here: https://github.com/jupyter-widgets/ipywidgets/blob/d2588f19001d26e97b9dfee89eb9371dc155ec2c/jupyter-js-widgets/src/widget_date.ts#L128

**Comment by jasongrout** [comment]
This may be related to #1320 or #1322 - CC @pbugnion.

**Comment by pbugnion** [comment]
Thanks for the heads up -- Unless soemone gets there first, I can look into this when I'm done with the current PR.
