### ISSUE TITLE
Big Split(tm) Figure out the development workflow after the split

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter-widgets/ipywidgets#1151]
Iterating on a development version of `jupyter-js-widgets`, `ipywidgets` and `widgetsnbextension` will probably be quite different.

I propose that the recommended development workflow will be to clone the different repos in the same location and we update the `update` scripts accordingly.

**Comment by jasongrout** [comment]
After talking with @SylvainCorlay, I plan to also split up jupyter-js-widgets into 3 packages: 

1. the base widget manager and base widget classes (i.e., Widget, DOMWidget, LabeledDOMWidget)
2. the core widget classes (basically everything subclassing CoreWidget
3. the embedded widget manager

**Comment by jasongrout** [comment]
Our thought is that the public api of the core widget classes will be the widget schema they implement, *not* the actual exported classes. Thus a change in a class interface will *not* be a breaking change, but a change in the schema they implement *will* be a breaking change. The thought is that there will be many more people implementing kernel-side implementations of the widgets (i.e., needing schema version compatibility), and not very many people extending the actual classes themselves (needing class interface compatibility), and that it would be too confusing to have two separate version numbers to keep track of (the schema compatibility and the javascript class interface compatibility).

**Comment by jasongrout** [comment]
One way of emphasizing this is to make a specific module entry point for the classes the module provides, and *not* export the classes in the module namespace. Then we could more easily say that the classes themselves are not part of the public api. There is questions about the extra friction that imposes, but it does make it nice to have a single entry point to get the widgets a package exposes for registration purposes, etc.

**Comment by jasongrout** [comment]
Here's a tentative outline for the split of `jupyter-js-widgets`:

* `@jupyter-widgets/base` - Base widgets, such as Widget, DOMWidget, LabeledDOMWidget, LayoutWidget. These are meant to be subclassed. This would also include the widget serializer, which is of general use.
  - `nativeview.ts`
  - `widget.ts`
  - `widget_layout.ts`
  - `utils.ts`
  - nominally, the output widget (i.e., the module for the output widget will be this namespace, and widget managers are responsible for providing it and special-casing it.)
* `@jupyter-widgets/manager` - the base widget manager that can be subclassed, depends on `@jupyter-widgets/base`
  - `manager-base.ts`
  - `services-shim.ts`
* `@jupyter-widgets/core` - Core jupyter widgets, such as sliders, boxes, etc. Basically, anything that now inherits from the core widget. The version number of this package tracks compatibility with the wire format, *not* the class implementations. Depends on `@jupyter-widgets/base`.
  - `phosphor/` directory of custom phosphor widgets
  - `widget_bool.ts`
  - `widget_box.ts`
  - `widget_button.ts`
  - `widget_color.ts`
  - `widget_controller.ts`
  - `widget_core.ts`
  - `widget_date.ts`
  - `widget_float.ts`
  - `widget_image.ts`
  - `widget_int.ts`
  - `widget_link.ts`
  - `widget_selection.ts`
  - `widget_selectioncontainer.ts`
  - `widget_string.ts`
  - `widget_style.ts`
* `@jupyter-widgets/embed-manager` - the embedded widget manager, depends on `@jupyter-widgets/manager`
  - `src-embed` directory
* `@jupyter-widgets/schema` - renamed from `jupyter-widgets-schema`
* `@jupyter-widgets/jupyterlab` - renamed `@jupyterlab/nbwidgets`


We keep the `jupyter-js-widgets` package, which imports from the other packages to provide compatibility. This package is deprecated.

The widgetsnbextension node package is a private package, not published.

**Comment by jasongrout** [comment]
The splits are pretty much done, we've now migrated to lerna to manage building, and we are finishing renaming packages over in #1447. I think this can be closed.
