### ISSUE TITLE
select SVG dropdown arrow always black

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#1159]
It would be great if we could customize the color of the dropdown arrow (https://github.com/ipython/ipywidgets/blob/master/jupyter-js-widgets/css/widgets-base.css#L635) for different themes. Having it always black can look bad when the select background is a different color.

I'm putting this as 6.0, but could be bumped to 6.1 if the fix isn't easy.

**Comment by SylvainCorlay** [comment]
I think that we can close this since it can be set in css.

**Comment by jasongrout** [comment]
We should make it a css variable then, so it is exposed as part of the styling interface. I'm reopening this to keep track of doing it.
