### ISSUE TITLE
When frontend version does not match backend print both version?

### ISSUE THREAD

**Issue by Carreau** [jupyter-widgets/ipywidgets#1177]
Just helped SO debugging an ipywidget issue (6.0 in the backend, 5.x in frontend I guess) Which was easy because of the "not matching" console message. 

it would be good to have this message print both version if that's possible. That would help to debug/downgrade to right version if needed.

**Comment by jasongrout** [comment]
That sounds like a really good idea. I thought we did it already, so +1.

**Comment by Carreau** [comment]
Maybe you do, I was just holding 3 bugs reports in my head and had to write
it down before forgetting.

**Comment by jasongrout** [comment]
Thanks for reporting it!

**Comment by jasongrout** [comment]
We took out the version checking between front and backends, so this is now a moot point.
