### ISSUE TITLE
ipywidgets compatibility with IPython.display.update_display?

### ISSUE THREAD

**Issue by gnestor** [jupyter-widgets/ipywidgets#1180]
I created an example notebook to demonstrate `update_display` for `IPython.display.HTML` and `ipywidgets.widgets.IntProgress` and the progress bar doesn't update.

https://gist.github.com/gnestor/867a1bd14125fbeba30dadf9c19c68a9

**Comment by jasongrout** [comment]
Has the ipython with the `update_display` command been released yet? Is it in 5.3.0? I'm having troubles importing it.

**Comment by gnestor** [comment]
No, I think it will be released with 6.0. Here is the PR: https://github.com/ipython/ipython/pull/10048

**Comment by deisi** [comment]
Ah I found https://github.com/jupyter-widgets/ipywidgets/issues/1764
I think that's what I need. Thx.

**Comment by saulshanabrook** [comment]
Here is a minimal example to show this behavior:

```python
import ipywidgets
import IPython.display

inn = ipywidgets.IntSlider()
out = ipywidgets.Output()

def create_and_update_display():
        d = IPython.display.display(IPython.display.Code("hi"), display_id=True)
        d.update(IPython.display.Code("there"))

def update_output(value):
    out.clear_output()
    with out:
         create_and_update_display()

    return out.outputs

ipywidgets.dlink((inn, 'value'), (out, 'outputs'), update_output)
ipywidgets.VBox([inn, out])
```

I would expect it to display `there` but it displays `hi`.

This support is needed when you want to wrap some output that is updated asynchronously in a widget.

**Comment by gnestor** [comment]
Here's a minimal example using `interact` that works and doesn't depend on `update_display`:

```py
import altair as alt
import ipywidgets as widgets

cars = alt.load_dataset('cars')

def render_chart(x, y):
    return alt.Chart(cars).mark_point().encode(
        x=x,
        y=y,
        color='Origin',
    )

widgets.interact(render_chart, x=list(cars), y=list(cars));
```

![](http://g.recordit.co/j3XWEBaKGd.gif)

**Comment by martinRenou** [comment]
Has this been fixed @vidartf ?
