### ISSUE TITLE
Interact in 6.0.0 does not clear the output before rendering a new pandas plot

### ISSUE THREAD

**Issue by carlchristophe** [jupyter-widgets/ipywidgets#1181]
I'm using @interact with pandas to plot and when I change a value another chart is added below the previous one. Reverting to 5.2.2 fixes the issue.

I'm running Jupyter 4.3.0 and ipython 5.3.0.

**Comment by jasongrout** [comment]
This works for me. Does it work for you?

```python
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from ipywidgets import interact

@interact(n=(1000,2000))
def f(n):
    ts = pd.Series(np.random.randn(n), index=pd.date_range('1/1/2000', periods=n))
    ts = ts.cumsum()
    ts.plot()
    plt.show()
```

Are you using `%matplotlib inline`? That doesn't work with interact anymore, due to the way it draws the plots.

**Comment by jasongrout** [comment]
Looking into it more led to opening this issue: https://github.com/ipython/ipython/issues/10376.

Basically, if you're using the `%matplotlib inline` backend, you can either not use it and call the `plt.show()` method explicitly, or you can import the `flush_figures` method and do something like:

```python
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from ipywidgets import interact
from ipykernel.pylab.backend_inline import flush_figures

%matplotlib inline

@interact(n=(1000,2000))
def f(n):
    ts = pd.Series(np.random.randn(n), index=pd.date_range('1/1/2000', periods=n))
    ts = ts.cumsum()
    ts.plot()
    flush_figures()
```

We're working on seeing if there is a better way...

**Comment by carlchristophe** [comment]
Thanks, yes that works! Sorry for not sharing more details earlier. I've been using `%matplotlib inline` out of habit to display plots inline, but is there a better option perhaps?

**Comment by jasongrout** [comment]
Actually, it seems that it's way simpler than I posted above. You *can* use `%matplotlib inline`, you just need to explicitly show the figure inside the function. You don't need to use the flush_figures method:

```python
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from ipywidgets import interact

%matplotlib inline

@interact(n=(1000,2000))
def f(n):
    ts = pd.Series(np.random.randn(n), index=pd.date_range('1/1/2000', periods=n))
    ts = ts.cumsum()
    ts.plot()
    plt.show()
```

**Comment by jasongrout** [comment]
Closing as resolved, but I'm happy to carry on the conversation if you have any other questions.

**Comment by jasongrout** [comment]
In ipython/ipython#10376 and #1457, we thought it might be worth it to do the `flush_figure` workaround in interact from ipython/ipython#10376.  I'm reopening this issue to track us implementing the workaround.
