### ISSUE TITLE
Document that DatePicker doesn't work in Safari

### ISSUE THREAD

**Issue by jpangburn** [jupyter-widgets/ipywidgets#1182]
# Summary

Datepicker doesn't work in Safari - we should document that it only works in supported browsers. See http://caniuse.com/#feat=input-datetime

---
# Original issue

I have a Jupyter notebook that I'm testing widgets in and found that the new DatePicker widget doesn't work in Safari, but works fine in Chrome.  Here's the offending code:

```
from IPython.display import display
import ipywidgets as widgets
datepicker = widgets.DatePicker(description="test desc")
display(datepicker)
```

Here's a screenshot of the console in Safari's Web Inspector:
![screen shot 2017-03-04 at 10 06 00 am](https://cloud.githubusercontent.com/assets/4357286/23581900/4ab0bd8c-00c2-11e7-98ea-67e473e44e88.png)

The line 26609 is found here (it's the line with "this._datepicker.valueAsDate" in it) in extension.js:

```
DatePickerView.prototype._update_value = function () {
    var value = this.model.get('value');
    this._datepicker.valueAsDate = createDateAsUTC(value);
};
```

The utils.js line 139 that writes the console error is here (it's the console.error line) in utils.js:

```
function reject(message, log) {
    return function promiseRejection(error) {
        var wrapped_error = new WrappedError(message, error);
        if (log)
            console.error(wrapped_error);
        return Promise.reject(wrapped_error);
    };
}
```

I'm using Python 3.5, with IPython 5.3.0, ipywidgets 6.0.0, and notebook 4.4.1:

> $ python3 -c "import IPython; print(IPython.sys_info())"
> {'commit_hash': '5a894b9',
>  'commit_source': 'installation',
>  'default_encoding': 'UTF-8',
>  'ipython_path': '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/IPython',
>  'ipython_version': '5.3.0',
>  'os_name': 'posix',
>  'platform': 'Darwin-16.4.0-x86_64-i386-64bit',
>  'sys_executable': '/Library/Frameworks/Python.framework/Versions/3.5/bin/python3',
>  'sys_platform': 'darwin',
>  'sys_version': '3.5.0 (v3.5.0:374f501f4567, Sep 12 2015, 11:00:19) \n'
>                 '[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]'}
> $ pip3 show ipywidgets
> Name: ipywidgets
> Version: 6.0.0
> Summary: IPython HTML widgets for Jupyter
> Home-page: http://ipython.org
> Author: IPython Development Team
> Author-email: ipython-dev@scipy.org
> License: BSD
> Location: /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages
> Requires: ipython, ipykernel, widgetsnbextension, traitlets, nbformat
> $ pip3 show notebook
> Name: notebook
> Version: 4.4.1
> Summary: A web-based notebook environment for interactive computing
> Home-page: http://jupyter.org
> Author: Jupyter Development Team
> Author-email: jupyter@googlegroups.com
> License: BSD
> Location: /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages
> Requires: jinja2, nbconvert, nbformat, jupyter-core, jupyter-client, traitlets, ipython-genutils, terminado, tornado, ipykernel

**Comment by jasongrout** [comment]
It looks like Safari doesn't support the html date picker: http://caniuse.com/#feat=input-datetime

It seems like you'll need to use Chrome for that widget to work. It will be great when other browsers support it too!

**Comment by jasongrout** [comment]
(Leaving this open so that we can document that some browsers may not support the datepicker widget)
