### ISSUE TITLE
Scale size of the `ToggleButtons` to the text they contain

### ISSUE THREAD

**Issue by RemiLehe** [jupyter-widgets/ipywidgets#1189]
With the new `ipywidgets 6.0`, the size of the `ToggleButtons` does not scale anymore with the size of the text that they contain. Consider for example the case below:
<img width="910" alt="screen shot 2017-03-07 at 8 10 32 am" src="https://cloud.githubusercontent.com/assets/6685781/23665544/9dbac52a-030d-11e7-9266-484abb206ef3.png">
Ideally, it would be nice to have the option for the button for "Super Super Super Super Slow" to automatically increase its width (I think this was the default with `ipywidgets 5`). Would it be possible to implement this?

**Comment by jasongrout** [comment]
Can you try this?

```python
import ipywidgets
ipywidgets.ToggleButton(description='this is a long description', layout={'width': ''})
```

**Comment by jasongrout** [comment]
No, that's just for a single toggle button - trying again...

**Comment by jasongrout** [comment]
How about we introduce a style attribute for the toggle buttons that essentially behaves like setting the `.layout.width` attribute of a single button? Something like:

```
t = ToggleButtons(options=['An extremely long option', 'option'])
t.style.button_width=''
```

CC @SylvainCorlay

**Comment by RemiLehe** [comment]
Thanks for those suggestions! As far as I am concerned, the option with `.style.button_width` sounds great.

**Comment by jasongrout** [comment]
Right. Above, I suggested that the button_width attribute should be added (no one has written the code for it yet, though). Would you like to submit a pull request for it? We can walk you through the process.

**Comment by kingbase** [comment]
Hi, sorry for the misunderstanding.

This was cool but I don't know much CSS/HTML, so sorry.

**Comment by jasongrout** [comment]
The changes are a mixture of python and javascript. I've marked this issue as 6.1, to be resolved in the next release.

**Comment by jasongrout** [comment]
(the changes would basically follow the pattern in https://github.com/jupyter-widgets/ipywidgets/pull/1163, where we added a `.style` attribute for progress bars)

**Comment by jasongrout** [comment]
I'm working on this. turns out we need some changes to how styles work since the toggle buttons reconstructs all of its buttons every time there is a change.
