### ISSUE TITLE
Ordering of elements in 'Select*', 'ToggleButtons' and 'RadioButtons' is inconsistent when updating 'options' on 5.x

### ISSUE THREAD

**Issue by jbweston** [jupyter-widgets/ipywidgets#1191]
On the 5.x branch, when updating the `options` of any of the above-mentioned widgets the option ordering in the DOM is inconsistent with the option ordering in the model. I would expect that if
`widget.options = ['d', 'a', 'c']` in the notebook, then the options presented in the DOM should be displayed in the same order.

This also gives rise to a weird effect in the `Select*` widgets where selecting option `a` causes option `c` to be selected.

See this gist [over here](https://gist.github.com/jbweston/c9d751d6a109ef2613da5db955be668e) to see what I mean

This bug is not present on `master`.

**Comment by pbugnion** [comment]
Since this is fixed on master, I'm going to close this. Thank you!
