### ISSUE TITLE
Inconsistent size of `FloatText` on Firefox and Chrome

### ISSUE THREAD

**Issue by RemiLehe** [jupyter-widgets/ipywidgets#1193]
Hi,
It seems that Firefox and Chrome interpret the `width` of a `FloatText` differently, in the case where a description is provided:
- here is the rendering with Firefox:
<img width="392" alt="screen shot 2017-03-07 at 9 19 19 pm" src="https://cloud.githubusercontent.com/assets/6685781/23691223/0783a44a-037c-11e7-877c-42b32d629a67.png">
- here is the rendering with Chrome:
<img width="401" alt="screen shot 2017-03-07 at 9 22 09 pm" src="https://cloud.githubusercontent.com/assets/6685781/23691252/32a0a682-037c-11e7-939d-6e959a25f6f7.png">

Is this a problem at the `ipywidgets` level, or is it a more general issue with widgets and web browsers?

Note: this issue only comes up with `ipywidgets<6`.

**Comment by ax3l** [comment]
Are we already ipywidgets 6 compatible? If yes we can just update to fix :D

**Comment by pbugnion** [comment]
Thanks for raising this.

As you noted, and as far as I can tell, this is fixed on master. I'll close this, but feel free to re-open if you think I'm missing something.
