### ISSUE TITLE
Data send multiple times to backend

### ISSUE THREAD

**Issue by maartenbreddels** [jupyter-widgets/ipywidgets#1195]
While working on #1194, I noticed what I think is a bug. Take the following code:
```python
import ipywidgets
s = ipywidgets.IntSlider(description="hello", min=0, max=2, value=0)
v = ipywidgets.IntText(value=1)
ipywidgets.jslink((v, 'value'), (s, 'value'))
ipywidgets.HBox([s,v])
```
Now in a next cell, you execute:
```python
s.description = "world"
```
All is fine, the js logic with `state_lock` will avoid that this gets send to the python backend again, however, in the js side, `s.model.change` still recorded that `description` was changed. If you now enter a digit in the IntText, it will trigger a save_changes in the IntSlider, and it will again send {description: 'world', ..} to the backend. This happens in many other cases. For instance, in my case, this is an array with a ~million entries, not something you'd like to send around multiple times.
I am not sure how to resolve this, although happy to try.

PS: Is there any way to get a reference to a widgets in the js console, in ipyvolume is just set window.last_scatter = this; for debugging, but maybe there is a general way.

**Comment by maartenbreddels** [comment]
Looking at the source (also of backbone), I suggest changing `WidgetModel.set_state`, it should remove all key/values from self.changed (*after* this.set(..)) is called, for which the value didn't change by a change listener that was called by `this.set`. This follows the same logic as in `WidgetModel.sync`. For instance state was before {'x': 1, 'y':2}, and say that when x is changed, in the 'change-listener' y is set to 3, 'x' should be removed from this.changes. This may feel uncomfortable poking around in backbonejs' internals, but I don't think backbone can handle this case.

**Comment by maartenbreddels** [comment]
Actually, changed will be reset on the next `.set`, it appears that `_buffered_state_diff` is the quilty one.

**Comment by maartenbreddels** [comment]
@jasongrout I've demonstated the bug [here](https://gist.github.com/maartenbreddels/270420a88ba7653ef0b432768657b9d8)
For some reason, 'y' enters in `last_doubler._buffered_state_diff`, since you're working on this now, you may see where it goes wrong. Also included a screenshot.
![screen shot 2017-04-12 at 21 17 52](https://cloud.githubusercontent.com/assets/1765949/24975357/9c4019f0-1fc5-11e7-8652-9b7ac1258798.png)

**Comment by jasongrout** [comment]
In your doubler example, you'll want to use `this.save_changes()`, not `this.save()`. The `save_changes` function automatically syncs the attributes that have changed since the last tie we synced.

**Comment by maartenbreddels** [comment]
👍  confirmed that works.
