### ISSUE TITLE
ipywidgets 6, unable to edit numeric values in FloatRangeSlider()

### ISSUE THREAD

**Issue by madridnick** [jupyter-widgets/ipywidgets#1217]
It appears that editing the numeric values broke with the latest release. Value are not persisted.

```python
import ipywidgets as widgets

widgets.FloatRangeSlider(
    value=[5, 7.5],
    min=0,
    max=10.0,
    step=0.1,
    description='Test:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='i',
    slider_color='white',
    color='black'
)
```

<img width="410" alt="bf" src="https://cloud.githubusercontent.com/assets/6982390/24119639/2e66de36-0d6f-11e7-83e3-f54f401328f3.PNG">

**Comment by jasongrout** [comment]
(to clarify, editing a value in the readout apparently used to change the range slider, but doesn't anymore)
