### ISSUE TITLE
pip install ipywidgets fails

### ISSUE THREAD

**Issue by isaphan** [jupyter-widgets/ipywidgets#1224]
$ pip install ipywidgets
Downloading/unpacking ipywidgets
  Running setup.py egg_info for package ipywidgets
    error in ipywidgets setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    Complete output from command python setup.py egg_info:
    error in ipywidgets setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

Python 2.7.10 virtualenv on OS X 10.11.6

**Comment by jasongrout** [comment]
Googling indicates that you may need to update your setuptools. Can you try `pip install --upgrade setuptools`, and then try installing again?

**Comment by jasongrout** [comment]
Closing as resolved. Please feel free to re-open if the above didn't help.

**Comment by isaphan** [comment]
Sorry Jason, I did not receive the comment you posted 16 days ago and installed jupyter via Anaconda instead. I’m pretty sure you are right with the setuptools.

On Apr 6, 2017, at 9:23 PM, Jason Grout <notifications@github.com<mailto:notifications@github.com>> wrote:


Closing as resolved. Please feel free to re-open if the above didn't help.

**Comment by shimul03** [comment]
pip install ipywidgets fail
Error: fatal error C1083: Cannot open include file: 'winpty.h': No such file or directory

**Comment by jasongrout** [comment]
That error should have nothing to do with ipywidgets. Perhaps it's the notebook failing to install?
