### ISSUE TITLE
Can widget rendering be delayed until a render method is called?

### ISSUE THREAD

**Issue by cornhundred** [jupyter-widgets/ipywidgets#1233]
Is it possible to delay widget rendering until I call a render method on the widget? I would like to use the widget to load data, perform calculations, and finally render the widget (I plan on having the widget inherit from widgets.DOMWidgets and my own class that performs calculations etc). I made a mock-up using the HelloWorld widget of what I would like:  [Render method notebook](http://nbviewer.jupyter.org/github/MaayanLab/widget_hello_world/blob/master/Hello%20World%20render%20method.ipynb)

**Comment by jasongrout** [comment]
Is your loading and calculation in the kernel? Perhaps you should have a class which is *not* a widget, and then have the render() method return a widget that can be displayed?

Alternatively, you could have a widget which initially has an empty model. When it is instantiated, it does the loading and calculations and fills in the appropriate data passed to the frontend. If the widget is displayed before the data is ready, it shows a spinner or progress bar or something. If the data is there, the widget displays it.

**Comment by cornhundred** [comment]
Thanks @jasongrout, yes the loading and calculations are being run on the kernel. I will look into your suggestions and I have something similar to what you discussed.

Currently, I have something that is almost working, but led to another issue (#1234) rendering on nbviewer. 

My current method for making a widget is: 
```
# instantiate class for loading, calc, etc.
net = Network()

# load dataframe and cluster
net.load_df(df)
net.make_clust()

# make widget by passing JSON from net to clustergrammer_widget
clustergrammer_widget(network=net.widget())
```

My attempt to simplify the API was to have the widget, `clustergrammer_widget`, inherit from `Network` so that I could load, perform calculations, and render from the same object:
```
cgm = clustergrammer_widget()

# load dataframe and cluster (new cluster method passes JSON to cgm.network)
cgm.load_df(df)
cgm.cluster()

# render widget (works, but would like a to render with cgm.render() to be more explicit)
cgm
```

This worked locally, but the widgets made using the new method did not show on nbviewer, which led to the new issue (#1234).

**Comment by cornhundred** [comment]
Update: the above nbviewer issue was being caused by my class, which the widget inherited from.

**Comment by cornhundred** [comment]
I'm going to use your first suggestion @jasongrout, which effectively delays rendering - I'm passing the widget class to my own class, which does the calculations and instantiates a widget when necessary. Thanks for the help.
