### ISSUE TITLE
Versioning of models/views

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#1235]
#1228 is leading to changes in how we deal with model and view version numbers. Here is a proposal:

* Each model has at least 6 attributes:
  * `_model_module`, `_model_module_version`, and `_model_name` describe a model specification, i.e., a documented list of attributes of the model state. The version number is a semver version string. Typically the version number will only have major version bumps (i.e., any change to a model specification is considered a breaking change). The `_model_module` is *not* necessarily tied to a specific package name. For example, the core Jupyter widgets would have a `_model_module` of `JupyterWidgets`. This allows a package to evolve independent of the actual attribute specification.
  * `_view_module`, `_view_module_version`, `_view_name` describe a view that understands the model specification and version. The view module is also not necessarily a package name (for example, core Jupyter widgets have a `_view_module` of `JupyterWidgets`.
* The view implementation used will automatically check to make sure that it understands the model specification at runtime. Thus the `_view_module_version` will normally default to `'*'` (i.e., load a version of the view that implements the model specification). If the view loaded does not support the model specification, an error is logged and a basic view is displayed with an error message.

In practice, third party widgets likely will have their `_model_module` attributes actually be a package name - especially if they don't have many different things implementing them. We could also keep `_model_module` to mean a package name, and make a new `jupyter-widgets` package that contains the specification for the models.

**Comment by jasongrout** [comment]
@SylvainCorlay - comments?

**Comment by SylvainCorlay** [comment]
I will comment on this tomorrow (11:30pm here) :)

**Comment by jasongrout** [comment]
I went through lots of iterations - this version ended up looking a lot closer to what we have than I thought it would.

Perhaps `_model_module` should be `_model_spec` or something, to clarify that it isn't necessarily a package or module?

**Comment by jasongrout** [comment]
Also, I thought making the model version number an integer - essentially on the major portion of a semver version.

**Comment by jasongrout** [comment]
Along with this refining of how we handle version numbers, we could more cleanly separate models and views again. For example, we could have the selection widgets have a `_model_name` be the `SelectionModel`, with just the view changing for the different widgets. This would map very nicely onto the javascript side, where the model and the views are instantiated separately. For the python side, we'd have to look up the appropriate class based on both the model name and the view name in the widget state.

Alternatively, now that we have the concept of subwidgets several places like LayoutWidget and StyleWidget which interact with the main widget, we could finally separate out the concept of models and views on the python side. We could have the main widget represent the model, with a subwidget representing the view. For example, you instantiate a SelectionWidget with a `.view` attribute that is a `ToggleButtonsView` view, or a `DropDownView`. (This could be too confusing, though.)

**Comment by jasongrout** [comment]
> For example, you instantiate a SelectionWidget with a .view attribute that is a ToggleButtonsView view, or a DropDownView.

With this approach, we separate state-based events from view-based events. For example, a button click is a view-based event (i.e., a single view sends a custom message). The view-based events do stuff to the view object, not the state-based widget model object. For example, the click can be triggered on the `ToggleButtonsView` object. Again, this may be too confusing - one of our core propositions is that we are simplifying things for the user by conflating the model and view on the python side.

**Comment by jasongrout** [comment]
Closing in favor of discussion on #1242.
