### ISSUE TITLE
Select Widget no longer a list box appearance as of 6.0

### ISSUE THREAD

**Issue by rskabelund** [jupyter-widgets/ipywidgets#1236]
```
lb = widgets.Select(height='200px', options=['apple','bananna', 'watermelon','peach','orange','grape','lemon','lime','strawberry','kiwi'])
display(lb)
```
used to look like a list box, now it just looks like a dropdown widget.

5.2.2
![image](https://cloud.githubusercontent.com/assets/18313265/24429971/4aa44aba-13c9-11e7-980e-6f38f83a65cd.png)

6.0.0
![image](https://cloud.githubusercontent.com/assets/18313265/24429987/5951353c-13c9-11e7-840b-51ca7e30ae3c.png)

**Comment by rskabelund** [comment]
Possible related issue: SelectMultiple used to obey the height parameter and it no longer does that...

**Comment by jasongrout** [comment]
Confirmed. I'll work on a fix tomorrow, if I can.

**Comment by jasongrout** [comment]
As for the height parameter, all layout information like that is now encapsulated in the `layout` property: `SelectMultiple(..., layout=Layout(height='100px'))`.

**Comment by rskabelund** [comment]
yeah, the Layout height doesn't work for either Select or SelectMultiple.  It did seem to make the widget div larger though...
![image](https://cloud.githubusercontent.com/assets/18313265/24436739/19379efe-13f2-11e7-80ee-c5d04647d8d3.png)

**Comment by jasongrout** [comment]
> yeah, the Layout height doesn't work for either Select or SelectMultiple. It did seem to make the widget div larger though...

I opened #1240 for this issue.
