### ISSUE TITLE
build static-export from Python

### ISSUE THREAD

**Issue by minrk** [jupyter-widgets/ipywidgets#1241]
It would be very useful if an offline Python script could produce a working static-widget export. That is, be able to get the result of Widgets > Embed Widgets from ipywidgets directly, run outside IPython / Jupyter.

This would allow standalone scripts to generate pages with bqplot or ipyvolume figures, for example.

How much work would this be? The model information should all be available, right? Is there anything more?

**Comment by SylvainCorlay** [comment]
Actually, the jupyter-sphinx extension does precisely that in a pure python way.

`get_manager_state` returns the serialized state that is computed from the python side and follows the same schema as what is generated in the front-end.

https://github.com/jupyter-widgets/jupyter-sphinx/blob/master/jupyter_sphinx/embed_widgets.py#L218

**Comment by minrk** [comment]
@SylvainCorlay perfect! Perhaps something like that should be included in ipywidgets itself? I think it would be great to have a simple `embed_widget_snippet()` that emits the whole shebang:

```html
<script type=...widget-state.json</script>
...state
</script>
<script src="npmcdn/jupyter-js-widgets..."></script>
...
```

so that it can be easily integrated into other environments. This is coming up right now where folks are interested in using widget-based plotting (e.g. ipyvolume), but don't want to make a choice that ties them to notebooks. If I can demonstrate a simple way to produce HTML files containing widget-based plots from a plain Python script, that would go a long way.

cc @vidartf



Can packages identify how to load their own js from npmcdn? Or does that already work, too? I see the ipyvolume docs load ipyvolume widget code, but I don't know how that actually works. Looks like magic!

**Comment by SylvainCorlay** [comment]
> @SylvainCorlay perfect! Perhaps something like that should be included in ipywidgets itself? I think it would be great to have a simple embed_widget_snippet() that emits the whole shebang:
>
> [...]
> 
> so that it can be easily integrated into other environments. This is coming up right now where folks are interested in using widget-based plotting (e.g. ipyvolume), but don't want to make a choice that ties them to notebooks. If I can demonstrate a simple way to produce HTML files containing widget-based plots from a plain Python script, that would go a long way.

Yes, that would make sense. `Widget.get_manager_state` and the python-side support forthe schema was added for the purpose of the sphinx extension, but it would probably make sense to enable a higher-lervel API.

Similarly, for beginner who are not familiar with the required minimal html boilerplate, optionally adding it with some css would make sense.

> Can packages identify how to load their own js from npmcdn? Or does that already work, too? I see the ipyvolume docs load ipyvolume widget code, but I don't know how that actually works. Looks like magic!

Yes, this is already done by the embed widget manager which comprises the logic to fetch the static assets on npmcdn. FYI, before going out to npmcdn, it tries to load it locally for offline use, or in case another version is locally vendored.

**Comment by jasongrout** [comment]
I'm putting this in the backlog milestone to put it somewhere, but if someone wants to do it in the next few weeks, by all means move it to the 7.0 milestone.

**Comment by SylvainCorlay** [comment]
I can give it a stab today or tomorrow. I need it too for something else :)

**Comment by jasongrout** [comment]
ping @SylvainCorlay on this...

**Comment by maartenbreddels** [comment]
Some of this is in [ipyvolume](https://github.com/maartenbreddels/ipyvolume/blob/master/ipyvolume/embed.py) which should go upstream.

**Comment by jasongrout** [comment]
Any takers for working on this? I'll move it to Future for now, but if someone wants to take it up, definitely put it back to 7.0.

**Comment by vidartf** [comment]
This would be really useful for us, so I can give it a go. @maartenbreddels Do you want to upstream the code from ipyvolume? Alternatively I can base a PR off the code you linked?

Any suggestions for where such functionality would best belong in the code base?

**Comment by jasongrout** [comment]
> This would be really useful for us, so I can give it a go.

Awesome!

**Comment by hainm** [comment]
+100

**Comment by vidartf** [comment]
(looking at the time, this probably won't be until Monday though)

**Comment by jasongrout** [comment]
We're not releasing before Monday :). Thanks for looking into this.

**Comment by maartenbreddels** [comment]
@vidartf sorry for my late reply, didn't see it, but my answer is yes :)
