### ISSUE TITLE
Tab issues with Layout

### ISSUE THREAD

**Issue by ssunkara1** [jupyter-widgets/ipywidgets#1243]
When I set the `layout` attribute on the `Tab`, the styles are set on the top level `TabPanel` element. But the styles are not applied to the containers below it, `TabPanel-tabContents` and `TabPanel-child` which causes the styles to be not effective when the final `Tab` is displayed.

**Comment by jasongrout** [comment]
Can you give an example of something you want reflected in the tabContents? For example, I noticed setting the height of the tabwidget did not make the tab contents expand, which is what I expected. The width sizes properly, though.

Are there other layout properties that are not behaving the way you want?

Another way to do it is to not have a tab contents - the tabs literally just hide and show the child widgets, and you are responsible for setting the children's layouts however you want. Would that be better? That would mean that it would be much harder to just have a widget as a child - you'd almost always have to encapsulate your tab into a Box or container of some kind.
