### ISSUE TITLE
Label layout regression - clarification of #1010

### ISSUE THREAD

**Issue by britishbadger** [jupyter-widgets/ipywidgets#1246]
Would it be possible to clarify what the expected behaviour of the Label widget is following closure of #1010 ? We have lots of notebooks, all with truncated labels following the upgrade to ipywidgets 6 and it isn't clear as to whether the pull request that enables was reverted or not based on the above. If it was reverted, which release would this be included with ?

I've used the latest jupyter/minimal-notebook docker stack, pip installed latest widgets, enabled the plugin and ran the following:

```
widgets.Label(
    value="A reallly long piece of text",
)
```
I get the output
`A reallly lo...`
The HTML widget works fine so we could transition to that if required. A label with such few charachters seems a little bit pointless though IMO.

**Comment by jasongrout** [comment]
The Label widget is meant to be a drop-in replacement of the description label next to controls. We apply the same styling (e.g., a limited width) like we do to control descriptions so that the Label widget plays nicely with the default control layout, which is based on a fixed-width control (but you can set the `layout.width` to have a wider label if you want).

If you want freeform html text, please use the HTML widget, which applies minimal styling. If you need freeform html with math, then please use the new HTMLMath widget.

**Comment by jasongrout** [comment]
In what context were you using Label? Was it for the descriptive labels next to controls?

**Comment by britishbadger** [comment]
Thanks @jasongrout for replying, yes we are using the label next to components to provide descriptive labels. We tried setting the width too but that seemed to have an upper bound, even when it it was just the label in a cell. This meant it wast not possible to display the full description we'd set for the label regardless of width set. 

Moving to the HTML widget would be fine as it looks like it looks like we would need to make a change eitherway. For the moment though we've reverted to ipywidgets 5.2.2 as 6.x. also breaks some of the complex layouts we have in on particular notebooks built using HBox, VBox and flex layouts. 

I'll close this issue for now.

**Comment by jasongrout** [comment]
> yes we are using the label next to components to provide descriptive labels.

@britishbadger: Great - that's what it is for. I think we've heard now from enough people trying to use labels in this way being frustrated with the width that we should revert the length restriction. I'll make a new PR, which should be included in 7.0, hopefully out pretty soon.

**Comment by jasongrout** [comment]
> For the moment though we've reverted to ipywidgets 5.2.2 as 6.x. also breaks some of the complex layouts we have in on particular notebooks built using HBox, VBox and flex layouts.

@britishbadger - can you describe the problems you were seeing in a new issue? We're drawing close to a 7.0 release, and we'd like to look at the pain points people had moving to 6.0.

**Comment by jasongrout** [comment]
@britishbadger - ipywidgets 7.0 has been out for a while now. Have you seen any issues with upgrading to 7.0?

**Comment by britishbadger** [comment]
Hi, Sorry. I've since moved off the project using this as I've moved companies and I'm unable to check.

**Comment by jasongrout** [comment]
Okay, thanks for the response.
