### ISSUE TITLE
Make it possible to have horizontal radio buttons

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#1247]
From #1239:
> I needed to arrange radio buttons horizontally, couldn't seem to accomplish this with existing widget in 5.2.2 so I made my own. Not sure if this has been addressed in 6.0, perhaps I could use the ToggleButtons now.

**Comment by xelibrion** [comment]
Yep, that would be great to have.

**Comment by amadabalam** [comment]
I would enjoy it too

**Comment by bybyte** [comment]
+1

**Comment by dgrosbard11** [comment]
+1

**Comment by gsaurabhr** [comment]
+1

**Comment by giswqs** [comment]
Any update on this? I would love to have the horizontal radio buttons.

**Comment by wielrenner** [comment]
+1

**Comment by tomnewg** [comment]
+1

**Comment by sjsmith757** [comment]
+1

**Comment by xudong-z** [comment]
+1

**Comment by d-vasek** [comment]
+1

**Comment by yanfeiguan** [comment]
+1

**Comment by rskabelund** [comment]
I don't have time to do a PR, but this small hack has been working for me:

**Comment by RexBarker** [comment]
A more self-contained example:
```
from ipywidgets import Layout, HBox, HTML, RadioButtons

rbuttons = RadioButtons(options=["A", "B", "C"], value="A")
_style = HTML(
    "<style>.widget-radio-box {flex-direction: row !important;}.widget-radio-box"
    " label{margin:5px !important;width: 120px !important;}</style>",
    layout=Layout(display="none"),
)

HBox([rbuttons, _style])
```
Gives:
![Screenshot 2024-05-15 113120](https://github.com/jupyter-widgets/ipywidgets/assets/22831637/4ed878ef-9ab7-4ea7-83bc-566de12d81ce)
