### ISSUE TITLE
Document SelectMultiple rows and layout.height attribute

### ISSUE THREAD

**Issue by julienschroder** [jupyter-widgets/ipywidgets#1271]
# Summary

What's left on this issue is to document that you can give a rows attribute to SelectMultiple, as well as set the height.

---

# Original issue

Hello
I came across #1019 which probably explains the issue I am having but I am not able to find a solution (the new way).
What is the "new way" of dealing with overflow parameters at a box level, as I believe since #1019, it can't be done at the box level anymore.

```
from ipywidgets import Layout
import ipywidgets as widgets
from IPython.display import display

a=widgets.SelectMultiple(
    options=['Apples', 'Oranges', 'Pears', 'Apples', 'Oranges', 'Pears'],
    value=['Oranges'],
    description='Fruits',
    disabled=False,
    layout=Layout(overflow_y="visible")
    
)

display(a)

```
So that doesn't extend the height of the box, what is the new way to display all options?

I also noticed a "non expected" behavior trying to set height and width manually at the box level, the width parameter extend the box width while the height parameter doesn't, it just increase the space under the box
<img width="1170" alt="screen shot 2017-04-07 at 1 03 23 pm" src="https://cloud.githubusercontent.com/assets/12923598/24819813/a35811f2-1b92-11e7-9ba6-d0e42c6abe2c.png">

Apologize if this is documented somewhere, I couldn't find anything relating to those issues.

**Comment by jasongrout** [comment]
In ipywidgets 7.0, we'll have a rows attribute you can use, and we also fixed the layout.height problem you're seeing:

<img width="687" alt="screen shot 2017-04-07 at 9 17 51 pm" src="https://cloud.githubusercontent.com/assets/192614/24824356/dbe31fd6-1bd7-11e7-8484-92fa83321cad.png">

**Comment by jasongrout** [comment]
Here's a pic showing the height fix too:

<img width="712" alt="screen shot 2017-04-07 at 9 21 56 pm" src="https://cloud.githubusercontent.com/assets/192614/24824391/4fbe4584-1bd8-11e7-863b-f78787b334ce.png">

**Comment by jasongrout** [comment]
> Apologize if this is documented somewhere, I couldn't find anything relating to those issues.

We should definitely do a better job with that!
