### ISSUE TITLE
Please document the documentation

### ISSUE THREAD

**Issue by infinity0** [jupyter-widgets/ipywidgets#1273]
It's unclear how to build the docs. Even after I build jupyter-js-widgets, I get:

~~~~
ipywidgets-6.0.0/docs$ make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.4.9
making output directory...

Extension error:
Could not import extension jupyter_sphinx.embed_widgets (exception: No module named jupyter_sphinx.embed_widgets)
Makefile:34: recipe for target 'html' failed
make: *** [html] Error 1
~~~~

Am I supposed to install jupyter-sphinx first? Can I build jupyter-sphinx by itself, without ipywidgets? Otherwise we have a circular dependency ipywidgets -> jupyter-sphinx -> ipywidgets.

**Comment by jasongrout** [comment]
CC @SylvainCorlay - I don't know how to build the docs right now either.

**Comment by jasongrout** [comment]
Found it! (and updated it...) https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/dev_docs.md
