### ISSUE TITLE
Move the disconnected state display into base widget manager/widget view

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#1275]
In order to have a more consistent UI for widgets not currently connected with a kernel, I think we should move the notion of a disconnected widget into the base widget manager. Right now in the classic notebook, we have a small broken link icon indicating a set of widgets not connected to a kernel. We should have some similar notion for other widget views, or at least the top-level containers.

The widgets formed by a widget manager should be considered broken when a kernel is disconnected, killed, restarted, or dead.

**Comment by jasongrout** [comment]
Here is the CSS currently applied to show the red broken chain icon:

```css
    content: "\f127"; /* chain-broken */
    font-family: "FontAwesome";
    color: #d9534f;
    top: 3px;
    padding: 3px;
```

I'm thinking a small absolute positioned div in the upper left of the top-most widget in an output area, with a z-index *under* the widget (so it doesn't interfere with mouse clicks).

**Comment by dsblank** [comment]
What if you didn't set the disconnected state icons until after someone tries to interact with a widget? That is, show the widgets without disconnected icons at first, and if they press a button (for example) then it would set the icons. 

Sometimes I like to scroll down to a newly opened notebook to motivate what our goal is (it will take a number of cells to build what we will see in the widget). But all of the disconnected icons make for confusion. Here is a snapshot of what it looks like:

![screenshot from 2018-01-27 15-25-47](https://user-images.githubusercontent.com/168568/35476000-80fa0fda-0376-11e8-8a5c-c77371ae3af4.png)

The only reason to care as far as I can figure out about the widget's disconnected state is if I am trying to interact with it, and it doesn't respond. 

It would be fine if the disconnected icons propagated up (for widgets with parents) or to the left (for widgets in a HBox) for a single icon per app-of-widgets. But that looks like a lot of work, and I'm trying to think of something simpler that would help resolve this issue.

**Comment by dsblank** [comment]
Another possibility: insert the connection-indicator class when a widget is displayed, but only the top-most-one (eg, non-recursively). Then there is only one classification per widget/widget-group.

**Comment by jasongrout** [comment]
> Another possibility: insert the connection-indicator class when a widget is displayed, but only the top-most-one (eg, non-recursively). Then there is only one classification per widget/widget-group.

I really like this idea. Definitely +1.

**Comment by jasongrout** [comment]
Can you open an issue for it?

**Comment by jasongrout** [comment]
(or a PR would be even better! :).

Thanks for bringing this up.
