### ISSUE TITLE
Not found: package jupyter-js-widgets@~3.0.0

### ISSUE THREAD

**Issue by hainm** [jupyter-widgets/ipywidgets#1283]
Hi, FYI: https://unpkg.com/jupyter-js-widgets@~3.0.0/dist/embed.js

Not found: package jupyter-js-widgets@~3.0.0

That's link is from embedded widget.

**Comment by hainm** [comment]
oh, I tried master branch that I install yesterday.

**Comment by jasongrout** [comment]
Yes, we haven't published that package yet.
