### ISSUE TITLE
Export custom widgets to PNG / static image

### ISSUE THREAD

**Issue by pbugnion** [jupyter-widgets/ipywidgets#1291]
I maintain [jupyter-gmaps](https://github.com/pbugnion/gmaps), which uses widgets to display data on Google Maps.

I occasionally receive [requests](https://github.com/pbugnion/gmaps/issues/62#issuecomment-294424416) for saving maps as static images. It seems like this could be done with a tool like [html2canvas](http://html2canvas.hertzen.com): the entire div containing the widget could just be exported to to a png. I note that something along those lines was done in [PR 314](https://github.com/jupyter-widgets/ipywidgets/pull/314), but I can't see how to use it -- apologies if I'm missing something obvious.

If the solution to this involves writing code or documentation, I'm more than happy to contribute, but I would definitely need initial guidance.

**Comment by jasongrout** [comment]
CC bqplot developers @dmadeka and @ssunkara1 as well.

We did have some sort of snapshot rendering of widgets at one point (the PR you mention). I'm not sure where that is these days - likely it was superseded by @SylvainCorlay's work on embedding live widgets instead.

Looking at your issue, are you imagining that every DOMWidget would have a .save() method that would instruct the frontend to take a screenshot using html2canvas and send it back to python? We'd have to deal with (or educate the user about) the limitation that the saving would have to be asynchronous - we couldn't just save and then use the file in the next line. Also there would be the confusion of trying to run the code with no frontend, or in a frontend that doesn't support widgets, or in multiple frontends (which one should do the rendering?).

Perhaps it's more natural to have a 'save to png' option (button, or whatever) in the frontend that would download a png of the map from the browser? That's the approach bqplot took. That way the widget can control exactly what is imaged and how it is imaged.

**Comment by pbugnion** [comment]
Thanks very much for getting back to me. 

I was thinking of DOMWidgets exposing a `.save('export.png')` method that would instruct the frontend to take a screenshot and either display it in a `data` url or send it back to Python which would save it to disk. I hadn't thought of the multiple frontend problems that you mention.

> Perhaps it's more natural to have a 'save to png' option (button, or whatever) in the frontend that would download a png of the map from the browser? That's the approach bqplot took. 

That makes a lot of sense. I will take a look at how `bqplot` does it.

**Comment by pbugnion** [comment]
I'm happy to close this, but any further advice or guidance would be really welcome.

**Comment by jasongrout** [comment]
Let's close this for now in favor of a frontend-based approach (i.e., a button or something in the frontend that keeps everything, including the saving/downloading in the browser). If that is not sufficient, let's take another look at what we could do.

**Comment by jasongrout** [comment]
> any further advice or guidance would be really welcome.

It's a bit different (more complicated) in bqplot since that is svg-based. You already have a canvas, right? You could just save the canvas as a png and download it or display it as a data url.

**Comment by pbugnion** [comment]
> You already have a canvas, right?

I don't think so -- I don't draw on the maps directly (that sounds hard). I just rely on the Google Maps JavaScript API to add overlays on top of the map. It looks like it just embeds an iframe with the rendered map in the page. Anyway, it looks like some people have had [some success](http://stackoverflow.com/questions/16235161/save-current-google-map-as-image) using `html2canvas` to export Google Maps to image.

Thanks again for your help -- this was really useful.
