### ISSUE TITLE
"Widget Javascript not detected" despite working progress bars

### ISSUE THREAD

**Issue by chrisvoncsefalvay** [jupyter-widgets/ipywidgets#1315]
```
ipywidgets==6.0.0
widgetsnbextension==2.0.0
jupyter-nbextensions-configurator==0.2.4
jupyter==1.0.0
```

My code involves a simple `FloatProgress` that's updated every time an iterator passes over a file - nothing fancy. However, every time a progress bar is supposed to be displayed, a `Widget Javascript not detected` error is triggered

![screenshot 2017-04-26 23 13 39](https://cloud.githubusercontent.com/assets/2670100/25457411/76d6afb4-2ad6-11e7-927f-c6f35c46ed6b.png)

I have installed the widgets and activated them just as the installation instructions suggest, and it seems at least the JS widget is fine 👍 

![screenshot 2017-04-26 23 16 51](https://cloud.githubusercontent.com/assets/2670100/25457424/8d873bf2-2ad6-11e7-9cf1-96876aafe4b9.png)

So why do I keep getting this error message?

**Comment by jasongrout** [comment]
Are these cells being run immediately after the kernel is started? There is a known issue with that (search for "Widget Javascript not detected"). We've removed this warning in the upcoming ipywidgets 7.0.

**Comment by jasongrout** [comment]
Closing as fixed in ipywidgets 7. Please reopen if you still have these issues with the latest 7.0 beta.
