### ISSUE TITLE
table_beautifier in widget

### ISSUE THREAD

**Issue by disimone** [jupyter-widgets/ipywidgets#1319]
Hi,

in jupyter I am using the table_beautifier extension to provide some nice display of dataframes, and I would now like to put one of such tables into a container widget.

How do I do it?

Using widgets.HTML as a wrapper and setting its value to the to_html version of the dataframe gives back the plain table layout. I tried adding the dataframe directly as child to the container, without wrapping it into anything, but this resulted in a "Can't clean for JSON" error.

Thanks for your help,

Andrea.

**Comment by jasongrout** [comment]
Maybe use an output widget?

```
from ipywidgets import Output, HBox
out = Output()
with out:
    ... do whatever you do to display the data frame ...
display(HBox([out, out]))
```

**Comment by disimone** [comment]
Thanks for the suggestion. In a normal notebook with the extension enabled, display(myDataFrame) is enough to get the interactive table in the output cell.

My attempt with ipywidgets is:

```
out=widgets.Output()
display(myDataFrame)
thewidget=widgets.VBox([                   
 out,
 something_else])
```

"thewidget" is then added to a tab, so I guess there is no need to explicitely call display(out). This runs without problems, but still gives the normal static table layout.

Any more suggestions?

Thanks for your help,

Andrea.

**Comment by jasongrout** [comment]
You need to follow the example I posted:

```
with out:
    display(myDataFrame)
```

**Comment by jasongrout** [comment]
(I don't know what the table_beautifier extension does - if the above doesn't work, the problem may be in getting the extension to recognize that there is a table in an output widget?)

**Comment by disimone** [comment]
Thanks Jason. your last recipe is not working either. AFAICT as a js-ignorant, the extension is passing the table through tablesorter:

http://tablesorter.com/docs/

could it be that the problem is that the widget does not call tablesorter and handles the display itself?

**Comment by disimone** [comment]
I did find this message in the browser console, though:

manager.js:313 Uncaught (in promise) Error: Could not determine where the display message was from.  Widget will not be displayed
    at WidgetManager.display_model (manager.js:313)
    at widget.js:161

**Comment by jasongrout** [comment]
Here is the code that works for me (on basically the latest alpha of ipywidgets)
```python
import pandas as pd
from ipywidgets import *
from IPython.display import display
import numpy as np

out = Output()
with out:
    display(pd.DataFrame(np.random.randn(10,5)))
display(HBox([out, out]))
```
If that doesn't work with the table beautifier extension, can you confirm it works without the extension?

**Comment by jasongrout** [comment]
<img width="745" alt="screen shot 2017-04-28 at 1 50 59 pm" src="https://cloud.githubusercontent.com/assets/192614/25540618/bf65ecc4-2c19-11e7-9262-d43c7b90e1b3.png">

**Comment by disimone** [comment]
Hi Jason,

thanks for your replies. I am happy to report that things are working perfectly now, using the Output widget as you suggested and the table_beautifier. All I did to make it work was to upgrade ipywidgets, so I guess it must have been something related to the older version.

Thanks for your help,
Andrea.

**Comment by jasongrout** [comment]
Great!

**Comment by disimone** [comment]
Hi Jason,

I am back to having problems with this. Display in jupyter now works smoothly, but I am now trying to use the "Embed widgets" functionality. I just paste the code into an empty html page and load it into a browser.

Things work nicely, exceptfor the tables created through the table_beautifier. Instead of the table, I get this text

![image](https://cloud.githubusercontent.com/assets/25104002/26727875/9c89ccd4-47a8-11e7-9662-44578dec64cb.png)

I am guessing the javascript table that went into the Output widget is not being correctly dumped by the embedding function. Is this a bug, or you do it by design?

Related to this: is there a way to create the embeddable code with a python command, possibly passing specifically the widgets I want to be embedded? I typically have a lot of widgets in a notebook, and want to export just one of them.

Thanks for your help,

Andrea.

**Comment by jasongrout** [comment]
The output widget is not implemented yet for the embedded widgets. See https://github.com/jupyter-widgets/ipywidgets/pull/1380 for progress.

Also, you might be able to get code for embedding specific widgets with https://github.com/jupyter-widgets/ipywidgets/pull/1387.

**Comment by enryH** [comment]
@jasongrout: I cannot see the scroll bar when I use your example (on a windows machine both in notebook and jupterlab). Any Idea how to solve that?

So: 
```python
import pandas as pd
from ipywidgets import *
from IPython.display import display
import numpy as np

w_dims = IntSlider()

out = Output()
with out:
    display(pd.DataFrame(np.random.randn(10,300)))

display(HBox([out]))
```
gives
![image](https://user-images.githubusercontent.com/2833836/74256073-22a19480-4cf3-11ea-85a4-b3736d7de17b.png)

whereas

```python
import pandas as pd
from ipywidgets import *
from IPython.display import display
import numpy as np
display(pd.DataFrame(np.random.randn(5,300)))
```
yields what I expect:
![image](https://user-images.githubusercontent.com/2833836/74256278-685e5d00-4cf3-11ea-9817-f0c6825ab82f.png)


(I need it for a more involved example, but I thought to start easy)

**Comment by jasongrout** [comment]
Can you open a new issue for this? I have some investigations that show what is happening, but it should be on a new issue we can pursue, and is not really relevant to this issue.
