### ISSUE TITLE
Create a Log output widget to log any output from sync messages

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#1321]
In #1320, we have the problem that a sync message is causing an error that has no place to be displayed in the front end. Until the front end has a place to display unhandled output, perhaps we should create an output widget that stores any output from sync handling.

I *think* this should be fairly straightforward - create an output widget when widgets are imported, and make sure we are using the output widget when we actually set the state of any widget.

**Comment by jasongrout** [comment]
By the way, this may make calling `this.touch()` on widget views unnecessary to save the changes - maybe now we should *always* call `this.model.save_changes()` (but leave in `this.touch()` for backwards compatibility).

**Comment by maxnoy** [comment]
This is a temporary solution that would allow capturing widget output until a dedicated output tab for all orphan output was implemented in jupyter-lab and/or jupyter-notebook.

The complexity is that the amount of output could be quite large (messages/errors can be generated for each widget change). 

This can be managed by either clearing output for each widget message or by having an adjustable-depth buffer.  The former would not work as the output widget utilizes the same widget messaging mechanism, resulting in the messages being cleared immediately by the update on the output widget. And the latter is a substantial amount of work/ux that may as well be redirected to the long-term solution.

**Comment by jasongrout** [comment]
Agreed! Closing this in favor of the notebook issue!
