### ISSUE TITLE
Be consistent with the tag names

### ISSUE THREAD

**Issue by infinity0** [jupyter-widgets/ipywidgets#1327]
Hi, there are tags like v7.0.0a1 and v5.0.0 but also 6.0.0 and 5.0.0. Could you adopt a consistent tag naming scheme please? This helps distributions' auto-checking scripts be more accurate when reporting upstream version status. Thanks!

**Comment by jasongrout** [comment]
You're right, we should be consistent. I checked a bunch of the Jupyter repos, and it seems that they are pretty consistent with tags without a `v` prefix, so I'll retag without the `v`.

**Comment by jasongrout** [comment]
I just pushed new tags for 7.0.0a* without the `v`.
