### ISSUE TITLE
<br/> is not working in HTML widget

### ISSUE THREAD

**Issue by jakhani** [jupyter-widgets/ipywidgets#1333]
Hi,

We are using Sparkmagic and Jupyter Notebook. It uses ipywidgets for UI. Before version 6.0, <br/> was working well and adding new line. After version 6.0, it has stopped accepting `<br/>` or `<p>` tags in HTML. Can you please provide solution for this issue of available?

Thanks,
Janki Akhani

**Comment by jasongrout** [comment]
It seems to work for me on master. Would you be able to try with the latest alpha to see if it's a problem there?

<img width="465" alt="screen shot 2017-05-05 at 7 34 29 pm" src="https://cloud.githubusercontent.com/assets/192614/25769288/08645c16-31ca-11e7-9e16-97a0c49f69a1.png">

**Comment by jasongrout** [comment]
Closing as fixed in 7.0. If it isn't working for you in 7.0 (like in the alpha), please reopen.
