### ISSUE TITLE
Benchmark the json vs binary transfer

### ISSUE THREAD

**Issue by maartenbreddels** [jupyter-widgets/ipywidgets#1339]
We should benchmark the speedup we get by going from json to binary, by measuring the roundtrip time of say sending 1M float's back and forth, so get to a number, like 'x100 speedup'. Happy to do this btw.

**Comment by jasongrout** [comment]
That would be great!

**Comment by maartenbreddels** [comment]
Took a shot at this, and the notebook [can be found here](https://gist.github.com/maartenbreddels/40fa030fdb922e6d2074282ceed6b753).
The speedup is only a factor of 6x, I thought it would be in the order of 100 (from my first experiments that is what I found). It's difficult to profile though.

**Comment by maartenbreddels** [comment]
Ok, found out at least something that isn't great. 
In backbone's [set](https://github.com/jashkenas/backbone/blob/09cb8871d81b6f627c1edef46de97d7c2e8e2078/backbone.js#L509) we eventually get to compare two typed array, eventually landing [in underscore's eq](https://github.com/jashkenas/underscore/blob/master/underscore.js#L1272) which then is calling _.keys() generating a list of a million integers...
So, maybe we need to have a PR for underscore for comparing typed arrays more efficiently, since this will happen anyway. Why this comparison is happening i'm not 100% sure.
Not sure this can be tackled for v7 though..

**Comment by maartenbreddels** [comment]
Ok, I'm not simply checking how fast it is to send the data to the front end (no sending it back). If I run the profiler using %%prof, I see 0.005 sec is being spend. Profiling the JS side, also no time is spend there.
Any idea how to attack this futher? The next logical step seems to profile the kernel and/or the notebook server, but I'm not sure how that can be done.

**Comment by jasongrout** [comment]
> In backbone's set we eventually get to compare two typed array, eventually landing in underscore's eq which then is calling _.keys() generating a list of a million integers...

That's awful! We need to figure out a way to be smarter. This might be the last straw for using backbone...

**Comment by maartenbreddels** [comment]
Well, the _.keys() is from _.isEqual

**Comment by jasongrout** [comment]
presumably if we replaced backbone, we'd be smarter than just calling `_.isEqual`, or at least make it easy to plug in your own comparison.

**Comment by jasongrout** [comment]
We already do that on the python side, originally to special-case numpy arrays.

**Comment by maartenbreddels** [comment]
That's true, maybe should also file an issue for _.

**Comment by jasongrout** [comment]
That makes sense too - they have lots of special cases already, so introducing another special case for typed arrays makes sense.

**Comment by maartenbreddels** [comment]
I'm focussing now only on sending data from the kernel to frontend
After profiling the kernel and the notebook (nbprofiler is born :)) I found out a lot of time was spend on compressing the data going over the websocket. Now I have 60x speedup of binary vs json! But, it requires turning off websocket compression. 
This was turned on in the notebook here https://github.com/jupyter/notebook/pull/1261/files
Any thoughts on what to do about this? I understand compression can be useful, I wonder if it should be disabled by default, and turned on for notebook servers that are expected to be approached from outside. When everything is running on localhost it's a massive slowdown.

cc @Carreau

**Comment by jasongrout** [comment]
Very interesting! Also CCing @minrk, @SylvainCorlay.

**Comment by jasongrout** [comment]
I think it makes sense to optimize for the localhost case (i.e., no compression), but provide an option to turn it on.

**Comment by maartenbreddels** [comment]
Transferring from kernel to frontend on a decent desktop running linux and notebook 4.4.1 (has no compression yet) gives a 100x speedup! I think that is a significant improvement and something we can 'advertise' with, provided compression is turned off by default in more recent notebook servers.

**Comment by maartenbreddels** [comment]
Sending an array with 10 million float32 values takes ~0.5 seconds, and 100 million takes ~5 seconds. That is 400 MB of data send to the browser, so it's close to 100MB/s, not that bad. But it's amazing that such large amounts of data can be send to the browser.

**Comment by maartenbreddels** [comment]
In case anyone reads this in the future, I used https://github.com/maartenbreddels/nbprofiler to profile the Jupyter notebook itself.

**Comment by jasongrout** [comment]
Do you want to add the information above to the changelog, and we can consider this issue closed? Or was there more benchmarking you wanted to do?

**Comment by maartenbreddels** [comment]
I'm not sure it belongs in the changelog, since it is not a change right? But I think we can close it?
Conclusion is, using binary versus json is up to 100x faster.

**Comment by jasongrout** [comment]
> I'm not sure it belongs in the changelog, since it is not a change right? But I think we can close it?
> Conclusion is, using binary versus json is up to 100x faster.

What I meant was to insert a phrase in bullet point talking about the binary serialization.
