### ISSUE TITLE
Process widget comm messages in the shell channel when Kernel's main thread is busy

### ISSUE THREAD

**Issue by krishnan-r** [jupyter-widgets/ipywidgets#1349]
I am trying to implement a widget to integrate the monitoring and visualization of Apache Spark jobs from within the notebook, including displaying of cell level progress bars and job cancel buttons. Apache Spark blocks the kernel thread and waits until the job is finished. The widget that monitors this job needs to communicate with the kernel while it is busy.

Currently from a background thread, the kernel side component is able to send comm messages via `IOPub` channel to the front-end widget. `IOPub` runs on its own thread and seems to be thread safe to publish messages from a background thread. So the kernel side can send progress updates.

However Widget Comm messages sent from the front-end to the kernel, are processed in the `shell` channel which is flushed only in the main thread loop of the kernel. When the kernel is busy executing, widgets can no longer send messages to the kernel, ie. kernel cannot process these messages until its main thread is free. This prevents the implementation of a stop button, or polling for updates(as mentioned in #1287). 
(please correct me if i am wrong)

I have tried using `ipython.kernel.do_one_iteration()` from a background thread for the incoming messages to get flushed, but this triggers all the shell channel messages to get processed including execution requests of later cells, which are not supposed to be processed until the current cell is done. This breaks the flow of the notebook.

I have gone through #642, but I cannot put the execution of spark in a separate thread as the widget has to be seamlessly integrated with the notebook. Would require asking the user to run the job on another thread.

Is it possible to create a mechanism to selectively process incoming widget comm messages from `shell_stream` in a background thread in the kernel, so that widgets can remain responsive while the kernel is busy?

Or it may be required to create a separate channel for full duplex communication with widgets from a background thread, How can I do this?

I read that an integration with Spark is in the [roadmap](https://github.com/jupyter/roadmap/blob/master/spark.md) for project Jupyter, I am working on something related to this as part of [Google Summer of Code](https://summerofcode.withgoogle.com/organizations/4978158764818432/#4603184614998016) with [CERN-HSF,](http://hepsoftwarefoundation.org/gsoc/proposal_ROOTspark.html) and I can help contribute towards this roadmap.

Please advise what can be done? Thank you.

**Comment by jasongrout** [comment]
Also cc @minrk

**Comment by jasongrout** [comment]
This is a pretty fundamental question about the design of the messaging system. The message spec implies that the shell queue is processed in order. For the ipython kernel implementation, it also brings up the point of where messages are processed.

> Is it possible to create a mechanism to selectively process incoming widget comm messages from shell_stream in a background thread in the kernel, so that widgets can remain responsive while the kernel is busy?

The only way right now to pre-empt the shell queue, according to the spec, is to use the control channel, but that still doesn't pre-empt a running execution. Discussion about a mechanism to process shell messages simultaneously should be taken up in an issue in the message spec repo, https://github.com/jupyter/jupyter_client.

@SylvainCorlay suggested that you invert your suggestion, and put your long-running process in a thread, and leave the main thread available to process widget messages. How far would that get you?

**Comment by jasongrout** [comment]
Closing since this issue goes far beyond widgets, and at the core of the Jupyter messaging spec. I'd suggest that you either (a) open an issue in the https://github.com/jupyter/jupyter_client repo, or probably better, (b) put the long-running process in a thread, and keep the main thread available to be responsive to messages.

**Comment by krishnan-r** [comment]
Thank you for the suggestion. However putting the long running operation on another thread requires the user of the notebook run another thread to use the widget. That makes the widget a not so useful integration. I shall open another issue in jupyter_client after some more investigation. Thank you.
