### ISSUE TITLE
draggable range sliders

### ISSUE THREAD

**Issue by alon-jacobi** [jupyter-widgets/ipywidgets#1351]
With IntRangeSlider and FloatRangeSlider, it is possible to drag each end of the slider to modify the value.
It would be useful if, when dragging the bar itself (and not the min/max markers), both the min and max would shift accordingly.
That way, when using a slider with 0,100 limit and current values 0,10, dragging the slider to 10,20 would be easier and not require dragging each of the markers individually.

**Comment by jasongrout** [comment]
Great idea. It looks like this is maybe implemented by [a jqueryui extension](http://stackoverflow.com/questions/5955343/drag-the-range-of-a-ui-input-range-slider/6095941#6095941), or I think it is also implemented in other slider implementations (see our discussion about replacing the slider with other sliders at https://github.com/jupyter-widgets/ipywidgets/issues/630)

**Comment by jasongrout** [comment]
It looks like it may have been added to jqueryui at some point: https://github.com/jquery/jquery-ui/pull/331, but I don't seem to find anything about the rangeDrag option now.

**Comment by thomasaarholt** [comment]
It looks like the PR in jquery/jquery-io#331 was never merged, @jasongrout.

I would like to see this feature implemented too.

I found a reference to it here: https://github.com/rassokhin-s/jquery.ui.slider.dragRange
What does it take to implement it in ipywidgets?

**Comment by vidartf** [comment]
This is possible in master (for upcoming 8.0 release) after the switch of the slider library.
