### ISSUE TITLE
Notebook validation failed

### ISSUE THREAD

**Issue by studiobytestorm** [jupyter-widgets/ipywidgets#1352]
I am trying to use ipywidgets in jupyter notebook. But whenever I add any widget to a notebook I keep getting the following message,

![image](https://cloud.githubusercontent.com/assets/6783945/26025024/94f79610-37fc-11e7-9aa2-73ddaac4c215.png)

![image](https://cloud.githubusercontent.com/assets/6783945/26025009/4f772cf4-37fc-11e7-82c0-63af45a020c4.png)

I tried changing browsers (firefox and chrome) also, it didn't help. 

ipywidgets version: 6.0.0
python: 3.5.2
jupyter: 1.0.0

How do I solve this issue? I couldn't find any solution for this on google, stackoverflow.

**Comment by jasongrout** [comment]
What version of nbformat do you have? Can you try upgrading nbformat?

**Comment by studiobytestorm** [comment]
Yes, that probably solved the problem, thanks...

These were the installed versions of nbformat,

```
C:\Users\Bishal Santra>conda list nbformat
# packages in environment at D:\Program Files\Anaconda3:
#
nbformat                  4.1.0                    py35_0
nbformat                  4.3.0                     <pip>
```

Updated it using

`conda update nbformat`

Now the versions are,

```
C:\Users\Bishal Santra>conda list nbformat
# packages in environment at D:\Program Files\Anaconda3:
#
nbformat                  4.3.0                    py35_0
nbformat                  4.3.0                     <pip>
```
and the 'notebook validation' problem is not popping up anymore.

**Comment by jasongrout** [comment]
Yes, you need at least nbformat 4.2.0. It does look like there is an issue with your setup if you have nbformat installed twice.

**Comment by aungmyohtet07** [comment]
I would like to know how to upgrade nbformat.

**Comment by talhaanwarch** [comment]
same issue on a fresh notebook installed on virtual env

**Comment by jasongrout** [comment]
Please open a new issue and include the version of nbformat and notebook and an example notebook that does not work.
