### ISSUE TITLE
SelectionRangeSlider is not visible

### ISSUE THREAD

**Issue by heavelock** [jupyter-widgets/ipywidgets#1359]
Hi! I'm just testing a feature introduced to master by #1356. The widget is not visible after running code which is in docs, see screenshot below.
![image](https://cloud.githubusercontent.com/assets/10303802/26201846/4660f730-3bd5-11e7-9a1f-978f93deee17.png)

There is no visible effect of executing the code. There is no error, no warning, nothing.

My config:
Linux Mint 18.1
Python 3.6.1
Jupyter installed from current master (73f26bf047da79cbe847ffa7f16301cdc374eb4a)
ipywidgets installed from current master (780b64e6a522267cdf0a17b143209d00b819c675)
Browser: 	Opera 45.0.2552.634 & Chrome 58.0.3029.110 (64-bit) & Firefox 50.0.2

**Comment by SylvainCorlay** [comment]
You need to display the widget eventually, by 

 - either ending the cell with a statement that is a widget such as `ww`
 - or calling `display(ww)` at any point (`from IPython.display import display`)

**Comment by heavelock** [comment]
Ugh, I pasted wrong screenshot... Anyway, the point is it does not work that way either.
ToggleButtons widget example taken from the docs works like a charm.
![image](https://cloud.githubusercontent.com/assets/10303802/26202228/e3b2029e-3bd6-11e7-90a1-065dd9a274e5.png)
![image](https://cloud.githubusercontent.com/assets/10303802/26202244/f68087b0-3bd6-11e7-9587-8c0ab3452bf4.png)
![image](https://cloud.githubusercontent.com/assets/10303802/26202288/1967b5aa-3bd7-11e7-8028-fcf996b2c098.png)

**Comment by maartenbreddels** [comment]
My best guess is that the notebook gets the wrong (old) javascript somehow, my way of attacking that is to delete the javascript file for the widgets, refresh the browser and make sure it *cannot* download it. Sometimes it may be installed in an unexpected location (such as `~/Library/Jupyter/....`). Once it is *fully* broken, reinstall it.

**Comment by jasongrout** [comment]
Does it give any warnings or errors in the browser's javascript console?

**Comment by heavelock** [comment]
Yup.
`Uncaught (in promise) TypeError: Cannot read property 'state_change' of undefined
    at WidgetManager.ManagerBase.create_view (manager-base.js:48)
    at WidgetManager.ManagerBase.display_model (manager-base.js:29)
    at extension.js:99
    at <anonymous>`

BTW: I'm not sure if connected at all but the DatePicker widget also looks to be broken now. It's not able to set any date either by typing it (it gets resetted to placeholder when trying to type third part of a date) or by choosing by calendar. But it doesn't throw anything to the javascript or jupyter console.

**Comment by jasongrout** [comment]
I'm in the process of releasing another alpha right now, FYI.

**Comment by heavelock** [comment]
I've installed using current master (3ae4d117d086c2c02ce5d8fdfb0c45230a46d1db) and it works great. 
Thanks!

PS: DatePicker widget also works now.

**Comment by jasongrout** [comment]
Great!
