### ISSUE TITLE
Fix failing ReadTheDocs build

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#1366]
@SylvainCorlay - RTD is failing to build master because of a conflict between python 3 and some config: https://readthedocs.org/projects/ipywidgets/builds/5442324/
I don't think I have permissions to fix it. Can you take a look?

**Comment by SylvainCorlay** [comment]
Fix coming.

**Comment by SylvainCorlay** [comment]
https://github.com/conda-forge/sphinx_rtd_theme-feedstock/pull/7

**Comment by jasongrout** [comment]
Note that we're not using the rtd theme anymore...

**Comment by SylvainCorlay** [comment]
Oh yes, the new alabaster thing. We would need a conda recipe for it.

**Comment by blink1073** [comment]
We're getting it from pip: https://github.com/jupyterlab/jupyterlab/blob/master/docs/environment.yml

**Comment by jasongrout** [comment]
Sylvain, can you just have it stop trying to install the RTD theme?

**Comment by SylvainCorlay** [comment]
No, we cannot do that. It is hardcoded into RTD. https://github.com/rtfd/readthedocs.org/blob/ef2a69848297bfa06fab9e4c13e75050b415e490/readthedocs/doc_builder/python_environments.py#L200

**Comment by SylvainCorlay** [comment]
The issue is that RTD uses `sphinx_rtd_theme` 1.7 from the default channel which is only available for python 3.4

**Comment by jasongrout** [comment]
We can change the environment.yml to require python 3.4, I suppose. I do want python 3 so that the example notebooks are executed with python 3.

**Comment by jasongrout** [comment]
I pushed to master a commit which reverted back to basically the old environment.yml:

http://ipywidgets.readthedocs.io/en/latest/index.html

However, it doesn't have the version selector, download to html/pdf, etc., that the rtd theme has. Thoughts?

**Comment by jasongrout** [comment]
Issue filed at https://github.com/jupyter/jupyter-alabaster-theme/issues/77 for the missing version selector, etc.

**Comment by jasongrout** [comment]
I think we can close this as fixed now.

**Comment by SylvainCorlay** [comment]
> Thoughts?

I think that we should never have made a custom theme to start with...

**Comment by jasongrout** [comment]
I just found that version selector - it's in the bottom right now, though!
