### ISSUE TITLE
Hardcoded max width of widget output box

### ISSUE THREAD

**Issue by heavelock** [jupyter-widgets/ipywidgets#1374]
Hey!
While playing around with Date Range Slider I found another problem with it. 
I wanted to create a widget that would allow to select range of dates formatted as yyyy-mm-dd. Unfortunately, the div that contains output has a hardcoded max width and the values doesn't fit the box. 

![div](https://cloud.githubusercontent.com/assets/10303802/26295216/20324068-3ec9-11e7-9fff-e5df7f5835b1.png)

Is there any workaround for that problem?

**Comment by heavelock** [comment]
Well, I should spend more time in docs before I asked. 
http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Styling.html

I'm sorry for spamming.

**Comment by jasongrout** [comment]
No problem! I had that issue too - we have some ideas about how to change the structure of sliders to give the slider more space and give more room to the readout, add ticks, etc.
