### ISSUE TITLE
NGL widget won't render

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#1375]
Continuing the conversation at the end of #1044, the NGL widget apparently won't render. @hainm is pursuing the issue.

**Comment by jasongrout** [comment]
Apparently it did render on the commit in #1270. @hainm - what commit does it not render on now?

**Comment by hainm** [comment]
> what commit does it not render on now?

`git bisect` tells me that the issue reappears from https://github.com/jupyter-widgets/ipywidgets/pull/1280 (right after the `OK` #1270).

**Comment by jasongrout** [comment]
Thanks for tracking that down. Hmm...My first guess is that it has to do with the issue from https://github.com/jupyter-widgets/ipywidgets/issues/1044#issuecomment-276514415 - something to do with the pending message counter. I'll try looking at this tomorrow again.

**Comment by jasongrout** [comment]
Does the issue show up with the self-contained demo?

```python
# cell 1
import nglview as nv
view = nv.demo()
view

# cell 2
# click the atoms
# then
view.picked
```

**Comment by hainm** [comment]
Yes, if things work, when you click to one of the atoms, the `view.picked` should have data.

If not, you will get `{}`.

**Comment by hainm** [comment]
![demo](https://cloud.githubusercontent.com/assets/4451957/26335671/7e0364c0-3f3b-11e7-8980-34d253594413.png)

**Comment by jasongrout** [comment]
@hainm - I think I found the fix in the ngl code: https://github.com/arose/nglview/issues/618

**Comment by jasongrout** [comment]
But this does bring up the point - should the message throttling apply to comm messages? Perhaps the pending message counter should only apply to sync messages. I'll think about that.

In this case it was good that the pending message counter applied to custom messages - it broke things enough that we found the bug in the ngl code.

**Comment by jasongrout** [comment]
Tagging as needs info so you can confirm the fix before we close this issue.

**Comment by hainm** [comment]
indeed `this.send` works. thanks Jason. You can close this now.

**Comment by jasongrout** [comment]
Great, glad we got to the bottom of this.

I'll open another issue about the message throttle applying to custom messages.
