### ISSUE TITLE
Discuss/approve default description width

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#1377]
In #1376, I adjusted the label width to be a single set value (instead of having a min/max). Is 80px sufficient, or should we make it a bit wider?

**Comment by mwcraig** [comment]
If it was up to me, I'd say that instead of adding more to a fixed width, add an option to adjust the size of the field to the text provided. The default could be *not* to do this so that there is still nice alignment by default. I find myself overriding the new behavior frequently.

**Comment by jasongrout** [comment]
That should correspond to setting it to 'initial'

**Comment by jasongrout** [comment]
To clarify, you should be able to get that behavior by setting `.style.description_width` to `'initial'`, as it says in the description of #1376.

**Comment by jasongrout** [comment]
Let's release a beta and change it if there are complaints about it being too short.
