### ISSUE TITLE
Accordion and button widgets doesn't work with observe

### ISSUE THREAD

**Issue by heavelock** [jupyter-widgets/ipywidgets#1386]
Hi!
I wanted to do an interactive plot with filtering based on ValueSliders for one of two columns in dataframe. For that purpose I made two ValueSliders which are stacked in the accordion. Additionally I added third panel to accordion with button which basically is supposed to clear the filters. All of the widgets (sliders, button, accordion) are set to observe and run one function. Unfortunately, the function is run only when value of any of sliders is changed. It is not executed when I click a button or change tab in accordion. 

I've checked the js console when using those widgets and nothing is thrown there.

My code:
https://gist.github.com/heavelock/410134ef382b09855b26619f4da02fc7

Jupyter and ipywidget installed using masters pulled 3 hours ago.
ipywidgets 2940f9f56f63257902b27509f18e872e77c3c014
Jupyter c9d399ace6bb2222b213a7727df49c5c9b2fca9b

**Comment by jasongrout** [comment]
It looks like the issue in the code is that you are always observing the `value` attribute, but for an accordion, the thing that changes is the `selected_index` attribute. For a button, a custom event is sent on click, so you register a handler with the button `.on_click()` method: `button.on_click(python_callback)`

**Comment by heavelock** [comment]
Uh. After applying changes you proposed the whole thing works like a charm.

Thanks for help and I'm sorry for bothering with such trivial problems...

**Comment by mwcraig** [comment]
> Thanks for help and I'm sorry for bothering with such trivial problems...

@heavelock -- I would say the bug report was quite useful, since `selected_index` isn't explained anywhere in the documentation! Can you please take a look at #1491, which adds some explanation?

**Comment by heavelock** [comment]
@mwcraig Thanks for this PR! Lack of this explanation was confusing and your instruction will be definitely useful in future!

**Comment by AbdealiJK** [comment]
Adding to this thread as it's related - In http://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Asynchronous.html I can see examples on how to make widgets asynchronous using the .observe() on the 'value'.

If buttons do not have the .observe() - how can I make this asynchronous ?

My aim is that:
 - Even if my kernel is busy doing some computation, my button should be able to do it's job (maybe in a different thread)
I was thinking of creating a thread and using the generator approach within the second thread.

**Comment by jasongrout** [comment]
If the main thread is busy, it cannot process messages from the frontend, so you won't be able to respond to button clicks. Either the main thread will need to periodically check for messages to process, or you'll need to move your main busy computation into a thread.

**Comment by jasongrout** [comment]
You can have the kernel process a message with something like `get_ipython().kernel.do_one_iteration()`
