### ISSUE TITLE
Button ipywidget won't update description to empty space

### ISSUE THREAD

**Issue by samzn** [jupyter-widgets/ipywidgets#1391]
the python code 

    w=widgets.Button(description='words')
    display(w)
    w.description='different words'

will show a button widget that is modified to have a description of 'different words'.

But, the code

    w=widgets.Button(description='words')
    display(w)
    w.description='     '

will show a button widget that is unmodified (with description 'words');

however, after this point ```print(w.description)``` will return ```'     '```and further calls to ```display(w)``` will have an updated display.

I think this may be a bug.  (I'm using ipywidgets 6.0.0)

**Comment by jasongrout** [comment]
Thanks for bringing this up. I've posted a fix in #1392, which should go into 7.0.
