### ISSUE TITLE
`DatePicker` should work with `datetime.date` instead of `datetime.datetime`

### ISSUE THREAD

**Issue by randomstuff** [jupyter-widgets/ipywidgets#1393]
A `DatePicker` really is about selecting a date and should probably yield a `datetime.date` value. It it implemented by a [`<input type=date>`](https://www.w3.org/TR/html5/forms.html#date-state-(type=date)) which is supposed to convey a [date](https://www.w3.org/TR/html5/infrastructure.html#concept-date). 

Currently `DatePicker` yields a `datetime.datetime`:

~~~
@widgets.interact(x=widgets.DatePicker())
def foo(x):
    return x
=> datetime.datetime(2017, 5, 19, 0, 0)
~~~

It would be nice to be able to have `DatePicker` work on `datetime.date` (as an option ?).

**Comment by SylvainCorlay** [comment]
The frontend language (js) does not have a notion of date, only datetime, which is what is reflected by the Python model.

**Comment by jasongrout** [comment]
In master currently, it is a date, not a datetime.

**Comment by pbugnion** [comment]
For reference, [this](https://github.com/jupyter-widgets/ipywidgets/pull/1348) is the PR that switched from a datetime to a date.

@SylvainCorlay Since the user has no ability to set the actual time value, only the date, it thought it made sense to just expose a date in Python.

**Comment by jasongrout** [comment]
Thanks @pbugnion for the reference. Closing this issue as fixed in master. Thanks for reporting it, @randomstuff!

If/when we have actual datetime pickers in the browser, I think we can look back at making a datetime variant in python.
