### ISSUE TITLE
initialize not called until render for WidgetView

### ISSUE THREAD

**Issue by finaiized** [jupyter-widgets/ipywidgets#1395]
Jupyter 5.0.0, Python 3.6.1, latest version of ipywidgets

Starting with the ipywidget cookie cutter template, I have a simple `WidgetView`:

```
var DisplayView = widgets.WidgetView.extend({
    initialize: function() {
        DisplayView.__super__.initialize.apply(this, arguments)
        console.log("initialized")
    },
    render: function() {
        console.log('rendering displayview.');
        return this;
    }
});
```
and a corresponding Python backend, with just setup code:

```
@register('Displayable')
class Displayable(Widget):
    _view_name = Unicode('DisplayView').tag(sync=True)
    _model_name = Unicode('DisplayModel').tag(sync=True)
    value = Unicode('Hello World!!!!').tag(sync=True)
```

From what I can tell, a `WidgetView` is used when there is no rendering to DOM. However, when I execute `g = Displayable()` in a cell, "initialized" is not printed to console. Even if I update the state, e.g. `g.value = 3`, initialize is still not called. In fact, I have to execute `render` (i.e. just have `g` in a cell) until it initializes and then displays "rendering displayview".

My question is, how do I initialize a non-visible Widget without displaying it? I would need to do this to, say, register model change callbacks. (I suppose this isn't a "view" anymore?)

**Comment by jasongrout** [comment]
What are you wanting to do? It may be that you don't want a view at all, and instead do your logic in a custom model itself?

In general, to get a view to display, you use the `display` function:

```
from IPython.display import display
display(my_widget_view)
```

**Comment by jasongrout** [comment]
There are at two classes of entities on the javascript side, a model and zero or more views associated with the model. When you instantiate the python widget, it automatically creates a javascript model object for the widget. When you `display` the widget, it creates a view for the model. Every time you display the widget, it creates another view associated with the model.

**Comment by finaiized** [comment]
You are absolutely right, thanks! For some reason I thought the view was a necessary part of creating a widget, even for one I didn't want to display, but everything I need to do can be done in the model.
