### ISSUE TITLE
Duplicating widgets quickly

### ISSUE THREAD

**Issue by thomasaarholt** [jupyter-widgets/ipywidgets#1408]
I've been trying to speed up creation of many (say, 100) `Button`s. Currently, creating 100 takes nearly 1 full second:

```python
%%time
for i in range(100):
    Button(description="")
CPU times: user 886 ms, sys: 35.8 ms, total: 922 ms
Wall time: 903 ms
```

My latest attempt was to create a dummybutton, `dummybutton = Button(description="")` and use pythons `copy` to create a bunch of them. Each one has a new memory position.

```python
>>> dummybutton = Button(description="")
>>> mybuttons = []
>>> for i in range(3):
        mybuttons.append(copy(dummybutton))
>>> mybuttons
[<ipywidgets.widgets.widget_button.Button at 0x108456fd0>,
 <ipywidgets.widgets.widget_button.Button at 0x108456f28>,
 <ipywidgets.widgets.widget_button.Button at 0x1084645c0>]
```

This is a lot faster:
```python
%%time
dummybutton = Button(description="")
for i in range(100):
    copy(dummybutton)
CPU times: user 81.5 ms, sys: 2.26 ms, total: 83.8 ms
Wall time: 82.1 ms
```

Unfortunately, changing the description on one button changes the description on them all. I was hoping to update just the description of each copied button from a list of names.

I tried deepcopy, but it fails:
```python
>>> deepcopy(dummybutton)
[much error]
/Users/thomas/miniconda3/envs/hs/lib/python3.5/copy.py in _deepcopy_dict(x, memo)
    241     memo[id(x)] = y
    242     for key, value in x.items():
--> 243         y[deepcopy(key, memo)] = deepcopy(value, memo)
    244     return y
    245 d[dict] = _deepcopy_dict

/Users/thomas/miniconda3/envs/hs/lib/python3.5/copy.py in deepcopy(x, memo, _nil)
    172                     reductor = getattr(x, "__reduce_ex__", None)
    173                     if reductor:
--> 174                         rv = reductor(4)
    175                     else:
    176                         reductor = getattr(x, "__reduce__", None)

TypeError: cannot serialize '_io.TextIOWrapper' object

Does anyone have a good suggestion to fix this or to create buttons faster?

**Comment by jasongrout** [comment]
Great question. I'm out for a bit, but can look at this when I get back. Or anyone else, feel free to look into this.

Profiling may help us narrow things down. Does it take that long to create generic HasTraits class instances?

**Comment by vidartf** [comment]
@thomasaarholt Currently, `copy` will create instances with the same ID (so they do not create copies on the javascript side). `copy` is also just a shallow copy, so it will likely have references to the same traits, which would be why you are seeing them all behave as one.

Regarding the speed for looped creation, my guess is that serialization for sending ( + compression?) is where the time is being spent. There is a bit of overhead when creating many widgets, as each widget is communicated individually to the browser. There might be some improvements with Notebook master, as it doesn't use compression by default.

Another optimization could be to create your own widget `ButtonArray`, which just has a list/tuple of descriptions (the `on_click` callback could maybe include the description of the button pushed?). This way only one widget is synced across to the browser side. This would however require some JS code...

**Comment by jasongrout** [comment]
All this aside - wow, 100 buttons is kind of a lot. Perhaps another way to get user input would be appropriate?

**Comment by thomasaarholt** [comment]
Never underestimate a poor coder with good intentions.

Yes, you are quite right. I was trying to find a quick way of making a clickable list for a file browser. Whilst buttons are "physically" quite large, their footprint should be low, so I was a bit surprised to see it take so long.

I was trying to avoid going the route of creating a new widget, although @rksabelund's [suggestion](https://gitter.im/jupyter-widgets/Lobby?at=5935e9376549436c7d1ca4cf) was a good one.

**Comment by jasongrout** [comment]
Closing as resolved, but please re-open or comment if you'd like to pursue this further.

**Comment by fran-pena** [comment]
Hi, 

I also find interesting to copy an existing widget. Is there any solution for that?

My case would be simpler than @thomasaarholt one, just to create a copy of an existing widget:
```python
a = wg.IntSlider(continuous_update=False)
a.observe(obs_int)
b = a.copy()
```
In the previous case, `copy` must create a new `IntSlider` with same properties that `a` has, i.e., preserving `continuous_update=False` and `.observe(obs_int)`. 
Thanks.
