### ISSUE TITLE
Tries to create view for Link

### ISSUE THREAD

**Issue by vidartf** [jupyter-widgets/ipywidgets#1412]
If you have a notebook cell that ends in a `ipywidgets.jslink(...)` statement, master gives various console errors. Doing some minor debugging, it seems that it tries to look up the class `''` (empty string) in `@jupyter-widgets/controls` (the view name for `Link` is empty string).

**Comment by jasongrout** [comment]
Perhaps we should have the default view in WidgetModel be `WidgetView`, which does nothing by default.

**Comment by jasongrout** [comment]
> Perhaps we should have the default view in WidgetModel be WidgetView, which does nothing by default.

(I think this is what we did before...)

**Comment by vidartf** [comment]
It's a little confusing to me: In `Widget._ipython_display_()`, there is a conditional `if self._view_name is not None`. However, it also defines the default view name as empty string. Could not `Widget._ipython_display_()` simply check for empty string as well, or the default value be `None`?

**Comment by vidartf** [comment]
Ref by git-blame: https://github.com/jupyter-widgets/ipywidgets/commit/5e70a60f1fb411323e3cb77e05d0f59b388814f7

**Comment by vidartf** [comment]
And commit that changes to empty string: https://github.com/jupyter-widgets/ipywidgets/commit/f3de6ccf2e30d8c508bf0d4fe38253c840ff62f4

**Comment by vidartf** [comment]
If this is simply a regression, I'd be happy to attempt a fix + test.

**Comment by jasongrout** [comment]
It is a regression. Thanks for looking up the references.
