### ISSUE TITLE
Move JupyterLab package to @jupyter-widgets/jupyterlab-manager

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#1414]
Or maybe `@jupyter-widgets/jupyterlabmanager`?

**Comment by blink1073** [comment]
I prefer the first, fwiw.

**Comment by blink1073** [comment]
Already done?

**Comment by jasongrout** [comment]
Yep, thanks for pointing this out. The package is now `@jupyter-widgets/jupyterlab-manager`
