### ISSUE TITLE
update cookiecutter

### ISSUE THREAD

**Issue by artur-trzesiok** [jupyter-widgets/ipywidgets#1415]
Hi,

Can you update your cookiecutter for version 7.0.0? I want to use new ipywidgets but i don't know what i shut set here instead of "jupyter-js-widgets":

https://github.com/jupyter-widgets/widget-cookiecutter/blob/master/%7B%7Bcookiecutter.github_project_name%7D%7D/js/src/extension.js

I try:
`'jupyter-widgets-controls': 'nbextensions/jupyter-widgets-controls/extension'`

But i get:
`Error: Cannot find module "jupyter-js-widgets/css/widgets.css"`

**Comment by jasongrout** [comment]
ping @SylvainCorlay

**Comment by jasongrout** [comment]
Done in https://github.com/jupyter-widgets/widget-cookiecutter/pull/23

We'll need to update to the final version after release.
