### ISSUE TITLE
Routing all 'output' of cell

### ISSUE THREAD

**Issue by finaiized** [jupyter-widgets/ipywidgets#1420]
Jupyter 5.0.0, Python 3.6.1, latest version of ipywidgets

I'm trying to do something a bit weird, as a result of having the constraint of not being able modify some existing Python code and instead building a Jupyter widget "wrapper" that calls it.

Basically, I have something that looks like this:

```
class Display():
    def customDisplay(self, *args):
        print(*args)

class UnmodifiableClass(Display):
    # Functions will call customDisplay here
    pass

class JupyterWidget(Widget):
    # Some _module and _view properties here...
    def __init__(self):
        self.unmodifiableClass = UnmodifiableClass() # Wraps this class
```

When I run this (by creating a `JupyterWidget()` and displaying it), all print statements naturally get directed to the output area. This is basically true for _all_ print output that was kicked off in the cell. What I want though, is to get all these either back to the corresponding `JupyterWidgetModel` in the frontend or to `JupyterWidget` for further processing. That is, imagine I replace `print(*args)` with some other function that emits all its output to the `JupyterWidget` that created it (or, sufficiently, everything in that cell). I can't directly use `self.send` in `customDisplay`, because `self` may not be a Jupyter instance (and besides, I want the `JupyterWidget` instance to ultimately receive all these outputs). Monkey-patching `self.unmodifiableClass.display` with a custom display function also doesn't work, because if `UnmodifiableClass` creates other instances, those `customDisplay` aren't overridden as well.

Hopefully I've explained this sufficiently!

**Comment by pbugnion** [comment]
Can you change the code in the `Display` class? 

Assuming that you can, I presume you want to act on the outputs in 'real time' (rather than just buffering them in some list in `Display`)? If so, you could use a traitlet in `Display` and observe it to note changes?:

```python
class Display(HasTraits):
    outputs = List(Unicode())
    
    def custom_display(self, output):
        new_outputs = self.outputs[:] + [output]
        self.outputs = new_outputs
        
    @observe('outputs')
    def _observe_outputs(self, change):
        print(change)

            
class UnmodifiableClass(Display):
    # Functions will call customDisplay here
    def say_hello(self, name):
        self.custom_display('hello {}'.format(name))

        
class JupyterWidget(widgets.Widget):
    # Some _module and _view properties here...
    def __init__(self):
        self.unmodifiable = UnmodifiableClass() # Wraps this class
        self.outputs = self.unmodifiable.outputs
    
    def activate_widget(self):
        self.unmodifiable.say_hello('Bob')
        self.unmodifiable.say_hello('Bill')

j = JupyterWidget()
j.activate_widget()
```

**Comment by vidartf** [comment]
Maybe what you want is `IPython.utils.capture.capture_output` ?

**Comment by finaiized** [comment]
@pbugnion: Yes, I can modify `Display`. That doesn't do exactly what I want, because if `UnmodifiableClass` creates and calls another `Display` subclass, it's `custom_display` output is not captured in the Widget (I would need not only `self.unmodifiable.observe(self._observe, ['outputs'])` in the Widget, but also observe `self.unmodifiable.someOtherInstanceItCreates.observe(...)`, which I don't necessarily know the name of). I definitely want realtime output (so `capture_output` is out of the bag).

I don't think this is a Jupyter problem, just a side effect of some limitations I'm imposing on myself that I need to rethink. For that reason, I'm closing this. A current workaround is to run `UnmodifiableClass` methods in a thread, which, using the thread ID, can identify all calls to `self.custom_display` from any `Display` instance created from that method. Not nice at all, I'll admit.
