### ISSUE TITLE
integer/float text boxes turn negative sign to 0

### ISSUE THREAD

**Issue by mwcraig** [jupyter-widgets/ipywidgets#1426]
The behavior shown below occurs in all of the int/float text widgets: `FloatText`, `BoundedFloatText`, `IntText`, `BoundedIntText`.

The first time a negative sign is entered in the widget it is almost immediately converted to a zero. Subsequently when a negative sign is enters it sticks around.

![bad-float-text](https://user-images.githubusercontent.com/1147167/27145787-8f0c7cac-50fc-11e7-9947-7805e0ad4b03.gif)

**Comment by jasongrout** [comment]
Confirmed. It doesn't happen when the value is not initialized as well.
