### ISSUE TITLE
Inconsistent keys in Slider classes

### ISSUE THREAD

**Issue by mwcraig** [jupyter-widgets/ipywidgets#1432]
The table below shows all of the keys (except `['layout', 'style', 'msg_throttle']` which are common to all widgets) for the `Slider` widget classes. To be explicit, the list of keys was generated by the `.keys` property of an instance of each class. 

Most of it is not surprising (e.g. no min/max for `SelectionSlider`) but a few things were:

+ There is a `readout_format` for all the numerical sliders except `IntRangeSlider`,
+ There is no `value` key for `SelectionSlider` or `SelectionRangeSlider`.
+ `options` is not a key for `SelectionSlider` or `SelectionRangeSlider`.

Both `value` and `options` are *attributes* of  `SelectionSlider` and `SelectionRangeSlider`. It may not be that important that they are not keys but wanted to point it out.

| Property           | Int | Float | IntRange | FloatRange | Selection | SelectionRange |
|--------------------|-----------|-------------|----------------|------------------|-----------------|----------------------|
| continuous\_update | X         | X           | X              | X                | X               | X                    |
| description        | X         | X           | X              | X                | X               | X                    |
| disabled           | X         | X           | X              | X                | X               | X                    |
| index              |           |             |                |                  | X               | X                    |
| max                | X         | X           | X              | X                |                 |                      |
| min                | X         | X           | X              | X                |                 |                      |
| orientation        | X         | X           | X              | X                | X               | X                    |
| readout            | X         | X           | X              | X                | X               | X                    |
| readout\_format    | X         | X           |                | X                |                 |                      |
| step               | X         | X           | X              | X                |                 |                      |
| value              | X         | X           | X              | X                |                 |                      |

**Comment by jasongrout** [comment]
`.keys` only lists synced attributes. `.value` and `.options` of selection widgets are not synced since the values may be arbitrary python objects which cannot be synced.

**Comment by jasongrout** [comment]
It does look like IntRange not having readout_format is an oversight. However, there are ramifications, since we do allow someone to type in a range and try to parse it - if the readout format is something that isn't easily parsed as an integer, then there will be a mismatch between what is displayed and what can be typed.
