### ISSUE TITLE
Widgets missing the `value` key

### ISSUE THREAD

**Issue by mwcraig** [jupyter-widgets/ipywidgets#1433]
In addition to the slider widgets mentioned in #1432, these widgets do not have a `value` key but do have an `index` key: 

+ Dropdown
+ RadioButtons
+ Select
+ ToggleButtons
+ SelectMultiple
+ SelectionSlider
+ SelectionRangeSlider

It may be this is deliberate; if so, I'll update the appropriate places in the tutorial notebooks.

**Comment by jasongrout** [comment]
The `.keys` attribute only lists synced traits. Any selection widget syncs the *index* of the selection, but they (should) also have a value traitlet that is set to the value selected.

**Comment by jasongrout** [comment]
The value is not synced for selection widgets since it may be an arbitrary python object that cannot be represented as JSON. That is a deliberate design decision.

**Comment by jasongrout** [comment]
However, you can still listen for changes on the `.value` trait, set the `.value` trait, etc.

**Comment by mwcraig** [comment]
Makes sense; thanks for the explanation!
