### ISSUE TITLE
SelectMultiple dont show all selected value

### ISSUE THREAD

**Issue by Mblp4ur** [jupyter-widgets/ipywidgets#1434]
```
w = widgets.SelectMultiple(
    options=['Apples', 'Oranges', 'Pears'],
    value=['Oranges','Apples'],
    #rows=10,
    description='Fruits',
    disabled=False
)
```
![bugwidget](https://user-images.githubusercontent.com/10047169/27321934-e3128600-55a4-11e7-8535-bd95be621881.png)

jupyter run python2.7
example code python3
ipywidgets version 7.0.0a4
 widgetsnbextension Version: 3.0.0a7
notebook Version: 5.0.0
jupyter Version: 1.0.0

ipywidgets version 6.0.0
its SelectMultiple work

**Comment by jasongrout** [comment]
I've reproduced this in master. Thanks for filing it.
