### ISSUE TITLE
communication between python and js

### ISSUE THREAD

**Issue by rolandjitsu** [jupyter-widgets/ipywidgets#1436]
I have a question about custom widgets. Consider the following scenario:
```python
some_widget = SomeWidget()
// .do_something() should actually make a call to some JS function
some_widget.do_something();
```

My question is, how do I actually call the JS function from the python function? Is it that I can only send messages?

And what happens when the JS fn has a callback which I want to print in `.do_something()`?

I suppose with the pub/sub model you would do:
```python
def do_something(self):
    def handle_msg():
        print('test')
    this.on_msg(handle_msg) # How do I ensure this only happens once? (one time subscription)
    this.send('some_event_name')
```

**Comment by jasongrout** [comment]
Was that enough of an answer to get you started?

**Comment by rolandjitsu** [comment]
@jasongrout sorry, yes, I think it should be enough. I just wanted confirmation that the only way to do it is through messaging.

As for python blocking, I guess I just have to make sure to not add very resource demanding logic in the handler. Thanks for the advice 💯
