### ISSUE TITLE
jupyterlab  dont work nbwidgets

### ISSUE THREAD

**Issue by Mblp4ur** [jupyter-widgets/ipywidgets#1438]
```
Widget Javascript not detected.  It may not be installed or enabled properly.
Unable to render data
```

install :`jupyter labextension install @jupyterlab/nbwidgets`

```
jupyter lab --version
0.24.1
jupyter notebook --version
5.0.0
jupyter --version
4.3.0
jupyterlab-nbwidgets-0.21.0
```

**Comment by jasongrout** [comment]
It looks like your ipywidgets installation is old. Is it 6.0? It should be the latest alpha.

**Comment by Mblp4ur** [comment]
```
pip show ipywidgets
Name: ipywidgets
Version: 7.0.0a4
```

**Comment by jasongrout** [comment]
This message: "Widget Javascript not detected.  It may not be installed or enabled properly." comes from ipywidgets 6. Can you check exactly what version is being used?

```
import ipywidgets
ipywidgets.__version__
ipywidgets.__file__
```

**Comment by Mblp4ur** [comment]
![widg](https://user-images.githubusercontent.com/10047169/27391453-ad3bb318-56ac-11e7-89b9-8468716e23c3.png)
How can I switch?

**Comment by jasongrout** [comment]
I'm not sure how you have your python set up, but it may be enough to just `pip uninstall ipywidgets` several times until it says none is installed. Then install the alpha version again.

**Comment by jasongrout** [comment]
@Mblp4ur - did you get this working?

**Comment by Mblp4ur** [comment]
I can not force to use ipywidgets 7.0

**Comment by jasongrout** [comment]
Are you still working on trying to run the 7.0 alpha?

It looks like your ipywidgets 6.0 is installed at the system level (`/user/local/lib/...`). Do you have write access to `/user/local/lib` to uninstall ipywidgets 6?

**Comment by Mblp4ur** [comment]
i have write access to /user/local/lib to uninstall ipywidgets 6

**Comment by jasongrout** [comment]
Would you still like help working through this?

**Comment by Mblp4ur** [comment]
Can i ask you
Write me the steps that need to be done

**Comment by jasongrout** [comment]
You'll need to uninstall ipywidgets 6. `pip uninstall ipywidgets` may be enough, or you may need to repeat that several times. Then install the alpha with `pip install --pre ipywidgets`.

**Comment by Mblp4ur** [comment]
Thanks it works

**Comment by jasongrout** [comment]
Great!

**Comment by jzf2101** [comment]
@jasongrout I get these errors when I try to install ipywidgets with jupyterlab 0.25.1
```
"@jupyterlab/nbwidgets@0.21.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
Required	Actual	Package
^0.8.1  	^0.7.0	@jupyterlab/application
^0.8.1  	^0.7.0	@jupyterlab/notebook
^0.8.1  	^0.7.0	@jupyterlab/rendermime

"@jupyter-widgets/jupyterlab-manager@0.23.3" is not compatible with the current JupyterLab
Conflicting Dependencies:
Required	Actual	Package
^0.8.1  	^0.7.0	@jupyterlab/application
^0.8.1  	^0.7.0	@jupyterlab/notebook
^0.8.1  	^0.7.0	@jupyterlab/rendermime
```

**Comment by jasongrout** [comment]
As the message says, we're not compatible with 0.25. we welcome prs to
update to 0.25. We're compatible with 0.24.1 now
