### ISSUE TITLE
readout_format not working in FloatRangeSlider

### ISSUE THREAD

**Issue by afonit** [jupyter-widgets/ipywidgets#1440]
ipywidgets 6.0

in the notebook:
```python
widgets.FloatRangeSlider(value=[-0.020, 0.020], min=-0.100, max=0.100, step=0.001, readout_format=".2%")
```
Produces:
-0.02 – 0.02

but using FloatSlider produces the expected output:
```python
widgets.FloatSlider(value=-0.02, min=-0.20, max=0.0, step=0.001, readout_format=".2%")
```
produces the expected formatting:
-2.00%

**Comment by jasongrout** [comment]
This works in master now. Thanks for reporting!

<img width="984" alt="screen shot 2017-06-22 at 6 22 09 am" src="https://user-images.githubusercontent.com/192614/27429475-31c61b1c-5713-11e7-9075-e343fc3a0fa2.png">
