### ISSUE TITLE
package names

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#1447]
Let's clean up the package names to be consistent:

Proposal:

* `jupyter-widgets-schema` -> `@jupyter-widgets/schema`
* `@jupyter-widgets/htmlmanager` -> `@jupyter-widgets/html-manager`
* `widgetsnbextension` is a private package, but for consistency we could call it `@jupyter-widgets/notebook-manager`
* Should we move the jupyterlab manager into widgets? `@jupyterlab/nbwidgets` -> `@jupyter-widgets/jupyterlab-manager`?

**Comment by blink1073** [comment]
Sounds good to me.

**Comment by jasongrout** [comment]
Thanks Steve. CC @pbugnion, @maartenbreddels, @vidartf, @SylvainCorlay as well.

**Comment by pbugnion** [comment]
Sounds good.
