### ISSUE TITLE
Output widget module

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#1449]
Right now, the browser Output widget model/view is always patched into the controls module by hand by each manager. This is awkward. The only reason we did this is so that there would be one javascript module name for the entire ipywidgets python package. However, now we don't have that anyway with the base and controls module.

How about we make a new package just for the output widget: `@jupyter-widgets/output` or something. Then each manager just has to look for that specific package and substitute its implementation in, rather than looking for the controls package and then checking the module name. This also lets us treat the controls package like any other package, and not *have* to patch something in.

**Comment by jasongrout** [comment]
Furthermore, the `@jupyter-widgets/output` package could be an actual package with an abstract implementation of the Output widget, or at least the typings/interface for one, so to make a new output widget you'd inherit from that base class.

**Comment by jasongrout** [comment]
Related to #1447.

**Comment by pbugnion** [comment]
I think that makes sense -- I came to similar conclusions when working on the embed bundle.

**Comment by pbugnion** [comment]
To clarify, you were thinking that the specific implementations of the output widget would remain in their respective packages (e.g. the implementation for notebooks would remain in `widgetsnbextension`? 

The only visible change would be the `widget_module` attribute in the state would now be `@jupyter-widgets/outputs`?

**Comment by jasongrout** [comment]
I was thinking that essentially the `_view_module_` and `_model_module_` would both be this new `@jupyter-widgets/output` module. And yes, I was thinking that each manager would still have their own implementation of at least the view, and possibly the model as well, which may inherit from some abstract base class in the output package.

**Comment by jasongrout** [comment]
Fixed by #1456.
