### ISSUE TITLE
Widgets don't work in nbviewer.

### ISSUE THREAD

**Issue by maver1ck** [jupyter-widgets/ipywidgets#1458]
I read ipywidgets 6.0 announcement and there is a link to sample notebook with widgets.
Is it running correctly ?
http://nbviewer.jupyter.org/github/ipython/ipywidgets/blob/master/docs/source/examples/Widget%20List.ipynb

I don't see any widgets inside.

![image](https://user-images.githubusercontent.com/4006010/27587780-fcea774e-5b45-11e7-9c9d-018551eb1adf.png)

**Comment by jasongrout** [comment]
Thanks. The correct link for the 6.0 docs should be the 6.0 version of the page: http://nbviewer.jupyter.org/github/ipython/ipywidgets/blob/6.0.0/docs/source/examples/Widget%20List.ipynb

**Comment by jasongrout** [comment]
(The reason the widgets don't display on master is that we didn't save the widget state to the master document, since it introduces a lot of churn to the file. We save the widget state before release. So we should fix the link in the announcement.) Thanks for pointing this out!

**Comment by jasongrout** [comment]
I just fixed the blog post to point to the 6.0 tag of the repo, so it should work now. Thanks again for pointing this out!
