### ISSUE TITLE
ipywidgets 6 problem with Tabs and Buttons

### ISSUE THREAD

**Issue by martin-hunt** [jupyter-widgets/ipywidgets#1459]
I am unable to upgrade to ipywidgets 6 because the the Tab widgets is broken.  It seems fixed in 7.0.0a4.  Can the fix be backported to 6.0?

The problem is including a Button or ToggleButton as a child in a Tab causes it to appear in all tabs.

![selection_037](https://user-images.githubusercontent.com/6372515/27606489-8dbad342-5b4e-11e7-8640-b096d29e9ca7.png)

**Comment by jasongrout** [comment]
Thanks for reporting this. We're close to the 7.0 release - would it satisfy your usecase to upgrade to a soon-to-be-released 7?

**Comment by martin-hunt** [comment]
If it is not an easy fix, then we can wait for 7.0.  I was having some
issues with it earlier.  I'll test the latest release.

**Comment by jasongrout** [comment]
Turns out that the underlying problem is in 7.0 as well.
