### ISSUE TITLE
Fix web3 and web-tmpnb examples

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#1473]
Currently these examples don't work because we don't register a renderer when we execute the code. We may just move them over to using the html manager (in which case, we should copy some of the changes we've been making in their widget manager back to the html manager, such as using async in loadClass, etc.)

**Comment by pbugnion** [comment]
I was planning on tackling the web3 example. As far as I can tell, this involves:

 - listening for iopub messages comming back from `kernel.requestExecute` with, e.g. the `onIOPub` handler. 
 - extract the `data` field from the message
 - pass the `data` object to a renderer like the the `WidgetRenderer` defined in the html-manager.

Am I on the right track?

**Comment by jasongrout** [comment]
Yes, something like that. Or even better, you can use the outputarea from the jupyterlab project so the example can render more than just widgets.

**Comment by jasongrout** [comment]
(but they are also rewriting the output area in jupyterlab right now...)

The other thing you could do is use the rendermime package from jupyterlab to render more than just widgets.

**Comment by jasongrout** [comment]
@pbugnion - any update on this? We're narrowing down on this being one of the last issues open, and I can try tackling it as well.

**Comment by jasongrout** [comment]
Actually, I think we ought to wait on the current jupyterlab refactor of its output area, and then use it. I *think* the output area part of the refactor may be done, but it may still be in flux.

@sccolbert - do you have any advice about us using the jlab output area for a single output area fed by some code execution we do in an html page? We're trying to update some examples showing how widgets can be embedded in an html page.

**Comment by jasongrout** [comment]
I think this issue shouldn't be a blocker for a release. I think we should wait for the updated output widget coming out of the jlab project, and if necessary for a release, remove the examples and add them later.

**Comment by pbugnion** [comment]
@jasongrout Sorry -- I missed your comments. Happy to push this to a future release if need be. I have only done minimal work on this (mostly just copying bits out of the html-manager to try and make it work).

**Comment by jasongrout** [comment]
Since this is basically the last blocker, and work is still progressing on the JLab output area, and the code will change fairly significantly to use the new output area widgets, I'm going to remove these examples for now, and we can pull what we need out of history when we implement them using the new JLab output area.

**Comment by jasongrout** [comment]
Turns out that it just took a little more work to get the examples *minimally* working (basically on the level they were working before). We'll take another look at this after the new jlab output area, but consider it fixed as well as it is going to be now.
