### ISSUE TITLE
How to remove widget metadata from a notebook?

### ISSUE THREAD

**Issue by ceball** [jupyter-widgets/ipywidgets#1477]
I'm using ipywidgets 6.0 and jupyter notebook 5.0. Once I've chosen "Widgets > Save Notebook With Widgets", is there anything like "Widgets > Save Notebook Without Widgets"?

**Comment by jasongrout** [comment]
Good question. We've added a clear widget state command in the 7.0 alpha versions we've posted. Can you upgrade to the alpha? `pip install --pre ipywidgets`

Alternatively, you can delete the widget metadata from the notebook JSON file manually.

**Comment by jasongrout** [comment]
(The clear widget state menu item was added in https://github.com/jupyter-widgets/ipywidgets/pull/1370)
