### ISSUE TITLE
Redirect ReadTheDocs default URL to the stable version

### ISSUE THREAD

**Issue by JoshuaC3** [jupyter-widgets/ipywidgets#1479]
The documentation for this used to be really helpful and quick to understand when it was hosted on readthedocs. Now it seems to have been changed to (or changes made to) http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html the widgets no longer render.

**Comment by jasongrout** [comment]
Thanks. Please use the latest stable docs to see the rendered widget: http://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html

**Comment by jasongrout** [comment]
To render widgets, we need to save the widget state to the document. This causes quite a bit of churn while we are in development, so we only  save this state before releasing a beta or final version.

**Comment by JoshuaC3** [comment]
A slight oversite on my behalf - however all Google searches lead me to http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html and not stable. I am not sure why this was the case.

![image](https://user-images.githubusercontent.com/11645712/27865112-35a7fee6-6189-11e7-9226-21d80baaf1d4.png)

This might be useful to know if more people cannot find the stable docs. Anyway, thanks for the explanation and the link :)

**Comment by vidartf** [comment]
Yes, if you go to https://ipywidgets.readthedocs.io/, it redirects to the latest docs. The default should be set to point to stable.

**Comment by JoshuaC3** [comment]
Yes. I get this also. Maybe I will re-open this.

**Comment by jasongrout** [comment]
I've modified the title to indicate what needs to be done.

**Comment by jasongrout** [comment]
@SylvainCorlay - can you redirect the default readthedocs URL to the stable version?

**Comment by jasongrout** [comment]
@SylvainCorlay - can you do this before the tutorial?

**Comment by jasongrout** [comment]
Done now, with @willingc's help! http://ipywidgets.readthedocs.io redirects to the stable version documentation.

**Comment by jasongrout** [comment]
(I don't know what we can do about the /latest docs showing up in the google search first, but hopefully the default pointing to stable will over time make the google rank the stable results higher).

**Comment by JoshuaC3** [comment]
Unfortunately, I have noticed this with other docs as well. Count be a wider issue!

**Comment by jasongrout** [comment]
> Unfortunately, I have noticed this with other docs as well. Count be a wider issue!

I think it's the ReadTheDocs default to point to the master documentation. Would you mind posting to the [Jupyter mailing list](https://groups.google.com/forum/#!forum/jupyter) about this? You're right that it might be something we consider at a project-wide level.

Thanks again!

**Comment by JoshuaC3** [comment]
@jasongrout posted [here](https://groups.google.com/forum/#!topic/jupyter/x9QNC_-XF1U). Hopefully this is what you were looking for.
