### ISSUE TITLE
Widget not catching the middle-click pasted value

### ISSUE THREAD

**Issue by antonelepfl** [jupyter-widgets/ipywidgets#1485]
Hello, I'm having an issue with the middle-click paste in linux. (The Ctrl+V works fine).
The problem is that I'm trying to get the value of a widget but if I paste with middle-click the value is never set to the widget.

I have generated a jupyter notebook to test: https://tmp60.tmpnb.org/user/ggp4k2EeGq3r/notebooks/Middle-click%20paste%20issue.ipynb

Just in case I attached the code and a screenshot.
[middle_click_issue.txt](https://github.com/ipython/ipython/files/1127856/middle_click_issue.txt)
![screen shot 2017-07-06 at 14 44 05](https://user-images.githubusercontent.com/24406041/27911723-5810991c-625a-11e7-8696-710d5a9839e1.png)

Thank you in advance
Stefano

**Comment by jasongrout** [comment]
Is this the same issue as in #1401?

**Comment by antonelepfl** [comment]
Yes, I tried the paste with the mouse and I have the same behaviour as with the middle-click.

**Comment by jasongrout** [comment]
Thanks. Let's join the conversation over there and close this issue as a duplicate.
