### ISSUE TITLE
Selection containers (Tab, accordion) should allow a selected index of None for consistency

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#1493]
This would make it consistent with the selection widgets.

**Comment by pbugnion** [comment]
The selection widgets explicitly disallow out of range indices. 

Do we want to do that for the selection containers as well? It breaks backwards compatibility (I'm not sure how much user code relies on being able to set / get -1 for `selected_index`), but it would be more consistent and ensures that there's only one way to set the container as having nothing selected.

**Comment by jasongrout** [comment]
Fixed by #1495.

**Comment by SylvainCorlay** [comment]
@jasongrout I wonder if the default should not also be `None`. At the moment, for some reason, the default is 0.

**Comment by jasongrout** [comment]
I think that would be confusing in most cases. Let's carry on discussion on #1822, though.
