### ISSUE TITLE
Fix interactive plot flicker via own layout

### ISSUE THREAD

**Issue by JazzTap** [jupyter-widgets/ipywidgets#1494]
# Status

- [x] Add the following tip to the docs
- [ ] Check to make sure the output height is being handled intelligently to prevent flickering (see below)

---
# Original issue

Been hitting a bugaboo (esp. in sage) where cells don't stay one height when their plot vanishes for recomputation. So everything below in the notebook bounces around.

But the interactive is a layout, so we can use CSS to fix height at an appropriate value (currently chosen manually) for a given matplotlib call.
```
interactive_plot = interactive(f, m=(-2.0, 2.0), b=(-3, 3, 0.5))
interactive_plot.layout.height = '350px'
interactive_plot
```
in the context of
```
%matplotlib inline
from ipywidgets import interactive
import matplotlib.pyplot as plt
import numpy as np

def f(m, b):
    plt.figure(2)
    x = np.linspace(-10, 10, num=1000)
    plt.plot(x, m * x + b)
    plt.ylim(-5, 5)
    plt.show()
```

**Comment by jasongrout** [comment]
Thanks for posting this example code!

I checked into it. Here is the code that tries to intelligently handle updates and heights: https://github.com/jupyter/notebook/blob/971e425c72a66068b3b0b8069f1c06ab7c627e1a/notebook/static/notebook/js/outputarea.js#L969. We should make sure we're triggering that code path.

**Comment by jasongrout** [comment]
Bumping the checking on triggering the update height codepath to 7.0 - the flicker is really quite noticeable.

**Comment by jasongrout** [comment]
Interestingly, when I look now, it seems that that code path is triggered, and I don't see any flickering.

So I'll put the note in the docs that you mention above and consider this fixed. If we can figure out how to reproduce the flickering better, we can take another look at it.
