### ISSUE TITLE
Links seem to be broken on overview page  ipywidgets/docs/source/examples/Index.ipynb 

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [jupyter-widgets/ipywidgets#1499]

**Comment by jasongrout** [comment]
Can you share where they are broken? I just checked opening the index.html in the Jupyter notebook, and all of the links worked fine.

**Comment by jasongrout** [comment]
@freifrauvonbleifrei - closing because we checked and can't seem to find where the broken links are. If you share a URL where you see them broken, or have other comments, feel free to reopen this.
