### ISSUE TITLE
IPyWidgets + JupyterLab 0.25.2

### ISSUE THREAD

**Issue by OliverEvans96** [jupyter-widgets/ipywidgets#1504]
# Installation

Installing with a blank conda env as follows:
```
conda create --name jlab-widgets python
source activate jlab-widgets
pip install jupyterlab
pip install --pre ipwidgets
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```
This shows the following versions:
```
(jlab-widgets) oliver@oliver-arch:~ % pip show jupyterlab
Name: jupyterlab
Version: 0.25.2
Summary: An alpha preview of the JupyterLab notebook server extension.
Home-page: http://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.com
License: BSD
Location: /home/oliver/local/miniconda3/envs/jlab-widgets/lib/python3.6/site-packages
Requires: notebook, jupyterlab-launcher
(jlab-widgets) oliver@oliver-arch:~ % 
(jlab-widgets) oliver@oliver-arch:~ % jupyter labextension install @jupyter-widgets/jupyterlab-manager
(jlab-widgets) oliver@oliver-arch:~ % pip show jupyterlab ipywidgets
Name: jupyterlab
Version: 0.25.2
Summary: An alpha preview of the JupyterLab notebook server extension.
Home-page: http://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.com
License: BSD
Location: /home/oliver/local/miniconda3/envs/jlab-widgets/lib/python3.6/site-packages
Requires: notebook, jupyterlab-launcher
---
Name: ipywidgets
Version: 7.0.0a11
Summary: IPython HTML widgets for Jupyter
Home-page: http://ipython.org
Author: IPython Development Team
Author-email: ipython-dev@scipy.org
License: BSD
Location: /home/oliver/local/miniconda3/envs/jlab-widgets/lib/python3.6/site-packages
Requires: nbformat, ipykernel, widgetsnbextension, traitlets, ipython
```
and
```
(jlab-widgets) oliver@oliver-arch:~ % jupyter labextension list
JupyterLab v0.25.2
Known labextensions:
   app dir: /home/oliver/local/miniconda3/envs/jlab-widgets/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager  enabled  OK
```

# Not working

Trying the following in Jupyter Lab (after `from ipywidgets import *`):
```
In [1]:
interact(lambda x: x, x=True)

True
Out[1]:
<function __main__.<lambda>>
```
produces no widget, and the following js console errors:
```
manager-base.js:258 Could not instantiate widget
(anonymous) @ manager-base.js:258
step @ manager-base.js:34
(anonymous) @ manager-base.js:15
rejected @ manager-base.js:7
utils.js:84 Error: Could not create a model.
    at promiseRejection (utils.js:84)
    at <anonymous>
promiseRejection @ utils.js:84
utils.js:84 Error: Could not process update msg for model id: ab5ef35ea7ff4671b23058eba12f4898
    at promiseRejection (utils.js:84)
    at <anonymous>
promiseRejection @ utils.js:84
utils.js:84 Error: Could not create view
    at promiseRejection (utils.js:84)
    at <anonymous>
promiseRejection @ utils.js:84
lab:1 Uncaught (in promise) Module @jupyter-widgets/output, semver range 3.0.0 is not registered as a widget module
lab:1 Uncaught (in promise) Module @jupyter-widgets/output, semver range 3.0.0 is not registered as a widget module
```

Also,
```
In [6]:
o = Output()
o

Error displaying widget
```
produces no further output and the following js console errors (similar to before):
```
manager-base.js:258 Could not instantiate widget
(anonymous) @ manager-base.js:258
step @ manager-base.js:34
(anonymous) @ manager-base.js:15
rejected @ manager-base.js:7
utils.js:84 Error: Could not create a model.
    at promiseRejection (utils.js:84)
    at <anonymous>
promiseRejection @ utils.js:84
lab:1 Uncaught (in promise) Module @jupyter-widgets/output, semver range 3.0.0 is not registered as a widget module
```

# Mostly working

Some things are working fine. For example,
```
 [7]:
s = IntSlider()
l = []
def f(change):
    l.append(change['new'])
s.observe(f, names='value')
s

--o-------- 44 (IntSlider widget)

In [10]:
l
Out[10]:
[3, 9, 37, 57, 56, 31, 12, 11, 23, 42, 52, 51, 37, 34, 38, 44]
```
appends to the list upon sliding as expected, however it still produces similar errors:
```

utils.js:84 Error: Could not create child view
    at promiseRejection (utils.js:84)
    at <anonymous>
promiseRejection @ utils.js:84
utils.js:84 Error: Could not add styleView to DOMWidgetView
    at promiseRejection (utils.js:84)
    at <anonymous>
promiseRejection @ utils.js:84
lab:1 Uncaught (in promise) Class StyleView not found in module @jupyter-widgets/base
lab:1 Uncaught (in promise) Class StyleView not found in module @jupyter-widgets/base
```
---

Thanks!
Oliver

**Comment by jasongrout** [comment]
#1506 fixes the style issue. Thanks again for pointing these out!

I just released these fixes. You should be able to install the new version with `jupyter labextension install @jupyter-widgets/jpuyterlab-manager`

**Comment by OliverEvans96** [comment]
You rock! Thank you!

Everything seems to work without errors in the notebook now. Although widgets don't seem to work in the console. I'm not sure if this is another minor fix or a major issue.

Creating any widget in the console (even without interact, just `IntSlider()`) produces the following js error:
```
default.js:1474 Uncaught (in promise) Error: Object 'jupyter.widget' not found in registry
    at default.js:1474
    at Promise (<anonymous>)
    at Object.loadObject (default.js:1453)
    at DefaultKernel._handleCommOpen (default.js:905)
    at DefaultKernel._onWSMessage (default.js:738)
    at WebSocket._ws.onmessage (default.js:664)
```
and no widget is produced.

**Comment by jasongrout** [comment]
yes, they don't work in the console.

**Comment by jasongrout** [comment]
(We're only registering widgets in the notebook)

**Comment by hainm** [comment]
> I just released these fixes. You should be able to install the new version with jupyter labextension install @jupyter-widgets/jpuyterlab-manager

@jasongrout  I don't think that works.

```
$ jupyter labextension install @jupyter-widgets/jpuyterlab-manager
> npm pack @jupyter-widgets/jpuyterlab-manager
npm ERR! code E404
npm ERR! 404 Not found : @jupyter-widgets/jpuyterlab-manager
npm ERR! 404 
npm ERR! 404  '@jupyter-widgets/jpuyterlab-manager' is not in the npm registry.
```

**Comment by hainm** [comment]
uhm, turns out you made a typos. :D

**Comment by jasongrout** [comment]
> uhm, turns out you made a typos. :D

You're right! Sorry. I've corrected the comment above so it doesn't catch other people.

**Comment by hainm** [comment]
hi @jasongrout, I got similar error after trying lab with `nglview` (master).

Any idea how? (googled pointed me to this issue too):

<img width="1280" alt="screen shot 2017-07-19 at 11 43 10 pm" src="https://user-images.githubusercontent.com/4451957/28399603-13a2dbaa-6cdc-11e7-987c-5ac2517411c5.png">

**Comment by jasongrout** [comment]
It looks like your `_model_module_version` or `_view_module_version` is not set, since it doesn't appear in the error message.

**Comment by hainm** [comment]
yeah, even `_model_module` is not set either.

https://github.com/arose/nglview/blob/master/js/src/widget_ngl.js#L18-L20

PS: I have hard time to understand the difference between `_view_module ` and `_model_module`.
In above example, thing still works fine in notebook without defining `_model_module` :( 

Should I open an issue about updating docs for them in ipywidgets?

**Comment by jasongrout** [comment]
> Should I open an issue about updating docs for them in ipywidgets?

That would be great.

> PS: I have hard time to understand the difference between _view_module and _model_module.
> In above example, thing still works fine in notebook without defining _model_module :(

You have two js classes: the model and the view. The model keeps the state (e.g., _model_module, _view_module, etc.), the view just renders the model state. Your view doesn't need the _model_module, _view_module, etc.

You should define the `_view_module_version` here: https://github.com/arose/nglview/blob/e982b1da1adfc0710d6073cf8e15cdd6c2caff78/nglview/widget.py#L88 - consistent with what version is registered in your jlab plugin.

**Comment by jasongrout** [comment]
Because you inherit from DOMWidget in the python side, and don't override the model information, it looks like you are using the DOMWidget model: https://github.com/jupyter-widgets/ipywidgets/blob/master/ipywidgets/widgets/domwidget.py#L16

**Comment by hainm** [comment]
wow, it's working. Thanks so much @jasongrout. I am gonna cry. 

<img width="1273" alt="screen shot 2017-07-20 at 1 16 57 am" src="https://user-images.githubusercontent.com/4451957/28401638-3c5616d6-6ce9-11e7-8267-9cde0f65e0a5.png">
