### ISSUE TITLE
Float Slider in safari has broken rendering/functionality

### ISSUE THREAD

**Issue by mpacer** [jupyter-widgets/ipywidgets#1511]
Working with @stargaser at Scipy2017 sprints on widget to html export, we discovered that Float sliders seem to improperly render in Safari in both the static html and the live notebook context. 

The slider value is clickable & it is capable of changing the value on the basis of the direction that you pull it, but it does not move. It seems to have no track along which to move, which may just be an issue with how Safari expects dimensions to be specified.

**Comment by stargaser** [comment]
Here's a screenshot of how it renders in Safari.

<img width="391" alt="screenshot 2017-07-15 10 58 17" src="https://user-images.githubusercontent.com/970146/28240745-95a39d62-694c-11e7-9946-5573fc26f713.png">

**Comment by jasongrout** [comment]
I can confirm that I see this in Safari version 10.1.2 (11603.3.8) with the current ipywidgets master. Also, I notice that the jqueryui vertical slider at http://jqueryui.com/slider/#slider-vertical works fine in Safari. Maybe we are using some CSS that Safari doesn't support?

Thanks for reporting this!

**Comment by jasongrout** [comment]
Changing https://github.com/jupyter-widgets/ipywidgets/blob/1efb9e46965bccd6899016f9613b8f7dc5d41861/packages/controls/css/widgets-base.css#L564 to a pixel value seems to extend the slider appropriately. For some reason, setting the height to 100% collapses the slider track down to something like 2px high.

And 100% height there works in other browsers...

**Comment by jasongrout** [comment]
It may be this issue - the parent of the slider track does indeed not have a specific height:

https://stackoverflow.com/a/33644245

**Comment by jasongrout** [comment]
It does seem that changing https://github.com/jupyter-widgets/ipywidgets/blob/1efb9e46965bccd6899016f9613b8f7dc5d41861/packages/controls/css/widgets-base.css#L564 to `height: auto` works in Safari. I'll check in other browsers too.

**Comment by jasongrout** [comment]
> height: auto works in Safari. I'll check in other browsers too.

It looks like it totally breaks Chrome - the slider is 0 height with height set to `auto`.

One thing that does look like it works in both browsers is to use flexbox all the way - set the container to be a vertical flexbox and set the slider to grow. I'll play with it a bit.
