### ISSUE TITLE
Accordion section title doesn't dynamically update

### ISSUE THREAD

**Issue by OliverEvans96** [jupyter-widgets/ipywidgets#1516]
The following displays an accordion as expected
```
a = Accordion(
    children = [
        ipw.IntSlider(),
        ipw.Text()
    ]
)

a.set_title(0, 'Title #1')
a.set_title(1, 'Title #2')
a
```
But
```
a.set_title(1, 'Test 123')
```
doesn't update the title on the existing accordion.
However,
```
a
```
will display  a new view of the accordion with the correct new title.

Tabs do not seem to have this issue - their titles can be updated live.

(Using ipywidgets 7.0.0a11)

**Comment by jasongrout** [comment]
Reproduced on master. Thanks for pointing this out!
