### ISSUE TITLE
"Widget Javascript not detected" in jupyterlab v0.25.2

### ISSUE THREAD

**Issue by himbeles** [jupyter-widgets/ipywidgets#1527]
I get the following error message in a fresh jupyterlab install with enabled jupyterlab-manager extension:

"Widget Javascript not detected"
![screen shot 2017-07-20 at 10 44 51](https://user-images.githubusercontent.com/7621724/28408670-8649623a-6d38-11e7-8b7e-6002c254f300.png)

Same warning occurs in the console output 

> [IPKernelApp] WARNING | Widget Javascript not detected.  It may not be installed or enabled properly.

Although it says the "labextension" is known and "OK":

> JupyterLab v0.25.2
Known labextensions:
   app dir: /usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager  enabled  OK

I also performed "jupyter lab clean" before reinstalling jupyterlab-manager again.

**Comment by jasongrout** [comment]
Your kernel has ipywidgets 6 installed. Update that to the latest 7 alpha.

**Comment by jasongrout** [comment]
(I think you can update by installing ipywidgets with `pip install --upgrade --pre ipywidgets`)

**Comment by himbeles** [comment]
Great, thank you...

**Comment by jasongrout** [comment]
Let us know if that solves the problem, and we'll close the issue.

**Comment by himbeles** [comment]
That’s what I meant by “great”. Sorry :) You can close it!

**Comment by jasongrout** [comment]
Okay, thanks!
