### ISSUE TITLE
Mutli-Widget Widget

### ISSUE THREAD

**Issue by mlucool** [jupyter-widgets/ipywidgets#1543]
I would like to create a class that has multiple Jupyter widgets in it. For example, an Input and a Label wrapped in an HBox:  
`HBox([Label('Enter Data'), Text('Data')])`

How do I wrap this so that I can have a class that manages both of these? For example:  
` LabelAndEntry('My Label', 'Default Text')`

I want this to also be a jupyter widget so I can compose it like:  
`VBox(LabelAndEntry('foo', 'bar'), LabelAndEntry('baz', 'qux');`

The response in issue https://github.com/jupyter-widgets/ipywidgets/issues/700 indicates this should be able to be done in pure python, but I can't seem to find an example in the documentation which focuses on making new DOMWidgets.

**Comment by pbugnion** [comment]
Thanks for raising an issue. 

The easiest is probably to write a new class that extends an existing container widget:

```python
import ipywidgets as widgets

class LabelAndEntry(widgets.HBox):
    def __init__(self, *args, **kwargs):
        label = widgets.Label('my-label')
        entry = widgets.Text('data')
        super(LabelAndEntry, self).__init__()
        self.children = [label, entry]
```

<img width="587" alt="screen shot 2017-07-27 at 19 20 29" src="https://user-images.githubusercontent.com/1392879/28685744-ac8a72ea-7300-11e7-878b-dcdb4b42cbff.png">

**Comment by mlucool** [comment]
I get the following error with the above:
```
TypeErrorTraceback (most recent call last)
<ipython-input-1-744a177f073a> in <module>()
      2 
      3 print type(widgets.HBox)
----> 4 class LabelAndEntry(widgets.HBox):
      5     def __init__(self, *args, **kwargs):
      6         label = widgets.Label('my-label')

TypeError: Error when calling the metaclass bases
    function() argument 1 must be code, not str
```

I think it stems from:
```
print type(widgets.HBox)
<type 'function'>
```

**Comment by pbugnion** [comment]
Yes -- it looks like `HBox` was promoted to a class in 6.x. I strongly recommend just upgrading to the latest stable version.

If that's not possible, you can try using `Box` instead of `HBox` and adding the extra parameters that the `HBox` function adds in the constructor of your custom widget.

**Comment by mlucool** [comment]
Thanks for the help closing
