### ISSUE TITLE
Selection widgets docstrings not helpful

### ISSUE THREAD

**Issue by pbugnion** [jupyter-widgets/ipywidgets#1552]
It's not particularly easy to discover how to use selection widgets (e.g. select, dropdown etc.). To pass in options, one has to use the `options=` kwargs argument, but this isn't visible in the docstrings. The [docs](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#Selection-widgets) are very detailed, but I think it would be useful to expand the docstring. I note that the docstrings for `Button` is very detailed, for instance.

I'm more than happy to write docstrings for the Selection widgets if we think it's useful.

**Comment by jasongrout** [comment]
Definitely!

**Comment by jasongrout** [comment]
Fixed by #1559.
