### ISSUE TITLE
Hard-code msg_throttle to be 1

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#1554]
I haven't seen a reason to have msg_throttle at more than 1. I think we should simplify the protocol and remove the attribute, and hard-code in the throttle at one message.

Thoughts? @SylvainCorlay, @maartenbreddels, @vidartf, @pbugnion?

**Comment by maartenbreddels** [comment]
maybe a middle way, remove it from the python side, leave some of the code intact so that if it comes up it's easy to restore. Some googling I found the default was 3 a [while back](https://github.com/ipython/ipython/pull/5170/files)

**Comment by jasongrout** [comment]
Yes, it was 3 initially, but that was confusing, so we dropped it down to 1, which was much more responsive and better reflected what we really wanted.

**Comment by jasongrout** [comment]
See #1557 for an implementation.
