### ISSUE TITLE
Custom Widget example is broken

### ISSUE THREAD

**Issue by dsblank** [jupyter-widgets/ipywidgets#1560]
The docs at:

https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/examples/Widget%20Custom.ipynb

appear to be broken. If I replace "@jupyter-widgets/base" with "jupyter-js-widgets" then it appears to work.

**Comment by jasongrout** [comment]
Thanks. We'll get a fix in.

**Comment by jasongrout** [comment]
The example in master works for me with the latest ipywidgets 7.0 beta. It technically had some other issues that wouldn't affect the example, which I fixed.

Are you using the latest 7.0 beta?

**Comment by dsblank** [comment]
No, using the latest released code.

Also, this example would be very handy to have: I need to communicate with JavaScript (no view) from Python. Here is the best I have so far. Is this right? I guess I can send JavaScript code to be evaled, etc.

```javascript
%%javascript
require.undef('hello_model');

define('hello_model', ["jupyter-js-widgets"], function(widgets) {
    
    var HelloModel = widgets.DOMWidgetModel.extend({
               
        set: function(key, val, options) {
            console.log("model.set called!");
            console.log(key, val, options); // key is dict {"value1: "42"}
        },
    });
    
    return {
        HelloModel : HelloModel
    };
});
```

```python
class HelloModel(widgets.Widget):
    _model_name = Unicode('HelloModel').tag(sync=True)
    _model_module = Unicode('hello_model').tag(sync=True)
    value1 = Unicode('Hello World!').tag(sync=True)    
    value2 = Unicode('Hello World!').tag(sync=True)
```

```python
h = HelloModel()
h
```

```python
h.value2 = "42"
```

**Comment by jasongrout** [comment]
> No, using the latest released code.

If you're using ipywidgets 6, then you should be using the 6.x version of the example notebook: https://github.com/jupyter-widgets/ipywidgets/blob/6.x/docs/source/examples/Widget%20Custom.ipynb



> I need to communicate with JavaScript (no view) from Python. Here is the best I have so far. Is this right?

Can you give more context about what you are trying to do? Overriding `set` is probably not what you should do. Instead, listen for change events from the initialize method, like in https://github.com/jupyter-widgets/ipywidgets/blob/master/packages/controls/src/widget_link.ts#L31. I'm making a lot of assumptions here (that you want to communicate values, and that you want to act on those values changing) - if you're not doing that, then that may change the answer.

**Comment by jasongrout** [comment]
If you're wanting to just have generic communication (i.e., messages) with javascript, and don't need the state-syncing machinery, then you might just directly use comms, which is what widgets is built on.

**Comment by dsblank** [comment]
Thanks! This brings up more questions/comments:

1) Ok, so "latest" from readthedocs is for an unreleased version? http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Custom.html 

2) There is no mention in the docs that this is for a particular version. That would help.

3) How does one write/distribute Python code that will work across versions?

4) Overriding the initialize code could use an example.

5) Can you point me to an easy to use example that uses the comm interface? Does that have version issues (as per above)? I just want to set some DOM items from python. It is an SVG object, if that matters (I'm setting the href of an embedded image). Example: https://www.youtube.com/watch?v=tA8KREaLEAo

**Comment by jasongrout** [comment]
> Ok, so "latest" from readthedocs is for an unreleased version?

Yes. It follows the master branch in the repo.

> There is no mention in the docs that this is for a particular version. That would help.

That the example is for a particular version? I had thought that when using a notebook from the master branch (i.e., the latest commit) on a repo, it would be clear that it works with the current master commit of the repo. Do you have some text you think would help clarify that?

> How does one write/distribute Python code that will work across versions?

Across major versions of ipywidgets? There will be some backwards incompatible changes (that's what a major version signifies). However, for the python side, the changes should be minimal. We've been keeping a list of issues that developers should be aware of in the change log: https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/changelog.md

> Overriding the initialize code could use an example.

Great idea. Can you file an issue, or even better, a PR?

> Can you point me to an easy to use example that uses the comm interface? Does that have version issues (as per above)? I just want to set some DOM items from python. It is an SVG object, if that matters (I'm setting the href of an embedded image). Example:

That context helps - it would be helpful if you elaborated more, though. Can you give an example of the python code a user would write, and describe exactly what you want to happen on the javascript side? Do you plan for this to work with the rest of the widgets (i.e., be embeddable in a widget hbox/vbox, etc.)? If so, then you'll need to make a widget.

**Comment by dsblank** [comment]
I would need an example of overriding the init code in order to make a PR :)

Initially, I would just like to have Python code in a module that would be called by a user to change the href of an embedded image. In this example, the neural network has activations that propagate through the layers, and we want to see those activations as an image in the SVG. Currently, I send this javascript:

```javascript
var image = document.getElementById("{netname}_{name}");
image.setAttributeNS(null, "href", "{data_uri}");
```

Later, it may be that we want to turn the SVG into a widget. But for now, having it just be an SVG image is most flexible. 

I am having trouble piecing together a comm example that I can issue directly from the notebook (eg, without extension setup). That is, I want to register the comm, and send it a message. Do you know of an example of that?

**Comment by jasongrout** [comment]
Here is an example: http://jupyter-notebook.readthedocs.io/en/latest/comms.html

**Comment by dsblank** [comment]
Thanks! I think this will do it:

```javascript
%%javascript
Jupyter.notebook.kernel.comm_manager.register_target('conx_svg_control', function(comm, msg) {
    comm.on_msg(function(msg) {
        console.log("on_msg", ); // key: value
        var data = msg["content"]["data"];
        var image = document.getElementById(data["id"]);
        image.setAttributeNS(null, "href", data["href"]);
    });
});
```
```python
from ipykernel.comm import Comm
my_comm = Comm(target_name='conx_svg_control')
my_comm.send({'id': "network_image1", "href": "GIFIMAGE"})
```

**Comment by jasongrout** [comment]
Great!

**Comment by dsblank** [comment]
It does work, and is super fast! Thanks for all of your help, and a great infrastructure! I'll point you to the completed project when ready.
