### ISSUE TITLE
Traiterror in ipywidgets  7.0.0b3 and 7.0.0b4

### ISSUE THREAD

**Issue by DougRzz** [jupyter-widgets/ipywidgets#1566]
Hi,

When I upgrade to ipywidgets 7.0.0b3 I get the following error message in Jupyter (see below).  I do not get this message in 7.0.0b2.  The Jupyter cell had numerous ipywidgets including buttons, multi-select drop down widgets.   I can try and isolate the issue and send an example if you need more information.  

---------------------------------------------------------------------------
TraitError                                Traceback (most recent call last)
<ipython-input-6-958cb2d59e65> in <module>()
    138     readout=True,
    139     readout_format='i',
--> 140     slider_color='white'
    141 )
    142 def on_change(change):

C:\Users\Reddeda0\AppData\Local\Continuum\Miniconda3\lib\site-packages\ipywidgets\widgets\widget_int.py in __init__(self, value, min, max, step, **kwargs)
     59         if step is not None:
     60             kwargs['step'] = step
---> 61         super(cls, self).__init__(**kwargs)
     62 
     63     __init__.__doc__ = _bounded_int_doc_t

C:\Users\Reddeda0\AppData\Local\Continuum\Miniconda3\lib\site-packages\ipywidgets\widgets\widget_int.py in __init__(self, value, min, max, step, **kwargs)
     91         if step is not None:
     92             kwargs['step'] = step
---> 93         super(_BoundedInt, self).__init__(**kwargs)
     94 
     95     @validate('value')

C:\Users\Reddeda0\AppData\Local\Continuum\Miniconda3\lib\site-packages\ipywidgets\widgets\widget_int.py in __init__(self, value, **kwargs)
     73         if value is not None:
     74             kwargs['value'] = value
---> 75         super(_Int, self).__init__(**kwargs)
     76 
     77 

C:\Users\Reddeda0\AppData\Local\Continuum\Miniconda3\lib\site-packages\ipywidgets\widgets\widget.py in __init__(self, **kwargs)
    367         """Public constructor"""
    368         self._model_id = kwargs.pop('model_id', None)
--> 369         super(Widget, self).__init__(**kwargs)
    370 
    371         Widget._call_widget_constructed(self)

C:\Users\Reddeda0\AppData\Local\Continuum\Miniconda3\lib\site-packages\traitlets\traitlets.py in __init__(self, *args, **kwargs)
    995             for key, value in kwargs.items():
    996                 if self.has_trait(key):
--> 997                     setattr(self, key, value)
    998                 else:
    999                     # passthrough args that don't set traits to super

C:\Users\Reddeda0\AppData\Local\Continuum\Miniconda3\lib\site-packages\traitlets\traitlets.py in __set__(self, obj, value)
    583             raise TraitError('The "%s" trait is read-only.' % self.name)
    584         else:
--> 585             self.set(obj, value)
    586 
    587     def _validate(self, obj, value):

C:\Users\Reddeda0\AppData\Local\Continuum\Miniconda3\lib\site-packages\traitlets\traitlets.py in set(self, obj, value)
    557 
    558     def set(self, obj, value):
--> 559         new_value = self._validate(obj, value)
    560         try:
    561             old_value = obj._trait_values[self.name]

C:\Users\Reddeda0\AppData\Local\Continuum\Miniconda3\lib\site-packages\traitlets\traitlets.py in _validate(self, obj, value)
    589             return value
    590         if hasattr(self, 'validate'):
--> 591             value = self.validate(obj, value)
    592         if obj._cross_validation_lock is False:
    593             value = self._cross_validate(obj, value)

C:\Users\Reddeda0\AppData\Local\Continuum\Miniconda3\lib\site-packages\ipywidgets\widgets\trait_types.py in validate(self, obj, value)
    182                     'be one of {}, but a value of \'{}\' was '
    183                     'specified.'.format(
--> 184                         list(_number_format_types), format_type)
    185                 )

TraitError: The type specifier of a NumberFormat trait must be one of ['', 'o', 'b', '%', 'x', 'd', 'e', 'f', 'r', 'p', 'g', 's', 'c', 'X'], but a value of 'i' was specified.
-------------------------------------------------------------------------------------------------------

**Comment by pbugnion** [comment]
Thanks for submitting an issue.

You are using a `readout_format` value of `'i'` (presumably for  a slider, but I can't tell exactly), which isn't actually valid. Previously, this was silently converted to a `readout_format` of `''`. Part of the confusion is that the docs used `'i'` in some places (despite it not being valid). I would just change that slider to use a readout format of `''`.

x.ref PR #1550 and issue #1544 .

**Comment by DougRzz** [comment]
Thanks v much. That fixed it.
