### ISSUE TITLE
Help developers of custom widgets with backwards compatibility and upgrading 

### ISSUE THREAD

**Issue by ricklupton** [jupyter-widgets/ipywidgets#1572]
I have a custom ipywidget which I'd like to update to work with the latest ipywidgets 7.0, but it's not clear to me what the implications would be for continuing to use the latest version of my widget in older Jupyter installations. Is that never going to work? Will it just work? Are there specific things I can do that will keep it working, and could you give some hints in the release notes or elsewhere for custom widget developers? Maybe it's a lot to ask but it'd be helpful! 😄

The specific question I'm thinking of is the move from `jupyter-js-widgets` to `@jupyter-widgets/base`. If I update this, do I need to have a compatibility table [like this](https://github.com/jupyter-widgets/ipywidgets#compatibility) for my widget?

**Comment by jasongrout** [comment]
There are some fundamental incompatibilities between ipywidgets 6 and 7, including the one you note. The changelog provides some hints for migration: https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/changelog.md. Are there other notes for the changelog that you think we should add? Should we add a note saying that it will likely be impossible to support both ipywidgets 6 and 7?

**Comment by pbugnion** [comment]
I'm happy to try and write a migration guide for custom widget developers. I need to migrate [jupyter-gmaps](https://github.com/pbugnion/gmaps) anyway.

**Comment by jasongrout** [comment]
That would be great!

**Comment by ricklupton** [comment]
A migration guide would be great. I think it should be complementary to the cookiecutter template, which is great at making it easy to get started, but doesn't have any advice on keeping up to date with new versions.

Yes, making it clearer in the changelog which developer-facing changes are backwards compatible are which aren't would be helpful. I think the question I was looking to answer were:
- can I do anything to keep backwards compatibility with reasonable effort or do I need to require the new ipywidgets?
- if so, how do I need to update the JS and Python dependency version constraints so that things will keep working for new users when I migrate the custom widget? 

Generally, I'm just unsure about how updating my custom widget could break things for users who may have old Jupyter installations. But maybe I'm asking the wrong question and backwards compatibility doesn't really matter here; if so I should just make sure the version constraints are right and let users find an old version or update their installation.

**Comment by jasongrout** [comment]
> can I do anything to keep backwards compatibility with reasonable effort or do I need to require the new ipywidgets?

Require a new ipywidgets.



> if so, how do I need to update the JS and Python dependency version constraints so that things will keep working for new users when I migrate the custom widget?

The previous widget should use jupyter-js-widgets 2.* as a dependency. The new widget will use new packages (`@jupyter-widgets/base`, likely). Right now the base package is pre-1.0 version, but will be bumped to 1.0 on the 7.0 release.

For python, ipywidgets 6.* should be the dependency for the previous version, ipywidgets 7.0 should be the dependency for the new version (right now a beta is published, so the dependency is actually ipywidgets 7.0.0b4).

**Comment by ricklupton** [comment]
Thanks Jason. Seems straightforward now you say it but I think it would be helpful to be explicit about this in the changelog / migration guide.

**Comment by jasongrout** [comment]
Re-opening to note adding a sentence or two to the changelog.

**Comment by ricklupton** [comment]
Ah sorry!

**Comment by jasongrout** [comment]
I added a note in #1581. We still welcome any wording improvements or larger update guide if you have time.

**Comment by pbugnion** [comment]
I've opened PR #1594 for a migration guide.
