### ISSUE TITLE
`interactive_output` flickers

### ISSUE THREAD

**Issue by jharrison** [jupyter-widgets/ipywidgets#1582]
Similar to the problem described [here](https://github.com/jupyter-widgets/ipywidgets/issues/910), I want to customize the layout of my interactive widgets. The kludgy approach is to call `interactive` then get the children out, put them in a specific layout, and put them back in. Like so:

```
from IPython.display import display
import numpy as np
from ipywidgets import *
import matplotlib.pyplot as plt

def plot_oscillation(wavelength, magnitude, phase):
    x = np.linspace(-20, 20, 1000)
    plt.plot(x, magnitude*np.sin((x+phase)/(wavelength/(2*np.pi))))
    plt.show()
    
w = dict(wavelength = FloatSlider(2*np.pi, min=0.1, max=20, step=0.1, description='wavelength'),
         magnitude = FloatSlider(1, min=0.1, max=10, step=0.1, description='magnitude'),
         phase = FloatSlider(0, min=0, max=10, step=0.1, description='phase'))

int_w = interactive(plot_oscillation, **w)

output = int_w.children[-1] # last child is the output

int_w.children = [HBox([VBox([*int_w.children[:-1]]), output])]
display(int_w)
```
This approach works and does *not* flicker, but it's pretty clunky. The `interactive_output` function was created to provide a better way to do this sort of thing. It works but flickers. See here:

```
from IPython.display import display
import numpy as np
from ipywidgets import *
import matplotlib.pyplot as plt

def plot_oscillation(wavelength, magnitude, phase):
    x = np.linspace(-20, 20, 1000)
    plt.plot(x, magnitude*np.sin((x+phase)/(wavelength/(2*np.pi))))
    plt.show()
    
w = dict(wavelength = FloatSlider(2*np.pi, min=0.1, max=20, step=0.1, description='wavelength'),
         magnitude = FloatSlider(1, min=0.1, max=10, step=0.1, description='magnitude'),
         phase = FloatSlider(0, min=0, max=10, step=0.1, description='phase'))

output = interactive_output(plot_oscillation, w)
box = HBox([VBox([*w.values()]), output])
display(box)
```
It seems like it might be related to [this](https://github.com/jupyter-widgets/ipywidgets/issues/145) now-fixed issue with `interact`.

**Comment by jasongrout** [comment]
This line: https://github.com/jupyter-widgets/ipywidgets/blob/84db08cdccd3d22cec3980e8ddd5ab8d76100e86/ipywidgets/widgets/interaction.py#L70 should probably be `clear_output(wait=True)`.

**Comment by jasongrout** [comment]
Can you try manually making the change in #1585 and see if that solves the problem?

**Comment by jasongrout** [comment]
Thanks again for bringing this up!

**Comment by jharrison** [comment]
How do I got about making that change? I installed ipywidgets (5.2.2) using pip. Do I need to install from github or something?

**Comment by jasongrout** [comment]
You can just edit that python file on your system. You can find the file by importing ipywidgets and looking at __file__

```python
import ipywidgets
import ipywidgets.widgets.interaction
print(ipywidgets.widgets.interaction.__file__)
```
Then you can search in that file for 'clear_output' to add the `wait=True`.

The fix did work for me, so the other thing you might do is wait just a bit for the next prerelease for ipywidgets 7.0 (which we'll probably release today).

**Comment by jharrison** [comment]
It worked! Thanks!
