### ISSUE TITLE
Widgets not Exporting to HTML

### ISSUE THREAD

**Issue by yngstr** [jupyter-widgets/ipywidgets#1586]
I've created an interactive jupyter notebook with ipywidgets and I have to say I love the functionality. I'm able to play with my data and filter/sort visualizations using the widgets.

However, now that I'm ready to "expose" it, I'm finding that it's not able to export to HTML. The widgets appear, but do nothing. When I use nbconvert, I get the "Widget Javascript not detected" error.

I think ipywidgets is great, but unless I can somehow expose the widgets to the end user, it's not solving my use-case. My larger goal is simply to get the interactive plots in front of the user, so if there's another way to that end, let me know.

**Comment by jasongrout** [comment]
In order for the widgets to do something, they must be hooked up to a kernel to do the computation.  This requires some extra javascript code and a server somewhere that is providing the python kernel. The [web3 example](https://github.com/jupyter-widgets/ipywidgets/tree/6.x/jupyter-js-widgets/examples/web3) shows one way to do this.

**Comment by yngstr** [comment]
Thanks Jason, yep, that makes sense.

Excuse my ignorance, but how do I "run" this example and see what it produces? I have the folder saved locally, but unsure how to explore it...

I mainly use python to work with data, so I'm fairly unfamiliar with dev frameworks, etc. Feel free to tell me to shove it and go learn more before I ask dumb questions ;)

On that note, any links you may have to that end would be appreciated

Dave

**Comment by jasongrout** [comment]
Sorry, I didn't see your comment. The readme in that directory has instructions - see it at the bottom of https://github.com/jupyter-widgets/ipywidgets/tree/master/examples/web3

**Comment by jasongrout** [comment]
And feel free to ask questions!

Steps 1-4 of that readme could be replaced with:

* run: `npm install`
*  run: `npm run build`
* run: `npm run host`

**Comment by jasongrout** [comment]
Closing as resolved. Please reopen if you'd like to continue the conversation.
