### ISSUE TITLE
Receiving binary buffers from frontend fails

### ISSUE THREAD

**Issue by vidartf** [jupyter-widgets/ipywidgets#1592]
If receiving buffers from the front end, the following line fails: https://github.com/jupyter-widgets/ipywidgets/blob/master/ipywidgets/widgets/widget.py#L601

The error is `TypeError: <memory at 0x000001E2CA4F8708> is not JSON serializable`.

An outline of the trace is:
 - Comm message with buffer received. Calls `set_state`.
 - `set_state`:
   - Locks the properties.
   - Deserializes the data (to numpy array in this case).
   - Calls `set_trait`.
 - `notify_change` calls `_should_send_property`.
 - `to_json` (my serializer) gives back a dict with a memoryview.
 - `jsondumps` chokes on the memoryview.

**Comment by vidartf** [comment]
A possible solution is to do the comparison in the the serialized state after calls to `_separate_buffers`. The buffers can be compared by instance (`a is b`) or possibly by numpy (that should maybe be left as an extension point for custom comparison).

**Comment by jasongrout** [comment]
Ah yes, good catch. That is from https://github.com/jupyter-widgets/ipywidgets/pull/1523. I like your solution.

We've tried to have a lot better testing around the syncing framework on the javascript side. We should have a unit test for this too - that would have caught this when the PR was merged.

**Comment by vidartf** [comment]
I'll PR a fix later. Gonna try to add a test as well!

**Comment by jasongrout** [comment]
Awesome, thanks!
