### ISSUE TITLE
3rd party widget won't be displayed twice

### ISSUE THREAD

**Issue by hainm** [jupyter-widgets/ipywidgets#1593]
Hi

This is a puzzle to me. Please check below:

![add_shape](https://user-images.githubusercontent.com/4451957/28998856-36a2bf7e-7a03-11e7-9e3b-31909f69cefb.png)

```python
import nglview as nv
from nglview.utils import get_colors_from_b64

view = nv.NGLWidget()
view
```

    A Jupyter Widget

```python
view.shape.add_sphere([0, 0, 9], [1, 0, 0], 1.5)
view.shape.add_arrow([1, 2, 7 ], [30, 3, 3], [1, 0, 1], 1.0)
```

```python
view.shape.add_label([ 0, 4, -1 ], [ 0.2, 0.5, 0.8 ], 2.5, 'Meow')
```

```python
view
```

    A Jupyter Widget

**Comment by hainm** [comment]
So we need to explicitly call `view.sync_view` again to make the 2nd display work.
https://github.com/arose/nglview/blob/master/nglview/widget.py#L392-L397

I am using `'7.0.0b0'`. 

Is there idea why?

PS: same thing happens if we want to make two views in the HBox

![box](https://user-images.githubusercontent.com/4451957/28998873-c97b9f14-7a03-11e7-87a5-118bf4115e29.png)

**Comment by jasongrout** [comment]
I'm not sure what the sync view function does...that is part of the ngl package and not part of ipywidgets.

**Comment by jasongrout** [comment]
Beta 0 is a bit old at this point. Does upgrading to the latest beta help? If not, it seems like it may be something that needs to be narrowed down in the ngl widget code.

**Comment by hainm** [comment]
> I'm not sure what the sync view function does...that is part of the ngl package and not part of ipywidgets.

sorry not to be clear. The `sync_view` is just command to send request to `NGL`. 

for example

```
# 1st displaying
view.add_surface()
view
```

With 2nd display I will get empty `view`, so the command `add_surface` need to be called again.
This is not I am expecting since seems to me that we can just display "view" again without doing anything (according to ipywidgets docs).

**Comment by hainm** [comment]
> Beta 0 is a bit old at this point. Does upgrading to the latest beta help? 

No

> If not, it seems like it may be something that needs to be narrowed down in the ngl widget code.

yeah I think so but I don't have any idea why. :( 
Here is the render code: https://github.com/arose/nglview/blob/master/js/src/widget_ngl.js#L28

thanks.

**Comment by hainm** [comment]
Uhm, to avoid confusing you, I think we only need to focus on question: Why `view` won't be displayed in `VBox([view, view])`?

**Comment by pbugnion** [comment]
As a data point, jupyter-gmaps (on this PR) has no problems with displaying the same view twice. This works as expected:

```
import gmaps
import ipywidgets as widgets
gmaps.configure(api_key="AIza...")

fig = gmaps.figure(center=(51.5, -0.2), zoom_level=11) # fig is a widget
fig.add_layer(gmaps.transit_layer())
widgets.VBox([fig, fig])
```

**Comment by hainm** [comment]
@pbugnion does `jupyter-gmaps` uses lots of `view.send(msg, ...)` or just syncing frontend and backend via traitlets (e.g: `Unicode(...).tag(sync=True)`).

In nglview, we use `send` to send instruction to frontend. May be this is the issue?

**Comment by pbugnion** [comment]
> does jupyter-gmaps uses lots of `view.send(msg, ...)` or just syncing frontend and backend via traitlets (e.g: `Unicode(...).tag(sync=True)`).

It only uses `Unicode(...).tag(sync=True)`.

**Comment by jasongrout** [comment]
> In nglview, we use send to send instruction to frontend. May be this is the issue?

It's very possible that this may be an issue (maybe not the only one?). If the model does not contain all of the information needed to display a model in synced attributes, then it will be harder to create two views for the same model.

**Comment by hainm** [comment]
thanks all for your inputs. I think we just let `nglview` be. Syncing heavy data in frontend seems not to be a good solution for us.
