### ISSUE TITLE
Add offline embedded html embed-local.js embedded entry point.

### ISSUE THREAD

**Issue by chrisjsewell** [jupyter-widgets/ipywidgets#1596]
As discussed at maartenbreddels/ipyvolume#41 and jupyter-widgets/ipywidgets#1568

Add a `save_js`  function to jupyter-widgets/ipywidgets/embed.py, to copy/paste all required javascript (currently embed.js, require.js, base.js, controls.js and index.js) to an external folder, such that the embedded html can call them locally.

This would also require a rewrite of embed.js to load the local javascript (rather than from unpkg.com). So either a duplicate version of embed.js with local links or, better, logic in the current embed.js to first look for local files then fall back to loading them from unpkg.com. @maartenbreddels already has this logic implemented in ipyvolume, although I can't actually find the code lines that implement it?

**Comment by pbugnion** [comment]
Thanks for raising an issue. I agree that this would be useful.

> logic in the current embed.js to first look for local files then fall back to loading them from unpkg.com

Unless I'm missing something, this is already the case. If you have a widget whose `_model_module` is called 'widget-example.js`, the html manager will first look for a local file called `./widget-example.js`, and, failing that, fall back to `unpkg.com/widget-example@<version>/dist/index.js`.

**Comment by chrisjsewell** [comment]
I guess that's only for external packages. For example, when loading my embedded html file [here](https://chrisjsewell.github.io/3d_atomic/converted/3D%20Atomic%20Visualisation_files/ivol_example1.html) (hosted [here](https://github.com/chrisjsewell/chrisjsewell.github.io/tree/master/3d_atomic/converted/3D%20Atomic%20Visualisation_files)) with all javascript files present locally, you get:

![jvascript_loading](https://user-images.githubusercontent.com/2997570/29006115-5d9f4028-7ae1-11e7-9f6f-b281374b9c2d.png)

Whereas I want all domains to be `chrisjsewell.github.io`. Or am I doing something wrong?

**Comment by chrisjsewell** [comment]
Also, a minor personal preference to keep things cleaner,  would be that the javascript is in a subfolder (e.g. `js`) and so the html manager would look for `./js/widget-example.js`.

**Comment by pbugnion** [comment]
> I guess that's only for external packages.

That's right. The relevant code for loading the dependencies is [here](https://github.com/jupyter-widgets/ipywidgets/blob/master/packages/html-manager/src/embed-webpack.ts#L62). To make it load local files first, I guess we would want to emulate the [logic for loading external widget libraries](https://github.com/jupyter-widgets/ipywidgets/blob/master/packages/html-manager/src/htmlmanager.ts#L63).

This change would also make manual testing of embedding easier -- when I was testing, I had to manually change that load command to load local files, rather than from unpkg.

**Comment by jasongrout** [comment]
Perhaps the most usual case would be to just load from the internet, rather than randomly trying to load files from the local webserver. However, it makes sense to me to *also* have, say, an "embed-local.js" file that does the local-first resolution you're talking about.

**Comment by chrisjsewell** [comment]
> Perhaps the most usual case would be to just load from the internet, rather than randomly trying to load files from the local webserver.

Well if you can guarantee to me that that files loaded from the internet won't suddenly change and break my web presentations again (as happened here maartenbreddels/ipyvolume#41), then I'd be happy not to have local webserver versions 😉

**Comment by jasongrout** [comment]
We have fixed that particular issue, in that we now request a specific version of the html manager. However, we don't run the free unpkg service, so we have no guarantees for it.

My point is that local loading should be an explicit opt-in - which I think safer, and is okay because the user will need to do some work anyway to host the necessary files.

**Comment by chrisjsewell** [comment]
Yeh no that's absolutely understandable. Just wanted to make the point that there is a risk for the user in hosting html which relies on external sources.  Other than that ipywidgets is great, so keep up the good work!

**Comment by jasongrout** [comment]
> Just wanted to make the point that there is a risk for the user in hosting html which relies on external sources.

Yep, totally understood! I normally would try to host all of my own files, rather than relying on external services, especially free ones.

**Comment by vidartf** [comment]
Maybe ipywidgets should also add integrity checks for fixed version CDN scripts? C.f https://github.com/jupyter/jupyter.github.io/issues/204 (https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity).

**Comment by jasongrout** [comment]
> Maybe ipywidgets should also add integrity checks for fixed version CDN scripts?

The hard part is that the version that we get changes with every release. If we had an automated way of updating the hash, that would be great.

**Comment by jasongrout** [comment]
(Note that I am including the SRI for the require.js file we load from CDN too)

**Comment by stonebig** [comment]
if ipywidgets is updated each time you need to update CDN scripts, then you can have the hash in ipywidgets, can't you ?

**Comment by jasongrout** [comment]
You could do a three-pass build:

1. build the necessary scripts
2. calculate the hash and store it, say, in package.json
3. import that hash in the embed script

**Comment by jasongrout** [comment]
The offline local js is now working with both the bundled script and the require.js embed module.

**Comment by jasongrout** [comment]
Fixed by #1615.
