### ISSUE TITLE
interactive and boxes don't play nicely on ipywidgets 7 and mpl inline backend

### ISSUE THREAD

**Issue by myyc** [jupyter-widgets/ipywidgets#1602]
this piece of code doesn't work on jupyter (inline backend, as usual); not sure whether it's a bug or something that has changed recently in ipywidgets.

```python
import pandas as pd
from ipywidgets import RadioButtons as RB, HBox as HB
from IPython.display import display

def f(c):
    pd.DataFrame([1,2,3]).plot(title=c)

iw = interactive(f, **{"c": RB(options=["a", "b"])})
b = iw.children[:-1]
iw.children = [HB(b)]
display(iw)
```

naturally, this does

```python
import pandas as pd
from ipywidgets import RadioButtons as RB

def f(c):
    pd.DataFrame([1,2,3]).plot(title=c)

interactive(f, **{"c": RB(options=["a", "b"])})
```

**Comment by stonebig** [comment]
you forgot to "import interactive". this works: 
![ipywidgets700b7](https://user-images.githubusercontent.com/4312421/29077912-66b35022-7c59-11e7-8545-a0504e3646e6.PNG)

**Comment by myyc** [comment]
you might want to give a big edit to your comment :)

**Comment by stonebig** [comment]
if we remove two lines in your first part, it looks ok now:
![ipywidgets700b7c](https://user-images.githubusercontent.com/4312421/29078430-ac77a0e4-7c5a-11e7-9890-eaf22fb9577b.PNG)

**Comment by jasongrout** [comment]
@myyc - What are you expecting as the output? It looks like exactly what I would expect - a single radiobutton control, since you cut off the output widget with your `[:-1]` slicing of `children`.

<img width="679" alt="screen shot 2017-08-08 at 11 29 52 am" src="https://user-images.githubusercontent.com/192614/29080157-0e81c0ae-7c2d-11e7-8df3-59da40489aeb.png">

**Comment by jasongrout** [comment]
Was this what you were wanting? (note the `%matplotlib inline`):

<img width="804" alt="screen shot 2017-08-08 at 11 36 20 am" src="https://user-images.githubusercontent.com/192614/29080485-e0e9f7f0-7c2d-11e7-9cbe-c72fadf0f66c.png">

**Comment by myyc** [comment]
OK my bad. I didn't realise that the output was indeed the plot that I wanted and this is normal behaviour.

In the past I used a much dirtier trick which mixed `interactive` with manual plots, this way – probably it was like this all along – is much nicer, and my old way doesn't work anymore, hence why i reported this.

Not a bug I guess :) thanks!

**Comment by jasongrout** [comment]
Ah, yes, we made things much nicer with the output widget these days :).

**Comment by myyc** [comment]
For the record, this is what I wanted

```python
from ipywidgets import interactive, RadioButtons as RB, HBox as HB
from IPython.display import display

def f(c):
    pd.DataFrame([1,2,3]).plot(title=c)

iw = interactive(f, **{"c": RB(options=["a", "b"])})
b = iw.children[:-1]
iw.children = [HB(b), iw.children[-1]]
iw
```
