### ISSUE TITLE
In a notebook, re-executing a cell containing a widget throws an exception

### ISSUE THREAD

**Issue by pbugnion** [jupyter-widgets/ipywidgets#1606]
In the classic notebook, create a widget with, e.g.

```
import ipywidgets as widgets

widgets.IntSlider()
```

Then re-execute the cell that generates the slider. This causes an exception to be thrown in the console (Exception in event handler for execute.CodeCell TypeError: Cannot read property 'el' of undefined).  The exception arises [here](https://github.com/jupyter-widgets/ipywidgets/blob/master/widgetsnbextension/src/extension.js#L67), at which point the `views` object that gets dereferenced is empty. I haven't had time to investigate this more, but it could be because `views` is being shadowed or overriden somewhere? Scoping rules around `var` are tricky...

Happy to look into this unless someone gets there first.

**Comment by jasongrout** [comment]
I don't get any errors when re-executing that cell multiple times in the classic notebook.

What version of widgets do you have? What version of the notebook?

**Comment by pbugnion** [comment]
Sorry -- I just hadn't re-built the extension correctly. Apologies for the noise.
