### ISSUE TITLE
Question on HTML widget width

### ISSUE THREAD

**Issue by dsblank** [jupyter-widgets/ipywidgets#1613]
Trying to set the max_width on an HTML widget, but there is a div in the way. Referring to this picture:

![screenshot from 2017-08-09 19-11-25](https://user-images.githubusercontent.com/168568/29147743-f8d10d72-7d36-11e7-93bb-8243639bb4db.png)

You'll see that I want the "Hello, World!" text and blue background to span the width of the cell (this is just an example of a larger HTML problem involving in iframe, but is a simple example). If I give a layout object, you can see that goes to the div above. The text has its own width. But the div between them (or the label div) could either be made to expand to 100% to allow the Text to span the region. I added a style= width: 100% and it did work. 

How can I access either the content or the description width to make room? Or is there another way?

**Comment by dsblank** [comment]
To be clear: if I add `style="width: 100%"` to the `widget-html-content` div directly above the actual HTML, then everything works as desired.Can I access that div via the widgets API?

**Comment by jasongrout** [comment]
I've reproduced what you see. I fixed it a different way, using flexbox. I also added position: relative so that html content can have absolute positioned content that will be positioned relative to the html widget.

**Comment by jasongrout** [comment]
Question, though: should the HTML widget have the same default width as all of the other widgets, to tile more nicely? The width could be changed, of course.

**Comment by jasongrout** [comment]
I guess changing the default width would break people's existing layouts, so we shouldn't do it without much wider community consensus.

**Comment by jasongrout** [comment]
That sounds like it would have broken. The issue is that now the html fills the space, so it's already centered. If you have a piece of content you need to center inside of that space, you'll need to center it yourself, perhaps with:`<p style="text-align:center">content</p>` work?

**Comment by dsblank** [comment]
Thanks! Yes, that is a fix. Is that a temp workaround? Or is this how it should work from here on?

**Comment by jasongrout** [comment]
I think it's how things will need to be done. I think we can't have both this issue fixed and the centering working like you had. Do you have a preference between which thing you'd like to work? I'd prefer to fixing this issue, since we have an easy fix for the centering.

**Comment by dsblank** [comment]
This is fine from my perspective. Just planning on whether I should identify my code now as "remove when ipywidgets version X" is released, or if it is fine going forward. Thanks again! Things are looking great for centering (using the <pre> tag) and for 100% (using the CSS refinements).
