### ISSUE TITLE
Widget Javascript not detected.  It may not be installed or enabled properly.

### ISSUE THREAD

**Issue by michaelaye** [jupyter-widgets/ipywidgets#1616]
Using conda-forge, I understand that the `nbextension` install and enable should have been done for me.
However, I get the above error message, and even manual enabling does not help.

Here's my nbextensions:

```bash
(stable) └─❱❱❱ jupyter nbextension list                                            +8565 14:57 ❰─┘
Known nbextensions:
  config dir: /Users/klay6683/.jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled
      - Validating: OK
    tree section
      tree-filter/index  enabled
      - Validating: OK
  config dir: /Users/klay6683/miniconda3/envs/stable/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled
      - Validating: OK
      nbextensions_configurator/config_menu/main  enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      contrib_nbextensions_help_item/main  enabled
      - Validating: OK
      bqplot/extension  enabled
      - Validating: OK
    tree section
      nbextensions_configurator/tree_tab/main  enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
```

Note, that despite the conda install enabling the widgets extension in the conda config dir, I added the one using the command without the `sys-prefix` in desperation to get things working but to no avail.

Here are my conda versions (all up-to-date with conda-forge) for related things:
```bash
(stable) └─❱❱❱ conda list jupyter                                                  +8567 15:00 ❰─┘
# packages in environment at /Users/klay6683/miniconda3/envs/stable:
#
jupyter_client            5.1.0                    py36_0    conda-forge
jupyter_contrib_core      0.3.1                    py36_0    conda-forge
jupyter_contrib_nbextensions 0.2.8                    py36_1    conda-forge
jupyter_core              4.3.0                    py36_0    conda-forge
jupyter_highlight_selected_word 0.0.11                   py36_0    conda-forge
jupyter_latex_envs        1.3.8.2                  py36_1    conda-forge
jupyter_nbextensions_configurator 0.2.5                    py36_0    conda-forge
jupyterlab                0.26.5                   py36_0    conda-forge
jupyterlab_launcher       0.3.1                    py36_0    conda-forge
```
```bash
(stable) └─❱❱❱ conda list widget                                                   +8568 15:00 ❰─┘
# packages in environment at /Users/klay6683/miniconda3/envs/stable:
#
ipywidgets                6.0.0                    py36_0    conda-forge
widgetsnbextension        2.0.0                    py36_0    conda-forge
```
and here the widget call I tried, from the docs:

<img width="908" alt="screenshot 2017-08-10 15 01 46" src="https://user-images.githubusercontent.com/69774/29191984-ddcb8c86-7ddc-11e7-87a1-6914bd4ce760.png">

**Comment by jasongrout** [comment]
Does the browser show the jupyer-js-widgets javascript being loaded?

**Comment by michaelaye** [comment]
how do i check that?

**Comment by jasongrout** [comment]
Go to the developer tools, reload the page, and look at the Networks tab. Check to see if the nbextension/jupyter-js-widgets/extension.js file was loaded.

**Comment by michaelaye** [comment]
Looks like it:
<img width="893" alt="screenshot 2017-08-10 15 46 17" src="https://user-images.githubusercontent.com/69774/29193564-21295b06-7de3-11e7-8606-e2c297bad869.png">

**Comment by michaelaye** [comment]
FYI, just in case browser is messed up or something else, i did a reboot of this iMac (was up for 15 days), but to no avail. I also re-executed [...] install and [...] enable commands, also no help.

**Comment by jasongrout** [comment]
I wonder if the javascript is the wrong version. Can you look in that file (in the Sources tab of developer tools) and search for "version_major: 1" (without the quotes)?

**Comment by michaelaye** [comment]
If I'm looking at the right place (see screenshot), the word "version" only appears twice in the source, once for notebook_version 5.0.0 and once for sys_version 3.6.2.

![screenshot 2017-08-10 18 55 25](https://user-images.githubusercontent.com/69774/29198008-7f426bdc-7dfd-11e7-9fc1-faf1f2308fe8.png)

**Comment by jasongrout** [comment]
What does the nbextensions/jupyter-js-widgets/extension.js source look like? Does "version" not appear in it?

**Comment by jasongrout** [comment]
It may be easier to hop on to gitter to debug this.

**Comment by michaelaye** [comment]
Ah that file. It says version_major 2 in the 3 places it appears. (see screenshot)

![screenshot 2017-08-10 19 01 25](https://user-images.githubusercontent.com/69774/29198132-6494b942-7dfe-11e7-82d7-cd9246ea4182.png)

**Comment by jasongrout** [comment]
Okay, that file is a newer version of the javascript. Can you delete all the jupyter-js-widgets nbextensions (in sys-prefix and in your user directory) to clean them out? Then reinstall the nbextension?

Maybe what happened is when you installed, the newer version was already installed, and you didn't do the `--overwrite` switch to overwrite an existing install.

**Comment by michaelaye** [comment]
sorry, could you be more precise? Which conda package do I need to remove? Only widgetsnbextension? Or also the ipywidgets package?
I do not know of any --overwrite switch for conda?

**Comment by michaelaye** [comment]
The folders "/Users/klay6683/miniconda3/envs/stable/etc/jupyter/nbconfig" and "/Users/klay6683/.jupyter/nbconfig" only contain the load instructions of the extension, not the extension code itself. How do I make sure, i.e. where is the JS code itself to remove? I don't see any pointer to it?

**Comment by jasongrout** [comment]
Sorry, this is not about the conda installation, but about the nbextension installation. Do `jupyter nbextension uninstall --py --sys-prefix widgetsnbextension` and then the same without the `--sys-prefix`. Then do `jupyter nbextension list` to make sure the extensions are gone.

Then re-install.

**Comment by jasongrout** [comment]
(and if you want to check manually, `jupyter --paths` gives the data directories, which is where the javascript actually is stored - you can check each of the data directories, in the nbextensions subdirectory, for the `jupyter-js-widgets` javascript.

**Comment by michaelaye** [comment]
To my knowledge, the nbextensions are installed by the conda package post-install scripts. so are they maybe missing an --overwrite ?

**Comment by jasongrout** [comment]
Looks like there is no `--overwrite`: https://github.com/conda-forge/widgetsnbextension-feedstock/blob/master/recipe/post-link.bat

CC @SylvainCorlay - any reason why there is no `--overwrite`?

**Comment by michaelaye** [comment]
Okay, that did it, thanks so much for your help!

**Comment by jasongrout** [comment]
Great!
