### ISSUE TITLE
Creating domwidgets on the frontend causes errors on the backend setting layout to null

### ISSUE THREAD

**Issue by maartenbreddels** [jupyter-widgets/ipywidgets#1620]
Lets's start how I found out:
With [ipywebrtc](https://github.com/maartenbreddels/ipywebrtc) I do the following:
```python
import ipywebrtc
import ipywidgets as widgets
from IPython.display import display
camera = ipywebrtc.CameraStream()
room = ipywebrtc.WebRTCRoomMqtt(stream=camera, room='bug')
room2 = ipywebrtc.WebRTCRoomMqtt(stream=camera, room='bug')
#to see what happens uncomment below:
#box = widgets.HBox(children=[])
#widgets.jslink((room, 'streams'), (box, 'children'))
#display(box)
```
What will happen, is that room.peers and room.streams will be set at the frontend when people join (here two, yourself twice).
However, streams are [MediaStream](https://github.com/maartenbreddels/ipywebrtc/blob/88857f401c8669f9a771b14e9f58288dc5238e1d/ipywebrtc/webrtc.py#L17) instances, and are a subclass of DOMWidget. DOMWidget has a layout property. After the comm gets created, it will update the values with `layout: null`, causing an error:
`"The 'layout' trait of a MediaStream instance must be a Layout, but a value of class 'NoneType' (i.e. None) was specified."`

You'd think this would happen with the Controller as well, except what Controller creates are not DOMWidgets, so it has no layout property on the backend, although the frontend [says it is a coredomwidget](https://github.com/jupyter-widgets/ipywidgets/blob/8aaae57fb625302eb614a3aaddd299e088de2468/packages/controls/src/widget_controller.ts#L17) (bug?).

**Comment by jasongrout** [comment]
> what Controller creates are not DOMWidgets, so it has no layout property on the backend, although the frontend says it is a coredomwidget (bug?).

Yes, definitely a bug.

**Comment by maartenbreddels** [comment]
cc @SylvainCorlay 
Ok, I can confirm that #1622 does expose this bug to the controller as well, which can be checked by.
```python
import ipywidgets as widgets
widgets.Controller()
#.... wait till the buttons get there ...
# then you run the following line:
widgets.Widget.get_manager_state()
/Users/maartenbreddels/src/ipywidgets/ipywidgets/widgets/widget.py in get_manager_state(drop_defaults, widgets)
    344         if widgets is None:
    345             widgets = Widget.widgets.values()
--> 346         for widget in widgets:
    347             state[widget.model_id] = widget._get_embed_state(drop_defaults=drop_defaults)
    348         return {'version_major': 2, 'version_minor': 0, 'state': state}

RuntimeError: dictionary changed size during iteration```
