### ISSUE TITLE
Switch default cdn from unpkg to jsdelivr

### ISSUE THREAD

**Issue by mlucool** [jupyter-widgets/ipywidgets#1627]
In case someone is having issues, there is a critical regression with unpkg: https://github.com/unpkg/unpkg-website/issues/51

**Comment by jasongrout** [comment]
Is this why I'm seeing errors loading fontawesome? Other than that, are there other places you see errors from this?

**Comment by MartinKolarik** [comment]
@jasongrout yes, it affects all links with a query string, font awesome is one of them.

If you'd like, you are welcome to use [jsDelivr CDN](http://www.jsdelivr.com/), which works in a similar fashion but is strongly focused on production usage and never breaks any existing links.

**Comment by jasongrout** [comment]
Thanks, we'll take that into consideration. As you can probably guess, we are extremely conservative in choosing a CDN to be used in our official sources.

**Comment by MartinKolarik** [comment]
>As you can probably guess, we are extremely conservative in choosing a CDN to be used in our official sources.

That makes sense 😄 let me know if you have any questions or need help... jsDelivr serves more than 10 times the traffic of unpkg so I'm sure it would work for you as well.

**Comment by jasongrout** [comment]
Thanks! Yes, I'm seeing lots of positive things about jsdelivr as I look around. And I suppose any hesitation about security is resolved by using SRI more consistently.

**Comment by MartinKolarik** [comment]
Yes, we're very serious about security too, but SRI definitely helps in that regard.

**Comment by jasongrout** [comment]
More background: it seems that jsdelivr was not an option when we were looking for CDNs last, but in May implemented the automated npm CDN part we wanted from unpkg: https://github.com/jsdelivr/jsdelivr/issues/13136

It does seem to me that it makes sense to switch to jsdelivr, given that unpkg is having issues, jsdelivr is more mature and (according to the above and other info I'm finding) serves much more traffic, and given the problem above.

@SylvainCorlay, @maartenbreddels, @pbugnion, @mwcraig, @vidartf - do any of you have opinions about switching from unpkg.com to jsdelivr for our hardcoded CDN? It'd basically just be switching the domain name, as the URLs and features are essentially equivalent.

**Comment by maartenbreddels** [comment]
No objections, I'd say if we need to switch the time is now.

**Comment by jasongrout** [comment]
I'm testing again to see if the fontawesome on unpkg is causing problems.

**Comment by mwcraig** [comment]
I don't have an opinion....

**Comment by SylvainCorlay** [comment]
Same. unpkg is supported by a large organization though.

**Comment by jasongrout** [comment]
> Same. unpkg is supported by a large organization though.

Where do you see that? I don't see it on https://unpkg.com/#/about (other than donations of services).

In any case, jsdelivr's sponsor list is also pretty impressive: http://www.jsdelivr.com/about

**Comment by jasongrout** [comment]
> I'm testing again to see if the fontawesome on unpkg is still causing problems.

I saw problems with fontawesome at some point, but I don't see problems now - possibly because we've rewritten how the embedding works. Now, we directly reference fontawesome fonts served up as part of the html-manager `/dist` assets, and there is no `?v` parameter, just a version number for the html manager.

So this doesn't seem to be the problem that I thought it was. Given our proximity to a release, I now recommend we take a look at this after our release, we want to switch to jsdelivr because of a bigger network, etc.

**Comment by maartenbreddels** [comment]
👍

**Comment by chrisvfritz** [comment]
We actually used to use jsDelivr for everything, but moved to unpkg to be able to use specific builds. Now that jsDeliver can do that too, I've moved all non-Vue CDN links back there and may soon update the Vue links as well.

**Comment by jasongrout** [comment]
I think now is a good time to switch the default to jsdelivr for ipywidgets 8.0

**Comment by mlucool** [comment]
> Does it makes sense to be able to set custom CDN (in the form of an environment variable)?

This would be helpful as part of this work.

**Comment by jasongrout** [comment]
> > Does it makes sense to be able to set custom CDN (in the form of an environment variable)?
> 
> This would be helpful as part of this work.

That is already done and released in #2185.

**Comment by jasongrout** [comment]
As an update, it appears that jsdelivr is still much larger than unpkg (like [4x more traffic](https://w3techs.com/technologies/comparison/cd-cdnjs,cd-jsdelivr,cd-unpkg)).
