### ISSUE TITLE
Holding sync sends empty sync messages

### ISSUE THREAD

**Issue by vidartf** [jupyter-widgets/ipywidgets#1631]
The following code sends an empty sync message over the wire:
```python
w = ipywidgets.Widget()
with w.hold_sync():
    pass
```

Expected behavior: If `_states_to_send` is empty, nothing is sent.

**Comment by jasongrout** [comment]
We could fix this in two places: 

https://github.com/jupyter-widgets/ipywidgets/blob/master/ipywidgets/widgets/widget.py#L633 - and check to see if there is state to send before calling send_state

https://github.com/jupyter-widgets/ipywidgets/blob/master/ipywidgets/widgets/widget.py#L480 - and never send an empty sync message.

I'm leaning towards the latter, as I don't think it generally makes sense to send empty sync messages. What do you think?

**Comment by vidartf** [comment]
No strong preference either way.
