### ISSUE TITLE
Get width and height of widget?

### ISSUE THREAD

**Issue by OliverEvans96** [jupyter-widgets/ipywidgets#1639]
When a widget is instantiated, `layout.height` and `layout.width` are empty. Is there a way to get the size of a widget before these properties are explicitly set?

Thanks,
Oliver

**Comment by jasongrout** [comment]
The layout width and height attributes are never explicitly set. Their only purpose is to override the actual width and height on the front end if they *are* set.

That said, most of the widgets have a fixed default width and height from the widgets CSS. Which widget are you talking about?

If you have a custom widget, you can always calculate the width and height after it is rendered and send it back to python, of course.

**Comment by OliverEvans96** [comment]
I didn't have a specific widget in mind, it was just an issue I kept
running in to.

Where in the source can I find the default values? Better yet, is there a
table in the documentation? (That sounds easy - I could do that)

With custom widgets, you're referring to calculating the size in js, then
sending back to Python?

It seems to me like having width and height properties automatically set on
widget creation would be nice. Do you agree? Any reason it would be
difficult or undesirable?

Thanks!
Oliver

**Comment by jasongrout** [comment]
> Where in the source can I find the default values? Better yet, is there a
> table in the documentation? (That sounds easy - I could do that)

I think the css file you're looking for is at https://github.com/jupyter-widgets/ipywidgets/blob/master/packages/controls/css/widgets-base.css. It may be easier to just display a particular widget and use the browser debugging tools to get the size of the DOM node. I think a table may go out of date pretty quickly, so I would hesitate to make one. What do you think?

> With custom widgets, you're referring to calculating the size in js, then
> sending back to Python?

Yes.


> It seems to me like having width and height properties automatically set on
> widget creation would be nice. Do you agree? Any reason it would be
> difficult or undesirable?

To me it sounds difficult and not that useful in my experience. Am I missing a usecase here? Some widgets will change height based on attributes (like the rows attribute of a textbox or listbox). Others may expand to fill their space (like the HTML widget). Custom widgets could have one size on creation, but then later change, which we wouldn't see.

Why do you want to know the width and height of a widget without setting it?

**Comment by OliverEvans96** [comment]
I see. That all makes sense. I agree that a table would go out of date
pretty fast - probably not a good idea.  I suppose the only reason that I
hesitated to set the size of my custom wishes on creation is to allow them
to expand to fill screen real estate. That, and I figured that I would just
use the defaults if possible.

Thanks for the tips!
Oliver

**Comment by jasongrout** [comment]
If you want them to expand, you can always set the height/width to `100%` or `initial`. Any valid CSS height/width will do.

**Comment by OliverEvans96** [comment]
Ah, of course! Thanks!

**Comment by jasongrout** [comment]
Closing as resolved.
