### ISSUE TITLE
block python code execution until getting data from frontend?

### ISSUE THREAD

**Issue by hainm** [jupyter-widgets/ipywidgets#1640]
Hi,

assuming backend send request to render an image to frontend.

```
# all 3 commands are in the same cell
from ipywidgets import Image
view.render() # -> ask frontend to send `_image_data` and update to view._image_data
Image(view._image_data) # -> How can I let this line to wait until _image_data is updated?
```

seems like a non-trivial task to me. But if you have any idea or code example,  I really appreciate. thanks and cheers.

**Comment by jasongrout** [comment]
There are several ways to do this. See https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/examples/Widget%20Asynchronous.ipynb for some examples.

**Comment by hainm** [comment]
Thanks Jason.
