### ISSUE TITLE
Sync widget property from python before widget is rendered

### ISSUE THREAD

**Issue by choudhary001** [jupyter-widgets/ipywidgets#1641]
Hi,
I have some property on python side in my custom widget that i want to sync before my widget is rendered. Is there any way to ensure this for example, any widget method i can override to do this before rendering happens. OR if i can trigger sync'ing to pick the latest value whenever rendering happens from javascript side.

I have tried overriding __repr__ and _repr_keys_ but they don't seem to work. The documentation mentions below but i am not sure which repr method it is referring to.
"After the Widget has been constructed, it can be displayed. Calling display(widgetinstance) causes a specially named repr method in the widget to run. "

Thanks,
Abhishek

**Comment by jasongrout** [comment]
`display()` calls the `_ipython_display_` function: https://github.com/jupyter-widgets/ipywidgets/blob/a28007e3a298672ad03b863b2cf472d49b719f61/ipywidgets/widgets/widget.py#L700

**Comment by choudhary001** [comment]
Thanks for the reply, overriding _ipython_display_ worked for me. Are there any issues if I try to sync some widget attributes in _ipython_display_ before calling super class method?

**Comment by jasongrout** [comment]
I don't think there would be any problem per se. Just be aware that there may be multiple views on a page, so what happens if the widget is displayed twice? When will the first one be updated? Only when a second is displayed?

**Comment by choudhary001** [comment]
> When will the first one be updated? Only when a second is displayed?
I am fine with first one getting updated only when second is displayed. But I am finding that the first view is not getting updated with latest value even after the second view is displayed and the second view has the updated value.

```
    def _ipython_display_(self):
        self._render_options = self._get_chart_options()
        super(MyWidget, self)._ipython_display_()

```

**Comment by jasongrout** [comment]
If the first view only has a render, and no update method, it won't be updated.

render gets called only on the initial render. update gets called any time a data attribute gets changed.

Do you have your code posted online somewhere?

**Comment by hainm** [comment]
@choudhary001 I am not sure about your implementation, so just show what [nglview](https://github.com/arose/nglview) handle stuff before the widget is displayed.

Basically if the widget is not displayed, a series of user's command will be put in stack and will be fired after the widget displayed.
https://github.com/hainm/nglview/blob/5fda0af1fc6a5d0977a84c1b642e13be5daa913b/nglview/widget.py#L334-L340

**Comment by jasongrout** [comment]
Closing as resolved (or at least the conversation has stalled) - @choudhary001, please reopen if you'd like to continue the conversation.
