### ISSUE TITLE
Page refresh for notebook does not work for widgets with buffers

### ISSUE THREAD

**Issue by maartenbreddels** [jupyter-widgets/ipywidgets#1642]
Using latest ipyvolume on pypi:
```python
import ipyvolume as ipv
ipv.examples.klein_bottle()
```
Refresh, and one of my deserializers is missing a .buffer property.

**Comment by jasongrout** [comment]
to install, `pip install --pre ipyvolume`? Or can you post a simple self-contained example?

**Comment by maartenbreddels** [comment]
Yes, that should work (not sure if I have time for that soon)

**Comment by jasongrout** [comment]
I'm working on a simple example by converting the Image widget to use binary transfer now that we have it. I think it will be good to have at least one controls widget using the binary transfer.

**Comment by jasongrout** [comment]
At least one problem is https://github.com/jashkenas/underscore/issues/2692 - since underscore seems to treat all dataviews and array buffers as equal, the appropriate change handlers are not called when a binary attribute is set if it is just a dataview or array buffer.

**Comment by maartenbreddels** [comment]
What does lodash say?

**Comment by jasongrout** [comment]
Looking more into it, it seems that underscore is pretty much abandoned at this point. Lodash 4.17.4 returns the correct result, but it's not clear at all how to change backbone to depend on lodash without actually changing the backbone package to something else.

I think this is another vote for replacing backbone in widgets.

**Comment by jasongrout** [comment]
For now, I'm working on a workaround.

**Comment by maartenbreddels** [comment]
See also my msg https://github.com/jupyter-widgets/ipywidgets/issues/1339#issuecomment-300569096 about _.eq being really slow (comparing each element), so it's slow and/or broken. Would be nice if that can be worked around as well.

**Comment by jasongrout** [comment]
ah yes, I thought I remembered seeing another problem with underscore's equality checking. Thanks.

**Comment by jasongrout** [comment]
Actually, my workaround is to default to that really slow checking! I'm not sure of another way to work around the deficiency in underscore.
