### ISSUE TITLE
Detect if widget Javascript is available

### ISSUE THREAD

**Issue by melund** [jupyter-widgets/ipywidgets#1646]
Here is a quick question. I have some code that uses ipywidgets when running the code from an IPython Notebook. When I run from normal python console I fall back to some ASCII graphics instead.  

This works well, except in the cases where it is running it in other types of IPython consoles. 

Then  I get 

```
Widget Javascript not detected. It may not be installed or enabled properly.
```

How do I programmatically detect if widget javascript is available before trying to use the widgets in the code?

/Morten

**Comment by jasongrout** [comment]
I think the root problem goes away in ipywidgets 7, since we now use the standard display system. Can you try our rc?

```
pip install --pre ipywidgets
```

**Comment by jasongrout** [comment]
Part of the Jupyter architecture is that you should not customize your kernel code based on the current frontend. Part of the reason for this is that you may have kernel code talking to several different frontends simultaneously (like a notebook and a console simultaneously). So the way to customize displays like this is to make a view message with fallback options, such as your ascii graphics.

**Comment by jasongrout** [comment]
(adding a future label, because I'm not sure if it's easy to build a display message that has both widget related things and a customized fallback rendering)

**Comment by melund** [comment]
Thanks @jasongrout . I will try with ipywidget 7. 

 I am using the widgets to display a progress bar. If there are any possiblity that it could fail I want to fall back to a ASCII based progress bar.

**Comment by jasongrout** [comment]
How do you plan to update the ascii-based progress bar?

**Comment by melund** [comment]
Before I started to use the widgets I only had the ASCII progress bar.  When running from IPython I would try to call `IPython.core.display.clear_output()` otherwise, I would just issue a `\r` and print the updated progress bar. 

Widgets are much nicer. But I need a way to fall back, for example in QT console which is used in Spyder or PyCharm

**Comment by jasongrout** [comment]
I don't see a way to do this right now. If QT console had updateable display outputs (a relatively recent feature), I could see it being possible, but I don't think it does.

**Comment by jasongrout** [comment]
Closing as answered. In a system that supports updateable display outputs, I think you might be able to implement both an ascii progress bar and a widget.
