### ISSUE TITLE
Output can end up in previous cell

### ISSUE THREAD

**Issue by maartenbreddels** [jupyter-widgets/ipywidgets#1648]
Originally reported by @chrisjsewell https://github.com/maartenbreddels/ipyvolume/pull/49#issuecomment-322384293
```python
import ipyvolume as ipv
ipv.figure(width=200,height=200)
ipv.examples.klein_bottle()
.. next cell
ipv.screenshot() # returns a PIL image
```
gives:
![screen shot 2017-08-17 at 19 29 28](https://user-images.githubusercontent.com/1765949/29425223-cadd91ae-8382-11e7-8697-c2e844bcf216.png)

So the output ends up in the previous cell. If I put in some print statement in this [while loop](https://github.com/maartenbreddels/ipyvolume/blob/c209b80ab638a4eb0e8a2a2273fd1289315c2ab1/ipyvolume/pylab.py#L671) it goes fine.
I tried to isolate the bug, but cannot reproduce it otherwise.

**Comment by jasongrout** [comment]
It sounds like this has to do with the callbacks. I think the question is what the screenshot function does.

**Comment by jasongrout** [comment]
Where is the screenshot function?

**Comment by maartenbreddels** [comment]
Could be, yes, https://github.com/maartenbreddels/ipyvolume/blob/c209b80ab638a4eb0e8a2a2273fd1289315c2ab1/ipyvolume/pylab.py#L686

**Comment by jasongrout** [comment]
Or can you explain how the screenshot function works? i.e., what messages are sent, etc.

**Comment by maartenbreddels** [comment]
* screenshot calls [_screenshot_data](https://github.com/maartenbreddels/ipyvolume/blob/c209b80ab638a4eb0e8a2a2273fd1289315c2ab1/ipyvolume/pylab.py#L646)
 * which attached a handler for the on_screenshot event https://github.com/maartenbreddels/ipyvolume/blob/c209b80ab638a4eb0e8a2a2273fd1289315c2ab1/ipyvolume/pylab.py#L658
 * screenshot handlers are part of the [Figure widget](https://github.com/maartenbreddels/ipyvolume/blob/c209b80ab638a4eb0e8a2a2273fd1289315c2ab1/ipyvolume/widgets.py#L153)
 * on the js side it is [here](https://github.com/maartenbreddels/ipyvolume/blob/c209b80ab638a4eb0e8a2a2273fd1289315c2ab1/js/src/figure.js#L616), it makes a screenshot and send the data back (the handler is called)
 * The [busy loop](https://github.com/maartenbreddels/ipyvolume/blob/c209b80ab638a4eb0e8a2a2273fd1289315c2ab1/ipyvolume/pylab.py#L671) waits till the screenshot is made.

**Comment by jasongrout** [comment]
I think the thing to do is to trace through:

1. the messages sent back and forth, keeping track of their message id
2. set a breakpoint on the send method on the js side.

My guess is that the view's callbacks are being registered for the send message somehow, so any output from the send message is sent to the output area the view is in.

I'm a bit confused by the busy loop. Did you think about doing this using some of the examples from https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/examples/Widget%20Asynchronous.ipynb ?

**Comment by jasongrout** [comment]
Or it may have to do with the busy loop doing an iteration in ipython and somehow that is confusing the message ids and callback system.

**Comment by jasongrout** [comment]
I think you ought to change the busy loop to use one of the methods in the async widgets notebook.

**Comment by maartenbreddels** [comment]
I was planning to do that, I counting on you suggesting that ;). However, I wanted to make sure this wasn't exposing a serious bug. I could try to trace back where this 'bug'(?) was introduced by installing an other beta version. But lets not keep this in the way of the release.

**Comment by jasongrout** [comment]
It could be a bug, but it could also be an effect from (ab?)using the do one iteration function. I agree it probably shouldn't hold up a release.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to ask on the [discourse site](https://discourse.jupyter.org/c/jupyterhub/10) or request that we reopen this issue. Thanks! 🌻
