### ISSUE TITLE
Fontawesome should be in embedded version

### ISSUE THREAD

**Issue by maartenbreddels** [jupyter-widgets/ipywidgets#1649]
@chrisjsewell  reported [here](https://github.com/maartenbreddels/ipyvolume/issues/41#issuecomment-322911209) that the embed-amd.js module downloads fontawesome from unpkg. I can confirm that I do not see any css part of fontawesome in html-manager/dist/embed-amd.js.

**Comment by chrisjsewell** [comment]
haha, timing, I just raised the issue as well jupyter-widgets/ipywidgets#1650

**Comment by maartenbreddels** [comment]
1 minute apart.. amazing :)
