### ISSUE TITLE
Help using handsontable with ipywidgets

### ISSUE THREAD

**Issue by clarka34** [jupyter-widgets/ipywidgets#1651]
I was wondering if anyone had any suggestions on how to make handsontable work with the most recent version of ipywidgets. I have been following instructions from:

https://gist.github.com/rossant/9463955
https://gist.github.com/rdhyee/9897356

However, I cannot get these instructions to work with the current versions of the notebook/ipywidgets (installed using: https://github.com/mwcraig/scipy2017-jupyter-widgets-tutorial). I have put the .js and .css for handsontable in the .jupyter/custom folder, but I am still not having any luck. Any help would be greatly appreciated!

**Comment by jasongrout** [comment]
I'd suggest starting with the widget cookiecutter: https://github.com/jupyter-widgets/widget-cookiecutter

Generate the sample widget with that, then modify it as appropriate.

Let us know if you have any questions!

**Comment by jasongrout** [comment]
Closing as answered. Please let us know if you have any other questions!
