### ISSUE TITLE
jupyterlab_widgets sys-prefix

### ISSUE THREAD

**Issue by sterlinm** [jupyter-widgets/ipywidgets#1653]
I've just installed jupyterlab in a conda environment and am trying to get widgets working. I've got jupyterlab version 0.26.5 installed and jupyterlab-widgets 0.6.15. ipywidgets is 6.0.0.

I installed jupyterlab_widgets and then tried to run `jupyter labextension install --sys-prefix --py jupyterlab_widgets`. I get the error message:

```
Bad config encountered during intialization:
Unrecognized flag: '--sys-prefix'
```

**Comment by jasongrout** [comment]
You'll need to have the latest prerelease for widgets to work in jupyterlab:

```
pip install --pre ipywidgets
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```

**Comment by sterlinm** [comment]
Thanks! When I try to run the prerelease version it says requirements are already met:
`Requirement already satisfied: ipywidgets in c:\users\msterling\appdata\local\continuum\anaconda3\envs\lab\lib\site-packages` but then when I run the second command it complains that `'npm.cmd' is not recognized`.

Trying to get myself setup for the tutorials at JupyterCon next week.

**Comment by jasongrout** [comment]
There is a plan to release a new version of jupyterlab, probably Monday, and we plan to release the next version of ipywidgets over the weekend too, so it's maybe best to wait.

**Comment by jasongrout** [comment]
but if you want to set up something now, let me know and I can walk you through it.

**Comment by sterlinm** [comment]
No I'm happy to wait until next week. I'm a bit unclear on what best practices are for installing ipywidgets and using multiple environments in jupyter notebook and jupyterlab. It's one of the things I'm hoping to learn about next week. Thanks!

**Comment by jasongrout** [comment]
Great. We hope to post instructions soon, and we can talk about it at the tutorial too.

**Comment by sterlinm** [comment]
Hi Jason, would now be a good time to set up my environment for the tutorials tomorrow (both widget and jupyterlab)?

**Comment by jasongrout** [comment]
Widgets is released, and should work fine in the classic notebook.

I think they're still planning to release jupyterlab 0.27, so you might hold off on that.

**Comment by mischki** [comment]
Hi, I have a similar problem - I am ipywidgets (e.g. sliders) work fine in normal jupyter but not in jupyter lab. 

Running anything with --sys-prefix doesn't seem to work:  

$ jupyter labextension install --sys-prefix --py jupyterlab_widgets
Install labextension(s)

Options
-------

Arguments that take values are actually convenience aliases to full
Configurables, whose aliases are listed on the help line. For more information
on full configurables, see '--help-all'.

--debug
    set log level to logging.DEBUG (maximize logging output)
--generate-config
    generate default config file
-y
    Answer yes to any questions instead of prompting.
--no-build
    Defer building the app after the action.
--dev-build
    Build in Development mode
--clean
    Cleanup intermediate files after the action.
--log-level=<Enum> (Application.log_level)
    Default: 30
    Choices: (0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL')
    Set the log level by value or name.
--config=<Unicode> (JupyterApp.config_file)
    Default: ''
    Full path of a config file.
--app-dir=<Unicode> (BaseExtensionApp.app_dir)
    Default: ''
    The app directory to target

To see all available configurables, use `--help-all`

Bad config encountered during initialization:
**Unrecognized flag: '--sys-prefix'**

**Comment by jasongrout** [comment]
The instructions for installing into jupyterlab are at https://github.com/jupyter-widgets/ipywidgets/tree/master/packages/jupyterlab-manager#package-install

**Comment by jasongrout** [comment]
(You need to do `jupyter labextension install @jupyter-widgets/jupyterlab-manager`)

**Comment by mischki** [comment]
Thanks,
Followed the instructions. No dice.
