### ISSUE TITLE
code to reproduce output from "Widgets -> Embed Widgets"

### ISSUE THREAD

**Issue by hainm** [jupyter-widgets/ipywidgets#1654]
hi,

I am working embedding `nglview`. The "Widgets -> Embed Widgets" works nicely (I can see the render after open the html file).

However, using the python API won't give the same expectation.
```
embed.embed_minimal_html('index2.html', [view], requirejs=True)
```

I guess I miss something here. Can you help? thanks

<img width="657" alt="screen shot 2017-08-17 at 8 52 45 pm" src="https://user-images.githubusercontent.com/4451957/29439784-12570c3a-838e-11e7-940f-774f312a3b2d.png">

**Comment by hainm** [comment]
Please see attach files for working (with "Widgets -> Embed Widgets") and non_working html
(from API)

[working.txt](https://github.com/jupyter-widgets/ipywidgets/files/1233001/working.txt)

[non_working.txt](https://github.com/jupyter-widgets/ipywidgets/files/1233003/non_working.txt)

**Comment by jasongrout** [comment]
The non-working example is missing some key properties in the widget state, namely the _view_* properties.

**Comment by hainm** [comment]
Is that intentional?

**Comment by hainm** [comment]
uhm, I actually get the same error if trying sphinx-jupyter PR from https://github.com/jupyter-widgets/jupyter-sphinx/pull/16

<img width="1275" alt="screen shot 2017-08-17 at 9 18 49 pm" src="https://user-images.githubusercontent.com/4451957/29440315-c753be0a-8391-11e7-908b-b5277a2355d0.png">

**Comment by hainm** [comment]
By the way, ipywidgets 7 is awesome and I love it much. ;)

**Comment by jasongrout** [comment]
It is intentional (default is to get the data without defaults). I'm considering whether it is the best, though. Usually these `_view_*` properties are set as defaults in javascript. Do your javascript models have the appropriate `_view_*` defaults defined?

**Comment by jasongrout** [comment]
The defaults are only defined on the model, not the view. The defaults defined at https://github.com/arose/nglview/blob/master/js/src/widget_ngl.js#L27 should be moved up to the model at https://github.com/arose/nglview/blob/master/js/src/widget_ngl.js#L17

**Comment by jasongrout** [comment]
> By the way, ipywidgets 7 is awesome and I love it much. ;)

Thanks! And thanks for testing things out!

**Comment by hainm** [comment]
> Do your javascript models have the appropriate _view_* defaults defined?

I am not sure what you meant here (due to my lack of understanding about how ipywidgets works).

But below is a short chunk of codes:
https://github.com/arose/nglview/blob/84a5873d98a703e1057b845026faae6aa4130f60/js/src/widget_ngl.js#L16-L36

**Comment by hainm** [comment]
> It is intentional (default is to get the data without default values).

so, are you going to change it? If not yet, what's the idiom to make `nglview` work with `sphinx-jupyter`? thanks.

**Comment by jasongrout** [comment]
Move these three lines (https://github.com/arose/nglview/blob/master/js/src/widget_ngl.js#L32-L34) to here (https://github.com/arose/nglview/blob/master/js/src/widget_ngl.js#L22). Delete the defaults() function in the view.

**Comment by hainm** [comment]
wow, work like a charm. Thanks Jason. (see the attached `wow.txt (-> wow.html`) and the figure).

[wow.txt](https://github.com/jupyter-widgets/ipywidgets/files/1233335/wow.txt)

<img width="1271" alt="screen shot 2017-08-18 at 12 55 57 am" src="https://user-images.githubusercontent.com/4451957/29444744-0cc352ac-83b0-11e7-919b-381da24ffa16.png">

cc @arose 

Happy to close this issue.

@jasongrout  PS: May be updating docs if there is not yet. :)
