### ISSUE TITLE
requirejs=True as default for embed.embed_snippet

### ISSUE THREAD

**Issue by hainm** [jupyter-widgets/ipywidgets#1655]
For most of the notebook users, I think the command below should just work for them

```
embed.embed_minimal_html('hi.html', [view])
```

In current code, user need to set `requirejs=True`. What do you think about use 'True' as default?

**Comment by jasongrout** [comment]
Good point. requirejs=True would be the backwards-compatible option, since we only supported requirejs-based embeddings before.
