### ISSUE TITLE
Add a note about clearing widget state by refreshing and restarting kernel

### ISSUE THREAD

**Issue by hainm** [jupyter-widgets/ipywidgets#1657]
Original title: Sometimes Embed Widgets does not correctly capture synced attribute

I am not sure how to let you reproduce the issue, but I just describe here.

For example, `_ngl_loadFile_msg_archive` is a List

You can see the figure to see that ` _ngl_loadFile_msg_archive ` in Embed Widget is empty

<img width="993" alt="screen shot 2017-08-17 at 11 09 53 pm" src="https://user-images.githubusercontent.com/4451957/29442731-74ac9a86-83a1-11e7-89d7-2b0ca2770c81.png">

The grey was got from `view.get_state()`. Using `7.0.0rc0`.

**Comment by hainm** [comment]
I am trying to make an easy example to reproduce the issue, however, getting another

<img width="1276" alt="screen shot 2017-08-17 at 11 15 09 pm" src="https://user-images.githubusercontent.com/4451957/29442814-0286392a-83a2-11e7-938c-35f19de8a53a.png">

I did try to clear notebook widget state but the notebook still remember the deleted cell (display NGLView widget before).

**Comment by jasongrout** [comment]
> The grey was got from view.get_state().

A view doesn't have a `get_state()` method in base ipywidgets. Is this a view method that ngl added?

**Comment by hainm** [comment]
No

<img width="706" alt="screen shot 2017-08-17 at 11 23 35 pm" src="https://user-images.githubusercontent.com/4451957/29443010-2673ad62-83a3-11e7-9a02-b9f33cbd1a8a.png">

**Comment by hainm** [comment]
<img width="726" alt="screen shot 2017-08-17 at 11 24 45 pm" src="https://user-images.githubusercontent.com/4451957/29443029-4852907e-83a3-11e7-9420-a9db89c82c3e.png">

**Comment by jasongrout** [comment]
Okay, so we're talking about the python `get_state` method having a different value than the javascript state?

**Comment by jasongrout** [comment]
1. A common problem with the List() trait is if it is modified in place, the modifications will not be synced to javascript. I usually use Tuple, which means that people have to set the whole list.
2. The next thing to look at is if an appropriate sync message was sent across the websocket. If it was, then the problem is on the js side. If it wasn't, the problem is on the python side.

**Comment by hainm** [comment]
> A common problem with the List() trait is if it is modified in place, the modifications will not be synced to javascript. I usually use Tuple, which means that people have to set the whole list.

oh, you remind me about my observation before. Yes, you are right. Should do something like

```
x.y = [...] rather x.y.append(...)
```
This answer my 1st question.

## 2nd issue
but if you look at above figure, I cleared all nglview related code, adding new code, did do `x.y = ['my work']` but the notebook still remember the old state (having nglview Widget).

**Comment by jasongrout** [comment]
The ngl widget state is still there - it could be displayed again if you wanted. To clear out the browser-side state, you'd need to restart the kernel and refresh the page. Actually, restarting the kernel should be enough too.

**Comment by jasongrout** [comment]
> Actually, restarting the kernel should be enough too.

Hmm...actually, probably not. Otherwise any existing widgets in outputs would disappear. Instead, those widgets should show as broken, but would still be embedded in a page.

So, restart the kernel and refresh the page to clear the widget state from the javascript side.

**Comment by hainm** [comment]
Can you update docs about that? thanks.

**Comment by jasongrout** [comment]
Sure. Where would you look for it?

**Comment by hainm** [comment]
https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/embedding.md#embedding-widgets-in-html-web-pages

**Comment by jasongrout** [comment]
Perfect, thanks. I'll add a note.

**Comment by hainm** [comment]
uhm, I have some thoughts:

- As an user, the behaviour of Embed Widgets is surprising. Saying user play with his/her notebook, create a bunch of widgets, change their mind to delete all of them and then create a new widget. They are expecting "Embed Widget" give what they want. How's about just save state of current widgets existing in the notebook page?

- To me, `view.get_state` return the same kind of data as Embed Widget. How's about using `get_state` to generate HTML code if using "Embed Widgets"? Use case: `nglview` has a bunch of large data that should not be synced with frontend. However, we can define our own `get_stage` 
to get the data on the fly when user click "Embed Widgets" (all are just matter of make a HTML template, right?). 

nglview certainly can create its own method `nglview.embed_html(view, ...)` but this will be different from the way other packages save their states.

```
def get_state(self, ...):
    state = super(NGLWidget, self).get_state(...)
    stage['some_big_data'] = ...
```
-> In the frond end code, we (nglview) will implement code to handle "some_big_data".

**Comment by jasongrout** [comment]
Can you open a new issue with these discussion items?

**Comment by hainm** [comment]
I will.
