### ISSUE TITLE
ipywidgets not working in dev mode

### ISSUE THREAD

**Issue by rsinha25** [jupyter-widgets/ipywidgets#1663]
Hi,

I am getting this error on console when I run JLab in dev mode, while using ipywidgets:

```
import ipywidgets as ipyw
ipyw.Text("hello")
```

```
Uncaught (in promise) Error: Object 'jupyter.widget' not found in registry
    at default.js:1469
    at Promise (<anonymous>)
    at Object.loadObject (default.js:1448)
    at DefaultKernel._handleCommOpen (default.js:897)
    at DefaultKernel._onWSMessage (default.js:729)
    at WebSocket._ws.onmessage (default.js:653)
```
However it works perfectly fine when I start jlab normally.
Any help with this?

**Comment by maartenbreddels** [comment]
Jupyter lab requires running extra commands, it's better to wait a few days for the for the new jlab release. But if you want, you should get a working version if you do:
```bash
conda create -n jupytercon7 jupyterlab traittypes pillow
source activate jupytercon7

pip install --pre ipywidgets bqplot ipyleaflet ipyvolume pythreejs ipywebrtc
jupyter nbextension enable --sys-prefix --py widgetsnbextension
jupyter nbextension enable --sys-prefix --py bqplot
jupyter nbextension enable --sys-prefix --py ipyleaflet
jupyter nbextension enable --sys-prefix --py ipyvolume
jupyter nbextension enable --sys-prefix --py pythreejs
jupyter nbextension enable --sys-prefix --py ipywebrtc

jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.25.10
jupyter labextension install jupyterlab-volume@0.1.0
jupyter labextension install jupyterlab-webrtc@0.2.1
```
Maybe you should install ipywidgets==7.0.0rc2 for this, the relase (just a day out) may not work with this set of commands.

**Comment by rsinha25** [comment]
Hey, so I am trying this with the latest Jlab: 0.27.0.dev, because the ipywidgets 7.0.0, was released just yesterday.
And it works fine when I start it as `jupyter lab` , however it doesn't work when I start it in dev mode:  jupyter lab `--dev-mode`

**Comment by maartenbreddels** [comment]
Sorry, misread your first msg.

**Comment by rsinha25** [comment]
Here are the steps I did:

```
git clone JLab
cd jlab
pip install -e .
npm install
pip install ipywidgets --pre
jupyter labextension install @jupyter-widgets/jupyterlab-manager

```
`jupyter lab`

ipywidgets work fine 

`jupyter lab --dev-mode `

Get `"A Jupyter Widget"` on notebook and 
```
Uncaught (in promise) Error: Object 'jupyter.widget' not found in registry
    at main.bundle.js:196343
    at Promise (<anonymous>)
    at Object.loadObject (main.bundle.js:196322)
    at DefaultKernel._handleCommOpen (main.bundle.js:195771)
    at DefaultKernel._onWSMessage (main.bundle.js:195603)
    at WebSocket._ws.onmessage (main.bundle.js:195527)
```

on console

run jupyter lab again, now gives the same errors.

**Comment by maartenbreddels** [comment]
Strange, for 0.26.5 it works.

**Comment by rsinha25** [comment]
Did you try with dev mode?

**Comment by maartenbreddels** [comment]
Yes, first normal, then dev, both work (ipywidgets and ipyvolume)

**Comment by rsinha25** [comment]
Alright. Let me try that. Thanks :)

**Comment by rsinha25** [comment]
Just checked out to v0.26.5, found same behaviour

```
git checkout v0.26.5
npm install
npm run build:main

jupyter lab
```

Works fine

jupyter lab --dev-mode

```
Uncaught (in promise) Error: Object 'jupyter.widget' not found in registry
    at default.js:1468
    at Promise (<anonymous>)
    at Object.loadObject (default.js:1447)
    at DefaultKernel._handleCommOpen (default.js:897)
    at DefaultKernel._onWSMessage (default.js:729)
    at WebSocket._ws.onmessage (default.js:653)
```

on console.

**Comment by jasongrout** [comment]
Widgets work with jlab 0.26, and haven't yet been updated to work with the latest master. Would you like to help update them to jlab 0.27 when it is released (probably on Monday)?

**Comment by rsinha25** [comment]
@jasongrout Sure 👍

**Comment by jasongrout** [comment]
We made a release of widgets for jlab 0.27 now, so `jupyter labextension install @jupyter-widgets/jupyterlab-manager` should work in jlab 0.27.

**Comment by drorspei** [comment]
I'm having the same problem as @rsinha25: after installing everything clean, ipywidgets work fine in `jupyter lab`, but not in `jupyter lab --dev-mode` :(

@jasongrout is it possible to get instructions on how to build a cloned directory with ipywidgets, and run in dev-mode?

**Comment by blink1073** [comment]
Running JupyterLab in `--dev-mode` does not use any of the extensions.

**Comment by blink1073** [comment]
See the notes on `addsibling` [here](https://github.com/jupyterlab/jupyterlab/blob/c64a4c68ff95d4016e740dcac355c739d5bda5a4/docs/extensions_dev.md) for the usage of running an extension against the unreleased JavaScript packages in JupyterLab.

**Comment by drorspei** [comment]
Ohhhhh...
Ok.
Great, thanks! I'll read it now.
