### ISSUE TITLE
reopen notebook ipywidget in jlab -  Error creating widget: could not find model

### ISSUE THREAD

**Issue by AbdealiJK** [jupyter-widgets/ipywidgets#1664]
I am using:
 - JupyterLab v0.26.5
 - @jupyter-widgets/jupyterlab-manager@0.26.0
 - ipywidgets-7.0.0
 - widgetsnbextension-3.0.0

I created a notebook with Jupyterlab and some ipywidgets - Textbox and int slider. When I close the notebook and reopen the notebook, the kernel is still attached but the widget has disappeared and instead shows:
```
Error creating widget: could not find model
```

In the notebook, when I close the notebook and reopen it the values in the Textbox and slider are persistent and do not get deleted. Here, to even see the widget again I have to re-run the cell

**Comment by jasongrout** [comment]
(If you want to try contributing this, the code for the classic notebook extension to do this is around https://github.com/jupyter-widgets/ipywidgets/blob/67af059687205f10a339472f72cd86d2b34948c2/widgetsnbextension/src/manager.js#L47

**Comment by spalato** [comment]
Same thing happens with plots opened using `%matplotlib ipympl`.

Current jupyter notebook displays a static image when opening a previous notebook.

**Comment by AbdealiJK** [comment]
Has there been any development on this? 
I can see ipywidget 7.1.2 is out.

I would like to contribute but when I tried it I wasn't able to figure it out =(

**Comment by Alexboiboi** [comment]
Just tested jlab 1.0.0a3 and it seems that this problem has been resolved ;)

**Comment by jasongrout** [comment]
Thanks!
