### ISSUE TITLE
how to use jquery css in embedded mode?

### ISSUE THREAD

**Issue by hainm** [jupyter-widgets/ipywidgets#1666]
Hi,

nglview is using `jquery-ui` for player slider. Things are fine in notebook but the player is not displayed in jupyterlab and in html embedded mode.

Is there any idiom to make the UI work in non traditional notebook? thanks

#### Notebook
<img width="1109" alt="screen shot 2017-08-20 at 7 54 21 pm" src="https://user-images.githubusercontent.com/4451957/29499522-79dfdd8c-85e1-11e7-96c3-4257caf2d141.png">

#### embed 
<img width="877" alt="screen shot 2017-08-20 at 7 54 14 pm" src="https://user-images.githubusercontent.com/4451957/29499528-8824e3a6-85e1-11e7-8965-16fdc50725d7.png">

#### Code
the code is here: https://github.com/arose/nglview/blob/master/js/src/widget_ngl.js#L5-L7

(PS: I tried to add "require('jquery-ui/themes/base/slider.css');" but won't help either). thanks.

**Comment by hainm** [comment]
Another work around is to insert below line in html file:

`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.0/jquery-ui.css">`

**Comment by pbugnion** [comment]
Thanks for raising an issue.

> I tried to add "require('jquery-ui/themes/base/slider.css'); but won't help either

In principle, that's the correct approach. Can you post more information about what goes wrong? (in general, the more details you post, the more likely it is that people can help).

At first glance, it looks like the webpack configuration for nglview doesn't include a CSS loader, so webpack presumably doesn't know what to do with it. At the top of `webpack.config.js`, loaders is defined as:

```
var loaders = [
    { test: /\.json$/, loader: 'json-loader' },
]; 
```

If you want to require CSS, you need a CSS loader. The most common way would be to change this to:

```
var loaders = [
    { test: /\.json$/, loader: 'json-loader' },
    { test: /\.css$/, loader: 'style-loader!css-loader' }
]; 
```

You'll also need to update the dev dependencies in package.json to include `style-loader` and `css-loader`.

**Comment by hainm** [comment]
@pbugnion 

> Can you post more information about what goes wrong? (in general, the more details you post, the more likely it is that people can help).

Hi, I have no issue with loading css and build it. The issue is in the figures I posted. There's no slider displayed in 2nd figure although I already using `require('jquery-ui/themes/base/slider.css');`

**Comment by pbugnion** [comment]
Is this still an issue? I note [PR 687](https://github.com/arose/nglview/pull/687) seems to fix it?

**Comment by hainm** [comment]
Hi

Yeah that PR include css in html file. But that won't help if we want to
use sphinx-jupyter

Hai

**Comment by hainm** [comment]
I think I solved the issue.

Just for the record.

First, include

```javascript
require('jquery-ui/themes/base/all.css')
```

then update `webpack.config.js`
```javascript
var loaders = [
    { test: /\.json$/, loader: 'json-loader' },
    { test: /\.css$/, loader: "style-loader!css-loader" },
    { test: /\.less$/, loader: "style-loader!css-loader!less-loader" },
    { test: /\.(jpg|png|gif)$/, loader: "file" },
];
```

<img width="1272" alt="screen shot 2017-08-30 at 9 10 38 pm" src="https://user-images.githubusercontent.com/4451957/29901753-b6d50d5a-8dc7-11e7-9687-5b71945f250b.png">
