### ISSUE TITLE
CSS for embedding causes blue links on readthedocs

### ISSUE THREAD

**Issue by maartenbreddels** [jupyter-widgets/ipywidgets#1673]
See http://ipyvolume.readthedocs.io/en/latest/index.html for an example, the links in the menu on the left are blue (it actually stars grey, but jumps to blue when the css is injected).

**Comment by pbugnion** [comment]
Is this why all the links are blue on ipywidgets [readthedocs](https://ipywidgets.readthedocs.io/en/latest/)?

**Comment by maartenbreddels** [comment]
I don't think so, since on ipyvolume it starts grey, for ipywidgets it stars blue directly.

**Comment by jasongrout** [comment]
I think this underlying issue causes the problem: https://github.com/jupyterlab/jupyterlab/issues/3257

**Comment by jasongrout** [comment]
I'll leave this open so that once the underlying jupyterlab issue is solved, we can be reminded to update our dependency to pull in the fix.

**Comment by jasongrout** [comment]
FYI, I think JupyterLab just had a release with this fix, so we can go ahead and update to pull it in here.

**Comment by jasongrout** [comment]
We've now updated our dependency.
