### ISSUE TITLE
Widgets not displayed in secondary JupyterLab notebook view

### ISSUE THREAD

**Issue by jonmmease** [jupyter-widgets/ipywidgets#1684]
Jupyterlab has the cool feature of being able to display multiple views of the same notebook. Views can be created by right-clicking the notebook tab and selecting "New View into File".  But it seems that widgets do not show up in the secondary view.

![screen shot 2017-08-28 at 6 42 13 pm](https://user-images.githubusercontent.com/15064365/29796848-89a15fca-8c21-11e7-8fad-9f7726c952bb.png)

I don't know if this functionality is expected to work yet, but it would be awesome if it did. For example, I would like to be able to simultaneously view different bqPlot plots from different sections of a long notebook file.

Versions:
 - ipywidgets 7.0
 - jupyterlab 0.27.0

**Comment by maartenbreddels** [comment]
Indeed a nice feature, my guess it's related to https://github.com/jupyter-widgets/ipywidgets/issues/1664

**Comment by jmmease** [comment]
In that case, I'm guessing that some work would also be needed in order to support JupyterLab's mirrored cells (jupyterlab/jupyterlab#2073) when they land for the beta.

**Comment by jasongrout** [comment]
Good call @maartenbreddels - solving that likely would solve this.

@jmmease - we had widgets working already for mirrored output, so it may just work. Or not, depending on how the mirrored cells are implemented.

**Comment by hainm** [comment]
would be awesome if two mirrors working. Otherwise, not having the message "Error creating widget: could not find model" in second mirror might be nice. (I am thinking about visualize in one notebook and do command stuff in another).

<img width="1270" alt="screen shot 2017-10-09 at 9 48 44 pm" src="https://user-images.githubusercontent.com/4451957/31365910-3df6b6ce-ad3c-11e7-8012-f236c283f6d5.png">

**Comment by michaelaye** [comment]
For that (visualize vs commanding), I thought I had seen in a demo that one can just drag a cell's output out of a notebook to keep it open?

**Comment by anthonyaag** [comment]
I think this is fixed 

<img width="953" alt="image" src="https://user-images.githubusercontent.com/6341861/166332988-36cf20e3-b126-4bed-992d-21a1f51190ec.png">

**Comment by jasongrout** [comment]
I think you're right. Thanks!
