### ISSUE TITLE
Widget Javascript not detected v5.2.2

### ISSUE THREAD

**Issue by hangyao** [jupyter-widgets/ipywidgets#1690]
I'm running ipywidgets 5.2.2 on Windows, Python 3.6, and:
- Jupyter 1.0.0
- Jupyter_client 5.0.1
- Jupyter_console 5.1.0
- Jupyter_core 4.3.0

and encounter this issue:
```
[IPKernelApp] WARNING | Widget Javascript not detected.  It may not be installed
 properly. Did you enable the widgetsnbextension? If not, then run "jupyter nbex
tension enable --py --sys-prefix widgetsnbextension"
```
Also Widgets are not shown in the Notebook.

Running ```jupyter nbextension enable --py --sys-prefix widgetsnbextension``` doesn't solve the issue.

Thanks.

**Comment by jasongrout** [comment]
What version of widgetsnbextension do you have installed?

**Comment by hangyao** [comment]
@jasongrout widgetsnbextension 2.0.0

Thanks.

**Comment by jasongrout** [comment]
Can you either:

1. upgrade to ipywidgets 6 (compatible with widgetsnbextension 2.0), or even better, ipywidgets 7/widgetsnbextension 3
2. Downgrade widgetsnbextension to 1.2.6

**Comment by jasongrout** [comment]
@hangyao, did you get it working now?

**Comment by hangyao** [comment]
@jasongrout I got it working by upgrading to 6 or 7. Thank you! I will close this issue.

**Comment by jasongrout** [comment]
Great, thanks!
