### ISSUE TITLE
Error displaying widget renderer.js:85 Module bqplot, semver range ^0.2.3 is not registered as a widget module

### ISSUE THREAD

**Issue by Vivian-Madu** [jupyter-widgets/ipywidgets#1704]
Ipyhton widget not working in Jupyter lab. I keep getting this error when I try to display a widget, any help?
In notebook, it just shows  
Error displaying widget

**Comment by jasongrout** [comment]
Can you give us the versions of jupyterlab, ipywidgets, `@jupyter-widgets/jupyterlab-manager`, and bqplot (it looks like you're using bqplot?).

Does a basic widget work, i.e., `from ipywidgets import IntSlider; IntSlider()`?

**Comment by jasongrout** [comment]
@Vivian-Madu - any update?

**Comment by jasongrout** [comment]
Closing as non-responsive. @Vivian-Madu - feel free to reopen if you'd like to continue the conversation.
