### ISSUE TITLE
overflow m

### ISSUE THREAD

**Issue by RDeRenzi** [jupyter-widgets/ipywidgets#1707]
I am trying to produce a width and height limited Output widget for a data analysis module composed of classes that creates a complex jupyter notebook widget interface. The part related to overflow is listed below. The result is that the overflow bars appear, but they do not work (dark, as can be seen in the snapshot). Do I go wrong or is it a bug? Thanks for any hint.

![screenshot_mujpy_ovflw](https://user-images.githubusercontent.com/25430702/30247442-2fe7ab6c-9615-11e7-8eb8-cb15f832dbea.png)

        ...
         self.out = Output(layout=Layout(width='100%'))
         thirdrow = HBox([self.out],layout=Layout(height='60px',
                                                  width='100%',
                                                  overflow_y='scroll',
                                                  overflow_x='scroll')) # x and y scroll do not work
         titlewindow = VBox()
         titlewindow_content = [titlerow, secondrow, thirdrow]
         ...

**Comment by jasongrout** [comment]
Great question. Can you make a self-contained example illustrating this that we can work from?

It may be enough to just move the layout you have for the hbox to the output widget itself.

**Comment by jasongrout** [comment]
For example:

```python
from ipywidgets import *
out = Output(layout={'height': '100px', 'overflow_y': 'auto', 'overflow_x': 'auto'})
with out:
    for i in range(10):
        print(i)
out
```

**Comment by jasongrout** [comment]
@RDeRenzi - any update?

**Comment by jasongrout** [comment]
Closing as non-responsive. I hope the solution above worked for you!

Feel free to reopen if you'd like to continue the conversation.
