### ISSUE TITLE
404 error and no such comm target when trying to use ipywidgets

### ISSUE THREAD

**Issue by npyoung** [jupyter-widgets/ipywidgets#1720]
I installed ipywidgets 7.0.1 via conda into a conda root python3 environment. When starting a notebook, I get a 404 when trying to load the extension
```
404 GET /nbextensions/widgetsnbextension.js?v=20170918194201 (171.66.17.71) 3.38ms referer=<my nb server's host IP>/notebooks/<my notebook>.ipynb
```
Followed by an error from IPkernelApp when I try to create and show a widget
```
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.version
```
I shouldn't have to manually enable the extension since I'm using conda, but I tried doing `jupyter nbextension enable --py widgetsnbextension` anyway, which did not solve this.

**Comment by jasongrout** [comment]
> [IPKernelApp] ERROR | No such comm target registered: jupyter.widget.version

This indicates that your javascript is from widgetsnbextension 2. What version of widgetsnbextension and ipywidgets do you have listed in `conda list`?

Do you have the same error when trying from the browser's incognito mode?

**Comment by tensionhead** [comment]
*When starting a notebook, I get a 404 when trying to load the extension*

I had exactly the same (and other) problem(s), however activating it didn't help ("could not Validate"). This line solved it for me:

*jupyter nbextension install --py widgetsnbextension --user*

(I guess for your setup you should leave out the *--user* flag)

And then I did the activation step

*jupyter nbextension enable --py widgetsnbextension*

**Comment by npyoung** [comment]
Results from `conda list`
```
widgetsnbextension        3.0.3                      py_1    conda-forge
widgetsnbextension        3.0.3                     <pip>
ipywidgets                7.0.1                      py_2    conda-forge
```
So it looks like I have version 3 of widgetsnbextension. Force-refresh and incognito give me the same errors as before.

`jupyter nbextension install --py widgetsnbextension --user` and `jupyter nbextension enable --py widgetsnbextension` also don't fix this. `nbextension install`gives me `- Validating: OK`

**Comment by mikeskaug** [comment]
Having the same issue today.

Strangely, it worked a few times, but after making various changes to my conda environment, reinstalling packages and restarting the notebook, it stopped rendering the widget and I noticed a similar 404 error to the one mentioned above:
```
404 GET /nbextensions/widgets/notebook/js/extension.js?v=20170919161620 (::1) 1.64ms referer=http://localhost:8888/notebooks/Untitled.ipynb
```

Here is what I have installed:
```
$ conda list
....
ipywidgets                7.0.1                      py_2    conda-forge
....
widgetsnbextension        3.0.3                      py_1    conda-forge
```

**Comment by mikeskaug** [comment]
Using @tensionhead suggestion above solved it for me.

**Comment by jasongrout** [comment]
Thanks for the report. We switched the conda-forge package to a noarch package in https://github.com/conda-forge/ipywidgets-feedstock/pull/27 - I wonder if that somehow had an effect on the files that are usually copied?

I can check in a few days.

**Comment by jasongrout** [comment]
This is likely the same issue as #1721, and would be an issue with the conda-forge widgetsnbextension package (see https://github.com/conda-forge/widgetsnbextension-feedstock/pull/29 for the PR migrating that to a noarch package).

**Comment by npyoung** [comment]
I tried installing the 3.0.2 version of widgetsnbextension as @beenje's suggests in #1721 to no avail. Now I don't get the `[IPKernelApp] ERROR`, but I still get the 404s and nothing renders. @tensionhead's solution didn't help either (I had to keep the --user flag or it would try to install the extension on my system python).

I also get a warning in my js console after the 404s telling me I need to install ipywidgets 4.0. Seems like a stale warning since the corresponding ipywidgets version is 7.0.

**Comment by jasongrout** [comment]
It seems that #1721 is the same issue - let's move the discussion there so we have one place for trouble-shooting this issue.

**Comment by irodionzaytsev** [comment]
Typical opensource problemsolving - a dozen of useless comments, no working solution. At least you didn't ignore the issue altogether though.

**Comment by jasongrout** [comment]
WIthin a day or two, we had identified and fixed the issue three years ago, as documented above and on #1721. Coming along and posting a snarky complaint three years later does not help move things forward for this issue or the community. We invite you to be uplifting and contribute to the solution, being respectful like everyone else on this issue, in the spirit of the code of conduct: https://github.com/jupyter/governance/blob/master/conduct/code_of_conduct.md#expected-behavior
