### ISSUE TITLE
datepicker cuts out the label (description)

### ISSUE THREAD

**Issue by denfromufa** [jupyter-widgets/ipywidgets#1730]
![image](https://user-images.githubusercontent.com/7870949/30985954-8aa289dc-a457-11e7-9b8a-fd627b4c10d3.png)

**Comment by jasongrout** [comment]
Use `style=dict(description_width='initial')`

**Comment by jasongrout** [comment]
To elaborate - the description width is a fixed width to help in laying out grids of widgets easily. In order to change the width of the description, use the code above, like:

```python
DatePicker(description='Pick an end date', style=dict(description_width='initial'))
```

**Comment by denfromufa** [comment]
@jasongrout this worked great! for longer labels looks like I have to use HBox:

https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/examples/Widget%20Styling.ipynb

**Comment by jasongrout** [comment]
You can also use the new description_width, like above, and also made the total widget wider so that the control isn't too narrow.

```python
DatePicker(description='Pick an really, really far end date', style=dict(description_width='initial'), layout=dict(width='400px'))
```
