### ISSUE TITLE
Can I pass a Dataframe or a function to the interactive widgets as parameters? I tried many times and it seems not work.

### ISSUE THREAD

**Issue by Chandlerwu007** [jupyter-widgets/ipywidgets#1732]

**Comment by jasongrout** [comment]
Can you give us some sample code that you'd like to work?

**Comment by jasongrout** [comment]
@Chandlerwu007 - just following up: can you post a sample of the sort of code you wish would work to discuss a specific usecase?

**Comment by jasongrout** [comment]
@Chandlerwu007 - we don't have a javascript control to represent a dataframe, allow a user to edit it, etc., so I think the direct answer is 'no, that doesn't work right now'. So I'm closing this as answered.

However, I think it would still be useful to talk about your usecase, so please re-open if you'd like to continue to engage in discussion.
