### ISSUE TITLE
Output.layout.border is not rendered in Jupyterlab

### ISSUE THREAD

**Issue by nleclercq** [jupyter-widgets/ipywidgets#1735]
The following code works in the classic notebook but not in Jupyterlab. By 'works' , I mean: the layout border is properly rendered in the classic notebook  but not  in Jupyterlab.

```
from IPython.display import display
import ipywidgets
o = ipywidgets.Output()
o.layout.border = "1px solid green"
display(o)
```

**Comment by jasongrout** [comment]
Thanks! I've reproduced this and am making a fix.
