### ISSUE TITLE
Can't display FloatProgress widget in Jupyter notebook

### ISSUE THREAD

**Issue by haykirstin** [jupyter-widgets/ipywidgets#1736]
Using the most up to date conda package versions for python 3.5:
```
ipython                   6.1.0                    py35_0
ipywidgets                6.0.0                    py35_0
widgetsnbextension        3.0.2                    py35_0 
```
and I have successfully executed the command
```
jupyter nbextension enable --py --sys-prefix widgetsnbextension
```
but I am still unable to get a widget displaying correctly in my jupyter notebook.
Here's the simplified version of the issue:
```
from ipywidgets import widgets
from IPython.display import display

widget_ = widgets.FloatProgress()
display(widget_)
```
which produces the following error message:
```
Widget Javascript not detected.  It may not be installed or enabled properly.
Error rendering Jupyter widget. Widget not found: {"model_id":"0191488c30714c48ab65613100085929"}
```
am I doing something wacky, or is there a package inconsistency?

**Comment by jasongrout** [comment]
The versions of ipywidgets and widgetsnbextension are not compatible. I suggest either upgrading ipywidgets to 7.0 or later , or downgrading widgetsnbextension to 2.*.

**Comment by haykirstin** [comment]
That has worked like a charm. Thank you

**Comment by jasongrout** [comment]
@haykirstin - we'd love to hear how you are using widgets. And I saw your website from your github profile - very, *very* nice! I really like how it very clearly and simply explained things you did with just enough detail and pictures to get me to click on the Find out more links, all the way down to your code.

**Comment by haykirstin** [comment]
Hi @jasongrout - I've not been using widgets directly, only for the progress bar to estimate how long my code will take! It's mostly actually the one implemented in [astropy](https://github.com/astropy/astropy/), which is a fab tool for astronomy work in python.

Thanks for the website complement - I'm just building it up at the moment :)
