### ISSUE TITLE
Pickup the last view a model to execute command?

### ISSUE THREAD

**Issue by hainm** [jupyter-widgets/ipywidgets#1743]
hi,

suppose I have code below

```python
view = nglview.demo()

view # 1st cell
view # 2nd cell

view.download_image()
```

In this case, download_image will be executed twice (2 views). Is there any way to tell that command only executed by last view? thanks.

**Comment by hainm** [comment]
may be
```
                var keys = Object.keys(this.model.views);
                var p = this.model.views[keys.length-1];
                p.then(function(s){          
                    // do something here?
                })  
```

**Comment by hainm** [comment]
so here is our work around

```
    render: funtion(){
    ...
        this.displayed.then(function() {
            this.ngl_view_id = this.get_last_child_id();
            ...
    }

    _downloadImage: function(filename, params) {
        if (this.ngl_view_id == this.get_last_child_id()){
            this.stage.makeImage(params).then(function(blob) {
                NGL.download(blob, filename);
            })
        }
    },
```

**Comment by jasongrout** [comment]
That sounds like a workable way to do it. Thanks for posting the code!

**Comment by jasongrout** [comment]
Note that there is a race condition, in that there may be two views created, but the displayed promise is executed for both after both views are created, so the wrong `this.ngl_view_id` gets set in the displayed promise.

Also note that it's possible that ipywidgets updates may break this code if it uses the .views attribute differently (for example, there is no guarantee that the last created view is the last item in the list).

**Comment by hainm** [comment]
thanks @jasongrout  for you headsup.

**Comment by maartenbreddels** [comment]
I have the same issue in ipyvolume for making screenshots, which I still didn't solve, I'll share my solution here as well when I get to it.
