### ISSUE TITLE
Password missing from documentation

### ISSUE THREAD

**Issue by maartenbreddels** [jupyter-widgets/ipywidgets#1747]
Noticed because of [this questions](https://stackoverflow.com/questions/46645369/is-there-a-way-to-define-a-textbox-for-passwords-with-ipywidgets/46671024#46671024)
that Password is missing at [String widgets](http://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html#String-widgets)

**Comment by jasongrout** [comment]
We should note in the docs that the value is transmitted in plaintext too.

**Comment by maartenbreddels** [comment]
And I guess possibly stored in the widget state, so it could end up in the notebook?

**Comment by jasongrout** [comment]
> And I guess possibly stored in the widget state, so it could end up in the notebook?

Yes, that should be documented too.
