### ISSUE TITLE
serializers returning an object with buffer key in it get treated as buffers

### ISSUE THREAD

**Issue by maartenbreddels** [jupyter-widgets/ipywidgets#1748]
https://github.com/jupyter-widgets/ipywidgets/blob/24f3312897f2694f10fddd207206af0aae10ecce/packages/base/src/utils.ts#L184 and https://github.com/jupyter-widgets/ipywidgets/blob/24f3312897f2694f10fddd207206af0aae10ecce/packages/base/src/utils.ts#L155 are too generous, they should whitelist specific types etc, I noticed this when I returned 
`{'buffer': ar.data.buffer, dtype:arrayToTypes[ar.data.constructor.name], shape:ar.shape}` from a serializer. On the python side I got passed a memory object, instead of a dict.
Might be worth to take a look at https://github.com/jashkenas/underscore/pull/2694/files#diff-0f36b362a0b81d6f4d4bfd8a7413c75dR62 for solving this.

PS: Btw, a simple workaround is not to name it buffer, but other people may get bitten by this.

**Comment by jasongrout** [comment]
+1 to making this more specific with a type whitelist.

**Comment by vidartf** [comment]
@maartenbreddels Just for making sure we're on the same page here, what would be a unit test that currently fails, but which will pass if this is fixed?

**Comment by maartenbreddels** [comment]
From js, if you would serialize a json structure like this:
```
value = {buffer: new Float32Array([1,2,3]).buffer, shape: [3]}
```
It things that value itself is a TypedArray, since it's .buffer property is of `ArrayBuffer`, and only value.buffer is send over the wire, and shape will not be send. Maybe there are more issues, I'm not sure.
