### ISSUE TITLE
tab contents and title overlap with vertical scrolling

### ISSUE THREAD

**Issue by mheilman** [jupyter-widgets/ipywidgets#1754]
If one sets the layout height for a `Tab` widget, then the contents overlap with the title after scrolling down:

![screen shot 2017-10-12 at 4 17 48 pm](https://user-images.githubusercontent.com/181744/31519737-f6103838-af68-11e7-8c0a-66c22b1233b1.png)

Here's some code to reproduce this:

```python
import ipywidgets
from IPython.display import display

out1 = ipywidgets.Output()
tab = ipywidgets.Tab([out1], layout=ipywidgets.Layout(height='400px'))

with out1:
    for _ in range(40):
        print("foo")

tab.set_title(0, "bar")
tab
```

Some version info:

* Python 3.6.2
* ipywidgets 7.0.1
* notebook 5.1.0
* Chrome 61
* Mac OS 10.12.6

**Comment by mheilman** [comment]
My best guess is that this is a CSS issue around [here](https://github.com/jupyter-widgets/ipywidgets/blob/b9e77f9fc6389a6535218287a5a30cd3868084ff/packages/controls/css/widgets-base.css#L900-L948).  The `<ul>` for the tab header/bar end up being about half the height of its `<li>` children that have the tab titles.  Here's a screenshot from the Chrome debug tools:

![screen shot 2017-10-12 at 4 42 38 pm](https://user-images.githubusercontent.com/181744/31520722-70259a98-af6c-11e7-8b34-1578a09c3080.png)

**Comment by jasongrout** [comment]
Right now it's set to `display: flex` in phosphor - I'm inquiring about why it is display: flex to make sure we're not messing up something.

**Comment by jasongrout** [comment]
From @sccolbert, about why the .p-TabBar has `display: flex` (https://github.com/phosphorjs/phosphor/blob/23b9d075ebc5b73ab148b6ebfc20af97f85714c4/packages/widgets/style/tabbar.css#L11)

> it looks like I've planned for people to add leading/trailing content (like a + button or something) to TabBar.node, and have set up the CSS to lay that out properly.

It looks like in JupyterLab, the display: flex is retained, but accompanied by a min-height that sets the height appropriately.
