### ISSUE TITLE
Compatible with JupyterLab 0.28

### ISSUE THREAD

**Issue by ktong** [jupyter-widgets/ipywidgets#1760]
JupyterLab just released 0.28 and currently release of @jupyter-widgets/jupyterlab-manager@0.27.1 is not compatible.

**Comment by ktong** [comment]
Thank @jasongrout & @blink1073 for upgrading it. Is it possible to release it before 7.1?

**Comment by jasongrout** [comment]
Yes, we'll probably release it this week.

**Comment by ktong** [comment]
Cool, thanks @jasongrout

**Comment by jasongrout** [comment]
I just released new versions of everything affected. `@jupyter-widgets/jupyterlab-manager` 0.28 should be compatible with jupyterlab 0.28.

**Comment by ktong** [comment]
Thanks @jasongrout
