### ISSUE TITLE
How to add new items to a HBox after being created

### ISSUE THREAD

**Issue by BenjaPH** [jupyter-widgets/ipywidgets#1764]
What would be the best way to add new items to an HBox once again being instantiated and displayed.

```
import ipywidgets as widgets
from IPython.display import display

HeaderLabels = ['Column-1', 'Column-2', 'Column-3']    
HeaderWidgets= [widgets.Label(Text) for Text in HeaderLabels]
HorizBox = widgets.HBox(HeaderWidgets)

display(HorizBox)
```
After some selection in another widget it is needed to add a new label to the HBox.
The only way I have found to do this is (in the change value event called function) to close it and recreate a new one to be displayed. This is,
```
NewHeaderWidgets=list(HorizBox.children)
HorizBox.close()
NewLabelWidget=widgets.Label('New Column')
NewHeaderWidgets.append(NewLabelWidget)
NewHorizBox = widgets.HBox(NewHeaderWidgets)
display(NewHorizBox, , display_id="1")
```

This works, but there is another straightforward method to do that?
I hope to find a method like 

`HorizBox.children.append(NewLabelWidget)                   # but it is an inmutable tuple an raise an error`

also i have tried to update the display, but the output header is duplicated (the old one is not erased)
```
HorizBox.children=tuple(list(HorizBox.children).append(widgets.Label('New Column')))
update_display(NewHorizBox , display_id="1")
```
It is possible to redisplay the HBox representation with the update in the same cell?

**Comment by jasongrout** [comment]
```python
NewLabelWidget=widgets.Label('New Column')
HorizBox.children += (NewLabelWidget,)
```

**Comment by jasongrout** [comment]
You don't need to redisplay, you just need to set the children to a new tuple containing the original items and the new one. You can add two tuples together to create a new tuple: `(1,2,3)+(4,)` creates `(1,2,3,4)`.  The `+=` is just a shortcut for `HorizBox.children = HorizBox.children + (NewLabelWidget,)`.

**Comment by jasongrout** [comment]
If you preferred, in python 3 you can also use a splatting syntax to create the new tuple: `HorizBox.children = (*HorizBox.children, NewLabelWidget)`

**Comment by BenjaPH** [comment]
Thanks a lot @jasongrout; not only for the correct solution but also for the different ways to do that and its explanations.
I am a newbie in python and all the information is welcome.

**Comment by jasongrout** [comment]
Great! I'm closing this issue as answered, but feel free to open other issues for other questions, or ask on our [gitter channel](https://gitter.im/jupyter-widgets/Lobby), etc.
