### ISSUE TITLE
hide out_prompt_overlay in Output widget

### ISSUE THREAD

**Issue by mheilman** [jupyter-widgets/ipywidgets#1765]
The Output widget shows the overlay on the left side of the output area that lets people collapse an output cell in a notebook (see screenshot below).  It doesn't seem like this is behavior that one would want when using an Output widget.  Would it be possible to hide this overlay by default or make it optional?

![screen shot 2017-10-20 at 12 49 13 pm](https://user-images.githubusercontent.com/181744/31834900-334c0c4a-b595-11e7-8abc-4fa4aee8ea3a.png)

Would it make sense to add some CSS like `.jupyter-widgets-output-area > .out_prompt_overlay {display: none}`?

**Comment by jasongrout** [comment]
That prompt area should be hidden: https://github.com/jupyter-widgets/ipywidgets/blob/3af1317a0b6a9626cefb50b6a855fa9114ee54c8/widgetsnbextension/src/widget_output.js#L113

It's hidden for me, with the element having an explicit style "display: none". Can you check the javascript code to make sure that line above is saying the prompt: false?

What version of the notebook are you using?

**Comment by mheilman** [comment]
It looks like that that line is in the version of the widgets nb extension I have (though I'm looking at webpacked JS here):

![screen shot 2017-10-20 at 1 49 21 pm](https://user-images.githubusercontent.com/181744/31837205-8a208f7a-b59d-11e7-9917-303748149f3e.png)

This is with the current commit in master (3af1317a0b6a9626cefb50b6a855fa9114ee54c8) and notebook==5.1.0

**Comment by jasongrout** [comment]
Huh, I just reproduced it. Looking into it...

**Comment by jasongrout** [comment]
Looks like a bug in the notebook, introduced in https://github.com/jupyter/notebook/pull/2681.

Proposed fix for the notebook at https://github.com/jupyter/notebook/pull/2961

For us, I agree that we should add some stop-gap CSS to get rid of it.

**Comment by jasongrout** [comment]
> Would it make sense to add some CSS like .jupyter-widgets-output-area > .out_prompt_overlay {display: none}?

Do you want submit a PR adding this to https://github.com/jupyter-widgets/ipywidgets/blob/master/widgetsnbextension/src/widget_output.css with an explanatory note pointing to the notebook PR and this discussion?

**Comment by jasongrout** [comment]
(then I'll release a quick widgetsnbextension 3.0.6 with just this fix)

**Comment by jasongrout** [comment]
> Do you want submit a PR

I went ahead and made a PR for it so we can get a fix out before the weekend.
