### ISSUE TITLE
Simplified interface for JupyterLab extension?

### ISSUE THREAD

**Issue by blink1073** [jupyter-widgets/ipywidgets#1781]
Do third party widgets need more than the [registerWidget](https://github.com/jupyter-widgets/ipywidgets/blob/c6520c644eb7bae477e3c8dc559d0771c42709d4/packages/jupyterlab-manager/src/plugin.ts#L115) function?  If not, a simplified token could be in `@jupyter-widgets/base` and third party widgets could be stable already. 

Survey, all using just that function:
[ipyvolume](https://github.com/maartenbreddels/ipyvolume/blob/a24d5ece55c4b36ebd962fe062daecc80dbece99/jslab/index.js)
[bqplot](https://github.com/bloomberg/bqplot/blob/a73a7e5929e194272350fd09b2958973f1745890/jslab/index.js)
[jupyter-matplotlib](https://github.com/matplotlib/jupyter-matplotlib/blob/1d50775d9d25ce19c261fa2f75042be8c3d0b7a3/js/src/labplugin.js)
[nglview](https://github.com/arose/nglview/blob/1c63952b0ab9293593f8d6cea76a218cb806dea2/jslab/index.js#L10)
[pythreejs](https://github.com/jovyan/pythreejs/blob/28193ffce96eb85f522209dd3c33772c11bc8caf/jslab/lib/index.js)
[ipyleaflet](https://github.com/ellisonbg/ipyleaflet/blob/e9061c53f9f80658c020214eb5d8c799d72c2ef2/jslab/index.js#L9)
[ipytalos](https://github.com/qzchenwl/ipytalos/blob/7549f34cce7420e3d1071d6a973c4e1c6120d29a/jslab/index.js)
[ipyscales](https://github.com/vidartf/ipyscales/blob/19e578084c9989c8713dbb962a859facbf905126/packages/jlextension/src/index.ts#L53)
[qgrid-jupyterlab](https://github.com/quantopian/qgrid/blob/7fda48b4abe65a7594641bd0ee0487f5eb1f70c2/jslab/index.js#L12)

These are the ones I knew about plus: https://www.npmjs.com/browse/depended/@jupyter-widgets/jupyterlab-manager

**Comment by blink1073** [comment]
cc @SylvainCorlay @maartenbreddels @hainm

**Comment by blink1073** [comment]
That same registry could be used for both notebooks and consoles (once we had an API for console extensions).

**Comment by blink1073** [comment]
cc @vidartf @chenwl @TimShawver

**Comment by vidartf** [comment]
Pythreejs needs access to the widget manager and certain functions on that in order to create new models from the JS side. Note that it will always get the reference to that widget manager from an existing widget reference (`this.widget_manager`). I'm not sure if this counts as "more than the registerWidget function"?

**Comment by blink1073** [comment]
Does pythreejs need more than [ManagerBase](https://github.com/jupyter-widgets/ipywidgets/blob/master/packages/base/src/manager-base.ts#L137) + a register function?

**Comment by blink1073** [comment]
It looks like [newKernel](https://github.com/jupyter-widgets/ipywidgets/blob/af75872fe0a3ce824f8c33e2bcce75b7bdf392d7/packages/jupyterlab-manager/src/manager.ts#L93) is the only other thing unique to the lab manager class.  Either way, it doesn't depend on any of the notebook or document manager interfaces.

**Comment by blink1073** [comment]
Ah, no, it does expose the [context](https://github.com/jupyter-widgets/ipywidgets/blob/af75872fe0a3ce824f8c33e2bcce75b7bdf392d7/packages/jupyterlab-manager/src/manager.ts#L172) and [rendermime](https://github.com/jupyter-widgets/ipywidgets/blob/af75872fe0a3ce824f8c33e2bcce75b7bdf392d7/packages/jupyterlab-manager/src/manager.ts#L176).

**Comment by vidartf** [comment]
> Does pythreejs need more than ManagerBase + a register function?

No, only ManagerBase.

**Comment by vidartf** [comment]
But it might want to depend on more in the future, e.g. for adding a PNG mime type to the output's bundle.

Details aside: Is the change you have in mind going to make it impossible for more complex behavior, or just make it easier for those extensions that only depend on a subset of the features?

**Comment by blink1073** [comment]
Ideally adding a PNG mime type would be the same abstraction at the Widget Manager level.  

Also ideally, we wouldn't need any JupyterLab specific interfaces moving forward, the way we do with the [classic notebook](https://github.com/jupyter-widgets/ipywidgets/blob/af75872fe0a3ce824f8c33e2bcce75b7bdf392d7/widgetsnbextension/src/manager.js#L26-L28).

Short of that goal, having a simplified interface and a more advanced one for the complex cases would be good as well.

We could also add a new JupyterLab extension type similar to the mime renderer extension so that `jupyter-widgets` are entirely declarative for simple use cases.

**Comment by jasongrout** [comment]
> Ah, no, it does expose the context and rendermime.

This is because of the output widget. Looking at this with fresh eyes, it may make sense to make the output widget part of the widget manager, with access to special properties that are not accessible to normal widgets. There has always been this weird, not-very-clean boundary between the output widget and the widget manager.



> Ideally adding a PNG mime type would be abstracted at the Widget Manager level.

Yes.

**Comment by jasongrout** [comment]
> Looking at this with fresh eyes, it may make sense to make the output widget part of the widget manager, with access to special properties that are not accessible to normal widgets. There has always been this weird, not-very-clean boundary between the output widget and the widget manager.

This is #1788.

**Comment by jasongrout** [comment]
Fixed in #1789.
