### ISSUE TITLE
Widgets in IJulia Notebooks

### ISSUE THREAD

**Issue by cortner** [jupyter-widgets/ipywidgets#1782]
I am trying to use [nglview](https://github.com/arose/nglview) to create a 3D visualisation from an Julia notebook. The object it generates is a `PyObject <nglview.widget.NGLWidget ...>` and looking at the source-code of `nglview` this is a subclass of `ipywidgets.DOMWidget`. When trying to display it using 
```julia
@pyimport nglview as nv
@pyimport IPython.display as ipydisp
ipydisp.display(nv.show_ase(si)). #  `si` is a python object that can be visualised using nglview
```
This generates the error message
```
Widget Javascript not detected.  It may not be installed or enabled properly.
```
The equivalent code works fine from a Python notebook.  Is anybody able to advise what the issue might be?

**Comment by cortner** [comment]
The promised MWE - requires `nglview` which can be installed via 
```
pip install nglview
jupyter-nbextension enable nglview --py --sys-prefix
```

In Python: 
```python 
import nglview as nv
view = nv.show_pdbid("1l2y")
view
```

In Julia:
```julia
using PyCall
@pyimport nglview as nv
@pyimport IPython.display as ipydisp
view = nv.show_pdbid("1l2y")
ipydisp.display(view)
```

**Comment by cortner** [comment]
seems it is [this issue](https://github.com/JuliaPy/PyCall.jl/issues/89)

**Comment by jasongrout** [comment]
I think you're probably right, if you want to use it from pycall. Often the python side is pretty lightweight, though - it may be easier to just rewrite the python side in Julia and interact with the javascript directly. I can imagine that would be pretty straightforward for the ipywidget controls (button, slider, checkbox, etc.).
