### ISSUE TITLE
Custom Widgets

### ISSUE THREAD

**Issue by orpheus92** [jupyter-widgets/ipywidgets#1799]
I recently updated ipywidgets and jupyterlab to 0.28. Basic ipywidgets work fine in jupyterlab. I was trying to build the custom widget by following the tutorial. When I try to specify the JS in the notebook, it reports that JavaScript output is disabled in JupyterLab and when I try to display it, it says Error displaying widget. 
Do I need to install some extension for JS or is there anything that needs to be done?

**Comment by jasongrout** [comment]
For JupyterLab, you'll need to build a custom widget as a separate extension (for example, using the cookiecutter at https://github.com/vidartf/opinionated-widget-cookiecutter). The tutorial custom widget only works in the classic notebook.

**Comment by orpheus92** [comment]
I tried to build a custom widget as a separate extension. It builds without error. However, when I try to run w = ipywidgetexample.ExampleWidget() in JupyterLab, it gives me the following error. 
main.bundle.js:49829 Error: Could not create a model.
    at promiseRejection (main.bundle.js:49829)
    at <anonymous>
promiseRejection @ main.bundle.js:49829
lab:1 Uncaught (in promise) Module jupyter-widget-example, semver range 0.1.0 is not registered as a widget module

Any idea why this happens?

**Comment by jasongrout** [comment]
You'll need to install the widget as an extension as well, something like:

```
jupyter labextension install ./path/to/cookiecutter
```
which looks in the package.json file (`'jupyterlab'` key) which tells it where the jupyterlab extension is in the source that registers this widget.

**Comment by jasongrout** [comment]
Looks like we should add that install step to the readme. CC @vidartf.

**Comment by vidartf** [comment]
@jasongrout Is this resolved now with data files, or will that command still need to be run?

**Comment by blink1073** [comment]
It will not need to be run.  You can run `jupyter lab build` to pick up the new extension, or the first time you run `jupyter lab` it will see you have new extension(s) and offer to rebuild and refresh the page.

**Comment by vidartf** [comment]
Alright, then I'm closing this as resolved (feel free to reopen if I missed anything outstanding).
