### ISSUE TITLE
Ipywidgets in Jupyterlab 

### ISSUE THREAD

**Issue by orpheus92** [jupyter-widgets/ipywidgets#1801]
I have a question regarding Source Build of ipywidgets in Jupyterlab. 
It works well without an error. However, right now I was trying to understand how it worked especially the comm part. I found that the comm part is initialized in services-shim.ts in the base part of @jupyter-widgets. So it seems @jupyter-widgets is something I already have in my local machine. I guess my question is why we only need to install jupyterlab-manager package instead of the whole ipywidgets package?

**Comment by jasongrout** [comment]
ipywidgets provides the kernel side of widgets - the python classes that interact with the javascript controls. Does that answer your question?

**Comment by orpheus92** [comment]
I am not sure whether I understand this correctly, so the package jupyterlab-manager is only one part of the ipywidget package such that ipywidget works for jupyterlab. I am trying to understand the comm between python kernel and the front-end. So I probably need to build the ipywidgets package from source. Is that right?

**Comment by orpheus92** [comment]
Does ipywidgets support source build with lerna? I have a problem error TS2688: Cannot find type definition file for 'node' when I run lerna bootstrap. It shows it is the problem with @jupyter-widgets/output. Does anyone have any idea why this is happening?

**Comment by jasongrout** [comment]
We already use lerna to build. npm run build uses lerna to build all of the packages.

Are talking about using a single package in another setup? Can you share exactly what you are doing?

**Comment by orpheus92** [comment]
I was trying to use lerna to build from the root level.When I run lerna bootstrap, it gives me an error 
lerna ERR! execute Error occured with '@jupyter-widgets/output' while running 'npm run prepublish'
lerna ERR! npm run prepublish [@jupyter-widgets/output] Output from stdout:
 
error TS2688: Cannot find type definition file for 'node'.
lerna ERR! npm run prepublish [@jupyter-widgets/output] Output from stderr:

lerna ERR! execute Error occured with '@jupyter-widgets/output' while running 'npm run prepublish'

I only put the error part. 
 Then I go to the output folder, it gives me the same error when I run npm install in jupyter-widgets/output

**Comment by jasongrout** [comment]
Can you try (a) cleaning everything out with something like `git clean -dfx` or creating a new clone, and then (b) using our `npm install`, `npm run build` commands (which invoke lerna themselves, but with some options. (See https://github.com/jupyter-widgets/ipywidgets/blob/master/package.json#L7)

**Comment by orpheus92** [comment]
I switched my environment using conda and clean everything out. npm install and npm run build work fine on the root level. Is there a way to use jupyter labextension link to link all the packages at the same time? Or do I need to link them separately?

**Comment by jasongrout** [comment]
(a) I don't use the labextension link (yet), so I'm not sure.

(b) You may only need to labextension link the actual plugin package, `jupyterlab-manager`.

**Comment by orpheus92** [comment]
I guess my question is after npm run build from the root level, and link jupyterlab-manager (which gave correct behavior for ipywidgets), how did jupyter lab know about other packages (such as base, control) that were built?

**Comment by blink1073** [comment]
jupyterlab-manager has controls and base in its [dependencies](https://github.com/jupyter-widgets/ipywidgets/blob/1eee3c60418c834df06f87c0e2290088d2cc4cfd/packages/jupyterlab-manager/package.json#L8-L9), so they are brought it when you install jupyterlab-manager.

**Comment by orpheus92** [comment]
Thanks, it makes sense now. 
One more question, in example 2, it is mentioned that the example for comm between front-end and python kernel can be viewed with the web-kernel example.  Could you let me know where I could find that?

**Comment by jasongrout** [comment]
That should refer to the web3 example. Do you want to submit a PR correcting the reference? Thanks for finding that mistake!

**Comment by orpheus92** [comment]
I am not exactly sure how I can do that

**Comment by jasongrout** [comment]
The easiest way is to go to the file we want to change:

https://github.com/jupyter-widgets/ipywidgets/blob/master/examples/web2/README.md

and click on the pencil icon (i.e., "Edit"), make the change, and submit the change using the button at the bottom. There are more detailed instructions at https://help.github.com/articles/editing-files-in-another-user-s-repository/

Thanks again!

**Comment by jasongrout** [comment]
Thanks for opening #1807!

**Comment by orpheus92** [comment]
Close this one.
