### ISSUE TITLE
Can the tab bar wrap horizontally?

### ISSUE THREAD

**Issue by creyl** [jupyter-widgets/ipywidgets#1803]
I have a tab widget that contains more children that can fit in usual window width. Each tab contains a bunch of check boxes in a Box widget. I can control the layout of the tab contents, so the check boxes wrap around, but I can't seem to control the layout of the tabs header (tab bar?), which scrolls horizontally. Is there a way to make the tab bar wrap horizontally, so the user doesn't have to scroll to select the tab? 

```
import ipywidgets as widgets

class TabsNotWrapping: 
    def __init__(self, available_factors):
        self.available_factors = available_factors
        self.layout = widgets.Layout(display='flex', flex_flow='row wrap')
        self.tabs = self.tabs_multi_checkbox(available_factors)

    def tabs_multi_checkbox(self, items):
        descriptions = ['_'.join([i, str(c)]) for i in items for c in range(10)]
        options_dict = {description: widgets.Checkbox(
            description=description, value=False, style = {'description_width': 'initial'}) 
                        for description in descriptions}
        options = [options_dict[description] for description in descriptions]
        tabs = widgets.Tab(children=[
            widgets.Box([options_dict[d] for d in descriptions if d.startswith(i)], layout=self.layout) 
            for i in items
        ])
        for c, f in enumerate(items):
            tabs.set_title(c, f)

        return tabs

items = ['Abong-Mbang', 'Ako', 'Akonolinga', 'Ambam', 'Bafang', 'Bafia', 'Bafoussam', 'Bafut', 'Bagangte', 
         'Bali', 'Bamenda', 'Bamingie', 'Nkwen', 'Bandjoun', 'Bangem', 'Banyo', 'Batouri', 'Bélabo', 'Bertoua', 'Buea']
tmp = TabsNotWrapping(items)
display(tmp.tabs)
```

Here is the output. You can see how the tabs' content wraps around, but the tabs' header doesn't.
![tabs_not_wrapping1](https://user-images.githubusercontent.com/7947319/32497462-a5673a1c-c39a-11e7-9755-f70c3727489d.GIF)
![tabs_not_wrapping2](https://user-images.githubusercontent.com/7947319/32497475-a9c3c594-c39a-11e7-95b1-a42454799361.GIF)

I tried to specify the tab's layout to be the same as the tab's content, but it didn't change anything:
```
        tabs = widgets.Tab(children=[
            widgets.Box([options_dict[d] for d in descriptions if d.startswith(i)], layout=self.layout) 
            for i in items
        ], layout=self.layout)

```

Setup:
- Kernel python 3.6.2
- Jupyter notebook 5.0.0
- ipywidgets 7.0.1
- widgetsnbextension 3.0.2
- Windows

Thank you.

**Comment by jasongrout** [comment]
There is no way to do that currently. We use the Phosphor tab bar - that would be a great place to ask: https://github.com/phosphorjs/phosphor

CC @sccolbert (author of Phosphor)

**Comment by jasongrout** [comment]
Closing as answered.

**Comment by sccolbert** [comment]
Yeah, that would be difficult to do with a tab bar with movable tabs. It would be easier to write a specific widget for that. The hardest part is that the desired height changes as the width changes. This is a difficult layout operation to implement in a way that integrates well with the rest of phosphor.

**Comment by jasongrout** [comment]
Thanks for your insight!

**Comment by creyl** [comment]
Thanks to both
