### ISSUE TITLE
output widget append_display_data does not display widgets

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#1811]
It seems there are some problems either with the output widget `append_display_data` method (from https://github.com/jupyter-widgets/ipywidgets/pull/1752), or how we display widgets.

```python
from ipywidgets import Output, IntSlider
out = Output(layout={'border': '1px solid black'})
out.append_display_data(IntSlider())
out
```
should capture the intslider inside of the output widget, but instead we get

<img width="574" alt="screen shot 2017-11-08 at 8 56 40 pm" src="https://user-images.githubusercontent.com/192614/32589107-7c2781ba-c4c7-11e7-86a7-b80f48ff4213.png">

If I use the output widget as a context manager, it works fine:
```python
from ipywidgets import Output, IntSlider
from IPython.display import display
out = Output(layout={'border': '1px solid black'})
with out:
    display(IntSlider())
out
```
<img width="533" alt="screen shot 2017-11-08 at 8 58 43 pm" src="https://user-images.githubusercontent.com/192614/32589132-a4c1ae7a-c4c7-11e7-8d2b-1c1ddd8bc43a.png">

**Comment by jasongrout** [comment]
From the docs http://ipython.readthedocs.io/en/stable/api/generated/IPython.core.formatters.html:

> Prior to IPython 6.1, _ipython_display_ was the only way to display custom mime-types without registering a new Formatter.
> IPython 6.1 introduces _repr_mimebundle_ for displaying custom mime-types, so _ipython_display_ should only be used for objects that require unusual display patterns, such as multiple display calls.

We use `_ipython_display_`, in which we manually call `display` to display a widget. When we switch to using `_repr_mimebundle`, I think this issue will resolve itself.

**Comment by jasongrout** [comment]
IPython 6.1 was released 31 May 2017. I think it will be a while before we can mandate IPython 6.1+ (likely not until ipywidgets 8), so we may just have to live with this for now.

**Comment by jasongrout** [comment]
actually, we may be able to register a display using the `for_type` mechanism instead, until we can move to a simple `_repr_mimebundle_`: http://ipython.readthedocs.io/en/stable/api/generated/IPython.core.formatters.html#IPython.core.formatters.BaseFormatter.for_type

**Comment by GaiYu0** [comment]
Hi, I am experiencing a similar problem. In my case, the slider widget is displayed properly but the output widget cannot be displayed. Is there any temporary solution? 

Thank you very much!

**Comment by jasongrout** [comment]
@GaiYu0, can you post the code you are using?

**Comment by GaiYu0** [comment]
It turns out that my problem was caused by broken dependencies, which is irrelevant from this issue. Sorry!

**Comment by jasongrout** [comment]
> actually, we may be able to register a display using the for_type mechanism instead, until we can move to a simple _repr_mimebundle_: http://ipython.readthedocs.io/en/stable/api/generated/IPython.core.formatters.html#IPython.core.formatters.BaseFormatter.for_type

This won't work.  It looks like registering a `for_type` handler in the ipython display formatter is equivalent to defining the `_ipython_display_` function, so it doesn't get us anything more than we had.

So I'm moving this issue into the Future milestone, for when we can require ipython >=6.1 and define a `_repr_mimebundle_` method.

**Comment by jasongrout** [comment]
It looks like IPython 6.1 was released May 31, 2017, so we should probably wait until at least June 2018 to make this change.

**Comment by jasongrout** [comment]
Perhaps we can put in a check for the ipython version, and use the `_repr_mimebundle_` if we are in a version that supports it, and otherwise use (monkeypatch?) our class to have the `_ipython_display_` method?

**Comment by vidartf** [comment]
Note: Python allows you to conditionally declare methods, so no monkey-patching would be needed:
```python
In [1]: class A:
   ...:     if True:
   ...:         def sum(self, a, b):
   ...:             return a + b
   ...:

In [2]: a = A()

In [3]: a.sum(5, 6)
Out[3]: 11

In [4]: class B:
   ...:     if False:
   ...:         def sum(self, a, b):
   ...:             return a + b
   ...:

In [5]: b = B()

In [6]: b.sum(5, 6)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-b0fbaf787c6b> in <module>
----> 1 b.sum(5, 6)

AttributeError: 'B' object has no attribute 'sum'
```
