### ISSUE TITLE
Automated Testing of Widgets?

### ISSUE THREAD

**Issue by OliverEvans96** [jupyter-widgets/ipywidgets#1814]
Hi all,

Not sure if this is the right place to ask, but I was just wondering if there's any common wisdom on automated testing of widgets? For example, ensuring that a button click triggers the correct function call? Has anyone tried ipywidgets with Selenium?

Thanks!
Oliver

**Comment by jasongrout** [comment]
We've had various testing frameworks over the years, including end-to-end testing. However, we don't have a good end-to-end framework in place now. It's on (at least a mental) todo list. The place I'd probably start is looking at the jupyterlab testing (which IIRC starts up a Jupyter notebook server, so can do end-to-end testing).

If you come up with something good, we'd love to see it!

**Comment by OliverEvans96** [comment]
Thanks for the info!

**Comment by maartenbreddels** [comment]
See https://github.com/jupyter-widgets/ipywidgets/issues/2934#issuecomment-1787216387
