### ISSUE TITLE
Help Wanted Label

### ISSUE THREAD

**Issue by jzf2101** [jupyter-widgets/ipywidgets#1820]
Based on https://github.com/jupyter/governance/issues/40 , should we include a help wanted label?

**Comment by jasongrout** [comment]
Yes!

**Comment by jasongrout** [comment]
What is the difference between `good first issue` (which I've been using a lot) and `help wanted`?

**Comment by jasongrout** [comment]
I followed up in the governance issue noted above. If I use `help wanted`, I will probably use it on just about everything. That seems like it will dilute its effectiveness, but hey, if that's what people are searching for, I'm all for it.

**Comment by jasongrout** [comment]
I created the help wanted label. I will be applying it liberally as time goes on :).

**Comment by jasongrout** [comment]
Thanks again for bringing this up!
