### ISSUE TITLE
Dev Installation Instructions and Contributing.md are confusing

### ISSUE THREAD

**Issue by jzf2101** [jupyter-widgets/ipywidgets#1827]
Dev Installation instructions are in readme not contributing.md. The dev installation instructions in the readme also are different from the dev installation instructions on the website.

**Comment by peristeri** [comment]
The instructions in the `dev_install.sh` provides yet an other way of setting up the dev environment.

**Comment by CleoQc** [comment]
I've copied the intructions that were in `dev_install.sh` but I am not sure what to do with 'it does not work on both a mac and linux environment python 3.6.x' 
(that aside, I'm totally failing at installing on Windows so I can't really test anything)

**Comment by Doodledun** [comment]
Per discussion in Gitter, trying to replace all the places use `npm` with `yarn`  in `dev_install.sh` seems to work for me. I am on linux 16.04 and using python 2.7

**Comment by peristeri** [comment]
I confirm that using `yarn` instead of `npm` worked for me.
