### ISSUE TITLE
Testing Documentation in Travis?

### ISSUE THREAD

**Issue by jzf2101** [jupyter-widgets/ipywidgets#1830]
Based on the `.travis.yml` it doesn't appear we do?

**Comment by jzf2101** [comment]
See https://github.com/jupyter/nbgrader/blob/master/.travis.yml

**Comment by jzf2101** [comment]
Also https://github.com/jupyter/notebook/blob/master/.travis.yml

**Comment by jasongrout** [comment]
We do test on travis, but only for python 3.6: gets/ipywidgets/blob/master/.travis.yml#L31

**Comment by jasongrout** [comment]
Closing, since we do test on Travis.
