### ISSUE TITLE
Widget text not getting synchronized value

### ISSUE THREAD

**Issue by rpedsel** [jupyter-widgets/ipywidgets#1843]
Hi, I tried to get  fresh text.value after submitting...but it seems to give out old values (submitted previously or empty string)
```
text = widgets.Text()
display(text)

def handle_submit(sender):
    print(text.value)
    
text.on_submit(handle_submit)
```
I actually follow the example from [this website](https://blog.dominodatalab.com/interactive-dashboards-in-jupyter/), and expect to have similar effect...

I installed ipywidgets through conda today (tried to pip install / install from git but failed, possibly because of some broken conda settings on my desktop...)

Just want to know if there's a way to get synchronized text widget value ? Also, it seems that the on_submit event is outdated? Is there a better way to achieve the same submitting event?

**Comment by rpedsel** [comment]
Oh...I just found that if I ctrl + enter on the text box before submitting would update the value. It kind of solve my problem here...

**Comment by jasongrout** [comment]
The recommended way to do this is to do something like:

```python
import ipywidgets as widgets
from IPython.display import display

# You could also pass in continuous_update=False to only send 
# the new value when pressing enter or leaving the textbox
t = widgets.Text()

def value_changed(change):
    # change.new contains the new value
    print('new value: ' + change.new)

t.observe(value_changed, 'value')

display(t)
```

**Comment by jasongrout** [comment]
And you're right, `on_submit` is deprecated in ipywidgets 7.

**Comment by jasongrout** [comment]
Closing as it seems your question is answered, but feel free to continue the discussion if you'd like.

**Comment by rpedsel** [comment]
Thanks for your recommendation! I tried to apply observe function before, but nothing happened after I click enter. It turns out that I need to click *ctrl + enter* to submit the text. 
Also, lots of thanks to ipywidgets developers! I am bad at web dev and this tool really helps me a lot to deliver a simple UI easily :+1:
