### ISSUE TITLE
Make sliders possible for logspace

### ISSUE THREAD

**Issue by gnestor** [jupyter-widgets/ipywidgets#1847]
via https://github.com/jupyter/notebook/issues/183:

@shashi wrote:

> as discussed in JuliaLang/Interact.jl#2 Currently the sliders work only for linearly increasing ranges. But it would be nice to have sliders work for logspace(-3, +3).

**Comment by jasongrout** [comment]
Thanks! We're tracking the conversation about log-scale sliders at https://github.com/jupyter-widgets/ipywidgets/issues/719.
