### ISSUE TITLE
Matplotlib graphs do not clear in events with clear_output

### ISSUE THREAD

**Issue by fractus** [jupyter-widgets/ipywidgets#1853]
Hi, I noticed this in 7.0.5, however it used to work in 6.0.0 with just `clear_output`, before it's behaviour was changed. Below is a screenshot to replicate it; every time I click the button, the frame is cleared, but the graph is not. I would appreciate it if you can have a look.

_Versions_
```
jupyter                   1.0.0            py36h422fd7e_2
jupyter_client            5.1.0            py36h9902a9a_0
jupyter_console           5.2.0            py36h6d89b47_1
jupyter_core              4.3.0            py36h511e818_0
jupyterlab                0.27.0           py36h34cc53b_2
jupyterlab_launcher       0.4.0            py36h22c3ccf_0
jupyterthemes             0.18.2                    <pip>

ipywidgets                7.0.5                    py36_0    conda-forge
widgetsnbextension        3.0.8                    py36_0    conda-forge

matplotlib                2.1.0                     <pip>
pandas                    0.20.3           py36hce827b7_2
```

_Screenshot_
![ipy705](https://user-images.githubusercontent.com/5813277/33587968-1b0ce57c-d936-11e7-8f18-bdc11bef4748.PNG)

_Code_
```python
import pandas as pd
import numpy as np
from IPython.display import clear_output
import matplotlib
from matplotlib import pyplot as plt
%matplotlib inline
import ipywidgets as widgets

button = widgets.Button(description="Plot!")
display(button)
out = widgets.Output()
display(out)

def on_button_clicked(b):
    with out:
        clear_output()
        x = pd.DataFrame(np.random.randn(8, 1))
        display(x.T)
        x.plot(figsize=[8, 1])
#         plt.plot(x) --- THIS ALSO CREATED DUPLICATES

button.on_click(on_button_clicked)
```

**Comment by jasongrout** [comment]
What's happening here is that the matplotlib inline backend makes some assumptions about how to display graphs that don't mesh well with capturing output. We had to work around this in interact as well at https://github.com/jupyter-widgets/ipywidgets/blob/02f406bd3ce1480ed3df2533f6acc1a4587b52af/ipywidgets/widgets/interaction.py#L75, which calls this function: https://github.com/jupyter-widgets/ipywidgets/blob/02f406bd3ce1480ed3df2533f6acc1a4587b52af/ipywidgets/widgets/interaction.py#L35

So you can use the same workaround we used. Import that function:

```python
from ipywidgets.widgets.interaction import show_inline_matplotlib_plots
```

then change your function to:
```python
def on_button_clicked(b):
    with out:
        clear_output()
        x = pd.DataFrame(np.random.randn(8, 1))
        display(x.T)
        x.plot(figsize=[8, 1])
        show_inline_matplotlib_plots()
```
Even better would be to use the matplotlib widget, which lets you update a matplotlib graph, respond to user input, etc: https://github.com/matplotlib/jupyter-matplotlib

**Comment by jasongrout** [comment]
(Basically the issue here is that the matplotlib inline backend waits until the cell finishes executing, outside of the `out` context, and only then creates the image and appends it to the output. Our function above forces the image to be made and displayed inside of the `out` context so that it can be captured.)

**Comment by fractus** [comment]
@jasongrout Thanks for the prompt response. The workaround works, I'll also check the matplolib widget.

**Comment by jasongrout** [comment]
Great!

**Comment by bybyte** [comment]
This does not work for me in Jupyter notebook. output.clear_ouput() clears other output but matplotlib plots are not cleared. 

Relatedly, I am not able to display matplotlib plots when plotting from a widget in Jupyter Lab, with or without running the Matplotlib widget magic first (%matplotlib widget).

**Comment by jasongrout** [comment]
> This does not work for me in Jupyter notebook.

Can you post exactly what code doesn't work for you? Did you try the work-around above, which works around how matplotlib displays plots?



> Relatedly, I am not able to display matplotlib plots when plotting from a widget in Jupyter Lab, with or without running the Matplotlib widget magic first (%matplotlib widget).

Again, please post a small reproducible example so we can see exactly what you are doing. Please do this in a new issue, since this issue has been resolved and closed for a while now.

**Comment by bybyte** [comment]
I was referring to the workaround not working for me. Yes, I understand -- I will post in a new thread. Thanks.
