### ISSUE TITLE
npm package error

### ISSUE THREAD

**Issue by AugustoYao** [jupyter-widgets/ipywidgets#1858]
After installed jupyterlab 0.29.2, it works for a while with `ipywidgets`.  Since 6, Dec, 2017, after I re-build jupyterlab with command `jupyter lab clean && jupyter lab build`, jupyterlab behaves a little weird. At first, the page's height is about180 px, it cannot take my full screen. After Checking for a while, I found that @jupyter-widgets/controls seems at wrong order, the css override order is not as it was before. I wait for quite a few hours, then I rebuild jupyterlab. This time,  the page seems work fine, but when executing `import ipywidgets
ipywidgets.IntSlider()`, the output area shows that `Error displaying widget`. I wonder how can I specify npm package version, so that it can only build my own package, without updating packages like @jupyter-wigets/controls and so on? 
P.s. I noticed that @jupyter-widgets/controls have two new versions in last two days. But both don't work well in my environment, so I just want to roll back to 1.0.10. 
@jasongrout  Could you give me some kindly advice, please?

**Comment by jasongrout** [comment]
I just pushed the `@jupyter-widgets/jupyterlab-manager` 0.31.3, which fixes this issue. You can upgrade to that, or you can install a specific version like 1.0.10 by doing something like `jupyter labextension install @jupyter-widgets/jupyterlab-manager@1.0.10` (you might need to uninstall your current extension first).

**Comment by jasongrout** [comment]
@AugustoYao - please let us know if one of the above solutions works for you.

**Comment by AugustoYao** [comment]
After uninstall @jupyter-widgets/jupyterlab-manager with command `jupyter lab uninstall @jupyter-widgets/jupyterlab-manager`, I re-install @jypyter-widgets/jupyterlab-manager@0.31.3, and it fails too, following is the error message while installing @jupyter-widgets/jupyterlab-manager@0.31.3
```
[jhyao@sdd002023 ~]$ jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.31.3
> node node-version-check.js
> npm pack @jupyter-widgets/jupyterlab-manager@0.31.3
jupyter-widgets-jupyterlab-manager-0.31.3.tgz
Traceback (most recent call last):
  File "/disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/bin/jupyter-labextension", line 6, in <module>
    sys.exit(jupyterlab.labextensions.main())
  File "/disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 174, in start
    super(LabExtensionApp, self).start()
  File "/disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/lib/python3.6/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 64, in start
    for arg in self.extra_args]
  File "/disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 64, in <listcomp>
    for arg in self.extra_args]
  File "/disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/lib/python3.6/site-packages/jupyterlab/commands.py", line 137, in install_extension
    return IOLoop.instance().run_sync(func)
  File "/disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/lib/python3.6/site-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/disk/sata/sdi/jhyao/Sky4.1/SkyDiscovery/lib/python3.6/site-packages/jupyterlab/commands.py", line 208, in install_extension_async
    raise ValueError(msg)
ValueError:
"@jupyter-widgets/jupyterlab-manager@0.31.3" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension            Package
>=0.12.0-0 <0.13.0-0    >=0.13.0-0 <0.14.0-0 @jupyterlab/application
>=0.12.0-0 <0.13.0-0    >=0.13.0-0 <0.14.0-0 @jupyterlab/coreutils
>=0.12.0-0 <0.13.0-0    >=0.13.0-0 <0.14.0-0 @jupyterlab/notebook
>=0.12.0-0 <0.13.0-0    >=0.13.0-0 <0.14.0-0 @jupyterlab/rendermime
>=0.51.0-0 <0.52.0-0    >=0.52.0-0 <0.53.0-0 @jupyterlab/services
```

**Comment by AugustoYao** [comment]
Finally, jupyterlab@0.29.2 is removed, and jupyterlab@0.30.2 is installed instead. Then I used 
```
jupyter lab clean
jupyter lab build
jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.31.3
```
Now everything works well. Thank you very much, @jasongrout .  Actually, I'm working on building jupyterlab extension, and I'm wondering how can I re-build my own extension without updating jupyter related packages no matter whether there're new packages on npmjs. Maybe it's not a good time to start to build jupyterlab extension.  Could you give me some advice, please?  Again, thank you very much for your great work.

**Comment by jasongrout** [comment]
There should be a fairly stable platform for developing ipywidgets jlab extensions - you shouldn't need to rebuild when jlab is upgraded. Is that what you are wanting?

**Comment by AugustoYao** [comment]
Yes, that's exactly what I want.  By the way, I'm working on build an extension like Spyder's Variable explorer. [Implement variable inspector for kernels](https://github.com/jupyterlab/jupyterlab/issues/443). I wonder whether somebody else have already done, or the community has a plan on this. If someone have already been working on it, maybe I can do some contribution to this feature.

**Comment by jasongrout** [comment]
Eventually we want to do something along those lines, but I don't know of anyone working on something yet.

**Comment by AugustoYao** [comment]
OK , I'm going to do this, and release source code on github when the demo is done.

**Comment by jasongrout** [comment]
Great!

**Comment by jasongrout** [comment]
Feel free to open an issue in the jupyterlab repo for discussion if you want some ideas about how to best implement something like this.

**Comment by AugustoYao** [comment]
OK, I would open a new issue in Jupyterlab repo for suggestions on this extension.

**Comment by jasongrout** [comment]
Or even better, how about extending the discussion already on this topic at https://github.com/jupyterlab/jupyterlab/issues/443?

**Comment by jasongrout** [comment]
Extending that discussion consolidates things, and lets people know that someone is working on this.

**Comment by AugustoYao** [comment]
I think it would be a good time when I release first demo. After that, I would post comments on topic [jupyterlab/jupyterlab#443](https://github.com/jupyterlab/jupyterlab/issues/443) for suggestions.
