### ISSUE TITLE
clear_output() does not clear the display of ipython widgets

### ISSUE THREAD

**Issue by suprithams** [jupyter-widgets/ipywidgets#1860]
I have a function that checks the value of a dropdown widget. When the value changes from one option of dropdown to other option, I have a function that observes the change and display slider according to the change. But in doing so, it does not clear the previous option's slider widget. I have tried using clear_output() but in vain. Can someone help me resolve the issue? Thanks.

**Comment by jasongrout** [comment]
Superseded by #1861.
