### ISSUE TITLE
Note python 2 vs 3 approaches in asynchronous widgets example

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#1867]
We should note in http://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Asynchronous.html#Generator-approach that the generator approach is suitable for python 2, and generally note which examples are python 3-only, and which work in python 2 as well.

**Comment by vidartf** [comment]
Since we do not support Python 2 any more, I think this can be closed.
