### ISSUE TITLE
Dropdown ipywidget after unobserve_all() does not accept any further observe()

### ISSUE THREAD

**Issue by joefresna** [jupyter-widgets/ipywidgets#1868]
I use ipywidget 7.0.5 (py35_0)
The dropdown ipywidget after unobserve_all() does not work for any further observe().
This is easily reproducible with the following code:

```
import ipywidgets.widgets as widgets
from IPython.display import display
def helloWorld(_=None):
    print("Hello World!")

# the dropdown is not working properly
widget = widgets.Dropdown( 
            options=[('One', 1), 
                     ('Two', 2),
                     ('Three', 3)],
            description='dropdown_w:',
            value = 2
        )
widget.observe(helloWorld, 'value')
display(widget)
widget.unobserve_all()
widget.observe(helloWorld, 'value')


## instead same code works for other widgets (as it should)
w = widget = widgets.FloatSlider(value = 0.5, min = 0, max = 1, step = 0.1, description = "w")
w.observe(helloWorld, 'value')
display(w)
w.unobserve_all()
w.observe(helloWorld, 'value')
```

**Comment by jasongrout** [comment]
Thanks. I've confirmed it and am investigating...

**Comment by joefresna** [comment]
```
## Also toggle buttons do not work as they should
plotToggle = widgets.ToggleButtons(
    options=[('one', 1), ('two', 2)],
    value = 1,
    description='btn_w:'
)
plotToggle.observe(helloWorld, 'value')
display(plotToggle)
plotToggle.unobserve_all()
plotToggle.observe(helloWorld, 'value')
```

**Comment by jasongrout** [comment]
It may be something to do with the selection widgets in general

**Comment by jasongrout** [comment]
ah, I think I know what may be going on. The way that value gets updated is through an observe handler. Basically, when the item is selected in the browser, it updates the selected index in python. An observe handler listening to the selected index then sets the value.

So one answer is: don't use `unobserve_all` - instead deregister your own handlers.

`unobserve_all` would also break `link`, etc.

**Comment by joefresna** [comment]
Thanks! your answer is very useful.

I look forward to the fix because I'd like to use `unobserve_all` because I've a list of widgets and I don't which is the function linked to each widget.

at the moment, the temporary solution is to re-build another widget (instead of `unobserve_all`); although, as long-term plan, I'd like to use `unobserve_all` if it will be available

**Comment by jasongrout** [comment]
A temporary kludgy workaround is to save the value of `widget._trait_notifications` before adding your handlers. Restore that to reset the handlers.

A more permanent thing might be to subclass `unobserve_all` in the selection widgets to *not* remove the internal observe handlers.

In general, I think you shouldn't assume that `unobserve_all` just removes your handlers, and it's fairly dangerous to use.

**Comment by joefresna** [comment]
Thanks for the suggestions and the quick reply! 
My solution at the moment is to store each registered handler for each widget and then I deregister only specific handlers (with `unobserve()`)

**Comment by jasongrout** [comment]
I think you found the best way to go about it, and not to indiscriminately use `unobserve_all`.

**Comment by NimSed** [comment]
Not sure if this is still relevant. But it may help some one.
`w.unobserve(None,...)` does something like what `unobserve_all` is expected to do. Of course you'd still need to pass `names` whenever needed. But at least you don't need to know the exact name of the handler. Specially if you have used a `partial` when setting the observer.
