### ISSUE TITLE
Is it possible to clear the output and not the widget?

### ISSUE THREAD

**Issue by rklarpit** [jupyter-widgets/ipywidgets#1869]
Hello team,

I want to clear my output with various available buttons depending on the functionality! However with the lates version of ipywidgets, clear_output() is clearing the widget as well. I want the widget form to stay intact for better User Experience. Can you help with the same?

**Comment by jasongrout** [comment]
The widget is part of the cell output, so clearing the cell output will get rid of the widget now.

A more powerful paradigm now that we suggest people moving to is using the new Output widget to capture output, put it wherever you want, and clearing it whenever you need. That's how `interact` works now, for example.

http://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html#Output
