### ISSUE TITLE
Rename manual interact button

### ISSUE THREAD

**Issue by rklarpit** [jupyter-widgets/ipywidgets#1870]
### Summary
It would be great to have an option to rename the text in the button that interact_manual creates.

---
### Original issue
Title: Integrate other functionality in interact manual

Hello Team,

I am trying to use the interact manual functionality. For the purpose I want to add a few more lines of code at my end to the run Interact button. I also want to rename the button to something else. Can you tell me the best way to address the problem?

**Comment by jasongrout** [comment]
It sounds like your needs are growing beyond the convenience functions (`interact`, `interact_manual`, etc.). You can build much more powerful and customized UI using the widgets directly (i.e., create sliders, checkboxes, etc. yourself; create a button to run your function from the current values of the widgets, and name the button whatever you want).

**Comment by jasongrout** [comment]
That said, I think adding an option to rename the button makes sense. The code for that button name is at https://github.com/jupyter-widgets/ipywidgets/blob/a9c4069570aa92368f590296569e411d9c49e123/ipywidgets/widgets/interaction.py#L203

I think it would be enough to make a new option at https://github.com/jupyter-widgets/ipywidgets/blob/a9c4069570aa92368f590296569e411d9c49e123/ipywidgets/widgets/interaction.py#L160 and use that option in the description of the button.

**Comment by jasongrout** [comment]
Can we keep this open as a good first issue for someone to tackle? I think it's a great idea to be able to rename the interact button.

**Comment by dharmaquark** [comment]
I'll take a look at this one

**Comment by rklarpit** [comment]
Thanks Jason for reopening it :). Will be of great help

**Comment by jasongrout** [comment]
Fixed by #1924
