### ISSUE TITLE
Combo Box Widget

### ISSUE THREAD

**Issue by AbdealiJK** [jupyter-widgets/ipywidgets#1871]
Would be awesome if IPywidgets had a combo box functionality. It would be a box which is a dropdown, but imagine a dropdown with 400 items. In such cases it becomes simpler to allow a search to search within the dropdown entries.

Example: http://rustemsoft.com/images/rghtcb.gif

**Comment by jasongrout** [comment]
Agreed - a combo box would be great to have.

**Comment by jasongrout** [comment]
Perhaps even better is for someone to build a third-party combo box widget, and when it is mature, look at including it in core.
