### ISSUE TITLE
jupyterlab_bokeh needs to be included

### ISSUE THREAD

**Issue by mbleuel** [jupyter-widgets/ipywidgets#1874]
Hi there,

I am trying to get bokeh to work with jupyterlab and couldn't find the right answer..
I am working under windows 10 and with other modules I found that using the Jupyter inline commands work best (I am a noobie and run into issues about where stuff gets installed all the time).

The following commands worked without errors (not sure if they are all relevant)

```
! conda install -y -c cpcloud npm
The following NEW packages will be INSTALLED:
    nodejs: 0.10.33-0 cpcloud
    npm:    1.4.12-0  cpcloud
[..]
import bokeh; bokeh.__version__
'0.12.13'
!conda list jupyter
# packages in environment at C:\Users\mnb3\AppData\Local\Continuum\anaconda3:
#
jupyter                   1.0.0            py36h422fd7e_2  
jupyter_client            5.1.0            py36h9902a9a_0  
jupyter_console           5.2.0            py36h6d89b47_1  
jupyter_core              4.3.0            py36h511e818_0  
jupyterlab                0.30.6           py36h047fa9f_0  
jupyterlab_launcher       0.6.0                    py36_0    conda-forge
```

But I got errors for 
```
! jupyter labextension list

JupyterLab v0.30.6
Known labextensions:
   app dir: C:\Users\mnb3\AppData\Local\Continuum\anaconda3\share\jupyter\lab
jupyterlab_bokeh
        jupyterlab_bokeh v0.1.0 enabled  ok

Build recommended:
    jupyterlab_bokeh needs to be included
```
==> I guess that is the problem, it seems the wrong version and how do I include it?
If I launch a jupyterlab from the anaconda navigator (1.6.10) it cycles through two popup windows:
```
Build Recommended
JupyterLab build is suggested:
jupyterlab_bokeh needs to be included
cancel      build
and
Build Complete
Build successfully completed, reload page?
cancel     reload
```
until I hit either cancel

```
from bokeh.io import output_notebook, show
from bokeh.plotting import figure

output_notebook()

# create a new plot with default tools, using figure
p = figure(plot_width=400, plot_height=400)

# add a circle renderer with a size, color, and alpha
p.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=15, line_color="navy", fill_color="orange", fill_alpha=0.5)

show(p) # show the results
```

```
Loading BokehJS ...
JavaScript output is disabled in JupyterLab
JavaScript output is disabled in JupyterLab
```
(works fine in a Jupyter notebook)

Thanks you for any suggestions...

**Comment by blink1073** [comment]
Hi!  The missing step is a `jupyter lab build` to pick up the extension.  You may need to `conda install nodejs` first if you don't already have node installed.

**Comment by jasongrout** [comment]
(And I'll just add for your information that this doesn't have anything to do with ipywidgets - it's a JupyterLab thing.)

**Comment by mbleuel** [comment]
Hi, thx for the fast answers, this place is awesome!
Unfortunately, I report back with more questions..
I did try a 
! conda install -y -c cpcloud npm
and it seemed to install nodejs: 0.10.33-0 cpcloud and    npm:    1.4.12-0  cpcloud 
(without errors)
And conda install -c javascript/label/dev nodejs
 nodejs: 0.10.33-0 cpcloud --> 4.4.1-0 javascript


But either of these is less successful:
!conda install -y-c conda-forge nodejs
!conda install  -y   nodejs

Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Users\mnb3\AppData\Local\Continuum\anaconda3:

The following packages will be UPDATED:

    nodejs: 0.10.33-0 cpcloud --> 6.10.3-0

CondaError: FileNotFoundError(2, 'No such file or directory')
CondaError: FileNotFoundError(2, 'No such file or directory')
CondaError: FileNotFoundError(2, 'No such file or directory')


I still do get the build to run:
!jupyter lab build
C:\Users\mnb3\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyterlab\staging\yarn.js:137
class MessageError extends Error {
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

C:\Users\mnb3\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyterlab\staging\yarn.js:137
class MessageError extends Error {
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
> node C:\Users\mnb3\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyterlab\staging\yarn.js install
> node C:\Users\mnb3\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyterlab\staging\yarn.js run build:prod

**Comment by jasongrout** [comment]
I think:

1. It would be best to create a completely new clean environment - it looks like lots of things were installed (like different versions of node), and they might be messing each other up.
2. We should probably take this issue over to the bokeh repo at https://github.com/bokeh/jupyterlab_bokeh. This repository is about ipywidgets, which is a completely different project.

CC @canavandl @bryevdv

**Comment by jasongrout** [comment]
For a new conda environment, I would do:

```
conda create -n jlabbokeh jupyterlab bokeh nodejs
```
Then I would ask over in the jupyterlab_bokeh repo about installation of their jupyterlab component.

**Comment by bryevdv** [comment]
https://github.com/bokeh/jupyterlab_bokeh/blob/master/README.md

**Comment by mbleuel** [comment]
Hi again,
as far as I can tell, the issue exists for a fresh made environment as well, I will take it over to  jupyterlab_bokeh 
Thanks again for your suggestions!

**Comment by jasongrout** [comment]
Great. I'll close this - but if the issue turns out to be an ipywidgets problem, feel free to reopen or open another issue.
