### ISSUE TITLE
Refreshing a live notebook with saved state

### ISSUE THREAD

**Issue by vidartf** [jupyter-widgets/ipywidgets#1875]
I'm not sure how big of an issue this is, but looking at the constructor of [WidgetManager](https://github.com/jupyter-widgets/ipywidgets/blob/a9c4069570aa92368f590296569e411d9c49e123/widgetsnbextension/src/manager.js#L55-L129), I notice that:
- If there is saved widget state, `set_state` is called, which checks for live widgets and connects to them etc, and creates any missing widgets. [here](https://github.com/jupyter-widgets/ipywidgets/blob/a9c4069570aa92368f590296569e411d9c49e123/widgetsnbextension/src/manager.js#L67)
- It checks if there are any live widgets on the kernel, and if so connects to them and creates the JS comms and widgets for them. [here](https://github.com/jupyter-widgets/ipywidgets/blob/a9c4069570aa92368f590296569e411d9c49e123/widgetsnbextension/src/manager.js#L79) and [here](https://github.com/jupyter-widgets/ipywidgets/blob/a9c4069570aa92368f590296569e411d9c49e123/widgetsnbextension/src/manager.js#L106)

This means that if you have a notebook with widgets, then save the state, and refresh the page without restarting the kernel, the JS comms and widgets are created twice. For certain widget configurations this can lead to an indeterminate state, as duplicates of widgets/comms are created with the same id (only the last one is registered with the manager). At least AFAICT.

**Comment by vidartf** [comment]
While I'm a little unsure what the correct behavior should be, I make the following observations:
- If there are no live comms, it will always be safe to load the saved state.
- If a saved widget has the same ID as a live one, the saved state should be ignored (current behavior).
- If there are live widgets, and there is an ID in the saved state that is not live, it is not clear what should be done. However, the "safe" behavior" would be to create it from the saved state. Any widgets orphaned by this behavior can be cleaned up by clearing the saved state and running the notebook again. This could however lead to people seeing widgets on the page that are not really "integrated" with the current kernel state (obscure debugging).

**Comment by jasongrout** [comment]
Thanks for investigating this.

**Comment by vidartf** [comment]
I can add a fix for this as well, as soon as we get agreement on what should be the expected behavior when refreshing the page with saved widget state, and there are "extra" widgets in the saved state compared to the live state. Should it restore the "extra" widgets, or ignore them?

**Comment by jasongrout** [comment]
To close the loop here, it looks like your PR decides "ignore them".

**Comment by vidartf** [comment]
Actually, it does recreate the ones that are present in the saved state, *but that are missing in the live state*. When they are present in both cases, live state is used, c.f. bullet point 2.

**Comment by jasongrout** [comment]
Oh right, I meant "ignore ones that are duplicate with live state".
