### ISSUE TITLE
installing ipywidgets for kernel-only

### ISSUE THREAD

**Issue by minrk** [jupyter-widgets/ipywidgets#1892]
ipywidgets currently depends on `widgetsnbextension`, which in turn depends on `notebook`. This means installing ipywidgets into a kernel-only env requires pulling in the notebook and all of its dependencies, which will be unused. This dramatically increases what's required for installing Python 3 notebook + a Python 2 kernel, for instance (what I'm working on right now).

Since ipywidgets does not in fact require `widgetsnbextension`, this is an artificial dependency. But I recognize that it's solving the single-command install case, which is more important than saving space. Still, it would be nice to have *an* answer for installing just ipywidgets in a kernel env, which right now appears to be impossible.

One option would be to remove widgetsnbextension's explicit dependency on notebook. Lots of people are going to install `ipywidgets` and expect the functionality of widgetsnbextension to be available. However, it is exceedingly rare that widgetsnbextension will be installed without notebook also being explicitly installed.

**Comment by jasongrout** [comment]
In our conda-forge package, we explicitly invoke a notebook command to enable the extension: https://github.com/conda-forge/widgetsnbextension-feedstock/blob/97cb47bef034edad5c7018425fc6641b91e0d1bb/recipe/post-link.sh

Clearly the technically correct solution is to make ipywidgets not depend on widgetsnbextension, though we've kept it for the convenience reasons you've mentioned. I think with the advent of JupyterLab (which no longer needs widgetsnbextension), we can start to make that change.

In the short term, could you install ipywidgets with the no dependencies flag as a workaround?

**Comment by jasongrout** [comment]
Labeling as Future because such a change might need to happen at a major release.

**Comment by maartenbreddels** [comment]
What about the following:
 * ipywidgets: meta package with no code that depends on ipywidgets-python & widgetsnbextension
 * ipywidgets-python: what is now distributed as ipywidgets, so this contains the python code
 * widgetsnbextension: the js extension
 * possibly: jupyter-widgets-jlab for the jupyter lab extension
For every release of the python code, you would release both ipywidgets-python and ipywidgets, where the dependency and version number for both are locked. So ipywidgets v7.x.y depends on ipywidgets-python v7.x.y, and they are released at the same time. Also the dependency on widgetsnbextension will be locked to the latest version in the repo. For most people that use 1 env (kernel and notebook in the same env that is), they install ipywidgets and get a consistent set of ipywidget-python and widgetsnbextension (possibly also jupyter-widgets-jlab). Other have to be a big more careful which versions they have in the notebook and kernel.

**Comment by jasongrout** [comment]
Nice! And thus we invoke the [fundamental theorem of software engineering](https://en.wikipedia.org/wiki/Fundamental_theorem_of_software_engineering), "We can solve any problem by introducing an extra level of indirection...except the problem of too many levels of indirection"

**Comment by maartenbreddels** [comment]
Ok, minus the version locking.. it's not that complex of a solution right?

**Comment by jasongrout** [comment]
I'm okay with splitting up the ipywidgets package into ipywidgets-python and the ipywidgets meta package, though it'd be great to get a better name than ipywidgets-python. Perhaps ipywidgets-kernel?

**Comment by SylvainCorlay** [comment]
I kinda like the `ipywidgets` name for the python side. We have `xwidgets` for the C++ side (most C++ kernel things start with `x`, and python kernel things start with `ipy`...)

**Comment by jasongrout** [comment]
That's a problem for backwards compatibility, though. How about ipywidgets-core for the kernel-only part?

**Comment by maartenbreddels** [comment]
I think this is also a good topic for next week's workshop.

**Comment by SylvainCorlay** [comment]
>That's a problem for backwards compatibility, though. How about ipywidgets-core for the kernel-only part?

In any case, when the classic notebook becomes legacy, we will want to break that dependency... ipywidgets-python is kind of a weird name. Also, with the debian package naming convention, it will become `python-ipywidgets-python`, which is a bit silly.

**Comment by maartenbreddels** [comment]
I agree, it's a silly name. ipywidget-core/kernel/backend would be better

**Comment by jasongrout** [comment]
An update: in ipywidgets 8.0, ipywidgets depends on widgetsnbextension and jupyterlab_widgets, but widgetsnbextension no longer depends on notebook. Thus installing ipywidgets in a kernel will install some unused js packages for notebook and jlab, but not pull in other dependencies like notebook.
