### ISSUE TITLE
Programmatically click widgets from Python side?

### ISSUE THREAD

**Issue by dsblank** [jupyter-widgets/ipywidgets#1896]
Is it possible to, say, programmatically click a Button widget?

**Comment by jasongrout** [comment]
Not currently.

**Comment by dsblank** [comment]
Any semi-easy way to fake it?

**Comment by jasongrout** [comment]
Do you just want to call your on_click handler? Just do the same thing the code is doing: https://github.com/jupyter-widgets/ipywidgets/blob/896ea55df966bb20f2d7e1829083f97d050c89cc/ipywidgets/widgets/widget_button.py#L97

**Comment by jasongrout** [comment]
Or call that message handling function with an appropriate dictionary

**Comment by dsblank** [comment]
Thanks! I think I found a bug. Reporting...

**Comment by jasongrout** [comment]
Great, thanks!

**Comment by jasongrout** [comment]
Great, thanks!

> I think I found a bug

For reference, this is presumably #1897.
