### ISSUE TITLE
Play widget will stop programmatically, but won't start

### ISSUE THREAD

**Issue by dsblank** [jupyter-widgets/ipywidgets#1897]
Using a Play() widget, I can stop the play with:

```python
play._playing = False
```
But this doesn't start it:

```python
play._playing = True
```
The Play button is highlighted, but it doesn't start playing.

**Comment by jasongrout** [comment]
Presumably a private `_playing` attribute is not part of the public api, so using it manually is undefined and at your own risk. However, it would be good to see if there is a way to pause playback from Python that is officially supported.
