### ISSUE TITLE
ipywidgets based projects IDE best practices

### ISSUE THREAD

**Issue by sergun** [jupyter-widgets/ipywidgets#1906]
Hi!

We are developing some intaractive tool based on ipywidgets. It will have 1000+ lines of code. So we will use  classes  / modules / packages.. What is the best practices to develop / debug and test everything.. So we need something like pycharm to deal with code / debug easily and Jupyter to test visually. How to combine everything together? As I know pycharm doesn't support ipywidgets now.

ipywidgets creators, in which IDEs are you developing and testing your product?

Thanks!

Sergey.

**Comment by jasongrout** [comment]
I typically use the notebook (importing libraries in as needed). These days, I also use JupyterLab to author pure code files.

**Comment by rskabelund** [comment]
I also use straight up Jupyter even for the js development.  I do often wonder if there is a better way though.  I would really like to use some sort of debugger to step through the code at times.  Right now, I use a bash script to recompile and print statements to debug with, which can be tedious at times...

**Comment by vidartf** [comment]
For debugging JS side I normally:
 - Set up compilation watch processes, ensuring source maps if there is any compilation.
 - Use the dev-tools in chrome, as these are quite powerful also for async debugging and DOM/styling.

For debugging PY side:
 - Use print statements and frequent kernel restarts.
 - Watch this repo for signs that it might become better: https://github.com/jupyter/debugger

**Comment by jasongrout** [comment]
Closing as answered. Thanks for asking! (Feel free to post more comments if you'd like to continue the discussion.)
