### ISSUE TITLE
matplotlib/plotly plot inside container

### ISSUE THREAD

**Issue by sergun** [jupyter-widgets/ipywidgets#1907]
Is it possible?

**Comment by jasongrout** [comment]
It depends on what you want. Matplotlib has a widget-based renderer, ipympl, so that widget could be directly added to a container. Other than that, anything that can be rendered in a cell output can be put in an Output widget.

**Comment by rskabelund** [comment]
I do it kinda of cheating, I use the output_type='div' option and get the html as a string.  Then I load the HTML into a custom widget that loads the HTML into a div.  This used to work great with just using the HTML widget, however they changed its behavior with ipywidgets 7.  Once it is in a widget, you can put it anywhere, inside a Box, a tab, etc..  I have also been able to scrape the div_id from the html and invoke js commands on it that are not available in python.  While this is a hack and it can work, I would not recommend it long term as it may not always be supported...

**Comment by sergun** [comment]
What I actually need is to place matplotlib chart inside HBox, VBox or Tab items.

**Comment by rskabelund** [comment]
I haven't used ipympl, but sounds like that may do it...
a quick search resulted in this:
https://github.com/matplotlib/jupyter-matplotlib

**Comment by sergun** [comment]
@jasongrout , @rskabelund thanks!

See class FigureCanvasNbAgg here https://github.com/matplotlib/jupyter-matplotlib/blob/master/ipympl/backend_nbagg.py
Looks like a widget. What I didn't catch - how to encourage matplotlib to plot something to such widget...

Anyway placing plots inside other containers like Boxes, Tab - is useful thing. But don't see any example in google :-(

**Comment by sergun** [comment]
Thank you @maartenbreddels!

Do you know how to say to matplolib to plot to this widget?

**Comment by maartenbreddels** [comment]
👍 
```python
with output:
  plt.plot(...)
  plt.show() 
```
should work

**Comment by sergun** [comment]
@maartenbreddels what if I need to plot multiple figures each in separate widget? In the same Jupyter cell.

**Comment by denfromufa** [comment]
I'm having one issue with latter approach of capture the output in with block of the widget - the plot interactivity is lost if using the `%matplotlib notebook` backend. Anyone found a workaround for this? 

Not sure if ipympl helps?

**Comment by maartenbreddels** [comment]
I'd go with ipympl, that should behave like a true widget.

**Comment by jasongrout** [comment]
Closing this question as answered. Please feel free to comment further if we should open back up the discussion. Thanks!
