### ISSUE TITLE
Make the installation use the notebook 5.3 nbextension conf.d installation approach

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#1908]
This would make it so that we don't have to use the post-link script in the conda package, and the pip package would not need to also do `jupyter nbextension install ...`.

See https://github.com/jupyter-widgets/widget-ts-cookiecutter/pull/9/files for an example of how to do this.

See jupyter/notebook#3116 for the notebook PR, released in notebook 5.3.

**Comment by jasongrout** [comment]
Another example of how to do this is https://github.com/maartenbreddels/ipyvolume/commit/415f0fb904b65a18cabb6939dc6a586c820ec797

**Comment by blink1073** [comment]
Happy to help with this at the workshop.

**Comment by jasongrout** [comment]
Thanks. I've been accumulating a lot of "good first issue"s particularly for people wanting to tackle things at the workshop.

**Comment by maartenbreddels** [comment]
working on it :)

**Comment by maartenbreddels** [comment]
or maybe I shouldn't, let me know.

**Comment by jasongrout** [comment]
I think it's fine. We definitely have enough "good first issue"s to go around.

**Comment by jasongrout** [comment]
(but if you have other stuff to do, and can wait a few days, you can do it with a new contributor next week and help them come up to speed...)

**Comment by jasongrout** [comment]
Fixed in #1911
