### ISSUE TITLE
Relation between ipywidgets, widgetsnbextension

### ISSUE THREAD

**Issue by sergun** [jupyter-widgets/ipywidgets#1909]
Hello,

I'm sorry for junior question!

But can you please explain relation between  ipywidgets and widgetsnbextension.

Does one include another? What are responsibilities of each one?

In which environment should live each of them in case of jupyterhub?  I'm I right widgetsnbextansions relate to nbextensions and it should be in the same environmant as jupyterhub, jupyter, nb_conda, nbextensions etc..? And ipywidges should be in environment of notebook?

Thanks!

Sergey.

**Comment by jasongrout** [comment]
widgetsnbextension contains the javascript needed for the classic notebook. ipywidgets contains the python code for the kernel. ipywidgets should be installed in the kernel, and widgetsnbextension should be installed with the notebook. ipywidgets depends on widgetsnbextension for convenience right now, but that is being looked at in https://github.com/jupyter-widgets/ipywidgets/issues/1892

**Comment by sergun** [comment]
Thank you @jasongrout  !
Now it is +/- clear. By the way I also read interesting thread https://github.com/jupyter/notebook/issues/2841. Feel the same as author.

**Comment by jasongrout** [comment]
We should put a few sentences in the docs to this effect. Perhaps after #1892, which will change the packaging breakdown slightly.

**Comment by jasongrout** [comment]
> By the way I also read interesting thread jupyter/notebook#2841. Feel the same as author.

Yes, that would be fairly tricky to support loading multiple versions of the widgets js, depending on the kernel. Especially in things like JupyterLab, where you can have multiple kernels all interacting with the same page.
