### ISSUE TITLE
Suggestion for core widget: A password input

### ISSUE THREAD

**Issue by oscar6echo** [jupyter-widgets/ipywidgets#1915]
This may useful.  
Maybe even a full login/pwd widget.
Or is it already available ?

**Comment by oscar6echo** [comment]
Oh well it does exist in fact - as mentionned by Maarten in this [SO post](https://stackoverflow.com/questions/46645369/is-there-a-way-to-define-a-textbox-for-passwords-with-ipywidgets/46671024).  
But it's not in the doc.

**Comment by SylvainCorlay** [comment]
There is a "password" widget

is this what you are looking for?

```python
from ipywidgets import Password
Password()
```

**Comment by SylvainCorlay** [comment]
ok, closing.
