### ISSUE TITLE
perhaps a ipywidget/lab cookiecutter?

### ISSUE THREAD

**Issue by paul-shannon** [jupyter-widgets/ipywidgets#1916]
When l was learning to write ipywidgets for the notebook  I found that

````https://github.com/jupyter-widgets/widget-cookiecutter```` 

was very helpful.  As best I can tell, by studying ````ipyleaflet/js/src/jupyterlab-plugin.js````  at least one extra configuration file is needed for jupyterlab beyond those created by the widget cookiecutter.  This additional file seems to register one's new widget with jlab.   

The absence of this file may be responsible for the error message

    Error displaying widget

mentioned also in issue [1912](https://github.com/jupyter-widgets/ipywidgets/issues/1912).

I found a couple of new-ish and somewhat related cookiecutters:
 - https://github.com/jupyterlab/extension-cookiecutter-js
 - https://github.com/jupyterlab/extension-cookiecutter-ts

but these do not address ipywidgets.

Perhaps a slightly expanded cookiecutter for ipython lab widgets could be cobbled together by someone who knows what he or she is doing?

Thanks for all the great work on jupyterlab!

 - Paul

**Comment by jasongrout** [comment]
https://github.com/jupyter-widgets/widget-cookiecutter/issues/29 is tracking this in the js cookie cutter.
