### ISSUE TITLE
interactive examples not working in jupyterlab-0.31.1 nor Notebook-5.3.1 of  january 20th ??

### ISSUE THREAD

**Issue by stonebig** [jupyter-widgets/ipywidgets#1917]
classic "interactive" ipywidgets seem not working in latest Jupyterlab and Notebook (on my windows10 PC). 

https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/examples/Beat%20Frequencies.ipynb

signaled on gitter to @jasongrout :
 [20 janvier 2018 00:17](https://gitter.im/jupyterlab/jupyterlab?at=5a627c83ce68c3bc74dced93)

there seems to be a problem with interact in jlab 0.31. I'm looking into it

JUPYTERLAB:

![beat_lab](https://user-images.githubusercontent.com/4312421/35192440-9391ff92-fe92-11e7-9c73-174de840bd20.PNG)

CLASSIC NOTEBOOK:
![beat_notebook](https://user-images.githubusercontent.com/4312421/35192447-c01aaa64-fe92-11e7-9746-2eb0f906ce4e.PNG)

**Comment by anoe** [comment]
I have the same problem. Using JLab 0.31.5 on Ubuntu 16.04 with widgetsnbextension=3.1.3 and ipywidgets=7.1.1

**Comment by jasongrout** [comment]
What version of the jupyterlab widgets extension do you have? What does `jupyter labextension list` give?

**Comment by anoe** [comment]
Doh! I hadn't installed the jupyterlab extension at all. I just did, and it works. Thanks!
