### ISSUE TITLE
kernel / front end communication performance drop

### ISSUE THREAD

**Issue by AaronWatters** [jupyter-widgets/ipywidgets#1920]
Sorry to be vague, but think I've noticed a significant performance drop in the communication round trip between the javascript front end and the python kernel with new versions of the widget infrastructure sometime in the last year.

For example this notebook

**https://github.com/simonsfoundation/jp_svg_canvas/blob/master/examples/Moving%20circles.ipynb**

(which can be tested using binder) uses tight loops between javascript mouse events and python callbacks.   A year or so ago there was no issue with performance in this notebook but something has changed and now the performance is markedly worse to the point where the features don't really work properly some of the time.   This is one of many cases where I've seen effect and I see the effect in both local and remote jupyter deployments.

I don't know what caused the performance drop, but I would prefer that widgets have performant communication with the kernel even if it means (for example) that you can't have "multiple views" of a widget.  I would prefer to have a single view with good performance.

Has the communication mechanism implementation changed in a way that might explain a decrease in perfomance?

Let me know if this issue is too vague to be useful and I will delete it, but please comment if you have suggestions or ideas.

**Comment by jasongrout** [comment]
We've always had multiple views, so I doubt that itself is an issue.

We have added things like the binary synchronization protocol in the message processing step. It would be good if someone actually benchmarked and/or profiled any change to have something more concrete to go on. Perhaps even a simple timing of a roundtrip data message (i.e., set a value in js, have it go to python, which triggers a different change in data which goes back to js) might be useful to diagnose what you are saying.

CC @maartenbreddels - who worked on the binary synchronization, and can be picky about things having good performance :).

**Comment by AaronWatters** [comment]
I'm closing this issue because I think "the problem" may have been "between the monitor and the chair" :).

**Comment by jasongrout** [comment]
Thanks for following up on this.

**Comment by maartenbreddels** [comment]
Actually, I think there may be a performance drop. I didn't have time to investigate it yet though.
