### ISSUE TITLE
install yarn

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#1921]
The version of yarn in conda-forge is old. Until it is updated, we should change the dev install instructions to also update yarn: `npm install -g yarn`

**Comment by blink1073** [comment]
How do we ping the core conda-forge maintainers?  cf https://github.com/conda-forge/yarn-feedstock/pull/2

**Comment by SylvainCorlay** [comment]
yarn has been released on conda-forge. Closing.
