### ISSUE TITLE
Centralise documentation for the output widget

### ISSUE THREAD

**Issue by pbugnion** [jupyter-widgets/ipywidgets#1935]
Currently, documentation for the output widget is scattered across:
 - [async widgets](https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Asynchronous.html#Interacting-with-output-widgets-from-background-threads)
 - [widget list](https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html#Output)

With PR #1934 , we need to extend the docs for the output widget to expose its use as a decorator. 

Given the output widget's power, we think it makes sense to bring docs on the output widget to the top level. I think it would be useful to structure the notebook as:

 - introduction (what's currently in the widget list)
 - displaying rich output (e.g., with an example from matplotlib?)
 - async widgets
 - using the `@capture` decorator, including as a way to debug widget callbacks.

Happy to tackle this today / this weekend, unless someone else is particularly keen to.

---

Jason deserves the credit for the idea behind this issue.

**Comment by jasongrout** [comment]
Definitely +1. I started an output widget notebook a while ago, but I'm not sure I pushed it anywhere.

**Comment by jasongrout** [comment]
Here is the output notebook I started working on a while ago. Feel free to use it as a start, or feel free to discard it and do what you think is best: https://gist.github.com/anonymous/eb176705a103517179b4f57b6201df1d

**Comment by jasongrout** [comment]
#1936 also has some interesting material that could be incorporated in an output notebook.

**Comment by jasongrout** [comment]
Fixed by #2020. Thanks again!
