### ISSUE TITLE
Valid control readout width

### ISSUE THREAD

**Issue by sergun** [jupyter-widgets/ipywidgets#1937]
Hi!

Didn't catch how to change readout width for Valid control. Is it possible?

Sergey.

**Comment by sergun** [comment]
Probably for Valid control readout width should be close to 100% of the control width (keep in mind ok / invalid icon)...

Similar question about Text description width..

What I see for long descriptions / readouts (added red border property in layout):

![image](https://user-images.githubusercontent.com/15171173/35473767-e8217db4-0395-11e8-86f4-3d8d08274800.png)

**Comment by pbugnion** [comment]
Thanks for raising this.

> Similar question about Text description width

You can control the text description width (for all widgets with a `description` traitlet) with the `style` argument:

```py
widget = widgets.Text(
    description='some very very long sentence about invalidity',
    style={'description_width': '300px'},
    layout={'width': '500px'}
)
widget
```

> how to change readout width for Valid control

As far as I can tell, there is no way to control the readout width at the moment. Adding a `readout_width` to the style traitlet for the `Valid` control would be valuable. In the meantime, you can hack this with something like:

```py
import ipywidgets as widgets
from IPython.display import display, HTML

display(
    HTML("""
    <style>
    .widget-valid-readout.widget-readout {
        max-width: 500px
    }
    </style>
    """)
)

widget = widgets.Valid(
    readout='some very very long sentence about invalidity',
    layout={'width': '700px'}
)
widget
```

**Comment by sergun** [comment]
@pbugnion thanks! That's what I need

**Comment by pbugnion** [comment]
Great!

I've opened issue 1939 to track adding a way to control the readout width.
