### ISSUE TITLE
remove x, y coordinates of matplotlib figure displayed in %matplotlib notebook mode

### ISSUE THREAD

**Issue by sergun** [jupyter-widgets/ipywidgets#1938]
Hi!

I deal with updatable matplotlib figures.
Use %matplotlib notebook magic

Do you know how to remove these updatable x, y coordinates values in right-bottom corner?

![image](https://user-images.githubusercontent.com/15171173/35473875-2725ec2e-0397-11e8-9cf0-17c9ad5922e5.png)

Sergey.

**Comment by jasongrout** [comment]
Great question. I don't remember seeing these. Can you post some code that reproduces the problem?

**Comment by sergun** [comment]
```
%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np
plt.plot(np.linspace(0,100, 100), np.sin(np.linspace(0,100, 100)))
```

**Comment by jasongrout** [comment]
Thanks. I think this question is for matplotlib. Do you mind posting it at https://github.com/matplotlib/matplotlib/issues, if it is still an issue?

**Comment by ianhi** [comment]
I think this is generally considered a feature of matplotlib. Although you can turn it off by setting `ax.format_coord` to be a no-op. See this example: https://matplotlib.org/stable/gallery/images_contours_and_fields/image_zcoord.html

I'm going to close this as not widget related - if you have more questions about this a great place to ask them is https://discourse.matplotlib.org/
