### ISSUE TITLE
validate value in FloatText widget

### ISSUE THREAD

**Issue by sergun** [jupyter-widgets/ipywidgets#1941]
Is it possible to validate modified value in FloatText and keep focus or switch it to old value?

**Comment by jasongrout** [comment]
I think the behavior right now is to wait for the float text to have a "change" event (sometimes that means when the user navigates away), and then validate, and if it is not valid, reset it to the old value. How do you want that to change?

**Comment by martinRenou** [comment]
Here is a small snippet of code that does what you want, and I guess what Jason is suggesting in his comment:

```Python
from ipywidgets import FloatText

text = FloatText(continuous_update=False)

def validate(change):
    # Put your validation condition here
    if change['new'] > 50:
        change['owner'].value = change['old']

text.observe(validate, 'value')

text
```

I am closing this for issue triage. Feel free to reopen it if you have more questions :)
