### ISSUE TITLE
Enabling widgets on jupyterhub for all users

### ISSUE THREAD

**Issue by tritemio** [jupyter-widgets/ipywidgets#1949]
Hi,

I am running jupyterhub with default local spawner installed via conda (system-wide installation). Jupyterhub is installed in its own coda-environment which also includes the single-user notebook. I provide another system environment to all users called `py36-sys`. I installed the ipywidgets package from conda-forge in the `py36-sys` environment. Still, users get an error when trying to use the widgets. 

I also tried to run this command after activating the `py36-sys` environment:

```
jupyter nbextension enable --py widgetsnbextension --sys-prefix
```

but the error persists.

**Test code:**
```python
from ipywidgets import interact

@interact(x=(0, 100, 10))
def p(x=50):
    pass
```
**Output**
```
Failed to display Jupyter Widget of type `interactive`.

If you're reading this message in the Jupyter Notebook or JupyterLab Notebook, it may mean that the widgets JavaScript is still loading. If this message persists, it likely means that the widgets JavaScript library is either not installed or not enabled. See the Jupyter Widgets Documentation for setup instructions.

If you're reading this message in another frontend (for example, a static rendering on GitHub or NBViewer), it may mean that your frontend doesn't currently support widgets.
```

**Comment by tritemio** [comment]
I solved the issue by:

1. installing ipywidgets also in the environment which holds jupyterhub (and the single-user notebook)
2. running `jupyter nbextension enable --py widgetsnbextension --sys-prefix` in the jupyterhub widgets
3. restarting jupyterhub

Only step 1 was not enough.

**Comment by jasongrout** [comment]
Great, thanks for following up with your solution so others can benefit!

**Comment by tritemio** [comment]
@jasongrout, would you be interested in adding a short section to the installation docs saying that when notebook and kernel are in different environments, both need to have `ipywidgets` installed?

I could send a PR.

**Comment by jasongrout** [comment]
Definitely! Actually, the ipywidgets python package does not need to be installed in the notebook environment - only the widgetsnbextension package needs to be installed (and enabled) in the notebook environment.

**Comment by jasongrout** [comment]
And technically only the ipywidgets python package needs to be installed in the kernel environment, but we make it depend on widgetsnbextension for convenience when you only have one environment. See also https://github.com/jupyter-widgets/ipywidgets/issues/1892 for more discussion on this topic.

**Comment by AndriiHanenko** [comment]
> 
> 
> I solved the issue by:
> 
>     1. installing ipywidgets also in the environment which holds jupyterhub (and the single-user notebook)
> 
>     2. running `jupyter nbextension enable --py widgetsnbextension --sys-prefix` in the jupyterhub widgets
> 
>     3. restarting jupyterhub
> 
> 
> Only step 1 was not enough.

True
