### ISSUE TITLE
widget Image not working in documentation and nbviewer

### ISSUE THREAD

**Issue by oscar6echo** [jupyter-widgets/ipywidgets#1950]
Issue #1914 tracks the resolution of the rendering of widgets in the documentation.  
Well, *almost* completely.  
The [widget Image](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#Image) still does not get rendered. 

It looks very much like the nbviewer behavior.
See an [example of nb containing widget Images](https://nbviewer.jupyter.org/github/oscar6echo/nbviewer-test/blob/master/demo_core_widgets_1.ipynb) rendered on nbviewer.

And it does work even less in nbconvert which still does not support widgets 7.x in general. Cf jupyter/nbconvert#636.

**Comment by SylvainCorlay** [comment]
Thanks for opening an issue to track this down. This is indeed a bug with the widgets inline renderer.

**Comment by oscar6echo** [comment]
If you can point to a possible cause, I could try to narrow down the bug.  
Unfortunately I cannot guarantee I'll succeed..
