### ISSUE TITLE
Hide Jupyter "Failed to display Jupyter Widget" on Github

### ISSUE THREAD

**Issue by PetrochukM** [jupyter-widgets/ipywidgets#1951]
Hello There!

Posting my notebook to GitHub adds:
> Failed to display Jupyter Widget of type HBox.
> 
> If you're reading this message in the Jupyter Notebook or JupyterLab Notebook, it may mean that the widgets JavaScript is still loading. If this message persists, it likely means that the widgets JavaScript library is either not installed or not enabled. See the Jupyter Widgets Documentation for setup instructions.
> 
> If you're reading this message in another frontend (for example, a static rendering on GitHub or NBViewer), it may mean that your frontend doesn't currently support widgets.

To every cell that I use `tqdm_notebook` with. I would like to hide that warning when posted on Github. It's a long warning that takes away from the content of the notebook!

I tried to follow this StackOverflow post: https://stackoverflow.com/questions/9031783/hide-all-warnings-in-ipython 

But alas, I was unable to remove the warning!

Thanks!

**Comment by Deepblue129** [comment]
See here where I tried to use:
```
import warnings
warnings.filterwarnings('ignore')
```

![image](https://user-images.githubusercontent.com/7424737/35770078-de3d9fb0-08c9-11e8-9845-4b818f93b7e3.png)

**Comment by jasongrout** [comment]
That warning is from the actual widget output, it has nothing to do with the python warnings. We're trying to be helpful and tell the user why they aren't seeing widgets (the same text is displayed in a normal notebook if someone doesn't have widgets installed). One way to get rid of it is to clear that cell's output. Would that work for you?

**Comment by PetrochukM** [comment]
That would not work for me. 

The problem is the warning is very long; therefore, it tends to hide or obscure the important cell's output. In addition, the warning comes up for any notebook contained in Github; therefore, it tends to obscure the main result with a warning. 

The only option for me is to not use Jupyter Widgets locally then when I post on Github, I do not get a warning right now.

**Comment by jasongrout** [comment]
I agree it's long. It used to not be so long, but people were getting really confused about what to do with a short error message, so we changed it to be something more informative.

Perhaps we should make it much shorter, with just a link to the docs, a faq page or something that basically gives the rest of the text.

Adding this to the 7.2 milestone to see if we can rephrase that text.

**Comment by jasongrout** [comment]
This also is an opportunity for us to correct https://github.com/jupyter-widgets/ipywidgets/issues/1777#issuecomment-339479688 and fix #1777.
