### ISSUE TITLE
Widget/Download widget state does nothing

### ISSUE THREAD

**Issue by oscar6echo** [jupyter-widgets/ipywidgets#1953]
My config:

```bash
# Name                    Version                   Build  Channel
ipywidgets                7.1.1                     <pip>
widgetsnbextension        3.1.3                     <pip>
```

How come ?

Not a real problem as widgets do work perfectly on my install.  
But would be curious to know why.

**Comment by SylvainCorlay** [comment]
I there any error message in the JavaScript console? It could come from a custom widget library installed in the environment making the feature crash.

**Comment by oscar6echo** [comment]
There was no msg in the console.  
But I tried on Chrome and it worked. It looks like a Firefox issue that silently prevents download.  

So no pb on ipywidget side.

**Comment by denfromufa** [comment]
I have a similar issue with downloading/embedding of widgets:

In Chrome the download fails with a network error.
In Firefox the download does nothing.
In both browsers the embedding stalls the notebooks UI.
