### ISSUE TITLE
How to save widget state programmatically ?

### ISSUE THREAD

**Issue by oscar6echo** [jupyter-widgets/ipywidgets#1954]
In the current situation, as far I as know, widget state is not saved in the notebook by default.  
You must manually select the menu 'Widgets/Save widget state'.  

**Is there a way to save widget state from nbconvert ?**

(assuming nbconvert can deal with ipywidget 7.x- which can be done with manually with such a [template](https://github.com/oscar6echo/notebook-snapshot/blob/master/notebook_snapshot/templates/main.tpl.html) - waiting for nbconvert to catch up)

If not widgetized notebooks cannot be part of a batch work in which nbconvert typically:
+ copy a notebook
+ execute it
+ convert it to html (burning in images and removing code cells)

See this [notebook-snapshot](https://github.com/oscar6echo/notebook-snapshot) convenience package and its [demo nb](https://github.com/oscar6echo/notebook-snapshot/blob/master/demo_notebook_snapshot.ipynb) for an example of such unit workflow.

Is that already possible ? If not any workaround ?  
If not I think such a feature would add many use cases for widgets.

**Comment by oscar6echo** [comment]
Cf. jupyter/nbconvert/issues/751

**Comment by jasongrout** [comment]
Great question. Let's track this discussion over in jupyter/nbconvert#751, since that is likely where the code needs to live, and I'll close this so the discussion is all in one place.
