### ISSUE TITLE
Deprecate old lab package

### ISSUE THREAD

**Issue by vidartf** [jupyter-widgets/ipywidgets#1955]
[This old npm package](https://www.npmjs.com/package/jupyterlab_widgets) for widgets in jupyterlab should be deprecated in favor of the new one ([@jupyter-widgets/jupyterlab-manager](https://www.npmjs.com/package/@jupyter-widgets/jupyterlab-manager)). See the similar jupyterlab issue for point instructions: https://github.com/jupyterlab/jupyterlab/issues/151

**Comment by jasongrout** [comment]
Thanks!

**Comment by jasongrout** [comment]
I at least added a deprecation warning now. We can follow up with the rest of the readme modifications, etc., later:

```
$ npm install jupyterlab_widgets
npm WARN deprecated jupyterlab_widgets@0.3.1: jupyterlab_widgets is deprecated. Use @jupyter-widgets/jupyterlab-manager instead.
```

**Comment by jasongrout** [comment]
I submitted a request to npmjs.com to prominently display deprecation warnings for deprecated packages. I think that's all we'll do here - we don't want to move the sources, and I'd rather not rebuild a special release of the package with the deprecation in the readme: (a) it will take some time, and (b) it falsely indicates activity to have a new version published.

**Comment by vidartf** [comment]
I think marking at as deprecated on npm + the readme on master (no release needed) is sufficient. 👍

**Comment by jasongrout** [comment]
npm just deployed a new interface that very clearly marks a deprecated package as deprecated, so I also think we're good there.

<img width="747" alt="screen shot 2018-03-27 at 11 36 53 pm" src="https://user-images.githubusercontent.com/192614/38012842-cdef0b2c-3217-11e8-9e3b-135072974da0.png">
