### ISSUE TITLE
Updating dropdown.options does not update value or label

### ISSUE THREAD

**Issue by fterbo** [jupyter-widgets/ipywidgets#1956]
I have a case where one dropdown selection updates another, with the 2nd dropdown starting with a singular value of `["  -"]`.

`.observe` on the 1st dropdown resets the contents of the second dropdown by setting the `.options` attribute.  This updates the dropdown *visually* for the user, but apparently not programmatically.  If the user does not make a choice, the `.value` is still the stub value we shoved in by default (`"  -"`).  As long as they twiddle the dropdown we get the real value returned when inspecting the control

**Comment by jasongrout** [comment]
I reproduced this with:

```python
from ipywidgets import *
x = Dropdown(options=['a', 'b'])
y = Dropdown(options=[' - '])

def change_x(*args):
    y.options=[1, 2, 3]
x.observe(change_x, 'value')

HBox([x,y])
```
Change the x value, and you'll see that the y dropdown updates, but y.value is still ' - '.

**Comment by jasongrout** [comment]
I think the problem here is that changing the options resets the `.index` to 0, but if it was already 0, it is regarded as no change, so the value and label are not changed.

**Comment by jasongrout** [comment]
As a workaround until this is merged and released, you can set the options *and* set the .index to None:


```python
from ipywidgets import *
x = Dropdown(options=['a', 'b'])
y = Dropdown(options=[' - '])

def change_x(*args):
    y.index = None
    y.options=[1, 2, 3]
    
x.observe(change_x, 'value')

HBox([x,y])
```

**Comment by Dommsko** [comment]
I am having the same problem right now and the workaround example is not working, either. Any ideas on what might be wrong?

Test Setup
ipywidgets          7.5.1
jupyterlab          2.2.6

Cheers!
