### ISSUE TITLE
Drop support for mutable types as dropdown options

### ISSUE THREAD

**Issue by fterbo** [jupyter-widgets/ipywidgets#1958]
I know this has been reviewed before, but I humbly request it be reviewed again.. :-)

I don't see any upside to supporting dictionaries as an options list (you can just use `widget.options = dict.items()` if you want the same behaviour, which more clearly separates ownership semantics), and it is a source of many pitfalls.  I suspect that many people use dictionaries simply because it's more prominently featured in the docs than the list-of-tuples approach.

I realize this is a backwards-incompatible change, but I think moving forward it would reduce community support burden (and frustrated user time).  Certainly this could be done in a phased manner with `DeprecationWarning` (making sure users can actually see it, of course).

**Comment by jasongrout** [comment]
I definitely agree.

**Comment by jasongrout** [comment]
We can start by deprecating when we see Mappings (e.g., dictionaries) here: https://github.com/jupyter-widgets/ipywidgets/blob/c64f88ff740a2c88e124909ada459dbeda42ca72/ipywidgets/widgets/widget_selection.py#L120-L122

(and change the docs and examples to not use dictionaries)

Later for 8.0 we can remove that case entirely.
