### ISSUE TITLE
Module is not defined requirejs

### ISSUE THREAD

**Issue by antonelepfl** [jupyter-widgets/ipywidgets#1963]
Hi all,

I'm trying to load some external script using the `display_javascript` function in IPython.display.

```
from IPython.display import display_javascript

display_javascript("""
  require(["https://.../renderjson.js"], function(renderer) {
    console.log(renderer);
  })""")
});

```

The problem is that when I load the resource I get `Uncaught ReferenceError: module is not defined` because in the external file it does 
```
module.exports = functionExample;
```

I have tried with [AsynchronousDefinition](http://wiki.commonjs.org/wiki/Modules/AsynchronousDefinition) but as it is an external file I cannot modify it.

There is any workaround/solution for this?

**Comment by jasongrout** [comment]
This sounds like a general requirejs question, is that right? Can you inspect the javascript in the browser's debugger and see where the error is thrown? I don't have a ton of experience using requirejs to load http urls as modules. Perhaps http://requirejs.org/docs/api.html#errbacks can help?

**Comment by jasongrout** [comment]
Closing as answered. Please post another comment here if you'd like to continue the discussion or to continue diagnosing the issue.
