### ISSUE TITLE
Download Widget that Sends Files to the Browser

### ISSUE THREAD

**Issue by eliasdabbas** [jupyter-widgets/ipywidgets#1966]
Is there a way to send file objects through a widget (or any other means) to the browser to be downloaded by the user? 

The main benefit here is when the notebook is online (I ran into this trying to share one on Binder). If the user has the notebook locally, we can easily have an `ipywidgets.Button` invoke `plt.savefig()` or `pd.DataFrame.to_csv()` for example. 

The problem here is that the end user does not have access to the file system on the server. 

Here is an example, if it's not clear: 
https://hub.mybinder.org/user/eliasdabbas-keywords_widget-q5layqhx/notebooks/keywords_widget.ipynb 

You can clearly see that my solution is clumsy, after generating the required DataFrame, the user will have to print it, then select, copy, and paste. 

Thanks!

**Comment by jasongrout** [comment]
You can just create an HTML widget with an a tag with a data URI, like:

```python
from ipywidgets import HTML
HTML("""<a download='test.csv' href='data:text/csv;charset=utf-8;base64,c2VwYWxfbGVuZ3RoLHNlcGFsX3dpZHRoLHBldGFsX2xlbmd0aCxwZXRhbF93aWR0aCxzcGVjaWVzDQo1LjEsMy41LDEuNCwwLjIsc2V0b3NhDQo0LjksMywxLjQsMC4yLHNldG9zYQ0KNC43LDMuMiwxLjMsMC4yLHNldG9zYQ0K'>asdf</a>""")
```

**Comment by jasongrout** [comment]
Or you can write a custom widget that does something similar. There shouldn't any problems blocking a custom widget from doing that.

**Comment by eliasdabbas** [comment]
Great, thanks a lot!
