### ISSUE TITLE
how to set the title width for Tab widgets

### ISSUE THREAD

**Issue by denfromufa** [jupyter-widgets/ipywidgets#1974]
How to set the title width for Tab widgets? This is not explained here:

http://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Styling.html

http://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html#Tabs

Note that width property sets the width of the Tab output area, not its title.

**Comment by jasongrout** [comment]
We're discussing this at https://github.com/jupyter-widgets/ipywidgets/issues/1905. Let's move the conversation there to keep it in one place. Thanks!
