### ISSUE TITLE
how to add control to dynamically swap between order of levels of Tab widgets in multi-level setup?

### ISSUE THREAD

**Issue by denfromufa** [jupyter-widgets/ipywidgets#1975]
Is it possible to dynamically change the layout of widgets (e.g. Tab) without resorting to writing custom python code that re-builds this layout based on external control switch?

A particular case I'm looking at is swapping the levels of Tab widgets. For example first level represents several objects, and second level represents several properties of these objects. I would like to be able to swap between order of these levels to have flexibility in scrolling through objects for the same property vs scrolling through properties for the same object.

Let me know if a code sample is necessary.

**Comment by denfromufa** [comment]
So then the widget state would be serializable to save into HTML due to this custom Python code?

**Comment by denfromufa** [comment]
So then the widget state would NOT be serializable to save into HTML due to this custom Python code?

**Comment by jasongrout** [comment]
You wouldn't be able to have the dynamic switching happen in a pure HTML page (e.g., with widget state saved to a pure HTML page) due to this custom python code - unless that HTML page had access to a python kernel somehow to run this python code.

**Comment by jasongrout** [comment]
Closing as answered. Please post another comment here if you'd like to continue the discussion.
