### ISSUE TITLE
[widgets specs] Produce a JSON file instead of the current markdown output

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter-widgets/ipywidgets#1979]
It would make it easier (IMO) to compare the widgets schemas of e.g. `xwidgets` with those of ipywidgets if we generated a `JSON` file instead of a markdown file.

We could generate a similar JSON file in xwidgets, and check that it matches that of ipywidgets.

The generated markdown document would still be useful as documentation.

**Comment by jasongrout** [comment]
The code that generates the markdown file is at https://github.com/jupyter-widgets/ipywidgets/blob/master/packages/schema/generate-spec.py. It's probably fairly straightforward to get that to generate a json document instead of/in addition to the markdown document.

**Comment by vidartf** [comment]
I just wanted to crossref this project, as it might be relevant: https://github.com/vidartf/widget-gen

**Comment by jasongrout** [comment]
Putting to beta 2, since Sylvain volunteered :).

**Comment by vidartf** [comment]
Closed by #1979
