### ISSUE TITLE
ipywidget error in jupyterlab notebook: "Could not find model"

### ISSUE THREAD

**Issue by DavidJVitale** [jupyter-widgets/ipywidgets#1980]
Hello, I work on the development of a [Python library that uses an ipywidget map](https://developers.arcgis.com/python/guide/install-and-set-up/). In the standard Jupyter Notebook environment, our map widget works great: 

![screen shot 2018-02-21 at 5 10 18 pm](https://user-images.githubusercontent.com/18691334/36514644-46edbb8a-172a-11e8-9d8c-f0575e6efffb.png)

I am attempting to see if the map widget and our API will work just the same in JupyterLab notebooks. I run the following commands in either OSX or Windows for setup:

```
conda create --name new_jlab_env
source activate new_jlab_env
conda install -c conda-forge jupyterlab
jupyter labextension install @jupyter-widgets/jupyterlab-manager
conda install -c esri arcgis
jupyter lab
```

However, I get the following error when trying to use the map widget in jupyterlab notebooks:

![screen shot 2018-02-21 at 3 37 55 pm](https://user-images.githubusercontent.com/18691334/36514754-ea16bece-172a-11e8-9dbf-a16096e3d297.png)

From my understanding, in theory most ipywidgets should work in jupyterlab by installing ```jupyterlab-manager``` like I did, correct? Am I missing a step, or is this a known issue like #1664 and #1684? Thanks for your help!

-----

[Here](https://user-images.githubusercontent.com/18691334/36514779-0e5913d6-172b-11e8-830f-b79ee7832d82.png) is a screenshot of my browser console during the widget drawing failure, 
[here](https://github.com/jupyter-widgets/ipywidgets/files/1746313/conda_env.txt) is my conda environment

**Comment by jasongrout** [comment]
You'll need to also modify the custom widget to make a jupyterlab extension. The jlab extension will  register the widget in jupyterlab. You can see how we did it for bqplot:

https://github.com/bloomberg/bqplot/blob/master/js/package.json#L43-L45

https://github.com/bloomberg/bqplot/blob/master/js/src/jupyterlab-plugin.js

**Comment by SylvainCorlay** [comment]
@DavidJVitale all you need to do for `ipyleaflet` to work in jupyterlab is

`jupyter labextension install jupyter-leaflet`.

**Comment by jasongrout** [comment]
Is the arcgis package using ipyleaflet, or their own map widget?

**Comment by DavidJVitale** [comment]
@jasongrout @SylvainCorlay We create our own map widget: it is not an ipyleaflet of an open street map. It is custom javascript that handles its own inputs, draws its own layers, calls map resources from our hosted servers, etc.

I tried the jupyter-leaflet commands just for thoroughness, and the issue still remains. Request to re-open, please.

**Comment by SylvainCorlay** [comment]
@DavidJVitale you would need to make it a jupyterlab extension. I think that there was another comment earlier in the issue which I deleted involuntarily from my phone.

> You'll need to also modify the custom widget to make a jupyterlab extension. The jlab extension will register the widget in jupyterlab. You can see how we did it for bqplot:
> 
> https://github.com/bloomberg/bqplot/blob/master/js/package.json#L43-L45
> 
> https://github.com/bloomberg/bqplot/blob/master/js/src/jupyterlab-plugin.js
> 

Quick note about ipyleaflet: you might still be interested in using it, as it supports arbitrary tile layers, as well as WMS layers.

**Comment by DavidJVitale** [comment]
@SylvainCorlay Thanks for your help! It's greatly appreciated.

This probably is a question better to ask in the jupyterlab repository; but I was under the impression that all 'legacy' ipywidgets should function in jupyterlab, provided that you configure jupyterlab correctly (with the ```jupyterlab-manager```, for example). In other words, I thought jupyterlab was trying to mantain backwards compatibility with existing ipywidgets.

Is this accurate? Or is Jupyterlab just trying to maintain compatibility with the notebook _format_, not necessarily all ipywidgets written for it?

**Comment by SylvainCorlay** [comment]
So that is not *quite* accurate. There is still a bit of work for your custom widget to work in jupyterlab. You can look at bqplot/ipyleaflet/ipyvolume for examples. 99% of your code will remain the same and you only have to add a bit a boilerplate.

**Comment by maartenbreddels** [comment]
Let me add to this that is will be transparent to users in the future.
A pip install of a package can enable it both in the jupyter notebook and jupyter lab, we're not there yet, but close!

**Comment by DavidJVitale** [comment]
Thank you to both of you, I appreciate it. To make sure I have it all straight:

While Jupyterlab is in beta (like it is today 2-22-2018), you need to do a bit of work to convert your legacy ipywidgets to a jupyterlab extension. Hopefully by the jupyterlab 1.0 release, legacy jupyter widgets should work in the notebooks area without any extra steps to convert it to a jupyterlab extension?

**Comment by maartenbreddels** [comment]
For developers it does need some extra steps to get widgets working in jupyter lab, but as Sylvain pointed out, these are in most cases pretty simple. For users we can make it so that a pip install will enable/install the widget for jupyter notebook and jupyter lab, also this requires a bit of work, I haven't tried this out yet, and I don't know of any widget library that tried to implement this.

**Comment by DavidJVitale** [comment]
Perfect, I think I understand everything now. Thank you.

We do a similar thing with our ```arcgis``` package now, after our install finishes the equivalent of the following two commands are run:
* ```jupyter nbextension install --py --sys-prefix arcgis```
* ```jupyter nbextension enable--py --sys-prefix arcgis``` 

In pip, this was accomplished by overriding the ```cmdclass```'s ```install``` object (see [here](https://stackoverflow.com/questions/17806485/execute-a-python-script-post-install-using-distutils-setuptools#18159969)), and in conda we just wrote ```post-link.sh``` and ```post-link.bat``` scripts.

I'm not sure any of this is applicable to your efforts in getting automatic installing/enabling of widgets, just figured I'd share. Thanks again :)

**Comment by jasongrout** [comment]
To elaborate - JupyterLab does not support the classic notebook nbextensions (it has a much better extension system). The target is to support the notebook document format in a notebook interface that is largely the same as the classic notebook.

In the ipywidgets world, we've worked hard to make it fairly straightforward to add some boilerplate to make both an nbextension and jupyterlab extension.

**Comment by jasongrout** [comment]
Also please note that the JupyterLab extension api is still in flux until 1.0, so you may need to update jupyterlab extensions to keep up with beta releases. We try to shield you from this in ipywidgets, so hopefully things will be fairly stable, but the JupyterLab "beta" indicates that the plugin api is not stable.
