### ISSUE TITLE
widget are not being displayed

### ISSUE THREAD

**Issue by tb8900** [jupyter-widgets/ipywidgets#1985]
I know this issue has been posted before, but I have read through multiple posts and tried their solutions with no luck. This might be due the fact that my set up is a bit different.

I am running Linux Subsystem on Windows 10 to launch Jupyter, then using my browser (Chrome or Firefox) to access localhost:8888. I know this may be an unusual setup, let me know if that does not work.

This is the simple test I am trying to run:
```python
from ipywidgets import *
IntSlider()
```

Here are the errors that in my Linux:
```
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.version
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.version
[W 10:26:07.747 NotebookApp] 404 GET /static/components/preact/preact.min.js.map (127.0.0.1) 2.81ms referer=None
[W 10:26:07.754 NotebookApp] 404 GET /static/components/proptypes/index.js.map (127.0.0.1) 5.04ms referer=None
[W 10:26:07.759 NotebookApp] 404 GET /static/components/preact-compat/preact-compat.min.js.map (127.0.0.1) 3.36ms referer=None
[W 10:26:07.801 NotebookApp] 404 GET /notebooks/widgets.min.css.map (127.0.0.1): No such file or directory: widgets.min.css.map
[W 10:26:07.813 NotebookApp] 404 GET /notebooks/widgets.min.css.map (127.0.0.1) 15.10ms referer=None
```

In my browser's console:
```
Uncaught (in promise) WrappedError
2manager.js:115 Could not cross validate the widget frontend and backend versions. Error: Timeout while trying to cross validate the widget frontend and backend versions.
    at manager-base.js:200
(anonymous) @ manager.js:115
utils.js:141 WrappedError
promiseRejection @ utils.js:141
kernel.js:1007 Couldn't process kernel message WrappedError
```

jupyter nbextension list ## returns the following
```
Known nbextensions:
  config dir: /root/.jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled
      - Validating: OK
  config dir: /root/anaconda3/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled
      - Validating: OK
      beakerx/extension  enabled
      - Validating: OK
      nbextensions_configurator/config_menu/main  enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      contrib_nbextensions_help_item/main  enabled
      - Validating: OK
    tree section
      beakerx/tree  enabled
      - Validating: OK
      nbextensions_configurator/tree_tab/main  enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
  config dir: /usr/local/etc/jupyter/nbconfig
    notebook section
      nbextensions_configurator/config_menu/main  enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      contrib_nbextensions_help_item/main  enabled
      - Validating: OK
    tree section
      nbextensions_configurator/tree_tab/main  enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
```

Things I have tried:
```
jupyter nbextension enable --py --sys-prefix widgetsnbextension
```

I do have widgetsnbextension 3.1.4 and ipywidgets 7.1.2 installed in my Linux Subsystem.

Any advice will be incredibly helpful. Thank you in advance!

**Comment by thomasaarholt** [comment]
Small thing: Encompass your posted code in three of these above and below:
`
That'll make your code look like this:
```
my code
more code
if True:
   tasty

**Comment by vidartf** [comment]
I edited it for formatting.

**Comment by tb8900** [comment]
Thank you for pointing out the issue with formatting and editing on my behalf.

I still have not been able to resolve the issue. Any advice will be much appreciated. Thanks!

**Comment by vidartf** [comment]
I just created a clean conda env to test using WSL, and it worked for me:

```bash
$ conda create -n widgets python=3.6 notebook ipywidgets -y
$ source activate widgets
$ jupyter notebook --no-browser
```

```python
import ipywidgets
ipywidgets.IntSlider()
```

Looking at your other output, I see that `jupyter nbextension list` reports some problems (`- Validating: problems found: ...`). If I were you, I'd try to start from a clean environment, and add any needed extensions one at the time.

Note: If you are having problems with a bare environment, you should ensure that your WSL is up to date:

```bash
$ sudo apt-get update
$ sudo apt-get upgrade
```

**Comment by jasongrout** [comment]
Notice that you have two jupyter-js-widgets extensions installed, one in your user directory and one in the root anaconda directory. Likely one is an old version. If I were you, I'd delete both versions, then install the widgetsnbextension package again.

**Comment by jasongrout** [comment]
Closing as answered. Please post another comment here if you'd like to continue the discussion or to continue diagnosing the issue.
