### ISSUE TITLE
widgets not working with SageMath kernel installed in anaconda jupyter notebook

### ISSUE THREAD

**Issue by bryangingechen** [jupyter-widgets/ipywidgets#1989]
I hope it's OK to ask this here. I am using SageMath 8.1 and the latest anaconda distribution on macOS 10.2.6. In an effort to streamline my workflow, I installed the SageMath kernel into my anaconda Jupyter, following the instructions [here](https://stackoverflow.com/questions/39296020/how-to-install-sagemath-kernel-in-jupyter/41595015#41595015). Interactive widgets using ipywidgets work fine in my anaconda Jupyter when I use its default Python 3.6 kernel, and they (and SageMath's interact elements) also work fine in SageMath's Jupyter notebook interface. However, they do not work in my anaconda Jupyter notebook when I use the SageMath kernel; I get the following error message in the notebook:

>Widget Javascript not detected.  It may not be installed or enabled properly.

and the following error message in the console:

>[IPKernelApp] WARNING | Widget Javascript not detected. It may not be installed or enabled properly.

I'm happy to try to solve this on my own but I wasn't able to find out enough about how jupyter loads extensions for each kernel from the documentation to figure out where to start.

(I asked the same question [here](https://ask.sagemath.org/question/41269/sagemath-and-interact-ipywidgets-with-jupyter/) a few days ago and there's a little bit more information there about how I set things up).

**Comment by jasongrout** [comment]
CC @jdemeyer

**Comment by jasongrout** [comment]
What version of ipywidgets and widgetsnbextension do you have installed? IIRC, Sage is still using an older version of ipywidgets that doesn't work with the current widgetsnbextension javascript.

**Comment by jdemeyer** [comment]
We should mention the obvious thing to do: **clearing browser cache**

Remember how I lost half a day at the widgets workshop because of this? It would be good to change that message to
```WARNING | Widget Javascript not detected. You may need to clear the cache of your web browser. It could also be that jupyter-js-widgets is not installed or enabled properly.```

**Comment by bryangingechen** [comment]
The versions of ipywidgets and widgetsnbextension I'm using are those that come with anaconda 5.1:

ipywidgets: 7.1.1
widgetsnbextension: 3.1.0

Clearing the cache didn't seem to change anything. Thanks for pointing out that the version of ipywidgets in Sage is different. I checked and it is using 6.0.0.

**Comment by jdemeyer** [comment]
How do nbextensions work? Are they attached to a specific Jupyter installation or to a specific kernel?

**Comment by jasongrout** [comment]
The error indicates that your python package ipywidgets in Sage is too old to interface with the widgetsnbextensions 3.1.0 package providing the javascript for the browser.

@jdemeyer, The nbextensions are for the notebook server, and can be installed at the user level, the environment level, or the system level. You can't install an nbextension for a single kernel.

**Comment by bryangingechen** [comment]
It looks like upgrading ipywidgets did the job! Thanks very much!

What follows are some details for anyone else who might have this question in the future:

When trying to upgrade ipywidgets in Sage using `sage -pip install --upgrade ipywidgets`, I found I had to install ssl in sage first, which I did following [the instructions in this thread](https://groups.google.com/forum/#!topic/sage-support/c2fm64j55Jk), namely, run
     sage -i openssl
     sage -f python2
     sage -i pyopenssl

After about 2 hours of rebuilding, this step was complete and the above pip command successfully upgraded ipywidgets and all of its dependencies for Sage.  I did some testing and now ipywidgets (and interact) elements work perfectly in my anaconda jupyter notebook.

**Comment by jdemeyer** [comment]
> You can't install an nbextension for a single kernel.

So in that case, there is really no bug. Sage 8.1 uses an older version of ipywidgets which is not compatible with the nbextension installed **outside** of Sage.

For the record: the next version of Sage will have ipywidgets 7.1.1
