### ISSUE TITLE
Code inside render function not executing

### ISSUE THREAD

**Issue by sreekanthreddy1991** [jupyter-widgets/ipywidgets#1990]
%%javascript

define('hello', ["@jupyter-widgets/base", "d3"], function(widgets, d3) {

    var HelloView = widgets.DOMWidgetView.extend({

        render: function() {
            alert("check");
            this.value_changed();
            this.model.on('change:value', this.value_changed, this);
        },

        value_changed: function() {
            alert("changed");
            this.el.textContent = this.model.get('value');
        },
    });

    return {
        HelloView : HelloView
    };
});

The alert inside render function is not being executed. My final goal would be to write code inside render to render charts using d3.js. I want to update the chart whenever there is a change in python data.

**Comment by Madhu94** [comment]
@sreekanthreddy1991 Can you also share the code of your backbone Model and python WidgetModel ?

**Comment by sreekanthreddy1991** [comment]
@Madhu94  Thank you for helping.
I have the following code for my python WidgetModel and I do not  have anything for backbone. I followed the example for creating the custom widget from http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Custom.html
It doesn't say anything about the backbone Model.

import ipywidgets as widgets
from traitlets import Unicode, validate

class HelloWidget(widgets.DOMWidget):
    _view_name = Unicode('HelloView').tag(sync=True)
    _view_module = Unicode('hello').tag(sync=True)
    _view_module_version = Unicode('0.1.0').tag(sync=True)
    value = Unicode('Hello world!').tag(sync=True)

**Comment by Madhu94** [comment]
@sreekanthreddy1991 I assume you have created an instance of the HelloWidget?

What version of notebook, ipywidgets are you using ?

**Comment by sreekanthreddy1991** [comment]
Yes I am creating the instance of the HelloWidget. 
ipywidgets-version 6.0.0
notebook-version 5.0.0

I have the following code to update the text content of the hello widget.

```
w = HelloWidget()
display(w)
names = ['Alexis Sanchez', 'Andres Iniesta', 'Angel Di Maria', 'Arjen Robben']
def update(name):
    w.value = name['new']
def createDropdown(names):
    mark_choose = widgets.Dropdown(options=names, description='Marks')
    mark_choose.observe(update, names='value')
    display(mark_choose)
createDropdown(names)
```
The content of the hello widget is changing whenever there is a change in the drop down. But I want to see the alert pop up when drop down value is changed.

**Comment by Madhu94** [comment]
You can add a ``console.log("check")`` and see if that works. If that works, then you could be using a browser extension to disable popups.

**Comment by sreekanthreddy1991** [comment]
Yes. I tried that already and its not working either.

**Comment by Madhu94** [comment]
Oh, I'm sorry not to be of more help, but your example works fine for me (if I remove the d3 part).

**Comment by sreekanthreddy1991** [comment]
Thank you. Console log is working for you ?

**Comment by Madhu94** [comment]
Yes. alerts work as well.

**Comment by sreekanthreddy1991** [comment]
Thank you. I guess I am missing something here. Its working for me as well if I refresh the page. Before I used to re-run the cells after editing the code and it wasn't working. Once I refresh the page, console works.

**Comment by Madhu94** [comment]
(Pure guesswork) If you haven't done ``require.undef('hello')``, you could have been picking up old code.

**Comment by sreekanthreddy1991** [comment]
Ohh yeah, that might be the case. Thank you for the help.
