### ISSUE TITLE
display = none for layout for one widget makes all widgets hidden

### ISSUE THREAD

**Issue by sindzicat** [jupyter-widgets/ipywidgets#1991]
Hello.

Small work example:

```
import ipywidgets as ipw
from IPython.display import display

st = {'description_width': '250px'}
lt = ipw.Layout(width = '600px')

D = ipw.Dropdown(
    options = ['a', 'b', 'c', 'd', 'e'],
    value = 'a',
    description = "Some parameter a:",
    disabled = False,
    style = st,
    layout = lt
)

TB = ipw.IntText(
    value = 5,
    min = 1,
    max = 10,
    description = "Other parameter b:",
    disabled = False,
    style = st,
    layout = lt
)

#TB.layout.display = 'none'
display(D, TB)
```

When `TB.layout.display = 'none'` is commented, all widgets are visible. When I uncomment this line, I don't see any widgets. I use chrome devtools and see that all widgets begin `display='none'`, although I wanted to make only one widget hidden.

Is this a bug? If no, what I do wrong? Please, help.

Best regards,
Andrey.

**Comment by sindzicat** [comment]
If I replace
```
TB.layout.display = 'none'
```
with
```
TB.layout = ipw.Layout(width='600px', display='none')
```
That all works fine. I mean that only `TB` widget begin to be hidden, as I want. But why 1st variant of code don't work for me?

**Comment by sindzicat** [comment]
The following works too:
```
L = TB.layout
L.display = 'none'
TB.layout = L
display(D, TB)
```
But I still have no idea to explay, why `TB.layout.display = 'none'` doesn't work as expeted.

**Comment by sindzicat** [comment]
I understood.
`D.layout is TB.layout` gives `True`. This is the same object, not copy.
But I have no idea now to make copy.
Using `copy` didn't help me, `deepcopy` isn't possible to use in my case.
Any ideas?

**Comment by sindzicat** [comment]
Solved:

```
st = {'description_width': '250px'}
lt = {'width': '600px'}   # <===

D = ipw.Dropdown(
    options = ['a', 'b', 'c', 'd', 'e'],
    value = 'a',
    description = "Some parameter a:",
    disabled = False,
    style = st,
    layout = ipw.Layout(**lt)   # <===
)

TB = ipw.IntText(
    value = 5,
    min = 1,
    max = 10,
    description = "Other parameter b:",
    disabled = False,
    style = st,
    layout = ipw.Layout(**lt)   # <===
)
```

This creates copies of Layouts, so `TB.layout.display = 'none'` will works now.

Closed.

**Comment by SylvainCorlay** [comment]
That is it. You figured it out. This feature is meant to allow multiple widgets to have the same layout attributes.
