### ISSUE TITLE
Selectmultiple display issue on Microsoft Edge

### ISSUE THREAD

**Issue by BarbaraPr** [jupyter-widgets/ipywidgets#1996]
Hi all, 

I have an issue with using the Selectmultiple ipywidget on Microsoft Edge. When I select items of the Selectmultiple widget I can't see the selection, altough it is selected. Unfortunately I couldn't find any solutions on the internet so far. Has anyone the same issue?

Details:
Microsoft Edge 41.16299.248.0
Microsoft EdgeHTML 16.16299
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) 
Jupyter  4.4.1
ipywidget 7.0.5

**Comment by jasongrout** [comment]
Can you post a screenshot?

**Comment by BarbaraPr** [comment]
![ezgif-3-d11f0b72a0](https://user-images.githubusercontent.com/26026619/37349506-df67f23e-26d6-11e8-89ec-b9154ae30264.gif)

I hope this helps

**Comment by jasongrout** [comment]
Thanks. I can confirm the issue with the following example:

```python
from ipywidgets import *
SelectMultiple(options=['option 1', 'option 2', 'option 3'])
```

For me, there seems to be a very slight difference in font weight or boldness for selected items, but like you I'm not seeing the background of the selected options change.

**Comment by jasongrout** [comment]
I'm also seeing this for a plain Select:

```python
from ipywidgets import *
Select(options=['a','b','c'])
```
