### ISSUE TITLE
IntText Displays Invalid Values

### ISSUE THREAD

**Issue by mlucool** [jupyter-widgets/ipywidgets#1999]
If I enter a decimal value into an InText, it will show me exactly what I typed in, but the value will be cast when I go to retrieve it. Instead, it should block typing in a '.' or verify the number and change it to the cast value when on unfocus.

![image](https://user-images.githubusercontent.com/1813603/37597700-85450f56-2b56-11e8-996a-8d8f8b9b0c21.png)

Widget Version: 7.0.3

**Comment by jasongrout** [comment]
That makes sense to me. Tagging as a "good first issue" - the fix likely involves listening to the keydown events in the textbox and resetting the text if the value doesn't parse as an integer (maybe except for plus/minus signs?)

**Comment by realslimshanky** [comment]
@jasongrout I worked on fixing this issue as part of #PyConIndia2018, thank @Madhu94 for mentoring me along the way. Raising a PR soon.
