### ISSUE TITLE
How to discriminate between user click and code change events

### ISSUE THREAD

**Issue by fran-pena** [jupyter-widgets/ipywidgets#2015]
When if I have a Select widget:
```
search   = widget.Select(...)
search.observe(foo, names='value')
```
then either an user click or a code change like 
 ```
search.options = [...]
```
produces an event. How I can discriminate these two cases in foo?

**Comment by jasongrout** [comment]
You can't discriminate between those currently.

**Comment by jasongrout** [comment]
Sorry, wait - you're resetting the options list programmatically, vs clicking to select a value? You could listen for an `options` change explicitly to distinguish between a value change and an options change.

**Comment by jasongrout** [comment]
Or perhaps you could store the last options list seen, and in foo compare to see if the options list was changed, or if the options list is the same. That's not foolproof, since the options list may change without changing the value, and then later the user selects a value.

**Comment by fran-pena** [comment]
Thanks @jasongrout. I made a global variable that marks when a change in _search_ is made by code. In those cases, I do not execute regular code in _foo_.
