### ISSUE TITLE
Remove large left margin in output widget in docs

### ISSUE THREAD

**Issue by pbugnion** [jupyter-widgets/ipywidgets#2025]
In the ['latest' docs](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#Output), the output widget has an ugly left margin. This seems to be due to a non-zero flex-basis in the prompt area of the output area used for the output widget.

<img width="1109" alt="screen shot 2018-03-28 at 15 13 22" src="https://user-images.githubusercontent.com/1392879/38034633-9ef22e20-329a-11e8-851a-d694da3c101c.png">

Happy to tackle this in the coming days, unless someone gets to it first.

**Comment by jasongrout** [comment]
See #2028 for a possible fix.

**Comment by jasongrout** [comment]
In the future, we should use the simplified output area (https://github.com/jupyter-widgets/ipywidgets/issues/2027).
