### ISSUE TITLE
Update contributor names

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#2032]
We typically include contributors real names in our release notes. Several recent contributors do not have their names in their commits or in the mailmap file.

@DougRzz, @Madhu94 - would you like your real names in our release notes? If so, can you comment below with your real name and I'll add it to the mailmap file?

@jzf2101 - you are listed as `J Forde` - is that what you want to be listed as? (you aren't in the release notes for 7.2, but I noticed this when looking back in older listings, so just wanted to confirm.)

For the future, if you'd like, you can include your real name in your commits by setting your name in the git config--see https://help.github.com/articles/setting-your-username-in-git/ for more details.

**Comment by DougRzz** [comment]
Hi Jason, my name is Doug Redden. I only did a minor documentation change but I'm glad to take some credit for v7.2 :)

**Comment by jzf2101** [comment]
J Forde is fine with me

**Comment by Madhu94** [comment]
Madhumitha Natarajan is the full name. The contribution isn't much, but
thanks for adding me to the contributors' list !
