### ISSUE TITLE
Widget Javascript not detected in jupyterlab

### ISSUE THREAD

**Issue by StephaneKazmierczak** [jupyter-widgets/ipywidgets#2036]
Hi 
I am getting the following error while trying to run: 

import ipwidgets as widgets
widgets.IntSlider()

Widget Javascript not detected.  It may not be installed or enabled properly.

I already try to update ipwidgets with pip 
reinstall jupyterlab-manager 
what should I check next ? 

jupyterlab 0.31.12
nodejs 9.10

**Comment by jasongrout** [comment]
You will need ipywidgets 7.0 or greater. It looks like you have ipywidgets 6 installed.

Also, if upgrading to ipywidgets 7 doesn't fix it, can you give us the output of `jupyter labextension list`

**Comment by StephaneKazmierczak** [comment]
Thank you very much for the help and your time! I had 7+ on python3 but my python 2.7 was using version 6, after upgrade to the last version it is now working, thanks !

**Comment by jasongrout** [comment]
Great! Enjoy!
