### ISSUE TITLE
ipywidgets 7.1.2 not compatible with new widgetsnbextension

### ISSUE THREAD

**Issue by pleabargain** [jupyter-widgets/ipywidgets#2049]
error:
ipywidgets 7.1.2 has requirement widgetsnbextension~=3.1.0, but you'll have widgetsnbextension 3.2.1 which is incompatible.

 python3.5 --version
Python 3.5.2

Is this the right place to post this error?

**Comment by jasongrout** [comment]
Thanks. It looks like our conda-forge recipe had the wrong widgetsnbextension requirement. I'll issue new conda-forge builds for 7.0, 7.1, and 7.2 with better widgetsnbextension requirements.

For now, you can explicitly install widgetsnbextension 3.1. Thanks!

**Comment by jasongrout** [comment]
I've opened up https://github.com/conda-forge/ipywidgets-feedstock/issues/37 to address this. Thanks for pointing it out!
