### ISSUE TITLE
pip3 install requires  older widgetsnbextension

### ISSUE THREAD

**Issue by pleabargain** [jupyter-widgets/ipywidgets#2054]
ipywidgets 7.1.2 has requirement widgetsnbextension~=3.1.0, but you'll have widgetsnbextension 3.2.1 which is incompatible.

**Comment by pleabargain** [comment]
command
`pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install --user -U`

**Comment by jasongrout** [comment]
To me, it looks like it is a problem with the command pipeline you are using. You're cutting off the version number with `cut`, then upgrading to the latest version with `xargs pip -U`. `pip` doesn't force you to have a consistent environment - you need to install a compatible version manually, or use a package manager like conda that tries to keep the environment consistent for you.

**Comment by jasongrout** [comment]
The only thing I guess I'm confused about here is that your upgrade on all pip packages didn't seem to upgrade ipywidgets, if you're still on ipywidgets 7.1.2. I would look at your logs to see what happened to the ipywidgets upgrade.

Closing as resolved, but go ahead and post further questions here if you'd like help debugging your install.

**Comment by pleabargain** [comment]
I used 
pip3 install --user --upgrade ipywidgets

and it seems to have fixed the issue
ipywidgets                        7.2.1  

thank you.

this issue is closed.
