### ISSUE TITLE
Error in the layout object documentation ?

### ISSUE THREAD

**Issue by AntoineGrapperon** [jupyter-widgets/ipywidgets#2059]
Hi, In the user guide, under [Layout and Styling of Jupyter Widgets](http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Styling.html):

It is reported that the  `layout` object has a `visibility` attribute. It seems to be `visible` instead.
(using `ipywidget`, version 7.0.5)

**Comment by AntoineGrapperon** [comment]
Nope, that is not a bug... I had trouble understanding the doc but the error message helped me: to change the visibility of a widget, one should do:

```python
my_widget.layout.visibility = 'hidden' # or 'visible'
```

**Comment by jasongrout** [comment]
Please feel free to submit a PR to the docs to make them clearer.
