### ISSUE TITLE
button font color different in classic notebook and jupyterlab

### ISSUE THREAD

**Issue by oscar6echo** [jupyter-widgets/ipywidgets#2062]
For button with styles primay, success, info, warning, danger, the text appears **black** in jupyterlab and **white** in the classic notebook, as in the [doc](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Styling.html#Predefined-styles) so presumably the intended color, and clearly the best option if you ask me.

Unfortunately the color attribute is not accessible, only the 'button_color' (background-color) says the doc.  So it would be good to add color to the button style keys.

That would more than solve the slight inconsistency between JupyterLab and the classic notebook.
What do you think ?

**Comment by jeffyjefflabs** [comment]
I noticed this too and found this issue.  There's a mismatch in CSS variable names between ipywidgets and Jupyter Lab.  I put in a ticket on the Lab side (https://github.com/jupyterlab/jupyterlab/issues/7861) but I'm not sure where it should be fixed.
