### ISSUE TITLE
Widget not displaying in Jupyter Lab (not Anaconda)

### ISSUE THREAD

**Issue by fitoprincipe** [jupyter-widgets/ipywidgets#2065]
I am on Linux Mint 18 (MATE 64bits). I have installed Jupyter Lab and Jupyter Notebook independently, NOT using Anaconda, and ipywidgets does not work in the Lab, but it does work fine in the Notebook.

![pantallazo-2018-05-04 13-45-37](https://user-images.githubusercontent.com/10751505/39640555-b69c659e-4fa1-11e8-81c3-3e822cf069fb.png)

**Comment by jasongrout** [comment]
Did you install the Lab widgets extension? http://ipywidgets.readthedocs.io/en/latest/user_install.html#installing-the-jupyterlab-extension

**Comment by fitoprincipe** [comment]
Yes, I have. I just checked (just in case). But the 'error' persists.

**Comment by fitoprincipe** [comment]
Solved @jasongrout. I had an issue with Nodejs I didn't see. Updating Nodejs and reinstalling lab widgets extension solved my problem. Thank you for your time.

**Comment by jasongrout** [comment]
Great!

**Comment by ahicks88** [comment]
pip install --upgrade Nodejs

**Comment by jasongrout** [comment]
If you are using conda, you can upgrade it using conda: `conda update nodejs` or something. pip doesn't have nodejs - if you are using pip, you'll need to upgrade it using whatever packaging system you used to install it, or download it fresh from the nodejs site.

**Comment by vidartf** [comment]
Note: The `nodejs` package will not install node for you (it seems to be a package that makes it easier to call out to / use node from Python, but it assumes you have installed node already).
