### ISSUE TITLE
Widgets error on first start

### ISSUE THREAD

**Issue by NM4455** [jupyter-widgets/ipywidgets#2066]
Hi,

There is an error displayed with Jupyter widgets on the first start of the notebook:

> Failed to display Jupyter Widget of type HBox.
> 
> If you're reading this message in the Jupyter Notebook or JupyterLab Notebook, it may mean that the widgets JavaScript is still loading. If this message persists, it likely means that the widgets JavaScript library is either not installed or not enabled. See the Jupyter Widgets Documentation for setup instructions. 
 
But if we run again all the cells or if I restart the kernel, it works very well.

How can I solve this issue please?

I'd like to load the notebook and execute the widgets correctly on the first run.

The aim is to have a notebook running well from the beginning, i.e. I'd like unexperimented people to just click on the notebook link and see the results directly.

Many thanks in advance,

Nicolas

**Comment by vidartf** [comment]
Have you saved the widget state with the notebook? The widget state is not saved by default, so you have to manually manage this. This should be available from the "Widgets" menu in the classic notebook (currently not available from lab). See also issues like #1970.

**Comment by NM4455** [comment]
Thanks for your suggestions Vidarf.

Unfortunatelly, I have the same result even with the save state option.

It seems that it is due to the opening notebook function. Any other solution to keep the results saved?

Otherwise, is there a way to automatically run all cells as soon as the notebook is opened?

**Comment by vidartf** [comment]
Which versions of ipywidgets are you using? I would recommend ensuring you have the latest version of both the python package and notebook extension. Also, check if the notebook is trusted upon load, and if it is not, see if trusting it changes anything.

**Comment by vidartf** [comment]
Also, check the browser console and server log for any error messages or warnings.

**Comment by vidartf** [comment]
Closing due to lack of feedback.
