### ISSUE TITLE
Interact shows sliders, but they do not work

### ISSUE THREAD

**Issue by brunoalvarez89** [jupyter-widgets/ipywidgets#2069]
Hi,

I created [this notebook ](https://github.com/brunoalvarez89/PrestamoBanco/blob/master/prestamo_banco.ipynb) to calculate loan payments. 

In  `In [1]`,  I have a function called `mostrar_evolucion_credito` that shows the loan evolution over time, with three input parameters. Such function is called inside `interact` in `In [2]`.

When I see the notebook in nbviewer, the interact sliders appear, but when I move them, `Out [2]` does not change. When playing with the notebook locally, the sliders change  `Out [2]`.

Also, I'm having this same issue even in the [interact documentation page](http://ipywidgets.readthedocs.io/en/latest/examples/Using%20Interact.html) (for `In [3]`, i don't see changes when moving the slider for the function f(x)).

Thanks in advance.

Bruno.

**Comment by brunoalvarez89** [comment]
Hi,

I still can't see the interact characteristic working, even in the documentation page. Is this expected behaviour, or am I asking the wrong question?

Thanks.

**Comment by jasongrout** [comment]
Since there is no python kernel doing the calculations, you won't see the effect of the slider. In order to see the effect of the sliders, you'll need to open the notebook in Jupyter Notebook or JupyterLab, where the is a python kernel to do the calculation.

**Comment by brunoalvarez89** [comment]
Ahh ok, thanks for the clarification. 

I thought interact was intended also for static representations of the notebook.

Best.

**Comment by jasongrout** [comment]
No problem. You still need a python kernel to do any actual calculations.
