### ISSUE TITLE
jupyterlab-manager installation removes ability for interactive altiar plots in jupyterlab

### ISSUE THREAD

**Issue by afonit** [jupyter-widgets/ipywidgets#2071]
I was not sure if I should report this against jupyterlab, altair, or jupyterlab-manger - if this is not the right place please let me know but I thought it might be a good place to start since after installation of jupyerlab-manager the interactivity ceases.

I was installing some extensions to do a demo and I noticed that interactivity of the altair plots in jupyterlab stopped working, after much testing this is the simplest reproducible path I came up with:

Step 1:
conda create -n testing anaconda
Step 2:
conda install -c conda-forge jupyterlab altair vega_datasets

Plots work. `Interactivity works`.

Step 3:
jupyter labextension install @jupyter-widgets/jupyterlab-manager

Plots work. `Interactivity does not work`.

Step 4:
jupyter labextension uninstall @jupyter-widgets/jupyterlab-manager

Plots work. `Interactivity does not work`.

The data for the chart to verify that interactivity is working/not working is here:
(Note: Paste the below python code into a cell in jupyterlab and execute it - for interactivity click the bars at the bottom)
```python
"""
Interactive Chart with Cross-Highlight
======================================
This example shows an interactive chart where selections in one portion of
the chart affect what is shown in other panels. Click on the bar chart to
see a detail of the distribution in the upper panel.
"""
# category: interactive charts
import altair as alt
from vega_datasets import data

pts = alt.selection(type="single", encodings=['x'])

rect = alt.Chart(data.movies.url).mark_rect().encode(
    alt.X('IMDB_Rating:Q', bin=True),
    alt.Y('Rotten_Tomatoes_Rating:Q', bin=True),
    alt.Color('count()',
        scale=alt.Scale(scheme='greenblue'),
        legend=alt.Legend(title='Total Records')
    )
)

circ = rect.mark_point().encode(
    alt.ColorValue('grey'),
    alt.Size('count()',
        legend=alt.Legend(title='Records in Selection')
    )
).transform_filter(
    pts.ref()
)

bar = alt.Chart(data.movies.url).mark_bar().encode(
    x='Major_Genre:N',
    y='count()',
    color=alt.condition(pts, alt.ColorValue("steelblue"), alt.ColorValue("grey"))
).properties(
    selection=pts,
    width=550,
    height=200
)

alt.vconcat(
    rect + circ,
    bar
).resolve_legend(
    color="independent",
    size="independent"
)
```
The source of the python code is from here: https://github.com/altair-viz/altair/blob/master/altair/vegalite/v2/examples/interactive_cross_highlight.py

**Comment by jasongrout** [comment]
Do you see any javascript errors in the above cases?

**Comment by afonit** [comment]
looks like this is just on windows.  I tried this on fedora28 and everything worked fine.  This seems to be related to windows 7.  I tried a fresh uninstall/reinstall (not just new environments) and the problem persists.  I will continue to toy with this and see what I can find.

**Comment by vidartf** [comment]
I can not reproduce the error on Windows 10 following your steps. This might be a yarn/node issue. Possibly relevant questions:
- What version of Node are you using (`node --version`)?
- After uninstalling lab manager, is there anything left in the "extensions" folder inn the app dir? To see what the app dir is, run `jupyter lab --help`, and see the default value for the `--app-dir` option.
- After uninstalling lab manager, what happens if you clear out the staging directory (subfolder "staging" in appdir) and then rebuild?
- If you add the `--debug` flag to the `jupyter labextension ...` commands, are there anything interesting in the output?

**Comment by afonit** [comment]
@vidartf , thanks for trying this out on windows.

* What version of Node are you using (node --version)?
    * v8.9.3
* After uninstalling lab manager, is there anything left in the "extensions" folder inn the app dir? To see what the app dir is, run jupyter lab --help, and see the default value for the --app-dir option.
    * that only showed `--app-dir=~/myjupyterlabapp`.  I went there, there is not a folder by that name.  I searched the whole hard drive and there are no results of a folder by that name.
    * I ran `jupyter lab paths` and it gave me some paths for three directories Application, User Settings and Workspaces.  Given what you have said above I think the Application folder would be the one in question as it has the extension *.tgz's in it. 
* After uninstalling lab manager, what happens if you clear out the staging directory (subfolder "staging" in appdir) and then rebuild?
    * after uninstalling the extension manager and clearing out the staging folder, I then did:
    * jupyter labextension install @jupyter-widgets/jupyterlab-manager
* If you add the --debug flag to the jupyter labextension ... commands, are there anything interesting in the output?
    * I did not do this as the above step of taking out staging and reinstalling the extension manager worked.

I did note that if I do:
```
jupyter lab --core-mode   # start JupyterLab in core mode, with no extensions
```
Then the interactivity comes back.


Thanks again @vidartf going through those steps got me up and running.

**Comment by vidartf** [comment]
Well, we found a workaround, but I'm not sure if I would say that the problem is fixed. I would still like to know if this is something that is wrong with jupyterlab code, or if this is an underlying issue with node/yarn.

> that only showed `--app-dir=~/myjupyterlabapp`.

That does not seem like a path you would see on Windows?

**Comment by vidartf** [comment]
`--app-dir=~/myjupyterlabapp` is from the example usage:

```
--app-dir=<Unicode> (LabApp.app_dir)
    Default: '<path to e.g. conda>\\share\\jupyter\\lab'     <---------- This is what I was thinking of
    The app directory to launch JupyterLab from.

To see all available configurables, use `--help-all`

Examples
--------

    jupyter lab                       # start JupyterLab
    jupyter lab --dev-mode            # start JupyterLab in development mode, with no extensions
    jupyter lab --core-mode           # start JupyterLab in core mode, with no extensions
    jupyter lab --app-dir=~/myjupyterlabapp # start JupyterLab with a particular set of extensions
    jupyter lab --certfile=mycert.pem # use SSL/TLS certificate
```

**Comment by afonit** [comment]
@vidartf 
I am wondering if this issue was specific to the version I was using at the time?
I am not sure what jupyterlab version was released when I had posted this originally, unfortunately I did not post the version in my original report.

Currently I show:
jupyterlab                0.32.1                   py36_0    conda-forge

After I did what you said, I thought, let me try this in new environments just as I posted above and I now cannot reproduce the error I was getting.

Which is odd because I was able to reproduce this with many new clean environments and even uninstalled anaconda and reinstalled into new directories.

I have got to thing the only thing that changed was some new version being released between now and then in either jupyterlab/nodejs or for the extension manager?

**Comment by vidartf** [comment]
@afonit It's hard to keep track of all the moving pieces, so if it is fixed in the current latest releases, I think we can leave this for now. If you or anybody else are able to reproduce this issue at a later state, feel free to comment again. Maybe with a conda environment specification for reproduction since this seems to be quite elusive.

**Comment by oxanderv** [comment]
I had this error (Javascript Error: Can not find a selection named "selector008"), when trying to concatenate two graphs, it seems to be generated if one of them is not interactive, so to solve it I eliminated the next part of the code (
.transform_filter (
     brush.ref () # the filter transform uses the selection
                 # to filter the input data to this chart
)
).
At the end you can see the two graphics without the option of the interactive, I think there are some graphics that ALTAIR has not given a feature to be interactive.

**Comment by jakevdp** [comment]
@oxanderv I would ask about this on the Altair mailing list or on StackOverflow... I don't think the error you're seeing is related to jupyter widgets.
