### ISSUE TITLE
widgets.HTML events

### ISSUE THREAD

**Issue by MichaelHalfon** [jupyter-widgets/ipywidgets#2080]
Hi,

I'm playing a little bit with the ipywidgets' features, and I was wondering if there's actually a way to add events on the HTML widget ?

My problem is the following: I'd like to create checkboxes that are actually a little bit customizable. Nonetheless, I noticed that this isn't quite possible with the widgets.Checkbox() for now. 

I used then the widgets.HTML() feature, with some css and HTML I managed to get a checkbox with some customized style. But obviously, the value of the widget being hardcoded HTML and CSS, when I try to do `my_html.observe(func, names="value")` it doesn't work.

Is there another way to implement such feature ?
I'm on JupyterLab by the way.

Thank you very much, this question aside I'm really enjoying the ipywidgets' features so far !

Michael

**Comment by MichaelHalfon** [comment]
Thank you for your anwer !

I guess it would be enough! Is there a documentation about adding css to an already existent widget ? I didn't find anything about it on readthedocs.

**Comment by jasongrout** [comment]
```python
from ipywidgets import *

w = IntSlider()
w.add_class('my-class')
w
```
this puts the `my-class` class on the top-level DOM. Then you put css on the page to style things scoped to `.my-class`

**Comment by jasongrout** [comment]
We could use some docs showing a good example in this doc: http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Styling.html#

**Comment by jasongrout** [comment]
once the class is added, you could put css on the page in a number of ways. For example, just using a plain ipython display html call.

**Comment by MichaelHalfon** [comment]
Thank you very much, you've been really helpful !
I'll look into that !

**Comment by MichaelHalfon** [comment]
mmmh.. this code doesn't seem to work:

`
var = widgets.Checkbox(value=False, description='One')

var.add_class('custom_class')
`

`
%%html
<style>
.custom_class {
    font-size: 22px;
    color: red;
}
</style>
`

I may have an idea why, but I'm not sure: Should I use a custom label for the text, the css properties for the checkbox being helpful only for the actual square and not the description ?

**Comment by jasongrout** [comment]
You would customize things by using CSS selectors, something like:

```
.custom_class .widget-label-basic {
    font-size: 22px;
    color: red;
    width: 50px;
}
```
However, it comes with the caveat that the DOM structure of the checkbox is an implementation detail, not a supported interface, so styling things based on this DOM structure is brittle and could break even in a patch release of ipywidgets.

**Comment by martinRenou** [comment]
Another solution might be to use @mwcraig 's [ipyevents](https://github.com/mwcraig/ipyevents) which allows you to listen to lots of events on a specific widget. I am not sure about the granularity of it though (e.g. if you can listen to events on a specific part of your HTML).

I suppose it is safe to close this issue now. But feel free to reopen it if needed.
