### ISSUE TITLE
Reliably disable keyboard events

### ISSUE THREAD

**Issue by willcrichton** [jupyter-widgets/ipywidgets#2082]
I have an interactive ipywidget for which I would like to use keyboard shortcuts. Although it's not ideal, I'd like to have essentially two modes, either "in-my-widget" mode or "not-in-my-widget" (i.e. in Jupyter) mode. For now, let's say my ipywidget has a button that toggles between the two modes.

The Jupyter KeyboardManager has a [disable](https://github.com/jupyter/notebook/blob/ca50f1af5afb525fd95b98b2e61e69db28094467/notebook/static/notebook/js/keyboardmanager.js#L234) method that could theoretically be used for this purpose, but the issue is that this is a global, forgetful (i.e. not stack-ful) bit of state. Specifically, in ipywidgets, the widget area is registered with the keyboard manager via [register_events](https://github.com/jupyter-widgets/ipywidgets/blob/4aceb8670a64aff89c528d5d00205f1428c68d16/widgetsnbextension/src/extension.js#L144), which means that every time the widget area is focused or blurred, any other attempts to change the KeyboardManager settings [are erased](https://github.com/jupyter/notebook/blob/ca50f1af5afb525fd95b98b2e61e69db28094467/notebook/static/notebook/js/keyboardmanager.js#L241-L246). This produces a poor interaction paradigm where if a user accidentally clicks outside the widget area (or generally does any blurring action, which in practice seems to happen more frequently than I expect), then the keyboard shortcuts reactivate.

Is there some way I can more reliably disable the Jupyter keyboard events to preclude this issue?

**Comment by jasongrout** [comment]
I don't know of a way to handle the keyboard events better off the top of my head, and still play nicely with user expectations about working in the rest of notebook. It sounds like it is an issue that needs to be solved at the notebook level?

**Comment by willcrichton** [comment]
Is there a reason that `register_events` needs to be called on the widget container, instead of letting widgets individually call register events on the elements that need it?

**Comment by jasongrout** [comment]
First thought is that widgets themselves typically don't know if they are running in the notebook, or JupyterLab, or on a web page. That's why it's useful to do it at the widget manager level, which *does* know what environment widgets are running in.

**Comment by willcrichton** [comment]
Ok, fair enough. I'll raise an issue on the notebook repo.
