### ISSUE TITLE
Widgets dont display in jupyter lab 

### ISSUE THREAD

**Issue by ronyarmon** [jupyter-widgets/ipywidgets#2083]
Perhaps reopening [#1981](https://github.com/jupyter-widgets/ipywidgets/issues/1981) but couldn't open widgets in jupyterlab after using your example:

import ipywidgets as widgets
out=widgets.Dropdown(
options=['1', '2', '3'],
value='2',
description='Number:',
disabled=False,
)
display (out)

The output is the object rather than widget:
Dropdown(description='Number:', index=1, options=('1', '2', '3'), value='2')

The same result running in a console (Spyder) though it worked fine in a jupyter notebook. 
I tried with: from IPython.display import display but got the same result. 

Seems like some issue with Java Script on my lab but Plotly works well.
Any other ideas I should try?

**Comment by jasongrout** [comment]
> The same result running in a console (Spyder)

Spyder doesn't support ipywidgets, IIRC.

It seems that the jupyter widgets lab extension is not installed or not working. What does `jupyter labextension list` print?

**Comment by ronyarmon** [comment]
JupyterLab v0.32.1
No installed extensions

**Comment by jasongrout** [comment]
You'll need to install the ipywidgets jupyterlab extension, then: http://ipywidgets.readthedocs.io/en/latest/user_install.html#installing-the-jupyterlab-extension

**Comment by ronyarmon** [comment]
Got stuck in resolving pacakges with this file: 
@jupyter-widgets/jupyterlab-manager@file:../extensions/jupyter-widgets-jupyterlab-manager-0.35.0.tgz

I installed nodejs and ran jupyter lab clean

**Comment by jasongrout** [comment]
> I installed nodejs and ran jupyter lab clean

So does it work now after you did that?

**Comment by vidartf** [comment]
There is an issue of lab build hanging with node 10, maybe this is what you are experiencing?

**Comment by ronyarmon** [comment]
And how can I check if this is the issue?

**Comment by vidartf** [comment]
```
node --version
```

If it is 10, try to install v8 and see if that fixes it (you'll have to google that one, since the best way to do it depends on your local setup).

**Comment by jasongrout** [comment]
See the jlab issue for supporting node 10: https://github.com/jupyterlab/jupyterlab/issues/4585

**Comment by ronyarmon** [comment]
I installed yarn 1.7.0 but widgets still not appearing.

**Comment by jasongrout** [comment]
JLab distributes it's own version of yarn, which it uses exclusively, so
installing a newer version won't help. There is a pr to upgrade jlab's yarn.

**Comment by adhg** [comment]
Install nodeJS (yep, the docs explicitly mentioned that). So for me what worked was:
1. Install nodeJS (https://nodejs.org/en/) 
2. pip install ipywidgets
3. jupyter nbextension enable --py widgetsnbextension
4. jupyter labextension install @jupyter-widgets/jupyterlab-manager
5 (may need to restart your lab)

**Comment by vidartf** [comment]
PS: The latest lab supports node 10 now 👍
