### ISSUE TITLE
button.on_click with parameters

### ISSUE THREAD

**Issue by monchin** [jupyter-widgets/ipywidgets#2103]
In the example of "Widgets Events" of the ipywidgets doc, I knew that button.on_click can call a function without parameters. But suppose that I define a str variable a, and a function
`def fun(a):
    print(a)`
I would like to call this 'fun' function when I click the button, but I don't know how to give the parameter a to the function fun. Thank you for your kind help!

**Comment by jtpio** [comment]
How about calling the `fun` function in the `on_button_clicked`?

```python
import ipywidgets as widgets
from IPython.display import display
button = widgets.Button(description="Click Me!")
display(button)

def fun(a):
    print(a)

def on_button_clicked(b):
    fun('a')

button.on_click(on_button_clicked)
```

**Comment by monchin** [comment]
@jtpio Thank you very much! It worked for me!

**Comment by jtpio** [comment]
Glad it worked!

**Comment by Erikzzz** [comment]
How do I make this work when the argument is an object created outside the function(s)? thanks

**Comment by jasongrout** [comment]
I would use functools.partial for something like that

**Comment by rishabhmulani** [comment]
I'm not sure how to use that, but I built another function that would initialize the "random_string" variable in my ".py" package, and then used this already initialized "random_string" in the callback function (event handler function)

**Comment by zmk5** [comment]
@rishabhmulani It would be something like this:

```python
import functools

def on_button_clicked(b, rs_="some_default_string"):
    fun(random_string)

button.on_clicked(functools.partial(on_button_clicked, rs_="abcdefg"))
```
