### ISSUE TITLE
Invalid link in the documentation

### ISSUE THREAD

**Issue by nathaneastwood** [jupyter-widgets/ipywidgets#2106]
Just a quick note to say that the link for the [output widget examples](https://ipywidgets.readthedocs.io/examples/Output%20Widget.html) found on [this page](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#Output) is invalid. I quite like to use [html-proofer](https://github.com/gjtorikian/html-proofer) in combination with my CI to check for broken links :)

**Comment by SylvainCorlay** [comment]
Thanks @nathaneastwood ! Good catch.

Feel free to open a PR to fix the broken link.

**Comment by jtpio** [comment]
Fixed in #2108 with a few other typos.
