### ISSUE TITLE
[DOC] Update Widget Asynchronous.ipynb

### ISSUE THREAD

**Issue by rs2** [jupyter-widgets/ipywidgets#2112]
Update [comment](https://github.com/jupyter-widgets/ipywidgets/blob/f51a7badd28fd8510b0e74b4858e840b2ca3a87c/docs/source/examples/Widget%20Asynchronous.ipynb?short_path=c567e87#L41) in Widget Asynchronous.ipynb as https://github.com/ipython/ipykernel/pull/246 has been merged and released in 4.7.
Please assign to me.

**Comment by SylvainCorlay** [comment]
😄

**Comment by jasongrout** [comment]
@rs2 - it looks like we needed this fix for #2115, and our next release. Does #2134 look good to you?

**Comment by rs2** [comment]
:'(

**Comment by jasongrout** [comment]
Don't worry, there are definitely many other places where the docs and other things can be improved! We definitely welcome your contributions!
