### ISSUE TITLE
Identify which widget is being observed

### ISSUE THREAD

**Issue by fran-pena** [jupyter-widgets/ipywidgets#2118]
I need to create a variable number of widgets and then identify which widget is being observed when the user interacts with one of them. In the following example, *n* `IntSliders` are being created:
```
import ipywidgets as wg
def obs(change):
    print(change)
def fun(n):
    l  = []
    for i in range(n):
        l.append(wg.IntSlider())
        l[i].observe(obs, names='value')
    display(wg.VBox(l))
fun(4)
```
When interacting with one of the sliders, the `change` variable only gives the values for *owner*, *old*, *new*, *type* and *name*.
 ```
{'owner': IntSlider(value=1), 'new': 1, 'old': 0, 'type': 'change', 'name': 'value'}
```
**Is there any way to "tweak" the content of change to include its position in the list *l*?**

**Note:** I cannot use existing `IntSlider` attributes like *description* because then it will be reflected in the widget appearance.

**Comment by jasongrout** [comment]
That's why we give the owner - you can search the list for that widget to find its index. Something like `myindex = l.index(owner)`.

**Comment by jasongrout** [comment]
(in order to do that, you'd need the list to live in the global namespace):

```
import ipywidgets as wg
widget_list = []
def obs(change):
    index = widget_list.find(change.owner)
    print(change)
def fun(n):
    global widget_list
    for i in range(n):
        slider = wg.IntSlider()
        widget_list.append(slider)
        slider.observe(obs, names='value')
    display(wg.VBox(l))
fun(4)
```
or something like that (I didn't test the above code...)

**Comment by fran-pena** [comment]
Thank you. For future readers, I leave here a correction of your code:
```
import ipywidgets as wg
widget_list = []
def obs(change):
    index = widget_list.index(change.owner)
    print(index, change)
def fun(n):
    global widget_list
    for i in range(n):
        slider = wg.IntSlider()
        widget_list.append(slider)
        slider.observe(obs, names='value')
    display(wg.VBox(widget_list))
fun(4)
```
When, for example, the first slice is clicked, the index (0) and the variable *change* are printed:
```
0 {'new': 4, 'name': 'value', 'old': 0, 'type': 'change', 'owner': IntSlider(value=4)}
```
