### ISSUE TITLE
jupyterlab button can not use print

### ISSUE THREAD

**Issue by fangaofeng** [jupyter-widgets/ipywidgets#2121]
ipywidgets:version_info = (7, 2, 1, 'final', 0)
jupyterlab:Version 0.32.1
```python
button4 = widgets.Button(description=" button1")
display(button4)    
def on_button_clicked4(b):
    print(4)


button4.on_click(on_button_clicked4)
print(5)
```

when click button1,can not show 4. but 5 is show.

**Comment by fangaofeng** [comment]
Thank you.I will try it.

**Comment by jasongrout** [comment]
Closing as resolved. Please comment here if you have more questions.
