### ISSUE TITLE
Error creating widget: could not find model

### ISSUE THREAD

**Issue by stonebig** [jupyter-widgets/ipywidgets#2125]
i'm cluless on bqplot + ipyleaflet not wanting to work anymore with jupyterlab-0.32.1, with a "model not found error", generated per ipywidgets (?).

I'm trying to build on jupyterlab-0.32.1, but something is not  working anymore.

see https://github.com/bloomberg/bqplot/issues/671

Any idea would be welcome, as the jupyter-launcher <0.11 was my only guess, and going back to jupyter-launcher-0.10.5 doesn't resolved the problem.

**Comment by SylvainCorlay** [comment]
can you please post the result of:

`jupyter labextension list`

**Comment by stonebig** [comment]
JupyterLab v0.32.1
Known labextensions:
   app dir: C:\WinP\bd37\bu\winp32-3.7.x.1\python-3.7.0\share\jupyter\lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.36.0-0 enabled  ok
@pyviz/jupyterlab_pyviz
        @pyviz/jupyterlab_pyviz v0.5.2 enabled  ok
bqplot
        bqplot v0.3.6 enabled  ok
jupyter-leaflet
        jupyter-leaflet v0.9.0 enabled  ok
jupyter-matplotlib
        jupyter-matplotlib v0.3.0 enabled  ok
jupyter-threejs
        jupyter-threejs v1.1.0 enabled  ok
jupyterlab-datawidgets
        jupyterlab-datawidgets v5.0.1 enabled  ok
jupyterlab-scales
        jupyterlab-scales v0.2.1 enabled  ok
jupyterlab_bokeh
        jupyterlab_bokeh v0.5.0 enabled  ok

**Comment by stonebig** [comment]
in console , I see:
````
leaflet-src.js:400 Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. Error
    at A (http://localhost:8888/lab/static/main.d8ea9c226b14f3c18538.js:1:4741653)
    at Function.j.extend (http://localhost:8888/lab/static/main.d8ea9c226b14f3c18538.js:1:4740655)
    at Object.5Sud (http://localhost:8888/lab/static/main.d8ea9c226b14f3c18538.js:1:559801)
    at o (http://localhost:8888/lab/static/manifest.cb3954b0319f707b9917.js:1:434)
    at Object.efmC (http://localhost:8888/lab/static/main.d8ea9c226b14f3c18538.js:1:4052873)
    at o (http://localhost:8888/lab/static/manifest.cb3954b0319f707b9917.js:1:434)
    at Object.pgwt (http://localhost:8888/lab/static/main.d8ea9c226b14f3c18538.js:1:4988662)
    at o (http://localhost:8888/lab/static/manifest.cb3954b0319f707b9917.js:1:434)
    at Object.mLf/ (http://localhost:8888/lab/static/main.d8ea9c226b14f3c18538.js:1:4639323)
    at o (http://localhost:8888/lab/static/manifest.cb3954b0319f707b9917.js:1:434)
````

and then 
````
Plugin 'bqplot' failed to activate.
(anonymous) @ index.js:267
````

**Comment by jasongrout** [comment]
`@jupyter-widgets/jupyterlab-manager v0.36.0-0` is the prerelease that only works with JupyterLab 0.33 prerelease. You'll need to install @jupyter-widgets/jupyterlab-manager version 0.35.

**Comment by stonebig** [comment]
hum, but it comes by default when I do "jupyter.exe" labextension install --no-build @jupyter-widgets/jupyterlab-manager.

how do I force an older version ? will I have the same problem on other plugins ?

**Comment by stonebig** [comment]
sorry, I didn't noticed this possibility of problem before.

**Comment by jasongrout** [comment]
Interesting! You're right, it seems that we published that to the wrong tag. I'll fix it now.

**Comment by jasongrout** [comment]
Fixed now - installing should bring in 0.35, not 0.36.0-0. Thanks for bringing this to our attention!

**Comment by stonebig** [comment]
you're welcomed.

**Comment by jasongrout** [comment]
Thanks!
