### ISSUE TITLE
Widgets not working on nbviewer

### ISSUE THREAD

**Issue by mthmn20** [jupyter-widgets/ipywidgets#2126]
Hi. First off, thanks for the awesome library! So I've been trying to get interactive widgets working in a notebook on nbviewer. In order to do so, I ran the notebook, hit the "Save Notebook Widget State" button in the Widgets menu, downloaded the notebook as an ipynb, uploaded it to github, and made an nbviewer page from that github link. As you can see, the widget itself is visible and the sliders move, but the widget does not respond to the sliders. Any advice? Thanks.

Github link: https://github.com/mthmn20/graphing_notebooks/blob/master/parabola_vertex_test.ipynb
Nbviewer link: http://nbviewer.jupyter.org/github/mthmn20/graphing_notebooks/blob/master/parabola_vertex_test.ipynb

**Comment by oscar6echo** [comment]
The plot cannot not update without a Python kernel running you `draw_plot` function.  
The nbviewer view is only a snapshot of the frontend.  
You would need a JupyterHub. The simplest way to post your notebook on [mybinder.org](mybinder.org), which you can see as a sort of ad hoc public JupyterHub. Read their docs to learn how. It is quite tractable.

**Comment by jasongrout** [comment]
@oscar6echo is correct (thanks for answering the question!). Closing as answered. Feel free to comment here if you have more questions.
