### ISSUE TITLE
IJupyterWidgetRegistry problem

### ISSUE THREAD

**Issue by artur-trzesiok** [jupyter-widgets/ipywidgets#2132]
Hi,

I try to write labextensions and I spot a issue.

Common approach is to write something like:
```javascript
var k3d = require('./../dist/labextension');
var base = require('@jupyter-widgets/base');

module.exports = {
    id: 'k3d',
    requires: [base.IJupyterWidgetRegistry],
    activate: function(app, widgets) {
        widgets.registerWidget({
            name: 'k3d',
            version: k3d.version,
            exports: k3d
        });
    },
    autoStart: true
};
```
base.IJupyterWidgetRegistry will produce something like:
```javascript
{
name:"jupyter.extensions.jupyterWidgetRegistry"
_tokenStructuralPropertyT: null
}
```
But in phosphor code we have:
```javascript
var id = this._serviceMap.get(token);
```

token will be the same by value but not by reference. Unfortunately javascripts Map() treat given keys as refereneces. Please check the results:

```javascript
var map = new Map();
var k1 = {a:1,b:2};
var k2 = {a:1,b:2};
map.set(k1,"issue");
map.get(k1);
map.get(k2);
```

I think that this will require to change a little bit a ipywidgets/packages/jupyterlab-manager/src/plugin.ts file.

**Comment by jasongrout** [comment]
I'm not sure exactly what you are saying is the problem. The service map depends on there being a deduplication step in the build, and you actually *do* want to retrieve a token by reference.

What do you see the actual problem being, and the effect of that problem?

**Comment by artur-trzesiok** [comment]
Propably deduplication step isn't working in our case. I'm currently on workshop with @vidartf and We started working on k3d integration with jupyterlab. I will write down a update at the end.

**Comment by jasongrout** [comment]
You can check by going into the staging directory (do `jupyter lab path`, go to the "Application direction", then to the staging subdirectory), then check the yarn.lock there to see if it has the duplicate package you are seeing.

Also you can try cleaning out the build to see if that takes care of issues: `jupyter lab clean` `jupyter lab build`.

**Comment by ivanov** [comment]
Hi there, @artur-trzesiok, this issue's been open for about a year now, does it make sense to resolve it? thanks.

**Comment by artur-trzesiok** [comment]
This issue is probably deprecated. I will close it. Thanks.
