### ISSUE TITLE
[BUG] Dependency on beta package widgetsnbextension

### ISSUE THREAD

**Issue by fritzo** [jupyter-widgets/ipywidgets#2137]
The latest release of ipywidgest depends on widgetsnbextension 3.3.0 which has not been published yet (only 3.3.0b0 has been published). This is causing travis build failures on downstream packages, e.g. https://travis-ci.org/uber/pyro/jobs/405145060

https://github.com/jupyter-widgets/ipywidgets/blob/master/setup.py#L122

**Comment by jasongrout** [comment]
I *just* published the pip versions of these packages (widgetsnbextension, then ipywidgets). Likely the cache for widgetsnbextension is not updated yet.
