### ISSUE TITLE
ipywidgets' has no attribute 'FloatLogSlider

### ISSUE THREAD

**Issue by derelearnro** [jupyter-widgets/ipywidgets#2140]
I got this error when ran it, I also tried to upgrade version 7.3 of ipywidgets

```
widgets.FloatLogSlider(
    value=10,
    base=10,
    min=-10, # max exponent of base
    max=10, # min exponent of base
    step=0.2, # exponent step
    description='Log Slider'
)
```

AttributeError                            Traceback (most recent call last)
<ipython-input-16-28f1ce065eb7> in <module>()
----> 1 widgets.FloatLogSlider(
      2     value=10,
      3     base=10,
      4     min=-10, # max exponent of base
      5     max=10, # min exponent of base

AttributeError: module 'ipywidgets' has no attribute 'FloatLogSlider'

**Comment by jasongrout** [comment]
What version do you have? `ipywidgets.__version__`

**Comment by derelearnro** [comment]
@jasongrout Thanks for your response, I fixed it, I have re-run again, and it works fine now. 

Anyway, the version I ran your code is '7.3.0'

I am going to build a GUI and visualize to my network. Could you suggest some source and ideas to develop it? I am a beginner for  both Widgets and GUI.

**Comment by jasongrout** [comment]
I'm glad you fixed it!

As for resources, there are many resources out there for designing GUIs; I'm sure searching will find many options. For ipywidgets in particular, you can check out the documentation for some help on laying out controls, etc. ipywidgets 7.3 comes with a new grid layout that might be helpful too. You can also watch the scipy widgets tutorial (most recent version from last week: https://www.youtube.com/watch?v=NBZBjEjN-rU, material at https://github.com/jupyter-widgets/tutorial).

Closing as resolved.
