### ISSUE TITLE
Slider is not displayed in Jupyterlab, shows IntSlider(value=0) instead

### ISSUE THREAD

**Issue by hans-permana** [jupyter-widgets/ipywidgets#2141]
Hi all,

It is part of my learning process in installing ipywidgets on my Jupyterlab that I browsed through the issues in this repository (open and closed). However, I could not find one to fix my current issue. 

I have successfully installed ipywidgets using `conda install` but when trying to display a slider using an instruction from this [guide](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Basics.html), it does not give me the slider I wanted. Instead, it shows me `IntSlider(value=0)` instead. What's the trick here?

Here is some information about my environment:
**ipywidgets**: 7.3.0
**widgetsnbextension**: 3.1.4
**jupyterlab**: 0.32.1
**jupyter labextension list**
![image](https://user-images.githubusercontent.com/7643370/43006226-71ffd7f6-8c35-11e8-81ea-c76e0dd95420.png)
**node**: 8.10.0

**Comment by jasongrout** [comment]
The JLab widgets plugin doesn't support 7.3 yet. Downgrade to 7.2.1. We're waiting until jlab 0.33 next week for 7.3 support.

**Comment by hans-permana** [comment]
Unfortunately downgrading to 7.2.1 does not solve the problem. 

While downgrading to 7.2.1 using this command `conda install -c conda-forge ipywidgets=7.2.1` I observed that my widgetsnbextension was upgraded to 3.2.1. Possibly because previously it was the conda package from `anaconda` channel.

**Comment by hans-permana** [comment]
Downgrading to 7.2.1 did actually solve the problem. I just needed to reload my Jupyterlab page after downgrading it. Thanks for the help!

**Comment by jasongrout** [comment]
Great!

**Comment by LLyq17** [comment]
> Great!

Hi,I have the same problem above,but Downgrading seems not work!
