### ISSUE TITLE
Request for help in interpreting a diagnostic message from ipywidgets (`KeyError`)

### ISSUE THREAD

**Issue by mprogram** [jupyter-widgets/ipywidgets#2163]
It's rather a question, not an issue: 

With the help of [kernelspy](https://github.com/vidartf/jupyterlab-kernelspy) upon running various examples (animations in pythreejs, etc., namely, when rendering a core functional part of a corresponding widget)* I'm getting this kind of a diagnostic message:

`0: "---------------------------------------------------------------------------"`
`1: "KeyError Traceback (most recent call last)"`
`2: "/usr/lib/python3/dist-packages/ipywidgets/widgets/widget.py in _handle_msg(self, msg)  660 """Called when a msg is received from the front-end"""  661 data = msg['content']['data'] --> 662 method = data['method']  663   664 if method == 'update': "`
`3: "KeyError: 'method'"`

How should I interpret it in simple terms? Thank you in advance. 
*. JupyterLab 0.33.6 and ipywidgets 7.3.1

**Comment by jasongrout** [comment]
Do you have a simple self-contained example reproducing the issue?

**Comment by jasongrout** [comment]
It seems that the kernel side is not getting a correctly-formed message from the javascript.

**Comment by mprogram** [comment]
Yes, it's a continuation of issue(s) #206 on pythreejs, #14 and #13 on ipywebrtc, and #159 on ipyvolume.

**Comment by mprogram** [comment]
_I've just posted a detailed investigation on the pythree issues. Please, have a look there._

**Comment by mprogram** [comment]
No longer the issue after various upgrades, closing.

**Comment by jasongrout** [comment]
Great, thanks for following up here. I'm glad it's working for you now.
