### ISSUE TITLE
Move to es2015 compile target

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#2164]
It looks like even if we are supporting notebook 4.4 (released beginning of 2017), the supported browsers are current chrome/safari/firefox for that time, and all of those support es2015 modules. So I think it's fine to upgrade our typescript compile target to es2015 instead of es5.

Might as well upgrade to typescript 3.0 while we are at it.

**Comment by vidartf** [comment]
Would this not require all dependents (third-party widget extensions) to also compile to es2015? If so, it should be a major release of the npm packages?

**Comment by jasongrout** [comment]
No, third party packages don't have to upgrade their target. Webpack can mix and match, IIRC.

**Comment by vidartf** [comment]
But `@jupyterlab/base` is always declared as external, and widgets always inherit `Widget`. As far as I know, it is not possible for an ES5 "class" to inherit an ES6 class.

**Comment by jasongrout** [comment]
Very good point. That is something easy to check, though.

**Comment by vidartf** [comment]
Resolved by https://github.com/jupyter-widgets/ipywidgets/pull/2456

**Comment by SylvainCorlay** [comment]
> Resolved by #2456

Closing then.
