### ISSUE TITLE
Remove method for a WidgetView not called when clearing outputs

### ISSUE THREAD

**Issue by jtpio** [jupyter-widgets/ipywidgets#2171]
When clearing a view using "Clear Outputs" from the context menu (or re-executing the notebook cell), the user defined `remove` method from a `DOMWidgetView` is never called.

This seems to happen only in JupyterLab (and also when using an `Output` widget). As far as I remember it used to work fine when creating widgets on the fly in the classic notebook (from [Building a Custom Widget](https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Custom.html)).

A simple way to reproduce this is to start from the [Jupyter Widget Hello](https://github.com/vidartf/jupyter-widget-hello) and add the following to the view:

```typescript
export
class ExampleView extends DOMWidgetView {

  interval : number

  initialize() {
    console.log('initialize');
  }

  render() {
    super.render();
    console.log('render');
    this.interval = window.setInterval(() => {
      console.log(`Interval: ${this.model.get('value')}`);
    }, 1000);
    console.log(`create interval ${this.interval}`);
    this.el.textContent = this.model.get('value');
  }

  remove() {
    console.log('remove')
    window.clearInterval(this.interval);
    console.log(`cleared interval ${this.interval}`);
    super.remove();
  }
}
```

Since the `remove` method is not called, the interval keeps running in the background and new ones are added when re-executing the cells. This can be problematic when the view allocates more memory (sprites, images and so on) and needs to do some cleanup before being removed.

After digging a little bit in the code, the further I could get down the chain is in the `dispose` method of the `WidgtetRenderer`, which doesn't seem to hold information related to the current `viewId`.

https://github.com/jupyter-widgets/ipywidgets/blob/537b171d5faec7883a38098dcf5c7a952499cb23/packages/jupyterlab-manager/src/renderer.ts#L77-L82

The view is however properly disposed with the `remove` method being triggered when closing the widget with `widget.close()`:

https://github.com/jupyter-widgets/ipywidgets/blob/537b171d5faec7883a38098dcf5c7a952499cb23/packages/base/src/manager-base.ts#L180

Is there a way to know which views are attached to an output area, so they could be removed whenever the output area is cleared?

**Comment by jasongrout** [comment]
What should be happening here is that the phosphor dispose method is called when the phosphor widget is removed from the page in JupyterLab, and that calls the view remove method: https://github.com/jupyter-widgets/ipywidgets/blob/537b171d5faec7883a38098dcf5c7a952499cb23/packages/base/src/widget.ts#L718

Are you saying this only happens in JLab when you are displaying a widget inside of an output widget?

**Comment by jasongrout** [comment]
Thanks for bringing this up! In the method you pointed out above, we should have called the parent's dispose method, which takes care of propagating the phosphor dispose calls down into the children, which in turn each trigger a view remove call where appropriate.

**Comment by jtpio** [comment]
Thanks for the quick fix and new release!
