### ISSUE TITLE
widget not displaying

### ISSUE THREAD

**Issue by Allen8838** [jupyter-widgets/ipywidgets#2183]
Hello, 

I am trying to display an HBOX and a button widget in jupyter notebook but after I run the cell, all I see is 
the following:

![image](https://user-images.githubusercontent.com/35154803/44665682-7e376f80-a9e4-11e8-8ecf-72e2daf575fc.png)

I looked at previous issues and suggestions and still have not been able to resolve this. For example I have looked at issue #1778 and enabled the notebook extension at the system level as well as delete the notebook.json file but the problem persists. Please let me know if you have any suggestions. Thanks.

**Comment by jasongrout** [comment]
Is this the jupyter notebook or JupyterLab? If in the Jupyter notebook, please post the output of `jupyter nbextension list`. If in JupyterLab, the output of `jupyter labextension list`

**Comment by Allen8838** [comment]
Hi @jasongrout it is in jupyter notebook. Please see below

![image](https://user-images.githubusercontent.com/35154803/44688916-c033d600-aa23-11e8-84b9-aac9fb2ebd1b.png)

**Comment by jasongrout** [comment]
Thanks. Are there any javascript errors in the browser javascript console?

It appears that the widget javascript isn't getting loaded for some reason.

**Comment by Allen8838** [comment]
@jasongrout Sorry for the delay in reply. There are errors in the javascript console. Please see below. Thanks. 

![image](https://user-images.githubusercontent.com/35154803/45254778-c2633200-b34b-11e8-98f3-356000528723.png)

**Comment by markiemarkus** [comment]
@Allen8838 did you solve this? I have the same issue

**Comment by jasongrout** [comment]
Can you find the very first error in the JavaScript console? That likely tells us why the widgets javascript isn't getting loaded.

What version of ipywidgets?

**Comment by markiemarkus** [comment]
@jasongrout 
Switched browser to chrome and this fixed it.
Have stepped away from desk.
Let me know if you would still want more details

**Comment by jasongrout** [comment]
Great! If you want to pursue this further, feel free to post more details.

@Allen8838 - do you still have this issue?

**Comment by martinRenou** [comment]
Closing this issue.

If you encounter a similar issue, please be sure you:
- installed ipywidgets in a clean environment
- followed all the installation steps
- restarted the Notebook server AND/OR refreshed your notebook page
