### ISSUE TITLE
Adding a file selection widget

### ISSUE THREAD

**Issue by deeplook** [jupyter-widgets/ipywidgets#2190]
I was looking for a "file selection widget", basically a Text field that would open an OS-specific file selection dialog and return the path of the selected file as a string value. I could not find that. Is that because it doesn't exist? And if so, would this be possible/doable? I'm not sure how this could be done in some OS-independant way, though.

**Comment by andymcarter** [comment]
I have used this gist as a basis for developing similar widgets in the past, I am not hugely familiar with tkinter but managed to get something to achieve what you need.

https://codereview.stackexchange.com/questions/162920/file-selection-button-for-jupyter-notebook

I ended up linking together this button and a text field to display the returned filename.

**Comment by deeplook** [comment]
@andymcarter i've just tested this on macOS and JupyterLab. I get a Python process started with a file selection dialog, but it's not immediately in the foreground and will not close after selecting files. So I have to kill it. Also, I'm totally not sure Tk is the way to go... ;)

**Comment by soerendip** [comment]
That does not seem to work when the notebook runs remotely though.

**Comment by motin** [comment]
> I'm not sure how this could be done in some OS-independant way, though.

Here is an existing OS-independent implementation: https://pypi.org/project/ipyfilechooser/

**Comment by keatonb** [comment]
There's something similar implemented already as FileUpload that returns the contents of the file.  Would it be straightforward to make a version of this that just returns the path to the file?  Would be great to be able to make another similar dialog box pop up for saving a file, where you can navigate to a path and select or name the file to save to.  I have not found the Tk solutions to play nice with ipy notebooks on as Mac.

**Comment by Jhsmit** [comment]
I'm looking for something similar, I want to make a locally running Voila app and I'd like to have a widget that lets the user specify a folder or file where I can access the full path.

**Comment by scolobs** [comment]
I've been trying to do this too

**Comment by huyuhuster** [comment]
Is there any plan for this?

**Comment by jasongrout** [comment]
Would you like to look into what it would take to modify the existing file upload widget to just return a path?

**Comment by keatonb** [comment]
I found ipyfilechooser to provide the functionality I was looking for https://github.com/crahan/ipyfilechooser

**Comment by jasongrout** [comment]
Cool, thanks for posting about that package!

**Comment by hugofluhr** [comment]
> Would you like to look into what it would take to modify the existing file upload widget to just return a path? We could help you get started.

I'd be interested in a little help to get started as I think this widget would be a big plus.

**Comment by maartenbreddels** [comment]
We have built a [FileBrowser component in Solara](https://solara.dev/api/file_browser) that solves this problem. It shows the files on the server:
```python
import solara
solara.FileBrowser(directory="/Users/maartenbreddels/data/", on_file_open=print)
```
Demo:


<video src="https://user-images.githubusercontent.com/1765949/224358217-a492d3b2-16f3-4f98-bf84-8480f74ef1e2.mp4" controls="controls" >
</video>

It's a solara component, so if you want to use this in a classic ipywidgets application, use the [`.widget`](https://solara.dev/api/widget) method, like:
```python
import ipywidgets as widgets
widgets.VBox(
    children=[
        solara.FileBrowser.widget(directory="/Users/maartenbreddels/data/", on_file_open=print)
    ]
)

```

I hope this is useful to you.

**Comment by sorenwacker** [comment]
Beautiful!

**Comment by huyuhuster** [comment]
I was looking for a "multi-file selection widget". It seems that ipyfilechooser only allows selecting a single file.
