### ISSUE TITLE
interact not displaying in JupyterLab

### ISSUE THREAD

**Issue by codercahol** [jupyter-widgets/ipywidgets#2199]
I followed the instructions at https://ipywidgets.readthedocs.io/en/latest/user_install.html#installing-the-jupyterlab-extension to install and am not getting any errors, but when I run `interact(...)` I get:

![image](https://user-images.githubusercontent.com/5104722/45062952-3f4a8f00-b060-11e8-82cd-ffc094813ccc.png)

Running `jupyter labextension list` yields:
![image](https://user-images.githubusercontent.com/5104722/45063075-f0512980-b060-11e8-9259-0b1489f0d5e4.png)

**Comment by codercahol** [comment]
Restarting the entire JupyterLab app worked; I was previously trying to just restart the kernel

**Comment by jasongrout** [comment]
It actually should be sufficient to refresh the page, but restarting JupyterLab does it as well. Would you mind adding a note to the documentation to help others in your situation? The file to edit is here: https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/user_install.md#installing-the-jupyterlab-extension
