### ISSUE TITLE
button.on_click event does not work

### ISSUE THREAD

**Issue by 3kgmett** [jupyter-widgets/ipywidgets#2202]
Hi folks,
I am new on github and could not find an already reported issue on the button.on_click event. I mention that this was already found or I did a stupid mistake.

I am using: 
 * Python 3.7.0
 * Anaconda 1.8.7
 * Jupyterlab 0.34.7
* ipywidgets 7.4.1
on a Windows 7 machine

When running the following program the method "push.on_click(click(ar))" is always called a startup for one time without clicking the button. If I click the button nothing happens. 

Does somebody know what the issue is?

So long

```
import ipywidgets as widgets
from IPython.display import display
from random import choice

push = widgets.Button(
    description="Push",
    tooltip='click me',
)

# Display buttons
display(push)

# push.on_click(print('push_button_clicked'))

ar=['monkey','bert','cebra','hippo','bunny']

def click(l):
    push.description=choice(ar)
    return(0)

push.on_click(click(ar))
```

**Comment by andymcarter** [comment]
1) If you want to pass an argument with an on_click, I use `functools.partial`. Using `click(ar)` as the argument in the first example is what calls the function, this version passes the function and argument separately.

2) Also the button instance will be passed as the first argument, but seeing as you don't need it, I have added it to `click` as an unused argument (`click(_, l)`).

Is this desired functionality? The button just changes its label each time you click.

```python
import ipywidgets as widgets
from IPython.display import display
from random import choice
from functools import partial

push = widgets.Button(
    description="Push",
    tooltip='click me',
)

# Display buttons
display(push)

# push.on_click(print('push_button_clicked'))

ar=['monkey','bert','cebra','hippo','bunny']

def click(_, l):
    push.description=choice(ar)
    return(0)

push.on_click(partial(click, ar))
```

**Comment by 3kgmett** [comment]
Hi Andymcarter,
This is the desired functionallity (I have separated a simplified the program to get it done better on this platform). The solution works. Thank you very much!
