### ISSUE TITLE
Can you have 2 separate interactions on one plot?

### ISSUE THREAD

**Issue by AxleMaxGit** [jupyter-widgets/ipywidgets#2203]
I've posted the details here but no answers yet.

TL;DR I want to scatter plot some data and manually mimic linear regression on the scatter plot. At the momnt when I move the regression line the scatter plot regenerates. I'd like to be able to regenerate the scatter plot occasionally not every time the regression line moves

https://stackoverflow.com/questions/52238567/have-2-ipywidgets-acting-on-one-matplotlib-plot-in-jupyter-python

**Comment by maartenbreddels** [comment]
The discussion seems to happen on SO, closing this.

**Comment by jasongrout** [comment]
That is some nice discussion and explanation! @pbugnion and @maartenbreddels - thanks! It would be great if some portion of those explanations were put in the docs somewhere.
