### ISSUE TITLE
Upgrade to Font-Awesome v5.x

### ISSUE THREAD

**Issue by DougRzz** [jupyter-widgets/ipywidgets#2217]
Upgrade Font Awesome from v4.7 to v5.3.   There are twice as many free icons in v5.3 so it would be a useful upgrade.  

However, this would be a breaking change because some of the names have changed. e.g pie-chart (https://fontawesome.com/v4.7.0/icon/pie-chart ) vs. chart-pie (https://fontawesome.com/icons/chart-pie?style=solid).

**Comment by jasongrout** [comment]
Thanks for filing this, and for noting the incompatibility!

**Comment by martinRenou** [comment]
Maybe now would be a good time to update fontawesome @jasongrout ?

**Comment by jasongrout** [comment]
Do you know if there were any backwards-incompatible name changes?

I think it's great to look at upgrading fontawesome.

**Comment by martinRenou** [comment]
According to what @DougRzz is saying, yes, there seem to be name changes :)

But I guess it's fine as the next ipywidgets version will be backward-incompatible.

**Comment by jasongrout** [comment]
Ah, right, sorry, I should have read the whole thread :).

That's unfortunate, but sure, I guess now is the time to make the change.

**Comment by rskabelund** [comment]
Perhaps this can be addressed while at it? https://github.com/jupyter-widgets/ipywidgets/issues/2477

**Comment by jasongrout** [comment]
@martinRenou and I discussed this. The current status quo:

1. the widget manager is responsible for making sure font-awesome on the page
2. the widget manager may already put font-awesome 5 on the page (or be in an environment where fa5 is on the page). Luckily, all the environments that we know about have FA4 (though we haven't checked cocalc or nteract)


So, the question becomes: do we namespace the entire FA5 library and ship it with controls to have a known version? Or do we just leave this unspecified and up to the environment?

**Comment by jasongrout** [comment]
Also, FA5 includes a shim css file that maps v4 names to v5, so apparently it doesn't have to be backwards incompatible.

**Comment by martinRenou** [comment]
One upside of leaving this responsibility to the environment is the possibility to use a pro version of FA. If we ship the free version of FA, the user is stuck with it and can't use their license.

**Comment by martinRenou** [comment]
So Font-Awesome is upgraded in JupyterLab and the HTMLManager, see https://github.com/jupyterlab/jupyterlab/pull/7769 and https://github.com/jupyter-widgets/ipywidgets/pull/2713.

Now we might want to discuss upgrading in Jupyter Notebook :)

**Comment by jasongrout** [comment]
Closing as resolved. Upgrading the notebook can be a ticket for that repo. Thanks again!
