### ISSUE TITLE
Jupiter Widget Slider will not display

### ISSUE THREAD

**Issue by ebuka-nweke** [jupyter-widgets/ipywidgets#2234]
I am trying to follow a basin tutorial showing how to create a simple widget but when i execute the slider it does not display. There is no error but it shows "FloatSlider(value=1.0, description='Amp', max=10.0, min=1.0)"

Below is a screenshot of the example code I wrote that is giving the output:

![screen shot 2018-10-03 at 10 08 16 pm](https://user-images.githubusercontent.com/43839082/46453939-df2b3380-c758-11e8-9fe3-2b54aefd7143.png)

Does someone have a solution to this? I have tried a couple of different things, some from a different issue posted on GitHub as well: Slider is not displayed in Jupyterlab, shows IntSlider(value=0) instead #2141

However, nothing has worked. What else can i do?

**Comment by jasongrout** [comment]
This indicates the javascript is not loaded or has an error. This is in JupyterLab? Can you post the output of:

`jupyter labextension list`
`jupyter lab --version`

**Comment by jasongrout** [comment]
Also, does the browser Javascript console show any errors?

**Comment by ebuka-nweke** [comment]
Below is the outputs:

![screen shot 2018-10-03 at 11 14 01 pm](https://user-images.githubusercontent.com/43839082/46456167-c758ad00-c762-11e8-8dc3-b6f16b378155.png)

There were errors in the browser javascript console. The errors are shown in the screenshot below:

![screen shot 2018-10-03 at 11 26 30 pm](https://user-images.githubusercontent.com/43839082/46456463-d0964980-c763-11e8-8f99-b6ea5c60197e.png)

Here is a zoomed in screenshot incase the above is not readable:

![screen shot 2018-10-03 at 11 27 35 pm](https://user-images.githubusercontent.com/43839082/46456492-ee63ae80-c763-11e8-89e8-8679bb81fb88.png)

**Comment by jasongrout** [comment]
Looks like you just need to follow the installation instructions for widgets in JupyterLab: https://ipywidgets.readthedocs.io/en/stable/user_install.html#installing-the-jupyterlab-extension

**Comment by ebuka-nweke** [comment]
The sliders worked once i installed nodes and followed the installation instruction for widgets in the link you provided. However, when i continue the tutorial and try to display the output of the widget I get no response (does not plot sine wave) on the first execution. Upon re-execution it outputs errors that dont seem to make sense (it says it cannot find matplotlib in registry). Below is a screenshot of the issue:

![screen shot 2018-10-04 at 12 16 36 am](https://user-images.githubusercontent.com/43839082/46458495-ce83b900-c76a-11e8-949d-8f8bc41a714c.png)

![screen shot 2018-10-04 at 12 16 45 am](https://user-images.githubusercontent.com/43839082/46458501-d4799a00-c76a-11e8-9dc0-75ff2c1193d2.png)

Here is the beginning of the jupyterlab notebook:
![screen shot 2018-10-04 at 12 17 22 am](https://user-images.githubusercontent.com/43839082/46458545-fa9f3a00-c76a-11e8-978a-c7325a323e33.png)

Im not sure if the reinstallation of the widgets altered/affected other parts. please advise

**Comment by jasongrout** [comment]
What tutorial is this?

**Comment by ebuka-nweke** [comment]
This is a youtube tutorial:

https://www.youtube.com/watch?v=SN0Bflf14C4

**Comment by jasongrout** [comment]
Where is the code for it?

My hunch is that that tutorial code is very specific to the classic notebook, and won't work in JupyterLab without some updating.

**Comment by ebuka-nweke** [comment]
The youtube tutorial is being executed on jupiter notebook. The code is identical to what i have posted in the screenshots above. Again, the only difference is that the tutorial is being executed on jupiter notebook. 

Is JupyterLab execution different from Jupyter Notebook?

**Comment by jasongrout** [comment]
Ah, I see the nbagg backend. That matplotlib backend does not work in JupyterLab (it relies heavily on being in the classic notebook and the javascript from the classic notebook). Instead, you may want to use the new ipympl matplotlib widget: https://github.com/matplotlib/jupyter-matplotlib

**Comment by jasongrout** [comment]
> Is JupyterLab execution different from Jupyter Notebook?

The python code execution is the same.

JupyterLab has a complete rewrite of the frontend javascript code, so if something was written that relies heavily on the old classic notebook javascript code (like the nbagg matplotlib code), then it won't work in JupyterLab without some updating.

**Comment by ebuka-nweke** [comment]
Things are working now but not smoothly. It seems that i have to execute the jupyter lab notebook twice to get the widget eta display and operate. When i open the same code on jupyter notebook i also have to execute it twice to get the widget to display and operate but the display is too large for the output box and the plot is being cutoff on the right side of the figure:

![screen shot 2018-10-04 at 1 13 29 am](https://user-images.githubusercontent.com/43839082/46461122-bdd74100-c772-11e8-8b1d-e0bd30546e52.png)

Do you know why this is occurring?

This is what it shows when i first open the file in jupyterlab:

![screen shot 2018-10-04 at 1 15 29 am](https://user-images.githubusercontent.com/43839082/46461232-0a228100-c773-11e8-9187-9a5de9ee3ee8.png)

This is what it shows after first execution:

![screen shot 2018-10-04 at 1 16 15 am](https://user-images.githubusercontent.com/43839082/46461259-1e667e00-c773-11e8-9c63-7552976ec99f.png)

This what it shows after the second execution:

![screen shot 2018-10-04 at 1 16 55 am](https://user-images.githubusercontent.com/43839082/46461301-363e0200-c773-11e8-9106-2a5e76c63c43.png)

As you see above, it takes a couple of times to get it to run properly. Again, do you have any idea as to why this is occurring?

**Comment by jasongrout** [comment]
I don't have a lot of experience with the matplotlib widget, and I'm not sure why that is happening. Perhaps filing an issue in that repo (https://github.com/matplotlib/jupyter-matplotlib) would help?

**Comment by ebuka-nweke** [comment]
Thank you for your help. Things seem to be working okay now. I will look into the matplotlib issue per your suggestion.

**Comment by jasongrout** [comment]
Great, glad widgets are working now!
