### ISSUE TITLE
Symbol fill colour not rendering

### ISSUE THREAD

**Issue by janitor9** [jupyter-widgets/ipywidgets#2235]
Firstly this is great and really help with some visualisations I'm producing.

The problem I've got is that I'm creating using gmaps to create a symbol_layer with different colours for the stroke colours and fill colours and an info box. The map renders perfectly in Jupyter Notebook but when exported using embed_minimal_html or a html template, the fill colours are not rendering in the browser so the symbol looks like a doughnut

Using the developer tools I can see "fill_color" in the HTML script and everything else in there appears to be working correctly.

I've tried both solutions under the "Python Interface" section on https://ipywidgets.readthedocs.io/en/latest/embedding.html#python-interface

Hopefully that makes sense. I'm not a HTML or Python expert so apologies if this is something obvious!

**Comment by vidartf** [comment]
If you use the JS embedding way (https://ipywidgets.readthedocs.io/en/latest/embedding.html#embeddable-html-snippet), does it work differently? It is hard to say if this is an issue with the embedding code, or if the gmaps extension relies on the kernel being present. CC @pbugnion

**Comment by janitor9** [comment]
I'll check it out next week

**Comment by janitor9** [comment]
As far as I can tell that is doing nothing? I assume I should get a dialog of some sort?

**Comment by vidartf** [comment]
> As far as I can tell that is doing nothing? I assume I should get a dialog of some sort?

Yes, clicking the menu item should open a dialog with code in it. Are there any errors in the browser console? Regarding the code you get from the python interface, I would maybe try opening an issue on the gmaps repo (https://github.com/pbugnion/gmaps), at least for the initial debugging.

**Comment by janitor9** [comment]
Thanks @vidartf I'll post it there too

There are two errors:

> Error serializing widget state attribute: store

> Uncaught (in promise) TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at DrawingControlsModel.WidgetModel.serialize (widget.js:415)
    at manager-base.js:321
    at Array.forEach (<anonymous>)
    at manager-base.js:319

**Comment by janitor9** [comment]
Error seems to be caused by a conflict between default values set by google map and the gmaps package so closing this off.

**Comment by vidartf** [comment]
Thanks for posting back!

Xref: https://github.com/pbugnion/gmaps/issues/275

**Comment by pbugnion** [comment]
Apologies -- I missed this issue. The problem was completely in gmaps not setting defaults appropriately client-side.
