### ISSUE TITLE
Using an iPython Button Widget is causing the Vertical Scroll position to change 

### ISSUE THREAD

**Issue by JohnOmernik** [jupyter-widgets/ipywidgets#2243]
I am using the button widget to scroll through a list of images. Essentially, it lets me page through things and it's working quite well except one thing. Since I need to clear_output (otherwise, it just keeps adding to the output, not what we want) There is a moment where the output is clear, and then rewritten causing Jupyter to try to reposition the vertical scroll bar.  It's quite frustrating, but picture two button (prev and next) 3-5 lines of text, and then an image in the output.   To get here, I need to run the cell that has the code below.  arstream is an array of dictionary objects, with one key being the raw bytes. When i press the button, I want to advance the index, and then display the image at the current index (and the json that makes up the message minus the image blob).  

Like I stated, this is all working well, when I execute the code block, I scroll so the buttons are the top my screen, press next, and an image and text shows up, but the vertical scroll bar is now repositioned.  Ok, adjust scroll, click next, and again, only half the picture is shown, because the notebook, after pressing the widget, moves the image down.  I adjust, and so on and so forth. 

Basically, I need a way, for these button presses, to do what I want them to do, without adjusting the scroll bar position. Is this possible?

*Note This code block doesn't have the loading of the array, so it doesn't work by itself. It's just here to show how it works. 
* Double note: any ideas for improvements on this methodology will be taken! I am new to this!

thanks!

```
curidx = 0
but_next = widgets.Button(description='Next Image')
but_prev = widgets.Button(description='Prev Image')
out = widgets.Output()
def on_button_clicked_next(b):
    global curidx
    curidx += 1
    if curidx >= len(arstream):
        curidx = 0
        
        
    with out:
        clear_output(wait=False)
        print("Current Index: %s of %s"  % (curidx, len(arstream)))
        msg, img = eventdisplay(curidx)
        print(msg)
        d = display(img)

def on_button_clicked_prev(b):
    global curidx
    curidx -= 1
    if curidx < 0:
        curidx = len(arstream) - 1
    with out:
        clear_output(wait=False)
        msg, img = eventdisplay(curidx)
        print("Current Index: %s of %s"  % (curidx, len(arstream)))
        print(msg)
        d = display(img)
    
but_next.on_click(on_button_clicked_next)
but_prev.on_click(on_button_clicked_prev)

butbox = widgets.HBox([but_prev, but_next])
widgets.VBox([butbox, out])
```

**Comment by jasongrout** [comment]
My guess is that the height of the notebook is changing when the output is cleared, which resets the notebook document scroll, then the output is populated again, which flows down from the current scroll position. I have two suggestions:

1. use `clear_output(wait=False)`, which doesn't clear immediately, but waits until the new input comes before replacing the old input - then there isn't a flash where the output is empty

2. Explicitly set a height for the output widget, so it never is short, even when empty. The docs mention this as a solution to this type of problem at https://ipywidgets.readthedocs.io/en/stable/examples/Using%20Interact.html#Flickering-and-jumping-output

**Comment by JohnOmernik** [comment]
Thank you! The clear_output(wait=True) didn't work for me. But setting the output size did. Thank you for that!
John
