### ISSUE TITLE
button on_click action not working if defined in a class

### ISSUE THREAD

**Issue by ozej8y** [jupyter-widgets/ipywidgets#2246]
Hi All, 

This is my first time raising an issue on ipywidgets.
To tidy up my code, I have been putting it into classes but found an issue in that the button click action is not working.

Here is my sample code for reproducing the issue:

```py
import ipywidgets as widgets

class buttonTest:

    debug = widgets.Textarea(
        description='Debugging:',
        description_tooltip='Standard output',
        disabled=False,
        rows=10)     
    
    runProgram = widgets.Button(
        description='Run',
        disabled=False,
        button_style='',
        tooltip='Run program',
        icon='check')    
    
    def buttonClick(self):
        self.debug.value = self.debug.value + 'Button action!!\n'
    
    def __init__(self):
        display(self.debug, self.runProgram)
        self.runProgram.on_click(self.buttonClick)
            
buttonAction = buttonTest()
```

buttonAction.buttonClick() will execute the action as expected but clicking on the button does not work.
Any suggestions are appreciated.
Thanks,
                   Jay.

Settings:
Python 3.6.2
ipykernel           4.9.0  
ipython             6.5.0  
ipython-genutils    0.2.0  
ipywidgets          7.4.2  
jupyter             1.0.0  
jupyter-client      5.2.3  
jupyter-console     5.2.0  
jupyter-core        4.4.0  
jupyterlab          0.34.10
jupyterlab-launcher 0.13.1 
traitlets           4.3.2 
widgetsnbextension  3.4.2

**Comment by pbugnion** [comment]
Thanks for raising this! The callback passed to `on_click` needs to take one argument. It gets passed the identity of the button that called it.

Modifying your example slightly makes it work for me:

```py
class ButtonTest:

    # ... 

    def buttonClick(self, target):
        self.debug.value = str(target)
```

**Comment by ozej8y** [comment]
Thanks, it's working now!

**Comment by wookayin** [comment]
It would be even better in case function signature doesn't match (i.e. a callback takes no arguments) an error is thrown.
