### ISSUE TITLE
ipywidgets, widget not showing

### ISSUE THREAD

**Issue by VetleSPZ** [jupyter-widgets/ipywidgets#2248]
Hi,

I am trying to use the interact slider in ipywidgets, but I am not able to access the widget in Jupyter notebook. Take the following example code
```
from ipywidgets import interact, interactive, fixed, interact_manual
def f(x):
    return x
interact(f, x=10);
```

which only prints 10, but no slider in the output cell in Jupyter notebook.

I've tried re-installing ipywidgets and running `jupyter nbextension enable --py widgetsnbextension`. This did not help.

The `jupyter nbextension list` gives
```
Known nbextensions:
  config dir: C:\Users\vetlee\.jupyter\nbconfig
    notebook section
      jupyter-js-widgets/extension enabled
      - Validating: ok
    tree section
      nbextensions_configurator/tree_tab/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
  config dir: C:\Users\vetlee\AppData\Local\Continuum\anaconda3\etc\jupyter\nbconfig
    notebook section
      jupyter-js-widgets/extension enabled
      - Validating: ok
      nbextensions_configurator/config_menu/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      contrib_nbextensions_help_item/main enabled
      - Validating: ok
    tree section
      nbextensions_configurator/tree_tab/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
```

The `conda list` gives
```
# packages in environment at C:\Users\vetlee\AppData\Local\Continuum\anaconda3:
#
# Name                    Version                   Build  Channel
...
ipywidgets                5.0.0                     <pip>
ipywidgets                7.4.1                    py37_0  
...
notebook                  5.6.0                    py37_0 
...
widgetsnbextension        3.4.1                    py37_0  
...
```
Any tips on how to fix the problem?

**Comment by vidartf** [comment]
I'm not seeing anything immediately incorrect, but maybe these questions can help diagnose it:
- I'm seeing widget extensions being enabled both on the user level and on the sys-prefix (conda) level, but I don't think that is should matter?
- Do you get any output in the browser developer tools console?

**Comment by VetleSPZ** [comment]
Hi. Thanks for your reply. 

I tried to run the widget again, but now with another browser (not Internet Explorer). Not sure why, but this seems to fix the problem.

**Comment by vidartf** [comment]
I believe Internet Explorer is unsupported (Edge support is variable), so that sounds reasonable. Thanks for reporting back!
