### ISSUE TITLE
Detection of value widgets as input fields for @interact: inconsistency between code and doc

### ISSUE THREAD

**Issue by nthiery** [jupyter-widgets/ipywidgets#2261]
The [@interact documentation](https://ipywidgets.readthedocs.io/en/stable/examples/Using%20Interact.html) states:

    This examples clarifies how interact processes its keyword arguments:
    - If the keyword argument is a Widget instance with a value attribute, that widget is used. Any widget with a value attribute can be used, even custom ones.
    - Otherwise, the value is treated as a widget abbreviation that is converted to a widget before it is used.

However the code instead checks whether the keyword argument is a `ValueWidget`:
https://github.com/jupyter-widgets/ipywidgets/blob/463cb0444d1a2f31c3d5cacfe6b38d067f231406/ipywidgets/widgets/interaction.py#L305-L307

It also requires the argument to have a "description" attribute:
https://github.com/jupyter-widgets/ipywidgets/blob/463cb0444d1a2f31c3d5cacfe6b38d067f231406/ipywidgets/widgets/interaction.py#L298-L299
 
I don't have an opinion about whether duck typing should or not be the preferred option; this issue is only about resolving the inconsistency between the documentation and the code, one way or the other.

**Comment by SylvainCorlay** [comment]
Indeed the ValueWidget base class was added with ipywidgets 7.0 and the documentation was not properly modified to reflect it.

**Comment by pbugnion** [comment]
Closed by #2544, which enforces using a ValueWidget and updates the documentation.
