### ISSUE TITLE
Button tooltips don't default to the description

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#2286]
Widgets with descriptions have a `description_tooltip` option that sets the tooltip, which defaults to the description if not specified: https://github.com/jupyter-widgets/ipywidgets/blob/1223d4128aebe6c8831a034a73d1546a91f5138a/packages/controls/src/widget_description.ts#L70-L73

The button tooltip defaults to the empty string, rather than defaulting to the description. Perhaps we should make this consistent and default the button tooltip to the description.

**Comment by jasongrout** [comment]
This probably requires a protocol change, since after this the button `tooltip` can be None.

**Comment by zerline** [comment]
Yes, by default, if both `description_tooltip` and `tooltip`are null or void,  we can _remove_ `tooltip` attribute if `description` is also null or void.
But here, I don't understand why we have 2 tooltips on a button. Same question could be asked for all widgets actually (see https://github.com/jupyter-widgets/ipywidgets/issues/421#issuecomment-483169783).  But especially for a button, I don't understand why we need a `description_tooltip`.

**Comment by ianhi** [comment]
Also, currently the `Button` widgets don't actually inherit from `description`

https://github.com/jupyter-widgets/ipywidgets/blob/90365264e6d7b7fa5f754a4e812ebe6b83fe4679/packages/controls/src/widget_button.ts#L50

**Comment by ianhi** [comment]
A related consequence of this is that setting a `button`'s decsription will not update the existing views.

```python
import ipywidgets as widgets
button = widgets.Button(description='something')
display(button)
button.description = ''
display(button)
```

gives this for output:
![image](https://user-images.githubusercontent.com/10111092/106815493-f38ddc80-6641-11eb-9210-1754de7786df.png)
