### ISSUE TITLE
Button doesn't work when displayed via magic command

### ISSUE THREAD

**Issue by Salbinus** [jupyter-widgets/ipywidgets#2291]
Hello,
untill here it took me hours but can't figure out what's wrong. 
Hopefully somebody is able to provide any ideas:

First my setup:
'ipython_version': '7.2.0',
 'platform': 'Windows-10',
 'sys_version': '3.7.1',
'jupyter_version': '4.4.0'

I want to display a login widget to have acces to a database.

```python
tab_nest = widgets.Tab()
tab_instruction = widgets.HTML(
    value="Hello, click the Log In- tab and type username and the password"
)

user_name = widgets.Text(description='user')
user_pw = widgets.Password(description='pw')
login_button = widgets.Button(description='Log In')
logout_button = widgets.Button(description='Log Out')


tab_login = widgets.VBox(children=[user_name, user_pw, login_button, logout_button ])
tab_nest.children = [tab_instruction, tab_login]

tab_nest.set_title(0, 'Instructions')
tab_nest.set_title(1, 'Log In')
```
The Login with the proper credentials works just fine.

```python
def connect(username, password):
    
    e = f'oracle+cx_oracle://{username}:{password}@{params["host"]}:{str(params["port"])}/?service_name={params["service_name"]}'

    dsn = cx_Oracle.makedsn(params['host'], str(params['port']), service_name = params['service_name'])
    db = sqlalchemy.create_engine('oracle+cx_oracle://'+username+':'+password+'@'+dsn)
    engine = db.connect()
    return db, e
```
and

```python
def in_button_clicked(b):
    print('hallo')

    try:
        db, e = connect(user_name.value, user_pw.value)
        print('connected successfully.')
        print(db, e)
        global ES
        global DB
        ES = e
        DB = db
        
        return db, e
    except:
        print('wrong credentials.')
    
```
 My script works well when I run it from a notebook cell. But I actually want to display it by using a magic command. 
So far so good. 

After registering it as an ipython extension, I'm able to display the widget i.e by typing
```python
%load_ext
%%display
disp
```

But now the button doesn't work.

Is there anzthing I have to pay attention at this point?
Any ideas?

**Comment by jasongrout** [comment]
Try capturing the output from the button in an output widget: https://ipywidgets.readthedocs.io/en/stable/examples/Output%20Widget.html#Debugging-errors-in-callbacks-with-the-output-widget

**Comment by Salbinus** [comment]
Sorry for the late response, but your answer was indirectly absolutely helpful. 
Thank you!
