### ISSUE TITLE
Closing widget leaves layout and descriptionstyle in global widget dict

### ISSUE THREAD

**Issue by nickpollari** [jupyter-widgets/ipywidgets#2308]
It looks like even when a widget is closed that the layout and description style widgets associated with it still are maintained in the global widget dictionary. 

```python
import ipywidgets

# starts empty
print(ipywidgets.widgets.Widget.widgets)
# create a widget
w1 = ipywidgets.Label("wiurghieugb")
# now global dict has 3 entries
print(ipywidgets.widgets.Widget.widgets)
# close the widget
w1.close()
# now global dict has 2 entries still
print(ipywidgets.widgets.Widget.widgets)
```

**Comment by jasongrout** [comment]
Right. Those layout and description widgets could be used in other widgets (that's how you can share a single layout with multiple widgets, for example), so we don't want to delete them unconditionally.

This is related to https://github.com/jupyter-widgets/ipywidgets/issues/1345 - using a weakreference would do this 'garbage collecting' for us.

**Comment by nickpollari** [comment]
I see, that makes sense. Thank you for clarifying.
