### ISSUE TITLE
Buttons vs. Text in layout

### ISSUE THREAD

**Issue by krey** [jupyter-widgets/ipywidgets#2319]
Reading https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Styling.html

Why do `Button`s behave differently to `Text`s? I would expect to see two smaller text areas, and no scrollbar.

![2019-02-15-091433](https://user-images.githubusercontent.com/223908/52862428-455e9480-3103-11e9-91d8-97863825b800.png)

(Sorry, not much of a frontend guy)

**Comment by jasongrout** [comment]
Good question. Text boxes have a fixed width, while buttons have some flexibility in their shape, because it's much more common to have some buttons next to each other than text boxes. You can set the layout of the text boxes to have a different width if you want, of course.

**Comment by krey** [comment]
Thanks @jasongrout 

Is it possible to pass something in as an argument, e.g. `Text(widgets.Layout(width='none'))` that would make the `Text` widget behave like the `Button` widget?

Or you're saying that the only workaround is to set width to 49% and hope there's enough room for the margin?

**Comment by jasongrout** [comment]
For some reason, the browser is clamping things to a minimum width. Try explicitly setting it, like this:

```python
import ipywidgets as widgets

widgets.HBox([
    widgets.Text(layout={'min_width': '0'}),
    widgets.Text(layout={'min_width': '0'}),    
], layout={'width': '200px'})
```

**Comment by jasongrout** [comment]
I played with a bit. I'm not sure why the browser is insisting on a minimum width for those text boxes. Explicitly setting the minimum width does seem to solve the problem.

**Comment by jasongrout** [comment]
Closing as resolved - feel free to comment below if needed, though!
