### ISSUE TITLE
Readthedocs not building

### ISSUE THREAD

**Issue by Carreau** [jupyter-widgets/ipywidgets#2321]
Since 2 month ago, RTD needs to be setup explicteley. 

Here is the URL for the webhook: 
https://readthedocs.org/api/v2/webhook/ipywidgets/76611/

and the docs on how to set it up. 
If you give me access I'm happy to finish the setup.

**Comment by jasongrout** [comment]
Thanks! I invited you to be a member. You should have enough permissions now.

**Comment by Carreau** [comment]
Should be rebuilding now. I manually triggered a stable build. 

Thanks.

**Comment by jasongrout** [comment]
Thank you very much!

**Comment by SylvainCorlay** [comment]
Thanks @Carreau
