### ISSUE TITLE
About variable inspector: it can't show up once draged out of the screen

### ISSUE THREAD

**Issue by fthou** [jupyter-widgets/ipywidgets#2324]
Hello,

I am trying to make the Variable Inspector show up again. This widget vanished when I want to drag it to the extension screen. It seems that it can only be shown on the principle screen, and once the widget is dragged out of the principle screen, it cannot show up again.

![image](https://user-images.githubusercontent.com/32544474/53455021-23023a80-3a64-11e9-8d3e-55975041f6b3.png)

I looked at previous issues and suggestions and still haven't found any answers about this. Please let me know if you have any suggestions. Thanks.

**Comment by fthou** [comment]
I restarted the widget, and it shows up again. Why this, even reinstallation didn't work before

**Comment by jasongrout** [comment]
I know it's been a while, and I'm glad you found a resolution. I'll point out that that icon you are pointing to is not in the standard Jupyter notebook, so presumably it is coming from some custom extension you've installed? If so, then it would be best to file an issue with that custom extension.
