### ISSUE TITLE
tooltip on Text input itself if no description is present?

### ISSUE THREAD

**Issue by zerline** [jupyter-widgets/ipywidgets#2328]
```
import ipywidgets
ipywidgets.__version__
```
'7.4.2'

```
t = ipywidgets.Text('ok')
t.description_tooltip = "my tooltip"
t
```
 -> I see no tooptip on mouse over ..

**Comment by jasongrout** [comment]
Thanks for posting code to illustrate what you are seeing.

The description tooltip is only for the description, which you don't have in the above code. Try this:

```python
t = ipywidgets.Text('ok')
t.description_tooltip = "my tooltip"
t.description="description"
t
```
and hover over 'description'.

**Comment by zerline** [comment]
That's right, thanks for the enlightenment!
Now: would it be possible to have tooltips on the text input itself? Tell me. If you find that unreasonable, then I will subclass it, np.

**Comment by jasongrout** [comment]
> Now: would it be possible to have tooltips on the text input itself? Tell me. If you find that unreasonable, then I will subclass it, np.

I think the browser may make it possible. Whether it's a reasonable ux or not is a UX decision, probably not a browser capability. I won't have time to work on this anytime soon, though, so that may also help you decide what to do.

**Comment by zerline** [comment]
I'll try to do it then.

**Comment by jasongrout** [comment]
Are you saying you'd like to contribute it to ipywidgets, or subclass the widget for your own purposes? If it's for upstream, we would need to have that UX discussion about having tooltips on widget contents (not just descriptions).

**Comment by zerline** [comment]
Yes, that's the idea: contribute if it's useful (subclassing is done already, and works afaik). My purpose is perhaps somewhat particular : a grid of small text inputs with no description.

What about a tooltip that would appear either on the description if any, or on the actual input if no description is present?

**Comment by jasongrout** [comment]
> What about a tooltip that would appear either on the description if any, or on the actual input if no description is present?

That sounds like a reasonable compromise to me. Great idea!

**Comment by jasongrout** [comment]
do you just want to use the existing description_tooltip field then, without introducing another tooltip field?

**Comment by zerline** [comment]
I think that's possible. 
NB: I'm using the HTML attribute named 'title'. It's a rather general attribute. So I was wondering where to put the code. Maybe _String.

**Comment by jasongrout** [comment]
I was imagining it would go around https://github.com/jupyter-widgets/ipywidgets/blob/092c085aaf3b1165a5c8f24a9ce663ae523e7969/packages/controls/src/widget_string.ts#L275

**Comment by zerline** [comment]
yes. But, as I want to be able to update it, I plan to clone your code for the placeholder.

**Comment by jasongrout** [comment]
I'm a little confused. I thought the current thing you are proposing is checking if the description is empty, and if so, set the title attribute of that input to be the description tooltip if there is one. Then hooking up the appropriate change listeners to update things as appropriate.

**Comment by zerline** [comment]
Ok. Maybe I have to look at the code more throughly, but what you describe is actually what I have in mind.

**Comment by zerline** [comment]
I just sent a PR; yet I must confess that I was unable to build and test.
