### ISSUE TITLE
Duplicating\copying a widget

### ISSUE THREAD

**Issue by netafr** [jupyter-widgets/ipywidgets#2352]
Hi,
I'm trying to duplicate a widget, and haven't found anything about it and nothing I tried worked so far.
For example:
```
orig_text = widgets.Text(description="work")
dup_text = text.copy()
```
Both copy(), deepcopy(), and trying to manually copy __dict__ didn't work.
I want them to have different ID's, so I can type in each of the text-boxes a different unrelated text, but dup_text should have the not only the same description but every other property of orig_text, while still have a different ID.

Is there any (preferably elegant) way to achieve this?
Thank alot.

**Comment by jasongrout** [comment]
I don't think we support `__copy__`. Right now, I think you'd need to write your own copy function that would create a new text widget and set the appropriate attributes.

I think implementing `__copy__` would be a great first issue, so tagging this as such.

**Comment by jasongrout** [comment]
Notes for someone wanting to work on this:

1. I'd probably try implementing `__copy__` by defining it in the Widget base class around https://github.com/jupyter-widgets/ipywidgets/blob/092c085aaf3b1165a5c8f24a9ce663ae523e7969/ipywidgets/widgets/widget.py#L408
2. It's important to not copy the `.comm` and `.keys`. Probably copy all other trait values that are synced and not dunder traits. I'd probably also experiment with using `.get_state` and `.set_state` to see if that's an easy way to transfer state between the original and copy.

**Comment by BrySchroeder** [comment]
I have been working with ipywidgets for some time now and I also think that this would be a useful feature.

**Comment by mmc1718** [comment]
I would like to work on a PR for this (part of Jupyter Hack Night)
