### ISSUE TITLE
dev-install "@jupyter-widgets/jupyterlab-manager@0.39.1" is not compatible with the current JupyterLab

### ISSUE THREAD

**Issue by xmnlab** [jupyter-widgets/ipywidgets#2355]
hey everyone!

I am following these steps described here https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/dev_install.md#installing-with-conda .. but with no sucess.

This is the error:

```
jupyter-widgets-jupyterlab-manager-0.39.1.tgz

Errored, use --debug for full output:
ValueError: 
"@jupyter-widgets/jupyterlab-manager@0.39.1" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.19.1 <0.20.0        >=1.0.0-alpha.3 <2.0.0@jupyterlab/application
>=0.19.2 <0.20.0        >=1.0.0-alpha.4 <2.0.0@jupyterlab/notebook
>=0.19.1 <0.20.0        >=1.0.0-alpha.3 <2.0.0@jupyterlab/rendermime
```

any idea?

**Comment by jasongrout** [comment]
Can you try doing `jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.38` for jlab 0.35?

**Comment by xmnlab** [comment]
thanks @jasongrout for the feedback.

do you mean change the `dev-install` script?
or do it before run `dev-install`?

**Comment by xmnlab** [comment]
I changed the `dev-install` script and it worked! 

maybe we should add any extra information on https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/dev_install.md#installing-with-conda or change something on `dev-install` script .. related to this issue?

**Comment by jasongrout** [comment]
Good point. Or change the npm tags to point `latest` to the version that works with jlab 0.35, and `next` to point to the prerelease version.

**Comment by xmnlab** [comment]
the changing of npm tags sounds good.

**Comment by javabrett** [comment]
Current tags do look wrong:
>0.39.1 latest
>0.39.0 next

**Comment by jasongrout** [comment]
I just adjusted the tags so that latest points to 0.38.1, and next points to 0.39.1. That should resolve this issue here. Thanks again for filing this issue!

**Comment by xmnlab** [comment]
hey @jasongrout, I rebased here my branch on top of upstream/master ... and if I run `./dev-install.sh` it raises the same error.

`./dev-install.sh` install `jupyterlab-manage` from local and its version is 0.39.1  https://github.com/jupyter-widgets/ipywidgets/blob/master/packages/jupyterlab-manager/package.json#L3

**Comment by jasongrout** [comment]
Ah, right. You're right - to do a dev install of ipywidgets (including the dev version of the jupyterlab manager), you'll need the latest jupyterlab prerelease. That's where master is right now.

**Comment by xmnlab** [comment]
I see ... the instructions here https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/dev_install.md#installing-with-conda shows to install jupyterlab from conda .. so probably it should emphasize to install jupyterlab from github master.

it says `the latest JupyterLab release` one line before `Installing With Conda` but in the instructions for conda .. it just install from conda

**Comment by jasongrout** [comment]
Ah, we're in a bit of a transition period for JupyterLab, where we have a prerelease for JupyterLab that is not up on conda-forge. We should change the instructions. Thanks for pointing this out, sorry for the confusion.

**Comment by jasongrout** [comment]
I've opened #2356 to address this. Thanks for pointing it out.

**Comment by xmnlab** [comment]
thanks @jasongrout !
