### ISSUE TITLE
widget support on Kaggle kernel

### ISSUE THREAD

**Issue by cornhundred** [jupyter-widgets/ipywidgets#2360]
I'm unable to get my widget (https://github.com/ismms-himc/clustergrammer2) to work in Kaggle (link to public kaggle notebook https://www.kaggle.com/cornhundred/kernel064927894e). I'm seeing the following error that begins with `Could not instantiate widget`: 

<img width="999" alt="Screen Shot 2019-04-05 at 1 19 41 PM" src="https://user-images.githubusercontent.com/8352840/55645093-a15da500-57a5-11e9-8e40-dd4891152153.png">

I'm using the following commands to pip install the widget:
```
!pip install ipywidgets
!pip install clustergrammer2
!jupyter nbextension enable --py --sys-prefix widgetsnbextension
!jupyter nbextension enable --py --sys-prefix clustergrammer2
```

**Comment by maartenbreddels** [comment]
Opening that page it does not work, if I fork you kernel it does work. Did you refresh it so the extension loads?

**Comment by cornhundred** [comment]
Thanks, re-running Chrome in incognito mode got it to work. That is really cool to see the widget running on Kaggle :D 

I'm guessing that embedding the widget into the saved notebook is not supported.

**Comment by maartenbreddels** [comment]
(from mobile phone)

On Fri, 5 Apr 2019, 21:49 Nicolas Fernandez, <notifications@github.com>
wrote:

> Thanks, re-running Chrome in incognito mode got it to work. That is really
> cool to see the widget running on Kaggle :D
>

Indeed, it surprised me as well.

> I'm guessing that embedding the widget into the saved notebook is not
> supported.
>
We could ask them to support it, what is the normal communication channel
with them?

**Comment by cornhundred** [comment]
I think we can just raise a question on their Q&A section. Someone already asked about Jupyter widgets here (https://www.kaggle.com/questions-and-answers/33450) and here (https://www.kaggle.com/cavendish/interactive-widgets-in-a-notebook). 

It was actually seems to be very easy to get the widget to run in the notebook (see notebook https://www.kaggle.com/cornhundred/clustergrammer2-viz-stoeckius-et-al-2017). You just have to go to settings (on the right panel), Packages: Install, and just give the name of the custom package. I did not even need to do the usual `jupyter nbextension enable --py --sys-prefix widgetsnbextension` step. 

On a related note, I could not get the widget working on Google's colab. 

If widgets in kaggle works as easily as it seems to (and especially if we can embed the widgets into the static html notebooks) then it will be very useful for our group. Kaggle offers computers with 16GB of ram, private projects, easy version controlling, etc.

**Comment by cornhundred** [comment]
I commented on someone facing the same issue on Kaggle under product-feedback https://www.kaggle.com/product-feedback/42782

**Comment by jaipara** [comment]
Yes, widgets are NOT working after committing the notebook. It would be really great if they fix it.
I commented on the related two of the related threads in kaggle https://www.kaggle.com/questions-and-answers/33450, https://www.kaggle.com/product-feedback/42782 and https://www.kaggle.com/getting-started/135862#784075

**Comment by jasongrout** [comment]
Thanks for following up here. Since it doesn't look like we can do anything about this, I'll close this issue, and put it in the reference milestone so others can learn from the discussion here.
