### ISSUE TITLE
Displaying different string name of variables in an interact widget

### ISSUE THREAD

**Issue by scottwsides** [jupyter-widgets/ipywidgets#2362]
I love the widgets, and I'm starting to use these more. I'd like to know if there's a way of displaying a string variable name other than the one in the function argument. In the image below for instance... how to display, say... "checking  account balance" instead of 'x'?

<img width="758" alt="Screen Shot 2019-04-08 at 11 20 02 AM" src="https://user-images.githubusercontent.com/13578795/55743787-71eea880-59f0-11e9-90a5-672288330d60.png">

**Comment by jasongrout** [comment]
You can construct the actual widget used, and give the description name there:

```python
from ipywidgets import IntSlider
interact(f, x=IntSlider(description='balance', min=0, max=100, value=40))
```

**Comment by scottwsides** [comment]
Ah! Thanks!
