### ISSUE TITLE
Widgets with saved state not re-rendering

### ISSUE THREAD

**Issue by andyjmc** [jupyter-widgets/ipywidgets#2368]
My widgets are saving their state (when I refresh and download widget state json it contains all the correct details. However they wont seem to rerender on the page. Am I missing something? I have attached a screenshot to show the cell output I am getting upon a page refresh. 
![Screenshot 2019-04-12 at 09 51 30](https://user-images.githubusercontent.com/42138224/56024892-eaaf7680-5d08-11e9-8abc-db0082bcde54.png)

**Comment by andyjmc** [comment]
It was because the notebook was not trusted.

**Comment by jasongrout** [comment]
Thanks for following up here. That sounds right.
