### ISSUE TITLE
Checkbox description should be clickable

### ISSUE THREAD

**Issue by kmike** [jupyter-widgets/ipywidgets#237]
It'd be nice to have widgets.Checkbox description clickable in addition to the checkbox itself.

**Comment by jdfreder** [comment]
@kmike thanks for the suggestion.  I plan on building the descriptions using subwidgets for ipywidgets 6.0, because right now ipywidgets is violating DRY like crazy.  Once I do that, I'll make sure this is possible.

**Comment by jasongrout** [comment]
This should be fixed by #1346.

**Comment by jasongrout** [comment]
Fixed in #1346.
