### ISSUE TITLE
How can I pass a parameter whose type isn't integer,float or string to the interact?

### ISSUE THREAD

**Issue by wuqian5000** [jupyter-widgets/ipywidgets#2374]
.

**Comment by wuqian5000** [comment]
I just mean that only some  parameters of my function  need  the slides to change their values, whereas others do not,

**Comment by wuqian5000** [comment]
For example,  here is a definition of my function
![image](https://user-images.githubusercontent.com/38652084/56076452-dc925080-5e03-11e9-894b-a48c2e1d263e.png)
x is typeof dataset and k is typeof  integer.
I want to make use of the function 'interact'  to help me change the value of  k.
I tried to code like this：interact(pca(x,k), k=1) , but ir didn;t work.

**Comment by jasongrout** [comment]
Try "fixing" the arguments: https://ipywidgets.readthedocs.io/en/stable/examples/Using%20Interact.html?highlight=fixed#Fixing-arguments-using-fixed

**Comment by jasongrout** [comment]
Alternatively, you could use the python `partial` from functools to make your function a single-parameter function. Or wrap it in another function that takes a single value and use interact on that.

**Comment by wuqian5000** [comment]
OK, I decide to receive the dataset as a global variable in order to modify the function to be a single-parameter one.
Thank you!

**Comment by jasongrout** [comment]
Oh right, that's another way to do it. Thanks for posting so we could collect a few ways to do this for others.
