### ISSUE TITLE
Javascript Error: define is not defined

### ISSUE THREAD

**Issue by nscozzaro** [jupyter-widgets/ipywidgets#2379]
Hi, I'm trying to follow the HelloWorld widget tutorial but get this error: Javascript Error: define is not defined

Please let me know how I can resolve the issue. 

![image](https://user-images.githubusercontent.com/15185105/56157783-68d07f00-5f8e-11e9-901a-fab35015cc9d.png)

**Comment by jasongrout** [comment]
Is this in JupyterLab? The Hello World notebook does not work in JupyterLab. We should note that in the notebook (or remove the tutorial altogether?).

**Comment by nscozzaro** [comment]
Thanks for your response. Yes, it's in a Jupyter Notebook in Jupyter Lab. I guess I'll try in regular Jupyter Notebook....

**Comment by williamstein** [comment]
For completeness, here's a link to the tutorial: https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Custom.html

**Comment by nscozzaro** [comment]
It works fine for me in regular Jupyter Notebook so you can close this issue.

**Comment by williamstein** [comment]
I have a bunch of questions.

Question 1: What exactly is `define`?     Is it something that is part of ipywidgets, and is only supposed to be used to define models/views?  Or is it some general module loader functionality that classical Jupyter just happens to have, and JupyterLab does not have?

Question 2: How does one create custom widgets in JupyterLab?  There are evidently many important custom widgets out there?    Is there only way to use custom widgets in JupyterLab to (my guess?) somehow install a standard JupyterLab extension, which happens to provide the custom widget?    If so, how do you **plan to** alert your users that they are doing it wrong?  E.g., saying "Javascript Error: define is not defined" isn't the best answer.  I'm putting some code like this in CoCalc right now:
```
  let define = (..._) => {
    throw Error("Custom ipywidgets are not yet supported in CoCalc.");
  };
```
so at least users have more of a clue what they are doing wrong.  What should I do?

Question 3: Is this define approach to creating custom widgets deprecated?  What should I implement for CoCalc?

**Comment by jasongrout** [comment]
> What exactly is `define`?

`define` is from the requirejs loader that classic notebook uses, but JupyterLab does not: https://requirejs.org/

> Is this define approach to creating custom widgets deprecated? What should I implement for CoCalc?

Let's distinguish between creating a custom widget (i.e., writing a widget python and model/view js classes that work together), and making a frontend aware of the widget (i.e., telling a widget manager about the custom model/view js classes). Creating a custom widget is typically done by creating an npm package, for example using the https://github.com/jupyter-widgets/widget-ts-cookiecutter cookiecutter.

Loading a widget into a frontend changes depending on the widget manager, and is encapsulated in the overridden base manager `loadClass` method (see https://github.com/jupyter-widgets/ipywidgets/search?q=loadClass&unscoped_q=loadClass). For classic notebook widget manager, it loads custom widgets using requirejs: https://github.com/jupyter-widgets/ipywidgets/blob/99b977eabc9f56ca163d228f701a3e2a39f2e8df/widgetsnbextension/src/manager.js#L145-L163. JupyterLab uses its own registry that you have to register widgets with: https://github.com/jupyter-widgets/ipywidgets/blob/99b977eabc9f56ca163d228f701a3e2a39f2e8df/packages/jupyterlab-manager/src/manager.ts#L305-L335. Other examples load the widget classes from CDN.

Right now, we have basically each of these three options as small files in the widget cookiecutter template, so each widget has to include small stubs for loading itself into each environment. We'd welcome another small file to make custom widgets available in cocalc. Obviously this doesn't scale as well as we'd like, but loading systems are sufficiently different and the number of custom widgets is still sufficiently small that including small loaders in each widget hasn't been too much of a burden. I can imagine a better future where we do away with these stubs in each custom widget, and the widget classes themselves *just* provide the model/view classes.

This example notebook should be deprecated, as it only works in the classic notebook. It was only ever intended to be a quick way to experiment with widgets before creating a real widget package, so is a bit hacky.


(I think this helps answer the other questions too, but if something isn't clear, please comment)

**Comment by nscozzaro** [comment]
Hi @jasongrout my main issue now is that I couldn't get the web3 & web5 examples in the 6.x branch to work, seemingly because tmpnb has been retired? It's possible I'm just doing something wrong. Should those examples still work, or do they need to be updated (e.g. to use binderhub)?

**Comment by jasongrout** [comment]
> Hi @jasongrout my main issue now is that I couldn't get the web3 & web5 examples in the 6.x branch to work, seemingly because tmpnb has been retired? It's possible I'm just doing something wrong. Should those examples still work, or do they need to be updated (e.g. to use binderhub)?

Sorry, I was answering @williamstein above.

The examples likely need to be updated.

**Comment by makaylas** [comment]
I just ran across the same issue in JupyterLab.

Could you please update the example to clearly state that it does not work with JupyterLab? Or make a new example that does work with JupyterLab (that would be better 😄 ).

**Comment by SylvainCorlay** [comment]
The custom widget example notebook relies on javascript injection in the classic notebook, which is not allowed by JupyterLab.

**Comment by jasongrout** [comment]
We should probably delete that notebook in the docs, especially in ipywidgets 7.5 with the jlab 1.0 release? Instead, point people to the widgets ts cookiecutter?

**Comment by ashutosh29** [comment]
As a work-around this solves the problem

https://stackoverflow.com/questions/54442858/javascript-output-is-disabled-in-jupyterlab
