### ISSUE TITLE
how should i install "widgets JavaScript library " ??

### ISSUE THREAD

**Issue by junlei007** [jupyter-widgets/ipywidgets#2383]
"Answer: A text representation of the widget is printed if the widget control is not available. It may mean the widget JavaScript is still loading. If the message persists in the Jupyter Notebook or JupyterLab, it likely means that the widgets JavaScript library is either not installed or not enabled. See the installation instructions above for setup instructions."

how should i install "widgets JavaScript library " ??

**Comment by jasongrout** [comment]
Here are the install instructions in the docs: https://ipywidgets.readthedocs.io/en/stable/user_install.html

**Comment by davesque** [comment]
I'm not sure that really clarifies things.  I have the same question and it's not very obvious what steps in the documentation article describe how to do this.  Can you screenshot what we should be looking at?

**Comment by jasongrout** [comment]
The installation instructions from the docs linked above are simply:

```
pip install ipywidgets
```
or if you are using conda
```
conda install -c conda-forge ipywidgets
```
