### ISSUE TITLE
Question: append_stdout and output widgets -- bad complexity?

### ISSUE THREAD

**Issue by williamstein** [jupyter-widgets/ipywidgets#2385]
Suppose you run the following code:
```
from ipywidgets import *
out = Output()
display(out)
out.append_stdout("interactive")
out.append_stdout("jupyter")
out.append_stdout("widgets")
```

Then some of the IOPUB messages look like this:
```
{
  "header": {
    "version": "5.3",
    "date": "2019-04-19T01:36:30.879825Z",
    "session": "8a2252e5-74d113e744b54f28ccbc592d",
    "username": "user",
    "msg_type": "comm_msg",
    "msg_id": "0ddc9f49-f347f34c7748f96f50c579fe"
  },
  "parent_header": {
    "msg_id": "execute_6d9d00b1-1884-45b6-bfef-46e887c38200",
    "username": "",
    "session": "",
    "msg_type": "execute_request",
    "version": "5.3",
    "date": "2019-04-19T01:36:30.864853Z"
  },
  "metadata": {},
  "content": {
    "data": {
      "method": "update",
      "state": {
        "outputs": [
          { "output_type": "stream", "name": "stdout", "text": "interactive" }
        ]
      },
      "buffer_paths": []
    },
    "comm_id": "0aa12891adec40d78b6969443cbb4b0f"
  },
  "buffers": []
}

```

and

```
{
  "header": {
    "version": "5.3",
    "date": "2019-04-19T01:36:30.880616Z",
    "session": "8a2252e5-74d113e744b54f28ccbc592d",
    "username": "user",
    "msg_type": "comm_msg",
    "msg_id": "63613a13-a8d069e3f0df7bcff445a458"
  },
  "parent_header": {
    "msg_id": "execute_6d9d00b1-1884-45b6-bfef-46e887c38200",
    "username": "",
    "session": "",
    "msg_type": "execute_request",
    "version": "5.3",
    "date": "2019-04-19T01:36:30.864853Z"
  },
  "metadata": {},
  "content": {
    "data": {
      "method": "update",
      "state": {
        "outputs": [
          { "output_type": "stream", "name": "stdout", "text": "interactive" },
          { "output_type": "stream", "name": "stdout", "text": "jupyter" }
        ]
      },
      "buffer_paths": []
    },
    "comm_id": "0aa12891adec40d78b6969443cbb4b0f"
  },
  "buffers": []
}
```

and finally 

```
{
  "header": {
    "version": "5.3",
    "date": "2019-04-19T01:36:30.881454Z",
    "session": "8a2252e5-74d113e744b54f28ccbc592d",
    "username": "user",
    "msg_type": "comm_msg",
    "msg_id": "72e74899-54b6747525980b54946907bf"
  },
  "parent_header": {
    "msg_id": "execute_6d9d00b1-1884-45b6-bfef-46e887c38200",
    "username": "",
    "session": "",
    "msg_type": "execute_request",
    "version": "5.3",
    "date": "2019-04-19T01:36:30.864853Z"
  },
  "metadata": {},
  "content": {
    "data": {
      "method": "update",
      "state": {
        "outputs": [
          { "output_type": "stream", "name": "stdout", "text": "interactive" },
          { "output_type": "stream", "name": "stdout", "text": "jupyter" },
          { "output_type": "stream", "name": "stdout", "text": "widgets" }
        ]
      },
      "buffer_paths": []
    },
    "comm_id": "0aa12891adec40d78b6969443cbb4b0f"
  },
  "buffers": []
}

```

QUESTION: Ok that works, but what if you did
```
out.append_stdout('something HUGE')
# some clears
out.append_stdout('something even more HUGE')
# etc.
...
```
as you could easily imagine someone doing.  Isn't this going to blow up in your face?  Am I missing something?  Even if you do clears, every IOPUB message contains the full history.

Just curious.

**Comment by jasongrout** [comment]
>  Isn't this going to blow up in your face?

Yes, quite possibly if you are doing something huge.

> Am I missing something?

No.

> Even if you do clears, every IOPUB message contains the full history.

This is a problem with the simple syncing protocol for this outputs array - we sync the full array every time. If you do a clear using the method on the widget, it should clear the array. If you do a clear using the clear_output() function, the clearing happens on the client and we run into issues with messages crossing between the client and kernel.

**Comment by jasongrout** [comment]
I've thought a little about how to do proper append-only syncing for ipywidgets attributes (or in general some sort of diff-based syncing), which would also be useful for streaming sources like browser cameras or audio. I (and others) haven't thought about it enough to sit down and figure it out, though.

**Comment by williamstein** [comment]
I understand -- I just wanted to make sure I wasn't missing something in the protocol.  

> This is a problem with the simple syncing protocol for this outputs array - we sync the full array every time

In CoCalc I have the same problem with diffing arrays, which I haven't got around to adding to the protocol (I just record the whole array in the diff).  However, I have much better diffing of Maps (just send the changed key/values), so I use maps (with "integer" keys) instead of arrays for output, thus avoiding the problem.   The main thing you have to watch out for is that all map keys are actually strings in Javascript, and of course the JSON representation is a tiny bit less efficient.

> If you do a clear using the method on the widget, it should clear the array. If you do a clear using the clear_output() function, the clearing happens on the client

That's useful.  By "the widget" you mean the frontend widget in the browser?  Basically, you're saying that there is some comm message the frontend widget can send the kernel, which will actually clear that array?  And, if one calls `clear_output()` from Python, then the frontend client should always send that comm message *back* to the kernel?   That makes sense, and I just need to figure out what that comm message actually is.  Of course, for cocalc all do this back and forth entirely on the backend.

**Comment by maartenbreddels** [comment]
Maybe this PR is useful:
https://github.com/QuantStack/voila/pull/91
I had to 'fake' an Output widget at the nbconvert level.

**Comment by jasongrout** [comment]
William, the front end should just sync an empty outputs array...that's the comm message.

**Comment by williamstein** [comment]
Got it.  So it sends a message updating the value to be empty.  I'll try that.

**Comment by jasongrout** [comment]
Yes. Here is the code in the classic notebook output widget doing that: https://github.com/jupyter-widgets/ipywidgets/blob/f78dcb6474e68d7fed6202dd2d1ddd3fdecc835e/widgetsnbextension/src/widget_output.js#L47-L48

**Comment by maartenbreddels** [comment]
Note that code is actually wrong I believe, assuming https://github.com/jupyter-widgets/ipywidgets/pull/2351/files is correct, it does not respect wait=True.

A similar fix was done for nbconvert here: https://github.com/jupyter/nbconvert/pull/969/files

Hope that helps to clarify things.

**Comment by williamstein** [comment]
Thanks for the all the help everybody.  With that, it was pretty easy to implement clear_output, and here's what I came up with for CoCalc:

https://github.com/sagemathinc/cocalc/commit/e3a28d150e9735bdeecbb14d409c95342efe46fd

**Comment by jasongrout** [comment]
Closing as answered.

**Comment by jasongrout** [comment]
CC also the other output widget discussion from William, which contains a few more insights into the output widget design decisions: #2377
