### ISSUE TITLE
Question: comprehensive list of widgets that have children

### ISSUE THREAD

**Issue by williamstein** [jupyter-widgets/ipywidgets#2387]
Are the widgets listed under [Container/Layout widgets](https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html#Container/Layout-widgets) a comprehensive list of all standard widgets that have children. 

I ask because the Output widget for CoCalc is written using React (etc.) rather than Phosphor, so all widgets that might contain output in it should also be written using React.  So I'm re-implementing everything in the list above.  Do I have to implement anything else?

**Comment by SylvainCorlay** [comment]
Actually, most widgets have children (such as `style` and `layout`).

Also, many widget libraries like bqplot, ipyvolume, pythreejs are implemented with hierarchies of widgets.

**Comment by jasongrout** [comment]
If you're asking about standard (i.e., `controls package`) widgets who have widget children who manage their own DOM elements - the Box, HBox, VBox, and GridBox widgets are the ones that come to mind, i.e., the ones implemented in https://github.com/jupyter-widgets/ipywidgets/blob/master/ipywidgets/widgets/widget_box.py.

(see https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Styling.html#The-Grid-layout for the GridBox widget)

**Comment by jasongrout** [comment]
(then also the accordion and tab widgets, like you saw...)

**Comment by williamstein** [comment]
Thanks, yes that's what I was asking about.

> Also, many widget libraries like bqplot, ipyvolume, pythreejs are implemented with hierarchies of widgets.

Unfortunately, I won't be supporting third party custom widgets for the first version of Cocalc-Jupyter widgets.  I don't know if I'll ever be able to support them, but in any case I'll be worrying about them later.

**Comment by jasongrout** [comment]
Closing as answered.
