### ISSUE TITLE
Question: why do you use a lot of different attributes for the "value" of a widget (in the model), rather than just using "value"?

### ISSUE THREAD

**Issue by williamstein** [jupyter-widgets/ipywidgets#2388]
- The value of a slider is stored in the `value` attribute of the model.
- The value of a dropdown selector is stored in the `index` attribute of the model, and `value` is not used.
- The "value" of an output widget (list of output messages) is stored in the `output` attribute of the model. 
- ... and potentially infinitely more variations.

Question: Is there a good reason for this?  Are there situations where the value of a widgets involves multiple attributes in the model at once?

**Comment by jasongrout** [comment]
Most widgets use `value` for the main value, and indeed, are descended from the ValueWidget class: https://github.com/jupyter-widgets/ipywidgets/blob/f78dcb6474e68d7fed6202dd2d1ddd3fdecc835e/ipywidgets/widgets/valuewidget.py

For the dropdown (and the "select" widgets in general), inspired from Sage interacts, the value can be a python object, which cannot in general be synced to the js side. Instead, we sync the index and a list of labels. The `.value` attribute still exists in python, but is set when the index is changed: https://github.com/jupyter-widgets/ipywidgets/blob/f78dcb6474e68d7fed6202dd2d1ddd3fdecc835e/ipywidgets/widgets/widget_selection.py#L223-L231

From the user's perspective in python, the value attribute on selection widgets exists and works just fine, but what is synced is the index and a list of labels.

**Comment by jasongrout** [comment]
For the output widget - that indeed could have been `.value` instead of `.outputs`. My mistake. Perhaps we can change it in ipywidgets 8.

**Comment by williamstein** [comment]
Thanks for the explanation.  I've [changed my architecture](https://github.com/sagemathinc/cocalc/commit/957ed96a460d975f1694b0c055cd8ebcf17b46bc) to support having any fields change, rather than just value/outputs.

**Comment by jasongrout** [comment]
Oh, absolutely. An explicitly supported usecase is changing attributes other than `value`, like the min/max, etc. The underscore view and model attributes shouldn't change. Others can change.

**Comment by jasongrout** [comment]
Closing as answered.
