### ISSUE TITLE
Button induces persistence

### ISSUE THREAD

**Issue by soerendip** [jupyter-widgets/ipywidgets#2391]
I am running the following code in a jupyter notebook. It produces some plots based on the selection in the SelectMultiple widget. When I use the plot method directly, the output works. But when I use the button to create new plots the output is not cleared. Any idea why that happens and how to fix it? When the button is used the old plots are not cleared and new plots are appended to the old plots. 

```
import pandas as pd
import numpy as np

import ipywidgets as widgets    
from ipywidgets import SelectMultiple, Select, Layout, Button
from ipywidgets import IntProgress as Progress
from IPython.display import display, clear_output

from bokeh.plotting import figure, output_file, show
from bokeh.layouts import gridplot
from bokeh.io import output_notebook
# from functools import lru_cache

output_notebook()

class TheClass():
    def __init__(self):
        self._xmax = 0
        self._xmin = 10
        self.selector_steps = SelectMultiple(options=[5, 10, 100, 1000], value=(10, 100))
        self.output = widgets.Output()
        self.n_steps = 10
        self.button_plot = Button(description='Plot')
        self.button_plot.on_click(self.plot)
        
    @property
    def xmax(self):
        return self._xmax
    
    @xmax.setter
    def xmax(self, value):
        self._xmax = value

    def x(self):
        return np.linspace(self._xmin, self._xmax, self.n_steps)
        
    def y(self):
        return np.sin(self.x())
    
    def plot(self, b=None):
        with self.output:
            clear_output()
            p = self._create_plots()
            show(p)
        display(self.output)
    
    #@lru_cache(maxsize=32)    
    def _create_plots(self):
        plots = []
        for n_steps in self.selector_steps.value:
            p = figure()
            self.n_steps = n_steps
            p.line(self.x(), self.y())
            plots.append(p)
        return gridplot(plots, ncols=1)

inst = TheClass()

inst.selector_steps

# new cell
inst.plot()

# new cell
inst.button_plot
```

**Comment by jasongrout** [comment]
I'm not sure exactly what is going on here. It seems like some weird interaction with bokeh and the output widget. There is one problem with your code that probably causes or at least exacerbates the issue. You are displaying the output widget on every update, but typically you display the output widget *once*.  It works for me if you remove the last line of `plot` (the display line), and then you can explicitly display that output widget with `inst.output`.

**Comment by soerendip** [comment]
It also happens with matplotlib. 

[See here](https://stackoverflow.com/questions/55835389/ipywidget-button-induces-persistence-of-output
)

**Comment by soerendip** [comment]
But that fixed it!
