### ISSUE TITLE
How to disable tab?

### ISSUE THREAD

**Issue by trllrgn** [jupyter-widgets/ipywidgets#2393]
I am trying to create a simple GUI. The user sets some settings on one tab and runs a calculation. During this process, the second tab, which contains a "Results Drilldown" section should be disabled. Once the calculation is finished, I want to enable the results drilldown tab.

Is this currently possible using widgets.Tab()?

**Comment by andymcarter** [comment]
I don't think this is possible with Tab at present, the `disabled` attribute doesn't have an effect in the same way as other widgets.

Two ways you could achieve the behaviour you want:

- Run your calculation, and then **add** a new child tab to the Tab container called 'Results Drilldown'  with your results output.
- Create a blank Output widget in the 'Result Drilldown' tab when you start up the notebook, and when your calculation is complete, append your results to this Output widget.

**Comment by trllrgn** [comment]
Thanks for the answer, I opted for adding the tab later.
