### ISSUE TITLE
ToggleButtons without a default value

### ISSUE THREAD

**Issue by Majik0327** [jupyter-widgets/ipywidgets#2396]
It'd be nice to be able to create a ToggleButtons row in which no value was set by default.

For example, 
```
import ipywidgets as widgets

fruits = ["Apple", "Banana", "Orange"]
tb_fruits = widgets.ToggleButtons(options = fruits)
html_desc = widgets.HTML(value = "")

def get_info(value):
    with open("files/{}.html".format(value["new"])) as inf:
        html_desc = inf.read()

tb_fruits.observe(get_info, names = "value")

widgets.VBox(children=(tb_fruits, html_desc))
```
I don't want the contents of the HTML file to display initially (and not unless the user clicks on one of the fruits). But if "Apple" is already selected initially, then they have to click on something else (e.g. "Banana") in order to then click on Apple to get the function called by .observe() to read in the file and populate the html_desc variable, displaying the desired information.

Note: Attempting to set the value to "None" initially for ToggleButtons throws a "TraitError: Invalid Selection

(Further note: I'm also working -- not by choice -- on an older version of Jupyter with a slightly outdated version of ipywidgets, so if this has already been implemented, I apologize)

**Comment by jasongrout** [comment]
Adding `value=None` to the toggle buttons constructor works in widgets 7.4:

<img width="636" alt="Screen Shot 2019-04-29 at 7 33 23 AM" src="https://user-images.githubusercontent.com/192614/56903432-ce8f3180-6a8b-11e9-900e-57ef70b4efb7.png">

**Comment by jasongrout** [comment]
> (Further note: I'm also working -- not by choice -- on an older version of Jupyter with a slightly outdated version of ipywidgets, so if this has already been implemented, I apologize)

No problem. Looks like it has been fixed (we did do a refactor of the logic to set no selection a bit ago). I'll close this as fixed.
