### ISSUE TITLE
ToggleButtons in multiple rows

### ISSUE THREAD

**Issue by Majik0327** [jupyter-widgets/ipywidgets#2399]
Again, I'm working on an outdated version, so perhaps this has been changed already (if so, sorry!)

It would be awesome to be able to display ToggleButtons in multiple rows for a single selection.

For example, I'd like to create a 3x3 grid of a ToggleButtons object (where all the cells are the same size so it aligns and looks nice). I know I can do this with 3 ToggleButtons objects in a VBox, using .observe() -- since 7.4 includes the ability to set value=None, but I was looking for a better way to do it.

**Comment by jasongrout** [comment]
You could do this by controlling the wrapping:

```
tb_fruits = widgets.ToggleButtons(options = fruits, style={'button_width':'100px'}, layout={'width': '320px'})
```
<img width="1037" alt="Screen Shot 2019-04-29 at 8 04 41 AM" src="https://user-images.githubusercontent.com/192614/56905680-30ea3100-6a90-11e9-93f4-1c0d1c6a6363.png">

**Comment by Majik0327** [comment]
Awesome, that'll work. You can close this out. Thanks so much! I had tried messing with it like that, but must've mistyped something.
