### ISSUE TITLE
Is it possible to set rgb color borders?

### ISSUE THREAD

**Issue by trllrgn** [jupyter-widgets/ipywidgets#2405]
I am currently using 

`layout={'border':'1px solid black'}`

to set a border around an Output widget. Is it possible to use custom colors (e.g. rgb) instead of black?

**Comment by andymcarter** [comment]
You can use a hex code as the last part of the string.

```
from ipywidgets import Output
o = Output()
o.layout = {'border':'1px solid #FFCC00'}
```

**Comment by trllrgn** [comment]
Thanks for the information. If this is documented somewhere, can you please point me to it?

**Comment by jasongrout** [comment]
it uses the same syntax as the css border attribute: https://developer.mozilla.org/en-US/docs/Web/CSS/border

**Comment by trllrgn** [comment]
Thank you for the answers.
