### ISSUE TITLE
IPyWidget Asynchronous issue with ipython.core.display.Javascript Callout

### ISSUE THREAD

**Issue by aa2858** [jupyter-widgets/ipywidgets#2406]
Hi All, I am working on a UI that is primarily composed with ipywidgets objects, vbox, tab, etc including some buttons[python code]. The UI get user's inputs and then confirms the selection before before running python function attached to these buttons with on_click event. I implemented the confirmation prompt with ipython.core.display.Javascript using dialog.modal JS function in "base/js/dialog".

The problem I have now is that I am not able to synchronize the wait to get user's dialog option, make decision with the choice and continue the running the remaining part of the module. I have looked at using asycnio as explained in the documentation to control the flow with no luck.

IPython.notebook.kernel,execute is how I could get response back. For some reasons, I could mix-up the python model/view with js model/view. I am very new to this and I will appreciate all help to move this forward.
The main functionality of the widget is to call AWS API using boto3 module which are largely in python. I only venture into JS to get the confirmation and I am suspecting going to JS is root of this problem.

My notebook version is 5.7.8

```
display(Javascript("""
            require(["base/js/dialog"],
                function(dialog) {
                    function processResult(answer){
                        var kernel = IPython.notebook.kernel;
                        var callbacks = {
                               iopub : {
                                        output : handle_output,
                                        }
                        }
                        var msg_id = kernel.execute('py_ans="' + answer + '";', callbacks, {silent:false});
                        console.warn('got here ');
                    }
                    function handle_output(out_type, out){
                        console.log(out_type);
                        console.log(out);
                        var res = null;
                        if(out_type == "stream"){
                            res = out.data;
                        }
                        else if(out_type === "pyout"){
                            res = out.data["text/plain"];
                        }
                        else if(out_type == "pyerr"){
                            res = out.ename + ": " + out.evalue;
                        }
                        else{
                            res = "[out type not implemented]";   
                        }
                        document.getElementById("result_output").value = res;
                    }
                    var dialog_body = $('<div/>').append(
                        $("<p/>").addClass("rename-message")
                            .text('Enter a new filename:')
                    ).append(
                        $("<br/>")
                    ).append(
                        $('<input/>').attr('type','text').attr('size','25').addClass('form-control')
                        );
                    var d = dialog.modal({
                        title: 'Confirmation Page',
                        body: dialog_body,
                        default_button: "Cancel",
                        buttons: {
                            Continue: {
                                class: 'btn-primary',
                                click: function() {
                                    processResult(true);
                                }

                            },
                            Cancel: {
                                class: 'btn-danger',
                                click: function() {
                                    processResult(false);
                                }

                            }
                        }
                    });
                }
            );
            """ ))
```

**Comment by jasongrout** [comment]
You're right that this code is a bit awkward, and not portable to things like JuptyerLab since it depends heavily on the classic notebook js code. However, it looks like you have a kernel.execute above. Can you just run your code from that?

**Comment by aa2858** [comment]
Are you referring to the JS code?  I am using kernel.execute to capture user dialog selection which is working now.

The problem is that the JS code is not pausing until user makes selection.  I have tried what suggestion in the documentation for async etc but none work.

**Comment by jasongrout** [comment]
Are you saying the dialog pops up, but the kernel execution `py_ans=...` happens before the user confirms something? If that is the issue, then that is dealing with the notebook dialog box, which has nothing to do with ipywidgets.

**Comment by aa2858** [comment]
No, it is code after the display(Javascript(""""""") that executes before the click.  The kernel.execute is working properly to set py_ans but wait is not happening to allow me to route the logic for yes or no and continue.

That is my issue.

**Comment by jasongrout** [comment]
I'm a little confused. Why not have the code that is supposed to execute after the dialog box called in that kernel execute request? Instead of `py_ans = ...`, just do `some_function() # executed after dialog box returns`?

**Comment by aa2858** [comment]
Good point Jason.  The only reason I am using the kernel.execute is because I couldn't figure out a better to set py_ans, which keeps the user's choice, after the dialog. it is working with get_ipython and looking up the dictionary. I need to come back to widget python class to continue the flow.

The UI is python heavy and requires lots of logic to call AWS API etc with python.  Having those logic within kernel.execute will be limiting as I do not have access to widget class to continue the flow of the program.

![widget-ui](https://user-images.githubusercontent.com/546463/57244735-0c013b00-7007-11e9-8f98-3af76bdf9a0e.png)


Hope this makes sense?

**Comment by aa2858** [comment]
When the "Launch Cluster" button is clicked, the confirmation page shows and should be waiting for clicks on dialog.  But at the moment, the code after display runs which throws my code.

**Comment by jasongrout** [comment]
What you are trying to do is harder because you are mixing widgets and the dialog from the classic notebook (which has nothing to do with widgets).

However, you could wrap all of what you wanted to do in a function, and then just call the function from your kernel execute request.

The widgets won't wait for a dialog - they don't know anything about a dialog that they should wait for.

**Comment by jasongrout** [comment]
Another thing you could do is having confirmation in widgets, which appear when the launch button is clicked. They'd be embedded in the widget UX (or you could even hide everything and just show the confirmation buttons and text, simulating a dialog), but they would play nicer with widgets and it would also work in other frontends like jupyterlab.

**Comment by aa2858** [comment]
Uhmm, I will implement that to get this moved along. I have been in this rabbit hole for too long :-)

The following is my last attempt to get the async with JS working but still same issue :-

```python
self.launch_button.on_click(self.wait_for_confirmation)

async def _prompt_user(self, msg):
        bound = partial(self._display_prompt, msg)
        loop = asyncio.get_event_loop()
        try:
            await loop.create_task(self._display_prompt(msg))
        except Exception as exc:
            print(f'The coroutine raised an exception: {exc!r}')
        
        #print("end of display")

    def wait_for_confirmation(self, b):
        s_tab = self.tab.selected_index
        resp = {}
        global py_ans
        #global py_ans
        if s_tab == 0:
            msg = "You have selected to create " + str(self.emr_no_nodes.value) + " nodes[" +\
                    str(self.inst_type.value) + "] EMR cluster.  Click Continue to launch the cluster or Cancel to abort."
        elif s_tab == 1:
            msg = "You have selected to create " + str(self.no_of_dpu.value) + " DPUs." +\
                "  Click Continue to launch the cluster or Cancel to abort."
        loop = asyncio.get_event_loop()
        # task = loop.create_task(self._prompt_user(msg))
        task = loop.create_task(self._prompt_user(msg))
        print("task is", task)
        ip = get_ipython()
        print("ip global name for", ip.user_global_ns['py_ans'])

    async def _display_prompt(self, msg):
        
        display(Javascript("""
            require(["base/js/dialog"],
                function(dialog) {
                   // this.model.set('truthy truthy')
                    function processResult(answer){
                        var kernel = IPython.notebook.kernel;
                        // var callbacks = {'output' : handle_output};
                        var callbacks = {
                               iopub : {
                                        output : handle_output,
                                        }
                        }
                        var msg_id = kernel.execute('py_ans="' + answer + '";', callbacks, {silent:false});
                       // console.log(this.model.get('value'));
                        console.warn('got here ');
                        // console.warn(msg_id);
                    }
                    function handle_output(out_type, out){
                        console.log(out_type);
                        console.log(out);
                        var res = null;
                        // if output is a print statement
                        if(out_type == "stream"){
                            res = out.data;
                        }
                        // if output is a python object
                        else if(out_type === "pyout"){
                            res = out.data["text/plain"];
                        }
                        // if output is a python error
                        else if(out_type == "pyerr"){
                            res = out.ename + ": " + out.evalue;
                        }
                        // if output is something we haven't thought of
                        else{
                            res = "[out type not implemented]";   
                        }
                        document.getElementById("result_output").value = res;
                    }
                    var dialog_body = $('<div/>').append(
                        $("<p/>").addClass("rename-message")
                            .text('Enter a new filename:')
                    ).append(
                        $("<br/>")
                    ).append(
                        $('<input/>').attr('type','text').attr('size','25').addClass('form-control')
                        );
                    var d = dialog.modal({
                        title: 'Confirmation Page',
                        body: dialog_body,
                        default_button: "Cancel",
                        buttons: {
                            Continue: {
                                class: 'btn-primary',
                                click: function() {
                                    processResult(true);
                                   // return false;
                                }
                                
                            },
                            Cancel: {
                                class: 'btn-danger',
                                click: function() {
                                    processResult(false);
                                    // return false;
                                }
                                
                            }
                        }
                    });
                }
            );
            """ ))
```

The ip.user_global_ns['py_ans'] print shows immediately after the click.  Giving up on this.

**Comment by jasongrout** [comment]
> The ip.user_global_ns['py_ans'] print shows immediately after the click. Giving up on this.

Right. You're not awaiting the dialog box anywhere, wait_for_confirmation schedules the dialog box to show, then continues executing the next lines.

**Comment by jasongrout** [comment]
> I will implement that to get this moved along

Closing as resolved, then.
