### ISSUE TITLE
Change button on_click function at runtime

### ISSUE THREAD

**Issue by aa2858** [jupyter-widgets/ipywidgets#2412]
I am trying to call a different function for wigets.Button object at runtime but the original binding is being executed.

```
def fxn_1(b):
  print('fxn 1')

def fxn_2(b):
  print('fxn 2')

def fxn_3(b):
  print('fxn 3')


launch_button.on_clict(function_1)

if tab.selected_index == 0
  launch_button.on_clict(fxn_1)
elif tab.selected_index == 1:
  launch_button.on_clict(fxn_2)
elif tab.selected_index == 2:
  launch_button.on_clict(fxn_3)

```

My implementation is close to the above code snippet and it always execute fxn_1 for a reason which is not clear to me. I have looked at the documentation with no luck.

Any hint will be appreciated.

Thanks!

**Comment by andymcarter** [comment]
In the middle single line, should `launch_button.on_clict(function_1)` be `launch_button.on_clict(fxn_1)`?

**Comment by aa2858** [comment]
HI Andy, thanks for the response and I think your nudge did the trick.  I was able to discover the issue when I was trying to create a MCVE for you.  The re-wiring of the click might not be necessary since it is going to be after fact.  The following is the MCVE :-

```
from ipywidgets import widgets, VBox

def fxn_1():
    print("fxn 1")
    
    
def fxn_2():
    print("fxn 2")

def fxn_3():
    print("fxn 3")
    
def click_me(b):
    if tab.selected_index == 0:
        fxn_1()
    elif tab.selected_index == 1:
        fxn_2()
    elif tab.selected_index == 2:
        fxn_3()
        
launch_button = widgets.Button(
            description='Click me',
            button_style='info',
            disabled=False
)
launch_button.on_click(click_me)

label1 = widgets.Label(value='label 1')
label2 = widgets.Label(value='label 2')
label3 = widgets.Label(value='label 3')

tab1 = widgets.VBox(children=[label1])
tab2 = widgets.VBox(children=[label2])
tab3 = widgets.VBox(children=[label3])

tab = widgets.Tab(children=[tab1, tab2, tab3])

tab.set_title(0, '1')
tab.set_title(1, '2')
tab.set_title(2, '3')

main = widgets.VBox(children=[tab,launch_button]) 

main
```
This logic will do what I am trying to do and I am going to proceed with this and close this issue as well.

Thanks,
Adams

**Comment by aa2858** [comment]
Appreciate your help @andymcarter .
