### ISSUE TITLE
Create markdown widget

### ISSUE THREAD

**Issue by choldgraf** [jupyter-widgets/ipywidgets#2428]
I would like to create a ["Tab" widget](https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html#Tabs) where each tab contains markdown that I've generated. I saw that there is an [HTML widget](https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html#HTML), but I didn't see something similar for a Markdown widget. Is this possible in ipywidgets?

E.g., I'd like to do something like:

```python
tab_contents = ['# Heading 1\nMy awesome page', '# Heading 2\nMy awesome second page']
children = [widgets.<MarkdownWidgetIfItExists>(content=content) for content in tab_contents]
tab = widgets.Tab()
tab.children = children
for i in range(len(children)):
    tab.set_title(i, str(i))
tab
```

**Comment by SylvainCorlay** [comment]
At the moment, there is not widget to render markdown.

However, the `HTMLMath` widget renders Mathjax equations

```python
from ipywidgets import HTMLMath
HTMLMath(value='$\int f(s) ds$')
```

**Comment by DanielAristidou** [comment]
something as simple as 

```python
import markdown 
from ipywidgets import HTML

html = markdown.markdown("""# Markdown""")
HTML(html) 
```

should work.

**Comment by choldgraf** [comment]
I'm closing this because I think @DanielAristidou 's suggestion works nicely!
