### ISSUE TITLE
Error While Embedding Jupyter Widgets in Other Contexts than the Notebook

### ISSUE THREAD

**Issue by Pabla007** [jupyter-widgets/ipywidgets#2439]
I was trying to make my notebook run in the Nb-viewer with the interaction feature.
I was following this reference :
https://ipywidgets.readthedocs.io/en/latest/embedding.html#save-notebook-widget-state

This is the link of my code :
https://gist.github.com/Pabla007/408e02b9a646d89fdf98e6e3615afd1b

This is my error screenshot : 
![Screenshot from 2019-06-10 07-50-25](https://user-images.githubusercontent.com/35897183/59168719-96801180-8b54-11e9-913a-a7caec2169fb.png)

Due to this error the data is not linked with the output and as a result it is not rendered.
![Screenshot from 2019-06-10 07-54-36](https://user-images.githubusercontent.com/35897183/59168827-1908d100-8b55-11e9-9e0c-e4b824bf9511.png)

Can you tell me what is going wrong I google the error but i was not able to found any solution pointing to this error.

**Comment by vidartf** [comment]
I think I replied to this on stackoverflow :)
