### ISSUE TITLE
FloatText widget replaces values as Int 

### ISSUE THREAD

**Issue by denphi** [jupyter-widgets/ipywidgets#2444]
![FloatText](https://user-images.githubusercontent.com/17455636/59522611-1ed81c80-8e9d-11e9-8df6-af838a5e6209.gif)

Problem started after PR b42accc, FloatTextView inherits its event-handlers from IntTextView.

**Comment by DevFabrx** [comment]
This is a big issue for me because I need to insert floating point data. It is also not possible to write a decimal number using the keyboard because it will not let you type the decimal point.

**Comment by SylvainCorlay** [comment]
Thanks. This was just fixed in https://github.com/jupyter-widgets/ipywidgets/pull/2459.
