### ISSUE TITLE
Is there a way to generate a button with an href?

### ISSUE THREAD

**Issue by choldgraf** [jupyter-widgets/ipywidgets#2445]
I'm trying to generate a button that downloads data based on the content of other ipywidgets.

I know that I can just create my own `HTML(` widget with a link to that data, but I'd like the HTML widget's `href` to update automatically as people fill out other items in the page. If I create the button with hand-crafted HTML, then the link for the button will be static after I create it.

Is there a way I can attach an `href` to a button that automatically updates itself as other items in the page change?

**Comment by jasongrout** [comment]
You can update the HTML widget's content any time you like (just set the `value` attribute). Can you just generate new html and put it in there?

**Comment by choldgraf** [comment]
ah I see, so I'd use an onchange callback to update it? I bet that'd work
