### ISSUE TITLE
embed.embed_snippet caused KeyError: '\\u' in jupyterlab

### ISSUE THREAD

**Issue by hainm** [jupyter-widgets/ipywidgets#2454]
hi, 
Below simple code works ok with traditional notebook:

```
from ipywidgets import embed
from ipywidgets import Text
embed.embed_snippet([Text("hello")])
```

However, it causes error with the latest lab, 0.35.6 (I am using ipywidgets '7.4.2')
<img width="922" alt="Screen Shot 2019-06-22 at 12 23 07 AM" src="https://user-images.githubusercontent.com/4451957/59959376-07dc9000-9484-11e9-9001-ece8a6e8aeb7.png">

cheers

**Comment by vidartf** [comment]
Hi and thanks for the report. I suspect this might be a duplicate of https://github.com/jupyter-widgets/ipywidgets/issues/2277. Would you mind testing against master of ipywidgets?

**Comment by hainm** [comment]
> Would you mind testing against master of ipywidgets?

yeah, that fixes the issue. thanks.
