### ISSUE TITLE
Spec version number for Controls and Base

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter-widgets/ipywidgets#2466]
The current state of master in ipywidgets decouples the spec version from the module versions for the `base` and `control` packages.

- As pointed out by Vidar, this approach may be an issue in the case where these versions are used to fetch the package from a CDN.
- Jason said that in the case of Controls and Base, the packages are bundled with the manager so that it may not happen
- However, this makes a special case for these two packages.

We probably need to make a decision *today* to make a release of ipywidgets right after that of JupyterLab 1.0.

@vidartf @jasongrout

**Comment by jasongrout** [comment]
I think the version numbers should be decoupled generally, but have historically made the concession to convenience for other widgets packages that they could be coupled for the html manager. We already have other special cases for controls and base to experiment with ideas for 8.0, like that the spec version number is specified exactly in the messages, and then prepended with `^` on the client side.

Decoupling the version number means that ipywidgets 7.4 should work fine in jlab 1.0. I think that's important.

**Comment by vidartf** [comment]
I think the solution here is to keep the status quo, i.e. allow core packages to be decoupled, but additionally document this clearly. Probably we want to add this to
- docstrings
- docs
- examples
- cookiecutters

It could be the same string copy and pasted to all thos locations (with a slightly more verbose explanation in the docs). I don't think the docs should block the current release cycle, but should probably come not too long after.

**Comment by SylvainCorlay** [comment]
> I think the solution here is to keep the status quo

OK. The current state of master implements the status quo, but not the first RC.

I can make another RC before the end of the afternoon including Vidar's combobox PR.
