### ISSUE TITLE
[Classic notebook] Add event listener to window.resize for top-level Phosphor widgets

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter-widgets/ipywidgets#2467]
Jupyter Widget views are phosphor widgets.

When displayed in a classic notebook output area, they are not notified for window resize events.

We should probably update the widgetsnbextension to add these event listeners.

**Comment by SylvainCorlay** [comment]
cc @jasongrout @vidartf

**Comment by jasongrout** [comment]
Let's make sure this is happening.

**Comment by jasongrout** [comment]
@ibdafna is working on this at https://github.com/jupyter-widgets/ipywidgets/pull/3124

**Comment by jasongrout** [comment]
Fixed in #3124.
