### ISSUE TITLE
Description of the button is selectable

### ISSUE THREAD

**Issue by mbektasbbg** [jupyter-widgets/ipywidgets#2474]
When you click and drag over the mouse or double click over the text it becomes selected. It better be non-selectable like most other button implementations.

<img width="337" alt="Screen Shot 2019-07-01 at 5 10 08 PM" src="https://user-images.githubusercontent.com/40003442/60467009-55df5980-9c23-11e9-8d87-9edf04275412.png">

**Comment by SylvainCorlay** [comment]
Thanks @mbektasbbg ! A PR would be super welcome!
