### ISSUE TITLE
"after-show" event not triggered in classic

### ISSUE THREAD

**Issue by martinRenou** [jupyter-widgets/ipywidgets#2476]
The PhosphorJS "after-show" event is not triggered in classic Notebook. Is it something that could be fixed in ipywidgets? And is there a way around it?

**Comment by SylvainCorlay** [comment]
Probably related to #2467.

**Comment by martinRenou** [comment]
The "after-attach" seems to be triggered, so that's what I'm using now

**Comment by jasongrout** [comment]
Yes, we should make sure `after-show` is triggered in classic notebook.

**Comment by jasongrout** [comment]
Actually, according to [Phosphor/Lumino documentation](https://github.com/jupyterlab/lumino/blob/master/packages/widgets/src/widget.ts#L797), `after-show` is not triggered by attaching to the DOM. It's triggered by an explicit `.show` command on the phosphor widget. Were you expecting it to be triggered on attachment?

**Comment by jasongrout** [comment]
> Actually, according to [Phosphor/Lumino documentation](https://github.com/jupyterlab/lumino/blob/master/packages/widgets/src/widget.ts#L797), `after-show` is not triggered by attaching to the DOM. It's triggered by an explicit `.show` command on the phosphor widget. Were you expecting it to be triggered on attachment?

Closed as answered.
