### ISSUE TITLE
Button Icons/FontAwesome regression no longer supports fa-spin

### ISSUE THREAD

**Issue by rskabelund** [jupyter-widgets/ipywidgets#2477]
since this was added:
https://github.com/jupyter-widgets/ipywidgets/blob/master/ipywidgets/widgets/widget_button.py#L65-L73

we are no longer able to pass in additional fa classes to specify fa-spin or fa-lg etc.

I really liked my spinning gear icon button before this change...

i.e.
```
from ipywidgets import Button
Button(description='Running...', icon='fa-gear fa-spin fa-lg')
```

it will error on the add of the DOMTokenList due to the spaces in the string
https://github.com/jupyter-widgets/ipywidgets/blob/master/packages/controls/src/widget_button.ts#L91

**Comment by rskabelund** [comment]
Running on ipywidgets 5.2.2
![fontawesomebutton](https://user-images.githubusercontent.com/18313265/60558652-d32bcc80-9cfe-11e9-9f6f-90ce2c839ff9.gif)

**Comment by rskabelund** [comment]
@jasongrout what would be the path forward to allow multiple font awesome parameters?  Are there existing accommodations for this that I am missing?

**Comment by kebwi** [comment]
I was just wishing yesterday for multiple icons on a button and found this discussion. The implication is that it used to work and such behavior was explicitly removed? Why not leave it in and let the user decide if they find multiple icons useful? I could use it frankly.

Thanks.

**Comment by rskabelund** [comment]
@kebwi I ended up creating a custom widget for my purposes using the ipywidgets cookiecutter template.  But, yeah, disappointed this support is no longer available with little explanation why.

**Comment by rskabelund** [comment]
Here is an example custom font awesome button:

```
from traitlets import Unicode, Bool, validate, TraitError, Any
from ipywidgets import DOMWidget, register

@register
class FaButton(DOMWidget):
    _view_name = Unicode('FaButtonView').tag(sync=True)
    _view_module = Unicode('fabutton_widget').tag(sync=True)
    _view_module_version = Unicode('0.1.0').tag(sync=True)

    # Attributes
    description = Unicode('ww', help="Button Text").tag(sync=True)
    icon = Unicode('fa-cloud-download', help="Font Awesome String").tag(sync=True)
    disabled = Bool(False, help="Enable or disable button").tag(sync=True)
    callback_event = Any().tag(sync=True)
```

```
%%javascript
require.undef('fabutton_widget');

define('fabutton_widget', ["@jupyter-widgets/base"], function(widgets) {

    var FaButtonView = widgets.DOMWidgetView.extend({

        // Render the view.
        render: function() {
            this.btn = document.createElement('button');            
            this.btn.setAttribute("class", "jupyter-button widget-button");
            
            this.update_text();
            
            this.el.appendChild(this.btn);
            
            this.el.setAttribute("class", "widget-html-content");
            
            // Python -> JavaScript update
            this.model.on('change:icon', this.update_text, this);
            this.model.on('change:description', this.update_text, this);

        },

        events: {
            // List of events and their handlers.
            'click': 'handle_click'
        },   
        
        handle_click: function() {
            if (event.target.tagName == 'BUTTON') {
                this.model.set('callback_event', {'target':event.target.innerHTML, 'data':event.target.dataset, 'type': 'button_click' , 'name':event.originalEvent , 'timeStamp':event['timeStamp']}); 
                this.touch();
            }
        },

        update_text: function() {
            this.btn.innerHTML = '<i class="fa ' + this.model.get('icon') + '" aria-hidden="true"></i>' + this.model.get('description');
        },

    });

    return {
        FaButtonView: FaButtonView
    };
});
```

```
def handle_btn_click_callback(e):
    print('hello from custom btn widget')
    
    
btn = FaButton(icon='fa-spin fa-gear', description = 'Hello')
btn.observe(handle_btn_click_callback, 'callback_event')
display(btn)
```

**Comment by kebwi** [comment]
Hmmm. Thanks. I admit, I've haven't delved into custom widgets yet. I guess it's time to roll up my sleeves.

**Comment by martinRenou** [comment]
I'll try to have a look at this issue tomorrow

**Comment by martinRenou** [comment]
PR opened https://github.com/jupyter-widgets/ipywidgets/pull/2685

@kebwi Please note that this PR does not add support for multiple icons in a Button. It is only fixing the regression that appeared in 6.0, allowing: 
- spinning icons
- larger icons
Which I understand is the original issue here. Maybe we could open another issue for multiple icons support?
