### ISSUE TITLE
"Explore Random Graphs Using NetworkX" shows error

### ISSUE THREAD

**Issue by sazzadurrahman** [jupyter-widgets/ipywidgets#2479]
I have tried Explore Random Graphs Using NetworkX example, but it shows the following error:

"AttributeError: module 'matplotlib.pyplot' has no attribute 'ishold'"

Do I need to import other modules?

**Comment by pbugnion** [comment]
Thanks for raising this.

I've tested this on ipywidgets 7.5, matplotlib 3.1.1, networkx 2.4 and both Jupyter notebook and JupyterLab, and had no issues. Is this still not working for you?

Closing this, but feel free to re-open if  you think the issue persists.
