### ISSUE TITLE
FileUpload counter with multiple=False

### ISSUE THREAD

**Issue by jtpio** [jupyter-widgets/ipywidgets#2480]
It looks a bit odd that the `FileUpload` counter is increasing every time a file is uploaded, even when `multiple=False` is set:

![fileupload-counter](https://user-images.githubusercontent.com/591645/60599735-42f99000-9daf-11e9-8fd0-d1d52965b229.gif)

When `multiple=False` is set shouldn't the counter equal to 1?

Can be tested with:

```python
from ipywidgets import FileUpload, Output

out = Output()

@out.capture()
def show_content(change):
    print(change['new'].keys())

w = FileUpload(multiple=False)
w.observe(show_content, 'value')
with out:
    display(w)
out
```

**Comment by dadamson** [comment]
I'm also wondering about this -- even when `multiple=True`, the counter _increments_ after each upload (even though the new `value` only contains the most recent set of uploaded files), and there doesn't seem to be a way to reset it (in a callback, for example) after processing the files.
![Screenshot 2019-10-31 10 04 12](https://user-images.githubusercontent.com/4378846/67953630-df00a000-fbc5-11e9-8d2d-5905fe4d2ef1.png)

How can we reset the counter?

**Comment by JmiXIII** [comment]
Hello,

Facing the same issue, is there any workaround to reset the widget ?
