### ISSUE TITLE
Does latest ipywidgets support jupyterlab v1.0 yet?

### ISSUE THREAD

**Issue by hainm** [jupyter-widgets/ipywidgets#2483]
Hi,
I gave it a try for nglview and pythreejs but getting below error:

<img width="1278" alt="Screen Shot 2019-07-05 at 1 39 36 AM" src="https://user-images.githubusercontent.com/4451957/60700394-c6a5a080-9ec5-11e9-8f9c-bd59b7a49c8f.png">

Here is further info:
```
 jupyter-labextension list
JupyterLab v1.0.1
Known labextensions:
   app dir: /Users/haichit/miniconda3/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.0.0  enabled  OK
        jupyter-matplotlib v0.3.0  enabled  OK
        jupyter-threejs v2.1.0  enabled  OK
        jupyterlab-datawidgets v6.1.0  enabled  OK
        nglview-js-widgets v2.5.1  enabled  OK*
```

thanks and cheers.

**Comment by jasongrout** [comment]
Yes, ipywidgets supports JLab 1.0. custom widgets need to updated to support JLab 1.0, though. See https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/changelog.md#updates-for-widget-maintainers

**Comment by hainm** [comment]
thanks. I will give it a try now.

**Comment by hainm** [comment]
@jasongrout I might not follow the instruction correctly.
Here is what I did
- Update the package.json
```
-    "@jupyter-widgets/base": "^1.0.0"
+    "@jupyter-widgets/base": "^1.1 || ^2"
```
- Rerun: `jupyter-labextension install ./js/` (in nglview root folder)
- Reopen jupyterlab, but I am getting the same error.

**Comment by jasongrout** [comment]
Your other widget extensions also need to be updated.

**Comment by hainm** [comment]
What do you mean about "Your other"? I only develop `nglview`. Do you mean I need to uninstall `jupyter-pythreejs` (for example) if I want to get rid of the issue? :D

**Comment by hainm** [comment]
OMG, that's true. I need to uninstall any extensions that don't follow the rule (yet). Thanks for your help (as always)

<img width="1268" alt="Screen Shot 2019-07-05 at 2 15 02 AM" src="https://user-images.githubusercontent.com/4451957/60701735-b93ee500-9eca-11e9-81aa-9321eaa7fcc4.png">

**Comment by flekschas** [comment]
Thanks for figuring that out! Any chance this information could be added somewhere in the docs? It could save a lot of people time when they run into this issue (like myself).

**Comment by jasongrout** [comment]
Do you have some text and location in the docs you are proposing?

**Comment by jasongrout** [comment]
i.e., what would have helped you and where would you have looked for it?

**Comment by flekschas** [comment]
Sorry, I should have been more precise. I was just thinking it might be nice to mention at https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/changelog.md#updates-for-widget-maintainers that *all third-party plugins have to be updated* to avoid the issue. Not critical though.
