### ISSUE TITLE
ComboBox floats away

### ISSUE THREAD

**Issue by mrinalraghupathi** [jupyter-widgets/ipywidgets#2486]
When I use the new combobox widget and I start to type I get the completion list. If I scroll the notebook while this list is open, the dropdown stays fixed and floats away from the text input.

![image](https://user-images.githubusercontent.com/864553/60792914-6d36af00-a11b-11e9-968d-876e517b63bd.png)

Also, if I type text it makes the choices in the dropdown shorter (narrows the list). If I then delete text it doesn't expand the list. Not sure if this is expected or not. It only seems to be an issue when you type one character and then delete. If you type 2 characters and then delete one the list expands again.

*Start*

![image](https://user-images.githubusercontent.com/864553/60793036-b25ae100-a11b-11e9-9c3c-f6c4f7181b0c.png)

*Type*

![image](https://user-images.githubusercontent.com/864553/60793117-e0402580-a11b-11e9-93e8-409a43009850.png)

*Delete*

![image](https://user-images.githubusercontent.com/864553/60793152-f0580500-a11b-11e9-8995-53e0644003ed.png)

**Code**

```python
import ipywidgets as widgets
w = widgets.Combobox(options=['Chicago', 
                              'New York', 
                              'San Francisco', 
                              'Jakarta', 
                              'Rhode Island'])
w
```

**Comment by vidartf** [comment]
The comobobox widget uses the browser implementation of a combobox (using the HTML5 tag `<datalist>`). As such, it is important to know which browser you are seeing these issues with, or if they are reproducible across all browsers.

**Comment by mrinalraghupathi** [comment]
Google Chrome: Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by vidartf** [comment]
Just tested this locally. I can reproduce, with some further observations:
- The problem of the suggestion update on character deletion only seems to happen when the field becomes empty (e.g. from 1 to 0 characters, but not from 2 to 1, or 3 to 2).
- When scrolling away from the combobox (such that it becomes misaligned), it will subsequently be realigned after a scroll event that I didn't generate.

I'll try to look further into this.

**Comment by vidartf** [comment]
Note: This seems to be general problems for the `datalist` tag on Chrome, see e.g. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist .

Firefox has a different behavior.

The forced scroll seems weird, but might be a lab issue...

**Comment by jasongrout** [comment]
Since we don't control the placement or how the filtering works, I don't think there is anything we can do here. It sounds like a browser issue, like @vidartf implied.
