### ISSUE TITLE
Save widget state with nbconvert?

### ISSUE THREAD

**Issue by choldgraf** [jupyter-widgets/ipywidgets#2493]
Papermill is really useful for generating notebook reports from notebooks that have lots of widgets in them. There is a JupyterLab setting to save the widget state from a notebook so that they'll show up in nbviewer etc, but is something like this possible with Papermill? (or more generally with nbconvert etc?)

**Comment by choldgraf** [comment]
Thinking about this more, I don't think that this is a papermill issue, but an nbconvert issue (since nbconvert is what papermill uses). It should be possible for the saving behavior of nbconvert to be the same as the saving behavior of jupyterlab - is that currently the case?

Otherwise, how do people programmatically generate notebooks that use widgets?

**Comment by mgeier** [comment]
If I understand your question correctly, this has been implemented in https://github.com/jupyter/nbconvert/pull/900.

**Comment by maartenbreddels** [comment]
Indeed, this is implemented.
