### ISSUE TITLE
"Error creating widget: could not find model"

### ISSUE THREAD

**Issue by mayadebellis** [jupyter-widgets/ipywidgets#2494]
Hi - I have created an extension in jupyterlab that creates an interactive widget in a notebook. I am having an issue where when I reopen/reload a notebook the interactive widget is gone an in it's place is the message "Error creating widget: could not find model". My extension was created with the [widget-ts-cookiecutter](https://github.com/jupyter-widgets/widget-ts-cookiecutter)

It seems other people have had this issue in the past but I can't find a solution. 
https://github.com/matplotlib/jupyter-matplotlib/issues/38
https://github.com/jupyter-widgets/ipywidgets/issues/2125

I am using JupyterLab v0.35.3 and  @jupyter-widgets/jupyterlab-manager v0.38.1.

Are there any solutions?

**Comment by metya** [comment]
the same with tqdm

**Comment by jasongrout** [comment]
Upgrade to 1.0, which implements the fix.
