### ISSUE TITLE
CSS class 'jupyter-widgets' should not appear node 'jp-OutputArea-output'

### ISSUE THREAD

**Issue by qzchenwl** [jupyter-widgets/ipywidgets#2499]
| package | version |
| ---          | ---        |
| jupyterlab | 1.0.2 |
| jupyterlab-manager | 1.0.1 |

When customizing my own widget, I need to calculate the output area width. If the node 'jp-OutputArea-output' has css attribute 'overflow: visible', I cannot get the correct width.

And there's no means to change css attribute of node 'jp-OutputArea-output', because it's my parent node.

Without 'jupyter-widgets' class, the node 'jp-OutputArea-output' has css attribute 'overflow: auto' which is fine.

![image](https://user-images.githubusercontent.com/146802/61178909-37695d00-a62a-11e9-88d1-44e921798825.png)

**Comment by jasongrout** [comment]
Closed by #2500.
