### ISSUE TITLE
Errors/warning during installing widgets for JupyterLab 0.35

### ISSUE THREAD

**Issue by scottwsides** [jupyter-widgets/ipywidgets#2501]
I'm getting the following error messages when installing widgets for JupyterLab v. 0.35 It seems to work on my local machine, but I'm seeing problems in a remote container. I wanted to be sure that these error messages aren't causing problems when trying to setup remotely. Thanks!   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │       New minor version of npm available! 6.4.1 → 6.10.1       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.10.1   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

Failed to fetch package metadata for 'jupyterlab_iframe': URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)'))
Failed to fetch package metadata for 'jupyterlab_iframe': URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)'))

Errored, use --debug for full output:
ValueError: No version of jupyterlab_iframe could be found that is compatible with the current version of JupyterLab.

Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.19.1 <0.20.0        >=1.0.0 <2.0.0   @jupyterlab/application
>=0.19.1 <0.20.0        >=1.0.0 <2.0.0   @jupyterlab/apputils
>=2.2.1 <3.0.0          >=3.0.0 <4.0.0   @jupyterlab/coreutils
>=0.19.1 <0.20.0        >=1.0.0 <2.0.0   @jupyterlab/docmanager

**Comment by pbugnion** [comment]
Thanks for raising this, and apologies for the late reply.

It looks like you're missing a certificate chain for talking to npmjs in your container. I would recommend starting from [one of the officially supported Docker images](https://jupyter-docker-stacks.readthedocs.io/en/latest/).

I'm closing this since it refers to an outdated JupyterLab and an outdated widget manager for JupyterLab.

Feel free to re-open if the issue still arises on JupyterLab 1.x.
