### ISSUE TITLE
Displaying ANSI escape characters in widgets

### ISSUE THREAD

**Issue by romain-intel** [jupyter-widgets/ipywidgets#2508]
Is there a way to display ANSI escape sequences properly in widgets?

I have some code which used the ```colored``` method from the ```termcolor``` library to insert ANSI escape sequences do to things like adding color, underline, bold, etc and I used ```print``` to display the output text, for example: ```print(colored('This is red', color='red'))```. This works fine and outputs the text with the proper color.

However, I cannot seem to get this output in a widget like a Text widget. I can obviously use HTML instead to add the color but I was wondering if there was an easier way to take ANSI escaped text and allow it to be put into widgets.

**Comment by jasongrout** [comment]
You could use an output widget.

**Comment by romain-intel** [comment]
That was exactly what I was looking for. Brilliant and thank you!
