### ISSUE TITLE
RadioButton with options having the same value

### ISSUE THREAD

**Issue by bbettss** [jupyter-widgets/ipywidgets#2513]
```python
import ipywidgets as widgets
# widgets.__version__ == 7.2.1

colors = [["red",1], ["blue",2] ,["green",3], ["yellow",2]]
blob = widgets.RadioButtons(options=colors)
blob
```
For example selecting "yellow", it will automatically change the selected option to "blue". It picks the lowest indexed option with the same value. To actually select "yellow" a second click is needed.

Is this the intended behavior? If not, it would be real neat if options with different labels and the same values was supported.

**Comment by jasongrout** [comment]
Does it work in widgets 7.5?

**Comment by jasongrout** [comment]
(It should work - it should be based on the index, not the value)

**Comment by jasongrout** [comment]
I confirmed that the same issue exists in ipywidgets 7.5. The radio buttons are correctly labeled by index. My guess is that this is some weird interaction with the validation logic in python.

**Comment by jasongrout** [comment]
Indeed, setting it programmatically also doesn't work:

```python
blob.index=3
```

**Comment by maartenbreddels** [comment]
I think this fix is hidden in an old PR from me: https://github.com/jupyter-widgets/ipywidgets/pull/2232

More specifically, this commit: https://github.com/jupyter-widgets/ipywidgets/pull/2232/commits/5c40113efb58eeafa31ea7edde4ac819f4fce148

**Comment by jasongrout** [comment]
This is the radio button, not the toggle button. And it does appear that the HTML correctly uses the index, not the value.

My guess is still that it is an interaction on the python side with the validation code that sets the `.value`, etc., from the index change.

**Comment by jasongrout** [comment]
Indeed, looking at the websocket messages, I first see the correct index 3 going from the browser to the kernel, then I see the incorrect index 1 coming back from the kernel to the browser. So something in the python code is taking that index 3 change and resetting it to index 1.
