### ISSUE TITLE
Jupyter and Ipywidgets up to date, yet ImportError: IntProgress not found. Please update jupyter and ipywidgets. 

### ISSUE THREAD

**Issue by janPesl** [jupyter-widgets/ipywidgets#2527]
Hello,

I have been getting this error when trying to use Tpot library in a jupyter notebook.

**tpot.TPOTClassifier.fit(x_train, y_train)**
```

Warning: xgboost.XGBClassifier is not available and will not be used by TPOT.
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/usr/local/lib/python3.7/site-packages/tqdm/_tqdm_notebook.py in status_printer(_, total, desc, ncols)
    102             if total:
--> 103                 pbar = IntProgress(min=0, max=total)
    104             else:  # No total? Show info style bar with no progress tqdm status

NameError: name 'IntProgress' is not defined

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-7-c5de40c7b1e7> in <module>
----> 1 tp.fit(x_train, y_train)

/usr/local/lib/python3.7/site-packages/tpot/base.py in fit(self, features, target, sample_weight, groups)
    733 
    734         self._pbar = tqdm(total=total_evals, unit='pipeline', leave=False,
--> 735                           disable=not (self.verbosity >= 2), desc='Optimization Progress')
    736 
    737         try:

/usr/local/lib/python3.7/site-packages/tqdm/_tqdm_notebook.py in __init__(self, *args, **kwargs)
    210         # Replace with IPython progress bar display (with correct total)
    211         self.sp = self.status_printer(
--> 212             self.fp, self.total, self.desc, self.ncols)
    213         self.desc = None  # trick to place description before the bar
    214 

/usr/local/lib/python3.7/site-packages/tqdm/_tqdm_notebook.py in status_printer(_, total, desc, ncols)
    109             # #187 #451 #558
    110             raise ImportError(
--> 111                 "IntProgress not found. Please update jupyter and ipywidgets."
    112                 " See https://ipywidgets.readthedocs.io/en/stable"
    113                 "/user_install.html")

ImportError: IntProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
```

I have followed the ipywidgets installation instructions (https://ipywidgets.readthedocs.io/en/stable/user_install.html), updated conda, but despite all the effort this problem still remains.

The jupyter version:
```
jupyter core     : 4.5.0
jupyter-notebook : 6.0.0
qtconsole        : 4.5.2
ipython          : 7.6.1
ipykernel        : 5.1.1
jupyter client   : 5.3.1
jupyter lab      : 1.0.4
nbconvert        : 5.5.0
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.2
```
Thank you in advance for any suggestions how to get around this!

**Comment by jasongrout** [comment]
Can you file the issue with tqdm? It seems that is the library generating the error. https://github.com/tqdm/tqdm

**Comment by jasongrout** [comment]
And you can double-check that ipywidgets is working fine by trying to import that yourself:

```
from ipywidgets import IntProgress
```

**Comment by janPesl** [comment]
> And you can double-check that ipywidgets is working fine by trying to import that yourself:
> 
> ```
> from ipywidgets import IntProgress
> ```

Thanks! That is a really good hint! I cannot import it.
```---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-715f981b17d8> in <module>
----> 1 from ipywidgets import IntProgress

ModuleNotFoundError: No module named 'ipywidgets'
```

Any idea how to make ipywidgets available in the jupyter notebook?

**Comment by hainm** [comment]
Check the last line of your 1st post: there is a link to show how.

**Comment by hainm** [comment]
ImportError: IntProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html

**Comment by janPesl** [comment]
> ImportError: IntProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html

Hi! Thanks for commenting! This is exactly why I was raising the issue in the first place. Check my jupyter version against the current changelogs. All seems to be up to date. 

Even though I can import the IntProgress, it still returns the error...

**Comment by hainm** [comment]
I replied to your question about ipywidgets 

> Any idea how to make ipywidgets available in the jupyter notebook?

**Comment by PatAlbright** [comment]
> 
> 
> > ImportError: IntProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
> 
> Hi! Thanks for commenting! This is exactly why I was raising the issue in the first place. Check my jupyter version against the current changelogs. All seems to be up to date.
> 
> Even though I can import the IntProgress, it still returns the error...

Have you been able to resolve this issue? :) 

I face the exact same problem.

**Comment by eeegnu** [comment]
> > > ImportError: IntProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
> > 
> > 
> > Hi! Thanks for commenting! This is exactly why I was raising the issue in the first place. Check my jupyter version against the current changelogs. All seems to be up to date.
> > Even though I can import the IntProgress, it still returns the error...
> 
> Have you been able to resolve this issue? :)
> 
> I face the exact same problem.

pip install --upgrade jupyter_client resolved this problem for me.

**Comment by shehroz010** [comment]
Run these commands for conda

conda install -n base -c conda-forge widgetsnbextension
conda install -n py36 -c conda-forge ipywidgets

**Comment by morawi** [comment]
> from ipywidgets import IntProgress

I can do the import, but still having the same mentioned error when I run this PyTorch code:
`model = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True)`

**Comment by AhmadQatamesh** [comment]
I had the same issue FloatProgress not found. i applied all the solutions above and one of them worked, only after I Restarted my Jupyetr notebook. since it's an extension as it seems.
