### ISSUE TITLE
Using Interact demo cell 32 not showing

### ISSUE THREAD

**Issue by mtlam** [jupyter-widgets/ipywidgets#2529]
In https://ipywidgets.readthedocs.io/en/latest/examples/Using%20Interact.html, which pulls from docs/source/examples/Using%20Interact.ipynb, the last code cell, #32, fails on "%matplotlib inline", causing that demo to fail.

**Comment by pbugnion** [comment]
Thanks for raising this!

This is working now, so I'll close this issue. Feel free to re-open if you see other issues.
