### ISSUE TITLE
Output does not display a widget correctly?

### ISSUE THREAD

**Issue by hainm** [jupyter-widgets/ipywidgets#2530]
Hi all,

please see screenshot below. I thought the `Text("hello")` should be displayed in the previous cell.
Is this a bug?

![output](https://user-images.githubusercontent.com/4451957/62643375-d9bced80-b915-11e9-8d23-080aa4b27666.png)

**Comment by hainm** [comment]
```
with out:
    display(ipywidgets.Text("today is nice"))
```
works as expected.

**Comment by jasongrout** [comment]
This is https://github.com/jupyter-widgets/ipywidgets/issues/1811 - see that issue for further discussion of the current technical limitation causing this.

**Comment by hainm** [comment]
thanks, I should search 'append_display_data' in the issue before asking. :D
