### ISSUE TITLE
'Style not applied because a parent view does not exist' on Chrome, Google Colab, 

### ISSUE THREAD

**Issue by safak17** [jupyter-widgets/ipywidgets#2539]
I am using Google Colab Jupyter Notebook on Chrome. The styles and layouts of the widgets are not updating. Nothing changes! 

```python
import ipywidgets as widgets
from ipywidgets import *
from IPython.display import display
```

```python
b1 = widgets.Button()
b2 = widgets.Button()

AppLayout(left_sidebar = b1,
          right_sidebar = b2)
```

Here is what I get as the output on Google Colab Jupyter Notebook.
![image](https://user-images.githubusercontent.com/16006127/63561607-4285a600-c563-11e9-9080-d807913c94e7.png)

And this is the Chrome console output.
![image](https://user-images.githubusercontent.com/16006127/63561611-487b8700-c563-11e9-8f30-ea1d41f1a79f.png)

How can I solve this?

**Comment by jasongrout** [comment]
CC @blois, who works on colab.

(This issue is probably better filed on the google colab repo: https://github.com/googlecolab/colabtools)

**Comment by vidartf** [comment]
Closing this then :)
