### ISSUE TITLE
Creating new Widgets based on the Multiple Selection!

### ISSUE THREAD

**Issue by moradza** [jupyter-widgets/ipywidgets#2547]
I have a multiple selections widget, each time the user selects new options from the MultipleSelection widget, I want to display new floatslider widgets with the  selected options.

Is it possible?

Thanks,

**Comment by pbugnion** [comment]
Unless I'm mistaken, this is a duplicate of #2551. I'm closing this one, but feel free to re-open if you think it's a distinct issue.
