### ISSUE TITLE
ipywidgets not working with jupyterlab 1.0

### ISSUE THREAD

**Issue by scottwsides** [jupyter-widgets/ipywidgets#2552]
I install with 

pip install jupyterlab==1.0
pip install ipywidgets=7.5

I enable the widgets manager with
   jupyter labextension install @jupyter-widgets/jupyterlab-manager

Then do a 
   jupyter lab build --name='Chemistream'

Then I check with:
(chemistream-env) phoenix:chemistream swsides$ jupyter labextension list
JupyterLab v1.0.0
Known labextensions:
   app dir: /Users/swsides/hpccloud-trunk/chemistream/chemistream-env/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.0.2  enabled  OK
        jupyter-threejs v2.0.3  enabled  OK
        jupyterlab-datawidgets v6.2.0  enabled  OK

But my widgets in a notebook like sliders and progress bars are giving the "Error displaying widget" message. This all worked with jupyterlab==0.35.5 and ipywidgets==7.4.2.

Can ipywidgets work with newer versions of jupyterlab?

**Comment by hainm** [comment]
have you done `jupyter nbextension enable --py --sys-prefix widgetsnbextension` yet?

**Comment by scottwsides** [comment]
Ah, I left that out. I had this in when I was using jupyterlab==0.35.5, but I thought it was related to some other extensions. The extensions seem to build fine (see below)

---------------------------------------------------------------------------------------
Installing jupyter-widgets manager

Building jupyterlab assets
Installing jupyter nbextension
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
Done: Installing jupyter nbextension

Building JupyterLab with --name=Chemistream
[LabBuildApp] JupyterLab 1.0.0
[LabBuildApp] Building in /Users/swsides/hpccloud-trunk/chemistream/chemistream-env/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets
Done: building JupyterLab with name
------------------------------------------------------------------------------------------

However, displaying widgets still fails. I've tried specifying the version number for widget manager version and leaving it off and I get the same results. I'm sorta counting on widgets working for jupyterlab going forward with a big project. If widgets only work for 0.35.5 I'm going to have to do some rethinking. 

Are there flags I can give to the extension configuration to get more debug info?

The zoo of extension commands that are out there are confusing. Is there some logic to what extension commands provide what functionality?

Thanks!

**Comment by hainm** [comment]
@scottwsides May be try with a clean conda env?
Here is the binder recipe that works pretty well (see `environment.yml` and `postBuild`)
https://github.com/hainm/nglview-binder/tree/master/binder

**Comment by hainm** [comment]
![lab](https://user-images.githubusercontent.com/4451957/64446285-6e964080-d0a6-11e9-85db-699e1dd38797.png)

**Comment by scottwsides** [comment]
Ah. I'm using pip installs for ipywidgets and jupyterlab. Maybe pip versions aren't as well maintained? Also, the extra extension commands are not necessary with conda installed versions?

**Comment by hainm** [comment]
> Also, the extra extension commands are not necessary with conda installed versions?

most of them will be done by conda (through the package's recipe).

> Maybe pip versions aren't as well maintained? 

pip version works fine if you correctly do it. But I would avoid install jupyterlab from pip.

**Comment by scottwsides** [comment]
I'm in the process of switching over to conda from pip for my larger project. After trying a number of combinations of different instructions from the ipywidgets GitHub the following works. 


- Assuming inside an activated miniconda3 environment running python 3.7.1
- conda install -y -c conda-forge nodejs
- conda install -y -c conda-forge ipywidgets
- conda install -y -c conda-forge jupyterlab
- jupyter labextension install @jupyter-widgets/jupyterlab-manager

<img width="414" alt="Screen Shot 2019-09-06 at 12 19 35 PM" src="https://user-images.githubusercontent.com/13578795/64451071-a9957580-d0a0-11e9-9b0c-959b67c4d95a.png">



Understood about pip. Curious about pip not working with new jupyterlab, because the same procedure was working with an older version and I'm following the online help.

**Comment by jasongrout** [comment]
pip should work just as well as conda. The one big difference is that you can install nodejs using conda, and if you are using pip you'll need nodejs installed some other way to install jupyterlab extensions.

**Comment by scottwsides** [comment]
Yes. For the older jupyterlab version I was mixing nodejs from conda and ipywidgets, jupyterlab from pip. This is messy but it happen to work (nodejs from pip had problems I could never solve). pip *should* work... but for me it didn't. When I took a procedure that worked for jupyterlab==0.35.5 and then substituted jupyterlab==1.0.0 things definitely break. 

Again, I'm in the process of migrating from pip environments --> to conda tools for building and installing. This seems to be a good way to go for a number of reasons. Only one of these reasons is that I can't get jupyterlab >=1.0.0 to work any other way.

**Comment by jasongrout** [comment]
Great. Closing as resolved, then. Feel free to continue commenting if you need anything more.
