### ISSUE TITLE
Drop python 2 support

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#2554]
Python 2 has [end-of-life on January 1, 2020](https://www.python.org/doc/sunset-python-2/). Accordingly, a few of us feel that we should make an 8.0 ipywidgets release that moves to Python 3 only before then.

**Comment by vidartf** [comment]
I agree. Let's use this issue as a tracker for things to refactor as a part of that switch. E.g. "change this API to use async generator"; "change this internal code to cleanup bytestring/unicode use", etc.

**Comment by hugovk** [comment]
Please see PR https://github.com/jupyter-widgets/ipywidgets/pull/2558 to take care of some of this.
