### ISSUE TITLE
Move to conda-forge noarch package

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#2555]
If we haven't moved to a noarch package on conda-forge yet, we should complete the migration by 8.0.

See https://github.com/conda-forge/widgetsnbextension-feedstock/issues/52

**Comment by jasongrout** [comment]
I did this in the prerelease widgetsnbextension package: https://github.com/conda-forge/widgetsnbextension-feedstock/pull/58. Leaving this open until the main package moves to noarch, though.

**Comment by mwcraig** [comment]
`ipywidgets` has been done, see https://github.com/conda-forge/ipywidgets-feedstock/blob/master/recipe/meta.yaml#L13 but `widgetsnbextension` has not been done yet on the main branch https://github.com/conda-forge/widgetsnbextension-feedstock/blob/master/recipe/meta.yaml#L11

**Comment by davidbrochart** [comment]
I opened https://github.com/conda-forge/widgetsnbextension-feedstock/pull/65.

**Comment by jasongrout** [comment]
This is currently done in the prerelease conda-forge package, so should Just Work when we release the next major version.
