### ISSUE TITLE
Video widget doesn't display video - codec problem?

### ISSUE THREAD

**Issue by kartoshhka** [jupyter-widgets/ipywidgets#2559]
Hello!

I discovered that Video widget can't open .mp4 file that I made with cv2.VideoWriter.

Here's some code:

```
cam1 = cv2.VideoCapture('test.mp4')
s = cam1.isOpened()
print(s)

frames = []
total = int(cam1.get(cv2.CAP_PROP_FRAME_COUNT))
print(total)
for i in range(total) :
        _, frame = cam1.read()
        fgmask = cv2.Canny(frame, 100, 100)
        mask = fgmask > 100
        frame[mask, :] = 0

        frames.append(frame)

width = int(cam1.get(3))
height = int(cam1.get(4))

filename = 'output.mp4'

fourcc = cv2.VideoWriter_fourcc('V','M','P','4')
writer = cv2.VideoWriter(filename, fourcc, 30, (width, height))

for frame in frames:
    writer.write(frame)
```
This lines create **output.mp4** file that can be opened with some videoplayer (e.g. VLC), but when I try to view it in the Jupyter, I get this (it can't be played and doesn't do anything):

![image](https://user-images.githubusercontent.com/41269229/65339482-e9964580-dbd4-11e9-85a6-0963efbb1eb0.png)

I suppose problem may be in video codec. Is there some codec that should be used?

Thanks!

**Comment by jasongrout** [comment]
The video widget merely exposes the data to your web browser's `<video>` element, so you'd need to pick a codec, etc., that your browser supports.

**Comment by kartoshhka** [comment]
@jasongrout Thank you very much! After some searching I've discovered that VP90 codec is working with Jupyter running on Chrome.
![image](https://user-images.githubusercontent.com/41269229/65878131-f9144c00-e395-11e9-8ccf-eefdab3e53f2.png)

**Comment by jasongrout** [comment]
Keep in mind if all you are doing is displaying a video file, and you don't need to interactively change it or hook it up to other widgets, it's probably better to use the IPython.display.Video rich display:

https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.Video

```python
from IPython.display import Video
Video('./output.mp4')
```

**Comment by SylvainCorlay** [comment]
Although the widget will use binary serialization while the Video output will base64 encode it :)

**Comment by jasongrout** [comment]
I think it uses binary encoding by default (i.e., a link and a file get), unless you pass the embed=True option. See the docs: https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.Video
