### ISSUE TITLE
How to best implement comm_info_request/comm_info_reply message?

### ISSUE THREAD

**Issue by captainsafia** [jupyter-widgets/ipywidgets#2562]
I'm currently working on exploring the messages that are exchanged for a simple widget in a notebook. I've created the notebook (attached) with a single `IntSlider`. One of the things I noticed is that when the notebook launches, the following `comm_info_request` is sent to the kernel.

```
{"header":{"msg_id":"d50522c862e540e094c627a35cd86833","username":"username","session":"857776f10f7c46c783bc1855977da954","msg_type":"comm_info_request","version":"5.2"},"metadata":{},"content":{"target_name":"jupyter.widget"},"buffers":[],"parent_header":{},"channel":"shell"}
```

The [protocol docs](https://jupyter-client.readthedocs.io/en/stable/messaging.html#comm-info) state that this message is sent when the client needs information about the comms currently opened by the kernel.

My question is: should this message be sent only once? What is the correct approach to using this message in an ipywidgets implementation?

**Comment by jasongrout** [comment]
The point is that when a page is refreshed, we want to reconstruct any active widgets on the page. So the first thing when starting up is to ask the current kernel what comms it has open, so we can reconstruct the appropriate widgets.

**Comment by jasongrout** [comment]
For example, here is the relevant code in the jlab manager: https://github.com/jupyter-widgets/ipywidgets/blob/a311d753385f0867c34525eacad9496108e43cc1/packages/jupyterlab-manager/src/manager.ts#L192 and https://github.com/jupyter-widgets/ipywidgets/blob/a311d753385f0867c34525eacad9496108e43cc1/packages/jupyterlab-manager/src/manager.ts#L171-L176 called from the constructor: https://github.com/jupyter-widgets/ipywidgets/blob/a311d753385f0867c34525eacad9496108e43cc1/packages/jupyterlab-manager/src/manager.ts#L123

**Comment by captainsafia** [comment]
Got it! Thanks for answering the question.

I'll go ahead and close this issue as my question has been answered.
