### ISSUE TITLE
Output widget context manager in a coroutine

### ISSUE THREAD

**Issue by davidbrochart** [jupyter-widgets/ipywidgets#2567]
It looks like the `Output` widget context manager, when used from within an async function, doesn't work, as shown in the example below.
```python
%gui asyncio
from ipywidgets import ToggleButton, Output
import asyncio
```
```python
out = Output()
out
```
```python
def wait_for_change(widget, value):
    future = asyncio.Future()
    def getvalue(change):
        future.set_result(change.new)
        widget.unobserve(getvalue, value)
        widget.value = False
    widget.observe(getvalue, value)
    return future
```
```python
button = ToggleButton(description='Go!')
async def f():
    i = 0
    while True:
        x = await wait_for_change(button, 'value')
        # this works:
        out.append_stdout(str(i) + '\n')
        # this doesn't work:
        # with out:
        #     print(i)
        i += 1
asyncio.ensure_future(f())
button
```

**Comment by jasongrout** [comment]
Does https://ipywidgets.readthedocs.io/en/latest/examples/Output%20Widget.html#Interacting-with-output-widgets-from-background-threads seem relevant in this situation?

**Comment by davidbrochart** [comment]
And is it consistent with the fact that executing the following in a new cell works?
```python
with out:
    print(0)
```
The thing is that I have a more complex code (involving Dask's progress bar widget) that shows the same behavior, and it still doesn't work when I replace the context manager with `append_display_data`, but that could be another issue.

**Comment by jasongrout** [comment]
> And is it consistent with the fact that executing the following in a new cell works?

Yes. The problem is capturing output after a cell execution has finished, which is what happens in the async execution situation.

**Comment by jasongrout** [comment]
> The thing is that I have a more complex code (involving Dask's progress bar widget) that shows the same behavior, and it still doesn't work when I replace the context manager with `append_display_data`, but that could be another issue.

Yeah, not sure on that without more info.

**Comment by davidbrochart** [comment]
Thanks.
