### ISSUE TITLE
%manage_spark: Error creating widget: could not find model

### ISSUE THREAD

**Issue by ebebpl** [jupyter-widgets/ipywidgets#2568]
Hello Experts,
Read through various issues but not yet sure what to do. This works in Jupyter notebook but fails in JupyterLAB running in Centos via Jupyterhub.
 
%load_ext sparkmagic.magics      ----- this works fine
%manage_spark
First error I got was instead of widget form for creating Spark session  I got:
error is: MagicsControllerWidget(children=(Tab(children= 
(ManageSessionWidget(children=(HTML(value='<br/>'), HTML(value='…

Based on some prior issues which suggested:
https://ipywidgets.readthedocs.io/en/latest/user_install.html#installing-the-jupyterlab-extension
I ran as root:
root>$ jupyter labextension install @jupyter-widgets/jupyterlab-manager

It found some incompatible version and installed different version as below:
/opt/anaconda3/bin/npm pack @jupyter-widgets/jupyterlab-manager
jupyter-widgets-jupyterlab-manager-1.0.2.tgz
Incompatible extension:

"@jupyter-widgets/jupyterlab-manager@1.0.2" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.18.4 <0.19.0        >=1.0.0 <2.0.0   @jupyterlab/application
>=2.1.4 <3.0.0          >=3.0.0 <4.0.0   @jupyterlab/coreutils
>=0.18.4 <0.19.0        >=1.0.0 <2.0.0   @jupyterlab/notebook
>=0.18.4 <0.19.0        >=1.0.0 <2.0.0   @jupyterlab/rendermime
>=3.1.4 <4.0.0          >=4.0.0 <5.0.0   @jupyterlab/services

Found compatible version: 0.37.4
> /opt/anaconda3/bin/npm pack @jupyter-widgets/jupyterlab-manager@0.37.4
jupyter-widgets-jupyterlab-manager-0.37.4.tgz

It completed the install.
Now when I run in Jupyterlab:
%manage_spark   
I get the error: Error creating widget: could not find model

Any help to fix will be really appreciated!

**Comment by ebebpl** [comment]
UPDATE:
If anyone is interested, this got resolved by stopping and starting the Jupyter server. In addition I had to do %reload_ext sparkmagic.magics  instead of %load_ext sparkmagic.magics prior to running:
%manage_spark

**Comment by ebebpl** [comment]
Found one issue with %manage_spark in JupyterLAB is that it does not give any helpful message like below which was given in the old jupyter. Even if there is an error it doesnt display anything. These messages were helpful to see if the spark session started or not.

Starting Spark application
ID | YARN Application ID | Kind | State | Spark UI | Driver log | Current session?
-- | -- | -- | -- | -- | -- | --
15 | None | pyspark | idle |   |   | ✔
SparkContext available as 'sc'.
SqlContext available as 'sqlContext'.

**Comment by pbugnion** [comment]
Hi @ebebpl -- thanks for raising this.

This feels like a good question for the [sparkmagics](https://github.com/jupyter-incubator/sparkmagic) repository? Not sure anyone here has much experience with interacting with Spark.
