### ISSUE TITLE
In-person sprint for ipywidgets 8.0, Jan 6-10, 2020 in Paris

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#2587]
We're having an intensive code sprint for ipywidgets 8.0, Jan 6-10 in Paris, France.

Please let us know below if you will be able to make it (sorry, we don't have funding to support people coming), or if you would like to participate remotely (we'll be active on gitter, and may have opportunities to have discussions on video conference).

CC @jupyter-widgets/jupyter-widgets @SylvainCorlay @vidartf @maartenbreddels @mwcraig

**Comment by jasongrout** [comment]
I just talked to @SylvainCorlay, and it sounds like he might have space available in Paris.

**Comment by mwcraig** [comment]
I'm definitely interested, have more constraints than I used on when I can travel. Depending on when and where it is I may need to participate remotely.

**Comment by jasongrout** [comment]
How does Paris in January sound? (I know, great time to visit Paris :)

**Comment by vidartf** [comment]
Sounds good to me! The earlier we can fix the dates, the more likely I can attend 👍

**Comment by jasongrout** [comment]
We have now fixed the dates! Jan 6-10 in Paris, France. @SylvainCorlay is arranging the venue, with a capacity of 12 (right now). Thanks @SylvainCorlay!

Let us know here if you want to come, and we'll share the planning spreadsheet with you for logistics details.

**Comment by jasongrout** [comment]
CC @nthiery as well

**Comment by SylvainCorlay** [comment]
Hello,

On our side, I can confirm provisionally

 - @SylvainCorlay 
 - @martinRenou 
 - @jtpio (but not the whole week)
 - @johanmabille

**Comment by nthiery** [comment]
I should be able to drop by for some of the days. Looking forward to it!

**Comment by jasongrout** [comment]
Superseded by #2641.
