### ISSUE TITLE
return value doesn't show 

### ISSUE THREAD

**Issue by eromoe** [jupyter-widgets/ipywidgets#2589]
### Basic

```
def f(x):
    return x
interact(f, x=10);
```

Nothing output :

![image](https://user-images.githubusercontent.com/3938751/67085121-d628cb00-f1d0-11e9-9775-9bdc2a139c0b.png)

## Example from docs

https://ipywidgets.readthedocs.io/en/latest/examples/Output%20Widget.html#Output-widgets-as-the-foundation-for-interact

![image](https://user-images.githubusercontent.com/3938751/67085277-1ee08400-f1d1-11e9-9d2d-9e598fb9e729.png)

Mine: 
![image](https://user-images.githubusercontent.com/3938751/67085011-a4afff80-f1d0-11e9-9aa5-95e81f348fb8.png)

use widgets.Output still no output  .

**Comment by jasongrout** [comment]
Some more info is needed to begin diagnosing:

* ipywidgets version
* Jupyter notebook/lab version
* can you reproduce this in a clean new environment install with just ipywidgets installed
* any js or server errors?

**Comment by jasongrout** [comment]
This is what it looks like for me:
<img width="411" alt="Screen Shot 2019-10-18 at 4 13 38 AM" src="https://user-images.githubusercontent.com/192614/67089948-b5735d80-f15d-11e9-9cc7-aa13465b18ad.png">

**Comment by eromoe** [comment]
Just find this was caused by `Limit Output` extention

![image](https://user-images.githubusercontent.com/3938751/67136742-48df8800-f25d-11e9-9b8d-078db312762b.png)

Parameters : 
![image](https://user-images.githubusercontent.com/3938751/67136755-6d3b6480-f25d-11e9-8d46-0746a634e727.png)

Disable this work it out : 

![image](https://user-images.githubusercontent.com/3938751/67136732-2f3e4080-f25d-11e9-93a0-cc13025469e0.png)

**Comment by jasongrout** [comment]
Thanks for following up here.
