### ISSUE TITLE
Duplicate Documentation for "docs/source/examples/Widget Styling.ipynb"

### ISSUE THREAD

**Issue by jhl0204** [jupyter-widgets/ipywidgets#2592]
Hello everyone, 

This is my first time opening an issue so I apologize in advance if the issue is a trivial one. 

As I was reading the documentations for "Layout and Styling of Jupyter widgets" (path specified in title above), I noticed that the contents under "Image layout and sizing" header has a duplicate. I wasn't sure if this was intentional or not and if it wasn't intentional (shouldn't have been duplicated), I can make a PR to delete that part. 

[Readthedocs Link to the Documentation mentioned above](https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Styling.html#Image-layout-and-sizing)

Thanks!

**Comment by jasongrout** [comment]
That looks like a mistake. PR appreciated!

**Comment by mwcraig** [comment]
Closed by #2593
