### ISSUE TITLE
cannot complete installation of jupyterlab-manager@1.0.3

### ISSUE THREAD

**Issue by sbowman-mitre** [jupyter-widgets/ipywidgets#2595]
I am using a fresh conda env on CentOs7. I've searched the issue archive and cannot find anything that helps. No matter how I install jupyterlab-manager@1.0.3, I get an error log. I've installed it per the normal instructions:
`jupyter labextension install @jupyter-widgets/jupyterlab-manager`

I've also installed from source using the [npm instructions here](https://www.npmjs.com/package/@jupyter-widgets/jupyterlab-manager). The consistent result looks like a missing dependency error. But even when I try installing each dependency by hand (as listed in [the package.json](https://github.com/jupyter-widgets/ipywidgets/blob/master/packages/jupyterlab-manager/package.json)) nothing works. 

Output of debug installation is attached. 
[jupyterlab-manager-install-failure.log](https://github.com/jupyter-widgets/ipywidgets/files/3764797/jupyterlab-manager-install-failure.log)

**Comment by sbowman-mitre** [comment]
FYI: I was also able to reproduce this problem using the instructions here:
`https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html`

This just consistently produces an error whenever I try to install jupyterlab-manager :( 

Relevant Versions:
ipykernel                 5.1.3            py37h5ca1d4c_0    conda-forge
ipython                   7.8.0            py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jupyter_client            5.3.3                    py37_1    conda-forge
jupyter_core              4.5.0                      py_0    conda-forge
jupyterlab                1.1.4                      py_0    conda-forge
jupyterlab_server         1.0.6                      py_0    conda-forge
nodejs                    12.11.1              h10a4023_0    conda-forge
notebook                  6.0.1                    py37_0    conda-forge
widgetsnbextension        3.5.1                    py37_0    conda-forge

Thanks for any help you can provide!

**Comment by jasongrout** [comment]
What is in the log file it mentions? /tmp/jupyterlab-debug-smymdyq3.log - is that the file you posted?

The first thing I would check is the network connection: for example `npm pack @jupyter-widgets/base`, which should download that package from npm.

**Comment by sbowman-mitre** [comment]
The log file that I posted was the terminal STDOUT dump. But, the terminal dump is the same as /tmp/jupyterlab-debug-smymdyq3.log . I definitely have a working network connection or else conda wouldnt' have been able to download all of the packages for this brand-new env. 

`npm pack @jupyter-widgets/base` produces:
(jlab-test) 22:16:20:jupyter$ npm pack @jupyter-widgets/base
npm notice 
npm notice \U0001f4e6  @jupyter-widgets/base@2.0.1
npm notice === Tarball Contents === 
npm notice 2.6kB  package.json           
npm notice 1.5kB  LICENSE                
npm notice 467B   css/index.css          
npm notice 76B    lib/backbone-patch.d.ts
npm notice 4.8kB  lib/backbone-patch.js  
npm notice 264B   lib/index.d.ts         
npm notice 367B   lib/index.js           
npm notice 8.3kB  lib/manager-base.d.ts  
npm notice 21.3kB lib/manager-base.js    
npm notice 1.2kB  lib/nativeview.d.ts    
npm notice 7.4kB  lib/nativeview.js      
npm notice 1.1kB  lib/registry.d.ts      
npm notice 299B   lib/registry.js        
npm notice 5.9kB  lib/services-shim.d.ts 
npm notice 11.6kB lib/services-shim.js   
npm notice 3.0kB  lib/utils.d.ts         
npm notice 11.1kB lib/utils.js           
npm notice 105B   lib/version.d.ts       
npm notice 188B   lib/version.js         
npm notice 2.3kB  lib/viewlist.d.ts      
npm notice 4.0kB  lib/viewlist.js        
npm notice 972B   lib/widget_layout.d.ts 
npm notice 6.2kB  lib/widget_layout.js   
npm notice 903B   lib/widget_style.d.ts  
npm notice 4.9kB  lib/widget_style.js    
npm notice 10.9kB lib/widget.d.ts        
npm notice 33.9kB lib/widget.js          
npm notice === Tarball Details === 
npm notice name:          @jupyter-widgets/base                   
npm notice version:       2.0.1                                   
npm notice filename:      jupyter-widgets-base-2.0.1.tgz          
npm notice package size:  32.6 kB                                 
npm notice unpacked size: 145.7 kB                                
npm notice shasum:        b31b5c8b2206bb008216f32abd488e5414bce3b7
npm notice integrity:     sha512-jRNeQzvEf6MMG[...]Pdk8/aCsJRw9w==
npm notice total files:   27                                      
npm notice 
jupyter-widgets-base-2.0.1.tgz

Thanks.

**Comment by sbowman-mitre** [comment]
For reference, I've also recreated this (nearly) exact error log in a fresh conda env on Windows 10 using WSL Ubuntu 16.04. New error log attached. This appears to me to occur every time I run:
`jupyter labextension install @jupyter-widgets/jupyterlab-manager`

[jupyterlab-debug-60x1apdn.log](https://github.com/jupyter-widgets/ipywidgets/files/3770147/jupyterlab-debug-60x1apdn.log)

`npm list` shows:
(jlab-test) sbowman@MM224395-PC:/mnt/c/Users/sbowman/git$ npm list
/mnt/c/Users/sbowman/git
└─┬ @jupyter-widgets/base@2.0.1
  ├─┬ @jupyterlab/services@4.1.1
  │ ├─┬ @jupyterlab/coreutils@3.1.0
  │ │ ├── @phosphor/commands@1.7.2 deduped
  │ │ ├── @phosphor/coreutils@1.3.1 deduped
  │ │ ├── @phosphor/disposable@1.3.1 deduped
  │ │ ├── @phosphor/properties@1.1.3 deduped
  │ │ ├── @phosphor/signaling@1.3.1 deduped
  │ │ ├─┬ ajv@6.10.2
  │ │ │ ├── fast-deep-equal@2.0.1
  │ │ │ ├── fast-json-stable-stringify@2.0.0
  │ │ │ ├── json-schema-traverse@0.4.1
  │ │ │ └─┬ uri-js@4.2.2
  │ │ │   └── punycode@2.1.1
  │ │ ├─┬ json5@2.1.1
  │ │ │ └── minimist@1.2.0 deduped
  │ │ ├── minimist@1.2.0
  │ │ ├── moment@2.24.0
  │ │ ├── path-posix@1.0.0
  │ │ └─┬ url-parse@1.4.7
  │ │   ├── querystringify@2.1.1
  │ │   └── requires-port@1.0.0
  │ ├─┬ @jupyterlab/observables@2.3.0
  │ │ ├── @phosphor/algorithm@1.2.0 deduped
  │ │ ├── @phosphor/coreutils@1.3.1 deduped
  │ │ ├── @phosphor/disposable@1.3.1 deduped
  │ │ ├── @phosphor/messaging@1.3.0 deduped
  │ │ └── @phosphor/signaling@1.3.1 deduped
  │ ├── @phosphor/algorithm@1.2.0
  │ ├── @phosphor/coreutils@1.3.1 deduped
  │ ├─┬ @phosphor/disposable@1.3.1
  │ │ ├── @phosphor/algorithm@1.2.0 deduped
  │ │ └── @phosphor/signaling@1.3.1 deduped
  │ ├─┬ @phosphor/signaling@1.3.1
  │ │ └── @phosphor/algorithm@1.2.0 deduped
  │ ├── node-fetch@2.6.0
  │ └─┬ ws@7.2.0
  │   └── async-limiter@1.0.1
  ├── @phosphor/coreutils@1.3.1
  ├─┬ @phosphor/messaging@1.3.0
  │ ├── @phosphor/algorithm@1.2.0 deduped
  │ └─┬ @phosphor/collections@1.2.0
  │   └── @phosphor/algorithm@1.2.0 deduped
  ├─┬ @phosphor/widgets@1.9.3
  │ ├── @phosphor/algorithm@1.2.0 deduped
  │ ├─┬ @phosphor/commands@1.7.2
  │ │ ├── @phosphor/algorithm@1.2.0 deduped
  │ │ ├── @phosphor/coreutils@1.3.1 deduped
  │ │ ├── @phosphor/disposable@1.3.1 deduped
  │ │ ├── @phosphor/domutils@1.1.4 deduped
  │ │ ├── @phosphor/keyboard@1.1.3 deduped
  │ │ └── @phosphor/signaling@1.3.1 deduped
  │ ├── @phosphor/coreutils@1.3.1 deduped
  │ ├── @phosphor/disposable@1.3.1 deduped
  │ ├── @phosphor/domutils@1.1.4
  │ ├─┬ @phosphor/dragdrop@1.4.1
  │ │ ├── @phosphor/coreutils@1.3.1 deduped
  │ │ └── @phosphor/disposable@1.3.1 deduped
  │ ├── @phosphor/keyboard@1.1.3
  │ ├── @phosphor/messaging@1.3.0 deduped
  │ ├── @phosphor/properties@1.1.3
  │ ├── @phosphor/signaling@1.3.1 deduped
  │ └─┬ @phosphor/virtualdom@1.2.0
  │   └── @phosphor/algorithm@1.2.0 deduped
  ├─┬ @types/backbone@1.4.1
  │ ├─┬ @types/jquery@3.3.31
  │ │ └── @types/sizzle@2.3.2
  │ └── @types/underscore@1.9.3
  ├── @types/lodash@4.14.144
  ├─┬ backbone@1.2.3
  │ └── underscore@1.9.1
  ├── base64-js@1.3.1
  ├── jquery@3.4.1
  └── lodash@4.17.15

**Comment by sbowman-mitre** [comment]
For reference, I've also recreated this (nearly) exact error log in a fresh conda env on Windows 10 using WSL Ubuntu 16.04. New error log attached. This appears to me to occur every time I run:
`jupyter labextension install @jupyter-widgets/jupyterlab-manager`

[jupyterlab-debug-60x1apdn.log](https://github.com/jupyter-widgets/ipywidgets/files/3770147/jupyterlab-debug-60x1apdn.log)

`npm list` shows:
(jlab-test) sbowman@MM224395-PC:/mnt/c/Users/sbowman/git$ npm list
/mnt/c/Users/sbowman/git
└─┬ @jupyter-widgets/base@2.0.1
  ├─┬ @jupyterlab/services@4.1.1
  │ ├─┬ @jupyterlab/coreutils@3.1.0
  │ │ ├── @phosphor/commands@1.7.2 deduped
  │ │ ├── @phosphor/coreutils@1.3.1 deduped
  │ │ ├── @phosphor/disposable@1.3.1 deduped
  │ │ ├── @phosphor/properties@1.1.3 deduped
  │ │ ├── @phosphor/signaling@1.3.1 deduped
  │ │ ├─┬ ajv@6.10.2
  │ │ │ ├── fast-deep-equal@2.0.1
  │ │ │ ├── fast-json-stable-stringify@2.0.0
  │ │ │ ├── json-schema-traverse@0.4.1
  │ │ │ └─┬ uri-js@4.2.2
  │ │ │   └── punycode@2.1.1
  │ │ ├─┬ json5@2.1.1
  │ │ │ └── minimist@1.2.0 deduped
  │ │ ├── minimist@1.2.0
  │ │ ├── moment@2.24.0
  │ │ ├── path-posix@1.0.0
  │ │ └─┬ url-parse@1.4.7
  │ │   ├── querystringify@2.1.1
  │ │   └── requires-port@1.0.0
  │ ├─┬ @jupyterlab/observables@2.3.0
  │ │ ├── @phosphor/algorithm@1.2.0 deduped
  │ │ ├── @phosphor/coreutils@1.3.1 deduped
  │ │ ├── @phosphor/disposable@1.3.1 deduped
  │ │ ├── @phosphor/messaging@1.3.0 deduped
  │ │ └── @phosphor/signaling@1.3.1 deduped
  │ ├── @phosphor/algorithm@1.2.0
  │ ├── @phosphor/coreutils@1.3.1 deduped
  │ ├─┬ @phosphor/disposable@1.3.1
  │ │ ├── @phosphor/algorithm@1.2.0 deduped
  │ │ └── @phosphor/signaling@1.3.1 deduped
  │ ├─┬ @phosphor/signaling@1.3.1
  │ │ └── @phosphor/algorithm@1.2.0 deduped
  │ ├── node-fetch@2.6.0
  │ └─┬ ws@7.2.0
  │   └── async-limiter@1.0.1
  ├── @phosphor/coreutils@1.3.1
  ├─┬ @phosphor/messaging@1.3.0
  │ ├── @phosphor/algorithm@1.2.0 deduped
  │ └─┬ @phosphor/collections@1.2.0
  │   └── @phosphor/algorithm@1.2.0 deduped
  ├─┬ @phosphor/widgets@1.9.3
  │ ├── @phosphor/algorithm@1.2.0 deduped
  │ ├─┬ @phosphor/commands@1.7.2
  │ │ ├── @phosphor/algorithm@1.2.0 deduped
  │ │ ├── @phosphor/coreutils@1.3.1 deduped
  │ │ ├── @phosphor/disposable@1.3.1 deduped
  │ │ ├── @phosphor/domutils@1.1.4 deduped
  │ │ ├── @phosphor/keyboard@1.1.3 deduped
  │ │ └── @phosphor/signaling@1.3.1 deduped
  │ ├── @phosphor/coreutils@1.3.1 deduped
  │ ├── @phosphor/disposable@1.3.1 deduped
  │ ├── @phosphor/domutils@1.1.4
  │ ├─┬ @phosphor/dragdrop@1.4.1
  │ │ ├── @phosphor/coreutils@1.3.1 deduped
  │ │ └── @phosphor/disposable@1.3.1 deduped
  │ ├── @phosphor/keyboard@1.1.3
  │ ├── @phosphor/messaging@1.3.0 deduped
  │ ├── @phosphor/properties@1.1.3
  │ ├── @phosphor/signaling@1.3.1 deduped
  │ └─┬ @phosphor/virtualdom@1.2.0
  │   └── @phosphor/algorithm@1.2.0 deduped
  ├─┬ @types/backbone@1.4.1
  │ ├─┬ @types/jquery@3.3.31
  │ │ └── @types/sizzle@2.3.2
  │ └── @types/underscore@1.9.3
  ├── @types/lodash@4.14.144
  ├─┬ backbone@1.2.3
  │ └── underscore@1.9.1
  ├── base64-js@1.3.1
  ├── jquery@3.4.1
  └── lodash@4.17.15

**Comment by jasongrout** [comment]
Can you install other jlab extensions? (In other words, is this a more general problem with installing extensions, or is it specific to ipywidgets?)

**Comment by sbowman-mitre** [comment]
yeah, good question. It looks like the answer is `no`. I tried to install @jupyterlab/toc and that also failed. And the failure pattern continues. This is super strange. 

-------------------
[LabBuildApp] Building in /home/sbowman/miniconda3/envs/jlab-test/share/jupyter/lab
[LabBuildApp] Node v12.11.1

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] > node /home/sbowman/miniconda3/envs/jlab-test/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
error Couldn't find package "@jupyter-widgets/base@^2.0.1" required by "@jupyter-widgets/jupyterlab-manager@file:../extensions/jupyter-widgets-jupyterlab-
manager-1.0.3.tgz" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "@jupyter-widgets/controls@^1.5.2" required by "@jupyter-widgets/jupyterlab-manager@file:../extensions/jupyter-widgets-jupyte
rlab-manager-1.0.3.tgz" on the "npm" registry.
    at /home/sbowman/miniconda3/envs/jlab-test/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/home/sbowman/miniconda3/envs/jlab-test/share/jupyter/lab/staging/yarn.js:310:30)
    at /home/sbowman/miniconda3/envs/jlab-test/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by vidartf** [comment]
It would probably be better to repost this issue (linking back to this) on the jupyterlab issue page. Then any others with the same issue can help troubleshoot it, and all the people that might offer some insight will have a chance to look at it.

**Comment by sbowman-mitre** [comment]
Sure, that may be true now. I posted here originally because it really seemed like only a problem with jupyterlab-manager installation. But it is starting to feel like a larger problem at the jupyterlab level. I'll post there.

**Comment by jasongrout** [comment]
Superseded by https://github.com/jupyterlab/jupyterlab/issues/7432

**Comment by bmorier** [comment]
I had a similar problem while trying to execute:
`jupyter labextension install @jupyter-widgets/jupyterlab-manager
`
The log showed a missing dependency @jupyter-widgets/base@2.0.1. In my case the problem was that I was trying to run this in a computer were certificates were not working, and I had previously disabled the SSL check in npm and node, with

`set NODE_TLS_REJECT_UNAUTHORIZED=0`
and 
`npm config set strict-ssl false`

But it seems that jupyter uses the yarn to get the dependencies, in a diferent process to get the first tarball, that jupyter got using npm. So I needed to disable the ssl check in yarn, so jupyter could get this dependency. I did this editing the .yarnrc at the folder:
`base_environment\lib\site-packages\jupyterlab\staging`
adding a line with:
`strict-ssl false`

And that finally solved the issue. A better solution would include an option for jupyter to disable ssl check, but there is no such option yet

**Comment by malkindy** [comment]
I have similar problem as below and I am not able to resolve it!!!

======
bash-3.2$ jupyter labextension install @jupyter-widgets/jupyterlab-manager
Traceback (most recent call last):
  File "/opt/anaconda3/envs/donate/bin/jupyter", line 11, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/donate/lib/python3.7/site-packages/jupyter_core/command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "/opt/anaconda3/envs/donate/lib/python3.7/site-packages/jupyter_core/command.py", line 134, in _jupyter_abspath
    'Jupyter command `{}` not found.'.format(jupyter_subcommand)
Exception: Jupyter command `jupyter-labextension` not found.
