### ISSUE TITLE
Custom node distance

### ISSUE THREAD

**Issue by galaplexus** [jupyter-widgets/ipywidgets#2597]
Another interesting dimension of a Sankey diagram could be the horizontal distance between nodes. We already have the line width between nodes but the distance could indicate something different.

The intuition comes from dendrograms.

For simplicity, we could indicate the x-position of a node. They are now every x pixel but we could let the user define it for each node.

**Comment by vidartf** [comment]
Are you sure this is the right repository? I'm generally confused by this post :)

**Comment by galaplexus** [comment]
Ok. I didn't see that there was a special repository for the Sankey diagram on Jupyter. I'll post the feature request there. So you can delete here

**Comment by vidartf** [comment]
Thanks, closing.
