### ISSUE TITLE
Log Console logging twice

### ISSUE THREAD

**Issue by mbektasbbg** [jupyter-widgets/ipywidgets#2604]
@jasongrout While testing (https://github.com/jupyter-widgets/ipywidgets/pull/2572) I noticed an issue when you log some messages in `warning` level and then change level to `debug` level. After changing to debug level widget callback messages were being logged twice. Looks like one log is coming from widget manager other from nboutput logger extension.

**Comment by jasongrout** [comment]
Yes, the notebook output is being logged by the notebook logging extension independent of ipywidgets

**Comment by jasongrout** [comment]
Closing as expected. The notebook logging extension has no way of knowing if someone else also handled the output message.
