### ISSUE TITLE
widgets.link not working

### ISSUE THREAD

**Issue by VeneficusFerox** [jupyter-widgets/ipywidgets#2606]
Trying to get the `link `feature to work, but even on the [documentation page](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Events.html) the feature is broken.

`caption = widgets.Label(value='The values of slider1 and slider2 are synchronized')
'sliders1, slider2 = widgets.IntSlider(description='Slider 1'),\
                    widgets.IntSlider(description='Slider 2')
l = widgets.link((sliders1, 'value'), (slider2, 'value'))
display(caption, sliders1, slider2)`

Trying to run in my own JupyterLab environment with ipywidgets 7.5.1 gives

`AttributeError: module 'ipywidgets.widgets' has no attribute 'link'`

**Comment by vidartf** [comment]
How do you import widgets? The example notebook uses `import ipywidgets as widgets` which I agree can be very confusing.

**Comment by VeneficusFerox** [comment]
> How do you import widgets? The example notebook uses import ipywidgets as widgets which I agree can be very confusing.

Let's talk about the two cases separated:
1) I don't do anything on the documentation page. There, a notebook server is running, which has interactive elements (widgets) on its page. Those don't work.
2) I copy/paste the full code into my own environment. Also there, it doesn't work.

So how I import the widgets is exactly as on the documentation page, and that doesn't seem to work.

**Comment by VeneficusFerox** [comment]
> How do you import widgets? The example notebook uses `import ipywidgets as widgets` which I agree can be very confusing.

Thanks, that solved the issue on my own notebook. That might also be the mistake made on the documentation page, because there it's broken as well.
