### ISSUE TITLE
the @jupyter-widgets/jupyterlab-manager extension is not upgraded/updated for use with JupyterLab 1.2.X

### ISSUE THREAD

**Issue by rchossein** [jupyter-widgets/ipywidgets#2609]
As stated in the ReadMe file, we have compatibility only up to 1.0.X version of JupyterLab. The ReadMe file should be updated if it's compatible with other versions too.

**Comment by jasongrout** [comment]
The latest release is compatible with 1.2 (in fact, insists on 1.2.x and won't work with 1.0/1.1). So the readme should be updated.
