### ISSUE TITLE
Progress bar widget (used by tqdm) renders poorly in jupyterlab dark mode

### ISSUE THREAD

**Issue by owen-synergy** [jupyter-widgets/ipywidgets#2610]
I'm having a visual output issue when trying to use tqdm in jupyterlab in dark mode. I originally raised this issue on the tqdm github here: https://github.com/tqdm/tqdm/issues/842 but was told it is a general ipywidget issue.

The issue is in dark mode font color changes to white but it still shows a near white background rendering the text illegible. See examples below.

Output from:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```
4.37.0 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 22:01:29) [MSC v.1900 64 bit (AMD64)] win32

Screenshot of jupyterlab tqdm widget in light mode:

![jupyterlab_light](https://user-images.githubusercontent.com/50761413/68726621-065f6000-05fd-11ea-9a26-678e2791921b.png)

Screenshot of jupyterlab tqdm widget in dark mode:

![jupyterlab_dark](https://user-images.githubusercontent.com/50761413/68726623-065f6000-05fd-11ea-8cc4-aa549f851dfe.png)

I was importing tqdm as:

from tqdm.auto import tqdm

I'm using:
- ipywidgets 7.5.1
- jupyterlab 1.2.2
- tqdm 4.37.0

the conda-forge installs from each on Windows 10

**Comment by jasongrout** [comment]
The IntProgress widget looks fine to me in dark mode:

```python
from ipywidgets import *

x = IntProgress(description='progress', value=25)
x
```
<img width="538" alt="Screen Shot 2019-11-13 at 7 33 57 AM" src="https://user-images.githubusercontent.com/192614/68778466-1751a680-05e8-11ea-8bb3-16486ae2a61c.png">

Can you try the above code to see if it is an ipywidgets problem?

**Comment by owen-synergy** [comment]
Hi Jason - yes I can confirm I got the same result. The progress bar does have a black background. I'll copy your answer back to the tqdm issue.

**Comment by jasongrout** [comment]
Great!
