### ISSUE TITLE
Error message not shown when using a callback!

### ISSUE THREAD

**Issue by alex4200** [jupyter-widgets/ipywidgets#2612]
Using JupyterLab 1.1.4 

When using a simple code snippet like this

```
from IPython.display import display
from ipywidgets import widgets
button = widgets.Button(description="Click Me!")
display(button)

def on_button_clicked(b):
    a=1/0
    # do something important

button.on_click(on_button_clicked)
```

and I run the code and click on the button, **I do not get any error message**! There is clearly an error, but I do not see it in any output!

Will this bug fixed in a future release?

**Comment by SylvainCorlay** [comment]
This is actually the expected behavior. Unless you capture output with the output widget, there isn't a natural output area where to place that error (same for a print statement).

There is a debug console being developped for jupyterlab to display all error messages that don't naturally go to a given cell.

**Comment by alex4200** [comment]
@SylvainCorlay So you are saying that I cannot see such an error at all? 

If so, then `ipywidgets` is not useable.

**Comment by jasongrout** [comment]
> So you are saying that I cannot see such an error at all?

You can *always* see such errors.

* In the classic Jupyter Notebook, errors and output are appended to the cell where the button is displayed
* In recent JupyterLab (1.2.0 or later), errors and output are displayed in a new output log - you'll see a flashing indicator on the status bar to open the output log when a message is displayed
* In either case (and especially in JupyterLab before 1.2) you can capture the output (including errors) as documented in the ipywidgets documentation: https://ipywidgets.readthedocs.io/en/latest/examples/Output%20Widget.html#Debugging-errors-in-callbacks-with-the-output-widget

**Comment by alex4200** [comment]
@jasongrout 

We are using here version 1.1.4 currently, I am asking for an upgrade. 

As for your third point, it looks like that _by default_ no error is shown, and only with the very complicated and non-intuitive output capturing it is possible to get any possible error message. This makes is extremely hard and cumbersome to develop software. 

It should be the other way around: _By default_ show any error, and only if you have finished developing then you maybe can turn off error output!

**Comment by jasongrout** [comment]
> As for your third point, it looks like that _by default_ no error is shown, and only with the very complicated and non-intuitive output capturing it is possible to get any possible error message. This makes is extremely hard and cumbersome to develop software.
> 
> It should be the other way around: _By default_ show any error, and only if you have finished developing then you maybe can turn off error output!

By default, in classic notebook, any output or error is shown. From now on in JupyterLab (1.2 or later), errors and output are shown by default in the new log console. 

For various technical reasons, we had to fall back to output capturing for JupyterLab 1.0 and 1.1 (i.e., the last few months) as the primary way to see errors in these callbacks, which did require adding a few more lines of code following the example shown in the ipywidgets docs.

**Comment by jasongrout** [comment]
And we are *very* grateful for @mbektasbbg for implementing the log console in JupyterLab 1.2 (and his employer Bloomberg for prioritizing him to work on it) so that we could move back to showing errors and output by default!

**Comment by jasongrout** [comment]
I think we can close this as answered now? Feel free comment if you want to continue the discussion.

**Comment by alex4200** [comment]
@jasongrout I think we can migrate to JupyterLab 1.2 and then the log console should be enough to be able to develop code. If there is any issue, I will open a new ticket.

And thanks for your useful comments!

**Comment by jasongrout** [comment]
> I think we can migrate to JupyterLab 1.2

Enjoy!
