### ISSUE TITLE
Create new button from on_click() method OR create 2nd button during 1st button press event 

### ISSUE THREAD

**Issue by shek2994** [jupyter-widgets/ipywidgets#2614]
I am trying to create a button run time. Example, On click 'Load' button, create 'Test' button. How do I achieve this feature in widgets?
'''Code here'''

```python
from ipywidgets import Button
def mycallbackk(b):   
    btn1=Button(description='test')
    display(btn1)
    pass
    

btn = Button(description='Load')
btn.on_click(mycallbackk)
display(btn)
```

**Comment by jasongrout** [comment]
Lots of ways to do this. One way is to create both buttons, but hide the test button (`bn1.layout.display='none'`) until you are ready to show (`bn1.layout.display=''`)

**Comment by jasongrout** [comment]
(or another way to do it would be `bn1.layout.visibility='hidden'` and `bn1.layout.visibility='visible'`)

**Comment by shek2994** [comment]
@jasongrout, Let me elaborate project requirement.

'Load' button will load json file in **mycallback**() and scan (key, value) pair. if '**value**' type is **string** create **Text**() widget. Else check **value** for the other 3 types (int, float, boolean) and create widgets accordingly. Meaning, IntText() or FloatText or Dropdown() widget.  So inside mycallbackk(), i dynamically(run-time) create UI(or widgets) based on json 'value' type.

Is there a way to achieve this requirement.

**Comment by jasongrout** [comment]
You absolutely can create a new button in your callback. You may want to make sure you can *access* that created button outside the callback too.

I think you may be running into the issue that you would need to capture the output of the callback, i.e., put the button somewhere. Take a look at the docs at https://ipywidgets.readthedocs.io/en/latest/examples/Output%20Widget.html#Debugging-errors-in-callbacks-with-the-output-widget

Alternatively, you could create a hbox at the global level, and in the callback add the button to the hbox, which would then automatically display it.

**Comment by shek2994** [comment]
"**Alternatively, you could create a hbox at the global level, and in the callback add the button to the hbox, which would then automatically display it.**"

Thanks, @jasongrout , your 2nd method works.

**Here is the code:**
from ipywidgets import (widgets, Button, Text, IntText, FloatText, Dropdown, Output,
                       VBox, HBox)
from IPython.display import display
import json

from ipyfilechooser import FileChooser

# Create and display a FileChooser widget
fc = FileChooser('./')
display(fc)
out = widgets.Output()
display(out)


t = None
vb = VBox()
wi_list = list()
    
def mycallback(b):
    
    for wi_obj in wi_list:
        with out:
            print('found =',wi_obj)
        wi_obj.close()  

    wi_list.clear() #NOTE:  clear list containing widget obj for previous json file. Also destroy wi obj before selecting another json file
        
    with out:
        print(b, fc.selected)
    json_config = None
    with open(fc.selected, 'r') as fp:
        json_config = json.load(fp)
    for k, v in json_config.items():
        t = None

        if type(v) == type('str') :
            t = Text(description=k, style = {'description_width': 'initial'})
            t.value = v; wi_list.append(t)        
        elif type(v) == type(0.23) :
            t = FloatText(description=k, style = {'description_width': 'initial'})
            t.value = v; wi_list.append(t)
        elif type(v) == type(1) :
            t = IntText(description=k, style = {'description_width': 'initial'})
            t.value = v; wi_list.append(t)
        elif type(v) == type(True) :
            t = Dropdown(description=k, style = {'description_width': 'initial'})
            t.options = [True, False]; wi_list.append(t)
        else :
            t = Dropdown(description=k, style = {'description_width': 'initial'})
            t.options = [None]; wi_list.append(t)
    
    
    vb.children = list(wi_list)
    
    pass
    

btn = Button(description='Load')
btn.on_click(mycallback)
display(btn,vb)

**Comment by jasongrout** [comment]
Thanks for following up with a solution!

As a tip, enclose code in three backticks to have it formatted nicely (I edited your comment so you can see how to do it).
