### ISSUE TITLE
Need to close persistent npm window

### ISSUE THREAD

**Issue by scottwsides** [jupyter-widgets/ipywidgets#2615]
I'm installing jupyter and configuring the widgets on windows through a pkg installer. During installation I configure the widgets... and a windows cmd terminal is opening (labeled npm) showing the status of the config steps. This all works fine... but I'd like for the window to close upon completion of configuration (so as not to confuse users). Is this possible through the jupyter, nodejs, npm settings? 

I know that there must be fancy ways of doing this programmatically with windows Powershell scripting, but I'd really rather not add that complication to the post install scripts.

**Comment by jasongrout** [comment]
I have no idea. My guess is this is a good question for your pkg installer.

**Comment by scottwsides** [comment]
I'm using conda constructor to create the pkg installer and as far as I can tell there's no way to control this behavior. BTW, a separate terminal does not show when going through the same steps on MacOS. I know this question is a stretch for this page... but I'd thought I'd give it a shot.

**Comment by jasongrout** [comment]
Sorry, no idea about how to deal with this. I'll close this since it seems like we can't help further, but if you find a resolution, please follow up here for others to learn from. Thanks!

**Comment by scottwsides** [comment]
Sounds good. Thanks
*Dr. Scott W Sides*
(303) 718-7028
