### ISSUE TITLE
Combobox adjust the number of options displayed?

### ISSUE THREAD

**Issue by tonyluo98** [jupyter-widgets/ipywidgets#2621]
Just like how select multiple has the attribute 'rows' that limit how many rows of options are shown, is there an equivalent for Combobox to limit the options being displayed on screen ?

**Comment by vidartf** [comment]
The combo box uses the built in browser controls (a text input with an HTML5 `datalist` tag). I have not been able to find any such functionality supported with this. It might be that some widget libraries wrapping JS libraries might offer this feature (ipymaterialui?).
