### ISSUE TITLE
Is it possible to create a Matplotlib graph in a cell of GridspecLayout?

### ISSUE THREAD

**Issue by KristianLN** [jupyter-widgets/ipywidgets#2624]
Hi,

I'm trying place two plots, in two interactive widgets, in two different cells without the desired outcome.
I did expect them to be placed below the SelectMultiple widgets, yet they are placed to the left of them. See [here](https://drive.google.com/open?id=1Zi2iRUCHCH_mcj37N7blK8VwAI1t1pz9) 

I know I can do it using bqplot, but I was wondering if it was possible using Matplotlib directly, such that I don't have to convert my plotting function from Matplotlib to bqplot (It's more complex than the example below ;) )

The code below should reproduce the output seen from the link above.

```python
from ipywidgets import *
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

grid = GridspecLayout(5,8)#, height = '200px'
testTable = pd.DataFrame({'a':np.random.randn(10),
                    'b':np.random.randn(10),
                    'c':np.random.randn(10),
                    'd':np.random.randn(10),
                    'e':np.random.randn(10)})
# print(testTable)

def plotData(x):
  print(x)
  print(type(x))
  if len(x) > 1:
    plt.plot(testTable.loc[list(x)])
  else:
    plt.plot(testTable.loc[x])
  plt.show()

# header
grid[0,:] = widgets.HTML(value = f"<center><font size = 6><b><font color='white'>{'Historical           Overview'}</b></center>")
# Sub-headlines
grid[1,2] = widgets.HTML(value = f"<center><font size = 2><u><font color='white'>{'Historical Development Graph'}</u></center>")
grid[1,4] = widgets.HTML(value = f"<center><font size = 2><u><font color='white'>{'Upper Pie Chart'}</u></center>")
grid[1,6] = widgets.HTML(value = f"<center><font size = 2><u><font color='white'>{'Lower Pie Chart'}</u></center>")
# Interactive controls and descriptions
grid[2,1] = widgets.HTML(value = f"<center><font color='white'>{'Categories:'}")
grid[2,2] = widgets.SelectMultiple(options=testTable.index,
                              disabled=False,
                              value = [0])
grid[2,3] = widgets.HTML(value = f"<center><font color='white'>{'Time periods:'}")
grid[2,4] = widgets.SelectMultiple(options=testTable.index,
                      value = [0],
                      disabled = False)
grid[2,5] = widgets.HTML(value = f"<center><font color='white'>{'Time periods:'}")
grid[2,6] = widgets.Select(options=testTable.columns,
                      value = 'a',
                      disabled = False)
# Graphs
interactive_graph_1 = widgets.interactive(plotData, x = grid[2,2]);
grid[4,1:4] = interactive_graph_1.children[-1]

grid[4,4:8] = interactive_output(plotData, {'x':grid[2,4]});

display(grid)
```

In advance, thank you.

**Comment by jasongrout** [comment]
I edited your code above for clarity and to add the imports necessary for the example to run.

I got this when I ran it in JupyterLab (sorry, zoom is something like 50% so I could fit it all into one screenshot). I turned on the Firefox gridspec "overlay grid" and "Display area names" from the firefox debugger so it was clearer what the gridspec was doing:
<img width="1608" alt="Screen Shot 2019-11-25 at 8 00 44 AM" src="https://user-images.githubusercontent.com/192614/69551386-d3e92780-0f59-11ea-8044-08c5b54c777a.png">

As far as I can tell, that is exactly the layout you wanted and asked for? Can you give us more information to reproduce the issue, like what frontend you are using, browser, etc.?

**Comment by KristianLN** [comment]
Hi Jason,
it's nice to see that it appears to work as intended at your end.
I'm using Google Colaboratory via Chrome on Windows 10.

**Comment by jasongrout** [comment]
Here it is for me under Chrome, to take at least one of those variables:

<img width="1619" alt="Screen Shot 2019-11-25 at 8 15 09 AM" src="https://user-images.githubusercontent.com/192614/69552465-bcab3980-0f5b-11ea-92c1-ecbaa1230a34.png">

And you're *sure* that the above code is *exactly* what you are running?

If so, perhaps someone can try running this on Windows in Chrome, or you can post to the Colaboratory issue tracker?

CC @blois as well.

**Comment by KristianLN** [comment]
Yes, it is the exact code that I'm running into the issue with.
I can start out by trying to run the code on Jupyter Notebook via Anaconda, to see it it appears to be an issue related to Colaboratory.

**Comment by KristianLN** [comment]
Update:
It does appear to be a Colaboratory issue, as I get the same output as you via Anaconda.
I'll open an issue that their end.

Thank you Jason!

**Comment by blois** [comment]
I am seeing some errors running this in Colab, please do open a bug in https://github.com/googlecolab/colabtools/issues/new.
