### ISSUE TITLE
Documentation notebook output duplicated

### ISSUE THREAD

**Issue by davidbrochart** [jupyter-widgets/ipywidgets#2629]
The documentation which is generated from a notebook (e.g. https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html) has all the outputs duplicated.

**Comment by mwcraig** [comment]
Thanks for reporting this; will take a look this week.

**Comment by mgeier** [comment]
The dupllication has been fixed in  #2660.

Sadly, currently no widgets are displayed at all: https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html

There is a JavaScript error:

    Class StackedModel not found in module @jupyter-widgets/controls@1.5.0

And I guess this is a known problem, see #2708.
