### ISSUE TITLE
Play widget adjustable speed setting

### ISSUE THREAD

**Issue by mironvanderkolk** [jupyter-widgets/ipywidgets#2631]
Hello,

I use the play widget as part of a larger visualization GUI. I use it to run an animation. However, the play widget updates too fast for the frontend of the visualization to keep up. Is there some way I could make it loop slower of make it wait until a function is done executing?

**Comment by jtpio** [comment]
The `Play` widget has the `interval` option, which corresponds to the time between two animation frames.

For example to trigger 1 animation step every second:

```python
from ipywidgets import Play
play = Play(min=0, max=100, step=1, interval=1000)
```

**Comment by pbugnion** [comment]
Closing this. Feel free to re-open if you find something that isn't working.

Thanks!
