### ISSUE TITLE
Extending the height of the output cell pro-grammatically to avoid double drop downs

### ISSUE THREAD

**Issue by acivitillo** [jupyter-widgets/ipywidgets#2635]
In the below case I am using the app layout but the center item is a list of many checks and thus it cannot be displayed within the height of a normal cell so I get a drop down. However, double drop down (center and right) are not very comfortable to use. I was wondering if it'd be possible to extend the height of the cell to be able to fill into it all the checks?

![image](https://user-images.githubusercontent.com/54931660/70091498-838a5d80-161c-11ea-965b-0d53b354fc6d.png)

I tried setting the height of the app layout manually using the height attribute but then I get some strange behavior. I get a lot of white space between the label in the header and the left, center and right sidebar. It's like if defining a fixed height somehow messes up the height of the header.

**Comment by martinRenou** [comment]
Did you try setting the `height` to `auto` ?
