### ISSUE TITLE
Avoid implicit innerHTML assignments

### ISSUE THREAD

**Issue by blois** [jupyter-widgets/ipywidgets#2636]
Since innerHTML assignments can lead to unintended side effects it should be clear to consumers of these APIs when data may lead to an innerHTML assignment.

An example of an assignment which should probably be clearer:
```python
import ipywidgets as widgets
widgets.Checkbox(description="<marquee>this is html</marquee>")
```

Potential ways to address this:

- Switch to textContent assignments. This is the easiest to audit and in many cases may be what users expect.
- Use a sanitizer to sanitize the text before assigning to innerHTML. Good for cases where you want to allow rich content but not arbitrary code execution.
- Require an opt-in to use innerHTML or to disable sanitization.

From a quick glance, a few places that could be worth changing:
- https://github.com/jupyter-widgets/ipywidgets/blob/ab54ea03f90ee1d3ea1b97d390f62a5dd7558fe2/packages/controls/src/widget_bool.ts#L89
- https://github.com/jupyter-widgets/ipywidgets/blob/ab54ea03f90ee1d3ea1b97d390f62a5dd7558fe2/packages/controls/src/widget_description.ts#L78
- https://github.com/jupyter-widgets/ipywidgets/blob/ab54ea03f90ee1d3ea1b97d390f62a5dd7558fe2/packages/controls/src/widget_selection.ts#L463
- https://github.com/jupyter-widgets/ipywidgets/blob/ab54ea03f90ee1d3ea1b97d390f62a5dd7558fe2/packages/controls/src/widget_string.ts#L458

**Comment by jasongrout** [comment]
Thanks. This has also bothered me for a long time too.

**Comment by jasongrout** [comment]
I think a nontrivial fraction of users appreciate being able to do simple styling (bold, italics, colors, etc.) on things like descriptions or checkbox. The widget_selection example is sanitized a few lines above.

**Comment by jasongrout** [comment]
> Require an opt-in to use innerHTML or to disable sanitization.

I like this thought. I think the vast majority of cases are served by textContent. It's nice to have some formatting capability when needed, and for backwards compatibility at this point. I think we probably always ought to sanitize in controls, and have the opt-in to using innerHTML.

**Comment by jasongrout** [comment]
Is there anyone willing to push this forward in the next week or so for 8.0?

**Comment by zerline** [comment]
> Is there anyone willing to push this forward in the next week or so for 8.0?

If nobody more qualified is available, I can find the time.

**Comment by blois** [comment]
I was hoping to be able to get a chance to work on this but have not been able to carve out any time yet. 

I agree that a default of sanitizing with an option to skip sanitization would be a reasonable approach.

**Comment by jasongrout** [comment]
Do you think we ought to default to using textContent, or innerHTML with sanitization and perhaps *very* limited whitelist (like font weight, colors, italics, underline, etc.)?

**Comment by blois** [comment]
On a clean implementation I'd definitely recommend textContent as it avoids surprises when the text happens to contain chars such as `<`. Since this is a breaking change it depends on how often people are using the formatting capabilities.

**Comment by jasongrout** [comment]
@zerline - you may be the one I know that is most using formatting in descriptions, so it would be great to hear your thoughts.

Here is one idea: switch to using textContent by default for descriptions (so no formatting, but no surprises either, just plain text), and have a new `description_html` flag that when it is true, switches to using innerHTML (hopefully with some sanitization)?

**Comment by zerline** [comment]
> @zerline - you may be the one I know that is most using formatting in descriptions, so it would be especially great to hear your thoughts.

It is a rather common practice to have icons within input descriptions. Or links to a footnote (anchors). Styling options should be accepted too (&lt;i&gt;, &lt;b&gt;, ... and &lt;style&gt;)

**Comment by vidartf** [comment]
Did #2785 close this?

**Comment by blois** [comment]
Yes- great work here, thanks @zerline!
