### ISSUE TITLE
Date picker not showing on Safari

### ISSUE THREAD

**Issue by leschiffres** [jupyter-widgets/ipywidgets#2639]
Hi!

For some reason datepicker is not showing in my jupyter notebook. I used pip3 install ipywidgets and then run the command jupyter nbextension enable --py widgetsnbextension, but this specific component is not shown (the rest work normally). Any ideas?

![image](https://user-images.githubusercontent.com/3209404/70702394-48e48d00-1cce-11ea-8185-59c2c58378f6.png)

**Comment by vidartf** [comment]
Does other widgets work?

**Comment by leschiffres** [comment]
Yeah. They work normally.

**Comment by blois** [comment]
What browser? The `<input type="date">` is not supported on all browsers:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#Browser_compatibility

**Comment by leschiffres** [comment]
I was using Safari. That's why it could not open. With chrome date picker works normally. Thanks @blois !
