### ISSUE TITLE
Meta issue for in-person Jan 2020 in-person sprint

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter-widgets/ipywidgets#2641]
As discussed in #2587, there will be an in-person code developer sprint:

**Date**: Jan 6-10, 2020
**Location**: CFM, 23 rue de l'Université, 75007 Paris
**Hours**: 9:30am - 6pm

The goal is to have a push towards ipywidgets 8.0.

Here are a few bullet points for items that we may want to handle for the 8.0 release

[HackMD](https://hackmd.io/ZashAmckQXSdKtU8tG_9dw) for notes

## Packaging

 - drop the dependency of `ipywidgets` to `widgetsnbextension` and of `widgetsnbextension` to `ipykernel`.
 - pattern to split custom widget packages into a pure python package and the different extensions -> to be contributed to the cookiecutters. (Maarten wants to be in this discussion even if he cannot attend the sprints).
 - should we split ipywidgets (python package) into `ipycontrols` and `ipywidget-core`?
 - rewrite the slider without JQueryUI so that we can drop this dependency
 - drop as much of the calls to IPython APIs. These API calls require alternative Python Jupyter kernels (such as xeus-python) to do some monkey-patching of these APIs to support ipywidgets.

## New controls?

 - We have PRs in for tags/colors/inputs (manipulation of sequences of the base trait types) and a text slider.

## The future of BackboneJS in ipywidgets

 - What alternative implementation of the observer pattern should we use?

## Drop deprecated APIs

 - There are a number of deprecated APIs in ipywidgets that we should finally be able to remove.

## Dropping Python 2 support

 - should we also take this occasion to not need the `ipython_genutils` package?

### Drop static directory in custom widgets

 - This is probably only around for legacy reasons.

**Comment by SylvainCorlay** [comment]
@SylvainCorlay @jasongrout @maartenbreddels @martinRenou @vidartf @pbugnion @captainsafia @johanmabille @mariobuikhuizen @wolfv @nthiery @zerline @blois @saulshanabrook @philippjfr @nmearl @eteq.

**Comment by SylvainCorlay** [comment]
Feel free to add new discussion items to the list!

**Comment by zerline** [comment]
@SylvainCorlay do you think we could also examine my PRs about tabindex, tooltip .. ?

**Comment by jasongrout** [comment]
CC also @kaiayoung, @jdfreder, @ellisonbg, @afshin, @mbektasbbg, @ChakriCherukuri, @ibdafna, @cquah

We still have capacity, so if anyone wants to come and help on an intensive sprint towards ipywidgets 8.0 and beyond, please let me or Sylvain know. Unfortunately, we don't have a travel budget to help with expenses.

**Comment by martinRenou** [comment]
We came to some TypeScript improvements ideas with @kaiayoung @mbektasbbg @ibdafna. Currently, there is no type validation on the backbone model. For example `this.model.get('value')` on an `IntSlider` widget should return a `number` while it should return a `string` for a `Text` widget. 

It would be super nice to be able to define the model attributes types in the `WidgetModel.defaults` method implementation.

**Comment by captainsafia** [comment]
Hello everyone! If possible, I'd like to discuss standardizing module resolutions for ipywidgets.

@blois and others from Google brought this up a while back and drafted [this doc](https://github.com/nteract/nes/tree/master/portable-widgets).

ipywidgets support was recently added to nteract and quite a few people have requested support for custom widgets so I'm especially interested in working on this.

Also, I've got some more ideas about things we can improve in ipywidgets, especially from the perspective of implementors. I will update this comment later with concrete pieces of feedback.

**Comment by jasongrout** [comment]
Thanks @captainsafia! Would you be able to attend the meeting too?

**Comment by jasongrout** [comment]
Some more items I'd like to explore for 8.0:

* Moving simple controls implementation to react: #1796 
* Abstracting the data model so that we don't depend on backbone for the data storage. This would make it possible for the widget manager to provide a centralized data store that all widgets use, rather than data being spread out over all widgets. I think this could largely be done in the base widget class, so hopefully would not require huge changes in third-party widgets.

**Comment by jasongrout** [comment]
* triage the 400+ issues we have open

**Comment by jasongrout** [comment]
* Move from travis to github actions?

**Comment by jasongrout** [comment]
* Use prettier for js code, black for python code

**Comment by jasongrout** [comment]
Review/merge:
* https://github.com/jupyter-widgets/ipywidgets/pull/2654
* https://github.com/jupyter-widgets/ipywidgets/pull/2021

**Comment by jasongrout** [comment]
FYI, right now the dev-install script doesn't work on master since the jlab prerelease beta is broken. This should be fixed in the next day or so (we need a new release of jlab). Until then:

```
conda create -c conda-forge -n devw yarn notebook
conda activate devw
pip install --pre jupyterlab
jupyter lab build # fails
```

Apply the following patch to the jupyterlab python installation staging directory (find this directory by `python -c "import jupyterlab; print(jupyterlab.__file__)"`. This temporarily adds some missing dependencies.

```patch
--- staging/package.json	2020-01-06 07:43:28.000000000 +0100
+++ staging/package.json	2020-01-06 07:44:11.000000000 +0100
@@ -56,7 +56,10 @@
     "@jupyterlab/tooltip-extension": "~2.0.0-beta.1",
     "@jupyterlab/ui-components-extension": "~2.0.0-beta.1",
     "@jupyterlab/vdom-extension": "~2.0.0-beta.1",
-    "@jupyterlab/vega5-extension": "~2.0.0-beta.1"
+    "@jupyterlab/vega5-extension": "~2.0.0-beta.1",
+    "vega": "^5.9.0",
+    "vega-embed": "^6.2.1",
+    "vega-lite": "^4.0.2"
   },
   "devDependencies": {
     "@jupyterlab/buildutils": "^2.0.0-beta.1",
```

**Comment by jasongrout** [comment]
> FYI, right now on master, ipywidgets doesn't work in jlab or the latest jlab beta

JupyterLab had a new beta released, and things seem to work fine now. So feel free to run the dev-install script after doing `pip install --pre jupyterlab` to pull in JupyterLab 2.0b2.

**Comment by vidartf** [comment]
@captainsafia Is there a time for you that would be good for calling in to discuss module resolution etc? We are typically all in during 10-18 CET.

**Comment by jasongrout** [comment]
Thanks everyone for the successful sprint!
