### ISSUE TITLE
Ipiwidgets to flask app

### ISSUE THREAD

**Issue by kfk** [jupyter-widgets/ipywidgets#2643]
If I wanted to translate ipywidgets into a flask app programmatically, where should I start? I am thinking it should be doable to take an applayout container as an input and generate a flask view as an output.

**Comment by maartenbreddels** [comment]
Try out https://github.com/maartenbreddels/flask-ipywidgets

(from mobile phone)

**Comment by martinRenou** [comment]
I guess it is safe to close this issue now. But feel free to reopen it if needed! :)
