### ISSUE TITLE
change value from js without sending to python

### ISSUE THREAD

**Issue by bdch1234** [jupyter-widgets/ipywidgets#2644]
On the below page there is a solution for updating widget values from javascript, and have that propagate to python: 

https://stackoverflow.com/questions/33028218/set-an-ipython-widget-value-from-javascript

How can I update values from javascript but making sure that any changes do NOT propagate to python model (but jslinks still work etc)?

Also, I was planning to do this in an app hosted with voila, but it does not seem to work to get WidgetManager as in above solution when it is hosted like so. Is there another way of doing that which works in voila?

**Comment by martinRenou** [comment]
> Also, I was planning to do this in an app hosted with voila, but it does not seem to work to get WidgetManager as in above solution when it is hosted like so. Is there another way of doing that which works in voila?

What was the exact issue you had? I suspect you need to tell Voila to use the nbextension installed on the machine (instead of downloading it from npmjs, which is the default behavior), using:
```
voila my_notebook.ipynb --enable_nbextensions=True
```

Concerning your initial question, you can do:
```JavaScript
this.model.set('value', 32);
```
This will set the JavaScript model but won't propagate the change to Python. Propagating the change to Python is done by:
```JavaScript
this.model.save_changes();
```

**Comment by martinRenou** [comment]
Closing this. But feel free to ask more questions :)

**Comment by bdch1234** [comment]
> What was the exact issue you had? I suspect you need to tell Voila to use the nbextension installed on the machine (instead of downloading it from npmjs, which is the default behavior), using:

The issue is this line:
```python
IPython.WidgetManager._managers[0];
```
It seems that IPython is not available when running from voila. I tried both with and without nbextensions with the same results. Is there perhaps some self-contained js-file I can use to make it available from voila?
