### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by fitoprincipe** [jupyter-widgets/ipywidgets#2645]
I am creating a custom widget using in Jupyter Notebook that in some point hangs my browser, so I decided to have a look at the memory usage. Reading [this](https://stackoverflow.com/questions/33978/find-out-how-much-memory-is-being-used-by-an-object-in-python) and [this](https://stackoverflow.com/questions/449560/how-do-i-determine-the-size-of-an-object-in-python), I understand that is not always straightforward. But after reading [this](https://jakevdp.github.io/PythonDataScienceHandbook/01.07-timing-and-profiling.html#Profiling-Memory-Use:-%memit-and-%mprun), I decided to try with memory_profiler.

I realized that using any widget increases the memory usage in a way I don't understand. Maybe it is not the correct way to measure the memory usage, but it's what I have.

First I load

    from ipywidgets import *
    %load_ext memory_profiler

Then measure a simple object

    test = HTML()
    %memit test
    >> peak memory: 57.00 MiB, increment: 0.26 MiB

Then added some content and measure

    test.value = '<b>HELLO WORLD</b>'
    %memit test
    >> peak memory: 57.05 MiB, increment: 0.01 MiB

Ok, not much added. Then I display it

    test

**HELLO WORLD**

Then measure again

    %memit test
    > peak memory: 57.43 MiB, increment: 0.01 MiB

Ok, seems like the memory usage increases when displaying the widget, it's fine!

But... if I make a new widget

    test2 = HTML()
    %memit test2
    > peak memory: 57.46 MiB, increment: 0.00 MiB

1. Why does `test2` occupy more memory than test displayed? And this keeps accumulating over and over.
2. What do I have to do to make `test2` occupy the same amount of memory as test when it was just created?

**Comment by vidartf** [comment]
> Reading (this) and (this)

Were those supposed to be links? if so they disappeared.

> Why does test2 occupy more memory than test displayed? And this keeps accumulating over and over.

I'm not sure how `memit` counts the memory use. Does it count class attributes as well (i.e. attributes that are shared between all instances of the class)?

**Comment by fitoprincipe** [comment]
Hi @vidartf ! Thanks! I am sorry, I've updated the question now =)

**Comment by fitoprincipe** [comment]
I also asked on SO: https://stackoverflow.com/questions/59376252/ipython-widget-memory-usage

**Comment by martinRenou** [comment]
Just a note on the fact you can use @jtpio 's widget for displaying memory used by the kernel: https://github.com/jtpio/ipyresuse

**Comment by fitoprincipe** [comment]
Thanks @martinRenou , I did't know that repo =)

**Comment by martinRenou** [comment]
I am far from being an expert in this, but if your browser freezes, I suspect it is the front-end that uses too much memory or too much CPU time. Maybe there is a JavaScript profiler in your browser's developer tools?

We are currently doing an issue triage. Would you mind if we close this issue? :)

**Comment by fitoprincipe** [comment]
I don't mind at all! I will just write down your suggestion =)

**Comment by martinRenou** [comment]
Thanks!
