### ISSUE TITLE
Play Widget: remove the pause button

### ISSUE THREAD

**Issue by jtpio** [jupyter-widgets/ipywidgets#2671]
Most players out there use a single button that toggles between a "Play" and a "Pause" state.

For now the `Play` widget in `ipywidgets` has both:

![image](https://user-images.githubusercontent.com/591645/71889021-98896d80-3141-11ea-8161-a0c91c280ea3.png)

How about removing it and keep only one button instead?

**Comment by jasongrout** [comment]
> How about removing it and keep only one button instead?

That sounds great to me.
