### ISSUE TITLE
Jupyter widget list document page is bugged

### ISSUE THREAD

**Issue by tonywang531** [jupyter-widgets/ipywidgets#2702]
See the links:
https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html

At first I could not find the widget list page, then I realized this is the page. Does this mean new widgets are coming?

**Comment by pbugnion** [comment]
Well spotted! Should be fixed by #2704 (thanks @jtpio !). I'll check the build process and report here.

**Comment by pbugnion** [comment]
I've raised [this issue](https://github.com/spatialaudio/nbsphinx/issues/374) in nbsphinx to avoid future errors.

Alternatively, we could check the notebooks with nbformat ourselves in the CI pipeline.
