### ISSUE TITLE
Documentation: "Widget List" section acutally does not display the widgets.

### ISSUE THREAD

**Issue by sitnarf** [jupyter-widgets/ipywidgets#2726]
![Screenshot_20200111_180831](https://user-images.githubusercontent.com/289991/72207970-c520ea80-349d-11ea-8429-6266cfd99ee4.png)

**Comment by SylvainCorlay** [comment]
In the "latest" section of the documentation it is a known issue because the currwnt backend requires a unreleased version of the frontend.

**Comment by jasongrout** [comment]
Closing as answered - this will be fixed when we do a release.
