### ISSUE TITLE
Unexpected truncation of VBox when using Tab

### ISSUE THREAD

**Issue by tonywang531** [jupyter-widgets/ipywidgets#2738]
For some reason, when I create a tab with identical VBox contents, the second tab's graph object becomes shorter (truncated). The logical expectation is they should have the same width. Here is a sample code to create such "bug".

```
from ipywidgets import *
import plotly
import plotly.graph_objects as py 
fig = py.FigureWidget(layout = plotly.graph_objs.Layout(title = ""))
box = widgets.VBox([fig])
tab_contents = ['1', '2']
children = [box, box]
tab = widgets.Tab(children = children)
for i, j in enumerate(tab_contents):
    tab.set_title(i, j)
display(tab)
```
I suspect this has something to do with Figure widget from plotly. As I have tried other standard widgets and it displays without problem.  How do I fix such issue?

**Comment by martinRenou** [comment]
Maybe try to set the size of the figure so that it takes the available space? Something like:
```python
fig.layout.width = 'auto'
fig.layout.height = 'auto'
```

**Comment by martinRenou** [comment]
Well I don't really know plotly myself, but it looks like they overwrote the layout attribute with their custom logic. I wonder if this question should not be asked directly to the plotly teams.

**Comment by tonywang531** [comment]
> Maybe try to set the size of the figure so that it takes the available space? Something like:
> 
> ```python
> fig.layout.width = 'auto'
> fig.layout.height = 'auto'
> ```

Thanks for the suggestion. It appears that the length and width have to be int so setting to "auto" will not work. Plotly does have the property of autosize. However setting to to True still results in truncation of the graph. Right now the only way is to set it to fixed pixel for example 600 or 800 etc. 

Is there a way to return the width of notebook cells as int? Since the resolution for different PC can be different, I wish to set the width like [width='100%'].

**Comment by tonywang531** [comment]
On a related note, plotly figure widget does not seem to allow update scatter graph to a plotly table . These seems to be of different instances and there one cannot use fig.data = new data. Therefore once you have created a plotly table it will remain as a plotly table, you can update its value, make changes to the number of columns, but you cannot make it into something like a scatter plot.

There is a workaround for this. This refers to an earlier issue I have opened before. As in issue 451 mentioned by DougRzz:
https://github.com/voila-dashboards/voila/issues/451
Nest the figure widget inside a HBox. After changing the data, reset the children again, then the figure widget can become a different type. There is a slight side effect of screen flickering for like less than one second which I think is unavoidable.

**Comment by tonywang531** [comment]
Closing as it is more of a problem for the Plotly library than ipywidget
