### ISSUE TITLE
How to make interact ignore arguments?

### ISSUE THREAD

**Issue by TomNicholas** [jupyter-widgets/ipywidgets#2740]
Hi,

Firstly, widgets are amazing.

Now, I'm trying to create an interactive plotting function with a signature like `interactively_plot(data, plotfunc, **kwargs)`. To do that I want to pass the function I want to `interact` with some arguments, which `interact` is to ignore, e.g.

```python
def plotfunc(data, **kwargs):
    return data.plot()

def interactively_plot(data, plotfunc, **kwargs):
    wrapped = functools.partial(plotfunc, data=data)
    return interact(wrapped, **kwargs)
```

**However**, `functools.partial` doesn't behave as expected in this context: `interact` is still demanding that `data` be treated as a widget.

Here's a minimum example that demonstrates my problem

```python
from ipywidgets import interact
from functools import partial, update_wrapper

# This is to avoid the error
# AttributeError: 'functools.partial' object has no attribute '__name__'
def wrapped_partial(func, *args, **kwargs):
    partial_func = partial(func, *args, **kwargs)
    update_wrapper(partial_func, func)
    return partial_func

def g(dat, x):
    print("dat={dat} from inside g")
    return dat

g_plus_dat = wrapped_partial(g, dat='a')

interact(g_plus_dat, x=10)

```
which raises
```
Traceback (most recent call last):
  File "/home/tegn500/Documents/Work/Code/experimentation/xwidget/mwe_partial.py", line 17, in <module>
    interact(g_plus_dat, x=10)
  File "/home/tegn500/anaconda3/lib/python3.7/site-packages/ipywidgets/widgets/interaction.py", line 528, in __call__
    w = self.widget(f)
  File "/home/tegn500/anaconda3/lib/python3.7/site-packages/ipywidgets/widgets/interaction.py", line 444, in widget
    return self.cls(f, self.opts, **self.kwargs)
  File "/home/tegn500/anaconda3/lib/python3.7/site-packages/ipywidgets/widgets/interaction.py", line 188, in __init__
    new_kwargs = self.find_abbreviations(kwargs)
  File "/home/tegn500/anaconda3/lib/python3.7/site-packages/ipywidgets/widgets/interaction.py", line 288, in find_abbreviations
    raise ValueError('cannot find widget or abbreviation for argument: {!r}'.format(name))
ValueError: cannot find widget or abbreviation for argument: 'dat'
```
I don't understand how what I've done is different from the use of `functools.partial` in [this answer](https://stackoverflow.com/a/45473481/3154101).

I could possibly get around this by [using closures](https://stackoverflow.com/a/45473481/3154101), but I really would rather not. I would also eventually like to do something [similar but with methods](https://stackoverflow.com/questions/56567251/telling-ipython-interact-widget-to-ignore-self-argument-in-oop).

**Comment by pbugnion** [comment]
Thanks for raising this! 

> Firstly, widgets are amazing.

Thanks for your kind words.

I'm not sure about that StackOverflow answer, but I note it's two years old. `interact` has changed a bit since then. I haven't tried it specifically, but I don't think it would work.

*Solutions*

You can either use `fixed` to tell interact to pass parameters through to your function without changing them:

```python
from ipywidgets import interact, fixed

def g(dat, x):
    print(f"dat={dat}, x={x} from inside g")
    return dat

interact(g, x=10, dat=fixed("a"));
```

... or you can use a lambda. You mentioned wanting to avoid closures, so I'm not sure if this fits your use case:

```python
from ipywidgets import interact

def g(dat, x):
    print(f"dat={dat}, x={x} from inside g")
    return dat

interact(lambda x: g("a", x), x=10);
```

*Why functools.partial doesn't work*

As far as I can tell, the callable returned by `functools.partial` is not a proper closure. With your example, this works as you might expect of a closure:

```python
g_plus_dat(x=5)
#=>  dat=a from inside g
```

... however, unexpectedly, I can *still* pass in `dat`:

```python
g_plus_dat(x=5, dat="b")
#=>  dat=b from inside g
```

The [documentation](https://docs.python.org/3/library/functools.html#functools.partial) says:

> If additional keyword arguments are supplied, they extend and override keywords

So `g_plus_dat` still has the same *signature* as `g`, to allow passing in an override for `dat`. `interact` then inspects `g_plus_dat` and determines that it should be a widget. Evidently, at some point in the past, interact behaved slightly differently, since I assume the SO answer worked.

**Comment by TomNicholas** [comment]
Thanks for the quick reply!

> You can either use fixed to tell interact to pass parameters through to your function without creating a widget for them

That seems like a reasonable solution.

> ... or you can use a lambda:
>
> (you mentioned wanting to avoid closures, but inasmuch as closures are the right solution for specifying some of a function's arguments, I'm not sure avoiding them makes sense)

The reason I wanted to avoid closures is because the pattern of nested functions seemed like it might produce code that was harder to understand and unit test, whereas `functools.partial` makes it obvious what's happening (for me personally). Do you think closures are the right pattern to use here? Even if the wrapped logic becomes complex? The full setup I want to implement would look more like 

```python
from xarray import register_dataarray_accessor

@register_dataarray_accessor('interactive')
class InteractiveAccessor:
    def __init__(self, da):
        self.data = da

    def plot(self, plotfunc, **kwargs):
        widget_ready_kwargs = interrogate(**kwargs)
        wrapped = functools.partial(plotfunc, data=self.data)
        return interact(wrapped, **widget_ready_kwargs)

# to allow an API like
da.interactive.plot(plotfunc, time=20, position=4.5, ...)
```

> As far as I can tell, the callable returned by functools.partial is not a proper closure.

Hmm okay, I wonder if there's a way to force it to act like a proper closure...

> Evidently, at some point in the past, interact behaved slightly differently, since I assume the SO answer worked.

Huh, okay. In that case once I have this working I'll update that SO answer, as I'm would think other people might want to implement a similar pattern.

**Comment by pbugnion** [comment]
> Do you think closures are the right pattern to use here?

If you can use `fixed`, it'll probably lead to somewhat more readable code than nested functions or lambdas.

> I wonder if there's a way to force it to act like a proper closure

I suspect just using closures is what you're supposed to do.

> the pattern of nested functions seemed like it might produce code that was harder to understand and unit test

Yes, having to write nested functions is definitely harder to understand. However, it feels like using a lambda as in:

```python
from ipywidgets import interact

def g(dat, x):
    print(f"dat={dat}, x={x} from inside g")
    return dat

interact(lambda x: g("a", x), x=10);
```

is fairly readable.

**Comment by pbugnion** [comment]
>  In that case once I have this working I'll update that SO answer, as I'm would think other people might want to implement a similar pattern.

Thank you! That would be great! Do link to this issue.

**Comment by pbugnion** [comment]
Closing this issue since it's resolved. Do re-open if I'm missing something.
