### ISSUE TITLE
Error on FileUpload

### ISSUE THREAD

**Issue by ahulist** [jupyter-widgets/ipywidgets#2744]
I recently updated `ipywidgets` to 7.5 to try `FileUpload` widget. Yet this code (in Jupyter):
```
import ipywidgets as w
upload = w.FileUpload(accept='.json')
display(upload)
```

gives a JS error in console:

![error](https://i.imgur.com/7p8lufO.png)

Same error on both Opera and Chrome. This causes no widget to be displayed in Jupyter.

**Comment by vidartf** [comment]
You could try reinstalling the new nbextension, in case that was not updated correctly when you updated ipywidgets. `jupyter nbextension install --sys-prefix --py widgetnbextension`. Alternatively, try uninstalling ipywidgets and widgetnbextension, andre reinstalling them.

**Comment by ahulist** [comment]
Unfortunately, this was not the case. I installed both in fresh environment and still got
`Uncaught (in promise) Error: Cannot find model module @jupyter-widgets/controls@1.5.0, FileUploadModel`

**Comment by vidartf** [comment]
@ahulist Would you mind sharing the commands you use to install in a fresh environment? It would hopefully make it easier to reproduce.

**Comment by ahulist** [comment]
Sure. I used the standard `conda create --name py38 python=3.8` (same effect with python 3.6). The only thing I can think of is the fact that it is a system-wide conda with multiple users having their own user environments.
If you can think of any necessary test, I will gladly carry it out.

**Comment by ahulist** [comment]
Now that I wrote that I got an idea and running `jupyter nbextension install **--user** --py widgetsnbextension` solved the problem.
Thank you for the assistance.

**Comment by vidartf** [comment]
Closing as resolved then, thanks for sharing your solution!
