### ISSUE TITLE
Play Widget does not stop updating when output is cleared

### ISSUE THREAD

**Issue by LunarLanding** [jupyter-widgets/ipywidgets#2747]
Hi, I hope I can get some guidance.
I'm trying to use ipywidgets play widget with k3d.
However, if I leave the play widget in the play and repeat state, and then re-run the cell that outputs it, the old play widget keeps updating on the background a plot that is no longer displayed.
I understand there might be a use for keeping these widgets in memory; what would be the most practical way to trigger the removal of the widget as soon as the output is cleared?
Here's a notebook example:

https://gist.github.com/LunarLanding/932e5095eb0f989816f9b674812300d9

**Comment by jasongrout** [comment]
A kludge would be to listen to the view count of the widget, and close it when the view count reached zero. To get the view count to track views (an undocumented, somewhat unsupported 'feature'), first set `_view_count` to 0.

For example:

```python
def close_on_zero(change):
    if change.new is not None and change.new == 0:
        change.owner.close()
```
```python
p = Play(repeat=True, interval=500, _view_count=0)
p.observe(close_on_zero, '_view_count')
p
```
Start playing the widget. Then clear the output or overwrite it somehow. Notice that once the view goes away, the widget is closed and the playing stops.

**Comment by LunarLanding** [comment]
Thanks, it works!
