### ISSUE TITLE
More problems in the documentation examples

### ISSUE THREAD

**Issue by tonywang531** [jupyter-widgets/ipywidgets#2759]
This is the stable version not the latest version that contains bugs. 

Please refer to the link

https://ipywidgets.readthedocs.io/en/stable/examples/Layout%20Templates.html#Creating-scatter-plots-using-GridspecLayout

The example could not be displayed due to import error:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-29-8a9727022650> in <module>
----> 1 import bqplot as bq
      2 import numpy as np
      3 from ipywidgets import GridspecLayout, Button, Layout
      4
      5 n_features = 5

ModuleNotFoundError: No module named 'bqplot'

I have just found another problem in another section
https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Styling.html#Image-layout-and-sizing

The section image layout and sizing is repeated twice.

**Comment by jasongrout** [comment]
> ModuleNotFoundError: No module named 'bqplot'

This is fixed in master: https://ipywidgets.readthedocs.io/en/latest/examples/Layout%20Templates.html


> The section image layout and sizing is repeated twice.

This is fixed in master: https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Styling.html#Image-layout-and-sizing
