### ISSUE TITLE
Output widget should use .value instead of .outputs?

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#2760]
In https://github.com/jupyter-widgets/ipywidgets/issues/2388#issuecomment-485038702, I mention that the output widget should probably use `.value` instead of `.outputs`. Thoughts?

Tagging as 8.0 as this definitely would be a breaking change.

**Comment by vidartf** [comment]
I think an output widget is conceptually more  similar to a layout container, e.g. a `Box`. The boxes have `children`, not `value`, so I think there is a consistency here that makes sense.

**Comment by jasongrout** [comment]
I think that argument is compelling. Certainly the "value" here is not a typical value you could link with other widgets's values.

**Comment by jasongrout** [comment]
Plus, one of the things about value widgets is they are used for interacts. I can't see an output widget being used as an input for an interact value very naturally.
