### ISSUE TITLE
Requesting new widget type

### ISSUE THREAD

**Issue by tonywang531** [jupyter-widgets/ipywidgets#2763]
First of all, thank you for all the work so far. I have managed to make a UI with these and even into dashboard with Voila. 

This is related to issue number #1239. My current concerns is that the current dropdown widget allows selection of one value only. Is there a need for such restriction? I think it is not difficult to create another dropdown widgets which allow multiple list selections. SelectMultiple widget does the work, but imagine if there is like more than 10 items in the list, it will look messy. This is why I believe dropdown allows better representation. 

Another improved dropdown widget would be allow multiple level selection (list with hierarchy). Similar to the default menu in Jupyter notebook:

![image](https://user-images.githubusercontent.com/51065728/73323903-61176800-428c-11ea-8b82-a73d62608b39.png)

By allowing lists to have different levels, it simplifies the number of widgets to 1. Currently I have to use 2 different dropdown widgets to do this. 

Meanwhile I will try to make these as a custom widget, but integrating these widgets into default list would be nice.

**Comment by jasongrout** [comment]
The core set of widgets is intentionally constrained to essentially browser html controls and a few very limited common container (like tabs or accordions). For more advanced widgets, I encourage you to look at things like [ipyvuetify](https://github.com/mariobuikhuizen/ipyvuetify) or [ipymaterial](https://github.com/maartenbreddels/ipymaterialui) which wrap much more complex and full-featured UI systems, or like you said, make a custom widget. We've worked really hard to build a framework so there can be a robust ecosystem of widget packages beyond the core widgets.

Thanks! I look forward to seeing more widgets in the ecosystem!

**Comment by jasongrout** [comment]
That said, I've heard multiple people request a multi-select widget that was more than the list box the browser provides, but perhaps more like a list of checkboxes. Perhaps a nice multiselect widget based on checkboxes could be one of the exceptions in core ipywidgets by popular request. First it would probably be best to develop as a custom widget, and then move to core if it was extremely popular and just used standard browser checkboxes, etc.

**Comment by tonywang531** [comment]
I have been using Plotly recent for greater control and customization. The default dropdown component which can contain "multi" value, seems very neat and easy to use. If I have spare time, I am probably going to recreate something like that.

https://dash.plot.ly/dash-core-components/dropdown

**Comment by jasongrout** [comment]
> If I have spare time, I am probably going to recreate something like that.

Great! Feel free to post an update here when you do this. I'll close this issue for now to help us manage the issue queue.
