### ISSUE TITLE
"Loading widgets" message should be replaced with an error when there is no widget support

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#2764]
In #2623, we saw that the code console (which does not support widgets) just continued to display a "Loading widgets" message instead of indicating that widgets were not supported.

I [said](https://github.com/jupyter-widgets/ipywidgets/issues/2623#issuecomment-579409913):

> That's a pretty unhelpful message. What is happening is that there is a global widget rendermime that immediately says things are loading, and later on the widget manager gets connected to the kernel and for that specific activity and starts rendering widgets for real. The console will get that global rendermime renderer. What it should do is, after a short time, go ahead and render the text version, or some sort of message saying the widgets are not supported in that activity. Or perhaps we don't need to wait if we know we are in a console.

**Comment by jasongrout** [comment]
Here is what it looks like now, with ipywidgets current master b3708e1305248b132999322266aab07c7e9ec3dc
<img width="605" alt="Screen Shot 2020-01-29 at 5 43 00 AM" src="https://user-images.githubusercontent.com/192614/73361682-4deba480-425a-11ea-8a79-767fc150b054.png">

**Comment by steveepreston** [comment]
still having this issue in 2024, in Kaggle TPU VM Notebooks

**Comment by martinRenou** [comment]
ipywidgets is now supported in the JupyterLab console. @steveepreston I'd suggest updating to the latest ipywidgets if not done already! Otherwise I believe you're having another issue

**Comment by martinRenou** [comment]
I'm not sure this is a valid workflow. What is the ipywidgets version you have if you don't run `!pip install ipywidgets --upgrade`?

**Comment by steveepreston** [comment]
the ipywidgets is not installed by default in Kaggle TPU VM env (`No module named 'ipywidgets'`).

can you explain why you are not sure that this is a valid workflow?
just 3 lines of code to reproduce:

```python
!pip install ipywidgets --upgrade

from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased", clean_up_tokenization_spaces=True)
```

**Comment by martinRenou** [comment]
Do you see errors in the JavaScript console?

> can you explain why you are not sure that this is a valid workflow?

I'm thinking that if ipywidgets was not installed in the kaggle deployment in the first place, then the JavaScript code for ipywidgets may be missing.
