### ISSUE TITLE
Edit Combobox dropdown? 

### ISSUE THREAD

**Issue by tonyluo98** [jupyter-widgets/ipywidgets#2770]
Using the combobox widget with a large list of options results in a large dropdown box being displayed with all the options when you press the text box. I was wondering if it was possible to limit the number rows the scrollable dropdown menu displays?

**Comment by jasongrout** [comment]
Good question. We are using the built-in browser functionality that provides that dropdown. Looking at the example at https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist, it appears that firefox and safari limit it to 6 options before scrolling, but chrome uses the full vertical space to list as many options as it can.

**Comment by jasongrout** [comment]
I looked around, and I don't see a way to change Chrome's behavior of using as much space as it can for the datalist.

**Comment by vidartf** [comment]
You might be able to gain more control by using a component library like https://github.com/maartenbreddels/ipymaterialui

**Comment by tonywang531** [comment]
Since the exact behavior differs from browser to browser, I wonder what about using custom written component using Python GUI like Tkinter? Is this bad design?

**Comment by jasongrout** [comment]
>  I wonder what about using custom written component using Python GUI like Tkinter?

The reference controls in ipywidgets are browser-based, so would not be able to use something like Tkinter.

**Comment by jasongrout** [comment]
Closing as answered. As @vidartf suggested, you could use a widgets library like [ipymaterialui](https://github.com/maartenbreddels/ipymaterialui) or [ipyvuetify](https://github.com/mariobuikhuizen/ipyvuetify) for more full-featured controls and UX designs.
