### ISSUE TITLE
Saving output controlled by Play widget as gif?

### ISSUE THREAD

**Issue by TomNicholas** [jupyter-widgets/ipywidgets#2774]
I currently have a function which plots some data as a function of the value of a widget. By passing in the `Play()` widget, I can create an animation within the jupyter notebook, which is great.

![](https://user-images.githubusercontent.com/35968931/72755630-de731680-3bc2-11ea-9d0f-46da96d6efda.gif)

I would like to save this animation (e.g. as a gif or video), but I've not found any way to do this. Does anyone know if this functionality exists anywhere?

If not, would it be something which could be implemented in ipywidgets? Or in jupyter more generally? It would require:
-  Capturing the output of the notebook cell on each update of the widget value (probably requiring something similar to what's described in [this jupyter issue](https://github.com/jupyter/notebook/issues/3039)) - this might be the hard bit though,
- Saving each output frame, probably allowing the user to specify the output type,
- Then stitching the resulting frames together using `imagemagick` or `ffmpeg`. 

Perhaps it might be used as (if the output object has a html representation and you wanted to save a `.gif` file)
```python
with SaveOutput.from_html().to_gif(fps=5, backend='imagemagick'):
    interactive.isel(da, xplot.plot, time=Play())
```

**Comment by jasongrout** [comment]
Interesting. I'm not sure what `interactive.isel` is, but perhaps that function could save the image as a png?

It is a more difficult problem to convert an arbitrary output to png. @maartenbreddels has explored some ideas around this. Probably what is easier is to have whatever is generating the actual plot save that plot as an image.

**Comment by TomNicholas** [comment]
> I'm not sure what interactive.isel is

Sorry, it's basically a (WIP) wrapper of `ipywidgets.interactive` and `xarray.DataArray.isel` that allows me to use a widget to select a value along a dimension of a multidimensional `xarray.DataArray` object. In this case along the `'time'` dimension of the data object `da`.

> perhaps that function could save the image as a png?

Yes fair point, although then you need to run something else later to join up all the pngs (which is fine, just less neat).

I was originally thinking that this could be done in a general way in the `widgets.Play()` code or the `interactive.update()` method, but you're probably right that this should really be done in my `interactive.isel` or my `plot` function. (and then for general png output one could allow the user to pass whatever writer function they wanted)
