### ISSUE TITLE
 How to hide the tree of an ipywidgets application with appmode?

### ISSUE THREAD

**Issue by idespindola** [jupyter-widgets/ipywidgets#2782]
I created a simple application for my work using ipywidgets with Appmode. I need to hide the tree of notebook in AppMode On (I practically want to hide the logo and the link below.).

![sistema-mostrar](https://user-images.githubusercontent.com/13322651/74393690-8ad2a200-4de9-11ea-8084-90e95644e95b.png)

**Comment by jasongrout** [comment]
Are you talking about this project: https://github.com/oschuett/appmode ? Can you file this issue there? Ipywidgets doesn't have any control over how that app mode works.
