### ISSUE TITLE
Do not capture stderr with output widget?

### ISSUE THREAD

**Issue by sladekm** [jupyter-widgets/ipywidgets#2784]
Is it possible to capture only stdout and not stderr with output widget?
So that:

```
with out:
    sys.stdout.write('Some output to stdout') #this would get cleared
    sys.stderr.write('Some output to stderr') #this would not get cleared
    clear_output()
```

**Comment by jasongrout** [comment]
Not currently. That would probably involve changing how the output widget works (in particular, sending not just a captured message id to the frontend, but also which streams to capture).

I suppose you could manually inspect the output widget outputs and do the selective clear yourself, if you wanted.
