### ISSUE TITLE
[Feature Request] Option to let @jupyter/html-manager import js files from cdn directly

### ISSUE THREAD

**Issue by Bobgy** [jupyter-widgets/ipywidgets#2786]
Current behavior is: https://github.com/jupyter-widgets/ipywidgets/blob/4b485b1ed34325b927362e0a67a4aa7dfa71e1c5/packages/html-manager/src/libembed-amd.ts#L65

1. load using requirejs first
2. if 1. fails, load from cdn

## Context
However, as I investigated in issue: https://github.com/kubeflow/pipelines/issues/3114
My application is deployed in a secured cluster, it is exposed to user through a proxy that checks some cookies for authentication. However, the embedded jupyter widget visualization is run in a sandboxed iframe, so it will never be able to talk to same site urls. This caused the infinite redirection error. (the widget still loads successfully falling back to cdn, but it takes about 2 seconds to wait for the meaningless redirections.)

## Feature Request
Therefore, I'm proposing this feature request. I think if we can configure behavior to load from cdn directly that will solve the problem for us.

Add an option similar to `data-jupyter-widgets-cdn` to skip the first try and load from cdn directly.

**Comment by jasongrout** [comment]
Can you write your own loader, based on that requireLoader, and instantiate the HTML manager with that loader that does what you want? That `requireLoader` function is just the default, but it is meant to be overridden if you want a different behavior: https://github.com/jupyter-widgets/ipywidgets/blob/4b485b1ed34325b927362e0a67a4aa7dfa71e1c5/packages/html-manager/src/libembed-amd.ts#L94-L97

**Comment by Bobgy** [comment]
@jasongrout Thanks for the suggestion.
I'm currently using `<script src="https://unpkg.com/@jupyter-widgets/html-manager@^0.18.0/dist/embed-amd.js" crossorigin="anonymous" data-jupyter-widgets-cdn="https://cdn.jsdelivr.net/gh/Bobgy/model-analysis@kfp/tensorflow_model_analysis/notebook/jupyter/js/dist/" crossorigin="anonymous"></script>`
This script tag to load html-manager. Can you point me to where I can add the requireLoader customization?

**Comment by Bobgy** [comment]
I guess I found something close, am I expected to use the libembed-amd.js and call it as a library?
https://github.com/jupyter-widgets/ipywidgets/blob/4b485b1ed34325b927362e0a67a4aa7dfa71e1c5/packages/html-manager/scripts/concat-amd-build.js#L13

But I didn't find any usage example, is there any documentation out there?

**Comment by jasongrout** [comment]
I didn't realize you were loading the pre-built manager (with the default loader) from a CDN, rather than using the html manager as a library in your own code. For that usecase, I think you're right that a configuration option would be the most convenient, and certainly similar to the cdn configuration option. Do you want to submit a PR?

**Comment by Bobgy** [comment]
Thanks, I'll see if I have time soon. Doesn't seem like a complex change to me.

**Comment by jasongrout** [comment]
I think you are right that it should be pretty straightforward, especially if you follow the pattern in that file already for the other data attribute.

**Comment by Bobgy** [comment]
FYI, sent https://github.com/jupyter-widgets/ipywidgets/pull/2792 to resolve this.
