### ISSUE TITLE
How to create a button to lock/unlock user's input

### ISSUE THREAD

**Issue by RichardoTiono** [jupyter-widgets/ipywidgets#2791]
Hi, I am trying to find a way to create a button to lock/unlock user's input. So far I found that Togglebutton doesn't have on_click handler so I try to use button but can only manage to do oneway exchange for ex: lock->unlock but not unlock->lock. This is the code I used
```python
class LockButton(widgets.Button):
    """A file widget that leverages tkinter.filedialog."""

    def __init__(self):
        super(LockButton, self).__init__()
        # Add the selected_files trait
        self.add_traits(files=traitlets.traitlets.List())
        # Create the button.
        self.description = "Lock"
        self.icon = "lock"
        self.style.button_color = "#ada9a4"
        # Set on click behavior.
        if(self.description=='Lock'):
            self.on_click(self.get_input)
        else :
            self.on_click(self.first_input)

    @staticmethod
    def get_input(b):
        """Generate instance of tkinter.filedialog.

        Parameters
        ----------
        b : obj:
            An instance of ipywidgets.widgets.Button 
        """
        # Create Tk root
        root = Tk()
        # Hide the main window
        root.withdraw()
        # Raise the root to the top of all windows.
        root.call('wm', 'attributes', '.', '-topmost', True)
        # List of selected fileswill be set to b.value
        b.description = "Unlock"
        b.icon = "unlock"
        b.style.button_color = "#b8b8bb"
    
    @staticmethod   
    def first_input(a):
        """Generate instance of tkinter.filedialog.

        Parameters
        ----------
        b : obj:
            An instance of ipywidgets.widgets.Button 
        """
        # Create Tk root
        root = Tk()
        # Hide the main window
        root.withdraw()
        # Raise the root to the top of all windows.
        root.call('wm', 'attributes', '.', '-topmost', True)
        # List of selected fileswill be set to b.value
        a.description = "Lock"
        a.icon = "lock"
        a.style.button_color = "#ada9a4"
```
Can someone give me advice/help for this problem? Thank you

**Comment by jasongrout** [comment]
I'm really confused about what you are trying to do (I don't know what you mean by "user's input", and I'm confused by what you are trying to do with tkinter), so this may not be helpful: the init method is only run once, so you are only setting that handler once with your if statement.

The toggle button changes its state value when the button is toggled. Perhaps you could trigger off of that state value change?

**Comment by RichardoTiono** [comment]
ah sorry if it isn't complete, so I have a text area that will receive user's input. When the lockbutton is clicked, I want to retrieve the value from text area and change the text into not able to receive user's input anymore kinda like locked state and the lockbutton icon change into locked icon. When the user click the lockbutton again it will revert to previous version and the text area able to receive user's input again. I hope it is clear 

And about the tkinter truthfully I am still learning about it and I copy those from another website and modify it. What i was hoping is something like a toggle button for locking and unlocking a textarea

**Comment by jasongrout** [comment]
How about something like this?

```python
from ipywidgets import Textarea, ToggleButton, VBox, link

text = Textarea()
button = ToggleButton(description="Lock")
link((button, 'value'), (text, 'disabled'))
display(VBox([text, button]))
```

**Comment by RichardoTiono** [comment]
Hi, I have tried your solution, and I found out that after clicking the button, even though it makes the textarea become inactive I can still fill in on the textarea, is it possible to fully disabled the textarea until I click the button for the second time? And is it possible to retrieve the value on textarea when click the button for the first time? Thank you in advance
