### ISSUE TITLE
Importing 'GridspecLayout' from 'ipywidgets' issue

### ISSUE THREAD

**Issue by Shyam1287** [jupyter-widgets/ipywidgets#2795]
Im facing the import error when ProfileReport is run from pandas_profiling package.

from pandas_profiling import ProfileReport

Following command leads to the import error:
profile.to_widgets()

ImportError: cannot import name 'GridspecLayout' from 'ipywidgets' (path to lib/python3.7/site-packages/ipywidgets/__init__.py)

even if my ipywidgets is of version 7.5.1 the above issue still remains

![image](https://user-images.githubusercontent.com/13358855/75351182-b6678900-58cd-11ea-96a0-f2db92017c6e.png)

**Comment by jasongrout** [comment]
Just to double check, what do you get from:

```python
import ipywidgets
ipywidgets.__version__
```

**Comment by Shyam1287** [comment]
Just now I checked. I get 7.4.2.

But what I did was, I directly downloaded the git master latest distribution and took it to the anaconda's lib and pasted that as ipywidgets folder.

**Comment by jasongrout** [comment]
> But what I did was, I directly downloaded the git master latest distribution and took it to the anaconda's lib and overwrited that as ipywidgets folder.
> Im unsure why the version is not showing as the updated one, and from where the jupyter notebook is taking the code, not sure.

That is definitely not the recommended installation procedure. That likely corrupted things, as git master is on 8.0 with many backwards incompatible changes.

At this point, it may be easiest to start from a fresh environment rather than try to fix the hand-edited site-packages. Install ipywidgets using conda, if you are using conda, and it will do the correct thing.

**Comment by Shyam1287** [comment]
But just now I reinstalled the whole package with conda.
Even then the 7.4.2 package is only installed.
![image](https://user-images.githubusercontent.com/13358855/75357550-8f15b980-58d7-11ea-9779-b90033f09622.png)

**Comment by jasongrout** [comment]
Did you start from a clean fresh new environment?

**Comment by Shyam1287** [comment]
Solved it. Thanks a lot for your ideas. Problem was the version.
