### ISSUE TITLE
Ipywidgets 7.0.5 @out.capture does not work

### ISSUE THREAD

**Issue by alex4200** [jupyter-widgets/ipywidgets#2796]
In the [documentation](https://ipywidgets.readthedocs.io/en/stable/examples/Output%20Widget.html) it is explained that with an `output` widgets you can capture the output of a function inside a jupyter notebook. However, using `ipywidgets` 7.0.5, the following (complete) code 

```
from ipywidgets import widgets
out = widgets.Output()

@out.capture()
def test():
    print("Some text")
```

produces an error
```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-1eea2ab84230> in <module>()
      2 out = widgets.Output()
      3 
----> 4 @out.capture()
      5 def test():
      6     print("Some text")

AttributeError: 'Output' object has no attribute 'capture'
```

Is there a bug in `ipywidgets` or a problem in the documentation? Or did I misunderstand something?

**Comment by jasongrout** [comment]
Please upgrade your ipywidgets version. The current version is something like 7.5.1.

**Comment by jasongrout** [comment]
(That method was added in ipywidgets 7.2: https://ipywidgets.readthedocs.io/en/stable/changelog.html#id4)

**Comment by alex4200** [comment]
Is there any similar functionality in `ipywidgets` 7.0.5, i.e. to suppress parts of output, or the output of a function?

**Comment by jasongrout** [comment]
Use the output widget as a context handler. The capture decorator is just syntax sugar for that. See the [output widget documentation](https://ipywidgets.readthedocs.io/en/stable/examples/Output%20Widget.html) (the cells that have `with out:`)

**Comment by alex4200** [comment]
Thanks for that help, but unfortunately the outpout generated in that part of the code (its a matplotlib output-  text and graphics) is not captured. Maybe it is some stderr output or something else that cannot be captured?

**Comment by jasongrout** [comment]
Matplotlib is a special case because of they way they do their outputs (essentially, one of the default backends for matplotlib waits until the cell is done, *then* renders the plot, it doesn't actually display the plot immediately). We have to work around it in our `@interact` decorator as well.

Here is how we use the output widget in that case to capture matplotlib plots:

https://github.com/jupyter-widgets/ipywidgets/blob/1479bea61f852ee2e7e3de08669baefcfaf08c44/ipywidgets/widgets/interaction.py#L63-L66

In particular, we have a utility function (which you can just import and use): https://github.com/jupyter-widgets/ipywidgets/blob/1479bea61f852ee2e7e3de08669baefcfaf08c44/ipywidgets/widgets/interaction.py#L26-L48

**Comment by jasongrout** [comment]
(the heart of that utility function is calling the `flush_figures` method, which immediately outputs the plot while we are still inside the context of the output widget. The other stuff is just to make sure it is appropriate to call `flush_figures`, e.g., we're actually using that backend, etc.

**Comment by alex4200** [comment]
But I want actually to suppress the output of an matplotlib image. I do not want to see the image (as the image is saves as a plot and used later on in a different context).

**Comment by jasongrout** [comment]
ah, then maybe the output widget is not really want you want. Perhaps there is a better way to tell matplotlib to not show a plot, or to delete the plot in the cell where you are creating it without showing it.

I mean, you could capture the plot with the output widget, then never display it, using the above workarounds. But if you really don't want it to be displayed ever, then maybe it's better to ask on the matplotlib issue tracker if there is a way to disable the automatic display in a single cell.

**Comment by jasongrout** [comment]
https://stackoverflow.com/questions/30878666/matplotlib-python-inline-on-off and https://stackoverflow.com/questions/26970002/matplotlib-cant-suppress-figure-window suggest either calling `plt.ioff()` (interactive mode off), or closing your plot before the cell ends (`plt.close()`) might work.

**Comment by alex4200** [comment]
Thanks that seems to work, even with version 7.0.5.
