### ISSUE TITLE
Jupyter Notebook: save widgets state automatically

### ISSUE THREAD

**Issue by martinRenou** [jupyter-widgets/ipywidgets#2797]
Is it possible to save the widgets state automatically on Notebook save in the classical Notebook?

I see from [this other issue](https://github.com/jupyter-widgets/ipywidgets/issues/2063#issuecomment-507672090) that is is possible in JupyterLab but I don't see it in the classical Notebook.

**Comment by jasongrout** [comment]
> Is it possible to save the widgets state automatically on Notebook save in the classical Notebook?

I don't think so. The only option right now is the manual "save widget state" menu item.

**Comment by jasongrout** [comment]
See https://github.com/jupyter-widgets/ipywidgets/issues/1632 for a long discussion about this, which inspired the architecture in JupyterLab to allow this.

**Comment by jasongrout** [comment]
(let's continue any further discussion on #1632 to keep things consolidated)
