### ISSUE TITLE
@jupyter-widgets/base 3.0.0-rc.0

### ISSUE THREAD

**Issue by jtpio** [jupyter-widgets/ipywidgets#2802]
It looks like there is an issue with the `3.0.0-rc.0` release of the `@jupyter-widgets/base` package.

For example it still exports `JupyterPhosphorWidget` instead of `JupyterLuminoWidget`. Inspecting the tarball directly (`npm pack @jupyter-widgets/base@next`):

```
$ cat lib/widget.js | grep -i phosphor
var JupyterPhosphorWidget = /** @class */ (function (_super) {
    __extends(JupyterPhosphorWidget, _super);
    function JupyterPhosphorWidget(options) {
    JupyterPhosphorWidget.prototype.dispose = function () {
     * Process the phosphor message.
     * Any custom phosphor widget used inside a Jupyter widget should override
    JupyterPhosphorWidget.prototype.processMessage = function (msg) {
        this._view.processPhosphorMessage(msg);
    return JupyterPhosphorWidget;
export { JupyterPhosphorWidget };
var JupyterPhosphorPanelWidget = /** @class */ (function (_super) {
    __extends(JupyterPhosphorPanelWidget, _super);
    function JupyterPhosphorPanelWidget(options) {
     * Process the phosphor message.
     * Any custom phosphor widget used inside a Jupyter widget should override
    JupyterPhosphorPanelWidget.prototype.processMessage = function (msg) {
        this._view.processPhosphorMessage(msg);
    JupyterPhosphorPanelWidget.prototype.dispose = function () {
    return JupyterPhosphorPanelWidget;
export { JupyterPhosphorPanelWidget };
                        // trigger phosphor resize messages.
        this.pWidget = new JupyterPhosphorWidget({
    DOMWidgetView.prototype.processPhosphorMessage = function (msg) {
```

xref https://github.com/jtpio/ipylab/pull/34 and https://github.com/jtpio/ipylab/pull/34/checks?check_run_id=476743986 for an example.

**Comment by jasongrout** [comment]
It's *called* JupyterPhosphorWidget for backwards compatibility, even though it really is a Lumino widget.

**Comment by jasongrout** [comment]
(The idea is that there will be minimal changes for downstream custom widget authors until widgets 8.0).

**Comment by jtpio** [comment]
Thanks for the insights.

My understanding was that `3.0.00-rc.0` was released from master (which removed mentions to Phosphor).

**Comment by jtpio** [comment]
For more details: https://github.com/jupyter-widgets/ipywidgets/pull/2781 (and its linked issues and PRs)

**Comment by jasongrout** [comment]
See also https://github.com/jupyter-widgets/ipywidgets/issues/2798 for more discussion

**Comment by maartenbreddels** [comment]
Yes great, we depend on that for a lot of vuetify related code (cc @mariobuikhuizen), I would not mind keeping this in for a few years.

**Comment by jasongrout** [comment]
> I would not mind keeping this in for a few years.

I was planning on doing a rename change JupyterPhosphorWidget to JupyterLuminoWidget for ipywidgets 8.

**Comment by jtpio** [comment]
@maartenbreddels do you mean both `JupyterPhosphorWidget` and `JupyterLuminoWidget` should be kept in 8.0?
