### ISSUE TITLE
Compatibility of jupyter-widgets/base with JupyterLab 1.2 and 2.0

### ISSUE THREAD

**Issue by emmanuelle** [jupyter-widgets/ipywidgets#2809]
Hello! I hope this is the right place to open this issue.

With @nicolaskruchten we're trying to upgrade the `plotlywidget` JS package to work with JupyterLab 2.0 and running into a problem related to `@jupyter-widgets/base` ... Version 1.5.3 of our package depends on version 2.0.0 of `@jupyter-widgets/base` and works in JupyterLab 1.2, which is great. When we try to upgrade to version 3.0.0 we gain JupyterLab 2.0 support, but it no longer works with JupyterLab 1.2. Is this a known limitation? Is it intended that JS packages depending on `@jupyter-widgets/base` can work both with JupyterLab 1.2 and 2? Thank you :-).

**Comment by jasongrout** [comment]
See https://github.com/jupyter-widgets/ipywidgets/issues/2798#issuecomment-593716999

Short answer: make the dependency `^2 || ^3`

**Comment by nicolaskruchten** [comment]
Thanks @jasongrout! Unfortunately this doesn't appear to resolve our issue in JupyterLab 1.2... I still get the following output, which doesn't appear when depending on `^2.0.0`:

![image](https://user-images.githubusercontent.com/203523/76117941-d2001d00-5fba-11ea-8e31-6602f7c85f16.png)

**Comment by jasongrout** [comment]
Where is your PR?

**Comment by nicolaskruchten** [comment]
These are the changes I'm trying: https://github.com/plotly/plotly.py/pull/2256

Note that `package-lock.json` bakes in the dependency on version 3, so I'm not sure how this `^2 || ^3` change makes things work when folks try to install... Maybe I'm just seeing this error because I'm running `jupyter labextension install .` from the `plotlywidget` directory?

**Comment by jasongrout** [comment]
> Note that `package-lock.json` bakes in the dependency on version 3, so I'm not sure how this `^2 || ^3` change makes things work when folks try to install...

The package-lock.json is not used in JupyterLab. JLab will build its own dependency tree straight from the package.json, in consideration with other packages in the jlab build.

**Comment by jasongrout** [comment]
I tried making a dev installation of the plotly PR in jlab 1.2.7 to see if I could reproduce this, but ran into troubles when trying to create a plot: js error of "ReferenceError: require is not defined" from a line:

```javascript
                require(["plotly"], function(Plotly) {
                    window.PLOTLYENV=window.PLOTLYENV || {};
```
Is that expected? Are there instructions for making a dev installation that cover installing the jlab plugin? I tried to follow https://github.com/plotly/plotly.py/blob/master/contributing.md

**Comment by nicolaskruchten** [comment]
That is... not expected, although it's been reported from time to time and not easily reproduced on our end :)

The way I install the dev version is what I had assumed is the standard way, which is to `cd packages/javascript/plotlywidget && npm install && npm run build && jupyter labextension install .` but I always have a nagging feeling that I'm doing it wrong :)

**Comment by nicolaskruchten** [comment]
Looks like the way I was testing things until now was not correct, and that the path @jasongrout suggested above does work if you install into a clean JLab 1.2 instance, see https://github.com/plotly/plotly.py/pull/2261. I was downgrading from 2 to 1 using `pip` but I guess that leaves little bits hanging around somehow?

**Comment by jasongrout** [comment]
> but I guess that leaves little bits hanging around somehow?

I think it can. I'd want to delete the jlab application directory if you downgraded to be sure - that's where jlab is built when you have extensions installed.

**Comment by jasongrout** [comment]
Sounds like this is resolved over in https://github.com/plotly/plotly.py/pull/2261. Thanks!
