### ISSUE TITLE
Testing Ipywidgets

### ISSUE THREAD

**Issue by tonyluo98** [jupyter-widgets/ipywidgets#2814]
I've set up classes that uses ipywidgets to display information/data. I have classes call a separate class that contains all the widgets 

eg. x = widgetClass.button(value,desc,etc...)

I then saw that the documentation has a command for testing 
'pytest --cov=ipywidgets ipywidgets'

I ran this in the folder with all the python classes that some do use ipywidgets and some don't
(assuming the command goes through every file)
I get a error saying  

ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov=ipywidgets
  inifile: None
  rootdir: /home/myuser

I then tried running pytest [dir] 
and got the issue of :

============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /home/myuser
plugins: openfiles-0.4.0, doctestplus-0.4.0, remotedata-0.3.2, arraydiff-0.3
collected 0 items                                                              

============================ no tests ran in 0.01s =============================
I'm unsure if it's because i'm not running it correctly or some other issue.
If it makes any difference, I'm running the classes on Jupyter Notebook via anaconda. I'm using version 7.5.1(newest one?)
 

I've updated to python 3.7 and issue (?) still persists

============================= test session starts ==============================
platform linux -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /home/myuser/project
plugins: openfiles-0.4.0, astropy-header-0.1.2, doctestplus-0.5.0, remotedata-0.3.2, hypothesis-5.5.4, arraydiff-0.3
collected 0 items                                                              

============================ no tests ran in 1.28s ==============================

**Comment by vidartf** [comment]
You are missing a dependency, pytest-cov. Note that this is not related to ipywidgets.
