### ISSUE TITLE
No tab selected by default

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#2818]
In ipywidgets 8.0.0a0, when creating a tab widget, by default no tab is activated, which is really confusing. I think the first tab should be selected.

```python
tab_nest = widgets.Tab()
tab_nest.children = [accordion, accordion]
tab_nest.titles = ('An accordion', 'Copy of the accordion')
tab_nest
```

<img width="726" alt="Screen Shot 2020-03-10 at 8 20 42 AM" src="https://user-images.githubusercontent.com/192614/76328123-24398a80-62a8-11ea-9b80-0d99481926e0.png">

**Comment by vidartf** [comment]
It seems we handle this if `children` is set in the init:

https://github.com/jupyter-widgets/ipywidgets/blob/78cdfcbc5c797a5724ae96b7cfff5bb374f50f99/ipywidgets/widgets/widget_selectioncontainer.py#L51-L52

Is there a counter-example where we would want to set the `children` trait (to a non-empty collection) and not change the `index` from `None` to `0`? If not, then maybe we want a cross-validator here (though cross-validators have a history of being fickle..).

**Comment by vidartf** [comment]
Reopening due to me (potentially) being to quick on the trigger in merging. See PR for discussion.
