### ISSUE TITLE
Displaying a previously created Matplotlib figure in a widget

### ISSUE THREAD

**Issue by thomasaarholt** [jupyter-widgets/ipywidgets#2821]
Edit: Reworded this, since the original questions was more suited for ipympl.

I'm trying to find a way to take a previously created Matplotlib figure, and show it inside a widget.
Here's a short version of my approach (which may not be the right one):

```python
fig = plt.figure() # previously created figure
out = widgets.Output()
with out:
    display(fig)
# other things happening
display(widgets.HBox([fig, some_other_fig]))
```
I notice that it's very easy to trigger the same error that I get at the end of the attached notebook:  If I call `fig1` at the end of the notebook, I'd expect the regular figure to be shown. The error is `AttributeError: 'NoneType' object has no attribute '_send_event'`. I get this error if I add the same figure twice to an output as well.

Here is a [nbviewer view](https://nbviewer.jupyter.org/github/thomasaarholt/tests/blob/master/Output%20Example%20Notebook.ipynb) of a MWE notebook I created, download it top right on the window. It's best if one downloads it and runs it since the first figure appears buggy in the nbviewer.

**Comment by martinRenou** [comment]
Oh sorry, I meant you could open an issue in jupyter-matplotlib. I guess it's more a jupyter-matplotlib issue.

**Comment by thomasaarholt** [comment]
I'll open one there too then. Part of the question is still related to jupyter-widgets:
"Is this the best way to do this?"

**Comment by thomasaarholt** [comment]
Reworded this issue to reflect the error I got at the end of the attached notebook.

**Comment by martinRenou** [comment]
> Is this the best way to do this?

The best way, I don't know. I am not sure what you are trying to achieve. But it should work at least. Let me try to reproduce your error.

**Comment by martinRenou** [comment]
Oh yes, now I see it.

Try changing your code to:
```python
fig = plt.figure() # previously created figure
out = widgets.Output()
with out:
    display(fig.canvas)
# other things happening
display(widgets.HBox([fig.canvas, some_other_fig]))
```

**Comment by martinRenou** [comment]
It's the `canvas` attribute that is the interactive widget, not the figure.

**Comment by thomasaarholt** [comment]
That works nicely. However, I still notice that the following results in an error, which i don't think should happen (although isn't a huge problem)

```python
%matplotlib widget
import numpy as np
import matplotlib.pyplot as plt

fig1, ax1 = plt.subplots() # plot is created
ax1.imshow(np.random.random((5,5)))

fig1 # here the notebook tries to display the image, and causes an error
```
If I instead use the inline backend, there is no error, and I see the image twice.
```python
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

fig1, ax1 = plt.subplots() # plot is created
ax1.imshow(np.random.random((5,5)))

fig1 # no error with inline
```
[gist with error](https://gist.github.com/thomasaarholt/20e0e04ca701503c14369467f438a3c2).

**Comment by martinRenou** [comment]
Yeah. I think there is an issue opened for that in jupyter-matplotlib.

I am not sure how to deal with this issue. Maybe in the Python implementation, the figure should be the widget, not the canvas.
I am not very familiar with the Python implementation, nor the matplotlib API actually, so I would not know how to touch this part of the code without breaking everything.

**Comment by thomasaarholt** [comment]
That's alright. Thanks for your help, closing this one, as you've solved the main problem I was having! :)
