### ISSUE TITLE
readthedocs example error

### ISSUE THREAD

**Issue by RH-sdavey** [jupyter-widgets/ipywidgets#2828]
https://ipywidgets.readthedocs.io/en/stable/examples/Layout%20Templates.html

cell 8/9 has an import error which is not shown in docs/source/examples/Layout Templates.ipynb

**Comment by jasongrout** [comment]
Thanks. It looks like that is corrected in master (see the "latest" docs). It seems there was a PR a while ago that added bqplot etc. to the docs build requirements.
