### ISSUE TITLE
Read the docs not rendering

### ISSUE THREAD

**Issue by MSeal** [jupyter-widgets/ipywidgets#2838]
https://ipywidgets.readthedocs.io/en/latest/ is giving me 404's for all the links on the page. I didn't see anything in the recent history of the `docs` directory that would suggest why those links broke.

**Comment by sterlinm** [comment]
FYI it's only the links that direct to pages built off of the notebooks in the [examples](https://github.com/jupyter-widgets/ipywidgets/tree/master/docs/source/examples) folder.

**Comment by willingc** [comment]
Resolved.
