### ISSUE TITLE
version 8.0.0 seems not working with Jupyter Lab 2.0

### ISSUE THREAD

**Issue by dou-du** [jupyter-widgets/ipywidgets#2840]
I am testing the pre-release version 8.0.0.alpha0 for ipywidgets. It seems not working with
JupyterLab 2.0.

**Comment by stonebig** [comment]
ipywidgets-7.5.1 seems not reactive either on this example and Jupyterlab-2.1.0rc0

 ```
# Networks graph Example : https://github.com/ipython/ipywidgets/blob/master/examples/Exploring%20Graphs.ipynb
%matplotlib inline
from ipywidgets import interact
import matplotlib.pyplot as plt
import networkx as nx
# wrap a few graph generation functions so they have the same signature

def random_lobster(n, m, k, p):
    return nx.random_lobster(n, p, p / m)

def powerlaw_cluster(n, m, k, p):
    return nx.powerlaw_cluster_graph(n, m, p)

def erdos_renyi(n, m, k, p):
    return nx.erdos_renyi_graph(n, p)

def newman_watts_strogatz(n, m, k, p):
    return nx.newman_watts_strogatz_graph(n, k, p)

@interact(n=(2,30), m=(1,10), k=(1,10), p=(0.0, 1.0, 0.001),
        generator={'lobster': random_lobster,
                   'power law': powerlaw_cluster,
                   'Newman-Watts-Strogatz': newman_watts_strogatz,
                   u'Erdős-Rényi': erdos_renyi,
                   })
def plot_random_graph(n, m, k, p, generator):
    g = generator(n, m, k, p)
    nx.draw(g)
    plt.title(generator.__name__)
    plt.show()
    
```

**Comment by stonebig** [comment]
with jupyterlab-2.1.0 final, I just have to relaunch the cell and it works.... I have also to do the same relaunch for **%matplotlib widget** cells, so maybe more a Jupyterlab thing than ipywidgets.

**Comment by tcwalther** [comment]
I have the same problem. Running the following code freezes the kernel. Pressing "restart kernel" doesn't help; however, shutting down the kernel and then restarting the kernel does 🤷‍♂️.

```python
import ipywidgets
audio_player = ipywidgets.Audio(loop=False)
```

Env:
```
jupyter@***:~$ pip freeze | grep widgets
ipywidgets==7.5.1
widgetsnbextension==3.5.1
jupyter@***:~$ pip freeze | grep jupyter
jupyter==1.0.0
jupyter-aihub-deploy-extension==0.1
jupyter-client==5.3.4
jupyter-console==6.0.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.6.1
jupyter-highlight-selected-word==0.2.0
jupyter-http-over-ws==0.0.6
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyter-server-proxy==1.3.2
jupyter-tensorboard==0.1.10
jupyterlab==2.1.0
jupyterlab-git==0.6.1
jupyterlab-nvdashboard==0.2.1
jupyterlab-server==1.1.0
jupyter@tw-beatbox:~$ 
```

**Comment by jasongrout** [comment]
Correct: we have not released an 8.0 alpha that supports JLab 2.0.

**Comment by thomasaarholt** [comment]
@jasongrout what is the current status on versions of ipywidgets and widgetsnbextension? "Is" there a v8 / v4 of these?

I was looking at the widgetsnbextension because I noticed that `conda install widgetsnbextension` depends on `notebook`, but it looks like this is no longer the case? Ref: [matplotlib/ipympl#34](https://github.com/matplotlib/ipympl/issues/34#issuecomment-760148537)

**Comment by jasongrout** [comment]
> @jasongrout what is the current status on versions of ipywidgets and widgetsnbextension? "Is" there a v8 / v4 of these?

Current ipywidgets is [7.6.3](https://pypi.org/project/ipywidgets/). I did not publish a new version of widgetsnbextension (not necessary) when I did ipywidgets 7.6, so it is still at [3.5.1](https://pypi.org/project/widgetsnbextension/).

widgetsnbextension does indeed [depend on notebook](https://github.com/jupyter-widgets/ipywidgets/blob/7.x/widgetsnbextension/setup.py#L224), like it always has. I think the plan is to break that dependency link in the next major version (ipywidgets 8, widgetsnbextension 4).

**Comment by jasongrout** [comment]
If it's causing a huge issue, we could consider releasing widgetsnbextension 4 with basically the major change being breaking the dependency link to notebook.

We're having a planning meeting for ipywidgets 8 sometime soon ([by early February](https://gitter.im/jupyter-widgets/Lobby?at=5fff75df81c55b09c7075bf3)) where we can evaluate whether it is better to move forward with updating widgetsnbextension like this before ipywidgets 8, or whether we should push forward to ipywidgets 8. Feel free to come to the planning meeting if you'd like.

**Comment by thomasaarholt** [comment]
It's not a major pain point at all - it's just nice to be able to slim down environments when possible.
I'd be happy to come to the meeting! I might not say much, but I might have some thoughts. Is there a mailing-list or similar?

**Comment by jasongrout** [comment]
For the meeting details and planning, see the [gitter](https://gitter.im/jupyter-widgets/Lobby?at=5fff75df81c55b09c7075bf3).

**Comment by jasongrout** [comment]
More about the 8.0 planning meeting is at #2750

**Comment by willingc** [comment]
> widgetsnbextension does indeed depend on notebook, like it always has. I think the plan is to break that dependency link in the next major version (ipywidgets 8, widgetsnbextension 4).

fyi @captainsafia @MSeal

**Comment by jasongrout** [comment]
ipywidgets 8.0 currently is targeting JupyterLab 3 and classic Jupyter Notebook
