### ISSUE TITLE
widgets that interact with multiple functions 

### ISSUE THREAD

**Issue by gioxc88** [jupyter-widgets/ipywidgets#2843]
When I have widgets that interacts with multiple functions is there a way to temporarily disable the event in order to avoid an infinite loop?

Something like in VBA Application.EnableEvents = False?

**Comment by vidartf** [comment]
The normal pattern is to use something like a *change guard* variable. I.e. you set a variable to let you know if you are recursing or not. A simplified example:

```python
changing_a = False
def on_change_a(...):
    if changing_a:
        return
    changing_a = True
    try:
        set_b(...)  # will trigger on_change_b
    finally:
        changing_a = False

changing_b = False
def on_change_b(...):
    if changing_b:
        return
    changing_b = True
    try:
        set_a(...)  # will trigger on_change_a
    finally:
        changing_b = False
```

A more pythonic way is probably to use a decorator (or a context manager). Something like this (untested):

```python
import functools

def reentry_guard(func):
    in_function = False
    @functools.wraps(func)
    def _reentry_guard(*args, **kwargs):
        if in_function:
            return
        try:
            return func(*args, **kwargs)
        finally:
            in_function = False
    return _reentry_guard
```

which you can then use as:

```python
@reentry_guard
def on_change_a(...):
    set_b(...)  # will trigger on_change_b

@reentry_guard
def on_change_b(...):
    set_a(...)  # will trigger on_change_a
```

**Comment by vidartf** [comment]
Depending on what you are doing, `widget.hold_trait_notification()` might be relevant as well in order to control the timing of *when* notifications fire.

**Comment by rsheftel** [comment]
This was a helpful in answering a question I had, I suggest including in the docs. The docs are silent on a single widget interacting with multiple functions, being clear about that would be helpful

**Comment by jasongrout** [comment]
Thanks! Do you want to make a PR for adding it where it would have made sense to you to read it?

**Comment by rsheftel** [comment]
@jasongrout I will do that. One question I cannot figure out: when there are multiple interacts tied to the same widget, is there any way to predict the order of operations? When function will be executed in what order when that widget is used?

**Comment by gioxc88** [comment]
> @jasongrout I will do that. One question I cannot figure out: when there are multiple interacts tied to the same widget, is there any way to predict the order of operations? When function will be executed in what order when that widget is used?

it is the order in which they are linked to widget
