### ISSUE TITLE
ipywidgets/packages/jupyterlab-manager/README.md information out of date

### ISSUE THREAD

**Issue by matburnham** [jupyter-widgets/ipywidgets#2846]
`ipywidgets/packages/jupyterlab-manager/README.md` implies JupyterLab 1.0 is the current default:

> **Prerequisites**
> * JupyterLab (see package.json for appropriate version, currently JupyterLab 1.0)

`ipywidgets/packages/jupyterlab-manager/package.json` appears to show otherwise:
```
  "dependencies": {
    ...
    "@jupyterlab/application": "^2.0.2",
```

**Comment by matburnham** [comment]
At least that's what it looks like to me, I could well be wrong. Only came across this while researching a fix for #2845.

**Comment by jasongrout** [comment]
Would you mind submitting a PR to remove that "currently" statement, since it's going to fall out of date again and again?

**Comment by ohrely** [comment]
This issue can be closed.  As far as I can tell, the string in question is no longer in the codebase.
