### ISSUE TITLE
Some font-awesome icons not working for ToggleButtons

### ISSUE THREAD

**Issue by giswqs** [jupyter-widgets/ipywidgets#2848]
I am trying to add some font-awesome icons (e.g., chart-line, chart-scatter, chart-bar) to ToggleButtons, but these [charting icons](https://fontawesome.com/icons?d=gallery&q=chart) could not show up on the ToggleButtons. Any help will be appreciated. 

```
import ipywidgets as widgets
t = widgets.ToggleButtons(
    options=['', '', '', ''],
    disabled=False,
    button_style='primary', 
    tooltips=['Pointer', 'Open a file', 'bar chart', 'line chart'],
    icons=['mouse-pointer', 'folder-open', 'chart-bar', 'chart-line'],
    layout=widgets.Layout(width='auto', height='auto')
)
t.style.button_width='40px'
t
```
Here is what it looks like
![](https://i.imgur.com/WERHaj6.png)

**Comment by martinRenou** [comment]
As far as I know, the current front-end version (JupyterLab and Jupyter Notebook) are using an font awesome 4.7 https://fontawesome.com/v4.7.0. So only those icons are available.

**Comment by martinRenou** [comment]
I updated JupyterLab so that it uses latest font-awesome two months ago, but we should do the same for Jupyter Notebook.

**Comment by giswqs** [comment]
@martinRenou Thanks a lot for your prompt response. I just tried it on JupyterLab, it did show up correctly. It would be nice to have it working on Jupyter notebook. I am trying to add a toolbar to the ipyleaflet-based geemap package. 

![](https://i.imgur.com/rAXGpKs.png)

**Comment by martinRenou** [comment]
I agree it would be nice

**Comment by giswqs** [comment]
BTW, would it be possible to arrange the ToggleButtons as two columns vertically? I can only make it either one row horizontally or one column vertically, but I am not sure how to arrange it into more columns. It would be too long vertically with more than 10 icons. 

![](https://i.imgur.com/PRdeoiF.png)
