### ISSUE TITLE
Unloading values from multiple widgets in a container 

### ISSUE THREAD

**Issue by UGuntupalli** [jupyter-widgets/ipywidgets#2849]
All, 
    I just started using ipywidgets and I am trying to find the ropes, so if this question has been answered previously or the documentation covers it in some way, kindly point me to that section. Essentially, here is a miniature version of the UI I am trying to develop. The question that has got me perplexed is, once I construct a UI like shown below, and the user provides their input, how do I unload the input ? I am hoping to collect values for each of the variables and trigger my logic, but the only thing I see in the documentation talks about using either interact or interactive. However I am not really sure how to use them with multiple widgets, all the examples I have come across seem to point to using them with a single widget. If anyone could point me to a good resource or provide a sample, that would be helpful.
 With that classifier, here is what I am trying to do: 

```
style = {'description_width': 'initial'}

def input_tab(tab_list, tab_names_list):
    if len(tab_list) == len(tab_names_list):
        this_tab = Tab()
        this_tab.children = tab_list
        [this_tab.set_title(i, title) for i, title in enumerate(tab_names_list)]
        return this_tab
    else:
        raise ValueError('\n Input lists should be of the same size')

def get_input_panel_num():
    input_1 = widgets.Text(value='3000', description='Input-1', style=style)
    input_2 = widgets.Dropdown(options=['yes', 'no'], description='Select one', value='yes', disabled=False, style=style)
    input_3 = widgets.IntSlider(value=0, min=0, max=1, step=1, description='Input-3', orientation='horizontal', readout=True, 
                               style=style)
    input_list_num = [input_1, input_2, input_3]
    return input_list_num

def get_input_panel_char():
    input_a = widgets.Text(value='3000', description='Input-1', style=style)
    input_b = widgets.Dropdown(options=['yes', 'no'], description='Select one', value='yes', disabled=False, style=style)
    input_c = widgets.IntSlider(value=0, min=0, max=1, step=1, description='Input-3', orientation='horizontal', readout=True, 
                               style=style)
    input_list_char = [input_a, input_b, input_c]
    return input_list_char

def create_master_tab():
    tab_names = ["tab-1", "tab-2"]
    panel_num = VBox(get_input_panel_num())
    panel_char = VBox(get_input_panel_char())
    final = input_tab(tab_list=[panel_num, panel_char], tab_names_list=tab_names)
    return final

demo = create_master_tab()
demo 
```

**Comment by joseberlines** [comment]
you have to look for .observe
this is an example:

# those are 5 toggle buttons (it can be anything, or a simple button)
# frist create button
lang_buttons = widgets.ToggleButtons(
            options=['EN', 'DE', 'FR','NL','IT'],
            button_style='info',
            description='')

# second define what is going to happen when someone clicks one of the buttons
def handle_lang_buttons(change):
            lang = change.new
            self.language = lang
            update_wd_info_procedure_label()
            logging_in_GUI('user_entered_language', self.lang)
 
#third join both with .observe
# here basically lang_buttons  is observing. what? the method called handle_lang_buttons, what is passed to the method?    names='values'
lang_buttons.observe(handle_lang_buttons, names='value')

**Comment by UGuntupalli** [comment]
@joseberlines : Thank you for your response. Can you kindly provide a working example ? The example you provided yields an error, so it is harder to understand exactly what you are pointing towards. Additionally, unloading the value from an individual button seems to be different from unloading it from a container which can have many such widgets. Imagine a tab or an accordion, how do you unload the user input for every widget in a container like a tab ? Is it possible using observe? If so, can you kindly use the example I have provided to show how to get it to work ?

**Comment by UGuntupalli** [comment]
@jasongrout : any advice or can you guide me to a working example ?

**Comment by jasongrout** [comment]
In your case, `demo.children[0].children[0].value` gets the value of the first text box. You can explore your tree of widgets, for example:

`demo.children[0]` is your first tab
`demo.children[0].children` is the list of child widgets in that tab
`demo.children[0].children[0]` is the first child widget in that tab
`demo.children[0].children[0].value` is the value of that widget.

Or another approach is to save a reference to those widgets individually, perhaps in global variables, so you could directly address them as, say, `input_1.value` instead of needing to drill down through your UI.
