### ISSUE TITLE
jupyter notebook dropdown box value quoted

### ISSUE THREAD

**Issue by przytula** [jupyter-widgets/ipywidgets#2854]
I am using a dropdown box that receives the values from %sql select... 🆗 
 I display drop.value and it indicates 'SYSCAT' = ok 
 now I need to use this drop.value as an input to another %sql
 %sql select .. from table where col=$drop.value
 in this case the value is supplied but I need the quotes
 % sql select ..from table where col1='SYSCAT'
 how can this be done ? any idea 
 thanks for all update, Best regards, Guy

**Comment by jasongrout** [comment]
This isn't so much an ipywidgets question as a `%sql` question, better suited for wherever you get %sql from - is that https://github.com/catherinedevlin/ipython-sql ?

Perhaps using their binding is what you want? `x = drop.value` and using `:x` in your statement?
