### ISSUE TITLE
Adding tags to widgets

### ISSUE THREAD

**Issue by dextersLabRat** [jupyter-widgets/ipywidgets#2861]
First, I so appreciate all the great work that has gone into this repo! I'm using it and loving it; it's great to be able to visualize data and communicate it to my team.

I have been using a Grid layout (GridspecLayout) of FloatText widgets--6 rows by 4 columns. I currently have them all using the same callback (via observe() ) to keep things simpler (rather than creating 24 different functions!). 

In my callback, I identify what FloatText widget is calling me by referencing its description. Having each FloatText widget have its description next to it, though, was too visually cluttered, so I hid the description using `style={'description_width': '0px'}`. 

This works, but it's a bit clunky. What would be nice is a 'user' or 'tags' field in the widget to identify it if multiple widgets use the same callback. Or perhaps, there's a nicer way that I'm just not aware of right now. Thanks.

Some sample code (forgive the hardcoded formatting--I'm not sure about all the Layout and Style options at present):
```
dbgOut = widgets.Output()

@dbgOut.capture(clear_output=True, wait=True)
def myFloatTextHandler(change):
    myRegex = re.compile(r"description='R(\d)+C(\d)+'") #"\'R(\d)+C(\d)+\',")
    m = myRegex.search(str(change.owner))
    
    rowNum = int(m.groups()[0])
    colNum = int(m.groups()[1])
    
    rowIdx = rowNum - 1
    colIdx = colNum - 1
    
    print('Handling: Row ' + str(rowIdx) + ', Column ' + str(colIdx))
    
    # do some stuff here...

numGridRows = 7
numGridCols = 5
numGridPadCols = 3 # just for padding--nothing in these

tweakGrid = widgets.GridspecLayout(numGridRows, numGridCols+numGridPadCols, height='300px', width='780px')

for row in range(1, numGridRows):
    tweakGrid[row, 0] = widgets.Label(value='MyRowLabel{}'.format(row), layout=widgets.Layout(min_width='90px'))
    
colLabels = ['X Offset', 'XScale', 'Y Offset', 'Y Scale']

for col in range(1, numGridCols):
    tweakGrid[0, col] = widgets.Label(value=colLabels[col-1])
    
for row, col in [(r, c) for r in range(1, numGridRows) for c in range(1, numGridCols)]:
    if col == 2 or col == 4:
        initValue = 1.0
    else:
        initValue = 0.0
        
    wdg = widgets.FloatText(value=initValue, placeholder='0.0', description='R'+str(row)+'C'+str(col),
        step='0.05', disabled=False, style={'description_width': '0px'},
        layout=widgets.Layout(max_width='120px', max_height='80px'))
        # layout=widgets.Layout(max_width='120px', max_height='80px', justify_self='end')) # (max_width='auto', max_height='auto'))

    wdg.observe(myFloatTextHandler, names='value')
    tweakGrid[row, col] = wdg
    
headerVBox = widgets.VBox([tweakGrid, dbgOut])

AppLayout(
    header=None,
    center=headerVBox,
    footer=None,
)
```

**Comment by 8080labs** [comment]
Hi,

so you want to identify in the callback which element did trigger the callback. In the example you want to identify the element via `row` and `col`.
You mentioned that you did not want to create 24 different functions - and it seemed like you thought that you have to create them manually. Maybe you are not aware of the fact that you can also dynamically create functions and pass them around as objects?

Here is your example using a function that creates a custom CallbackFunction for each element:

```
import ipywidgets as widgets

dbgOut = widgets.Output()

def createFloatTextHandler(row, column):
    @dbgOut.capture(clear_output=True, wait=True)
    def myFloatTextHandler(change):
        print(f'Handling: Row {row}, Column {column}')
        # do some stuff here...
    return myFloatTextHandler

numGridRows = 7
numGridCols = 5
numGridPadCols = 3 # just for padding--nothing in these

tweakGrid = widgets.GridspecLayout(numGridRows, numGridCols+numGridPadCols, height='300px', width='780px')

for row in range(1, numGridRows):
    tweakGrid[row, 0] = widgets.Label(value='MyRowLabel{}'.format(row), layout=widgets.Layout(min_width='90px'))
    
colLabels = ['X Offset', 'XScale', 'Y Offset', 'Y Scale']

for col in range(1, numGridCols):
    tweakGrid[0, col] = widgets.Label(value=colLabels[col-1])
    
for row, col in [(r, c) for r in range(1, numGridRows) for c in range(1, numGridCols)]:
    if col == 2 or col == 4:
        initValue = 1.0
    else:
        initValue = 0.0
        
    wdg = widgets.FloatText(value=initValue, placeholder='0.0',
        step='0.05', disabled=False,
        layout=widgets.Layout(max_width='120px', max_height='80px'))

    wdg.observe(createFloatTextHandler(row, col), names='value')
    tweakGrid[row, col] = wdg
    
headerVBox = widgets.VBox([tweakGrid, dbgOut])

widgets.AppLayout(
    header=None,
    center=headerVBox,
    footer=None,
)
```

What do you think about this approach?

**Comment by dextersLabRat** [comment]
While I think it could still be a useful thing to have widget tags in situations like these, I do see the nicety of your scheme here. I don't see any issues with it, except that I wonder if the multiple Row x Col callbacks increase memory/CPU usage? I don't know, and maybe with 8GB+ of RAM on most all machines nowadays, it's not an issue. Or, perhaps, there's some sort of referencing going on, such that there really aren't Row x Col number of callbacks, but just some common code with some sort of wrapper that handles the dereferencing of the object that called the callback? I don't know enough to answer that.

Very nice approach. I see a lot of OO Python from folks like yourself--and even more in-depth than this example required--and I'm a bit out of my depth. I'm more of a C/C++ guy that uses Python for data analysis. I like Python a lot, but I'm a n00b in a lot of ways. Thanks for the help!

**Comment by jasongrout** [comment]
Here's another solution that keeps your one event handler (which I prefer) and just stores the mapping in another dictionary:

```python
dbgOut = widgets.Output()

@dbgOut.capture(clear_output=True, wait=True)
def myFloatTextHandler(change):
    row, col = rowcol[change.owner]
    
    print('Handling: Row ' + str(row-1) + ', Column ' + str(col-1))
    
    # do some stuff here...

numGridRows = 7
numGridCols = 5
numGridPadCols = 3 # just for padding--nothing in these

tweakGrid = widgets.GridspecLayout(numGridRows, numGridCols+numGridPadCols, height='300px', width='780px')

for row in range(1, numGridRows):
    tweakGrid[row, 0] = widgets.Label(value='MyRowLabel{}'.format(row), layout=widgets.Layout(min_width='90px'))
    
colLabels = ['X Offset', 'XScale', 'Y Offset', 'Y Scale']

for col in range(1, numGridCols):
    tweakGrid[0, col] = widgets.Label(value=colLabels[col-1])
    
rowcol = {}

for row, col in [(r, c) for r in range(1, numGridRows) for c in range(1, numGridCols)]:
    if col == 2 or col == 4:
        initValue = 1.0
    else:
        initValue = 0.0
        
    wdg = widgets.FloatText(value=initValue, placeholder='0.0', myval='R'+str(row)+'C'+str(col),
        step='0.05', disabled=False, style={'description_width': '0px'},
        layout=widgets.Layout(max_width='120px', max_height='80px'))
        # layout=widgets.Layout(max_width='120px', max_height='80px', justify_self='end')) # (max_width='auto', max_height='auto'))

    wdg.observe(myFloatTextHandler, names='value')
    tweakGrid[row, col] = wdg
    
    # Store a reverse dictionary of widgets to their row and column
    rowcol[wdg] = (row, col)
    
headerVBox = widgets.VBox([tweakGrid, dbgOut])

widgets.AppLayout(
    header=None,
    center=headerVBox,
    footer=None,
)
```

**Comment by jasongrout** [comment]
I will add that creating a new widget is probably way more resource intensive than creating a new callback, so I think having a widget per cell is probably going to bottleneck you way more than having a callback per cell.

**Comment by dextersLabRat** [comment]
@jasongrout, thanks for the great response!! I seriously appreciate responsive folks like yourself. You are on most, if not all, of the Issues threads--it's cool that you consistently give your time and attention to this.

I like your solution. Because each widget has its own GUID (right?), the `rowcol[wdg] = (row, col)` line captures that in a dictionary with the GUID as key--I think that's what happens :). Please correct me if I'm wrong. That's essentially the unique part that I was looking for.

This thread has helped me learn a couple of new tricks. Thanks again!!

**Comment by jasongrout** [comment]
It actually has the actual widget instance as the key. It may be slightly easier to deal with the model id instead, though, if you want.
