### ISSUE TITLE
No module matplotlib

### ISSUE THREAD

**Issue by johncleveland** [jupyter-widgets/ipywidgets#2862]
The matplotlib library is not available for binder

**Comment by aidanmontare-edu** [comment]
I noticed the same thing. Oddly, matplotlib is in docs/requirements.txt, but maybe this isn't getting installed somehow?

**Comment by martinRenou** [comment]
It must be listed in the `environment.yml` for it to be installed on Binder

**Comment by ianhi** [comment]
This should be fixed by https://github.com/jupyter-widgets/ipywidgets/pull/2701

Thanks for reporting!
