### ISSUE TITLE
Subcalssing Checkbox doesn't work properly

### ISSUE THREAD

**Issue by Alexboiboi** [jupyter-widgets/ipywidgets#2864]
Hi there,
first, thanks for the amazing work on this library!

I am currently trying to subclass the Checkbox widget in order to implement a small annotation. I have managed to make it work but it is not robust and I don't think this is the right way to do it.

here a self-contained code snippet:

```python
import ipywidgets as widgets
from traitlets import validate , Unicode
class AnnotatedCheckbox(widgets.Checkbox):
    annotation = Unicode()
    def __init__(self, *args, annotation='', **kwargs):
        super().__init__(*args, **kwargs)
        self._annotation_html = widgets.HTML(layout=dict(width='0px', margin = '-12px 0px 0px 0px'))
        self.annotation = annotation
        self._container = widgets.HBox()
        self._container.children= [self._annotation_html, self]
        self._model_id = self._container._model_id
    
    @validate('annotation')
    def _validate_annotation(self, proposal):
        annotation = proposal['value']
        self._annotation_html.value = f'''<p style="font-size:10px">{annotation}</p>'''
        return annotation

ac= AnnotatedCheckbox(annotation='annotation', description='mycheckbox',
                      style=dict(description_width='0px'))
ac
```

This works fine but as soon as I want to include the widget in a container the annotation disappears!

Any help is welcome, especially, I would like to understand it, in order to be able to generalize it to other similar subclassing.

Thanks ;)

**Comment by jasongrout** [comment]
It sounds like you really probably should subclass the hbox widget and make it have two children, one of which is a checkbox.

**Comment by jasongrout** [comment]
(That's if you're okay with the user having access to the children with the `.children` attribute)

**Comment by Alexboiboi** [comment]
> It sounds like you really probably should subclass the hbox widget and make it have two children, one of which is a checkbox.
Thanks for the quick answer @jasongrout,
This has actually been my first approach but then, the widget doesn't behave like a classical checkbox anymore, or I need to link all the attributes like value, layout, description, manually. Isn't there another way to do it by keeping the checkbox 's behavior ?

**Comment by jasongrout** [comment]
The "real" way to do it would be to implement it in Javascript. The way you're trying to do it (composing widgets with other widgets), I think it's better to use a container widget to do the composition.

**Comment by Alexboiboi** [comment]
If I would be to do it in javascript, could you tell me where to start learning, additionally to the ipywidgets docs on how to make a custom widget? In the future I would then be happy to contribute to the library if I can.

**Comment by jasongrout** [comment]
You can start with the [widget cookie cutter](https://github.com/jupyter-widgets/widget-ts-cookiecutter), for example. I would inherit from the [checkbox model](https://github.com/jupyter-widgets/ipywidgets/blob/bb1c473f60454809209f006870e2785e9028e03e/packages/controls/src/widget_bool.ts#L21) (which would have your new attribute) and the [checkbox view](https://github.com/jupyter-widgets/ipywidgets/blob/bb1c473f60454809209f006870e2785e9028e03e/packages/controls/src/widget_bool.ts#L32) (which would know how to display your attribute). On the python side, you could inherit from the checkbox model like you did and just have one new attribute for that annotation thing you are doing.

Would you mind posting a screenshot of what your goal is?

**Comment by Alexboiboi** [comment]
Hi @jasongrout, thanks for the answer,
It looks like the it is quite some work for little use case I guess. The goal was to visually keep track of the selection order in a minimalistic way. This is how I implemented it afterall:

```python
import ipywidgets as widgets
from traitlets import validate , Unicode
class AnnotatedCheckbox(widgets.HBox, widgets.Checkbox):
    annotation = Unicode()
    def __init__(self, *args, annotation='', **kwargs):
        super().__init__()
        self.checkbox = widgets.Checkbox(*args, **kwargs)
        link((self.checkbox,'value'),(self, 'value'))
        link((self.checkbox,'description'),(self, 'description'))
        #link((self.style, 'description_width'), (self.checkbox.style,'description_width'))
        self._annotation_html = widgets.HTML(layout=dict(width='0px'))
        self.annotation = annotation
        self.children= [self._annotation_html, self.checkbox]
    
    @observe('annotation')
    def _update_padding(self, change):
        self._annotation_html.layout.margin = f'-10px 0px 0px 0px'
        
    @validate('annotation')
    def _validate_annotation(self, proposal):
        annotation = proposal['value']
        self._annotation_html.value = f'''<p style="font-size:10px">{annotation}</p>'''
        return annotation
```
![image](https://user-images.githubusercontent.com/29252289/81048929-89cb8100-8ebd-11ea-9209-a0ca05562ba1.png)

**Comment by Alexboiboi** [comment]
I think I would rather invest some time in some javascript learning and ultimately I would like to create a custom rangeslider/slider with editable soft bounds.
Ideally this slider would have min max boxes to enter slider limits and a double click on the slider would make the slider take the min/max values. For now I had to do it with additional widgets, like this:

![gif1](https://user-images.githubusercontent.com/29252289/81050891-1af02700-8ec1-11ea-8cb8-b0c1e064cebd.gif)
