### ISSUE TITLE
Clear widget state programatically

### ISSUE THREAD

**Issue by jvail** [jupyter-widgets/ipywidgets#2867]
Sorry to bring this up again. I went through a lot of issues about this topic e.g. https://github.com/jupyter-widgets/ipywidgets/issues/1970

I am implementing a jupyter widget and the size of the state can be quite large (several MB) and if old states are kept within and serialized to the notebook file it becomes unusable (as described in several issues). Is there a way, does anyone have a recommendation how to clear the (view-)state of the widget e.g. inside the DOMWidgetView remove() function?

Thank you
Jan

**Comment by jasongrout** [comment]
In the notebook, the user can clear the widget state and restart the kernel (thus deleting the widget state in the notebook and frontend), then save the widget state to the notebook from the widget menu.

**Comment by jvail** [comment]
Thank you @jasongrout, but restarting the kernel does not help. Clearing widget state from the menu plus browser refresh removes the "old" state. That's my problem. And I think jupyter lab has no option to clear the widget state. It has an option save it automatically - and then each execution of the same cell + save will increase the size of the notebook.
I understood from the other discussions that it is difficult to find a solution inside ipywidgest/notebooks - because there are use-cases where this behavior might be useful. So I am not asking for a feature - just an idea how I could work around this problem in my widget.

**Comment by jasongrout** [comment]
Ah, you are in JupyterLab, not in Jupyter Notebook (i.e., classic notebook). Good point that in JupyterLab we don't have a similar option to the menu item in classic Notebook to clear the widget state.

One design decision in JupyterLab is that we only save active widget state. So if you have "save widgets" checked, and you restart the kernel so that no widgets are active, then save your notebook, it will save the cleared state (i.e., no widgets are active). So:

1. Make sure "save widget state" is checked
2. Restart the kernel
3. Save the notebook.

**Comment by jasongrout** [comment]
To close the widget programmatically, you can do this:

```python
from ipywidgets import Widget

Widget.close_all()
```
then save the notebook.

**Comment by jvail** [comment]
The only way to get rid of the old state in jupyter lab is restarting the kernel and clear all output - I suppose that has same effect as calling widget.close(). But then I loose the active state as well which I'd like to keep.

Here is a minimal example
```python
import ipywidgets
ipywidgets.Label('hello state')
```
If I execute the cell twice in jupyter lab (with "save widget state" activated) and save I have two widget states in the notebook file: 

```json
  "widgets": {
   "application/vnd.jupyter.widget-state+json": {
    "state": {
     "1313415da2374941977a3252ea8e457a": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "1.5.0",
      "model_name": "DescriptionStyleModel",
      "state": {
       "description_width": ""
      }
     },
     "1d6c515b43b44727a6ef26b6cfb0d956": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "1.5.0",
      "model_name": "LabelModel",
      "state": {
       "layout": "IPY_MODEL_340782808a6a490b910b9d294aa9b238",
       "style": "IPY_MODEL_1313415da2374941977a3252ea8e457a",
       "value": "hello state"
      }
     },
     "229a5e478da546c7910c70c4fce79cd0": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "1.5.0",
      "model_name": "LabelModel",
      "state": {
       "layout": "IPY_MODEL_37368ff380524794bf15bff4b99b12aa",
       "style": "IPY_MODEL_46cd309480674126af143efa42303859",
       "value": "hello state"
      }
     },
     "340782808a6a490b910b9d294aa9b238": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "1.2.0",
      "model_name": "LayoutModel",
      "state": {}
     },
     "37368ff380524794bf15bff4b99b12aa": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "1.2.0",
      "model_name": "LayoutModel",
      "state": {}
     },
     "46cd309480674126af143efa42303859": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "1.5.0",
      "model_name": "DescriptionStyleModel",
      "state": {
       "description_width": ""
      }
     }
    },
    "version_major": 2,
    "version_minor": 0
   }
  }
```

In my widget I'd like to keep only the last one - the one that is displayed and is rendered if I reopen the notebook later after shutting down the kernel. Calling widget.close() would remove the active state as well. I guess the solution is somewhere in JS, in the view rather than in python.

**Comment by jasongrout** [comment]
You can close just that widget if you keep a reference to it:

```python
import ipywidgets
try:
    # Close a previously created widget
    x.close()
except:
    pass
x = ipywidgets.Label()
x
```
Or you can turn on the experimental view counter and loop through widgets which have no views and close them. To start counting the views of a widget set that widget's `._view_count` attribute to 0. This may not be completely accurate.

It's a bit tricky to get just the widgets that are displayed in the client because you have to know all the ways a widget can contain another widget to come up with the graph of displayed widgets.

**Comment by jvail** [comment]
Yes, thank you, I have seen this view_count property and was hoping that I could do something with it but since there was the comment in the source that it is experimental I hesitated. But I will look into it and let you know if it would help me solving my issue.

**Comment by jvail** [comment]
What seems to work for me is using the views property of the model. Then I just don't return anything in the serialize function for my "heavy" property if there is no view:

```ts
    static serializers: ISerializers = {
        ...DOMWidgetModel.serializers,
        heavy: {
            serialize: (heavy, model) => {
                return Object.keys(model.views).length ? heavy : undefined;
            },
            deserialize: heavy => heavy
        }
    }
```
I hope this has no unwanted effects - not sure.

So, I wonder if it is an idea to just add this to the ManagerBase serialize_state function that is triggered when I click "Save widget state": https://github.com/jupyter-widgets/ipywidgets/blob/fa3c7066622a8cd869f1306033c5e8bf400bc2fb/packages/base-manager/src/manager-base.ts#L545-L548
Maybe as an option and not only drop defaults but also drop viewless states. I wonder why you would want to serialize states with no view.

**Comment by jasongrout** [comment]
Some widgets like jslink or other data only widvets have no view. But perhaps if you check to see what the view module is, this could work.

**Comment by jvail** [comment]
Ok. Makes sense then. I think a property like drop_viewless in the StateOptions that can be accessed and changed in a widget implementation would be helpful here. Then each widget can implement if it has a useful state w/o view that should be serialized as well.
