### ISSUE TITLE
Tab/Accordion missing titles

### ISSUE THREAD

**Issue by omribahumi** [jupyter-widgets/ipywidgets#2868]
I think there's a bug with the "titling" of `_SelectionContainer`s. It's empty.

```
tab = widgets.Tab(children=[widgets.IntSlider(), widgets.Text()], titles=('Slider', 'Text'))
tab
```

```
accordion = widgets.Accordion(children=[widgets.IntSlider(), widgets.Text()], titles=('Slider', 'Text'))
accordion
```

![image](https://user-images.githubusercontent.com/2558457/81281815-0055b380-9063-11ea-9871-b987f7980fe7.png)

```
$ pip freeze | egrep '(jupyter|ipy)'
ipykernel==5.2.1
ipython==7.14.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jupyter==1.0.0
jupyter-client==6.1.3
jupyter-console==6.1.0
jupyter-core==4.6.3
```

**Comment by jasongrout** [comment]
Use set_title: https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html#Tabs

You may have seen the documentation for the unreleased version of ipywidgets.

See also https://github.com/jupyter-widgets/ipywidgets/issues/2790
