### ISSUE TITLE
issue with step size in BoundedFloatText

### ISSUE THREAD

**Issue by shek2994** [jupyter-widgets/ipywidgets#2875]
Here is my simple float text widget. The default value is set to **7.5** and the step size is **3.1**. When I display this widget, I get a float text window/box with an **up** and **down** **button** within the window.

Now, if I press **up** button, incremented value should be **current_value**+**step_size** = 7.5+3.1=10.6. But I get **9.3**(6.2+3.1) which is wrong. 

ipywidget version = 7.5.1.
Not sure if this is fixed in the latest version. Please advice. Thanks

```
from ipywidgets import widgets
widgets.BoundedFloatText(
    value=7.5,
    min=0,
    max=20.0,
    step=3.1,
    description='Test:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='.01f',
    slider_color='white'
)

```

**Comment by jasongrout** [comment]
If you have a min of 0 and a step of 3.1, 7.5 isn't a valid value. I see that in the ux too:
<img width="671" alt="Screen Shot 2020-05-13 at 8 01 29 AM" src="https://user-images.githubusercontent.com/192614/81829703-0aa70000-94f0-11ea-87ed-4274742ab42a.png">

**Comment by shek2994** [comment]
ok go it. Thanks.
