### ISSUE TITLE
python file can't render

### ISSUE THREAD

**Issue by limj0825** [jupyter-widgets/ipywidgets#2877]
![image](https://user-images.githubusercontent.com/46365419/82040784-b3648380-96d9-11ea-9e7c-7ae893799c19.png)

It can render html in cell, but when i put it into the py file, it can't render

![image](https://user-images.githubusercontent.com/46365419/82040846-cd9e6180-96d9-11ea-83e8-3cea2434a804.png)

i wonder to know how to solve this problem , thanks!!!

**Comment by SylvainCorlay** [comment]
This is expected behavior.

Running `!python3` invokes the `python3` shell command, and only display in the cell output what would have been printed if you had called `python3` from the command line.

**Comment by limj0825** [comment]
ok, thank you very much, so i just can use it in the cell ? it there any other way to render my html?

**Comment by SylvainCorlay** [comment]
You can put the content in a file, and in a function, import that file and run the said function.

**Comment by limj0825** [comment]
![image](https://user-images.githubusercontent.com/46365419/82042276-34247f00-96dc-11ea-8720-158f6c405643.png)
it works. thank you very much!!!
