### ISSUE TITLE
Closing widgets leaves a small blank line

### ISSUE THREAD

**Issue by e-dorigatti** [jupyter-widgets/ipywidgets#2880]
This becomes noticeable in a loop. For example, run this in a notebook:
```
from ipywidgets import HTML
for i in range(5):
    c = HTML(f'it. <b>{i}</b>')
    display(c)
    if i < 4:
        c.close()
```

Even though the widgets are closed, the container is still there, with non-zero height:

![Screenshot_20200520_102146_cropped](https://user-images.githubusercontent.com/5585926/82423593-7dc1f080-9a73-11ea-936d-30f55b2ed267.png)

This is the HTML:

```
<!-- first four empty containers are like this -->
<div class="p-Widget p-Panel jp-OutputArea-child">
  <div class="p-Widget jp-OutputPrompt jp-OutputArea-prompt"></div>
  <div class="p-Widget p-Panel jupyter-widgets jp-OutputArea-output p-mod-hidden"></div>
</div>

<!-- last container with content --->
<div class="p-Widget p-Panel jp-OutputArea-child">
  <div class="p-Widget jp-OutputPrompt jp-OutputArea-prompt"></div>
  <div class="p-Widget p-Panel jupyter-widgets jp-OutputArea-output">
    <div class="p-Widget jupyter-widgets widget-inline-hbox widget-html">
      <label class="widget-label" style="display: none;" title=""></label>
      <div class="widget-html-content">it. <b>4</b></div>
    </div>
  </div>
</div>
```

```

**Comment by e-dorigatti** [comment]
Guess this is a duplicate of [#1845](https://github.com/jupyter-widgets/ipywidgets/issues/1845). Sorry.

**Comment by jasongrout** [comment]
> Guess this is a duplicate of [#1845](https://github.com/jupyter-widgets/ipywidgets/issues/1845). Sorry.

Yes. It's a difficult problem because we're working around things in the notebook paradigm.
