### ISSUE TITLE
Widgets in [Box, HBox or VBox] displayed with a grey background

### ISSUE THREAD

**Issue by stefanmeili** [jupyter-widgets/ipywidgets#2893]
After building a new environment, widgets inside some containers are surrounded with a grey background. I can't track down what package causes the change in background. ipywidgets version in both environments is 7.5.1. Python 3.7.7 in both environments.

Individual widgets displayed correctly, but the grey box shows up as soon as you wrap one or more in a Box, HBox or VBox. Layouts appear to work fine until they're wrapped in a box.
![image](https://user-images.githubusercontent.com/16913760/83574497-70305000-a4e2-11ea-89b4-3b8522e07401.png)

Can anyone suggest which dependency may cause this or tell me how to change the background color of a box?

**Comment by jasongrout** [comment]
This is indeed odd. I would right-click on the gray box and select "Inspect Element" to look at the page source and see what had a gray background and where it was coming from.

**Comment by stefanmeili** [comment]
Thanks for the quick response, @jasongrout,

It looks like a VBox attribute, but I can't find it in the layout namespace. background-color doesn't exist and border is None.

Inspecting the object in the non-working environment:
![Flexbox Issue](https://user-images.githubusercontent.com/16913760/83665996-1cc10f00-a581-11ea-9506-b58a6ceadd2e.png)

Inspecting the same object in the working environment:
![image](https://user-images.githubusercontent.com/16913760/83666744-47f82e00-a582-11ea-983e-f7f287884266.png)

Other pertinent info is that I'm running linux mint 19.3 and firefox. I guess I could list both environments, but that's a lot of packages to sort through.

**Comment by jasongrout** [comment]
Thanks. It does look like that `.widget-box` css is drastically different. Assuming this is in classic Jupyter Notebook, what is `jupyter nbextension list` in both environments? In the non-working environment, can you click on the "inline:1" in the upper right corner of that bit of CSS to try to see where this CSS is coming from? It seems that something on the page is defining some different CSS for the `.widget-box` CSS class.

**Comment by stefanmeili** [comment]
Thanks again for the support.

`jupyter nbextension list` returns the following:
Working env:
```bash
Known nbextensions:
  config dir: /home/stefan/miniconda3/envs/ML/etc/jupyter/nbconfig
    notebook section
      voila/extension  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
     - Validating: OK
```

Broken env:
```bash
Known nbextensions:
  config dir: /home/stefan/miniconda3/envs/ML2/etc/jupyter/nbconfig
    notebook section
      voila/extension  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
 ```

Digging through the inline1 css, I'm fairly sure it's coming from bokeh which is also imported into the notebook that breaks in the new env. I'll try to put together a small example that can be reproduced.

**Comment by jasongrout** [comment]
It's possible that bokeh and ipywidgets have conflicting css classes both named `.widget-box`.

**Comment by stefanmeili** [comment]
Bokeh in both environments is 2.0.2, but it's loaded as an extension of holoviews. In the broken environment it's 1.13.2. in the working env it's 1.12.6.

The following code should reproduce the problem:
```python
import ipywidgets as widgets
import holoviews as hv
hv.extension('bokeh')
widgets.VBox([widgets.IntSlider()])
```
If I comment out the two holoviews lines the widget is displayed without issue. However, once the problem appears after importing holoviews, I have to reload the page to get rid of it. Restarting the kernel isn't enough.

So I think I have a workaround - downgrade holoviews.

Thanks again for your support.

**Comment by jasongrout** [comment]
CC @philippjfr  - it appears that there is a conflict in the css between ipywidgets and bokeh or holoviews? In ipywidgets, we define `.widgets-box` here: https://github.com/jupyter-widgets/ipywidgets/blob/3bd75276370271e43ca5aa38d59a1848dfb65fb7/packages/controls/css/widgets-base.css#L99-L104

I searched briefly in holoviews and bokeh and didn't find a corresponding `.widget-box` class. Do you know if there is a conflict? If so, is it intentionally overriding ipywidgets css?

**Comment by philippjfr** [comment]
Thanks for the headsup, the CSS is coming from Panel and we've already had a user fix it so starting in with Panel 0.10.0 (due to be released this month) this clash should go away.

**Comment by philippjfr** [comment]
For reference here is the PR: https://github.com/holoviz/panel/pull/1355

**Comment by jasongrout** [comment]
Thanks! Arguably we also should have been more specific in our CSS namespacing than just `.widget-*`, given that 'widget' is pretty generic. Perhaps for ipywidgets 8.0 we might use something like `.jw-*`...
