### ISSUE TITLE
More specific namespacing for CSS classes?

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#2896]
Right now our widget CSS classes are namespaced as `.widget-*`. `.widget` is pretty generic. For example, #2893 showed at least one conflict with another library.

Perhaps we should change the namespace to something like `.jw-*`, which seems more specific to 'jupyter widgets' and less generic than `.widget`

**Comment by philippjfr** [comment]
Seems like a good idea to me, bokeh prefixes its css classes with `bk-` for example.

**Comment by jasongrout** [comment]
This may need a deprecation cycle...

**Comment by maartenbreddels** [comment]
maybe adopting BEM https://www.freecodecamp.org/news/css-naming-conventions-that-will-save-you-hours-of-debugging-35cea737d849/ makes sense?

**Comment by marimeireles** [comment]
>This may need a deprecation cycle...

What does this mean? Adding to the relevant docs?

I can work on this if @maartenbreddels doesn't mind.

**Comment by maartenbreddels** [comment]
Please do!

**Comment by marimeireles** [comment]
@maartenbreddels, I don't think following BEM now is a good idea because nothing else in `ipywidgets` does.
But seems like a very good name convention. Maybe for a next version @jasongrout ?

**Comment by maartenbreddels** [comment]
I'm ok with that, but I thought it was good to put it on our radar.
