### ISSUE TITLE
'Error displaying widget' on jupyterlab

### ISSUE THREAD

**Issue by krlng** [jupyter-widgets/ipywidgets#2899]
I guess I have the same issue as (on which I am not allowed to comment): https://github.com/jupyter-widgets/ipywidgets/issues/2514

<img width="553" alt="Screenshot 2020-06-08 at 17 48 10" src="https://user-images.githubusercontent.com/1107509/84052027-4aa6b900-a9b0-11ea-9cd9-5d8935ef7210.png">

I tried out multiple settings and found that it works neither with the most recent (2.1.4) nor with (1.2.6). I can post some more details, but it is also visible on the productive binder version linked in  https://jupyterlab.readthedocs.io/en/stable/ if you open the notebook demo/notebooks/bqplot.ipynb.

**Comment by martinRenou** [comment]
Could you please open an issue on the bqplot repository instead? Please be sure to install the labextension for both bqplot and ipywidgets: https://github.com/bqplot/bqplot#installation

**Comment by krlng** [comment]
I am pretty sure the problem is not bqplot especially, but something within jupyter-widgets or probably jupyter-manager, because I get kind of the same error if I try to use figures in any other context as well:

For example if I use plotly

```
import plotly.graph_objs as go
go.FigureWidget()
```

![Uploading Screenshot 2020-06-09 at 06.42.01.png…]()

or if I try to use the widget of azureML

```
from azureml.widgets import RunDetails
RunDetails(remote_run).show() 
```
<img width="549" alt="Screenshot 2020-06-09 at 06 50 24" src="https://user-images.githubusercontent.com/1107509/84107292-89268d00-aa1d-11ea-9217-96d6f63650d2.png">

> jupyter labextension list
JupyterLab v2.1.4
Known labextensions:
   app dir: /Users/nicokreiling/.local/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK

**Comment by martinRenou** [comment]
Do you have ipwidgets working? Do you get a button if you do:
```python
from ipywidgets import Button

display(Button(description='Click me'))
```

Looking at the labextension list you did not seem to install the bqplot labextension, nor the plotly one.

**Comment by krlng** [comment]
Yes, that works. Also a simple slider works.

I am sorry, I have way more extensions installed and forgot the Plotly extension:
        jupyterlab-plotly v4.8.1  enabled  OK

I do not have the bqplot labextension installed, that one was just the example I found on the binder page, which convinced me that it isn't just a local problem on my setup.

**Comment by martinRenou** [comment]
Are you sure `jupyterlab-plotly` is the right extension for the plotlywidget to work? Isn't it `jupyter labextension install plotlywidget` ?

**Comment by krlng** [comment]
I now also installed the plotlywidget, but that does not change anything. And I do not think it is plotly related, since all those libraries have a dependency problem when they try to load a widget module.

**Comment by krlng** [comment]
I was able to get it running by downgrading to ipywidgets==7.4.2

**Comment by martinRenou** [comment]
You could not expect the plotly widget to work if you did not have the plotly widget installed. All widgets extension have a specific labextension that you need to install separately: bqplot, ipyleaflet, plotly-widget etc.

> since all those libraries have a dependency problem when they try to load a widget module

What do you mean by that?
