### ISSUE TITLE
Add string formatting to SelectionSlider

### ISSUE THREAD

**Issue by ianhi** [jupyter-widgets/ipywidgets#2902]
### Issue
I can currently format the output of a `FloatSlider` but then I don't get the convenience of accessing the index of an array provided by a `SelectionSlider`. What I'd like to be able to do is:

```python
x = np.linspace(0,10,100)
slider = widgets.SelectionSlider(options = x, readout_format = '.2f')
....
x[slider.index] # where slider.index is an integer
```

however currently there is no format option so the result can look like this:
![image](https://user-images.githubusercontent.com/10111092/84705611-aa114580-af29-11ea-91a8-b36e75cd7153.png)

There are two basic workarounds
1. Use `widgets.Label` in conjunction with `widgets.IntSlider`
2. convert x to a list of formatted strings

However, both of those require more effort than the proposed `format` argument.

### Solution
Add a `readout_format` option a la the FloatSlider
https://github.com/jupyter-widgets/ipywidgets/blob/6be18d9b75353f7b4a1c328c6ea06d8959f978f6/ipywidgets/widgets/widget_float.py#L173-L174
It would have to be more general than the `NumberFormat` as the SelectionSlider can also work with strings but if the default was unformatted then this wouldn't change the current behavior without opt-in.

Thanks for consideration :) - and a bigger thanks for widgets generally

**Comment by jasongrout** [comment]
As you note, the selection slider works with arbitrary objects and lets you give exactly the string for each element. So what you can do is just format the values yourself:

```python
import numpy as np
import ipywidgets as widgets
x = np.linspace(0,10,100)
slider = widgets.SelectionSlider(options = [("{:.2f}".format(i), i) for i in x], readout_format = '.2f')
slider
```

**Comment by jasongrout** [comment]
> convert x to a list of formatted strings

What I suggest above is sort of like this, but is a bit different in that the value of the selection slider is still from your original numbers.

**Comment by ianhi** [comment]
Awesome thanks! I see now reading the documentation that this information is there, I just had only focused on the SelectionSlider example and not the nearby examples demonstrating this.

**Comment by jasongrout** [comment]
Great! Closing as answered, then.
