### ISSUE TITLE
AttributeError: ipywidgets.Box() object has no attribute '_repr_mimebundle_'

### ISSUE THREAD

**Issue by Kreijstal** [jupyter-widgets/ipywidgets#2906]
I was trying to run the example of Variable Inspector in google [colab](https://colab.research.google.com/github/jupyter-widgets/ipywidgets/blob/master/docs/source/examples/Variable%20Inspector.ipynb#scrollTo=Ta3fRfkF9AEf), and I encounter this error. Because of this line: https://github.com/jupyter-widgets/ipywidgets/blob/6be18d9b75353f7b4a1c328c6ea06d8959f978f6/docs/source/examples/Variable%20Inspector.ipynb#L84

Apparently it doesn't work as intended.
This is google colab's version
```jupyter core     : 4.5.0
jupyter-notebook : 5.2.2
qtconsole        : 4.5.2
ipython          : 5.5.0
ipykernel        : 4.10.1
jupyter client   : 5.3.1
jupyter lab      : not installed
nbconvert        : 5.5.0
ipywidgets       : 7.5.0
nbformat         : 4.4.0
traitlets        : 4.3.2
```
You see it has ipywidgets 7.5.0 is this version too old?

**Comment by Kreijstal** [comment]
https://colab.research.google.com/github/jupyter-widgets/ipywidgets/blob/7.x/docs/source/examples/Variable%20Inspector.ipynb
seems to work for now, an older version, I think I'll just use that.

**Comment by jasongrout** [comment]
Thanks. IIRC, that example has changed in master and is no longer compatible with 7.x, so using the 7.x branch version is the right thing to do.
