### ISSUE TITLE
Output.append_display_data() and Output.append_stdout() appending to different cells

### ISSUE THREAD

**Issue by tmtabor** [jupyter-widgets/ipywidgets#2907]
Here's how to reproduce the issue:

### Cell 1

```python
from ipywidgets import Output

output = Output()
output
```

### Cell 2

```python
from ipywidgets import Button

output.append_display_data(Button(description='foo'))
output.append_stdout('bar')
```

When you run these two cells, you will notice that the button appears in Cell 2 and the text appears in Cell 1, despite the fact that they're both being appended to the Output widget in Cell 1. I assume this is a bug.

(I encountered this with ipywidgets 7.5.1 and IPython 7.14.0.)

**Comment by jasongrout** [comment]
Closing as answered, but feel free to continue the discussion if you would like.

**Comment by jasongrout** [comment]
cf https://github.com/jupyter-widgets/ipywidgets/issues/1811 https://github.com/jupyter-widgets/ipywidgets/issues/2530
