### ISSUE TITLE
Incorrect Images in Low Level Widget Tutorial - All images are the same

### ISSUE THREAD

**Issue by ianhi** [jupyter-widgets/ipywidgets#2908]
If you go to either the Low Level Widget tutorial on either the [stable](https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Low%20Level.html) or [latest](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Low%20Level.html) links then all the images meant to demonstrate the messaging and that accompany the text are just the same overview image repeated for every paragraph.
![image](https://user-images.githubusercontent.com/10111092/85960463-ac37c300-b971-11ea-9081-9a144049f68b.png)

![image](https://user-images.githubusercontent.com/10111092/85960457-a3df8800-b971-11ea-84a2-148f9fb5a745.png)
etc...

 In contrast the source notebook has different images https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/examples/Widget%20Low%20Level.ipynb for different paragraphs. 
![image](https://user-images.githubusercontent.com/10111092/85960479-beb1fc80-b971-11ea-91e6-7b76d891dbb4.png)

I don't know why this is but maybe regenerating the docs would help? The notebook with the correct images is far more helpful for understanding what is going on so it would be great to have those images in the online docs.

**Comment by jtpio** [comment]
Thanks @ianhi.

It would indeed be useful to fix this part of the docs. Maybe it's just a matter of regenerating it if the sources already exist.

Otherwise we could recreate the diagrams with something like https://app.diagrams.net/

**Comment by ianhi** [comment]
There are these warnings when buliding the docs locally:

```
/home/ian/Documents/jupyter/ipywidgets/docs/source/examples/Widget Low Level.ipynb:109: WARNING: Duplicate substitution definition name: "image1".
/home/ian/Documents/jupyter/ipywidgets/docs/source/examples/Widget Low Level.ipynb:146: WARNING: Duplicate substitution definition name: "image1".
/home/ian/Documents/jupyter/ipywidgets/docs/source/examples/Widget Low Level.ipynb:296: WARNING: Duplicate substitution definition name: "image1".
/home/ian/Documents/jupyter/ipywidgets/docs/source/examples/Widget Low Level.ipynb:341: WARNING: Duplicate substitution definition name: "image1".
/home/ian/Documents/jupyter/ipywidgets/docs/source/examples/Widget Low Level.ipynb:365: WARNING: Duplicate substitution definition name: "image1".
/home/ian/Documents/jupyter/ipywidgets/docs/source/examples/Widget Low Level.ipynb:401: WARNING: Duplicate substitution definition name: "image1".
/home/ian/Documents/jupyter/ipywidgets/docs/source/examples/Widget Low Level.ipynb:425: WARNING: Duplicate substitution definition name: "image1".
/home/ian/Documents/jupyter/ipywidgets/docs/source/examples/Widget Low Level.ipynb:449: WARNING: Duplicate substitution definition name: "image1".
/home/ian/Documents/jupyter/ipywidgets/docs/source/examples/Widget Low Level.ipynb:486: WARNING: Duplicate substitution definition name: "image1".
```

**Comment by ianhi** [comment]
I think this is the same as https://github.com/spatialaudio/nbsphinx/issues/162
