### ISSUE TITLE
Colorbar/colorscale widget?

### ISSUE THREAD

**Issue by nvaytet** [jupyter-widgets/ipywidgets#2915]
Similarly to the `ColorPicker` widget, it would be very useful to have a `Colorbar` or `ColorScale` widget which would display a colorbar, with options to change the colormap (say from 'viridis' to 'magma'), and also change the min/max limits.
An option to also change to `log` would be great.

This may however be tying `ipywidgets` to some `matplotlib` code, which might not be within the scope of the project?

**Comment by martinRenou** [comment]
It might not be in the scope of ipywidgets but it would be great to see a custom widgets library that can do this.

@vidartf 's https://github.com/vidartf/ipyscales does this if I recall correctly.

> This may however be tying ipywidgets to some matplotlib code, which might not be within the scope of the project?

It might be better to do this without relying on Matplolib.

**Comment by nvaytet** [comment]
Nice, did not know about `ipyscales`, thanks for the link!

**Comment by vidartf** [comment]
Closing as answered :)
