### ISSUE TITLE
Enable Read The Docs Autobuild for Pull Requests

### ISSUE THREAD

**Issue by jtpio** [jupyter-widgets/ipywidgets#2921]
It would be nice if we could enable the "Autobuild Documentation for Pull Requests" feature of Read the Docs for this repo.

As an example, this was recently enabled in voila:

- https://github.com/voila-dashboards/voila/issues/649
- https://github.com/voila-dashboards/voila/pull/650#issuecomment-658122443

And it looks like this:

![image](https://user-images.githubusercontent.com/591645/87419663-2ef88900-c5d4-11ea-8de9-6ba4e2146d8b.png)

Clicking on Details redirects to the built docs with a warning header at the top:

![image](https://user-images.githubusercontent.com/591645/87425929-c5ca4300-c5de-11ea-95b7-31119e482dc8.png)

To make it work, we need to make sure to (if not already):

> add 'jupyter-widgets' org in https://readthedocs.org/accounts/social/connections/

(from https://github.com/voila-dashboards/voila/pull/650#issuecomment-658120051).

This might also make it easier to contribute documentation changes.

**Comment by jtpio** [comment]
cc @maartenbreddels

**Comment by martinRenou** [comment]
:+1: This would be really useful in ipyleaflet as well.

**Comment by jtpio** [comment]
cc @willingc who might also be interested

**Comment by jtpio** [comment]
Mentioning a couple more owners of the `jupyter-widgets` organization who could help with this:

@jasongrout @SylvainCorlay @vidartf @mwcraig 

Thanks!

**Comment by mwcraig** [comment]
Looks like I'm not a maintainer on RTD. If I'm added I'm happy to flip the switch. This feature is really convenient.

**Comment by willingc** [comment]
@jtpio I added a RTD webhook here, and updated the builds with RTD. We should now have autobuilds on new merges. Closing this.

**Comment by willingc** [comment]
Oops I resolved the autobuilds on merge. The autobuild on PR is still needed.

**Comment by willingc** [comment]
OK. I've now enable autobuild on PRs in the RTD advanced settings under Admin.

**Comment by willingc** [comment]
<img width="1160" alt="Screen Shot 2021-02-06 at 2 30 08 PM" src="https://user-images.githubusercontent.com/2680980/107131026-f843d200-6887-11eb-9a90-b190485d2717.png">
