### ISSUE TITLE
interact shows outputs in a small window below the widget selection input that cannot be expanded

### ISSUE THREAD

**Issue by jdrylewicz** [jupyter-widgets/ipywidgets#2936]
hi,
I am using interact on a function which plots a graph (it does not return the graph it plots it within the routine). In the cell, the output comes back  trimmed and rendered in a small window which cannot be expanded (I have a scroll bar menu instead on the right). When I run the cell the image seems to flash very quickly in normal/full size before  disappearing and shrinking to that smaller window.

I also tried using interactive_output and play with the layout features but I could not find which property to tweak.

If I run the cell without the widget and just call the function the output is a normal matplotlib graph and I can expand the cell to see the whole output normally.

Please let me know how to see the output normally when using the widget. Thanks.

These are the versions I use: 

jupyter core     : 4.6.3
jupyter-notebook : 5.7.5
qtconsole        : 4.3.1
ipython          : 7.16.1
ipykernel        : 5.3.4
jupyter client   : 6.1.6
jupyter lab      : 2.2.2
nbconvert        : 5.6.1
ipywidgets       : 7.0.0
nbformat         : 5.0.7
traitlets        : 4.3.3

**Comment by jdrylewicz** [comment]
actually using %matplotlib widget as opposed to %matplotlib inline fixed it.

**Comment by ianhi** [comment]
Hey @jdrylewicz I think ipympl is definitely the easiest way to get the functionality you want but this maybe should be re-opened as I believe that the interactive_output functions should also work with the inline backend as there is some special casing for that: https://github.com/jupyter-widgets/ipywidgets/blob/6be18d9b75353f7b4a1c328c6ea06d8959f978f6/ipywidgets/widgets/interaction.py#L59-L68

If you have the time to post a minimal example that may prove helpful in fixing a bug.

**Comment by jdrylewicz** [comment]
Hi,
I posted a code sample on a different thread:

https://github.com/jupyter-widgets/ipywidgets/issues/2937 <https://github.com/jupyter-widgets/ipywidgets/issues/2937>
