### ISSUE TITLE
Combobox does not work if options contain double quotes (")

### ISSUE THREAD

**Issue by ceball** [jupyter-widgets/ipywidgets#2940]
The second combobox doesn't offer any drop-down options:

![combobox](https://user-images.githubusercontent.com/1929/89279511-5e347000-d63f-11ea-8786-c6f0dfd42ed6.gif)

Code to reproduce the above:
```python
import ipywidgets
print(ipywidgets.__version__)
display(ipywidgets.Combobox(options=['OptionA','OptionB']))
display(ipywidgets.Combobox(options=['"Option A"','"Option B"']))
```

@vidartf pointed out the issue is here, with html escaping:

https://github.com/jupyter-widgets/ipywidgets/blob/6be18d9b75353f7b4a1c328c6ea06d8959f978f6/packages/controls/src/widget_string.ts#L534-L536

**Comment by concaho** [comment]
Hi guys,
Any ETA for this issue ? 
Thanks,
Hadrien
