### ISSUE TITLE
Support for CommonJS

### ISSUE THREAD

**Issue by ktech99** [jupyter-widgets/ipywidgets#2955]
I have been trying to implement Ipython Widgets just like in the [web-3](https://github.com/jupyter-widgets/ipywidgets/tree/master/examples/web3) example, but I keep getting the error `Unexpected token export`.

I believe that this occurs because we are using CommonJS, and these widgets use ESnext.
Is there a version of these packages, particularly @jupyter-widgets/html-manager, @jupyter-widgets/base; which I can use with CommonJS?

I have a constraint that I have to use @jupyterlab/services version 3.2.0 up to 4.0.0
Any suggestions or help would be welcome.

**Comment by jasongrout** [comment]
We don't compile these packages to commonjs anymore (see the setting at https://github.com/jupyter-widgets/ipywidgets/blob/6be18d9b75353f7b4a1c328c6ea06d8959f978f6/tsconfigbase.json#L11). Does your bundling tool not understand es modules?

Looks like you could use `@jupyter-widgets/base` version 1 (which was at that time compiled to commonjs): https://github.com/jupyter-widgets/ipywidgets/blob/34060411e6cd6398d697acb27611343d1133e8a0/packages/base/src/tsconfig.json#L8

**Comment by jasongrout** [comment]
Closing as answered. Thanks!
