### ISSUE TITLE
Update semver for jupyterlab-manager

### ISSUE THREAD

**Issue by fcollonval** [jupyter-widgets/ipywidgets#2957]
The semver package is duplicated on JupyterLab 2.2.6 when installing ipywidgets as there is a newer version 7. That version is a [refactoring of the v6](https://github.com/npm/node-semver/blob/master/CHANGELOG.md#700). So it should be safe to update it - I personally updated it in [jupyter_conda](https://github.com/fcollonval/jupyter_conda/tree/master/labextension) without problem.

**Comment by jtpio** [comment]
Closing as `semver` was updated to version 7 in https://github.com/jupyter-widgets/ipywidgets/pull/3215 :

https://github.com/jupyter-widgets/ipywidgets/blob/b78de43e12ff26e4aa16e6e4c6844a7c82a8ee1c/python/jupyterlab_widgets/package.json#L73
