### ISSUE TITLE
BoundedIntText: Pressing ENTER should trigger change event

### ISSUE THREAD

**Issue by chaffra** [jupyter-widgets/ipywidgets#2959]
Pressing `ENTER` after changing value of `BoundedIntText` does not trigger event change. Works for `BoundedFloatText`. To reproduce, run snippet below and try pressing `ENTER` after changing the value. Pressing `Tab` does what's expected.
```
num_rows = widgets.BoundedIntText(min=1, max=2**16, step=1, description='num_rows')
def on_value_change(change):
    print(change['new'])
num_rows.observe(on_value_change, names='value')
num_rows
```

**Comment by agoose77** [comment]
My team are currently developing a resource using ipywidgets, and all of the alpha testers have so far noticed this.

**Comment by gsteele13** [comment]
is there any progress on this? I also just noticed it, is is a bit annoying...?

**Comment by jasongrout** [comment]
Looks like https://github.com/jupyter-widgets/ipywidgets/pull/2975 is a PR fixing it. I've added it to my review queue.

**Comment by jasongrout** [comment]
@agoose77 - sorry I didn't see that PR earlier. Thanks for submitting it!
