### ISSUE TITLE
Error while installing jupyter labextension install @jupyter-widgets/jupyterlab-manager

### ISSUE THREAD

**Issue by ramanamohan** [jupyter-widgets/ipywidgets#2961]
I am getting error while installing the jupyter labextention, below is the error log

Node v10.13.0

> C:\Users\310208851\Anaconda3\npm.CMD pack @jupyter-widgets/jupyterlab-manager
npm notice 
npm notice package: @jupyter-widgets/jupyterlab-manager@2.0.0
npm notice === Tarball Contents === 
npm notice 1.5kB  LICENSE             
npm notice 380B   lib/index.js        
npm notice 15.3kB lib/manager.js      
npm notice 5.3kB  lib/output.js       
npm notice 7.8kB  lib/plugin.js       
npm notice 3.3kB  lib/renderer.js     
npm notice 862B   lib/semvercache.js  
npm notice 2.3kB  package.json        
npm notice 375B   schema/plugin.json  
npm notice 2.1kB  README.md           
npm notice 277B   lib/index.d.ts      
npm notice 6.0kB  lib/manager.d.ts    
npm notice 1.9kB  lib/output.d.ts     
npm notice 828B   lib/plugin.d.ts     
npm notice 960B   lib/renderer.d.ts   
npm notice 216B   lib/semvercache.d.ts
npm notice === Tarball Details === 
npm notice name:          @jupyter-widgets/jupyterlab-manager         
npm notice version:       2.0.0                                       
npm notice filename:      jupyter-widgets-jupyterlab-manager-2.0.0.tgz
npm notice package size:  13.3 kB                                     
npm notice unpacked size: 49.4 kB                                     
npm notice shasum:        05ab402833df07aac1ec2c549a1d748b3c303185    
npm notice integrity:     sha512-i+qtbEe//W9Ru[...]Fu0KbkxM9aQXQ==    
npm notice total files:   16                                          
npm notice 
jupyter-widgets-jupyterlab-manager-2.0.0.tgz

Fetching URL: https://registry.npmjs.org/@jupyter-widgets%2Fjupyterlab-manager
Failed to fetch package metadata for '@jupyter-widgets/jupyterlab-manager': URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)'))
Fetching URL: https://registry.npmjs.org/@jupyter-widgets%2Fjupyterlab-manager
Failed to fetch package metadata for '@jupyter-widgets/jupyterlab-manager': URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)'))
Traceback (most recent call last):

  File "C:\Users\310208851\Anaconda3\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "C:\Users\310208851\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 93, in start
    ans = self.run_task()

  File "C:\Users\310208851\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 147, in run_task
    for i, arg in enumerate(self.extra_args)

  File "C:\Users\310208851\Anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 147, in <listcomp>
    for i, arg in enumerate(self.extra_args)

  File "C:\Users\310208851\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 321, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "C:\Users\310208851\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 525, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "C:\Users\310208851\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 1450, in _install_extension
    raise ValueError(msg)

ValueError: No version of @jupyter-widgets/jupyterlab-manager could be found that is compatible with the current version of JupyterLab.

Conflicting Dependencies:
JupyterLab                        Extension      Package
>=1.1.3 <1.2.0                    >=2.0.0 <3.0.0 @jupyterlab/application
>=1.1.3 <1.2.0                    >=2.0.0 <3.0.0 @jupyterlab/notebook
>=1.1.3 <1.2.0                    >=2.0.0 <3.0.0 @jupyterlab/rendermime
>=1.4.0 <1.5.0                    >=2.0.0 <3.0.0 @jupyterlab/rendermime-interfaces
>=4.1.1 <4.2.0                    >=5.0.0 <6.0.0 @jupyterlab/services

Exiting application: jupyter

Appreciate the help.

**Comment by ianhi** [comment]
What version of jupyterlab are you using?

**Comment by ramanamohan** [comment]
> What version of jupyterlab are you using?

Version details-
jupyter core     : 4.5.0
jupyter-notebook : 6.0.1
qtconsole        : 4.5.5
ipython          : 7.8.0
ipykernel        : 5.1.2
jupyter client   : 5.3.3
jupyter lab      : 1.1.4
nbconvert        : 5.6.0
ipywidgets       : 7.5.1
nbformat         : 4.4.0
traitlets        : 4.3.3

**Comment by ianhi** [comment]
ah it looks like node was trying to install the version for jlab 2. From the readme (https://github.com/jupyter-widgets/ipywidgets#install):
For JupyterLab 1.0.x and 1.1.x, use `jupyter labextension install @jupyter-widgets/jupyterlab-manager@1.0`
For JupyterLab 1.2.x, use `jupyter labextension install @jupyter-widgets/jupyterlab-manager@1.1`

so I think you want the first option. Alternatively you could upgrade to jupyterlab version 2, either approach should work

**Comment by ramanamohan** [comment]
> ah it looks like node was trying to install the version for jlab 2. From the readme (https://github.com/jupyter-widgets/ipywidgets#install):
> For JupyterLab 1.0.x and 1.1.x, use `jupyter labextension install @jupyter-widgets/jupyterlab-manager@1.0`
> For JupyterLab 1.2.x, use `jupyter labextension install @jupyter-widgets/jupyterlab-manager@1.1`
> 
> so I think you want the first option. Alternatively you could upgrade to jupyterlab version 2, either approach should work

Nice, it worked very well.

Thanks a lot ianhi.

**Comment by vidartf** [comment]
Sounds like this was resolved! Thanks @ianhi 🥇
