### ISSUE TITLE
This is a bug that occurs with nbformat < 4.2. If you update nbformat, this should go away.

### ISSUE THREAD

**Issue by Jihyun22** [jupyter-widgets/ipywidgets#2963]
This is a bug that occurs with nbformat < 4.2. If you update nbformat, this should go away.

_Originally posted by @SylvainCorlay in https://github.com/jupyter-widgets/ipywidgets/issues/1305#issuecomment-295957837_

**Comment by jasongrout** [comment]
Yes, thank you.
