### ISSUE TITLE
Grid of accordions treats every accordion as selected

### ISSUE THREAD

**Issue by luca1308** [jupyter-widgets/ipywidgets#2971]
Hi, I made a grid of accordions with this function:
```
def detail_acc(legend_text, names):
    vert = len(legend_text)
    tgrid = GridspecLayout(vert, 1)
 
    for i in range(len(legend_text)-1):
        tgrid[i,0] = create_acc(legend_text[i].format(i,0), names[i])
    return tgrid
```
and the accordion function looks like this:
```
def create_acc(description, names): 
    acc_placeholder = widgets.HTML(value= names) 
    acc = widgets.Accordion(children=[acc_placeholder], selected_index=None, style={'font_weight': 'bold'}, layout=Layout( width='auto'))
    acc.set_title(0, description)
    return acc
```
Now when I click on one of the accordions to expand it, the space in between every single one is treated as if all were expanded.
How can I prevent this?

**Comment by vidartf** [comment]
Just for ease of triage, would you mind sharing a screenshot?

**Comment by luca1308** [comment]
> Just for ease of triage, would you mind sharing a screenshot?

Of course not, sorry.
Closed
![Closed](https://user-images.githubusercontent.com/60759393/93528062-10976c80-f93a-11ea-8582-408da7542015.png)

And now opened the second accordion in the grid
![Opened](https://user-images.githubusercontent.com/60759393/93528066-11c89980-f93a-11ea-8388-1627a5fe6911.png)

**Comment by luca1308** [comment]
> Just for ease of triage, would you mind sharing a screenshot?

And you can find a binder version [here](https://mybinder.org/v2/gh/luca1308/covidmaxdrawdown/master?filepath=display.ipynb)

**Comment by luca1308** [comment]
I decided to use this (not too pretty) workaround, which limits the widget to a size based on the number of accordions in the grid.
This, unfortunately, means that the widgets become scrollable when several, especially bigger accordions are opened:
```
def detail_acc(legend_text, names):
    height = str(len(legend_text)*100)+"px"
    layout ={'max_height': height}
    vert = len(legend_text)

    tgrid = GridspecLayout(vert, 1, layout=layout)
    
    for i in range(len(legend_text)-1):
        tgrid[i,0] = create_acc(legend_text[i].format(i,0), names[i])
    return tgrid
```
