### ISSUE TITLE
Add a widget dynamically to a interactive Object

### ISSUE THREAD

**Issue by vk496e1** [jupyter-widgets/ipywidgets#2978]
Hello,

First, thank you for your great work!

I'm trying to create a table where a user could add filters by himself to filter the rows. However, I'm not able to handle a very basic example of appending sliders to an already existing widget. A example:

```python
from IPython.display import display

def sum_all_args(**kwargs):
    d = 0
    for i, k in enumerate(kwargs.values()):
        d += k
    display(d)
    return d

w = interactive(sum_all_args,
                a=3,
                b=6
       )

display(w)
```
![image](https://user-images.githubusercontent.com/55134256/94012827-93d91800-fda9-11ea-8d7f-b25b05bbbc8d.png)

Until here all OK. But if I want to append a other IntSlider:

```python
new_elem = widgets.IntSlider(description='c', value=3, max=30, min=-30)
w.children += (new_elem,)
```

![image](https://user-images.githubusercontent.com/55134256/94012924-af442300-fda9-11ea-9019-438895ff5693.png)

The c slider is not "catched" by the function `sum_all_args`, so the final values is only linked to args `a` and `b`.

I've tried to manually "link" them with `new_elem.observe(w.update, names='value')`, but it doesn't work (the result don't change even if it "flash" when I move `c`).

What I'm doing wrong?

Thanks in advance

**Comment by ianhi** [comment]
Hey @vk496e1 you're on the right track with using `observe` to manually link the new widget to the callback. However, you need to take it a bit farther and do it fully manually. I don't think there is an easy way to add a widget into the callback generated by `interactive`. I think the following will do what you want:

```python
import ipywidgets as widgets

out = widgets.Output()
@out.capture(clear_output=True, wait=True)
def sum_all_args(change):
    d = 0
    for s in sliders.values():
        d += s.value
    display(d)
    return d
sliders = {}
sliders['a'] = widgets.IntSlider(value=3, min=-3, max=10, description='a')
sliders['b'] = widgets.IntSlider(value=6, min=-3, max=10, description='b')
for slider in sliders.values():
    slider.observe(sum_all_args, names='value')
controls = widgets.VBox(list(sliders.values()))
# run the function with a dummy argument once to initialize the display
sum_all_args(None)
display(widgets.VBox([controls, out]))
```

followed by:
```python
sliders['c'] = widgets.IntSlider(description='c', value=3, max=30, min=-30)
sliders['c'].observe(sum_all_args, names='value')
sum_all_args(None) # run again to instantly update
controls.children += (sliders['c'],)
```

gives this:
![Peek 2020-11-17 18-03](https://user-images.githubusercontent.com/10111092/99461165-47204200-28ff-11eb-83f1-a3a0e747c8e5.gif)

**Comment by vk496e1** [comment]
Thank you!

Is exactly what I was looking for. Directly related with this: https://stackoverflow.com/questions/64277556/ipywidgets-bind-dynamically-widgets-to-output

Have a good day :)
