### ISSUE TITLE
expose colo(u)r for IntProgress/FloatProgress

### ISSUE THREAD

**Issue by casperdcl** [jupyter-widgets/ipywidgets#2982]
### Problem

- `IntProgress` and `FloatProgress` have a `bar_style` argument to control colour... yet the option strings it accepts don't sound like they control colour. Directly defining custom colours is also not documented. This seems an odd design choice (or lack thereof).

### Proposed Solutions

- document the `style` kwarg, i.e.: `style={'bar_color': 'green'}`
- let `bar_style` accept colours (hex or plaintext, `'#00ff00' == 'green' == 'success'`)
- potentially rename this option `colour` (or `color` to keep Americans happy)
- or maybe just deprecate `bar_style`

### Additional context

https://github.com/tqdm/tqdm/issues/450#issuecomment-699544451

**Comment by ianhi** [comment]
It looks like these are exposed, though perhaps not in the most obvious way. You need to set them after you create the widget:
```python
import ipywidgets as widgets
prog = widgets.IntProgress()
prog.value = 50
prog.style.bar_color = 'maroon'
display(prog)
```
![image](https://user-images.githubusercontent.com/10111092/94368692-8c6c8400-00b3-11eb-8e13-dbc90896fc9f.png)

(Also, I :heart: tqdm)

Looking at the code here: https://github.com/jupyter-widgets/ipywidgets/blob/6667f8135e3877adc085afe5fc0569a04133a495/ipywidgets/widgets/widget_int.py#L173-L193 it seems that it should all these forms for colors:
https://github.com/jupyter-widgets/ipywidgets/blob/6667f8135e3877adc085afe5fc0569a04133a495/ipywidgets/widgets/trait_types.py#L13-L33

**Comment by casperdcl** [comment]
hmm thanks (though as you say, non-intuitive). Maybe wanna consider tidying up the init kwargs...

```python
import ipywidgets as widgets
prog = widgets.IntProgress()
prog.value = 50
#prog.style.bar_color = 'maroon'  # overrides `bar_style`
#prog.bar_style = 'success'  # turns green only if `bar_color` not set
display(prog)
```

or better:

```python
import ipywidgets as widgets
prog = widgets.IntProgress(style={'bar_color': 'maroon'})
prog.value = 50
display(prog)
```

Feel free to close if you want.

**Comment by ianhi** [comment]
It looks like your "or better" actually does work.

> Feel free to close if you want.

I don't have write access so I definitely won't do that :P. Also, I think this should stay open regardless as it is an opportunity to improve the documentation.

**Comment by casperdcl** [comment]
ah srry thought you were a maintainer. Was being lazy. Anyway updated the description.

**Comment by jtpio** [comment]
@casperdcl would you like to open a PR to update the docs?

**Comment by casperdcl** [comment]
do you mean update the `docs/` folder within this repo?

**Comment by jtpio** [comment]
Yes, if you think it would be useful for the examples provided in the comments above to be in the documentation.
