### ISSUE TITLE
JupyterLab Setup is unclear

### ISSUE THREAD

**Issue by keckelt** [jupyter-widgets/ipywidgets#2983]
### Problem

Hi!
I had a hard time to understand what is actually necessary to install when using ipywidgets in JupyterLab.
I tried following the documentation here: https://ipywidgets.readthedocs.io/en/latest/user_install.html

And eventually I was successful by putting `ipywidgets` and `nodejs` into my requirements.txt file and then enabling then installing the lab extension `jupyter labextension install @jupyter-widgets/jupyterlab-manager`.

However, it was unclear which things apply to my setup.
The first line in "Installing the JupyterLab Extension" says:

> To install the JupyterLab extension you also need to run the command below in a terminal which requires that you have nodejs installed.

"Also", also to what?
The headlines are all on the same level, so the JupyterLab instructions are not a subsection of something that was already installed. 

Some of my thoughts:
* The instruction for  Jupyterlab uses conda, but the conda section above says in enables the extension already.
* Do i need the widgetsnbextension too?
* Do I actually have to install ipywidgets if I install the extension?

I was additionally confused by this Binder example that I eventually discarded: https://github.com/binder-examples/jupyter-extension/

### Proposed Solution

I would suggest to either restructure to add some hierarchy to see what builds on top of what. or make the section self contained such that you only need to follow that are there.

**Comment by martinRenou** [comment]
> "Also", also to what?

Also to `pip install ipywidgets` or `conda install -c conda-forge` ipywidgets

> The instruction for Jupyterlab uses conda, but the conda section above says in enables the extension already.

It's automatic only for the Jupyter Notebook, not for JupyterLab

> Do i need the widgetsnbextension too?

This should always be done automatically if you have a version of Jupyter Notebook that is recent enough. But this is never needed for JupyterLab.

> Do I actually have to install ipywidgets if I install the extension?

Well you need to install ipywidgets if you want to use it.


Note that the JupyterLab build will be simplified with JupyterLab 3, you won't need to install the labextension yourself anymore.

**Comment by keckelt** [comment]
Thanks for the quick feedback @martinRenou!

But do you see that the instructions could be confusing? If so, I can suggest some changes in a PR. If it's just me, that's fine too. No hard feelings.

**Comment by martinRenou** [comment]
I understand the instructions can be confusing, we get lots of reports from people who could not follow the installations steps properly and en up with broken JupyterLab installation. But again, this should be simplified with the new extension system in JupyterLab 3.

Soon, you'll **only** need to run `pip install ipywidgets` or `conda install -c conda-forge ipywidgets`.

**Comment by keckelt** [comment]
okay,thanks. I'll then close this again. Looking forward to v3 :)

**Comment by martinRenou** [comment]
me too :D
