### ISSUE TITLE
Cannot install jupyterlab-manager 

### ISSUE THREAD

**Issue by mbalandari** [jupyter-widgets/ipywidgets#2996]
Hi I am trying to install jupyterlab-manager:
jupyter labextension install @jupyter-widgets/jupyterlab-manager

but am getting an error: 
An error occured.
ValueError: "@jupyter-widgets/jupyterlab-manager" is not a valid extension:
schemaDir is empty: "./schema"

How may I solve it?

**Comment by vidartf** [comment]
Which version of jupyterlab are you using?

**Comment by mbalandari** [comment]
> Which version of jupyterlab are you using?

Thanks for the reply. I reinstalled the anaconda and it works now. 
Have a lovely day Vidar, and Thank you again :)
