### ISSUE TITLE
Continuous Play widget (in contrast to "loopy" one)

### ISSUE THREAD

**Issue by Dommsko** [jupyter-widgets/ipywidgets#2999]
### Problem

* Play widget requires setting of `max`
* For continuous animations this requires workarounds

### Proposed Solution

* Add an argument to `Play` that makes it count to infinity (for example: `infinite = True`)
* OR: create a new widget with continuous behaviour

### Additional context

I am using ipywidgets for academic teaching purposes of physical phenomena. However, for some phenomena a play button that is not restricted to a maximum number of steps would be the better choice. I tried writing my own class, but I don't get it to work in the same way. I just did an ugly modulo-based workaround (mainly because I don't understand the theory behind widgets). It is probably much slower than a native solution, too, so I would greatly appreciate any help from you devs <3

Kind regards,
Domme

**Comment by ianhi** [comment]
Does just setting `max` to a very large integer work? For example you can get the max integer value on your system with `np.iinfo(np.int).max`. For me this is `9223372036854775807`. At the default interval of 100ms per update that works out to be `29247120867.7536` years, which I'd argue is infinity for all practical purposes.

**Comment by Dommsko** [comment]
It works, but it's ugly ;-)

**Comment by ianhi** [comment]
> It works, but it's ugly ;-)

A cleaner thing than my numpy nonsense would just be to use some very big number thats easier to write. Like `max=1e10`.
I think any official widget that did this would ultimately just implement a solution like this as they need a value to increment, though it would hide the need to set that from you. 

I think there's an argument to be made for having a widget (or changing the play) for which if you don't provide a value for max it just chooses a very big number. You could probably even make your own pretty easily by borrowing form these lines:
https://github.com/jupyter-widgets/ipywidgets/blob/6667f8135e3877adc085afe5fc0569a04133a495/ipywidgets/widgets/widget_int.py#L224-L242

**Comment by ianhi** [comment]
You can make a class that inherits from play like this
(caveat - this may be terrible practice :man_shrugging: )

```python
from ipywidgets import Play
class infPlay(Play):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.max = 10e10
```
