### ISSUE TITLE
Unwanted scroll bars for Dropdowns

### ISSUE THREAD

**Issue by joctee** [jupyter-widgets/ipywidgets#3011]
In JupyterLab, when I use a Dropdown widget without a description, everything looks as expected. However, when I add a description, it looks like the div overflows resulting in a scrollbar being shown:

![image](https://user-images.githubusercontent.com/25039546/98512878-4cc6b980-2267-11eb-9776-bf47a494b1c4.png)

I'm not sure if this is an ipywidget or a JupyterLab problem.

Versions:
```
ipywidgets                7.5.1
jupyter                   1.0.0
jupyter_client            6.1.7
jupyter_console           6.2.0
jupyter_core              4.6.3
jupyterlab                2.2.6
jupyterlab_pygments       0.1.2
jupyterlab_server         1.2.0
```

```
$ jupyter labextension list
JupyterLab v2.2.6
Known labextensions:
   app dir: /home/joctee/anaconda_20201106/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        jupyterlab-plotly v4.12.0  enabled  OK
        plotlywidget v4.12.0  enabled  OK
        qgrid2 v1.1.3  enabled  OK*

   local extensions:
        qgrid2: /home/joctee/dev/qgrid/js
```

**Comment by Alexboiboi** [comment]
Hi @joctee,
I cannot reproduce your problem, but the scrollbar appears sometimes if your widget is in a HBox

**Comment by joctee** [comment]
Hi,

it turns out it was css from the [qgrid extension](https://github.com/quantopian/qgrid) that was causing this. It contained this:

```css
.jupyter-widgets { 
  overflow: auto !important; 
}
```

When this is removed, everything looks fine again.

**Comment by joctee** [comment]
Issue not related to ipywidgets.
