### ISSUE TITLE
150x latency on displaying image with interactive

### ISSUE THREAD

**Issue by ysig** [jupyter-widgets/ipywidgets#3012]
Hey,

I am using interactive to create a realtime plot from some sliders that I have customly made (around 25).
Inside my interactive function I use some inference from tensorflow, but by measuring it, takes only about 0.01 seconds (with the PIL.Image conversion).

Unfortunately the display of my function takes about 2s per images making the latency huge.
I guess this is related with update time, but I really don't have a clue and I couldn't find something online.
I am really searching for a way to optimize this effectively.
Do you have an idea?

Thanks,
ysig

**Comment by ianhi** [comment]
Hey @ysig could you provide a minimal working example? It's okay if it doesn't include the TF parts, the most important points are that:
1. It demonstrates the problem
2. it should be runnable after copy pasting it into a fresh notebook (ideally with minimal dependencies)

**Comment by ysig** [comment]
```
%matplotlib notebook 
import matplotlib
import matplotlib.pyplot as plt
import math
import numpy as np
import sys
import os
import asyncio
import warnings
import ipywidgets as widgets

import numpy as np
from PIL import Image
import imageio
from subprocess import call
import sys
from tqdm import trange
import sys

#@title Run UI
from ipywidgets import fixed
import time;
import numpy as np

def display_sample_pytorch(**kwargs):
    tic = time.perf_counter()
    out = (np.random.rand(512, 512, 3)*255).astype(np.uint8)
    time.sleep(0.01)
    toc = time.perf_counter()
    print(f"Image gen takes {toc - tic:0.4f} seconds1")
    display(Image.fromarray(out))

style = {'description_width': 'initial'}
kwargs = {}
components = []
for i in range(20):
    component = widgets.FloatSlider(min=-20, max=20, step=1.0, value=0, description=str(i), continuous_update=False, orientation='vertical', style=style)
    kwargs[str(i)] = component
    components.append(component)


bot_box = widgets.HBox(components)
ui = widgets.VBox([bot_box])
out = widgets.interactive_output(display_sample_pytorch, kwargs)
display(ui, out)

```

**Comment by ysig** [comment]
Voila. Also if you think the print function causes the problem, comment it and you will see it is unrelated.

**Comment by ysig** [comment]
I just discovered that a big part of this latency was related with **google-collab**.
There is still some latency on refreshing images, but it is related with the dimension of the image, which in the end, I guess is related with the use of matplotlib.imshow() by IPython display.

Thank you for your support.
