### ISSUE TITLE
Dead link in the doc

### ISSUE THREAD

**Issue by mocquin** [jupyter-widgets/ipywidgets#3016]
The link in the doc on [this page in the section about using interact](https://ipywidgets.readthedocs.io/en/latest/examples/Using%20Interact.html) in the last sentence hereafter seems dead.

[From the doc about using interact](https://ipywidgets.readthedocs.io/en/latest/examples/Using%20Interact.html#Widget-abbreviations) : 

> Finally, if you need more granular control than that afforded by the abbreviation, you can pass a ValueWidget instance as the argument. A ValueWidget is a widget that aims to control a single value. Most of the widgets bundled with ipywidgets inherit from ValueWidget. For more information, see [this section](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Custom.ipynb#DOMWidget,-ValueWidget-and-Widget) on widget types.

**Comment by jtpio** [comment]
Closing as the link appears to be working now.

Thanks @mocquin for reporting!
