### ISSUE TITLE
Output Widget not displaying all of the results

### ISSUE THREAD

**Issue by dakenblack** [jupyter-widgets/ipywidgets#3017]
Hi,
I've been trying to create a generic class for me to run background tasks in a notebook. I've removed a lot of things to create an example of the problem (https://gist.github.com/dakenblack/d8a546227c97c3f9969da4ee38f94cbe). 

Issue : all of the text (I expect to see 10 TEST\n20 TEST\n30 TEST...) is not rendered in the output panel. See screenshot
![2020-11-18_12h23_28](https://user-images.githubusercontent.com/11382198/99470497-f2c9a080-2998-11eb-9b0e-a8f85a85372f.png)

How to reproduce
- run cell 1 to create threads and display the widgets
- run cell 2 to start the thread
  - the progress bar will update
  - the output text will start to be printed but not all of the output
- run cell 3 to stop the thread
  - a message will be displayed indicating that the thread was stopped
  - sometimes some more of the output is displayed once the thread is stopped

System Parameters
System: Windows 10
ipython : 7.16.1
ipywidgets : 7.5.1
Jupyter Lab : 2.1.5

I posted here because I believe the issue is with the output panel, if I have posted in the wrong place let me know.

**Comment by ianhi** [comment]
You've got some nested output contexts in there, which I'd guess is problematic. If I change your example to only use a single output context then I always get all of the output printed out:
```python
from IPython.display import display
from ipywidgets import FloatProgress, Output, VBox
import time
import threading
import datetime

class Job(object):
    def __init__(self, nloops=2000):
        self.nloops = nloops
        self.pb = FloatProgress(description='Progress Bar', min=0, max=1)
        self.out = Output()
        self._stopped = threading.Event()
        
    def display(self):
        display(VBox([self.pb, self.out]))

    def run(self):
        ticker = 1.0
        while ticker < self.nloops and not self._stopped.isSet():
            ticker += 1
            self.pb.value = ticker / self.nloops 
            # time.sleep(0.001)
            with self.out:
                if (ticker % 10) == 0:
                    print(ticker, 'TEST')
        

        with self.out:
            if self._stopped:
                with self.out:
                    print('Thread was stopped')
            else:
                with self.out:
                    print('Thread completed')
        

app = Job()

t = threading.Thread(target=app.run)
app.display()
t.start()
```

**Comment by dakenblack** [comment]
Hi @ianhi ,
Thanks for your response, unfortunately I still get the same problems after copying your snippet. I've run it a few times and the result is different each time:
* sometimes it will print all the output but only after a significant delay
* sometimes it will only print part of the output

E.g.:
![2020-11-19_08h40_40](https://user-images.githubusercontent.com/11382198/99591496-003b6500-2a43-11eb-8ac3-784633c0393b.png)

**Comment by dakenblack** [comment]
To anyone finding this issue, I managed to fix my issue by using the Output panel's convenience method instead of using it as a context manager.

Use:
```
self.out.append_stdout(msg + '\n')
```

Instead of:
```
with self.out:
    print(msg)
```

I've also uploaded a fixed gist at https://gist.github.com/dakenblack/78c84cad6d834ff97161b2422168d0af.

Closing the issue now.

**Comment by jasongrout** [comment]
Related docs: https://ipywidgets.readthedocs.io/en/stable/examples/Output%20Widget.html#Interacting-with-output-widgets-from-background-threads
