### ISSUE TITLE
Tab widget shows content from all tabs

### ISSUE THREAD

**Issue by miduncan** [jupyter-widgets/ipywidgets#3028]
# Repro
Using the following code to create a tab widget. Note: Use a non-phosphor IDE to do this, such as nteract
```
import ipywidgets as widgets
tab_contents = ['P0', 'P1', 'P2', 'P3', 'P4']
children = [widgets.Text(description=name) for name in tab_contents]
tab = widgets.Tab()
tab.children = children
for i in range(len(children)):
    tab.set_title(i, str(i))
tab
```
We see that all of the tab content is shown, even if it is content that is expected to be hidden
![image](https://user-images.githubusercontent.com/55718965/100785938-3c1ce580-33c6-11eb-8067-5ee544785cae.png)

# Underlying issue
This underlying issue is that there is no CSS rule that applies to the `p-mod-hidden` CSS class that is being added to the tab content that shouldn't be shown. For IDEs that include the phosphor CSS, this doesn't repro because there is a global rule for all .p-mod-hidden to `display: none`

**Comment by jasongrout** [comment]
It is the frontend-specific widget manager's responsibility to make sure that this css is loaded. Can you file an issue with the specific widget manager or frontend where you are seeing this issue?

**Comment by jasongrout** [comment]
For example, if you are seeing this problem with nteract, please file an issue with nteract.

**Comment by jasongrout** [comment]
> This underlying issue is that there is no CSS rule that applies to the `p-mod-hidden` CSS class that is being added to the tab content that shouldn't be shown. For IDEs that include the phosphor CSS, this doesn't repro because there is a global rule for all .p-mod-hidden to `display: none`

And thanks for tracking down the underlying problem and posting a good comprehensive issue. That made it much easier to direct this issue to the people that can solve it.
