### ISSUE TITLE
Cannot import qgrid

### ISSUE THREAD

**Issue by bebbanburg** [jupyter-widgets/ipywidgets#3031]
I did a developer install of the latest ipywidgets because I wanted to get the border side styling methods, but now I have a problem using qgrid. When I try to import, I get this issue: 

--> 524 @widgets.register()
    525 class QgridWidget(widgets.DOMWidget):
    526     """
TypeError: register() missing 1 required positional argument: 'widget'

Any solutions to this?

**Comment by vidartf** [comment]
```diff
- @widgets.register()
+ @widgets.register
```
