### ISSUE TITLE
Bug reading my video

### ISSUE THREAD

**Issue by julienguegan** [jupyter-widgets/ipywidgets#3036]
Hello,

I am experiencing some difficulties to read one of my own video with `ipywidgets.Video.from_file(my_video)` . First, I had no problem reading a test video lasting 33 seconds and weighing 500ko but then when trying with my own video (6min30 and 1.5Go), my computer completely froze and I had no other choice than manually restart it (try it 2/3 times). Note that I can read the video easily with VLC or the default microsoft 10 player ...

**I wanted to know if someone has an idea from where this bug could come and how to resolve it ?**

**Comment by jasongrout** [comment]
Ipywidgets sends the entire file to your browser in Javascript, and that was likely too much for your browser to handle.

**Comment by jasongrout** [comment]
Closing as answered, but feel free to continue the discussion if you'd like to reopen and continue the discussion.
