### ISSUE TITLE
jupyterlab-manager: allow CORS?

### ISSUE THREAD

**Issue by jeanmonet** [jupyter-widgets/ipywidgets#3037]
### Problem

The following error message appears in my Firefox console:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at
https://registry.npmjs.org/-/v1/search?text=+keywords%3A%22jupyterlab-extension%22&size=250&from=0.
(Reason: CORS request did not succeed).
```

Unless mistaken this is related to the search functionality in the jupyterlab-manager extension.

Search doesn't work, because the request is blocked.

### Proposed Solution

Is there a `allow-same-origin` header that is missing somewhere?

### Additional context

Noticed that this issue solved a similar (but unrelated) problem: https://github.com/jupyterlab/jupyterlab/issues/7506

I am using version 2.0 of the extension.

**Comment by vidartf** [comment]
This seems unrelated to ipywidgets, and should probably be reopened on the jupyterlab repo.

**Comment by vidartf** [comment]
Put differently: I'm not aware of ipywidgets opening any requests to the npm registry, and i we are, that would come as a surprise to me.

**Comment by jeanmonet** [comment]
I have just checked again.

The Extension Manager widget on the left-most toolbar of the Jupyter Lab is a ipywidget? More speficifically [Jupyter Lab Manager](https://github.com/jupyter-widgets/ipywidgets/tree/master/packages/jupyterlab-manager)?

![image](https://user-images.githubusercontent.com/15112920/103809930-9f033b80-505a-11eb-92df-51b58944a958.png)

Literally as soon as I clicked on Enable (above screenshot taken after clicking Enable), the following showed up in the browser's console:

![image](https://user-images.githubusercontent.com/15112920/103809993-c0fcbe00-505a-11eb-9c8a-648867a4ad1e.png)

I assumed it is related to the fact that the widget looks up available extensions? On npm? I'm not familiar with the code so I don't really know how it works.

**Comment by vidartf** [comment]
> The Extension Manager widget on the left-most toolbar of the Jupyter Lab is a ipywidget? 

The extension manager is a jupyterlab component, not an ipywidget. It allows you to install the ipywidgets jupyterlab extension (among many others), but otherwise has no connection to ipywidgets. I hope this clears up the confusion 😃
