### ISSUE TITLE
7.6.0 release notes

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#3048]
We released ipywidgets 7.6.0 today.

It turns out that lerna isn't as able to bump rc versions of packages as I remember. In order to do the 7.6 release, I did:
```
./node_modules/.bin/lerna version patch --force-publish=@jupyter-widgets/example-web1,@jupyter-widgets/example-web2,@jupyter-widgets/example-web3,@jupyter-widgets/example-web4,@jupyter-widgets/jupyterlab-manager,@jupyter-widgets/base,@jupyter-widgets/controls,@jupyter-widgets/html-manager,@jupyter-widgets/output,@jupyter-widgets/notebook-manager -m "Publish npm packages" --no-push
./node_modules/.bin/lerna publish from-git
```
This bumped the versions of appropriate packages from rc to final releases and published them.

**Comment by jasongrout** [comment]
We should probably annotate the changelog with a note that widget extension authors wanting to support JupyterLab 3 should add the sharedPackages config that is in the cookiecutter now:

```json
  "jupyterlab": {
    "sharedPackages": {
      "@jupyter-widgets/base": {
        "bundled": false,
        "singleton": true
      }
    }
  }
```
as noted in the jupyterlab docs: https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#requiring-a-service

**Comment by willingc** [comment]
@jasongrout I'm a bit confused why stable has documentation for 7.6 but the latest docs do not. I just spent a bunch of time trying to find up-to-date release notes in `changelog.md` on main. It seems to only be on the `7.x` branch. Can you update me on what the dev process in this repo is now? Thanks!

**Comment by MSeal** [comment]
Related -- are there any additional changelog notes for non-jupyterlab users of widgets? We're having difficulty debugging issues with Output widgets in nteract and don't know if there's contract changes we should be aware of outside of the extension system.

**Comment by jasongrout** [comment]
> @jasongrout I'm a bit confused why stable has documentation for 7.6 but the latest docs do not. I just spent a bunch of time trying to find up-to-date release notes in `changelog.md` on main. It seems to only be on the `7.x` branch. Can you update me on what the dev process in this repo is now? Thanks!

Master is tracking development of the forthcoming ipywidgets 8.0, which has stalled for a long time. The active work on 7.x is going on the 7.x branch. It's an unfortunate bifurcation of the branches and development effort stemming from the 8.0 release stalling out, but still needing updates to the existing 7.x line.

We're setting up a meeting in the next few weeks to restart effort on ipywidgets 8, and one of the first items to do is to migrate changes (like the changelog entries!) from the 7.x branch to master.

**Comment by willingc** [comment]
@jasongrout Thanks. Can you make sure that @MSeal, @captainsafia, and I are made aware of the upcoming meeting? It's great to see progress being made. I do think that there is a fair amount of confusion currently for non-JupyterLab frontends or applications since there isn't a real clear chart on which npm packages have support for something and which can be used together. Any thoughts on how to pull this info together easily and keep it updated as widgets evolve?

**Comment by jasongrout** [comment]
> Related -- are there any additional changelog notes for non-jupyterlab users of widgets? We're having difficulty debugging issues with Output widgets in nteract and don't know if there's contract changes we should be aware of outside of the extension system.

The output widget interface has been really stable. Here is the list of commits from that package (notice it is the 7.x branch, not master): https://github.com/jupyter-widgets/ipywidgets/commits/7.x/packages/output

You can see we've just been publishing new versions as the underlying `@jupyter-widgets/base` library had version bumps.

**Comment by jasongrout** [comment]
> Any thoughts on how to pull this info together easily and keep it updated as widgets evolve?

That sounds like an excellent topic to discuss in the meeting!

**Comment by jasongrout** [comment]
8.0 release discussion is on https://github.com/jupyter-widgets/ipywidgets/issues/2750

The upcoming meeting doodle poll is noted at https://github.com/jupyter-widgets/ipywidgets/issues/2750#issuecomment-760452959

**Comment by jasongrout** [comment]
> We should probably annotate the changelog with a note that widget extension authors wanting to support JupyterLab 3 should add the `package.json` `sharedPackages` config that is in the jlab 3 widget cookiecutter now:

Following up on this: this is done in https://github.com/jupyter-widgets/ipywidgets/pull/3051

**Comment by willingc** [comment]
Thanks @jasongrout. I appreciate the response 👍🏼

**Comment by MSeal** [comment]
Seconded and the response. Thanks for engaging on those points

**Comment by jasongrout** [comment]
Great. Closing this issue as resolved, and we can continue conversation on the 8.0 issue. Thanks!
