### ISSUE TITLE
[Help required]: How to write unit tests for custom widgets

### ISSUE THREAD

**Issue by anant-k-singh** [jupyter-widgets/ipywidgets#3054]
I am creating a custom ipywidget and using pytest framework for unit testing.
I am able to mock the `ipykernel.comm` and use it as a `@pytest.fixture` and test the kernel sending the messages (i.e. traitlet changes).

Q: How do I simulate the frontend sending some message to kernel in this mock comm?
I want to test my callback methods in kernel side code when the frontend changes some state/traitlet of model.

**Comment by anant-k-singh** [comment]
@jasongrout Can you please provide suggestions or docs about how we can approach unit testing for this scenario

**Comment by martinRenou** [comment]
One approach I would like to try on my side for end to end testing is to use [robotframework-jupyterlibrary](https://github.com/robots-from-jupyter/robotframework-jupyterlibrary). This might be the best approach IMO to test widgets.

If you just want to test the Python code then your approach is good. 

> Q: How do I simulate the frontend sending some message to kernel in this mock comm?

I guess calling your callbacks directly with the needed messages is enough?

**Comment by maartenbreddels** [comment]
A side-project that sprung out of [solara](https://github.com/widgetti/solara/) is [pytest-ipywidgets](https://pypi.org/project/pytest-ipywidgets/), which allows you to test with or without a browser (playwright).

It's [documented on our solara website](https://solara.dev/documentation/advanced/howto/testing).

As basic example is:
```python
import ipywidgets as widgets
import playwright.sync_api
from IPython.display import display

def test_widget_button_solara(solara_test, page_session: playwright.sync_api.Page):
    # The test code runs in the same process as solara-server (which runs in a separate thread)
    # Note: this test uses ipywidgets directly, not solara components.
    button = widgets.Button(description="Click Me!")

    def change_description(obj):
        button.description = "Tested event"

    button.on_click(change_description)
    display(button)
    page_session.locator("text=Click Me!").click()
    page_session.locator("text=Tested event").wait_for()
```
