### ISSUE TITLE
How to get the width of output cell of Jupyter notebook?

### ISSUE THREAD

**Issue by anant-k-singh** [jupyter-widgets/ipywidgets#3055]
I am creating a custom widget (ipywidget) and I need to get the width of the output cell of Jupyter notebook. So that I can occupy maximum width with my widget.

Question: How can I get this width at runtime in my widget view?

**Comment by jasongrout** [comment]
One idea is to set your width to 100% to expand your widget using CSS. If you need pixel dimensions, do that and then measure your own width using javascript.

**Comment by anant-k-singh** [comment]
So, if I want to maintain a certain aspect ratio (ratio is not fixed beforehand) of my widget in the output cell, I should render it with `width: 100%` first and then set the height (as per ratio) in the next render?

**Comment by jasongrout** [comment]
bqplot does something like this: https://github.com/bqplot/bqplot/blob/0620195ad4191db7b5bffab2d36e76564d435e24/js/src/Figure.ts#L68-L85

**Comment by anant-k-singh** [comment]
Thanks @jasongrout,
I was able to get the width of output cell (in px) using `this.el.getBoundingClientRect()`, which returns the following object:

![image](https://user-images.githubusercontent.com/22440924/103625327-d5f52680-4f60-11eb-81be-07932dd88511.png)
