### ISSUE TITLE
Error while installing jupyter labextension install @jupyter-widgets/jupyterlab-manager

### ISSUE THREAD

**Issue by cmrncrick** [jupyter-widgets/ipywidgets#3066]
I keep on getting errors trying to install jupyter labextension. Below is the error log that I'm getting. I'd appreciate any insight. 

Node v15.3.0

Yarn configuration loaded.
> C:\Anaconda\anaconda3\npm.CMD pack @jupyter-widgets/jupyterlab-manager
npm notice 
npm notice package: @jupyter-widgets/jupyterlab-manager@3.0.0
npm notice === Tarball Contents === 
npm notice 14.5kB LICENSE             
npm notice 2.8kB  README.md           
npm notice 277B   lib/index.d.ts      
npm notice 380B   lib/index.js        
npm notice 5.9kB  lib/manager.d.ts    
npm notice 15.3kB lib/manager.js      
npm notice 1.9kB  lib/output.d.ts     
npm notice 5.3kB  lib/output.js       
npm notice 828B   lib/plugin.d.ts     
npm notice 7.8kB  lib/plugin.js       
npm notice 960B   lib/renderer.d.ts   
npm notice 3.3kB  lib/renderer.js     
npm notice 216B   lib/semvercache.d.ts
npm notice 862B   lib/semvercache.js  
npm notice 3.3kB  package.json        
npm notice 375B   schema/plugin.json  
npm notice === Tarball Details === 
npm notice name:          @jupyter-widgets/jupyterlab-manager          
npm notice version:       3.0.0                                        
npm notice filename:      @jupyter-widgets/jupyterlab-manager-3.0.0.tgz
npm notice package size:  15.6 kB                                      
npm notice unpacked size: 64.0 kB                                      
npm notice shasum:        fa47d03e2e72399ce3af4b86cc29aba2166d5781     
npm notice integrity:     sha512-9diAvsHHiK/kY[...]cKQSYU/tiXxdQ==     
npm notice total files:   16                                           
npm notice 
jupyter-widgets-jupyterlab-manager-3.0.0.tgz

Fetching URL: https://registry.yarnpkg.com/@jupyter-widgets%2Fjupyterlab-manager
> C:\Anaconda\anaconda3\npm.CMD pack @jupyter-widgets/jupyterlab-manager@2.0.0
npm notice 
npm notice package: @jupyter-widgets/jupyterlab-manager@2.0.0
npm notice === Tarball Contents === 
npm notice 1.5kB  LICENSE             
npm notice 2.1kB  README.md           
npm notice 277B   lib/index.d.ts      
npm notice 380B   lib/index.js        
npm notice 6.0kB  lib/manager.d.ts    
npm notice 15.3kB lib/manager.js      
npm notice 1.9kB  lib/output.d.ts     
npm notice 5.3kB  lib/output.js       
npm notice 828B   lib/plugin.d.ts     
npm notice 7.8kB  lib/plugin.js       
npm notice 960B   lib/renderer.d.ts   
npm notice 3.3kB  lib/renderer.js     
npm notice 216B   lib/semvercache.d.ts
npm notice 862B   lib/semvercache.js  
npm notice 2.3kB  package.json        
npm notice 375B   schema/plugin.json  
npm notice === Tarball Details === 
npm notice name:          @jupyter-widgets/jupyterlab-manager          
npm notice version:       2.0.0                                        
npm notice filename:      @jupyter-widgets/jupyterlab-manager-2.0.0.tgz
npm notice package size:  13.3 kB                                      
npm notice unpacked size: 49.4 kB                                      
npm notice shasum:        05ab402833df07aac1ec2c549a1d748b3c303185     
npm notice integrity:     sha512-i+qtbEe//W9Ru[...]Fu0KbkxM9aQXQ==     
npm notice total files:   16                                           
npm notice 
jupyter-widgets-jupyterlab-manager-2.0.0.tgz

Fetching URL: https://registry.yarnpkg.com/@jupyter-widgets%2Fjupyterlab-manager
> C:\Anaconda\anaconda3\npm.CMD pack @jupyter-widgets/jupyterlab-manager@2.0.0
npm notice 
npm notice package: @jupyter-widgets/jupyterlab-manager@2.0.0
npm notice === Tarball Contents === 
npm notice 1.5kB  LICENSE             
npm notice 2.1kB  README.md           
npm notice 277B   lib/index.d.ts      
npm notice 380B   lib/index.js        
npm notice 6.0kB  lib/manager.d.ts    
npm notice 15.3kB lib/manager.js      
npm notice 1.9kB  lib/output.d.ts     
npm notice 5.3kB  lib/output.js       
npm notice 828B   lib/plugin.d.ts     
npm notice 7.8kB  lib/plugin.js       
npm notice 960B   lib/renderer.d.ts   
npm notice 3.3kB  lib/renderer.js     
npm notice 216B   lib/semvercache.d.ts
npm notice 862B   lib/semvercache.js  
npm notice 2.3kB  package.json        
npm notice 375B   schema/plugin.json  
npm notice === Tarball Details === 
npm notice name:          @jupyter-widgets/jupyterlab-manager          
npm notice version:       2.0.0                                        
npm notice filename:      @jupyter-widgets/jupyterlab-manager-2.0.0.tgz
npm notice package size:  13.3 kB                                      
npm notice unpacked size: 49.4 kB                                      
npm notice shasum:        05ab402833df07aac1ec2c549a1d748b3c303185     
npm notice integrity:     sha512-i+qtbEe//W9Ru[...]Fu0KbkxM9aQXQ==     
npm notice total files:   16                                           
npm notice 
jupyter-widgets-jupyterlab-manager-2.0.0.tgz

Incompatible extension:
@jupyter-widgets/jupyterlab-manager
Found compatible version: 2.0.0
> C:\Anaconda\anaconda3\npm.CMD pack @jupyter-widgets/jupyterlab-manager@2.0.0
npm notice 
npm notice package: @jupyter-widgets/jupyterlab-manager@2.0.0
npm notice === Tarball Contents === 
npm notice 1.5kB  LICENSE             
npm notice 2.1kB  README.md           
npm notice 277B   lib/index.d.ts      
npm notice 380B   lib/index.js        
npm notice 6.0kB  lib/manager.d.ts    
npm notice 15.3kB lib/manager.js      
npm notice 1.9kB  lib/output.d.ts     
npm notice 5.3kB  lib/output.js       
npm notice 828B   lib/plugin.d.ts     
npm notice 7.8kB  lib/plugin.js       
npm notice 960B   lib/renderer.d.ts   
npm notice 3.3kB  lib/renderer.js     
npm notice 216B   lib/semvercache.d.ts
npm notice 862B   lib/semvercache.js  
npm notice 2.3kB  package.json        
npm notice 375B   schema/plugin.json  
npm notice === Tarball Details === 
npm notice name:          @jupyter-widgets/jupyterlab-manager          
npm notice version:       2.0.0                                        
npm notice filename:      @jupyter-widgets/jupyterlab-manager-2.0.0.tgz
npm notice package size:  13.3 kB                                      
npm notice unpacked size: 49.4 kB                                      
npm notice shasum:        05ab402833df07aac1ec2c549a1d748b3c303185     
npm notice integrity:     sha512-i+qtbEe//W9Ru[...]Fu0KbkxM9aQXQ==     
npm notice total files:   16                                           
npm notice 
jupyter-widgets-jupyterlab-manager-2.0.0.tgz

Node v15.3.0

Yarn configuration loaded.
Building jupyterlab assets (build:prod:minimize)
> node C:\Anaconda\anaconda3\lib\site-packages\jupyterlab\staging\yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @lumino/coreutils@1.5.3" has unmet peer dependency "crypto@1.0.1".
[5/5] Building fresh packages...
error C:\Anaconda\anaconda3\share\jupyter\lab\staging\node_modules\jupyter-matplotlib: Command failed.
Exit code: 1
Command: npm run build
Arguments: 
Directory: C:\Anaconda\anaconda3\share\jupyter\lab\staging\node_modules\jupyter-matplotlib
Output:
> jupyter-matplotlib@0.8.2 build
> webpack && npm run build:labextension

Hash: 0659dc8e03cbf5eaeb49b80fac93cd37f5fed1ea32955f3439476b78d7da
Version: webpack 4.44.1
Child
    Hash: 0659dc8e03cbf5eaeb49
    Time: 352ms
    Built at: 01/18/2021 6:06:39 PM
           Asset     Size  Chunks             Chunk Names
    extension.js  1.1 KiB       0  [emitted]  main
    Entrypoint main = extension.js
    [0] ./src/nb_extension.js 312 bytes {0} [built]
    
    WARNING in configuration
    The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
    You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/
Child
    Hash: b80fac93cd37f5fed1ea
    Time: 709ms
    Built at: 01/18/2021 6:06:39 PM
           Asset      Size  Chunks                   Chunk Names
        index.js  22.3 KiB       0  [emitted]        main
    index.js.map  66.6 KiB       0  [emitted] [dev]  main
    Entrypoint main = index.js index.js.map
    [0] ./package.json 1.85 KiB {0} [built]
    [1] external "@jupyter-widgets/base" 42 bytes {0} [built]
    [2] ./src/nb_index.js 612 bytes {0} [built]
    [3] ./src/utils.js 651 bytes {0} [built]
    [4] ./src/mpl_widget.css 446 bytes {0} [built]
    [5] ../css-loader/dist/cjs.js!./src/mpl_widget.css 759 bytes {0} [built]
    [6] ../css-loader/dist/runtime/api.js 2.61 KiB {0} [built]
    [7] ../style-loader/dist/runtime/injectStylesIntoStyleTag.js 6.75 KiB {0} [built]
    [8] ./src/index.js + 2 modules 26.9 KiB {0} [built]
        | ./src/index.js 184 bytes [built]
        | ./src/toolbar_widget.js 5.38 KiB [built]
        | ./src/mpl_widget.js 21.3 KiB [built]
    
    WARNING in configuration
    The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
    You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/
Child
    Hash: 32955f3439476b78d7da
    Time: 663ms
    Built at: 01/18/2021 6:06:39 PM
           Asset      Size  Chunks                   Chunk Names
        index.js  22.2 KiB       0  [emitted]        main
    index.js.map    66 KiB       0  [emitted] [dev]  main
    Entrypoint main = index.js index.js.map
    [0] ./package.json 1.85 KiB {0} [built]
    [1] external "@jupyter-widgets/base" 42 bytes {0} [built]
    [2] ./src/utils.js 651 bytes {0} [built]
    [3] ./src/mpl_widget.css 446 bytes {0} [built]
    [4] ../css-loader/dist/cjs.js!./src/mpl_widget.css 759 bytes {0} [built]
    [5] ../css-loader/dist/runtime/api.js 2.61 KiB {0} [built]
    [6] ../style-loader/dist/runtime/injectStylesIntoStyleTag.js 6.75 KiB {0} [built]
    [7] ./src/index.js + 2 modules 26.9 KiB {0} [built]
        | ./src/index.js 184 bytes [built]
        | ./src/toolbar_widget.js 5.38 KiB [built]
        | ./src/mpl_widget.js 21.3 KiB [built]
    
    WARNING in configuration
    The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
    You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

> jupyter-matplotlib@0.8.2 build:labextension
> jupyter labextension build .

Please supply at least one subcommand: check, disable, enable, install, link, list, uninstall, unlink, update
npm ERR! code 1
npm ERR! path C:\Anaconda\anaconda3\share\jupyter\lab\staging\node_modules\jupyter-matplotlib
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c jupyter labextension build .

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Cameron Crick\AppData\Local\npm-cache\_logs\2021-01-19T00_06_41_266Z-debug.log
npm ERR! code 1
npm ERR! path C:\Anaconda\anaconda3\share\jupyter\lab\staging\node_modules\jupyter-matplotlib
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c webpack && npm run build:labextension

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Cameron Crick\AppData\Local\npm-cache\_logs\2021-01-19T00_06_41_284Z-debug.log
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

npm dependencies failed to install
Traceback (most recent call last):

  File "C:\Anaconda\anaconda3\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "C:\Anaconda\anaconda3\lib\site-packages\jupyterlab\labextensions.py", line 104, in start
    build(clean_staging=self.should_clean,

  File "C:\Anaconda\anaconda3\lib\site-packages\jupyterlab\commands.py", line 459, in build
    return handler.build(name=name, version=version, static_url=static_url,

  File "C:\Anaconda\anaconda3\lib\site-packages\jupyterlab\commands.py", line 652, in build
    raise RuntimeError(msg)

RuntimeError: npm dependencies failed to install

Exiting application: jupyter

**Comment by alu96** [comment]
I have recently also got this error message when trying to install the `jupyter-matplotlib` labextension for `jupyterlab < 3` on Python `3.5.6`. My solution was to upgrade to Python `3.7` (`3.6` will probably also work) and install `jupyterlab==3`. In this case you don't have to run the `jupyter labextension install ...` command and installing the `ipympl` package is sufficient.

If you want to resolve this issue in your existing conda environment, I would suggest to follow the instructions [here](https://github.com/matplotlib/ipympl) and to install a specific version which you can look up in the table.

**Comment by jasongrout** [comment]
Closing as answered, since there was no followup from the original author. Thanks @alu96 for answering!
