### ISSUE TITLE
Question on contributing

### ISSUE THREAD

**Issue by CatChenal** [jupyter-widgets/ipywidgets#3069]
Is it possible to contribute to the project using a Windows10 OS?

**Comment by jasongrout** [comment]
Absolutely! I believe @vidartf uses Windows, for example.

**Comment by CatChenal** [comment]
Thanks for your prompt response!
I would love to contribute & close a 3-year-old open question, but how do I deal with this bash script: ` ./dev-install.sh`?

**Comment by jasongrout** [comment]
I think @vidartf doesn't use it. I'll let him comment.

**Comment by vidartf** [comment]
I just manually execute the bits in dev install whenever I need it. Just make sure to keep your dev environment around, and you won't have to do it too often :)

**Comment by CatChenal** [comment]
Thanks!

**Comment by vidartf** [comment]
Closing as answered then :)
