### ISSUE TITLE
Bug in developer docs or dev-install.sh

### ISSUE THREAD

**Issue by metasim** [jupyter-widgets/ipywidgets#3072]
I followed the instructions according to `dev_install.md`, and failed in the final steps.

<details>
<summary>Output from <code>./dev-install.sh</code>`</summary>
<pre>
...
Installing collected packages: parso, prompt-toolkit, jedi, backcall, toml, py, pluggy, ipython, iniconfig, pytest, coverage, pytest-cov, ipywidgets

  Attempting uninstall: prompt-toolkit
    Found existing installation: prompt-toolkit 1.0.15
    Uninstalling prompt-toolkit-1.0.15:
      Created temporary directory: /anaconda3/envs/ipywidgets/lib/python3.7/site-packages/~rompt_toolkit-1.0.15-py2.7.egg-info
      Removing file or directory /anaconda3/envs/ipywidgets/lib/python3.7/site-packages/prompt_toolkit-1.0.15-py2.7.egg-info
      Created temporary directory: /anaconda3/envs/ipywidgets/lib/python3.7/site-packages/~rompt_toolkit
      Removing file or directory /anaconda3/envs/ipywidgets/lib/python3.7/site-packages/prompt_toolkit/
      Successfully uninstalled prompt-toolkit-1.0.15

  Attempting uninstall: ipython
    Found existing installation: ipython 5.8.0
    Uninstalling ipython-5.8.0:
      Created temporary directory: /private/var/folders/lr/7lb0jzbj1x951n71lpcc2cy40000gn/T/pip-uninstall-xw4n0jbq
      Removing file or directory /anaconda3/envs/ipywidgets/bin/iptest
      Removing file or directory /anaconda3/envs/ipywidgets/bin/iptest3
      Removing file or directory /anaconda3/envs/ipywidgets/bin/ipython
      Removing file or directory /anaconda3/envs/ipywidgets/bin/ipython3
      Created temporary directory: /anaconda3/envs/ipywidgets/lib/python3.7/site-packages/~Python
      Removing file or directory /anaconda3/envs/ipywidgets/lib/python3.7/site-packages/IPython/
      Created temporary directory: /anaconda3/envs/ipywidgets/lib/python3.7/site-packages/~python-5.8.0.dist-info
      Removing file or directory /anaconda3/envs/ipywidgets/lib/python3.7/site-packages/ipython-5.8.0.dist-info/
      Created temporary directory: /private/var/folders/lr/7lb0jzbj1x951n71lpcc2cy40000gn/T/pip-uninstall-aipe51x5
      Removing file or directory /anaconda3/envs/ipywidgets/share/man/man1/ipython.1
      Successfully uninstalled ipython-5.8.0

  changing mode of /anaconda3/envs/ipywidgets/bin/iptest to 755
  changing mode of /anaconda3/envs/ipywidgets/bin/iptest3 to 755
  changing mode of /anaconda3/envs/ipywidgets/bin/ipython to 755
  changing mode of /anaconda3/envs/ipywidgets/bin/ipython3 to 755

  changing mode of /anaconda3/envs/ipywidgets/bin/py.test to 755
  changing mode of /anaconda3/envs/ipywidgets/bin/pytest to 755

  changing mode of /anaconda3/envs/ipywidgets/bin/coverage to 755
  changing mode of /anaconda3/envs/ipywidgets/bin/coverage-3.7 to 755
  changing mode of /anaconda3/envs/ipywidgets/bin/coverage3 to 755

  Running setup.py develop for ipywidgets
    Running command /anaconda3/envs/ipywidgets/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/some/path/ipywidgets/setup.py'"'"'; __file__='"'"'/some/path/ipywidgets/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
    running develop
    running egg_info
    creating ipywidgets.egg-info
    writing ipywidgets.egg-info/PKG-INFO
    writing dependency_links to ipywidgets.egg-info/dependency_links.txt
    writing requirements to ipywidgets.egg-info/requires.txt
    writing top-level names to ipywidgets.egg-info/top_level.txt
    writing manifest file 'ipywidgets.egg-info/SOURCES.txt'
    reading manifest file 'ipywidgets.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files found matching 'docs/#*'
    warning: no directories found matching 'ipywidgets/static'
    no previously-included directories found matching 'docs/build'
    no previously-included directories found matching 'docs/dist'
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '.git' found anywhere in distribution
    warning: no previously-included files matching '.ipynb_checkpoints' found anywhere in distribution
    warning: no previously-included files found matching 'scripts'
    writing manifest file 'ipywidgets.egg-info/SOURCES.txt'
    running build_ext
    Creating /anaconda3/envs/ipywidgets/lib/python3.7/site-packages/ipywidgets.egg-link (link to .)
    Adding ipywidgets 8.0.0a0 to easy-install.pth file

    Installed /some/path/ipywidgets
Successfully installed backcall-0.2.0 coverage-5.4 iniconfig-1.1.1 ipython-7.19.0 ipywidgets jedi-0.18.0 parso-0.8.1 pluggy-0.13.1 prompt-toolkit-3.0.14 py-1.10.0 pytest-6.2.2 pytest-cov-2.11.1 toml-0.10.2
Removed build tracker: '/private/var/folders/lr/7lb0jzbj1x951n71lpcc2cy40000gn/T/pip-req-tracker-w15qntwt'
Installing /some/path/ipywidgets/packages/base as a linked package because it does not have extension metadata:
   No `jupyterlab` key
Installing /some/path/ipywidgets/packages/base-manager as a linked package because it does not have extension metadata:
   No `jupyterlab` key
Installing /some/path/ipywidgets/packages/controls as a linked package because it does not have extension metadata:
   No `jupyterlab` key
Installing /some/path/ipywidgets/packages/output as a linked package because it does not have extension metadata:
   No `jupyterlab` key
An error occured.
ValueError:
"@jupyter-widgets/jupyterlab-manager@3.0.0-alpha.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab                        Extension      Package
>=3.0.3 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/application
>=3.0.3 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/logconsole
>=3.0.2 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/mainmenu
>=3.0.3 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/notebook
>=3.0.3 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/rendermime
>=3.0.2 <3.1.0                    >=2.0.1 <3.0.0 @jupyterlab/rendermime-interfaces
>=6.0.2 <6.1.0                    >=5.0.2 <6.0.0 @jupyterlab/services
>=3.0.1 <3.1.0                    >=2.0.1 <3.0.0 @jupyterlab/settingregistry
See the log file for details:  /var/folders/lr/7lb0jzbj1x951n71lpcc2cy40000gn/T/jupyterlab-debug-0dcn7xf1.log
</pre>
</details>

<details>
<summary>Contents of <code>jupyterlab-debug-0dcn7xf1.log</code></summary>
<details>
<pre>
Node v15.3.0

Yarn configuration loaded.
> /anaconda3/envs/ipywidgets/bin/npm pack /Users/sfitch/Coding/OSS/ipywidgets/packages/jupyterlab-manager
npm notice
npm notice 📦  @jupyter-widgets/jupyterlab-manager@3.0.0-alpha.0
npm notice === Tarball Contents ===
npm notice 1.3kB  README.md
npm notice 312B   lib/index.d.ts
npm notice 380B   lib/index.js
npm notice 6.9kB  lib/manager.d.ts
npm notice 17.7kB lib/manager.js
npm notice 2.0kB  lib/output.d.ts
npm notice 5.4kB  lib/output.js
npm notice 864B   lib/plugin.d.ts
npm notice 8.2kB  lib/plugin.js
npm notice 998B   lib/renderer.d.ts
npm notice 3.3kB  lib/renderer.js
npm notice 269B   lib/semvercache.d.ts
npm notice 917B   lib/semvercache.js
npm notice 2.3kB  package.json
npm notice 375B   schema/plugin.json
npm notice === Tarball Details ===
npm notice name:          @jupyter-widgets/jupyterlab-manager
npm notice version:       3.0.0-alpha.0
npm notice filename:      @jupyter-widgets/jupyterlab-manager-3.0.0-alpha.0.tgz
npm notice package size:  12.6 kB
npm notice unpacked size: 51.3 kB
npm notice shasum:        a57aa58e0cd5f281f406aaac7e16679c7771b8f4
npm notice integrity:     sha512-w8djz19vR9SeY[...]cnWXNB+JIWhAw==
npm notice total files:   15
npm notice
jupyter-widgets-jupyterlab-manager-3.0.0-alpha.0.tgz

Traceback (most recent call last):

  File "/anaconda3/envs/ipywidgets/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/anaconda3/envs/ipywidgets/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 127, in start
    ans = self.run_task()

  File "/anaconda3/envs/ipywidgets/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 178, in run_task
    for i, arg in enumerate(self.extra_args)

  File "/anaconda3/envs/ipywidgets/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 178, in <listcomp>
    for i, arg in enumerate(self.extra_args)

  File "/anaconda3/envs/ipywidgets/lib/python3.7/site-packages/jupyterlab/commands.py", line 392, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "/anaconda3/envs/ipywidgets/lib/python3.7/site-packages/jupyterlab/commands.py", line 614, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "/anaconda3/envs/ipywidgets/lib/python3.7/site-packages/jupyterlab/commands.py", line 1677, in _install_extension
    raise ValueError(msg)

ValueError:
"@jupyter-widgets/jupyterlab-manager@3.0.0-alpha.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab                        Extension      Package
>=3.0.3 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/application
>=3.0.3 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/logconsole
>=3.0.2 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/mainmenu
>=3.0.3 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/notebook
>=3.0.3 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/rendermime
>=3.0.2 <3.1.0                    >=2.0.1 <3.0.0 @jupyterlab/rendermime-interfaces
>=6.0.2 <6.1.0                    >=5.0.2 <6.0.0 @jupyterlab/services
>=3.0.1 <3.1.0                    >=2.0.1 <3.0.0 @jupyterlab/settingregistry

Exiting application: lab
</pre>
</details>

**Comment by jtpio** [comment]
Thanks @metasim.

It looks like this is related to JupyterLab 3.0 not being compatible on `master` yet.

For now installing JupyterLab 2 with `pip install jupyterlab~=2.0` or `conda install -c conda-forge jupyterlab=2` should help for the local dev setup.

There is also ongoing work to port the changes from the `7.x` branch to `master`, which should enable support for JupyterLab 3.0.

**Comment by jasongrout** [comment]
> There is also ongoing work to port the changes from the `7.x` branch to `master`, which should enable support for JupyterLab 3.0.

This is done in #3086. Let's consolidate the conversation over there. Thanks!
