### ISSUE TITLE
Documentation: Add developer docs for 8.x change for custom widgets

### ISSUE THREAD

**Issue by MSeal** [jupyter-widgets/ipywidgets#3078]
With 8.0 release we should capture what changes custom widget developers would need to make. Breaking change, new capabilities, and instructions for how to test widgets in different environments for 8.x would be a helpful breakdown. The goal should be to point people to issues / code changes that widget developers need to account for in upgrading widgets and to ensure there's visibility in the amount of work needed to make that improvement.

**Comment by MSeal** [comment]
@vidartf since I can't assign issues yet and I don't have the internal knowledge to write this myself :point_up:

**Comment by vidartf** [comment]
This should now be done in https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/migration_guides.md
