### ISSUE TITLE
Custom JS in HTML Widget

### ISSUE THREAD

**Issue by willprice** [jupyter-widgets/ipywidgets#3079]
Hi there,

I'm wondering whether it's possible to inject custom JS into the `HTML` widget? I want to add some client side interactivity to a visualization (auto scroll a very wide div when I click a button), but it seems just putting a `<script>` tag into the string that drives the `HTML` widget doesn't work (no console.log invocations make their way to the console). Is this something that is/isn't supported? And if it isn't supported, any suggested *quick* workarounds? I'm not keen on creating a custom component in this scenario.

Thanks for ipywidgets, it's a great tool for interactive data analysis :smile:

**Comment by raziqraif** [comment]
You can inject the JS code using IPython's HTML class. 

E.g.
```
import ipywidgets as ui
from IPython.core.display import display, HTML

# Use ipywidgets HTML for the widget
text = ui.HTML("<div id='my-id'> Hello world </div>")   
display(text)

# Use IPython's HTML for the script
my_script = HTML("""
    <script>
        widget = document.getElementById("my-id")
        console.log(widget)
    </script>
""")

display(my_script)
```

**Comment by eric-wieser** [comment]
Note that the cause of this is that assigning `innerHTML` does not run script tags. `innerHTML` is assigned here:

https://github.com/jupyter-widgets/ipywidgets/blob/f89c5d983d534fe3bbf8440f085e228ee89d681c/packages/controls/src/widget_string.ts#L208-L211


There are various suggestions on StackOverflow on how to work around this,
