### ISSUE TITLE
Realign RTD builds for 8.0 master branch and 7.x branch

### ISSUE THREAD

**Issue by willingc** [jupyter-widgets/ipywidgets#3093]
I've got RTD building both branches properly again on PR merge. The requirements.txt for master and 7.x environment.yml diverged somewhere along the road. Ideally, this should be the same file on both branches.

**Comment by ianhi** [comment]
The builds seems to be broken on master again :(

In https://github.com/jupyter-widgets/ipywidgets/pull/2919 it seems to have failed as the docs/requirement includes `ipyleaflet` which hold `ipywidgets<8`

https://readthedocs.org/projects/ipywidgets/builds/12956312/

https://github.com/jupyter-widgets/ipyleaflet/blob/e3c63cdfdc41f53d8e21788213015afe3e8f88c6/setup.py#L62

I think the short term solution may be to drop the ipyleaflet from the docs.

**Comment by willingc** [comment]
@ianhi Can you point out the exact examples that use ipyleaflet? I haven't yet made any changes to the requirements themselves. PR #3094 only changes the 7.x branch.

**Comment by jasongrout** [comment]
I ran into this the other day testing #3086. https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/examples/Layout%20Example.ipynb uses ipyleaflet.

**Comment by ianhi** [comment]
Given that the notebook isn't actually accessible by following links in the TOC (I could only find it by searching for `ipyleaflet` - xref https://github.com/jupyter-widgets/ipywidgets/issues/3097) and that it has line explaining how it depends on extra packages how about removing those packages from the doc/requirements?

**Comment by ianhi** [comment]
Indeed, removing only `ipyleaflet` from the requirements.txt fixes the build on master: https://github.com/jupyter-widgets/ipywidgets/pull/3098

**Comment by willingc** [comment]
@jasongrout I've merged @ianhi pr removing ipyleaflet. Removing from 7.x branch as well in #3094
