### ISSUE TITLE
Make docs home page friendlier

### ISSUE THREAD

**Issue by ianhi** [jupyter-widgets/ipywidgets#3096]
### Problem
Currently the landing page of the docs is not super inviting. https://ipywidgets.readthedocs.io/en/latest/index.html#
![image](https://user-images.githubusercontent.com/10111092/107139168-2dcbd800-68e7-11eb-8098-db398bd99063.png)

1. There is no explanatory or welcome text
2. The TOC in the sidebar is totally collapsed:
![image](https://user-images.githubusercontent.com/10111092/107139136-dc234d80-68e6-11eb-8c4c-fe6b56f7a6d5.png)

### Proposed Solution
1. Add some friendly opening text.
    - e.g. "Ipywidgets is a library that ...." - "If you want to learn ___ go to `<link>`, if you want to ___ go to `<link 2>`"
2. Add a gif of some awesome widget interactions
     - and/or add some active widgets to the 

### Additional Context:
Two widget libraries that could serve as inspiration:
https://ipycytoscape.readthedocs.io/en/latest/
https://ipycanvas.readthedocs.io/en/latest/

**Comment by willingc** [comment]
PR #3104 is a first pass at this task using the suggested projects as inspiration. Thanks @ianhi.
