### ISSUE TITLE
Interactive fails for non-zero decimal default argument

### ISSUE THREAD

**Issue by ianhi** [jupyter-widgets/ipywidgets#3102]
## Description
On master if you have a default argument that has a non-zero decimal then `interactive` will fail to generate a slider.
This appears to be a regression from the `7.x` branch.
![image](https://user-images.githubusercontent.com/10111092/107157262-24775580-6951-11eb-8157-7cbd03163c37.png)

## Reproduce

```python
from ipywidgets import interactive

# only a non-zero decimal will fail
def f(tau=1, beta=1.0,  zeta=1.5):
    print(beta, tau)
interactive(f)
```
<details><summary>Jupyter Log Console</summary>
<pre>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/mambaforge/envs/widgets-2/lib/python3.9/site-packages/traitlets/traitlets.py in validate(self, obj, value)
   2093         try:
-> 2094             value = float(value)
   2095         except Exception:

TypeError: float() argument must be a string or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

TraitError                                Traceback (most recent call last)
~/Documents/oss/jupyter/ipywidgets/ipywidgets/widgets/widget.py in _handle_msg(self, msg)
    628                 if 'buffer_paths' in data:
    629                     _put_buffers(state, data['buffer_paths'], msg['buffers'])
--> 630                 self.set_state(state)
    631 
    632         # Handle a state request.

~/Documents/oss/jupyter/ipywidgets/ipywidgets/widgets/widget.py in set_state(self, sync_data)
    512                     from_json = self.trait_metadata(name, 'from_json',
    513                                                     self._trait_from_json)
--> 514                     self.set_trait(name, from_json(sync_data[name], self))
    515 
    516     def send(self, content, buffers=None):

~/mambaforge/envs/widgets-2/lib/python3.9/site-packages/traitlets/traitlets.py in set_trait(self, name, value)
   1434                                 (cls.__name__, name))
   1435         else:
-> 1436             getattr(cls, name).set(self, value)
   1437 
   1438     @classmethod

~/mambaforge/envs/widgets-2/lib/python3.9/site-packages/traitlets/traitlets.py in set(self, obj, value)
    576 
    577     def set(self, obj, value):
--> 578         new_value = self._validate(obj, value)
    579         try:
    580             old_value = obj._trait_values[self.name]

~/mambaforge/envs/widgets-2/lib/python3.9/site-packages/traitlets/traitlets.py in _validate(self, obj, value)
    608             return value
    609         if hasattr(self, 'validate'):
--> 610             value = self.validate(obj, value)
    611         if obj._cross_validation_lock is False:
    612             value = self._cross_validate(obj, value)

~/mambaforge/envs/widgets-2/lib/python3.9/site-packages/traitlets/traitlets.py in validate(self, obj, value)
   2094             value = float(value)
   2095         except Exception:
-> 2096             self.error(obj, value)
   2097         return _validate_bounds(self, obj, value)
   2098 

~/mambaforge/envs/widgets-2/lib/python3.9/site-packages/traitlets/traitlets.py in error(self, obj, value, error, info)
    688                     e = "The '%s' trait expected %s, not %s." % (
    689                         self.name, self.info(), describe("the", value))
--> 690                 raise TraitError(e)
    691 
    692     def get_metadata(self, key, default=None):

TraitError: The 'value' trait of a FloatSlider instance expected a float, not the NoneType None.
</pre>
</details>

## Expected behavior

A working slider is generated

## Context

- ipywidgets version 8.0.0a0 21c2dc66cd3e0653729c17dfe76c5c20003bafe8

**Comment by davidbrochart** [comment]
Also, the initial values of the sliders are not the default values of the function's parameters. Is that expected?

**Comment by SylvainCorlay** [comment]
cc @ibdafna

**Comment by davidbrochart** [comment]
It's not specific to `interactive`, it also affects a `FloatSlider`:
```python
from ipywidgets import FloatSlider
FloatSlider(value=1.5, description='zeta', min=-1.5, max=4.5)
```

**Comment by ibdafna** [comment]
On it!

**Comment by davidbrochart** [comment]
For now I have no idea what's going on, so no problem if you want to look into it too :smile:

**Comment by davidbrochart** [comment]
I can see that here:
https://github.com/jupyter-widgets/ipywidgets/blob/c46e5dc306b7a908f749ede13392d8bdc5379821/packages/controls/src/widget_int.ts#L229
we have `values = [NaN]`. Where is this value set?

**Comment by ibdafna** [comment]
I've done some tests and this combination of parameters seems to fail noUiSlider at the source😱. You can see the issue here; open the console and try dragging the slider: the https://jsfiddle.net/itayd/aoL43yn8/2/

Removing the built-in format function does seem to solve the problem, but we rely on it for float precision...I'll need to dig deeper to find a suitable fix.

**Comment by davidbrochart** [comment]
It is because here:
https://github.com/jupyter-widgets/ipywidgets/blob/c46e5dc306b7a908f749ede13392d8bdc5379821/packages/controls/src/widget_int.ts#L217-L220
`from` receives a string and [should return a number](https://refreshless.com/nouislider/number-formatting). If you replace with the following it works fine:
```js
from: (value) => Number(value),
```
I'll open a PR.
