### ISSUE TITLE
Widget out of sync: fundamental issue?

### ISSUE THREAD

**Issue by maartenbreddels** [jupyter-widgets/ipywidgets#3111]
# Code 
```python
import ipywidgets as widgets
import time

text = widgets.Text(value="...", continuous_update=False)
def on_change(change):
    if text.value == "sleep":
        time.sleep(6)
        text.value = "I computed for 6 seconds"
text.observe(on_change, "value")
text
```

# Demo
![sync-bug](https://user-images.githubusercontent.com/1765949/107614361-71f20c00-6c4a-11eb-92c8-ee380abe434f.gif)

# What happens?
If we enter 'sleep', an update event is send to the kernel, which takes 6 seconds to finish. Before it finishes, we change the text to `"bug?"`, which is queued at the kernel, because the `time.sleep(6)` is still ongoing. Next, we send an update event from the kernel to the frontend, changing the Text value to `"I computed for 6 seconds"`, after which we process the queued message from the frontend which changes the kernel side value to `"bug?"`.

Now the frontend thinks the value is `"I computed for 6 seconds"` while the kernel thinks it is `"bug?"`

# What I think should happen
There must be a ton of literature written about keeping two systems in sync, but I think there should be an agreement of which side holds the ultimate source of truth. Since ipywidgets is mainly about programming from the kernel, I think that should be the kernel by default, and therefore I think the kernel should by default echo back the value to the frontend.

In this case, the `"bug?"` update message should be sent back to the frontend. The reason we don't do that, is that we implicitly assume the message (update to `"bug?"`) was generated AFTER the change to `"I computed for 6 seconds"` and therefore we assume that the frontend also has that value.

There are situations, like in ipywebrtc where the 'source of truth' is the frontend, since it generates the data (video stream), so there should be an opt-out way of echoing back changes.

# Context

This bug/feature was discovered by @mariobuikhuizen while trying to solve an infinite echo problem: https://github.com/spacetelescope/jdaviz/issues/185 🤷

**Comment by ellisonbg** [comment]
I think this directly relates to the ongoing work on JupyterLab to add a shared data model (often known as real-time collaboration) to JupyterLab (https://github.com/jupyterlab/jupyterlab/pull/10118). We are starting to use Yjs as a data model for notebooks and text files and it handles the synchronization of distributed state. Eventually, to make jupyter widgets work in a real-time collaboration context, we will have to dive into that - a side effect would be to address this issue as well.
