### ISSUE TITLE
The variable inspector freezes the jupyter notebook when loading large files in R

### ISSUE THREAD

**Issue by suzannejin** [jupyter-widgets/ipywidgets#3115]
The jupyter notebook freezes when I tried to store the data read from a large file (not really large though, it only has about 60MB and 1223199 rows) into a variable (when running R), The problem only happened when the variable inspector extension was enabled.

**Comment by jasongrout** [comment]
What variable inspection extension are you talking about?

**Comment by suzannejin** [comment]
Sorry, my mistake, I should have posted it in another place. I am gonna close the post.
