### ISSUE TITLE
Binder missing many dependencies

### ISSUE THREAD

**Issue by ianhi** [jupyter-widgets/ipywidgets#3116]
Many of the examples do not run on [binder](https://mybinder.org/v2/gh/jupyter-widgets/ipywidgets/master?filepath=docs%2Fsource%2Fexamples) as it missing key dependencies such as `numpy` and `matplotlib`

As far as I can tell there are no files in the repo that give binder any dependencies, it just uses setup.py to install ipywidgets 

The fix is to make a `.binder` directory, perhaps inspired by https://github.com/jupyterlab/jupyterlab-demo/tree/lab3

## Reproduce

Go to [binder](https://mybinder.org/v2/gh/jupyter-widgets/ipywidgets/master?filepath=docs%2Fsource%2Fexamples) and try to run the Lorenz example

**Comment by jtpio** [comment]
This might be fixed by https://github.com/jupyter-widgets/ipywidgets/pull/2701
