### ISSUE TITLE
Proposal for new Issue Labels

### ISSUE THREAD

**Issue by ianhi** [jupyter-widgets/ipywidgets#3161]
### Problem

There are often issues that arise for people who are making a custom ipywidget, however there is currently no way to label these issues as such. The only related label is `Custom widget idea`.

### Proposed Solution

Create a new label: `Custom Widget`. This could then be combined with existing labels such as `docs` or `bug` in order to increase expressiveness.

**Comment by jasongrout** [comment]
In the dev meeting, we all voted in favor of moving forward with this. Thanks!
