### ISSUE TITLE
Is it possible to know if the dropdown/combox is expanded?

### ISSUE THREAD

**Issue by yanghang2015** [jupyter-widgets/ipywidgets#3177]
Hi expert,

Is it possible to know if the dropdown/combox is expanded (the state that its options can be seen)? many thanks for your help.

**Comment by jasongrout** [comment]
No, I don't think the browser lets us know when it is using the datalist attribute to show a completion box.

Closing as answered, but feel free to follow up if you can find a way to do this and want to contribute it.

**Comment by yanghang2015** [comment]
Many thanks Jsaongrout for your quick response.  Is it possible to get events like onfocus/ onselect when the dropdown/combox is selected?  I asked this question because we need to change the options programmingly. If we are changing options programmingly when the user is changing selection, the dropdown will refresh and make user failed to change selection.  if we can get onfocus/onselect event, we may change options later when user is moving focus on other widgets.
