### ISSUE TITLE
More helpful semver range message

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#3178]
### Problem

When this error is shown at the console: https://github.com/jupyter-widgets/ipywidgets/blob/e0d41f6f02324596a282bc9e4650fd7ba63c0004/jupyterlab_widgets/src/manager.ts#L270
it would be helpful to know what versions of that module actually *are* registered in the frontend, instead of just seeing that the requested version is not registered.

### Proposed Solution

Add a method to the semver cache at https://github.com/jupyter-widgets/ipywidgets/blob/master/jupyterlab_widgets/src/semvercache.ts to list all available versions of a given key, i.e., could just return `Object.keys(this._cache[key])` or something like that (and would probably have to deal with the case where `key` was not in `this._cache`). Then add this list of available versions to the error message above.

**Comment by bsyouness** [comment]
I'll get started on this now! :)

**Comment by jtpio** [comment]
Thanks @bsyouness!

**Comment by vidartf** [comment]
Closed in #3185
