### ISSUE TITLE
Interactive widgets on nbviewer

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter-widgets/ipywidgets#318]
With all the work that is being done on the embedding of interactive widgets in other web applications than the notebook, the elephant in the room in my opinion is nbviewer.

To render "static" widgets on nbviewer, in addition to serving the javascript of `jupyter-js-widgets`, we will need to define the best way to store the widget state _in_ or _with_ the notebook file.

I think that it is a good time to start the discussion on how we can get there from a practical viewpoint.

**Comment by danielballan** [comment]
On the subject of on storing widget state with the notebook file, here is the "Widget History" demo I was showing at SciPy. It relies on [historydict](https://pypi.python.org/pypi/historydict) a dictionary that remembers the history of all its keys, backed by a sqlite file.

https://gist.github.com/anonymous/ca3a6ed4a2228d64c398

**Comment by MatsGustavsson** [comment]
Sylvain,
Do you know if there has been any progress on this topic? I would love to use nbviewer for this!

**Comment by jasongrout** [comment]
This was fixed in ipywigets 6.0

**Comment by rishabhmulani** [comment]
Hi everyone!
I've uploaded an ipython notebook which I'm trying to view through nbviewer. Please note that this notebook contains loads of interactive widgets (ipywidgets) and plots using bqplot and plotly. Neither these plots nor the ipywidgets show up in the nbviewer. 
Any solutions to this issue?

**Comment by jasongrout** [comment]
You need to save the widget notebook state to embed that state in the notebook: http://ipywidgets.readthedocs.io/en/latest/embedding.html#save-notebook-widget-state
