### ISSUE TITLE
Enable adding in custom workweek to DatePicker widget

### ISSUE THREAD

**Issue by info-rchitect** [jupyter-widgets/ipywidgets#3189]
### Problem

Many companies/organizations have custom work week calendars.  The `DatePicker` widget does not have a workweek indicator.

![image](https://user-images.githubusercontent.com/26782653/116454271-6b286d80-a825-11eb-8450-17e4fbff91df.png)

### Proposed Solution

Provide a way to configure the `DatePicker` widget to show custom workweeks as so:

![image](https://user-images.githubusercontent.com/26782653/116454421-9612c180-a825-11eb-818a-18b45607aa30.png)

Notice the workweeks displayed as integers (18-21) to the left of the calendar days in the image above.

**Comment by jasongrout** [comment]
Core ipywidgets uses the [browser datepicker control](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date), which does not support custom workweeks. Unfortunately, this request is thus out of scope for core ipywidgets.
