### ISSUE TITLE
Don't use `names=traitlets.All` in `observe`

### ISSUE THREAD

**Issue by ianhi** [jupyter-widgets/ipywidgets#3193]
### Problem

We use `observe` inherited from `traitlets.HasTraits`  which uses `names=traitlets.All` as a default argument. This can have confusing effects for anyone who wants to manually observe a widget. For example see https://github.com/jupyter-widgets/ipywidgets/issues/3192

My sense is that for most of the core widgets people really only want to observe the `value` trait so it's a bit unnecessary to always have to do `slider.observe(callback, names='value')` or to add an `if` statement to the callback.

### Proposed Solution

Override `observe` for the widget classes to give a default argument for names that is curated for the widget being used. So for example for an `IntSlider` we would change the default to be `value`.

----

Marking as `8.0` due to back incompat.

**Comment by jasongrout** [comment]
In our dev meeting today, we discussed this and think that probably it would be too big of a change? Do you have a nice elegant solution we could look at?

**Comment by vidartf** [comment]
Closing for now.
