### ISSUE TITLE
`observe` behaviour changes when in a loop

### ISSUE THREAD

**Issue by loichuder** [jupyter-widgets/ipywidgets#3196]
## Description

I try to `observe` several `IntSliders` with a parametrized callback (as mentioned in #1680):
```python
from ipywidgets import IntSlider, Output, VBox

sliders = [IntSlider(max=10), IntSlider(max=10)]

o = Output()
def print_val(change, index):
    with o:
        print(index, change.new)

for i in range(2):
    sliders[i].observe(lambda change: print_val(change, i), 'value')

VBox([*sliders, o])
```

I would expect that moving the first slider prints `0, <value of the first slider>` and moving the second slider prints `1, <value of the second slider>`

However, whatever the slider, I always get `1, <value of the moved slider>`. That is, all sliders are bound to the same parameter (in this case the last one `i=1`).
![image](https://user-images.githubusercontent.com/42204205/117275477-5fa8f800-ae5e-11eb-80dd-e1dc7bf43ae8.png)

Doing
```python
sliders[0].observe(lambda change: print_val(change, 0), 'value')
sliders[1].observe(lambda change: print_val(change, 1), 'value')
```
instead of looping leads to the expected behaviour so it appears the declaration in the loop is to blame.
![image](https://user-images.githubusercontent.com/42204205/117275678-91ba5a00-ae5e-11eb-8f72-1172a41f8756.png)

I tried many things (creating the `sliders` list in the same loop, doing `for i, slider in enumerate(sliders)`, ...) but as long as the `observe` is in the loop, I always have all sliders bound to `i=1`...

An idea about the source of this issue ? Perhaps I am not doing it the right way ?

## Context

- ipywidgets version 7.6.3
- Operating System and version: Ubuntu 20.04
- Browser and version: Firefox 88.0

The problem appears both in notebooks and JLab.

## Related issues

#1680 #3192

**Comment by ianhi** [comment]
I think that this is an issue with scopes and how lambda functions work with them. The same variable `i` is being reference in both lambda functions because it is in the global scope. What you've done is equivalent to this:

```python
fxns = []
for i in range(2):
    def f():
        print(i)
    fxns.append(f)
fxns[0]()
fxns[1]()
```
which will print out:
```python
1
1
```


So the solution is to either use `functools.partial` or to use a closure like this:

```python
from ipywidgets import IntSlider, Output, VBox

sliders = [IntSlider(max=10, description='0'), IntSlider(max=10, description='1')]

o = Output()
def make_print_val(index):
    def print_val(change):
        with o:
            print(index, change.new)
    return print_val

for i in range(2):
    sliders[i].observe(make_print_val(i), 'value')

VBox([*sliders, o])
```

**Comment by loichuder** [comment]
I see. Using a closure indeed did the trick !

Thanks for the explanation :slightly_smiling_face:
