### ISSUE TITLE
Button with HTML as description

### ISSUE THREAD

**Issue by ssfd7** [jupyter-widgets/ipywidgets#3204]
Currently Button is taking only string text as description.  

Use case:
- I need a button's description to have certain words in bold.  Example:  "Create **Control** Processes and **Implementation**"

When can this be implemented?

Thanks you,
Radu

**Comment by afonit** [comment]
This is not a solution - but wanted to give you a quick workaround,
The description accepts unicode - so you could use a site like [this](http://slothsoft.net/UnicodeMapper/?lang=en-us) to type some test in and put it in the description.

For example I typed `here is some ` then from the site I copied the bold for `bold text`, here is a screenshot of the result:
![image](https://user-images.githubusercontent.com/1798497/120649748-19d65400-c44b-11eb-9b0b-f7daf7eaf015.png)

**Comment by jasongrout** [comment]
I think using html in buttons may become possible with https://github.com/jupyter-widgets/ipywidgets/pull/2785 in the forthcoming ipywidgets 8.0.

**Comment by ssfd7** [comment]
Thank you Jason - I will wait for 8.0 - and hope it is done right.  A necessary feature nowadays...
