### ISSUE TITLE
'The 'index' trait of a SelectionSlider instance expected an int, not the float'

### ISSUE THREAD

**Issue by Jayvir29** [jupyter-widgets/ipywidgets#3221]
Dear ipywidgets devs,

While trying to use the SelectionSlider I came across a bug which has not yet been reported to my knowledge and which occurs when I enter at least 6 options in the slider and drag the selection to the 6th item. The error is as follows: 

![bug1](https://user-images.githubusercontent.com/78556039/122976346-87afd480-d394-11eb-96fa-b5898325635e.PNG)

I'm currently using the last version of Jupyter Notebook and the pre-release of Ipywidgets 8.0.0.a4. I used the following code :

```
import ipywidgets as widgets

widgets.SelectionSlider(
    options=['1','2','3','4','5','6','7'],
    description='n',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True)
```

I'm not sure if this is a bug or a handling error on my part. Am I the only one to have such an error in this case? I would appreciate any help, thanks in advance !

**Comment by alimanfoo** [comment]
Hi ipywidgets devs, I'm seeing the same error using `SelectionSlider` from ipywidgets 7.6.5 on google colab:

![image](https://user-images.githubusercontent.com/703554/155208203-a5c4d81c-51e9-464a-8ffa-46b2fef1dd3c.png)

I'm also seeing a bug with `IntSlider` which I'm guessing has a similar root cause, but slightly different pathology. E.g., when I create a widget with `ipywidgets.IntSlider(min=0, max=9, step=1)` then slide the slider from left to right, the values shown are 0, 1, 2, 2, 4, 5, 5, 7, 8, 9.

**Comment by jasongrout** [comment]
The original 8.0 issue should be solved with https://github.com/jupyter-widgets/ipywidgets/pull/3365

**Comment by jasongrout** [comment]
> Hi ipywidgets devs, I'm seeing the same error using `SelectionSlider` from ipywidgets 7.6.5 on google colab:

Can you replicate this in Jupyter Notebook or JupyterLab?

CC @blois

**Comment by alimanfoo** [comment]
Hi @jasongrout, thanks so much for looking at this. I cannot reproduce in Jupyter Notebook or Jupyter Lab, but I've managed to isolate this in colab to an interaction with ipyleaflet. The problems with the sliders only occur after installing and importing ipyleaflet. [Demo colab notebook here](https://colab.research.google.com/drive/1NFHdtLFhHEdG98Yw93T4yNVW3IOOLvQW?usp=sharing).

**Comment by jasongrout** [comment]
@blois, it seems that this issue only happens on colab?

**Comment by jasongrout** [comment]
For Colab issues like this one, please create an issue at https://github.com/googlecolab/colabtools.
