### ISSUE TITLE
Visual Regession Tests failing on CI

### ISSUE THREAD

**Issue by jtpio** [jupyter-widgets/ipywidgets#3226]
Following the merge of https://github.com/jupyter-widgets/ipywidgets/pull/2715, the visual regression tests appear to be failing on master:

https://github.com/jupyter-widgets/ipywidgets/runs/2951930516

**Comment by vidartf** [comment]
It seems like all of these failures are timeout errors. Are there any known things that would cause such timeouts to appear?

**Comment by vidartf** [comment]
Also, I see master is back on green now, should we close this then?

**Comment by jtpio** [comment]
Ah yes the timeout issues were fixed by updating galata in https://github.com/jupyter-widgets/ipywidgets/pull/2715.

Thanks for checking!
