### ISSUE TITLE
Writing into modal

### ISSUE THREAD

**Issue by jakublala** [jupyter-widgets/ipywidgets#3228]
Hello, I am trying to create a Jupyter Notebook ipywidgets for an app called Chemiscope. The app uses modals to display settings with input boxes. The user can type numbers inside these, but whenever one does that it changes the active cell into a markdown cell. I am not sure if this is a bug, or if there is a workaround. I believe it's because the modal element lives outside of the cell / output of the cell.

**Comment by jasongrout** [comment]
First, I'm not aware of any modals in ipywidgets core. It sounds like the problem should probably be filed with whatever library is providing modals? To me, it sounds like whatever (the modal?) is interpreting the keystrokes is perhaps not canceling the event, and maybe that keystroke event is being propagated and acted upon by the notebook?

**Comment by jakublala** [comment]
Hi, sorry for not replying earlier as this project was on a pause for a while.

Yes, so the modals are provided by Bootstrap that is loaded within the custom widget. I believe I will have to look into the documentation of Bootstrap and Jupyter Notebook, so it's not really an issue from your side. Thank you anyway for the answer though.

**Comment by jakublala** [comment]
FYI, if anyone is going to have problems with this, the issue was what was mentioend above by @jasongrout. Essentially stopping the propagation through the modal was all that was necessary.
