### ISSUE TITLE
tagsinput widget not visible

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#3230]
## Description

Currently on master, the tagsinput widget seems to be not visible in jupyterlab: 
![Screen Shot 2021-07-03 at 2 51 21 AM](https://user-images.githubusercontent.com/192614/124350453-b48c9480-dba9-11eb-80c2-9d196ff3abf8.png)

## Reproduce

1. Install dev ipywidgets using the dev-install script
2. Try to create a tagsinput widget and display it. Notice it does not show up. The DOM structure also seems off:
<img width="704" alt="Screen Shot 2021-07-03 at 2 53 44 AM" src="https://user-images.githubusercontent.com/192614/124350504-e7cf2380-dba9-11eb-8cf1-3ebe9539edfe.png">

## Expected behavior

See the tagsinput widget

## Context

- ipywidgets version: current master
- Operating System and version: macos catalina
- Browser and version: Firefox 89

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

No problems in the server log

No errors in the browser js console

### If using JupyterLab
- JupyterLab version: 3.0.16, with just ipywidgets dev installed

**Comment by ibdafna** [comment]
The issue seems to stem from the container `div` of `TagsInput`: https://github.com/jupyter-widgets/ipywidgets/blob/be470468f3aa4608c27091acf9b9963f517f513c/packages/controls/src/widget_tagsinput.ts#L104. Display is initially set to `none` and although focusing on the widget should change the display style to `inline-block`, it does not.

**Comment by jasongrout** [comment]
Tagsinput was added in https://github.com/jupyter-widgets/ipywidgets/pull/2591

**Comment by SylvainCorlay** [comment]
Cc @martinRenou

**Comment by martinRenou** [comment]
I'll have a look
