### ISSUE TITLE
Widgets do not render in static documentation

### ISSUE THREAD

**Issue by astrojuanlu** [jupyter-widgets/ipywidgets#3235]
### Problem

I was following [the ipywidgets tutorial](https://github.com/jupyter-widgets/tutorial) in preparation of SciPy US 2021 and, when told to go to https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Events.html to see the differences between `link` and `jslink`, saw that no widgets appeared at all. This is both in latest Firefox and Chromium on Linux Mint 20.2.

In both browsers with all extensions disabled I see a `process is not defined` error. Chromium:

```
Uncaught (in promise) ReferenceError: process is not defined
    at Object.7482 (embed-amd.js:8)
    at __webpack_require__ (embed-amd.js:14)
    at Object.62207 (embed-amd.js:8)
    at __webpack_require__ (embed-amd.js:14)
    at Object.37552 (embed-amd.js:8)
    at __webpack_require__ (embed-amd.js:14)
    at Object.57850 (embed-amd.js:8)
    at __webpack_require__ (embed-amd.js:14)
    at Object.25741 (embed-amd.js:8)
    at __webpack_require__ (embed-amd.js:14)
```

Firefox:

```
Uncaught (in promise) ReferenceError: process is not defined
    7482 https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@^0.21.0-alpha.0/dist/embed-amd.js:8
    __webpack_require__ https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@^0.21.0-alpha.0/dist/embed-amd.js:14
    62207 https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@^0.21.0-alpha.0/dist/embed-amd.js:8
    __webpack_require__ https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@^0.21.0-alpha.0/dist/embed-amd.js:14
    37552 https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@^0.21.0-alpha.0/dist/embed-amd.js:8
    __webpack_require__ https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@^0.21.0-alpha.0/dist/embed-amd.js:14
    57850 https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@^0.21.0-alpha.0/dist/embed-amd.js:8
    __webpack_require__ https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@^0.21.0-alpha.0/dist/embed-amd.js:14
    25741 https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@^0.21.0-alpha.0/dist/embed-amd.js:8
    __webpack_require__ https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@^0.21.0-alpha.0/dist/embed-amd.js:14
    45705 https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@^0.21.0-alpha.0/dist/embed-amd.js:8
    __webpack_require__ https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@^0.21.0-alpha.0/dist/embed-amd.js:14
    93920 https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@^0.21.0-alpha.0/dist/embed-amd.js:8
    __webpack_require__ https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@^0.21.0-alpha.0/dist/embed-amd.js:14
    <anonymous> https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@^0.21.0-alpha.0/dist/embed-amd.js:14
    <anonymous> https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@^0.21.0-alpha.0/dist/embed-amd.js:14
    <anonymous> https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@^0.21.0-alpha.0/dist/embed-amd.js:14
    execCb https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    check https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    enable https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    enable https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    enable https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    bind https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    each https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    enable https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    init https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
    o https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js:1
```

However, this seemed to work fine in the 7.6.3 docs, see https://ipywidgets.readthedocs.io/en/7.6.3/examples/Widget%20Events.html.

**Comment by astrojuanlu** [comment]
It looks like `7.6.3` was built with conda on a newer Sphinx version https://readthedocs.org/projects/ipywidgets/builds/12954552/
whereas `latest` was built with Sphinx 1.8 https://readthedocs.org/projects/ipywidgets/builds/14178439/.

The change was made in https://github.com/jupyter-widgets/ipywidgets/pull/2708 right after 7.6.3 was released, about one year and a half ago. However, that pull request looks fine: https://ipywidgets--2708.org.readthedocs.build/en/2708/examples/Widget%20Events.html

Doing a rough binary search, I think this broke somewhere between https://github.com/jupyter-widgets/ipywidgets/pull/3107 (February, good) and https://github.com/jupyter-widgets/ipywidgets/pull/3167 (March, bad).

**Comment by astrojuanlu** [comment]
I confirm that:

- The problem is not time-dependent, but code-dependent. In other words: rebuilding the 7.6.3 docs today doesn't exhibit the problem, there are no dependency issues.
- The problem can be reproduced locally. Therefore, it is not a Read the Docs issue.
- Doing a `git bisect` I identified eadb5efd as the first bad commit. No widgets are seen locally.
  - Its first parent, 60c88a59, looks good
  - Its second parent, 5532c91d, corresponds to ipywidgets 7.6.3 and shows the widgets, but there is a bug and they appear twice ([this can still be seen online](https://ipywidgets.readthedocs.io/en/7.6.3/examples/Widget%20Events.html#Linking-widgets-attributes-from-the-client-side))
  - ❓ 

That's how far I can go with my limited knowledge of ipywidgets.

**Comment by jasongrout** [comment]
Thanks for tracking this down! Adding it to the 8.0 milestone.

**Comment by martinRenou** [comment]
Assigning myself
