### ISSUE TITLE
Download button -> pdf instead of png?

### ISSUE THREAD

**Issue by srosenzweig09** [jupyter-widgets/ipywidgets#3254]
### Problem

I love the toolbar that accompanies figures, especially since I can click to save them directly to my local drive (I work remotely). Currently, the download button defaults to .png file type. I would love the option to set this button to download as .pdf file types. Is this possible? Thanks!

**Comment by martinRenou** [comment]
Is this for ipympl specifically? I see that you opened https://github.com/matplotlib/ipympl/issues/339 already. If this is only for ipympl, then please close this issue in ipywidgets :)

**Comment by srosenzweig09** [comment]
Hi, so I'm not sure, honestly. Here is the procedure:

```
%matplotlib widget
import Matplotlib.pyplot as plt

fig, ax = plt.subplots()
** plot something **
```

A figure appears with a toolbar, as shown here:

![Screen Shot 2021-08-17 at 11 23 15 AM](https://user-images.githubusercontent.com/52184535/129754424-ab2c585a-76e6-4b2b-9fa9-5d265f32f6d3.png)

Clicking on the "Save" button downloads to my local drive. I'm not sure whether this is an ipympl or matplotlib mechanism... I just figured I'd post to a couple of places and see if anyone has an answer.

**Comment by martinRenou** [comment]
This is more likely to be an issue related to ipympl, or maybe matplotlib. But I believe this is unrelated to ipywidgets.

I answered to the ipympl one, let's continue to chat there :)
