### ISSUE TITLE
Button Icons so Thick in Jupyter Lab

### ISSUE THREAD

**Issue by massgh** [jupyter-widgets/ipywidgets#3259]
When I see e.g. `fa-right-angle` and `fa-left-angle` icons in classic Notebook or VS Code, these look like this
![image](https://user-images.githubusercontent.com/48522862/131066593-db7893cb-120c-4446-a05f-0c8b10a479de.png)
But same thing is so fat in Jupyter Lab
![image](https://user-images.githubusercontent.com/48522862/131066743-1ed62119-9a66-4840-a9ab-9b582b7e4114.png)

I am just curious which one is modern version? I honestly prefer smart icons like in classic notebook

**Comment by jasongrout** [comment]
It looks like the upcoming Fontawesome 6 version is back to being thinner again:

https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=angle&s=solid&m=free

I presume that will get pulled into JupyterLab at some point after it is released.

**Comment by massgh** [comment]
That would be great. I was actually trying to fit something in button description with i tag but no luck. It would a great idea if button allows using custom i tag where one can modify it per their needs. I am building live content slides in notebook similar to the concept of reveal.js but connected to kernel 
https://github.com/massgh/ipyslides
so a consistent ui is important.
