### ISSUE TITLE
What is the real status on PR 1834 "support more styles to toggle buttons"?

### ISSUE THREAD

**Issue by sdbbs** [jupyter-widgets/ipywidgets#3268]
Hi all,

I am using ipywidgets as part of a Jupyter notebook installation on an Ubuntu 20.04 server.

I wanted to change the toggled and untoggled background button colors, and I had some trouble finding references for that, and finally I found:

https://github.com/jupyter-widgets/ipywidgets/issues/1719

https://github.com/jupyter-widgets/ipywidgets/pull/1834

The PR starts with:

> Introduce button_color and font_weight to ToggleButtons style

... and does end with a "Merged" label; but then, there is a final [comment](https://github.com/jupyter-widgets/ipywidgets/pull/1834#issuecomment-471973747):

>  Is this supposed to be merged in ipywidgets-7.4.2 (jupyterlab-v0.35.4)?

... and here is my repetition of this test:

```
$ python3
Python 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ipywidgets
>>> import ipywidgets.widgets
>>> ipywidgets.__version__
'7.6.4'
>>> import pprint
>>> pprint.pprint(ipywidgets.widgets.Button().style.keys)
['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'button_color',
 'font_weight']
>>> pprint.pprint(ipywidgets.widgets.ToggleButton().style.keys)
['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'description_width']
```

Unfortunately, a bot locked that issue, without anyone ever confirming, if `button_color` is expected to be a part of the styiling of ToggleButton. or not?

I just spent couple of hours trying to figure this out, and so far, `style={'button_color':'#BBB'}` hasn't worked for my `widgets.ToggleButton` - but could anyone please confirm explicitly, if `button_color` can be used for `widgets.ToggleButton` as the pull request 1834 implies, or not?

**Comment by jasongrout** [comment]
It should work in the latest 8.0 alpha, but will not work in version 7.x.

**Comment by jasongrout** [comment]
It looks like that PR only added the field to `ToggleButtons`, not to `ToggleButton` (note the `s` at the end). `ToggleButtons` are for selecting an option among several alternatives, while `ToggleButton` is for setting a value true or false.

The button_color attribute was reverted in https://github.com/jupyter-widgets/ipywidgets/pull/1854 before a release (7.1.0) since it conflicted with how we were using color to signify state, i.e., it was impossible to see the state of the ToggleButtons with that implementation.

As it is today, neither `ToggleButtons` nor `ToggleButton` (no `s`) have a way to color the button. PRs are certainly welcome, but would need to take into account that we use the color to tell the user the state of the widget (so we'd need some other way to convey the state of the widget).

**Comment by jasongrout** [comment]
Note that in either case, you can set the `button_style` attribute of the button itself to get some pre-defined styling, IIRC including color changes.

**Comment by sdbbs** [comment]
Many, many thanks for that, @jasongrout - I just wanted to say the update on the status is very much appreciated (I do not want to change the status of this issue from "answered", apologies if adding this comment changes that).

> It looks like that PR only added the field to `ToggleButtons`, not to `ToggleButton` (note the `s` at the end). `ToggleButtons` are for selecting an option among several alternatives, while `ToggleButton` is for setting a value true or false.

Excellent, thanks for emphasizing this distinction, I did not have it in mind at all!


> As it is today, neither `ToggleButtons` nor `ToggleButton` (no `s`) have a way to color the button with an arbitrary color.

Fantastic, thanks again - great to have this explicitly stated!

> 
> Note that in either case, you can set the `button_style` attribute of the widget itself to get some pre-defined colors.
>

Thanks, was not really aware of this either!

In any case, I'm happy with all this info, so this issue might as well be closed - as it suits your issue tracking procedures ...  
Thanks again!
