### ISSUE TITLE
Widget output with class name

### ISSUE THREAD

**Issue by wdmhouston** [jupyter-widgets/ipywidgets#3273]
I have the following code in a class

Class q:
    output = widgets.Output()

    @a.output.capture(clear_output=True)
        def _onClick(b):
            my_js = """
            console.log("click called");
            """
            display(Javascript(my_js))
            print('_onClickLayoutGrid call done')
            display(Javascript(my_js))

I got error:    NameError: name 'a' is not defined.
what is the right way to write the output capture with class name inside?

**Comment by jasongrout** [comment]
It's telling you the right error. You have `@a`, but have not defined a anywhere. Try `@output` instead.
