### ISSUE TITLE
gcp ai platform jupyterlab+ explainable-ai-sdk + witwidget  can not display what-if tools widget

### ISSUE THREAD

**Issue by fenglin-ssb** [jupyter-widgets/ipywidgets#3289]
## Description

i have come the step that the the following witwidget can be shown:
![image](https://user-images.githubusercontent.com/66443940/135273249-c7a613e5-8a62-4e8e-a982-7970f84200c6.png)
but the data is empty.

## Expected behavior

i expect the data can be loaded into the widget.

## Context

- ipywidgets version 
- Operating System and version:
- Browser and version:

Paste the output from your command line running `jupyter lab` (or `jupyter notebook` if you use notebook) here, use `--debug` if possible.

![image](https://user-images.githubusercontent.com/66443940/135272871-ee795c23-b87a-4d12-9ad5-1b14573418e7.png)
![image](https://user-images.githubusercontent.com/66443940/135272957-046ad944-7932-43fb-848e-60c83e13aba0.png)

### If using JupyterLab
- JupyterLab version:

<details><summary>Installed Labextensions</summary>
<pre>
Paste the output from your command line running `jupyter labextension list`.
[W 2021-09-29 12:56:47.989 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
JupyterLab v3.1.13
/opt/conda/share/jupyter/labextensions
        nbdime-jupyterlab v2.1.0 enabled OK
        jupyterlab-jupytext v1.3.5 enabled OK (python, jupytext)
        @jupyter-widgets/jupyterlab-manager v3.0.1 enabled OK (python, jupyterlab_widgets)
        @jupyterlab/server-proxy v3.1.0 enabled OK
        @jupyterlab/git v0.32.4 enabled OK (python, jupyterlab-git)

Other labextensions (built into JupyterLab)
   app dir: /opt/conda/share/jupyter/lab
        beatrix_jupyterlab v3.1.1 disabled OK
        jupyterlab-plotly v5.3.1 enabled OK
        plotlywidget v4.14.3 enabled OK
        wit-widget v1.8.0 enabled OK
        xai_image_widget v0.1.0 enabled OK
        xai_tabular_widget v0.1.0 enabled OK
</pre>
</details>

**Comment by martinRenou** [comment]
I wonder if this issue should go under https://github.com/pair-code/what-if-tool? It's not clear if it's an ipywidgets issue.

**Comment by fenglin-ssb** [comment]
thanks i created a issue under the link you provide.

**Comment by fenglin-ssb** [comment]
> I wonder if this issue should go under https://github.com/pair-code/what-if-tool? It's not clear if it's an ipywidgets issue.

can you help me to find some one to help?

**Comment by martinRenou** [comment]
They might be able to help you in the issue you created there https://github.com/PAIR-code/what-if-tool/issues/181
