### ISSUE TITLE
Widget not rendering on JupyterLab, when starting main.py examples/app and examples/notebook 

### ISSUE THREAD

**Issue by erkin98** [jupyter-widgets/ipywidgets#3299]
## Description

Widget not rendering on JupyterLab when running main.py examples/app and examples/notebook

## Reproduce

1. Go to root folder after cloning https://github.com/jupyterlab/jupyterlab
2. Build examples folder after installing and building all node modules
3. Go to examples/app, run python main,py , open notebook type and run

```
import ipywidgets as widgets
widgets.Button(description="Hello")
```
![Screenshot from 2021-10-16 18-17-29](https://user-images.githubusercontent.com/20378722/137677786-5178d609-b898-47c1-920f-b19d5d058dd2.png)

## Expected behavior

![Screenshot from 2021-10-16 16-33-05](https://user-images.githubusercontent.com/20378722/137677774-eeb88840-38e7-4567-97db-53c7cfadc37c.png)

## Context

- ipywidgets version: 7.6.5
- Operating System and version: Linux Ubuntu 20.04
- Browser and version: Chrome 94.0.4606.71
- Nodejs version: 14.17.4

<details><summary>Troubleshoot Output</summary>
<pre>

</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` (or `jupyter notebook` if you use notebook) here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Access to font at 'about:blank' from origin 'http://localhost:8888' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
about:blank:1 Failed to load resource: net::ERR_FAILED
3 default.js:1027 Exception opening new comm
_handleCommOpen @ default.js:1027
</pre>
</details>

### If using JupyterLab
- JupyterLab version: 3.1.18

<details><summary>Installed Labextensions</summary>
<pre>
JupyterLab v3.1.18
/home/erkin98/miniconda3/envs/appshell/share/jupyter/labextensions
        jupyter-leaflet v0.14.0 enabled OK
        @jupyter-widgets/jupyterlab-manager v3.0.1 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /home/erkin98/miniconda3/envs/appshell/share/jupyter/lab
        jupyterlab-plotly v5.3.1 enabled OK
        jupyterlab-system-monitor v0.7.0 enabled OK
        jupyterlab-topbar-extension v0.6.0 enabled OK
        plotlywidget v4.14.3 enabled OK</pre>
</details>

**Comment by vidartf** [comment]
The part in the browser output seems very relevant: 
```
default.js:1027 Exception opening new comm
_handleCommOpen @ default.js:1027
```

Unfortunately it seems cut off. Is there more to that output that you could include?

**Comment by jmk89** [comment]
Looks like I'm able to replicate the issue. Running node version 14.17.4

![image](https://user-images.githubusercontent.com/50560042/209383664-effe9e75-51f9-45e2-8fac-96136d80a94d.png)

These errors are coming from `webpack://jupyterlab/packages/services/lib/kernel/default.js`. 

![image](https://user-images.githubusercontent.com/50560042/209388305-079f3cc8-6da1-4698-b484-19b0c4cdaf11.png)

In particular, the `content.target_module` and `this._targetRegistry`. However, this doesn't seem like an ipywidgets issue, rather a JupyterLab issue. Should this be moved to jupyterlab repository?

**Comment by erkin98** [comment]
i resolved it by adding jupyterlab-manager to package.json
