### ISSUE TITLE
FileUpload widget: specify initial directory as a parameter

### ISSUE THREAD

**Issue by EricThomson** [jupyter-widgets/ipywidgets#3305]
### Problem
When using the `widgets.FileUpload()` widgets, I'd like to specify the starting directory that will open. On the workstations we use at work, directory trees can be particularly complex, so it would save a lot of time if I could add this as an argument. 

### Proposed Solution
It would be great if this could be specified as a parameter. E.g.:

`uploader = widgets.FileUpload(initial_directory="C:/foo", accept=".txt", multiple=False)`

the `initial_directory` parameter would say which directory would be opened first when looking for files. 

I have noticed that once I open a file using the widget, its parent directory is automatically opened first the next time I use the widget. So there is something being stored in memory, but I haven't found/figured out how to use that mechanism.

**Comment by EricThomson** [comment]
Searching around for similar issues, I did find this:

https://github.com/jupyter-widgets/ipywidgets/issues/2190

Which leads to this existing widget:

https://github.com/crahan/ipyfilechooser

I will check to see if it provides enough functionality for my purposes (it lets you select a file, and seems to allow for setting an initial default directory when searching the directory tree). I haven't tested it yet.

**Comment by jasongrout** [comment]
Thanks for bringing this up, and thanks for posting about your research in the area. It looks like ipyfilechooser is for selecting a file on the server, whereas the file widget in the base controls is for selecting a file on the browser's computer and uploading that to the kernel. Often the server and browser are the same computer, but often they aren't (like in a JupyterHub scenario), so these are really two different widgets with different focuses.

The file upload widget that comes with ipywidgets is based on the HTML input https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file. I don't see a way in there to give a default directory, and given that the base controls are scoped to (basically) what HTML elements provide, it doesn't look like it is possible to give a default directory.

(It did seem that there is an attribute in that input HTML element to take a picture with the camera. That would be an interesting core widget as well - to allow you to snap a picture and get the picture to the kernel as data.)
