### ISSUE TITLE
interactive_output does not update function

### ISSUE THREAD

**Issue by walksonair** [jupyter-widgets/ipywidgets#3319]
## Description

I'm new to using `interactive_output` but there may be a bug where the given function is not being displayed at all or called...even on the [official page](https://ipywidgets.readthedocs.io/en/latest/examples/Using%20Interact.html#More-control-over-the-user-interface:-interactive_output) when I move the sliders, the printed function does nothing to update!

## Reproduce

1. Go check out and move sliders for [https://ipywidgets.readthedocs.io/en/latest/examples/Using%20Interact.html#More-control-over-the-user-interface:-interactive_output](https://ipywidgets.readthedocs.io/en/latest/examples/Using%20Interact.html#More-control-over-the-user-interface:-interactive_output)
2. Notice no change from `(0, 0, 0)`

## Expected behavior

The output should change to whatever the sliders were moved to...

## Context

- ipywidgets version 7.6.5
- Operating System and version: Mac OS 12.0.1
- Browser and version: Safari Version 15.1 (17612.2.9.1.20)

**Comment by artus9033** [comment]
The issue is still present - is any work on fixing this ongoing?

**Comment by jasongrout** [comment]
The generated docs are not hooked up to a live kernel, so the widgets there are not going to update output. If you open the notebook in JupyterLab or Jupyter Notebook, connected to a live kernel, you should see it work properly.

**Comment by jasongrout** [comment]
Thoughts about making this more clear:

1. Include a note in the docs about not being hooked up to a live kernel, perhaps with a link to binder where people can explore the docs from a live session.
2. Maybe provide a link to a JupyterLite page, so the kernel is actually running in the web browser.
3. Perhaps we can hook up a JupyterLite kernel directly to the html widget manager to have live rendered HTML docs.
4.
