### ISSUE TITLE
How to set button width?

### ISSUE THREAD

**Issue by stefaneidelloth** [jupyter-widgets/ipywidgets#3333]
I create a button with

`button = widgets.Button(description='A long description that does not fit on a button with default width')    `

and the button is not large enough to show the full description.

![image](https://user-images.githubusercontent.com/12675339/147578111-4d5d1691-6f33-4136-97d2-cc111e9d38c2.png)

I tried to adapt its width with

`button.style.button_width = 500`

but that option does not seem to be supported.

=> How can I set the width of the button or make its width automatically adapt with its description?

**Comment by afonit** [comment]
@stefaneidelloth , I usually use the layout parameter, see below:

```python
import ipywidgets as widgets

widgets.Button(
    description='A long description that does not fit on a button with default width',
    layout=widgets.Layout(width='500px'),
)
```

screenshot:
![image](https://user-images.githubusercontent.com/1798497/150562174-0a3b25e1-6af1-4662-9158-61a44bc9e73d.png)
