### ISSUE TITLE
Ipywidget font-size property

### ISSUE THREAD

**Issue by itepifanio** [jupyter-widgets/ipywidgets#3347]
### Problem

* I'm trying to increase the font-awesome size on the button. 
* I would like to change the font-size of the button (it would also increase the font-awesome icon), but ipywidget does not have this property.
* Since I'm shipping ipywidget using nbdev the use of custom CSS class wouldn't be enought.

### Proposed Solution

* Add the font_size property to the button style, like `btn = ipywidget.Button(style=dict(font_size="18px"))`

**Comment by samwelborn** [comment]
in ipywidgets 8 you should be able to specify this.

**Comment by itepifanio** [comment]
Great @samwelborn thanks for the information!
