### ISSUE TITLE
Problem with Output widgets using Plotly

### ISSUE THREAD

**Issue by cmartinotti** [jupyter-widgets/ipywidgets#3349]
##Description
I'm using JupyterNotebook to create little applications through Ipywidgets.
When running the code :
```
##CELL1##
import plotly.express as px
import pandas as pd
import ipywidgets as widgets

out=widgets.Output()
dfa=pd.DataFrame({'x':[1,2,3],'y':[1,2,3]})


with out:
    out.clear_output(wait=True)
    print('ciao')
    fig=px.scatter(dfa,x='x',y='y', width=800, height=400 )
    fig.show()

out
```
I expect the output widget to capture the fig.show() output, but I instead get the print output followed by an empty area.
The weirdest thing is that I used similar code multiple times in the past to craft interactive applications and they are actually still working. The weirderst thing is that if I run CELL 1 i get an empty output, but then if I run CELL2:
```
#CELL 2 
with out:
    out.clear_output(wait=True)
    print('ciao')
    fig=px.scatter(dfa,x='x',y='y', width=800, height=400 )
    fig.show()

out
```
The output of CELL2 is still empty, but the output from CELL1 updates to what should have been the output of CELL2.

Furthermore this seems to be a problem that affects different users differently, in fact running CELL1 I have been already told that:
a) it works on JupyterLab but not on JupyterNotebook (for me it works in neither)
b) it can be solved adding fig.show(renderer='notebook') (doesn't work for me either)

## Context
- ipywidgets version (7, 6, 3, 'final', 0)
- Operating System and version: Windows 10
- Browser and version: Chrome Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by jasongrout** [comment]
First, there is likely a race condition here the way you are using clear_output. If you are inside the context manager, please use the normal IPython.display `clear_output` function. If you are outside the context manager, you can use the `out.clear_output` to clear that specific output:

```python
from IPython.display import clear_output
with out:
    clear_output(wait=True)
    ...
```

This is documented in the docs at https://ipywidgets.readthedocs.io/en/latest/examples/Output%20Widget.html, but perhaps it can be made clearer?

> We can clear the output by either using IPython.display.clear_output within the context manager, or we can call the widget’s clear_output method directly.
