### ISSUE TITLE
Transition from Phosphor CSS class names to Lumino names

### ISSUE THREAD

**Issue by vidartf** [jupyter-widgets/ipywidgets#3357]
In the "controls" JS package's CSS we still have references to PhosphorJS CSS class names:

https://github.com/jupyter-widgets/ipywidgets/blob/1b1a49d39efb24d24422516d2730c73dfdec9d84/packages/controls/css/widgets-base.css#L1289-L1291

Mostly this seems to be `.p-Tabbar` related or `.p-mod`. By the time that JupyterLab chooses to drop the deprecated phosphor classes, we will need to update our CSS to either support both names, or to only support the Lumino class names.

**Comment by jasongrout** [comment]
Some of those classes are our classes that we add:
https://github.com/jupyter-widgets/ipywidgets/blob/1b1a49d39efb24d24422516d2730c73dfdec9d84/packages/controls/src/lumino/tabpanel.ts#L114
https://github.com/jupyter-widgets/ipywidgets/blob/1b1a49d39efb24d24422516d2730c73dfdec9d84/packages/controls/src/lumino/tabpanel.ts#L118
https://github.com/jupyter-widgets/ipywidgets/blob/1b1a49d39efb24d24422516d2730c73dfdec9d84/packages/controls/src/lumino/tabpanel.ts#L120

I agree that this is confusing and should be switched over to either lm-based classes or perhaps our own prefix.
