### ISSUE TITLE
ComboBox reset value

### ISSUE THREAD

**Issue by paoloalba** [jupyter-widgets/ipywidgets#3362]
After selecting a value from the combobox, I can not successfully clear the field value from the GUI.
This means that if I have a background process which depends on the value of the combobox, after selecting a specific value, the background will always see such value until I do not assign another one to it, that is not an empty string.

Is this a desired behaviour? I am using ipywidgets==8.0.0b1 on Chrome with jupyter lab Version 3.2.8

**Comment by jasongrout** [comment]
A combobox is just a text box with a dropdown. With its default settings, you can just delete the text of the box. With ensure_option set to True, you'd need to assign a specific option that meant "no selection".
