### ISSUE TITLE
SelectionSlider missing options, returns TraitError

### ISSUE THREAD

**Issue by chaedri** [jupyter-widgets/ipywidgets#3363]
## Description

The SelectionSlider widget occasionally fails to display options from a list. Opening the notebook log shows a TraitError.

![Screenshot](https://user-images.githubusercontent.com/69856275/151834856-fb36f04f-a978-48be-a05c-c87d4d3bf5b0.png)

## Reproduce

1. Open Widget List on Binder: 
     https://mybinder.org/v2/gh/jupyter-widgets/ipywidgets/8.0.0b1?urlpath=lab/tree/docs/source/examples/Widget%20List.ipynb
2. Run Notebook and scroll down to SelectionSlider Section
3. Add new cell and paste:
```
options_list = ["2010_01",
                "2010_02",
                "2010_03",
                "2010_04",
                "2010_05",
                "2010_06",
                "2010_07",
                "2010_08",
                "2010_09",
                "2010_10",
                "2010_11",
                "2010_12"]

widgets.SelectionSlider(
    options=options_list,
    value=options_list[0],
    description='I like my eggs ...',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True
)
```

4. Move the slider through options. Some of the options don't appear.
5. Open the Notebook Log (from bottom of browser window) and see error:
```
---------------------------------------------------------------------------
TraitError                                Traceback (most recent call last)
~/python/ipywidgets/ipywidgets/widgets/widget.py in _handle_msg(self, msg)
    676                 if 'buffer_paths' in data:
    677                     _put_buffers(state, data['buffer_paths'], msg['buffers'])
--> 678                 self.set_state(state)
    679 
    680         # Handle a state request.

~/python/ipywidgets/ipywidgets/widgets/widget.py in set_state(self, sync_data)
    558                     from_json = self.trait_metadata(name, 'from_json',
    559                                                     self._trait_from_json)
--> 560                     self.set_trait(name, from_json(sync_data[name], self))
    561 
    562     def send(self, content, buffers=None):

/srv/conda/envs/notebook/lib/python3.7/site-packages/traitlets/traitlets.py in set_trait(self, name, value)
   1436                                 (cls.__name__, name))
   1437         else:
-> 1438             getattr(cls, name).set(self, value)
   1439 
   1440     @classmethod

/srv/conda/envs/notebook/lib/python3.7/site-packages/traitlets/traitlets.py in set(self, obj, value)
    578 
    579     def set(self, obj, value):
--> 580         new_value = self._validate(obj, value)
    581         try:
    582             old_value = obj._trait_values[self.name]

/srv/conda/envs/notebook/lib/python3.7/site-packages/traitlets/traitlets.py in _validate(self, obj, value)
    610             return value
    611         if hasattr(self, 'validate'):
--> 612             value = self.validate(obj, value)
    613         if obj._cross_validation_lock is False:
    614             value = self._cross_validate(obj, value)

/srv/conda/envs/notebook/lib/python3.7/site-packages/traitlets/traitlets.py in validate(self, obj, value)
   2044     def validate(self, obj, value):
   2045         if not isinstance(value, int):
-> 2046             self.error(obj, value)
   2047         return _validate_bounds(self, obj, value)
   2048 

/srv/conda/envs/notebook/lib/python3.7/site-packages/traitlets/traitlets.py in error(self, obj, value, error, info)
    690                     e = "The '%s' trait expected %s, not %s." % (
    691                         self.name, self.info(), describe("the", value))
--> 692                 raise TraitError(e)
    693 
    694     def get_metadata(self, key, default=None):

TraitError: The 'index' trait of a SelectionSlider instance expected an int, not the float 2.0000000000000004.
```

## Expected behavior
All options from list should appear along SelectionSlider without error messages in notebook log.

## Context

- ipywidgets version: 8.0.0b1
- Operating System and version: Binder
- Browser and version: Chrome

<details><summary>Troubleshoot Output</summary>
<pre>
jovyan@jupyter-jupyter-2dwidgets-2dipywidgets-2d5qvmhurh:~$ jupyter troubleshoot
$PATH:
        /srv/conda/envs/notebook/bin
        /srv/conda/condabin
        /home/jovyan/.local/bin
        /home/jovyan/.local/bin
        /srv/conda/envs/notebook/bin
        /srv/conda/bin
        /srv/npm/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin

sys.path:
        /srv/conda/envs/notebook/bin
        /srv/conda/envs/notebook/lib/python37.zip
        /srv/conda/envs/notebook/lib/python3.7
        /srv/conda/envs/notebook/lib/python3.7/lib-dynload
        /srv/conda/envs/notebook/lib/python3.7/site-packages
        /home/jovyan/python/widgetsnbextension
        /home/jovyan/python/ipywidgets
        /home/jovyan/python/jupyterlab_widgets

sys.executable:
        /srv/conda/envs/notebook/bin/python

sys.version:
        3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:53) 
        [GCC 9.4.0]

platform.platform():
        Linux-5.4.129+-x86_64-with-debian-buster-sid

which -a jupyter:
        /srv/conda/envs/notebook/bin/jupyter
        /srv/conda/envs/notebook/bin/jupyter

pip list:
        Package                       Version   Editable project location
        ----------------------------- --------- --------------------------------------
        alembic                       1.7.5
        anyio                         3.3.4
        argcomplete                   1.12.3
        argon2-cffi                   21.1.0
        async-generator               1.10
        attrs                         21.2.0
        Babel                         2.9.1
        backcall                      0.2.0
        backports.functools-lru-cache 1.6.4
        bleach                        4.1.0
        blinker                       1.4
        bqplot                        0.12.31
        brotlipy                      0.7.0
        certifi                       2021.10.8
        certipy                       0.1.3
        cffi                          1.15.0
        chardet                       4.0.0
        charset-normalizer            2.0.0
        coverage                      6.2
        cryptography                  35.0.0
        cycler                        0.11.0
        debugpy                       1.5.1
        decorator                     5.1.0
        defusedxml                    0.7.1
        deprecation                   2.1.0
        entrypoints                   0.3
        fonttools                     4.28.5
        greenlet                      1.1.2
        idna                          3.1
        imageio                       2.13.5
        importlib-metadata            4.8.2
        importlib-resources           5.4.0
        iniconfig                     1.1.1
        ipykernel                     6.5.0
        ipyleaflet                    0.15.0
        ipython                       7.29.0
        ipython-genutils              0.2.0
        ipywidgets                    8.0.0b1   /home/jovyan/python/ipywidgets
        jedi                          0.18.1
        Jinja2                        3.0.3
        joblib                        1.1.0
        json5                         0.9.5
        jsonschema                    4.2.1
        jupyter-client                7.0.6
        jupyter-core                  4.9.1
        jupyter-offlinenotebook       0.2.1
        jupyter-packaging             0.11.1
        jupyter-resource-usage        0.6.0
        jupyter-server                1.11.2
        jupyter-telemetry             0.1.0
        jupyterhub                    1.4.2
        jupyterlab                    3.1.17
        jupyterlab-pygments           0.1.2
        jupyterlab-server             2.8.2
        jupyterlab-widgets            2.0.0b1   /home/jovyan/python/jupyterlab_widgets
        kiwisolver                    1.3.2
        Mako                          1.1.6
        MarkupSafe                    2.0.1
        matplotlib                    3.5.1
        matplotlib-inline             0.1.3
        mistune                       0.8.4
        mpmath                        1.2.1
        nbclassic                     0.3.4
        nbclient                      0.5.9
        nbconvert                     6.0.7
        nbformat                      5.1.3
        nest-asyncio                  1.5.1
        networkx                      2.6.3
        notebook                      6.3.0
        nteract-on-jupyter            2.1.3
        numpy                         1.21.5
        oauthlib                      3.1.1
        packaging                     21.3
        pamela                        1.0.0
        pandas                        1.3.5
        pandocfilters                 1.5.0
        parso                         0.8.2
        pexpect                       4.8.0
        pickleshare                   0.7.5
        Pillow                        8.4.0
        pip                           21.3.1
        pluggy                        1.0.0
        prometheus-client             0.12.0
        prompt-toolkit                3.0.22
        psutil                        5.8.0
        ptyprocess                    0.7.0
        py                            1.11.0
        pycparser                     2.21
        pycurl                        7.44.1
        Pygments                      2.10.0
        PyJWT                         2.3.0
        pyOpenSSL                     21.0.0
        pyparsing                     3.0.6
        pyrsistent                    0.18.0
        PySocks                       1.7.1
        pytest                        6.2.5
        pytest-cov                    3.0.0
        python-dateutil               2.8.2
        python-json-logger            2.0.1
        pytz                          2021.3
        PyWavelets                    1.2.0
        pyzmq                         22.3.0
        requests                      2.26.0
        ruamel.yaml                   0.17.17
        ruamel.yaml.clib              0.2.6
        scikit-image                  0.19.1
        scikit-learn                  1.0.1
        scipy                         1.7.3
        Send2Trash                    1.8.0
        setuptools                    59.1.1
        six                           1.16.0
        sniffio                       1.2.0
        SQLAlchemy                    1.4.27
        sympy                         1.9
        terminado                     0.12.1
        testpath                      0.5.0
        threadpoolctl                 3.0.0
        tifffile                      2021.11.2
        toml                          0.10.2
        tomli                         2.0.0
        tomlkit                       0.8.0
        tornado                       6.1
        traitlets                     5.1.1
        traittypes                    0.2.1
        typing_extensions             4.0.0
        urllib3                       1.26.7
        wcwidth                       0.2.5
        webencodings                  0.5.1
        websocket-client              1.2.1
        wheel                         0.37.0
        widgetsnbextension            4.0.0b1   /home/jovyan/python/widgetsnbextension
        xyzservices                   2021.11.0
        zipp                          3.6.0

conda list:
        # packages in environment at /srv/conda/envs/notebook:
        #
        # Name                    Version                   Build  Channel
        _libgcc_mutex             0.1                 conda_forge    conda-forge
        _openmp_mutex             4.5                       1_gnu    conda-forge
        alembic                   1.7.5              pyhd8ed1ab_0    conda-forge
        anyio                     3.3.4            py37h89c1867_1    conda-forge
        argcomplete               1.12.3             pyhd8ed1ab_2    conda-forge
        argon2-cffi               21.1.0           py37h5e8e339_2    conda-forge
        async_generator           1.10                       py_0    conda-forge
        attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
        babel                     2.9.1              pyh44b312d_0    conda-forge
        backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
        backports                 1.0                        py_2    conda-forge
        backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
        bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
        blinker                   1.4                        py_1    conda-forge
        bqplot                    0.12.31                  pypi_0    pypi
        brotlipy                  0.7.0           py37h5e8e339_1003    conda-forge
        c-ares                    1.18.1               h7f98852_0    conda-forge
        ca-certificates           2021.10.8            ha878542_0    conda-forge
        certifi                   2021.10.8        py37h89c1867_1    conda-forge
        certipy                   0.1.3                      py_0    conda-forge
        cffi                      1.15.0           py37h036bc23_0    conda-forge
        chardet                   4.0.0            py37h89c1867_2    conda-forge
        charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
        coverage                  6.2                      pypi_0    pypi
        cryptography              35.0.0           py37hf1a17b8_2    conda-forge
        cycler                    0.11.0                   pypi_0    pypi
        debugpy                   1.5.1            py37hcd2ae1e_0    conda-forge
        decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
        defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
        deprecation               2.1.0                    pypi_0    pypi
        entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
        fonttools                 4.28.5                   pypi_0    pypi
        greenlet                  1.1.2            py37hcd2ae1e_1    conda-forge
        icu                       68.2                 h9c3ff4c_0    conda-forge
        idna                      3.1                pyhd3deb0d_0    conda-forge
        imageio                   2.13.5                   pypi_0    pypi
        importlib-metadata        4.8.2            py37h89c1867_0    conda-forge
        importlib_metadata        4.8.2                hd8ed1ab_0    conda-forge
        importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
        iniconfig                 1.1.1                    pypi_0    pypi
        ipykernel                 6.5.0            py37h6531663_1    conda-forge
        ipyleaflet                0.15.0                   pypi_0    pypi
        ipython                   7.29.0           py37h6531663_2    conda-forge
        ipython_genutils          0.2.0                      py_1    conda-forge
        ipywidgets                8.0.0b1                   dev_0    <develop>
        jedi                      0.18.1           py37h89c1867_0    conda-forge
        jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
        joblib                    1.1.0                    pypi_0    pypi
        json5                     0.9.5              pyh9f0ad1d_0    conda-forge
        jsonschema                4.2.1              pyhd8ed1ab_0    conda-forge
        jupyter-offlinenotebook   0.2.1              pyhd8ed1ab_0    conda-forge
        jupyter-packaging         0.11.1                   pypi_0    pypi
        jupyter-resource-usage    0.6.0              pyhd8ed1ab_0    conda-forge
        jupyter_client            7.0.6              pyhd8ed1ab_0    conda-forge
        jupyter_core              4.9.1            py37h89c1867_1    conda-forge
        jupyter_server            1.11.2             pyhd8ed1ab_0    conda-forge
        jupyter_telemetry         0.1.0              pyhd8ed1ab_1    conda-forge
        jupyterhub-base           1.4.2            py37h89c1867_0    conda-forge
        jupyterhub-singleuser     1.4.2            py37h89c1867_0    conda-forge
        jupyterlab                3.1.17             pyhd8ed1ab_0    conda-forge
        jupyterlab-widgets        2.0.0b1                   dev_0    <develop>
        jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
        jupyterlab_server         2.8.2              pyhd8ed1ab_0    conda-forge
        kiwisolver                1.3.2                    pypi_0    pypi
        krb5                      1.19.2               hcc1bbae_3    conda-forge
        ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
        libcurl                   7.80.0               h2574ce0_0    conda-forge
        libedit                   3.1.20191231         he28a2e2_2    conda-forge
        libev                     4.33                 h516909a_1    conda-forge
        libffi                    3.4.2                h7f98852_5    conda-forge
        libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
        libgomp                   11.2.0              h1d223b6_11    conda-forge
        libnghttp2                1.43.0               h812cca2_1    conda-forge
        libnsl                    2.0.0                h7f98852_0    conda-forge
        libsodium                 1.0.18               h36c2ea0_1    conda-forge
        libssh2                   1.10.0               ha56f1ee_2    conda-forge
        libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
        libuv                     1.42.0               h7f98852_0    conda-forge
        libzlib                   1.2.11            h36c2ea0_1013    conda-forge
        mako                      1.1.6              pyhd8ed1ab_0    conda-forge
        markupsafe                2.0.1            py37h5e8e339_1    conda-forge
        matplotlib                3.5.1                    pypi_0    pypi
        matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
        mistune                   0.8.4           py37h5e8e339_1005    conda-forge
        mpmath                    1.2.1                    pypi_0    pypi
        nbclassic                 0.3.4              pyhd8ed1ab_0    conda-forge
        nbclient                  0.5.9              pyhd8ed1ab_0    conda-forge
        nbconvert                 6.0.7            py37h89c1867_3    conda-forge
        nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
        ncurses                   6.2                  h58526e2_4    conda-forge
        nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
        networkx                  2.6.3                    pypi_0    pypi
        nodejs                    14.17.4              h92b4a50_0    conda-forge
        notebook                  6.3.0              pyha770c72_1    conda-forge
        nteract_on_jupyter        2.1.3                      py_0    conda-forge
        numpy                     1.21.5                   pypi_0    pypi
        oauthlib                  3.1.1              pyhd8ed1ab_0    conda-forge
        openssl                   1.1.1l               h7f98852_0    conda-forge
        packaging                 21.3               pyhd8ed1ab_0    conda-forge
        pamela                    1.0.0                      py_0    conda-forge
        pandas                    1.3.5                    pypi_0    pypi
        pandoc                    2.16.1               h7f98852_0    conda-forge
        pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
        parso                     0.8.2              pyhd8ed1ab_0    conda-forge
        pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
        pickleshare               0.7.5                   py_1003    conda-forge
        pillow                    8.4.0                    pypi_0    pypi
        pip                       21.3.1             pyhd8ed1ab_0    conda-forge
        pluggy                    1.0.0                    pypi_0    pypi
        prometheus_client         0.12.0             pyhd8ed1ab_0    conda-forge
        prompt-toolkit            3.0.22             pyha770c72_0    conda-forge
        psutil                    5.8.0            py37h5e8e339_2    conda-forge
        ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
        py                        1.11.0                   pypi_0    pypi
        pycparser                 2.21               pyhd8ed1ab_0    conda-forge
        pycurl                    7.44.1           py37h88a64d2_1    conda-forge
        pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
        pyjwt                     2.3.0              pyhd8ed1ab_0    conda-forge
        pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
        pyparsing                 3.0.6              pyhd8ed1ab_0    conda-forge
        pyrsistent                0.18.0           py37h5e8e339_0    conda-forge
        pysocks                   1.7.1            py37h89c1867_4    conda-forge
        pytest                    6.2.5                    pypi_0    pypi
        pytest-cov                3.0.0                    pypi_0    pypi
        python                    3.7.12          hb7a2778_100_cpython    conda-forge
        python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
        python-json-logger        2.0.1              pyh9f0ad1d_0    conda-forge
        python_abi                3.7                     2_cp37m    conda-forge
        pytz                      2021.3             pyhd8ed1ab_0    conda-forge
        pywavelets                1.2.0                    pypi_0    pypi
        pyzmq                     22.3.0           py37h336d617_1    conda-forge
        readline                  8.1                  h46c0cb4_0    conda-forge
        requests                  2.26.0             pyhd8ed1ab_0    conda-forge
        ruamel.yaml               0.17.17          py37h5e8e339_1    conda-forge
        ruamel.yaml.clib          0.2.6            py37h5e8e339_0    conda-forge
        scikit-image              0.19.1                   pypi_0    pypi
        scikit-learn              1.0.1                    pypi_0    pypi
        scipy                     1.7.3                    pypi_0    pypi
        send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
        setuptools                59.1.1           py37h89c1867_0    conda-forge
        six                       1.16.0             pyh6c4a22f_0    conda-forge
        sniffio                   1.2.0            py37h89c1867_2    conda-forge
        sqlalchemy                1.4.27           py37h5e8e339_0    conda-forge
        sqlite                    3.36.0               h9cd32fc_2    conda-forge
        sympy                     1.9                      pypi_0    pypi
        terminado                 0.12.1           py37h89c1867_1    conda-forge
        testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
        threadpoolctl             3.0.0                    pypi_0    pypi
        tifffile                  2021.11.2                pypi_0    pypi
        tk                        8.6.11               h27826a3_1    conda-forge
        toml                      0.10.2                   pypi_0    pypi
        tomli                     2.0.0                    pypi_0    pypi
        tomlkit                   0.8.0                    pypi_0    pypi
        tornado                   6.1              py37h5e8e339_2    conda-forge
        traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
        traittypes                0.2.1                    pypi_0    pypi
        typing_extensions         4.0.0              pyha770c72_0    conda-forge
        urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
        wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
        webencodings              0.5.1                      py_1    conda-forge
        websocket-client          1.2.1            py37h89c1867_0    conda-forge
        wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
        widgetsnbextension        4.0.0b1                   dev_0    <develop>
        xyzservices               2021.11.0                pypi_0    pypi
        xz                        5.2.5                h516909a_1    conda-forge
        zeromq                    4.3.4                h9c3ff4c_1    conda-forge
        zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
        zlib                      1.2.11            h36c2ea0_1013    conda-forge

conda env:
        name: notebook
        channels:
          - conda-forge
          - defaults
        dependencies:
          - _libgcc_mutex=0.1=conda_forge
          - _openmp_mutex=4.5=1_gnu
          - alembic=1.7.5=pyhd8ed1ab_0
          - anyio=3.3.4=py37h89c1867_1
          - argcomplete=1.12.3=pyhd8ed1ab_2
          - argon2-cffi=21.1.0=py37h5e8e339_2
          - async_generator=1.10=py_0
          - attrs=21.2.0=pyhd8ed1ab_0
          - babel=2.9.1=pyh44b312d_0
          - backcall=0.2.0=pyh9f0ad1d_0
          - backports=1.0=py_2
          - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
          - bleach=4.1.0=pyhd8ed1ab_0
          - blinker=1.4=py_1
          - brotlipy=0.7.0=py37h5e8e339_1003
          - c-ares=1.18.1=h7f98852_0
          - ca-certificates=2021.10.8=ha878542_0
          - certifi=2021.10.8=py37h89c1867_1
          - certipy=0.1.3=py_0
          - cffi=1.15.0=py37h036bc23_0
          - chardet=4.0.0=py37h89c1867_2
          - charset-normalizer=2.0.0=pyhd8ed1ab_0
          - cryptography=35.0.0=py37hf1a17b8_2
          - debugpy=1.5.1=py37hcd2ae1e_0
          - decorator=5.1.0=pyhd8ed1ab_0
          - defusedxml=0.7.1=pyhd8ed1ab_0
          - entrypoints=0.3=pyhd8ed1ab_1003
          - greenlet=1.1.2=py37hcd2ae1e_1
          - icu=68.2=h9c3ff4c_0
          - idna=3.1=pyhd3deb0d_0
          - importlib-metadata=4.8.2=py37h89c1867_0
          - importlib_metadata=4.8.2=hd8ed1ab_0
          - importlib_resources=5.4.0=pyhd8ed1ab_0
          - ipykernel=6.5.0=py37h6531663_1
          - ipython=7.29.0=py37h6531663_2
          - ipython_genutils=0.2.0=py_1
          - jedi=0.18.1=py37h89c1867_0
          - jinja2=3.0.3=pyhd8ed1ab_0
          - json5=0.9.5=pyh9f0ad1d_0
          - jsonschema=4.2.1=pyhd8ed1ab_0
          - jupyter-offlinenotebook=0.2.1=pyhd8ed1ab_0
          - jupyter-resource-usage=0.6.0=pyhd8ed1ab_0
          - jupyter_client=7.0.6=pyhd8ed1ab_0
          - jupyter_core=4.9.1=py37h89c1867_1
          - jupyter_server=1.11.2=pyhd8ed1ab_0
          - jupyter_telemetry=0.1.0=pyhd8ed1ab_1
          - jupyterhub-base=1.4.2=py37h89c1867_0
          - jupyterhub-singleuser=1.4.2=py37h89c1867_0
          - jupyterlab=3.1.17=pyhd8ed1ab_0
          - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
          - jupyterlab_server=2.8.2=pyhd8ed1ab_0
          - krb5=1.19.2=hcc1bbae_3
          - ld_impl_linux-64=2.36.1=hea4e1c9_2
          - libcurl=7.80.0=h2574ce0_0
          - libedit=3.1.20191231=he28a2e2_2
          - libev=4.33=h516909a_1
          - libffi=3.4.2=h7f98852_5
          - libgcc-ng=11.2.0=h1d223b6_11
          - libgomp=11.2.0=h1d223b6_11
          - libnghttp2=1.43.0=h812cca2_1
          - libnsl=2.0.0=h7f98852_0
          - libsodium=1.0.18=h36c2ea0_1
          - libssh2=1.10.0=ha56f1ee_2
          - libstdcxx-ng=11.2.0=he4da1e4_11
          - libuv=1.42.0=h7f98852_0
          - libzlib=1.2.11=h36c2ea0_1013
          - mako=1.1.6=pyhd8ed1ab_0
          - markupsafe=2.0.1=py37h5e8e339_1
          - matplotlib-inline=0.1.3=pyhd8ed1ab_0
          - mistune=0.8.4=py37h5e8e339_1005
          - nbclassic=0.3.4=pyhd8ed1ab_0
          - nbclient=0.5.9=pyhd8ed1ab_0
          - nbconvert=6.0.7=py37h89c1867_3
          - nbformat=5.1.3=pyhd8ed1ab_0
          - ncurses=6.2=h58526e2_4
          - nest-asyncio=1.5.1=pyhd8ed1ab_0
          - nodejs=14.17.4=h92b4a50_0
          - notebook=6.3.0=pyha770c72_1
          - nteract_on_jupyter=2.1.3=py_0
          - oauthlib=3.1.1=pyhd8ed1ab_0
          - openssl=1.1.1l=h7f98852_0
          - packaging=21.3=pyhd8ed1ab_0
          - pamela=1.0.0=py_0
          - pandoc=2.16.1=h7f98852_0
          - pandocfilters=1.5.0=pyhd8ed1ab_0
          - parso=0.8.2=pyhd8ed1ab_0
          - pexpect=4.8.0=pyh9f0ad1d_2
          - pickleshare=0.7.5=py_1003
          - pip=21.3.1=pyhd8ed1ab_0
          - prometheus_client=0.12.0=pyhd8ed1ab_0
          - prompt-toolkit=3.0.22=pyha770c72_0
          - psutil=5.8.0=py37h5e8e339_2
          - ptyprocess=0.7.0=pyhd3deb0d_0
          - pycparser=2.21=pyhd8ed1ab_0
          - pycurl=7.44.1=py37h88a64d2_1
          - pygments=2.10.0=pyhd8ed1ab_0
          - pyjwt=2.3.0=pyhd8ed1ab_0
          - pyopenssl=21.0.0=pyhd8ed1ab_0
          - pyparsing=3.0.6=pyhd8ed1ab_0
          - pyrsistent=0.18.0=py37h5e8e339_0
          - pysocks=1.7.1=py37h89c1867_4
          - python=3.7.12=hb7a2778_100_cpython
          - python-dateutil=2.8.2=pyhd8ed1ab_0
          - python-json-logger=2.0.1=pyh9f0ad1d_0
          - python_abi=3.7=2_cp37m
          - pytz=2021.3=pyhd8ed1ab_0
          - pyzmq=22.3.0=py37h336d617_1
          - readline=8.1=h46c0cb4_0
          - requests=2.26.0=pyhd8ed1ab_0
          - ruamel.yaml=0.17.17=py37h5e8e339_1
          - ruamel.yaml.clib=0.2.6=py37h5e8e339_0
          - send2trash=1.8.0=pyhd8ed1ab_0
          - setuptools=59.1.1=py37h89c1867_0
          - six=1.16.0=pyh6c4a22f_0
          - sniffio=1.2.0=py37h89c1867_2
          - sqlalchemy=1.4.27=py37h5e8e339_0
          - sqlite=3.36.0=h9cd32fc_2
          - terminado=0.12.1=py37h89c1867_1
          - testpath=0.5.0=pyhd8ed1ab_0
          - tk=8.6.11=h27826a3_1
          - tornado=6.1=py37h5e8e339_2
          - traitlets=5.1.1=pyhd8ed1ab_0
          - typing_extensions=4.0.0=pyha770c72_0
          - urllib3=1.26.7=pyhd8ed1ab_0
          - wcwidth=0.2.5=pyh9f0ad1d_2
          - webencodings=0.5.1=py_1
          - websocket-client=1.2.1=py37h89c1867_0
          - wheel=0.37.0=pyhd8ed1ab_1
          - xz=5.2.5=h516909a_1
          - zeromq=4.3.4=h9c3ff4c_1
          - zipp=3.6.0=pyhd8ed1ab_0
          - zlib=1.2.11=h36c2ea0_1013
          - pip:
            - bqplot==0.12.31
            - coverage==6.2
            - cycler==0.11.0
            - deprecation==2.1.0
            - fonttools==4.28.5
            - imageio==2.13.5
            - iniconfig==1.1.1
            - ipyleaflet==0.15.0
            - joblib==1.1.0
            - jupyter-packaging==0.11.1
            - kiwisolver==1.3.2
            - matplotlib==3.5.1
            - mpmath==1.2.1
            - networkx==2.6.3
            - numpy==1.21.5
            - pandas==1.3.5
            - pillow==8.4.0
            - pluggy==1.0.0
            - py==1.11.0
            - pytest==6.2.5
            - pytest-cov==3.0.0
            - pywavelets==1.2.0
            - scikit-image==0.19.1
            - scikit-learn==1.0.1
            - scipy==1.7.3
            - sympy==1.9
            - threadpoolctl==3.0.0
            - tifffile==2021.11.2
            - toml==0.10.2
            - tomli==2.0.0
            - tomlkit==0.8.0
            - traittypes==0.2.1
            - xyzservices==2021.11.0
        prefix: /srv/conda/envs/notebook
</pre>
</details>

### If using JupyterLab
- JupyterLab version:

<details><summary>Installed Labextensions</summary>
<pre>
JupyterLab v3.1.17
/srv/conda/envs/notebook/share/jupyter/labextensions
        jupyter-offlinenotebook v0.2.1 enabled OK
        jupyter-leaflet v0.15.0 enabled OK
        bqplot v0.5.32 enabled OK (python, bqplot)
        @jupyter-widgets/jupyterlab-manager v4.0.0-beta.1 enabled OK
        @jupyter-server/resource-usage v0.6.0 enabled OK (python, jupyter-resource-usage)
</pre>
</details>

**Comment by chaedri** [comment]
This fixes it for me! Thank you.

**Comment by jasongrout** [comment]
@chaedri - thank you very much for testing the 8.0 beta and reporting this!
