### ISSUE TITLE
ipywidgets memory leak

### ISSUE THREAD

**Issue by jdfreder** [jupyter-widgets/ipywidgets#337]
Reported in https://github.com/ipython/ipython/issues/8207

---
For reference, here is the original text:

A reference cycle is formed by `_validate_border` being defined inside `__init__` (adding self to its closure) and added to `self._trait_notifiers` via `on_trait_change`. Because it also has a `__del__` method, gc won't collect it.

This problem can be fixed by defining `_validate_border` outside `__init__` or outside the class. A better solution may be to remove `__del__` altogether, since it is never called in practice. To trigger `__del__`, one would have to remove the widget from `Widget.widgets` and break another reference cycle formed by `Widget.comm` and `Comm._msg_callback`.

As widgets and their comms naturally form cycles, the presence of `__del__` on Comm is similarly unhealthy. I think this `__del__` is also expendable, because only a user call to `CommManager.unregister_comm` can trigger it.

To reproduce: 

```
from IPython.html import widgets
from IPython.display import display
w = widgets.FloatText()
display(w)
w.close()
%xdel w
import gc
# widget appears in garbage only after it has been displayed
gc.collect()
print gc.garbage
# but always in the full object list
print [obj for obj in gc.get_objects() if type(obj).__name__ == 'FloatText']
del obj
```

`objgraph` output for reference:
![widget_ref_cycle](https://cloud.githubusercontent.com/assets/11727027/6913062/03757450-d7be-11e4-8fc9-39c199d92321.png)

**Comment by jasongrout** [comment]
We do not have `_validate_border` anymore. We do still have a `__del__` method on widgets, though.

**Comment by SylvainCorlay** [comment]
Should we move this issue to ipykernel? @minrk

**Comment by minrk** [comment]
@SylvainCorlay sure, if it's reproducible without using widgets.

**Comment by jasongrout** [comment]
bumping to 6.1

**Comment by jasongrout** [comment]
We don't define the validator in __init__ anymore, and I checked using the code above and the del removes the widget from the object list.
