### ISSUE TITLE
Dropdown widget does not work properyl in VSCode

### ISSUE THREAD

**Issue by smackesey** [jupyter-widgets/ipywidgets#3383]
## Description

Clicking a dropdown list in VSCode causes the contents to flash briefly, rather than staying open and allowing you to change your selection.

https://user-images.githubusercontent.com/1531373/153889771-c9ca3ac8-46e6-4871-9b70-f089b575a02b.mov

## Reproduce

VSCode Info:
Version: 1.65.0-insider
Commit: 50089c3f92c17584a4aca179f51f220b56c22020
Date: 2022-02-14T05:17:15.582Z
Electron: 16.0.8
Chromium: 96.0.4664.110
Node.js: 16.9.1
V8: 9.6.180.21-electron.0
OS: Darwin x64 21.3.0

Python:
3.10.2

ipywidgets (tried two versions):
7.6.5
8.0.0b1

**Comment by vidartf** [comment]
I would report this to the relevant VSCode repo, as they should be able to more correctly troubleshoot this. Then, if it turns out there is an issue with the underlying ipywidgets code they should be able to give more details about what exactly is the problem.

**Comment by jasongrout** [comment]
CC also @DonJayamanne about this ipywidgets-in-vscode issue.

**Comment by DonJayamanne** [comment]
Oh sorry for missing this, 
I've tried this in VS Code insiders and seems to work well.
@smackesey Please could you install VS Code insiders, possible its been resolved in the latest dev version.
If the problem persists, please feel free to create an issue on VSCode or Jupyter repo https://github.com/microsoft/vscode-jupyter/issues
![image](https://user-images.githubusercontent.com/1948812/155616968-abcdded0-0337-4b8e-acf2-2b845a53f1bd.png)

**Comment by jasongrout** [comment]
Thanks Don!

>  If the problem persists, please feel free to create an issue on VSCode or Jupyter repo https://github.com/microsoft/vscode-jupyter/issues

I'll go ahead and close this issue.

**Comment by projeffboy** [comment]
Hey I use VSCode 1.68 (May) and I still get this issue:

https://user-images.githubusercontent.com/20577302/177211449-f43c67be-a573-44f3-ab07-dc9546cfcb98.mp4

Unfortunately, I can't capture the dropdown itself through windows xbox screen capture, but as you can see it won't change

**Comment by projeffboy** [comment]
Oh seems like it got moved to this issue: https://github.com/microsoft/vscode/issues/151981
