### ISSUE TITLE
Tab does not interact well with ipyleaflet Map object

### ISSUE THREAD

**Issue by PROgram52bc** [jupyter-widgets/ipywidgets#3384]
## Description

When an ipyleaflet Map object is placed inside a tab other than the first one, it doesn't get fully rendered, where there are gray areas as illustrated in the screenshot.

![Screenshot from 2022-02-14 19-15-06](https://user-images.githubusercontent.com/18290763/153968665-99e100d3-aa07-4002-84e1-d99e47e6682d.png)

I am suspecting this is an issue more related to the Tab widget rather than the Map class, because when I place the map on the first tab, it renders correctly. But it might be a bug with ipyleaflet as well. Let me know what you think!

## Reproduce

1. Create a fresh environment, with ipyleaflet and ipywidgets installed.
2. Create a new notebook with the following content
```python
from ipyleaflet import Map
from ipywidgets import Tab, Text
m = Map(center=(0,0), zoom=2)
display(Tab([Text("blah"), m]))
```
3. Click on the second tab
4. The behavior should be reproduced

## Expected behavior

Map should be rendered without gray areas.

## Context

- ipywidgets version 
- Operating System and version: Ubuntu 18.04
- Browser and version: Chrome Version 96.0.4664.110 (Official Build) (64-bit)

**Comment by jasongrout** [comment]
Yes, this should be fixed in 8.0. This is a relevant issue: https://github.com/jupyter-widgets/ipywidgets/issues/2762
