### ISSUE TITLE
slider does not work on mobile device

### ISSUE THREAD

**Issue by bdch1234** [jupyter-widgets/ipywidgets#3401]
When using touch screen, I can only change slider value with "point-click", i.e. touching the slider away from current value. Trying to do drag on current value does not change slider value, like it does when using mouse.

**Comment by jasongrout** [comment]
This should be fixed in ipywidgets 8. Can you check with the ipywidgets 8.0 prerelease?

**Comment by bdch1234** [comment]
Indeed, it is working in the pre-release.
