### ISSUE TITLE
FileUpload.value readonly ?

### ISSUE THREAD

**Issue by ruomad** [jupyter-widgets/ipywidgets#3406]
I can confirm that the last commit fixes the problem with voila not displaying widgets
But i ran into an unexpected error with FileUpload widget which reports that FileUpload.value is read-only.
Am I missing something ?

<pre>
File ~\AppData\Local\pypoetry\Cache\virtualenvs\azlab-TXIRGxn6-py3.10\lib\site-packages\ipywidgets\widgets\widget.py:412, in Widget.__init__(self, **kwargs)
    410 """Public constructor"""
    411 self._model_id = kwargs.pop('model_id', None)
--> 412 super(Widget, self).__init__(**kwargs)
    414 Widget._call_widget_constructed(self)
    415 self.open()

File ~\AppData\Local\pypoetry\Cache\virtualenvs\azlab-TXIRGxn6-py3.10\lib\site-packages\traitlets\traitlets.py:1079, in HasTraits.__init__(self, *args, **kwargs)
   1077 for key, value in kwargs.items():
   1078     if self.has_trait(key):
-> 1079         setattr(self, key, value)
   1080     else:
   1081         # passthrough args that don't set traits to super
   1082         super_kwargs[key] = value

File ~\AppData\Local\pypoetry\Cache\virtualenvs\azlab-TXIRGxn6-py3.10\lib\site-packages\traitlets\traitlets.py:604, in TraitType.__set__(self, obj, value)
    598 """Set the value of the trait by self.name for the instance.
    599 
    600 Values pass through a validation stage where errors are raised when
    601 impropper types, or types that cannot be coerced, are encountered.
    602 """
    603 if self.read_only:
--> 604     raise TraitError('The "%s" trait is read-only.' % self.name)
    605 else:
    606     self.set(obj, value)

TraitError: The "value" trait is read-only.
</pre>

**Comment by ruomad** [comment]
hum, sorry, I was in fact using a cached version of 7.6.5, humble apologies

**Comment by ruomad** [comment]
So OK it doesn't fix the problem with voila (it was just a hopeful try from my part). I'll have to wait the final version of ipywidgets 8 and the update of voila. Sorry for the noise.

**Comment by jasongrout** [comment]
> I can confirm that the last commit fixes the problem with voila not displaying widgets

I feel like this conversation started somewhere else, and I'm coming in halfway through. Do you have more context about what you are trying to do, example code, etc.?

> So OK it doesn't fix the problem with voila (it was just a hopeful try from my part). I'll have to wait the final version of ipywidgets 8 and the update of voila. Sorry for the noise.

On the other hand, it seems like you answered your own question here? Should we close this ticket as resolved? I'm a bit confused here.

**Comment by ruomad** [comment]
Yes you're right my first concern is that voila isn't yet compatible with ipywidgets-8. But I was  wrong to open this ticket, I'll close it, sorry again for this.
