### ISSUE TITLE
Unobserve doesn't work

### ISSUE THREAD

**Issue by gioxc88** [jupyter-widgets/ipywidgets#3411]
``` 
import ipywidgets as w

def test(change):
    print(3)

b = w.Button()
b.on_click(test)

b.unobserve(test)  # does not work
b.unibserve_all()  # does not work

```

**Comment by vidartf** [comment]
`on_click` does not use `observe`, so consequently, `unobserve` will not do anything in your example. Try setting `on_click = None`.

**Comment by jasongrout** [comment]
Please don't set `on_click = None`. Instead, call the function with the `remove=True` argument (see docs at https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20Events.html?highlight=on_click#Special-events).

```python
b.on_click(test, remove=True)
```
