### ISSUE TITLE
Combine dropdown widget  and text widget 

### ISSUE THREAD

**Issue by vpicouet** [jupyter-widgets/ipywidgets#3420]
Hello,
It would be extremely interesting to 
combine dropdown widget  and text widget (see image).
That would be great as it would allow to:
- give a lot of examples to the user while not preventing him to use different entries
- show the user the syntax of what should be written, etc.
Thanks a lot for the amazing work!
![Capture d’écran, le 2022-03-16 à 14 01 25](https://user-images.githubusercontent.com/37241971/158657006-e497e28e-7bf1-4bd3-9228-59b2ab69c1ee.jpg)

**Comment by jasongrout** [comment]
That is the combobox widget? https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html#Combobox

**Comment by vpicouet** [comment]
Thanks a lot!!! I did not know it, That's perfect!!
