### ISSUE TITLE
Using clear_output() inside with contextual manager

### ISSUE THREAD

**Issue by joseberlines** [jupyter-widgets/ipywidgets#3421]
I normally clear the output of a Ouput() widget as follows:

`import ipywidgets as wd
out = wd.Output()
with out:
    out.clear_output()`

Why fo you have to rewrite the name of the output widget inside the with? 
Is that not supposed to be a contextual manager?

I would expect this to work:
`with out:
    clear_output()`

This question is also in: https://stackoverflow.com/questions/71573200/ipywidget-output-in-contextual-with-clear-output

**Comment by jasongrout** [comment]
> I would expect this to work:
> `with out: clear_output()`

That's what you should do.

> `import ipywidgets as wd out = wd.Output() with out: out.clear_output()`

This will have subtle issues that could crop up. You should not use `out.clear_output()` inside the context manager.

We tried to hint at this distinction in the [docs](https://ipywidgets.readthedocs.io/en/stable/examples/Output%20Widget.html):

> We can clear the output by either using IPython.display.clear_output within the context manager, or we can call the widget’s clear_output method directly.

It seems we should be more clear that you should not use the widget's clear_output method inside its own context manager.
