### ISSUE TITLE
ImportError: cannot import name 'StaticInteract'

### ISSUE THREAD

**Issue by ranabanik** [jupyter-widgets/ipywidgets#3435]
trying to implement ipywidget examples [here](https://jakevdp.github.io/blog/2013/12/05/static-interactive-widgets/). 
```
def show_fib(N):
    sequence = ""
    a, b = 0, 1
    for i in range(N):
        sequence += "{0} ".format(a)
        a, b = b, a + b
    return sequence
```

```
from ipywidgets import StaticInteract, RangeWidget
StaticInteract(show_fib,
               N=RangeWidget(1, 100))
```

But getting the error mentioned in the title. The codes were run in a newly created python 3.6 environment. 

`ipywidgets.__version__`
'7.7.0'

**Comment by jasongrout** [comment]
Those instructions are for very old versions of ipywidgets and are out of date. See the instructions in the current docs: https://ipywidgets.readthedocs.io/en/stable/examples/Using%20Interact.html
