### ISSUE TITLE
pypi page for ipywidgets 8 is empty

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#3439]
@bollwyvl pointed out on [discourse](https://discourse.jupyter.org/t/ipywidgets-8-0-0rc0-prerelease-please-test/13747/3) that the pypi page for the 8.0rc is empty - no description, etc. Perhaps something got messed up with the python packaging?

**Comment by jasongrout** [comment]
See https://pypi.org/project/ipywidgets/8.0.0rc0/

**Comment by jasongrout** [comment]
Notice that https://github.com/jupyter-widgets/ipywidgets/blob/master/python/ipywidgets/setup.cfg#L8 points to a nonexistent file now.

**Comment by martinRenou** [comment]
Note that using `file: ../../README.md` in the `setup.cfg` makes `python -m build` fail with: 

```
distutils.errors.DistutilsOptionError: Cannot access '/home/martin/github/ipywidgets/python/ipywidgets/../../README.md' (or anything outside '/home/martin/github/ipywidgets/python/ipywidgets')
```

**Comment by vidartf** [comment]
The proper solution is probably to make a separate readme in the ipywidgets package directory, similar to how the two other python packages have their own readme file. It would probably be a copy of the root readme that had been focused only on the ipywidgets part.

**Comment by jasongrout** [comment]
This is done in #3461
