### ISSUE TITLE
plot=true does not work in catboost

### ISSUE THREAD

**Issue by breeze90** [jupyter-widgets/ipywidgets#3460]
https://i.stack.imgur.com/Z3WYl.png

https://i.stack.imgur.com/j3udw.png

Catboost doesnt show plot. I am using mac m1 arm. Jupyter is locally installed.

Selected Jupyter core packages... IPython : 8.3.0 ipykernel : 6.13.0 ipywidgets : 7.7.0 jupyter_client : 7.3.0 jupyter_core : 4.10.0 jupyter_server : not installed jupyterlab : not installed nbclient : 0.6.2 nbconvert : 6.5.0 nbformat : 5.4.0 notebook : 6.4.11 qtconsole : not installed traitlets : 5.1.1

Tried in safari and chrome. Tried everything i could. No idea what could be the reason.

Could you please understand where to look? I reinstalled everything, tried --sys and normal way

**Comment by jasongrout** [comment]
Do core ipywidgets show? i.e., does this show a widget?

```
from ipywidgets import IntSlider
display(IntSlider())
```
If a widget does show, then I'd suggest posting an issue in the catboost project. If it doesn't, then likely there is something amiss with your core ipywidgets configuration.

**Comment by breeze90** [comment]
This does work.

<img width="1089" alt="Screenshot 2022-05-17 at 18 00 09" src="https://user-images.githubusercontent.com/4200640/168843478-3a0172da-e0d3-4346-bb5f-0472b98b52f3.png">

I asked them but didnt get any answer. 

What I noticed is that after you enable the widget, the behavior of cells alters. Basically it has a little bit more space like its trying to load it but failes.

<img width="1133" alt="Screenshot 2022-05-17 at 18 00 21" src="https://user-images.githubusercontent.com/4200640/168844177-dbaadbd5-1d2c-407d-a3fc-9b744c48676d.png">
 
I also have errors in browser javascript console 

<img width="1092" alt="Screenshot 2022-05-17 at 18 04 53" src="https://user-images.githubusercontent.com/4200640/168844414-07c90d7e-771d-4ce9-aaf9-b4fe3d0bb35c.png">

No idea what to try more.

**Comment by jasongrout** [comment]
Thanks. It does seem like ipywidgets itself is working fine, and the error seems to be in the catboost widget, so working with that project seems to be the appropriate thing to do. Good luck!

**Comment by breeze90** [comment]
thanks.

I checked the console again.

This is what I get when I open jupyter notebook and does not even start anything.

<img width="1084" alt="Screenshot 2022-05-18 at 09 02 09" src="https://user-images.githubusercontent.com/4200640/168968397-d8c7cfc5-3bd3-4a9b-a396-d282ac00c39e.png">

And this is what i get when i call model.fit (the part of the code which is supposed to show the widget.

<img width="1091" alt="Screenshot 2022-05-18 at 09 03 04" src="https://user-images.githubusercontent.com/4200640/168968477-7c88c328-b299-47d4-9497-555ffaadee07.png">

Are you saying its on catboost side? I am not sure I understand it but it doesnt look like they use their own widgets, its like they use ipywidgets.

https://catboost.ai/en/docs/installation/python-installation-additional-data-visualization-packages

I mean I tried to reach them but well yeah not optimistic they could help.

**Comment by jasongrout** [comment]
I see the error about "http://localhost:8888/static/catboost-widget.js", so there is javascript from catboost. However, it does seem like you have a similar error about ipywidgets. In fact, there is a 404 for the ipywidgets javascript file. It may be that your installation is messed up and not finding the widgets appropriately.

As a test, you could try in a fresh new clean environment. With the latest ipywidgets and other packages, you shouldn't need any `--sys` or `nbextension install` or anything - just pip or conda install the packages.

**Comment by breeze90** [comment]
Yeah I tried it but it didnt work.

And again if I install everything I am gonna do it the same way I did because its the only way i know - by simply using pip install(

I guess I will have to cope with not having it, thanks for the help.

Last question I wanted to ask - Maybe I need to install something else like javascript files?

**Comment by breeze90** [comment]
Ok new info from this console also may help
<img width="1025" alt="Screenshot 2022-05-19 at 18 08 14" src="https://user-images.githubusercontent.com/4200640/169329681-908ed388-11d5-4fdf-9e62-cdef8f85566b.png">

**Comment by jasongrout** [comment]
Yes, there does seem to be a problem with the catboost-widget installation.

Can you give me exactly the commands you use to install your environment?

**Comment by breeze90** [comment]
Basically it was install brew, brew install python.

then pip installs python packages like numpy pandas
pip install notebook
pip install catboost
pip install ipywidgets
jupyter nbextension install --py --sys-prefix widgetsnbextension
jupyter nbextension enable --py --sys-prefix widgetsnbextension

i have this error though without --sys

<img width="996" alt="Screenshot 2022-05-19 at 19 24 09" src="https://user-images.githubusercontent.com/4200640/169350374-1f25c839-4abc-4559-977b-14ade0659a62.png">

maybe the problem is with home brew i dont know, maybe i could give you some kind of results of commands and directories if you tell me how too look through it

**Comment by jasongrout** [comment]
Yes, that certainly is a problem with --sys-prefix and home brew. I use https://github.com/mamba-org/mamba/, but you could also use [anaconda](https://www.anaconda.com/products/distribution). You also don't need the nbextension lines these days.

I created and activated a new conda environment with just python, then did `pip install notebook numpy pandas catboost ipywidgets`, then ran the example at https://catboost.ai/en/docs/concepts/python-usages-examples#cv-usage-example and the widgets showed up just fine.
