### ISSUE TITLE
Disconnect broken link problems

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#3466]
## Description

The disconnect UX signal isn't working in two cases in JupyterLab:

1. When restarting, the broken link icon is, well, broken in jupyterlab.
2. When stopping the kernel, the broken link does not show up.

Thanks @xiaochen-db for pointing out the stopping kernel problem.

See 
![connect](https://user-images.githubusercontent.com/192614/169420423-d51c1aa1-c8b2-4ffe-84d7-23782b0c0381.gif)

This may be a fontawesome CSS issue. Here is the CSS we use currently:

https://github.com/jupyter-widgets/ipywidgets/blob/fbdbd005da4dc58994704f39bcc19a40bbecdec5/packages/base/css/index.css#L5-L16

## Reproduce

1. Install widgets and JupyterLab
2. Create a widget. Restart the kernel. Notice the icon does not show up correctly.
3. Create a widget. Stop the kernel. Notice the disconnected symbol does not show up.

## Context

- ipywidgets version master (8.0rc0)
- Operating System and version: macos
- Browser and version: Firefox 100

**Comment by jasongrout** [comment]
Fixing the CSS to show the icon in JupyterLab for restarting a kernel is likely a good first issue.

**Comment by vidartf** [comment]
Closed by #3475
