### ISSUE TITLE
Bug: Message throttling is broken after first update message from frontend

### ISSUE THREAD

**Issue by maartenbreddels** [jupyter-widgets/ipywidgets#3469]
## Description

The message throttling mechanism should accumulate change in a widget model while the kernel is busy. When the kernel becomes idle again, we send the outstanding changes. To catch the kernel status changes (introduced in #1383 ) we save the previous callback in https://github.com/jasongrout/ipywidgets/blob/ae946250b0e3233da04c3a03c4f92d444b91bce3/jupyter-js-widgets/src/widget.ts#L417 and call it at https://github.com/jasongrout/ipywidgets/blob/ae946250b0e3233da04c3a03c4f92d444b91bce3/jupyter-js-widgets/src/widget.ts#L421

However, after the first call to `send_sync_message`, we never restore `callbacks.iopub.status`, and thus on the next call to `send_sync_message`, we call the function we assigned at https://github.com/jasongrout/ipywidgets/blob/ae946250b0e3233da04c3a03c4f92d444b91bce3/jupyter-js-widgets/src/widget.ts#L418 in the previous call.

This will cause `_pending_msg' to go to -1 at line https://github.com/jasongrout/ipywidgets/blob/ae946250b0e3233da04c3a03c4f92d444b91bce3/jupyter-js-widgets/src/widget.ts#L250 and the message throttling mechanism at https://github.com/jasongrout/ipywidgets/blob/ae946250b0e3233da04c3a03c4f92d444b91bce3/jupyter-js-widgets/src/widget.ts#L354 will never be used again.

## Reproduce

```
import ipywidgets as w
w.FloatSlider()
```
Move the slider once (a single click), now `_pending_msg` should be 0, but the `callbacks.iopub.status` contains the old function. Move the slider again, now the _pending_msg should be called twice when the kernel goes idle, and `_pending_msgs` should be -1. Now drag the slider, and check in the websocket messages, and you should see multiple update calls directly following each other:

In this screenshot in chrome:
<img width="810" alt="image" src="https://user-images.githubusercontent.com/1765949/170269952-33adc939-a36c-4550-9606-e3b2b7fb79ec.png">

We can see 6 (green) update messages.

## Expected behavior

We expected to see 1 update message, followed by a busy/idle pair, followed by a last single update, and another busy/idle message

**Comment by jasongrout** [comment]
@maartenbreddels - Sorry, I'm just taking a look at this now. I think the assumption in the code is that:

1. send_sync_message is only ever called *once* per message. When the original sync happens, either we put the message on the queue or we send it immediately, and the callback modifications happen only when we actually send the message.
2. I think an implicit assumption in the send_sync_message code is that the callback object is a new object unique to this message, i.e., we aren't modifying a global object, that then we'll modify again later.

Do you agree with both of those? I think with those two assumptions, the code that is there is okay (or am I missing something?). Which of those two assumptions is wrong?

**Comment by jasongrout** [comment]
> Do you agree with both of those? I think with those two assumptions, the code that is there is okay (or am I missing something?). Which of those two assumptions is wrong?

#3485 fixes this issue by ensuring assumption 2, i.e., it makes a copy of the callbacks dictionary before modifying it.
