### ISSUE TITLE
FloatRangeSlider fixes/enhancements

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#347]
@Arun-Verma noted a few improvements for FloatRangeSlider:
1. slider_color input (bug) - this only changes color of one of the two sliders
2. "readout" text should allow formatting
3. min & max values should be printed on top and bottom of scale
4. The title of the widget should align with vertical scale in vertical mode

**Comment by jasongrout** [comment]
Moving to 6.1

**Comment by jasongrout** [comment]
> slider_color input (bug) - this only changes color of one of the two sliders

Fixed by #1253.

**Comment by jasongrout** [comment]
Things seem to be aligned now:

<img width="433" alt="screen shot 2017-04-05 at 1 40 16 am" src="https://cloud.githubusercontent.com/assets/192614/24691358/ff65bc40-19a0-11e7-8ef5-82106abc791b.png">

**Comment by jasongrout** [comment]
> min & max values should be printed on top and bottom of scale

We'll move this to the larger discussion of slider style at #1134.

**Comment by solomonvimal** [comment]
would be nice to include a "linspace" option in the place of "step" for FloatRangeSlider

**Comment by vidartf** [comment]
@solomonvimal Please open a new issue for feature requests. Commenting on a closed issue is the best way to make sure your feature request gets forgotten.

**Comment by solomonvimal** [comment]
@vidartf thanks, done!
