### ISSUE TITLE
7.7.1 Release plans

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#3483]
We have a few backported bugfix PRs, so can release a 7.7.1.

Still to backport:

- #3470 (as well as #3485 if it is merged)
- #3476
- https://github.com/jupyter-widgets/ipywidgets/pull/3488

**Comment by vidartf** [comment]
7.7.1 is now released! https://pypi.org/project/ipywidgets/7.7.1/
