### ISSUE TITLE
module 'ipywidgets' has no attribute 'DatetimePicker'

### ISSUE THREAD

**Issue by James-O2** [jupyter-widgets/ipywidgets#3506]
## Description

cannot create a DatetimePicker widget as per the [documentation here](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#Datetime-picker)

## Reproduce

I am running the [jupyter datascience notebook docker image](https://hub.docker.com/r/jupyter/datascience-notebook) in a container on an AWS EC2 instance, with the default widget library installed.

I have attached a zip of the .ipynb file that recreates the error.

- JupyterLab version: 3.4.3
- Browser: Microsoft Edge Version 102.0.1245.44 (Official build) (64-bit)

![image](https://user-images.githubusercontent.com/103975000/176552106-49c3da96-78cf-4f8e-86a4-f7a2bcc02a8d.png)
[datetime error.zip](https://github.com/jupyter-widgets/ipywidgets/files/9014795/datetime.error.zip)

**Comment by jasongrout** [comment]
What version of ipywidgets do you have installed? It may be that the DateTimePicker is in the upcoming 8.0 release, not the current 7.x release.

**Comment by jasongrout** [comment]
Here is the documentation for the current stable release of ipywidgets: https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html 

(the documentation link you posted is for the upcoming 8.0 release, indicated by the "/latest/" in the URL)

**Comment by James-O2** [comment]
copy - I noticed the stable release doesn't have a DatetimePicker widget. So the error makes sense. When is the target date for the 8.0 version release?

**Comment by jasongrout** [comment]
We don't have a target date, but I'll be working on it tomorrow.
