### ISSUE TITLE
Interact retaining previous output until new output is loaded

### ISSUE THREAD

**Issue by KrishivVora** [jupyter-widgets/ipywidgets#3507]
I’m using interact for an interactive graph network visualization, where moving a slider recolors nodes. When I move the slider, the image disappears for a moment as the new graph is rendered and displayed, during which time the frame goes white.

Is there anyway to add an option to the interact function to retain the previous frame until the new frame has loaded, so I can move the slider smoothly without the constant flickering whenever the image updates? To be clear, I do want it to update every time the slider moves (so disabling continuous update is not the solution), but just to do so smoothly without the image going white between the previous and new output.

**Comment by jasongrout** [comment]
The interact function has logic to try to make seamless updates, but it only works for the first item displayed each time.

Some other tips are given in the documentation dealing with flickering displays: https://ipywidgets.readthedocs.io/en/stable/examples/Using%20Interact.html#Flickering-and-jumping-output

**Comment by jasongrout** [comment]
> Interact retaining previous output until new output is loaded

That is exactly what interact does (see the `wait=True` argument here: https://github.com/jupyter-widgets/ipywidgets/blob/7.x/ipywidgets/widgets/interaction.py#L253), but if it takes a fraction of a second for the browser to render the new output, that may still cause a visual flicker.
