### ISSUE TITLE
v7 widget_selectioncontainer.py needs deprecation warnings or fixes before v8 can be finalized...

### ISSUE THREAD

**Issue by gutow** [jupyter-widgets/ipywidgets#3520]
## Description
This stretch of code in v8 is incompatible with v7 compatible code:
widget_selectioncontainer.py lines 50 - 64.
```
    def set_title(self, index, title):
        """Sets the title of a container page.
        Parameters
        ----------
        index : int
            Index of the container page
        title : unicode
            New title
        """
        titles = list(self.titles)
        # for backwards compatibility with ipywidgets 7.x
        if title is None:
            title = ''
        titles[index]=title
        self.titles = tuple(titles)
```
Any version 7 compatible code that calls `container.set_title(indexnum,  titlestr)` will get an `IndexError: list assignment index out of range` from line 63 (`titles[index]=title`), if the calls are made immediately after the container is loaded with a list of objects. The tuple `titles` does not appear to get set to have a length = the number of sub objects, when the container is defined.

Thus I suggest that version 7 ipywidgets begin issuing a deprecation warning that the container.set_title() syntax will be replaced with specifying a titles tuple in the initial 8.0 release. I suspect the problem is related to @ dispatching. Naively, I would have checked in this code for `len(titles) == len(children)` and then appended empty strings to titles until they matched.

There is also the related issue that positional syntax for defining the objects in one of these containers `container([...])` is no longer supported only the keyword syntax `container(children=[...])`. As the keyword syntax has been the recommendation in the documentation at least since 7.6, this is not a huge concern. However, I wonder why that was acceptable without a deprecation warning? It is also not consistent with the base Box widget which does accept a positional list of children.

## Reproduce

This code running against ipywidgets v8.0.0rc1 in Jupyter Lab will reproduce the error.
```
from ipywidgets import widgets
tab_contents = ['P0', 'P1', 'P2', 'P3', 'P4']
children = [widgets.Text(description=name) for name in tab_contents]
tab = widgets.Tab()
tab.children = children
for i in range(len(children)):
    tab.set_title(i, str(i))
tab
```

I was testing [jupyter-Pandas-GUI](https://pypi.org/project/jupyter-Pandas-GUI/0.7.0rc0/) against Google Colab, where it did not work because Colab is using ipywidgets 8+. I then tested against ipywidgets 8.0.0rc1 in Juputer Lab to isolate the error.

## Expected behavior

Expect the titles to be set.
## Context

- ipywidgets version 8.0.0rc1
- Operating System and version:Linux Ubuntu 20.04lts
- Browser and version: Firefox and Chrome

### If using JupyterLab
- JupyterLab version: 3.4.3

<details><summary>Installed Labextensions</summary>
<pre>
JupyterLab v3.4.3
/home/jonathan/.local/share/jupyter/labextensions
        jupyterlab-datawidgets v7.0.0 enabled OK

/home/jonathan/.local/share/virtualenvs/JLabtst-Ix77i15z/share/jupyter/labextensions
        jupyterlab-drawio v0.9.0 enabled OK (python, jupyterlab-drawio)
        jupyterlab-plotly v5.9.0 enabled OK
        @jupyter-widgets/jupyterlab-manager v5.0.0-rc.1 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /home/jonathan/.local/share/virtualenvs/JLabtst-Ix77i15z/share/jupyter/lab
        @kptan86/jupyterlab-snippets-multimenus v0.1.4 enabled  X

   The following extension are outdated:
        @kptan86/jupyterlab-snippets-multimenus
</pre>
</details>

**Comment by jasongrout** [comment]
Thanks for the bug report. Indeed, there was an error where the logic for resetting titles was overridden. FIxed in #3522

**Comment by jasongrout** [comment]
> There is also the related issue that positional syntax for defining the objects in one of these containers `container([...])` is no longer supported only the keyword syntax `container(children=[...])`.

I'm a little surprised by this - I would expect the positional syntax to work, given it works with the box classes.

**Comment by gutow** [comment]
> > There is also the related issue that positional syntax for defining the objects in one of these containers `container([...])` is no longer supported only the keyword syntax `container(children=[...])`.
> 
> I'm a little surprised by this - I would expect the positional syntax to work, given it works with the box classes.

I was too, but could not figure out why this is the case. My code that used the positional syntax returned an error. I had to switch to the `children = ` syntax to reach get to the point where I encounted the error in `set_title()`.

**Comment by jasongrout** [comment]
> I was too, but could not figure out why this is the case.

It was because we incorrectly overrode the `__init__` function in Tabs. It works fine in Accordions, for example. I've fixed it in this PR, and added tests.

**Comment by gutow** [comment]
I can verify that both parts of this issue appear to be fixed when running in binder. I will await the next release candidate to check that it works with a plain vanilla `pip install`. I vote to roll this into v8.0.0. Although, I'm not sure I really get a vote. You can close this when it is merged and I will open another issue if I find things in the next release candidate.

**Comment by jasongrout** [comment]
Thanks for the review!
