### ISSUE TITLE
After installing ipywidgets, a warning appears when opening the notebook!

### ISSUE THREAD

**Issue by ghost** [jupyter-widgets/ipywidgets#3525]
Hello,
After installing the ipywidgets library, I restart and open a new notebook to get the following warning,

`[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control`
`[IPKernelApp] WARNING | No such comm: 8442000c-e99a-4ec4-854a-a3fc4580577f`

What caused this?

**Comment by jasongrout** [comment]
This message is harmless. It's a message noting that ipywidgets tried to communicate to the kernel to shortcut a process, but ipywidgets has a fallback if this communication does not succeed.

**Comment by hankgreurrayosin** [comment]
Okay,thank you !
