### ISSUE TITLE
widgets persist in memory despite being closed and deleted

### ISSUE THREAD

**Issue by rkishony** [jupyter-widgets/ipywidgets#3544]
## Description

It seems that there is a memory leak: widgets do not get garbage collected even when closed and when all references are deleted.

## Reproduce

In Jupyet lab

cell 1:
```python
from ipywidgets import IntSlider
from weakref import ref

w = IntSlider(4)
w_ref = ref(w)
w
```

a slider appears (as expected).

cell 2:
```python
w.close()
```

above slider closes (as expected).

cell 3:
```python
del w  # now we have no references to the slider. it should get deleted.
```

cell 4:
```python
w_ref()  # --> we get `IntSlider(value=4)`, indicating that the slider is still somehow alive.
```

## Expected behavior

Widgets should be deleted when they are closed and there is no reference to them.

## Context

- ipywidgets version: 7.7.1
- Operating System and version: Mac OS
- Browser and version: Chrome

**Comment by vidartf** [comment]
Thanks for the report. Note that IPython by default keeps a reference to your previous cell outputs. They are typically available in `Out[N]` (where `N` is an integer index) and the last three outputs are in `_`, `__` and `___`.

Ways to disable this are typically via config: `c.InteractiveShell.cache_size = 0`. There might also have been another setting needed (don't remember off the top of my head), but this should at least help you get started.

**Comment by jasongrout** [comment]
We've discussed this more over at https://github.com/jupyter-widgets/ipywidgets/issues/1345. Let's move any further discussion over there so we have it consolidated in one place. Thanks!

**Comment by rkishony** [comment]
very helpful - much thanks!
