### ISSUE TITLE
ipyaggrid has stopped working because it's no more available in unpkg.com

### ISSUE THREAD

**Issue by rajdeepyadav** [jupyter-widgets/ipywidgets#3550]
I am using in Jupyter notebook. Till yesterday it was rendering the grid.

Today it is complaining "ipyaggrid.js" is not present earlier it used be at this location https://unpkg.com/ipyaggrid@0.2.2/dist/index.js but it's no more available. 

Console error - 
Failed to load model class 'AgGridModel' from module 'ipyaggrid'
TypeError: Cannot read properties of undefined (reading 'AgGridModel')
    at https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:16:586623
    at async xc.loadModelClass (https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:16:585036)
    at async xc._make_model (https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js:16:581529)

Old structure
![Screen Shot 2022-08-18 at 6 56 58 PM](https://user-images.githubusercontent.com/23441305/185509404-23698e4a-86ed-41c1-8aaf-76879d818c80.png)

New Structure 
![Screen Shot 2022-08-18 at 6 57 14 PM](https://user-images.githubusercontent.com/23441305/185509455-cfefe8d9-fc30-4216-85c8-a753a1c02abe.png)

As, you can see it clearly missing that file. I tried to provide ipyaggrid.js locally but after that also it is giving me 

embed-amd.js:16 TypeError: o._deserialize_state is not a function
    at xc._make_model (embed-amd.js:16:581816)
![Screen Shot 2022-08-18 at 7 00 50 PM](https://user-images.githubusercontent.com/23441305/185509647-0b6f3738-1f4b-45ef-b78d-b29a83500485.png)

**Comment by vidartf** [comment]
@rajdeepyadav Just to confirm, can you share which version of ipywidgets you are using? Also, I see the content loading on the CDN link you provided: https://unpkg.com/ipyaggrid@0.2.2/dist/index.js

**Comment by rajdeepyadav** [comment]
I know the content is loading but do you see the structure got change. If you compare old structure with new one. 
In the the screenshot of new structure "index.js" is not present.

I am not using ipywidgets but I am using Ipyaggrid latest version 0.2.2. which pulls  ipywidgets.

**Comment by jasongrout** [comment]
Can you give us some example code reproducing the issue?

We just released ipywidgets 8 yesterday, so I'd like to investigate if that is causing the issue.

**Comment by rajdeepyadav** [comment]
<img width="861" alt="Screen Shot 2022-08-19 at 12 36 12 PM" src="https://user-images.githubusercontent.com/23441305/185666078-72c53d03-129f-4b4b-8129-bd4f09594464.png">

This the error I am gettting.

**Comment by jasongrout** [comment]
Thanks. I'd like to try to reproduce the issue. What I need are:

* installation instructions to set up a clean environment
* code to generate the error

**Comment by jasongrout** [comment]
Can you try with ipywidgets 7.7.2? We just published it a few hours ago with a fix that may help with this issue.

**Comment by rajdeepyadav** [comment]
I can try, but i think the main issue was in folder structure of unpkg.com which got changed.
Luckily, I had the old embed-amd.js and ipyaggrid.js. I updated the script to the point to the old js and it worked. 
So, main issue is in embed-amd.js.

**Comment by jasongrout** [comment]
If you can help us reproduce the issue, I can look at this further.

**Comment by jasongrout** [comment]
For context, we did publish a new version of the html manager yesterday, and I'd like to look into if that is causing issues and why.

**Comment by rajdeepyadav** [comment]
May be you can just revert the version of "embed-amd.js" and put the "ipyaggrid.js" at the same folder under unpkg.com, then it should work. 
You can compare the embed-amd.js with the old version.

**Comment by jasongrout** [comment]
We (here at ipywidgets) don't develop or distribute ipyaggrid.js, and have no control over it.

There have been lots of changes to the embed-amd.js script in the latest version of ipywidgets. Again, if I can reproduce what you're seeing, I have a chance of figuring out the issue.

**Comment by rajdeepyadav** [comment]
Hey Thanks, It's fine I pointed to the old version of embed-amd.js instead of downloading it from internet and it worked for me. You can ignore other things.
[embed-amd.js.zip](https://github.com/jupyter-widgets/ipywidgets/files/9385586/embed-amd.js.zip)

You can compare this old file with new one.

html_grid = metric_grid.export_html(build=True)
x = html_grid.replace("https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js", "../../embed-amd.js")
return x

Sorry, I cannot share my code. It's company policy. All I can say it was giving some deserialization issue for the grid.

**Comment by jasongrout** [comment]
> x = html_grid.replace("https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js", "../../embed-amd.js")

the `@*` means get the latest version. You can also just give a specific version or semver range: `https://unpkg.com/@jupyter-widgets/html-manager@^0.20/dist/embed-amd.js`, for example. That's what we do in ipywidgets when we export html - we make sure we load a version of the html manager that is compatible with the ipywidgets you are using.

**Comment by jasongrout** [comment]
(So to be clear, instead of using `https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js`, you should be more specific about the version of html-manager you want: `https://unpkg.com/@jupyter-widgets/html-manager@^0.20/dist/embed-amd.js`)

**Comment by rajdeepyadav** [comment]
Then it's the issue with ipyaggrid because when I do "grid.export_html(build=True)" library automatically adds all the required online scripts and instead of adding/specifying compatible version they add the script like following - 


<script 
  src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js" 
  integrity="sha256-Ae2Vz/4ePdIu6ZyI/5ZGsYnb+m0JlOmKPjt6XZ9JJkA=" 
  crossorigin="anonymous">
</script>


**<script 
  src="https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js" 
  crossorigin="anonymous">
</script>**

<script type="application/vnd.jupyter.widget-state+json">

Can you tell me where to check or what was the version of embed-amd.js day before yesterday (on Aug 17th) ?

**Comment by jasongrout** [comment]
It was 0.20.2, which you can get to from using `https://unpkg.com/@jupyter-widgets/html-manager@^0.20/dist/embed-amd.js`

**Comment by jasongrout** [comment]
Looks like there is an issue in ipyaggrid about compatibility with ipywidgets 8: https://gitlab.com/DGothrek/ipyaggrid/-/issues/55
