### ISSUE TITLE
Note in migration guide the privatization of .widgets and .widget_types

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#3562]
### Problem

The migration guide does not cover the privatization of `.widgets` and `.widget_types`, as noted [here](https://github.com/jupyter-widgets/ipywidgets/pull/3122#issuecomment-1222396020).

### Suggested Improvement

Put a note in the user migration guide that covers these usecases and provides a shim for accessing the variables in ipywidgets 7 and 8 if needed (though note that the variable is now private in ipywidgets 8, so references are discouraged).

**Comment by maartenbreddels** [comment]
See also how I fix this in react-ipywidgets:
https://github.com/widgetti/react-ipywidgets/commit/6fb07845d143f02165c11405ed5bec20391b09c5
