### ISSUE TITLE
Can not import qgrid - TypeError: register() missing 1 required positional argument: 'widget'

### ISSUE THREAD

**Issue by buenohernandez** [jupyter-widgets/ipywidgets#3563]
Hi, I just started a fresh env on my pycharm and when I try to import qgrid I get:

>>> import qgrid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\site-packages\qgrid\__init__.py", line 3, in <module>
    from .grid import (
  File "C:\Python37\site-packages\qgrid\grid.py", line 524, in <module>  
    @widgets.register()
TypeError: register() missing 1 required positional argument: 'widget'

I saw this issue: https://github.com/jupyter-widgets/ipywidgets/issues/3031, but I don't think it applies to me.

Python 3.7.9 
qgrid==1.3.1

What do I do?

**Comment by jasongrout** [comment]
Did you install ipywidgets 7 or ipywidgets 8?

My guess is that your fresh environment pulled in ipywidgets 8, but qgrid is not compatible with ipywidgets 8 yet. You may be able to just specify ipywidgets 7 in your environment.

**Comment by jasongrout** [comment]
(or contribute changes to qgrid to make it compatible with ipywidgets 8, like you suggest)

**Comment by buenohernandez** [comment]
I installed  ipywidgets==7 and it worked!!!!!
Thank you very much @jasongrout :)

**Comment by jasongrout** [comment]
> I installed ipywidgets==7 and it worked!!!!!

You'll probably want `pip install 'ipywidgets~=7.0'` to get 7.7.2, not 7.0.0, which is really old at this point.

**Comment by ErmakovSemen** [comment]
I have the same problem but installing ipywidgets 7 did not help me (( 
<img width="915" alt="Screenshot 2023-09-19 at 11 09 36" src="https://github.com/jupyter-widgets/ipywidgets/assets/101561868/29f00683-3a8a-4169-8141-11289475ab56">

**Comment by janfrederik** [comment]
> I have the same problem but installing ipywidgets 7 did not help me 

Did you restart the jupyter kernel after doing the pip install?

**Comment by jmmelen** [comment]
Another option is to use "Itables" instead.  No hassles
