### ISSUE TITLE
Installing `jupyterlab_widgets` in the JupyterLab environment and `ipywidgets` inside the kernel is not enough: `Error displaying widget: model not found`

### ISSUE THREAD

**Issue by astrojuanlu** [jupyter-widgets/ipywidgets#3577]
## Description

In Orchest we are using https://github.com/jupyter-server/enterprise_gateway/ to separate the JupyterLab environment from the kernel environment.

We want interactive widgets to work by default, but even if we're supposedly following these instructions:

https://ipywidgets.readthedocs.io/en/stable/user_install.html#installing-in-jupyterlab-3-x

> If JupyterLab and the IPython kernel are installed in different environments (for example, separate environments are providing different Python kernels), then the installation requires two steps:
> 
> 1. Install the jupyterlab_widgets package in the environment containing JupyterLab.
> 2. Install ipywidgets in each kernel’s environment that will use ipywidgets.

We still observe that, even though `import ipywidgets` work, attempting to use them results in

```
Error displaying widget: model not found
```

![image](https://user-images.githubusercontent.com/316517/187228731-8dba8478-2feb-48cb-9c06-35b6cbf9229b.png)

On the other hand, if we `pip install ipywidgets` in the JupyterLab environment, then everything works normally.

## Reproduce

I have no idea how to reproduce this in a few simple steps that don't involve Orchest. I hope the setup is clear though, but if more clarification is needed, I'd be happy to work with the developers.

## Expected behavior

Following the documentation results in a working ipywidgets installation.

## Context

JupyterLab 3.4 and ipywidgets 8.0.1, latest Firefox, latest Linux Mint.

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/opt/conda/bin
	/opt/conda/condabin
	/opt/conda/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin

sys.path:
	/opt/conda/bin
	/opt/conda/lib/python39.zip
	/opt/conda/lib/python3.9
	/opt/conda/lib/python3.9/lib-dynload
	/opt/conda/lib/python3.9/site-packages
	/orchest/orchest-sdk/python

sys.executable:
	/opt/conda/bin/python

sys.version:
	3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11) 
	[GCC 9.4.0]

platform.platform():
	Linux-5.15.0-46-generic-x86_64-with-glibc2.31

which -a jupyter:
	/opt/conda/bin/jupyter
	/opt/conda/bin/jupyter

pip list:
	Package                       Version   Editable project location
	----------------------------- --------- ---------------------------
	alembic                       1.7.6
	anyio                         3.5.0
	argon2-cffi                   21.3.0
	argon2-cffi-bindings          21.2.0
	asttokens                     2.0.5
	async-generator               1.10
	attrs                         21.4.0
	Babel                         2.9.1
	backcall                      0.2.0
	backports.functools-lru-cache 1.6.4
	bleach                        4.1.0
	blinker                       1.4
	brotlipy                      0.7.0
	certifi                       2022.6.15
	certipy                       0.1.3
	cffi                          1.15.0
	charset-normalizer            2.0.12
	colorama                      0.4.4
	conda                         4.11.0
	conda-package-handling        1.7.3
	cryptography                  36.0.1
	debugpy                       1.5.1
	decorator                     5.1.1
	defusedxml                    0.7.1
	entrypoints                   0.4
	executing                     0.8.3
	flit_core                     3.7.1
	future                        0.18.2
	greenlet                      1.1.2
	idna                          3.3
	importlib-metadata            4.11.2
	importlib-resources           5.4.0
	ipykernel                     6.9.1
	ipython                       8.1.1
	ipython-genutils              0.2.0
	ipywidgets                    8.0.1
	jedi                          0.18.1
	Jinja2                        3.0.3
	json5                         0.9.5
	jsonschema                    4.4.0
	jupyter-client                6.1.12
	jupyter-core                  4.9.2
	jupyter-server                1.13.5
	jupyter-telemetry             0.1.0
	jupyterhub                    2.2.0
	jupyterlab                    3.3.0
	jupyterlab-pygments           0.1.2
	jupyterlab-server             2.10.3
	jupyterlab-widgets            3.0.2
	libmambapy                    0.22.1
	Mako                          1.1.6
	mamba                         0.22.1
	MarkupSafe                    2.1.0
	matplotlib-inline             0.1.3
	mistune                       0.8.4
	nbclassic                     0.3.6
	nbclient                      0.5.12
	nbconvert                     6.4.2
	nbformat                      5.1.3
	nest-asyncio                  1.5.4
	notebook                      6.4.8
	notebook-shim                 0.1.0
	numpy                         1.23.2
	oauthlib                      3.2.0
	orchest                       0.3.10    /orchest/orchest-sdk/python
	packaging                     21.3
	pamela                        1.0.0
	pandocfilters                 1.5.0
	parso                         0.8.3
	pexpect                       4.8.0
	pickleshare                   0.7.5
	pip                           22.0.4
	prometheus-client             0.13.1
	prompt-toolkit                3.0.27
	psutil                        5.9.0
	ptyprocess                    0.7.0
	pure-eval                     0.2.2
	pyarrow                       7.0.0
	pycosat                       0.6.3
	pycparser                     2.21
	pycryptodomex                 3.15.0
	pycurl                        7.44.1
	Pygments                      2.11.2
	PyJWT                         2.3.0
	pyOpenSSL                     22.0.0
	pyparsing                     3.0.7
	pyrsistent                    0.18.1
	PySocks                       1.7.1
	python-dateutil               2.8.2
	python-json-logger            2.0.1
	pytz                          2021.3
	pyzmq                         22.3.0
	requests                      2.27.1
	ruamel.yaml                   0.17.21
	ruamel.yaml.clib              0.2.6
	ruamel-yaml-conda             0.15.80
	Send2Trash                    1.8.0
	setuptools                    60.9.3
	six                           1.16.0
	sniffio                       1.2.0
	SQLAlchemy                    1.4.32
	stack-data                    0.2.0
	terminado                     0.13.3
	testpath                      0.6.0
	tornado                       6.1
	tqdm                          4.63.0
	traitlets                     5.1.1
	urllib3                       1.26.8
	wcwidth                       0.2.5
	webencodings                  0.5.1
	websocket-client              1.3.1
	wheel                         0.37.1
	widgetsnbextension            4.0.2
	zipp                          3.7.0

conda list:
	# packages in environment at /opt/conda:
	#
	# Name                    Version                   Build  Channel
	_libgcc_mutex             0.1                 conda_forge    conda-forge
	_openmp_mutex             4.5                       1_gnu    conda-forge
	alembic                   1.7.6              pyhd8ed1ab_0    conda-forge
	anyio                     3.5.0            py39hf3d152e_0    conda-forge
	argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
	argon2-cffi-bindings      21.2.0           py39h3811e60_1    conda-forge
	asttokens                 2.0.5              pyhd8ed1ab_0    conda-forge
	async_generator           1.10                       py_0    conda-forge
	attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
	babel                     2.9.1              pyh44b312d_0    conda-forge
	backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
	backports                 1.0                        py_2    conda-forge
	backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
	bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
	blinker                   1.4                        py_1    conda-forge
	brotlipy                  0.7.0           py39h3811e60_1003    conda-forge
	bzip2                     1.0.8                h7f98852_4    conda-forge
	c-ares                    1.18.1               h7f98852_0    conda-forge
	ca-certificates           2022.6.15            ha878542_0    conda-forge
	certifi                   2022.6.15          pyhd8ed1ab_1    conda-forge
	certipy                   0.1.3                      py_0    conda-forge
	cffi                      1.15.0           py39h4bc2ebd_0    conda-forge
	charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
	colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
	conda                     4.11.0           py39hf3d152e_1    conda-forge
	conda-package-handling    1.7.3            py39h3811e60_1    conda-forge
	configurable-http-proxy   4.5.1           node17_h7e777a6_1    conda-forge
	cryptography              36.0.1           py39h95dcef6_0    conda-forge
	debugpy                   1.5.1            py39he80948d_0    conda-forge
	decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
	defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
	entrypoints               0.4                pyhd8ed1ab_0    conda-forge
	executing                 0.8.3              pyhd8ed1ab_0    conda-forge
	flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
	future                    0.18.2           py39hf3d152e_5    conda-forge
	gmp                       6.2.1                h58526e2_0    conda-forge
	greenlet                  1.1.2            py39he80948d_1    conda-forge
	icu                       69.1                 h9c3ff4c_0    conda-forge
	idna                      3.3                pyhd8ed1ab_0    conda-forge
	importlib-metadata        4.11.2           py39hf3d152e_0    conda-forge
	importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
	ipykernel                 6.9.1            py39hef51801_0    conda-forge
	ipython                   8.1.1            py39hf3d152e_0    conda-forge
	ipython_genutils          0.2.0                      py_1    conda-forge
	ipywidgets                8.0.1                    pypi_0    pypi
	jedi                      0.18.1           py39hf3d152e_0    conda-forge
	jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
	json5                     0.9.5              pyh9f0ad1d_0    conda-forge
	jsonschema                4.4.0              pyhd8ed1ab_0    conda-forge
	jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
	jupyter_core              4.9.2            py39hf3d152e_0    conda-forge
	jupyter_server            1.13.5             pyhd8ed1ab_1    conda-forge
	jupyter_telemetry         0.1.0              pyhd8ed1ab_1    conda-forge
	jupyterhub                2.2.0                hd8ed1ab_0    conda-forge
	jupyterhub-base           2.2.0              pyhd8ed1ab_0    conda-forge
	jupyterlab                3.3.0              pyhd8ed1ab_0    conda-forge
	jupyterlab-widgets        3.0.2                    pypi_0    pypi
	jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
	jupyterlab_server         2.10.3             pyhd8ed1ab_0    conda-forge
	keyutils                  1.6.1                h166bdaf_0    conda-forge
	krb5                      1.19.2               h3790be6_4    conda-forge
	ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
	libarchive                3.5.2                hccf745f_1    conda-forge
	libcurl                   7.82.0               h7bff187_0    conda-forge
	libedit                   3.1.20191231         he28a2e2_2    conda-forge
	libev                     4.33                 h516909a_1    conda-forge
	libffi                    3.4.2                h7f98852_5    conda-forge
	libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
	libgomp                   12.1.0              h8d9b700_16    conda-forge
	libiconv                  1.16                 h516909a_0    conda-forge
	libmamba                  0.22.1               h9c208ef_0    conda-forge
	libmambapy                0.22.1           py39h3216e65_0    conda-forge
	libnghttp2                1.47.0               h727a467_0    conda-forge
	libnsl                    2.0.0                h7f98852_0    conda-forge
	libsodium                 1.0.18               h36c2ea0_1    conda-forge
	libsolv                   0.7.19               h780b84a_5    conda-forge
	libssh2                   1.10.0               ha56f1ee_2    conda-forge
	libstdcxx-ng              11.2.0              he4da1e4_13    conda-forge
	libuuid                   2.32.1            h7f98852_1000    conda-forge
	libuv                     1.43.0               h7f98852_0    conda-forge
	libxml2                   2.9.12               h885dcf4_1    conda-forge
	libzlib                   1.2.11            h36c2ea0_1013    conda-forge
	lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
	lzo                       2.10              h516909a_1000    conda-forge
	mako                      1.1.6              pyhd8ed1ab_0    conda-forge
	mamba                     0.22.1           py39hfa8f2c8_0    conda-forge
	markupsafe                2.1.0            py39hb9d737c_1    conda-forge
	matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
	mistune                   0.8.4           py39h3811e60_1005    conda-forge
	nbclassic                 0.3.6              pyhd8ed1ab_0    conda-forge
	nbclient                  0.5.12             pyhd8ed1ab_0    conda-forge
	nbconvert                 6.4.2            py39hf3d152e_0    conda-forge
	nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
	ncurses                   6.3                  h9c3ff4c_0    conda-forge
	nest-asyncio              1.5.4              pyhd8ed1ab_0    conda-forge
	nodejs                    17.4.0               h8ca31f7_0    conda-forge
	notebook                  6.4.8              pyha770c72_0    conda-forge
	notebook-shim             0.1.0              pyhd8ed1ab_0    conda-forge
	numpy                     1.23.2                   pypi_0    pypi
	oauthlib                  3.2.0              pyhd8ed1ab_0    conda-forge
	openssl                   1.1.1q               h166bdaf_0    conda-forge
	orchest                   0.3.10                    dev_0    <develop>
	packaging                 21.3               pyhd8ed1ab_0    conda-forge
	pamela                    1.0.0                      py_0    conda-forge
	pandoc                    2.17.1.1             ha770c72_0    conda-forge
	pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
	parso                     0.8.3              pyhd8ed1ab_0    conda-forge
	pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
	pickleshare               0.7.5                   py_1003    conda-forge
	pip                       22.0.4             pyhd8ed1ab_0    conda-forge
	prometheus_client         0.13.1             pyhd8ed1ab_0    conda-forge
	prompt-toolkit            3.0.27             pyha770c72_0    conda-forge
	psutil                    5.9.0            py39h3811e60_0    conda-forge
	ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
	pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
	pyarrow                   7.0.0                    pypi_0    pypi
	pybind11-abi              4                    hd8ed1ab_3    conda-forge
	pycosat                   0.6.3           py39h3811e60_1009    conda-forge
	pycparser                 2.21               pyhd8ed1ab_0    conda-forge
	pycryptodomex             3.15.0           py39hb9d737c_0    conda-forge
	pycurl                    7.44.1           py39h72e3413_1    conda-forge
	pygments                  2.11.2             pyhd8ed1ab_0    conda-forge
	pyjwt                     2.3.0              pyhd8ed1ab_1    conda-forge
	pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
	pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
	pyrsistent                0.18.1           py39h3811e60_0    conda-forge
	pysocks                   1.7.1            py39hf3d152e_4    conda-forge
	python                    3.9.10          h85951f9_2_cpython    conda-forge
	python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
	python-json-logger        2.0.1              pyh9f0ad1d_0    conda-forge
	python_abi                3.9                      2_cp39    conda-forge
	pytz                      2021.3             pyhd8ed1ab_0    conda-forge
	pyzmq                     22.3.0           py39h37b5a0c_1    conda-forge
	readline                  8.1                  h46c0cb4_0    conda-forge
	reproc                    14.2.3               h7f98852_0    conda-forge
	reproc-cpp                14.2.3               h9c3ff4c_0    conda-forge
	requests                  2.27.1             pyhd8ed1ab_0    conda-forge
	ruamel.yaml               0.17.21          py39h3811e60_0    conda-forge
	ruamel.yaml.clib          0.2.6            py39h3811e60_0    conda-forge
	ruamel_yaml               0.15.80         py39h3811e60_1006    conda-forge
	send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
	setuptools                60.9.3           py39hf3d152e_0    conda-forge
	six                       1.16.0             pyh6c4a22f_0    conda-forge
	sniffio                   1.2.0            py39hf3d152e_2    conda-forge
	sqlalchemy                1.4.32           py39hb9d737c_0    conda-forge
	sqlite                    3.37.0               h9cd32fc_0    conda-forge
	stack_data                0.2.0              pyhd8ed1ab_0    conda-forge
	terminado                 0.13.3           py39hf3d152e_0    conda-forge
	testpath                  0.6.0              pyhd8ed1ab_0    conda-forge
	tk                        8.6.12               h27826a3_0    conda-forge
	tornado                   6.1              py39h3811e60_2    conda-forge
	tqdm                      4.63.0             pyhd8ed1ab_0    conda-forge
	traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
	tzdata                    2021e                he74cb21_0    conda-forge
	urllib3                   1.26.8             pyhd8ed1ab_1    conda-forge
	wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
	webencodings              0.5.1                      py_1    conda-forge
	websocket-client          1.3.1              pyhd8ed1ab_0    conda-forge
	wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
	widgetsnbextension        4.0.2                    pypi_0    pypi
	xz                        5.2.5                h516909a_1    conda-forge
	yaml                      0.2.5                h7f98852_2    conda-forge
	yaml-cpp                  0.6.3                he1b5a44_4    conda-forge
	zeromq                    4.3.4                h9c3ff4c_1    conda-forge
	zipp                      3.7.0              pyhd8ed1ab_1    conda-forge
	zlib                      1.2.11            h36c2ea0_1013    conda-forge
	zstd                      1.5.2                ha95c52a_0    conda-forge

conda env:
	name: base
	channels:
	  - conda-forge
	dependencies:
	  - _libgcc_mutex=0.1=conda_forge
	  - _openmp_mutex=4.5=1_gnu
	  - alembic=1.7.6=pyhd8ed1ab_0
	  - anyio=3.5.0=py39hf3d152e_0
	  - argon2-cffi=21.3.0=pyhd8ed1ab_0
	  - argon2-cffi-bindings=21.2.0=py39h3811e60_1
	  - asttokens=2.0.5=pyhd8ed1ab_0
	  - async_generator=1.10=py_0
	  - attrs=21.4.0=pyhd8ed1ab_0
	  - babel=2.9.1=pyh44b312d_0
	  - backcall=0.2.0=pyh9f0ad1d_0
	  - backports=1.0=py_2
	  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
	  - bleach=4.1.0=pyhd8ed1ab_0
	  - blinker=1.4=py_1
	  - brotlipy=0.7.0=py39h3811e60_1003
	  - bzip2=1.0.8=h7f98852_4
	  - c-ares=1.18.1=h7f98852_0
	  - ca-certificates=2022.6.15=ha878542_0
	  - certifi=2022.6.15=pyhd8ed1ab_1
	  - certipy=0.1.3=py_0
	  - cffi=1.15.0=py39h4bc2ebd_0
	  - charset-normalizer=2.0.12=pyhd8ed1ab_0
	  - colorama=0.4.4=pyh9f0ad1d_0
	  - conda=4.11.0=py39hf3d152e_1
	  - conda-package-handling=1.7.3=py39h3811e60_1
	  - configurable-http-proxy=4.5.1=node17_h7e777a6_1
	  - cryptography=36.0.1=py39h95dcef6_0
	  - debugpy=1.5.1=py39he80948d_0
	  - decorator=5.1.1=pyhd8ed1ab_0
	  - defusedxml=0.7.1=pyhd8ed1ab_0
	  - entrypoints=0.4=pyhd8ed1ab_0
	  - executing=0.8.3=pyhd8ed1ab_0
	  - flit-core=3.7.1=pyhd8ed1ab_0
	  - future=0.18.2=py39hf3d152e_5
	  - gmp=6.2.1=h58526e2_0
	  - greenlet=1.1.2=py39he80948d_1
	  - icu=69.1=h9c3ff4c_0
	  - idna=3.3=pyhd8ed1ab_0
	  - importlib-metadata=4.11.2=py39hf3d152e_0
	  - importlib_resources=5.4.0=pyhd8ed1ab_0
	  - ipykernel=6.9.1=py39hef51801_0
	  - ipython=8.1.1=py39hf3d152e_0
	  - ipython_genutils=0.2.0=py_1
	  - jedi=0.18.1=py39hf3d152e_0
	  - jinja2=3.0.3=pyhd8ed1ab_0
	  - json5=0.9.5=pyh9f0ad1d_0
	  - jsonschema=4.4.0=pyhd8ed1ab_0
	  - jupyter_client=6.1.12=pyhd8ed1ab_0
	  - jupyter_core=4.9.2=py39hf3d152e_0
	  - jupyter_server=1.13.5=pyhd8ed1ab_1
	  - jupyter_telemetry=0.1.0=pyhd8ed1ab_1
	  - jupyterhub=2.2.0=hd8ed1ab_0
	  - jupyterhub-base=2.2.0=pyhd8ed1ab_0
	  - jupyterlab=3.3.0=pyhd8ed1ab_0
	  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
	  - jupyterlab_server=2.10.3=pyhd8ed1ab_0
	  - keyutils=1.6.1=h166bdaf_0
	  - krb5=1.19.2=h3790be6_4
	  - ld_impl_linux-64=2.36.1=hea4e1c9_2
	  - libarchive=3.5.2=hccf745f_1
	  - libcurl=7.82.0=h7bff187_0
	  - libedit=3.1.20191231=he28a2e2_2
	  - libev=4.33=h516909a_1
	  - libffi=3.4.2=h7f98852_5
	  - libgcc-ng=12.1.0=h8d9b700_16
	  - libgomp=12.1.0=h8d9b700_16
	  - libiconv=1.16=h516909a_0
	  - libmamba=0.22.1=h9c208ef_0
	  - libmambapy=0.22.1=py39h3216e65_0
	  - libnghttp2=1.47.0=h727a467_0
	  - libnsl=2.0.0=h7f98852_0
	  - libsodium=1.0.18=h36c2ea0_1
	  - libsolv=0.7.19=h780b84a_5
	  - libssh2=1.10.0=ha56f1ee_2
	  - libstdcxx-ng=11.2.0=he4da1e4_13
	  - libuuid=2.32.1=h7f98852_1000
	  - libuv=1.43.0=h7f98852_0
	  - libxml2=2.9.12=h885dcf4_1
	  - libzlib=1.2.11=h36c2ea0_1013
	  - lz4-c=1.9.3=h9c3ff4c_1
	  - lzo=2.10=h516909a_1000
	  - mako=1.1.6=pyhd8ed1ab_0
	  - mamba=0.22.1=py39hfa8f2c8_0
	  - markupsafe=2.1.0=py39hb9d737c_1
	  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
	  - mistune=0.8.4=py39h3811e60_1005
	  - nbclassic=0.3.6=pyhd8ed1ab_0
	  - nbclient=0.5.12=pyhd8ed1ab_0
	  - nbconvert=6.4.2=py39hf3d152e_0
	  - nbformat=5.1.3=pyhd8ed1ab_0
	  - ncurses=6.3=h9c3ff4c_0
	  - nest-asyncio=1.5.4=pyhd8ed1ab_0
	  - nodejs=17.4.0=h8ca31f7_0
	  - notebook=6.4.8=pyha770c72_0
	  - notebook-shim=0.1.0=pyhd8ed1ab_0
	  - oauthlib=3.2.0=pyhd8ed1ab_0
	  - openssl=1.1.1q=h166bdaf_0
	  - packaging=21.3=pyhd8ed1ab_0
	  - pamela=1.0.0=py_0
	  - pandoc=2.17.1.1=ha770c72_0
	  - pandocfilters=1.5.0=pyhd8ed1ab_0
	  - parso=0.8.3=pyhd8ed1ab_0
	  - pexpect=4.8.0=pyh9f0ad1d_2
	  - pickleshare=0.7.5=py_1003
	  - pip=22.0.4=pyhd8ed1ab_0
	  - prometheus_client=0.13.1=pyhd8ed1ab_0
	  - prompt-toolkit=3.0.27=pyha770c72_0
	  - psutil=5.9.0=py39h3811e60_0
	  - ptyprocess=0.7.0=pyhd3deb0d_0
	  - pure_eval=0.2.2=pyhd8ed1ab_0
	  - pybind11-abi=4=hd8ed1ab_3
	  - pycosat=0.6.3=py39h3811e60_1009
	  - pycparser=2.21=pyhd8ed1ab_0
	  - pycryptodomex=3.15.0=py39hb9d737c_0
	  - pycurl=7.44.1=py39h72e3413_1
	  - pygments=2.11.2=pyhd8ed1ab_0
	  - pyjwt=2.3.0=pyhd8ed1ab_1
	  - pyopenssl=22.0.0=pyhd8ed1ab_0
	  - pyparsing=3.0.7=pyhd8ed1ab_0
	  - pyrsistent=0.18.1=py39h3811e60_0
	  - pysocks=1.7.1=py39hf3d152e_4
	  - python=3.9.10=h85951f9_2_cpython
	  - python-dateutil=2.8.2=pyhd8ed1ab_0
	  - python-json-logger=2.0.1=pyh9f0ad1d_0
	  - python_abi=3.9=2_cp39
	  - pytz=2021.3=pyhd8ed1ab_0
	  - pyzmq=22.3.0=py39h37b5a0c_1
	  - readline=8.1=h46c0cb4_0
	  - reproc=14.2.3=h7f98852_0
	  - reproc-cpp=14.2.3=h9c3ff4c_0
	  - requests=2.27.1=pyhd8ed1ab_0
	  - ruamel.yaml=0.17.21=py39h3811e60_0
	  - ruamel.yaml.clib=0.2.6=py39h3811e60_0
	  - ruamel_yaml=0.15.80=py39h3811e60_1006
	  - send2trash=1.8.0=pyhd8ed1ab_0
	  - setuptools=60.9.3=py39hf3d152e_0
	  - six=1.16.0=pyh6c4a22f_0
	  - sniffio=1.2.0=py39hf3d152e_2
	  - sqlalchemy=1.4.32=py39hb9d737c_0
	  - sqlite=3.37.0=h9cd32fc_0
	  - stack_data=0.2.0=pyhd8ed1ab_0
	  - terminado=0.13.3=py39hf3d152e_0
	  - testpath=0.6.0=pyhd8ed1ab_0
	  - tk=8.6.12=h27826a3_0
	  - tornado=6.1=py39h3811e60_2
	  - tqdm=4.63.0=pyhd8ed1ab_0
	  - traitlets=5.1.1=pyhd8ed1ab_0
	  - tzdata=2021e=he74cb21_0
	  - urllib3=1.26.8=pyhd8ed1ab_1
	  - wcwidth=0.2.5=pyh9f0ad1d_2
	  - webencodings=0.5.1=py_1
	  - websocket-client=1.3.1=pyhd8ed1ab_0
	  - wheel=0.37.1=pyhd8ed1ab_0
	  - xz=5.2.5=h516909a_1
	  - yaml=0.2.5=h7f98852_2
	  - yaml-cpp=0.6.3=he1b5a44_4
	  - zeromq=4.3.4=h9c3ff4c_1
	  - zipp=3.7.0=pyhd8ed1ab_1
	  - zlib=1.2.11=h36c2ea0_1013
	  - zstd=1.5.2=ha95c52a_0
	  - pip:
	    - ipywidgets==8.0.1
	    - jupyterlab-widgets==3.0.2
	    - numpy==1.23.2
	    - pyarrow==7.0.0
	    - widgetsnbextension==4.0.2
	prefix: /opt/conda
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` (or `jupyter notebook` if you use notebook) here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
Various "Error: Could not create a model." and "Error: Module @jupyter-widgets/controls, semver range ^2.0.0 is not registered as a widget module"
</details>

### If using JupyterLab
- JupyterLab version: 3.4.2

<details><summary>Installed Labextensions</summary>
<pre>
JupyterLab v3.3.0
/opt/conda/share/jupyter/labextensions
        @jupyter-widgets/jupyterlab-manager v5.0.2 enabled OK (python, jupyterlab_widgets)
</pre>
</details>

**Comment by jasongrout** [comment]
Note that we recently released ipywidgets 8 and jupyterlab_widgets 3, and they must be upgraded in sync. From your "installed labextensions" report and your browser output, it looks like there was a problem upgrading your jupyterlab_widgets package in the frontend, i.e., it looks like it is using the older version of the jupyterlab_widgets javascript in your browser. Your browser error indicates that the backend is using ipywidgets 8, but the frontend javascript is ipywidgets 7 (i.e., jupyterlab_widgets version 1).

**Comment by astrojuanlu** [comment]
Confirmed that upgrading `jupyterlab_widgets` on the JupyterLab environment to 3.0 worked. Thanks for the prompt response @jasongrout! Closing

**Comment by RGD2** [comment]
Me too.

With `pyenv --version ; python --version ; fnm --version ; node --version; jupyter --version`:
```
pyenv 2.3.35-4-g2798a669
Python 3.12.1
fnm 1.35.1
v20.10.0
Selected Jupyter core packages...
IPython          : 8.19.0
ipykernel        : 6.28.0
ipywidgets       : 8.1.1
jupyter_client   : 8.6.0
jupyter_core     : 5.6.1
jupyter_server   : 2.12.1
jupyterlab       : 4.0.10
nbclient         : 0.9.0
nbconvert        : 7.14.0
nbformat         : 5.9.2
notebook         : 7.0.6
qtconsole        : 5.5.1
traitlets        : 5.14.0
```

I installed jupyter with `pip install --upgrade jupyter ipympl` and then started it with `jupyter lab`
This seemed to go ok.

Then, in a new notebook, running:
 
```
%matplotlib widget
import matplotlib.pyplot as plt
plt.figure()
plt.plot(range(5))
```

Got me a javascript error instead of the expected plot.

I found I still had to run `jupyter labextension install jupyterlab_widgets` and wait for it to rebuild them before restarting the notebook kernel.

So, given that this is still true, at least for someone, isn't this ticket actually NOT `closed`? 

In general, i'm reinstalling jupyter fairly often, and run into this kind of error from time to time - it just keeps recurring. Every year or two.

Why is recent, 'vanilla' pip unable to install the javascript where it works?

Now, running the labextension install line I get:

```
(Deprecated) Installing extensions with the jupyter labextension install command is now deprecated and will be removed in a future major version of JupyterLab.

Users should manage prebuilt extensions with package managers like pip and conda, and extension authors are encouraged to distribute their extensions as prebuilt packages 
```

But this depreciation doesn't seem like it'll be safe, since prebuilt extensions apparently aren't entirely reliable.

Distro is debian trixie, BTW, but it isn't relevant, since Python was installed via pyenv, and nodejs was installed via fnm - neither from the system package manager. 

I have found this is a far safer way to get jupyterlab_widgets to actually work, regardless of the distro.

Please don't suggest anaconda. conda is an automatic maintenance nightmare generator, and will always be so: The creators can keep collecting money 'helping' people with problems it creates. I'm not playing that game. WSL2 basically means we can now just use 'real' package managers, not some third party one whose niche is because MS still doesn't know how to package manage deps properly. Conda only 'got big' because it was useful for python deps installation on windows, but now it's redundant.

Debian or Ubuntu under WSL2 from the MSFT Store, then installing jupyter using pyenv, a node package manager, and pip. This is the best way (quickest setup, most reliable, least maintenance cost, and best actual performance) to be running a local jupyter instance on a corporate-controlled Windows installation, I have found. (pro tip: Linux's cifs network mount support is orders of magnitude better than window's, if you have to work with data on a network share, even under WSL2.).

Personally, where able, I'll be using a debian or derivative natively; yet apt's packages are always a bit too stale for python: only good for the other build deps (although, *very* good for that). Pyenv 'fixes' that totally. dmn and friends similarly for nodejs.

This particular problem with needing to get the assets to be rebuilt, but only sometimes for some fresh installations, seems particularly annoying / difficult to isolate. Annoying because it predominantely is hitting new users, and it's a show-stopping heisenbug.

Probably needs a ticket to stay open for it, so there's someplace we can ask others tripping over it for diagnostics from their specific systems to figure out why it keeps happening. I came and am commenting here, because this was a the freshest (if 'closed') ticket with the 'ol 'Error displaying widget: model not found'

I can't reproduce it reliably, but that's no reason to short-close a ticket, esp. not where the issue is that this seemingly soon-to-be-retired step is still necessary. 

I came and am commenting here, because this was a the freshest (if 'closed') ticket with the 'ol 'Error displaying widget: model not found' to be found by a search on the issues. 

I'm sure others will by sooner or later.

Can we reopen this, and also have a command to run to get a better idea why this thing is happening, for the next me-too to come by?
