### ISSUE TITLE
Massive flickering when using `Output` widget

### ISSUE THREAD

**Issue by b3m2a1** [jupyter-widgets/ipywidgets#3608]
## Description

I have a custom interaction widget a la Mathematica's `Manipulate`, but it gives me terrible flickering because of how the `Output` widget is managing state updates.

Here's a video with the issue at hand

https://user-images.githubusercontent.com/18367787/195794312-96084560-5703-47a5-b2f2-84b3420bd6f7.mov

It also stalls partway through (b.c. of how `Output` manages its updates).

This _isn't_ coming from a `clear_output(wait=True)` because I'm not using any `clear_output` calls. Instead I directly set the `Output` widget's `outputs` tuple. I can confirm the issue is not fixed by rewriting my code to use `clear_output`.

## Reproduce

A version of this can be seen with the following

```python
import ipywidgets
import IPython.core.display as IPydisplay
from IPython.core.interactiveshell import InteractiveShell
import matplotlib.pyplot as plt, numpy as np, io

out = ipywidgets.Output(layout={"height":"300px"})

def prep_fig(fig):
    # InteractiveShell.instance().display_formatter.format bungles formatting matplotlib figures
    buf = io.BytesIO()
    fig.savefig(buf, format='png')
    return IPydisplay.Image(buf.getvalue())
    
def set_output(res):
    fmt = InteractiveShell.instance().display_formatter.format
    data, metadata = fmt(prep_fig(res))
    out.outputs = (
        {
            'output_type': 'display_data',
            'data': data,
            'metadata': metadata
        },
    )

def plot_output(change):
    grid = np.linspace(0, change.new, 100)
    fig, axes = plt.subplots()
    axes.plot(grid, np.sin(grid))
    set_output(fig)
    
slider = ipywidgets.IntSlider()
slider.observe(plot_output, names='value')

ipywidgets.VBox([slider, out])
```

https://user-images.githubusercontent.com/18367787/195795171-0ef53ab2-b742-4f20-8cbe-3731dd9b787f.mov

I've pruned pretty much everything away that could be causing the issue except for how `Output` works once the data gets passed to the TypeScript side through the `outputs` traitlet. Unfortunately I can't patch that and will probably (annoyingly) need to write my own custom `Output` widget, but maybe a future version of `ipywidgets` can fix this by using the equivalent of `clear_output(wait=True)` on the TypeScript side.

EDIT: it looks like the culprit is this block in [output.ts](https://github.com/jupyter-widgets/ipywidgets/blob/7.x/jupyterlab_widgets/src/output.ts#L124)
```javascript
// fromJSON does not clear the existing output
this.clear_output();
// fromJSON does not copy the message, so we make a deep copy
this._outputs.fromJSON(JSON.parse(JSON.stringify(this.get('outputs'))));
```
which is seemingly in the incorrect order as common sense would suggest you want to parse and build the JSON results _before_ you clear and reassign the output area body

EDIT2: I went in and manually fixed that line in the generated JS in the installation to see if that was a sufficient fix and it improves things but the flickering is still bad. Modifiy `this.clear_output()` to `this.clear_output(true)` also helps but again does not fully fix things.

## Expected behavior

Smooth, non-flickering animations.

## Context

- ipywidgets version 7.7.0
- Operating System and version: MacOS
- Browser and version: Safari (Chrome shows some lagging, but no flickering and JupyterLab Desktop is totally smooth)

**Comment by afonit** [comment]
Hello,
Thanks for your post.  This issue/description comes up fairly often and as a result there are two primary resolutions.
1.  Set the output to a fixed size if the issue is jumping while re-rendering.
2. Use a plotting library which has integration with ipywidgets (eg bqplot) so the plot is updated instead of performing a full redraw/rerender.

Here is an ipywidget issue which discusses some of the points you made in your post: https://github.com/jupyter-widgets/ipywidgets/issues/3507

**Comment by b3m2a1** [comment]
@afonit The issue is what Jason Grout mentioned in that linked post: Jupyter itself is too slow to render the new `mpl` image  after the output is cleared, so I'm moving over to writing a nicer `plot.ly` integration that will give me better update control and not have these flickering issues

**Comment by jasongrout** [comment]
> Jupyter itself is too slow to render the new `mpl` image after the output is cleared

Just to be clear, I said that the *browser* (not Jupyter per se) may be too slow in rendering the new image in the same update as when the output was cleared.
