### ISSUE TITLE
can it be possible to retrieve the Index of an executing cell in the extended child class of BaseWidgetView class in a custom JupyterLab widget extension? Something similar to ActiveCell method

### ISSUE THREAD

**Issue by jaidevjoshi83** [jupyter-widgets/ipywidgets#3636]
I can iterate over all the available cells, but not able to set a suitable check that can retrieve the index of the currently executing cell. I want to retrieve the embedded metadata of each of cell and want to generate a form based on the parameters retrieved from the cell metadata. 

     iterate_over_tool_cells() {
        if (!ContextManager.notebook_tracker) return;               
        if (!ContextManager.notebook_tracker.currentWidget) return; 

        const cells = ContextManager.notebook_tracker.currentWidget.content.widgets;
        cells.forEach((widget) => {
            console.log(widget)
        });
    }

**Comment by jaidevjoshi83** [comment]
I can iterate over all the available cells, but not able to set a suitable check that can retrieve the index of the currently executing cell. I want to retrieve the embedded metadata of each of the cell and want to generate a form based on the parameters retrieved from the cell metadata. 

     iterate_over_tool_cells() {
        if (!ContextManager.notebook_tracker) return;               
        if (!ContextManager.notebook_tracker.currentWidget) return; 

        const cells = ContextManager.notebook_tracker.currentWidget.content.widgets;
        cells.forEach((widget) => {
            console.log(widget)
        });
    }

**Comment by jasongrout** [comment]
This sounds like a JupyterLab question, not a Jupyter Widgets question. The appropriate place to ask it is https://github.com/jupyterlab/jupyterlab. Thanks!
