### ISSUE TITLE
Deprecation warnings on import

### ISSUE THREAD

**Issue by antonio-rojas** [jupyter-widgets/ipywidgets#3648]
## Description

After updating to 8.0.3, ipywidgets throws deprecation warnings on import

## Reproduce

 ```
$ python -c "import warnings; warnings.resetwarnings(); import ipywidgets"
/usr/lib/python3.10/site-packages/traitlets/traitlets.py:1009: DeprecationWarning: Widget._active_widgets is deprecated.
  value = getattr(cls, name)
/usr/lib/python3.10/site-packages/traitlets/traitlets.py:1009: DeprecationWarning: Widget._widget_types is deprecated.
  value = getattr(cls, name)
/usr/lib/python3.10/site-packages/traitlets/traitlets.py:1009: DeprecationWarning: Widget.widget_types is deprecated.
  value = getattr(cls, name)
/usr/lib/python3.10/site-packages/traitlets/traitlets.py:1009: DeprecationWarning: Widget.widgets is deprecated.
  value = getattr(cls, name)
```

## Expected behavior

No warnings

## Context

- ipywidgets version 8.0.3
- Operating System and version: Linux x86_64
- Browser and version:

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
        /usr/local/sbin
        /usr/local/bin
        /usr/bin
        /usr/lib/jvm/default/bin
        /usr/bin/site_perl
        /usr/bin/vendor_perl
        /usr/bin/core_perl

sys.path:
        /usr/bin
        /usr/lib/python310.zip
        /usr/lib/python3.10
        /usr/lib/python3.10/lib-dynload
        /usr/lib/python3.10/site-packages

sys.executable:
        /usr/bin/python

sys.version:
        3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0]

platform.platform():
        Linux-6.0.12-arch1-1-x86_64-with-glibc2.36

which -a jupyter:
        /usr/bin/jupyter

pip list:
        Package                       Version
        ----------------------------- -----------------
        alabaster                     0.7.12
        anyio                         3.6.2
        appdirs                       1.4.4
        apsw                          3.39.4.0
        argon2-cffi                   21.3.0
        argon2-cffi-bindings          21.2.0
        asttokens                     2.2.1
        async-generator               1.10
        async-timeout                 4.0.2
        attrs                         22.1.0
        autocommand                   2.2.2
        Automat                       22.10.0
        Babel                         2.11.0
        backcall                      0.2.0
        beautifulsoup4                4.11.1
        bleach                        5.0.1
        breezy                        3.3.1
        Brotli                        1.0.9
        brotlicffi                    1.0.9.2
        btrfsutil                     6.0.2
        cchardet                      2.1.7
        certifi                       2022.9.24
        cffi                          1.15.1
        chardet                       5.1.0
        click                         8.1.3
        colorama                      0.4.6
        comm                          0.1.2
        commonmark                    0.9.1
        configobj                     5.1.0.dev0
        constantly                    15.1.0
        contourpy                     1.0.6
        cryptography                  38.0.4
        css-parser                    1.0.8
        cssselect                     1.2.0
        cvxopt                        1.3.0
        cycler                        0.11.0
        cypari2                       2.1.3
        cysignals                     1.11.2
        Cython                        0.29.32
        debugpy                       1.6.4
        decorator                     5.1.1
        defusedxml                    0.7.1
        deprecation                   2.1.0
        distro                        1.8.0
        dnspython                     2.2.1
        docutils                      0.19
        entrypoints                   0.4
        executing                     1.2.0
        fastbencode                   0.1
        fastjsonschema                2.16.2
        feedparser                    6.0.10
        fonttools                     4.38.0
        fpylll                        0.5.7
        future                        0.18.2
        gmpy2                         2.1.3
        html2text                     2020.1.16
        html5-parser                  0.4.10
        html5lib                      1.1
        hyperlink                     21.0.0
        idna                          3.4
        ifaddr                        0.2.0
        imagesize                     1.4.1
        importlib-metadata            5.0.0
        incremental                   22.10.0
        inflate64                     0.3.1
        inflect                       6.0.2
        ipykernel                     6.19.2
        ipython                       8.7.0
        ipython-genutils              0.2.0
        ipywidgets                    8.0.3
        jaraco.classes                3.2.3
        jaraco.context                4.2.0
        jaraco.functools              3.5.2
        jaraco.text                   3.11.0
        jedi                          0.18.2
        jeepney                       0.8.0
        Jinja2                        3.1.2
        json5                         0.9.10
        jsonschema                    4.17.3
        jupyter_client                7.4.8
        jupyter_core                  5.1.0
        jupyter-events                0.5.0
        jupyter_packaging             0.12.3
        jupyter_server                2.0.1
        jupyter-server-mathjax        0.2.6
        jupyterlab                    3.5.1
        jupyterlab-pygments           0.2.2
        jupyterlab_server             2.16.5
        jupyterlab-widgets            3.0.4
        keyring                       23.11.0
        kiwisolver                    1.4.4
        lensfun                       0.3.3
        libmsym                       0.2.4
        libtorrent                    2.0.8
        lrcalc                        2.0.0
        lxml                          4.9.1
        Markdown                      3.4.1
        MarkupSafe                    2.1.1
        matplotlib                    3.6.2
        matplotlib-inline             0.1.6
        mechanize                     0.4.8
        memory-allocator              0.1.3
        mercurial                     6.3.1
        merge3                        0.0.12
        minidb                        2.0.7
        mistune                       2.0.4
        more-itertools                9.0.0
        mpmath                        1.2.1
        msgpack                       1.0.4
        multivolumefile               0.2.3
        nbclassic                     0.4.8
        nbclient                      0.7.2
        nbconvert                     7.2.6
        nbformat                      5.7.0
        nest-asyncio                  1.5.6
        netifaces                     0.11.0
        netsnmp-python                1.0a1
        networkx                      2.8.8
        nicotine-plus                 3.2.7
        notebook                      6.5.2
        notebook_shim                 0.2.2
        numpy                         1.23.5
        ordered-set                   4.1.0
        packaging                     21.3
        pandas                        1.5.1
        pandocfilters                 1.5.0
        parso                         0.8.3
        patiencediff                  0.2.10
        pdfarranger                   1.9.2
        pdftotext                     2.2.2
        pexpect                       4.8.0
        pickleshare                   0.7.5
        pikepdf                       6.2.5
        Pillow                        9.3.0
        pip                           22.3.1
        pkgconfig                     1.5.5
        platformdirs                  2.6.0
        ply                           3.11
        pplpy                         0.8.7
        primecountpy                  0.1.0
        prometheus-client             0.15.0
        prompt-toolkit                3.0.33
        psutil                        5.9.4
        ptyprocess                    0.7.0
        pure-eval                     0.2.2
        py7zr                         0.20.2
        pybcj                         1.0.1
        pybind11                      2.10.1
        pycairo                       1.23.0
        pychm                         0.8.6
        pycparser                     2.21
        pycryptodome                  3.16.0
        pycryptodomex                 3.12.0
        pydantic                      1.10.2
        pyelftools                    0.29
        Pygments                      2.13.0
        PyGObject                     3.42.2
        pyparsing                     3.0.9
        pyppmd                        1.0.0
        PyQt5                         5.15.7
        PyQt5-sip                     12.11.0
        PyQt6                         6.4.0
        PyQt6-sip                     13.4.0
        PyQt6-WebEngine               6.4.0
        pyrsistent                    0.19.2
        PySide2                       5.15.7
        python-dateutil               2.8.2
        python-json-logger            2.0.4
        pytz                          2022.6
        pytz-deprecation-shim         0.1.0.post0
        PyYAML                        6.0
        pyzmq                         24.0.1
        pyzstd                        0.15.3
        QtPy                          2.3.0
        Reflector                     2021.11.20.2.41.3
        regex                         2022.10.31
        requests                      2.28.1
        requests-unixsocket           0.3.0
        rich                          12.6.0
        rpy2                          3.5.6
        sagemath-standard             9.8b5
        sagetex                       3.6.1
        scipy                         1.9.3
        SecretStorage                 3.3.3
        Send2Trash                    1.8.0
        setuptools                    65.6.3
        sgmllib3k                     1.0.0
        shiboken2                     5.15.7
        six                           1.16.0
        sniffio                       1.3.0
        snowballstemmer               2.2.0
        soupsieve                     2.3.2.post1
        Sphinx                        5.3.0
        sphinxcontrib-applehelp       1.0.2
        sphinxcontrib-devhelp         1.0.2
        sphinxcontrib-htmlhelp        2.0.0
        sphinxcontrib-jsmath          1.0.1
        sphinxcontrib-qthelp          1.0.3
        sphinxcontrib-serializinghtml 1.1.5
        stack-data                    0.6.2
        sympy                         1.11.1
        TBB                           0.2
        team                          1.0
        terminado                     0.17.1
        testpath                      0.6.0
        texttable                     1.6.7
        tinycss2                      1.2.1
        tomli                         2.0.1
        tomlkit                       0.11.6
        tornado                       6.2
        traitlets                     5.7.0
        trove-classifiers             2022.12.1
        Twisted                       22.10.0
        typing_extensions             4.4.0
        tzdata                        2022.7
        tzlocal                       4.2
        unrardll                      0.1.5
        urllib3                       1.26.12
        urlwatch                      2.25
        validate                      5.1.0.dev0
        validate-pyproject            0.10.1
        wcwidth                       0.2.5
        webencodings                  0.5.1
        websocket-client              1.4.2
        wheel                         0.38.4
        yt-dlp                        2022.11.11
        zeroconf                      0.39.4
        zipp                          3.11.0
        zope.interface                5.5.0

</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` (or `jupyter notebook` if you use notebook) here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

### If using JupyterLab
- JupyterLab version:

<details><summary>Installed Labextensions</summary>
<pre>
Paste the output from your command line running `jupyter labextension list`.
</pre>
</details>

**Comment by maartenbreddels** [comment]
This is fixed in ipywidgets 8.0.4
