### ISSUE TITLE
Rename the default branch to `main`

### ISSUE THREAD

**Issue by jtpio** [jupyter-widgets/ipywidgets#3668]
Most of the other Jupyter projects have already adopted `main` as the name for the default branch.

We should do the same for `ipywidgets` at some point. We can do the rename via the GitHub UI, which should be straightforward. It will also automatically update existing PRs to target `main`.

Folks will have to update their local fork to switch to the new default branch.

**Comment by jasongrout** [comment]
I'm +1 so that everything is consistent between projects.

CC @jupyter-widgets/jupyter-widgets-council

**Comment by vidartf** [comment]
👍

**Comment by mwcraig** [comment]
👍

**Comment by bollwyvl** [comment]
This was done immediately after #3673

**Comment by mwcraig** [comment]
Closing, since it has been done
