### ISSUE TITLE
Sliders on mobile devices

### ISSUE THREAD

**Issue by switzel** [jupyter-widgets/ipywidgets#3678]
I am not sure at which level exactly the problem lies but issue #655 described the same problem and was marked solved without a proper solution. I created a Jupyter notebook that involves sliders and works fine on my desktop. But when I run it (including the server) on my Android device, I can move the slider by "taps" but sliding them doesn't work, presumably because the sliding is caught on a different level by the mobile browser. Could mobile-friendly sliders be used instead?

I'm using
Pydroid 3 to run Jupyter and then
Firefox to display the notebook.

Edit: the sliders [here](https://ipywidgets.readthedocs.io/en/8.0.2/examples/Widget%20List.html) for instance do work on my Android device. So as I said, it's not clear to me at which level this fails.

**Comment by jasongrout** [comment]
I just tried the link to the docs you suggest on an android 13 device, and I can drag sliders just fine in both firefox and chrome. It's a little tricky to get my finger directly on the slider so I can drag it, but once I'm on it I can drag it just fine.

Can you try another mobile device to check, or zoom into the page so the slider handle is bigger?
