### ISSUE TITLE
Fix visual regression test

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#3693]
Looks like JupyterLab now puts up a notification we are capturing, as noted in https://github.com/jupyter-widgets/ipywidgets/pull/3689#issuecomment-1416053688

We could just put that notification in our screenshots, or we could figure out how to get jlab to dismiss its notification (or not show it to begin with).

Before:
![5ce58ad328bfeb9101010a5869582d09cd9a3423](https://user-images.githubusercontent.com/192614/216647117-64ca241f-00b3-4a94-b5ca-6f0da63c0ed3.png)

After:
![e8e28c1915c46f081dfa437328e00a0e2b83efc1](https://user-images.githubusercontent.com/192614/216647163-729f4fd9-0069-49a1-89b7-29a1f236d1db.png)

Diff:
![53c0f077a9d975bdaf6162ddf4a69d6885b84e5f](https://user-images.githubusercontent.com/192614/216647193-390efe26-ba48-496e-b11f-50d902eed0d6.png)

Video:
[65d1d9910585b72a41935ee1db5f6de6c9ed1ef1.webm](https://user-images.githubusercontent.com/192614/216647745-4d385343-d9c7-4b29-a682-dd08cd59bf7e.webm)

**Comment by martinRenou** [comment]
Updating Galata seems to do the trick for getting rid of this new notification. We had the same in bqplot.

**Comment by jasongrout** [comment]
Thanks! I was looking in JLab and wasn't finding any place where they disabled notifications for test reproducibility. I didn't think about updating Galata.
