### ISSUE TITLE
Xyz

### ISSUE THREAD

**Issue by fr33zespace** [jupyter-widgets/ipywidgets#3705]
![Screenshot_20230220-170224_Advance Kubernetes.png](https://user-images.githubusercontent.com/83383618/220210504-5b037282-b306-48de-b8a6-b9e9ed84aca8.png)

[]()![Screenshot_20230220-170224_Advance Kubernetes.png](https://user-images.githubusercontent.com/83383618/220210558-73d7c79c-f508-4eaf-84d8-8a63abdc3604.png)

![Screenshot_20230220-170132_Advance Kubernetes.png](https://user-images.githubusercontent.com/83383618/220210573-14b1a10a-3ddd-4e0f-9bac-425772c232a6.png)

**Comment by ianhi** [comment]
Hi @fr33zespace I think you may have posted this in the wrong place so i'm going to close it. But feel free to open a new issue if you have  trouble with ipywidgets in the future.
