### ISSUE TITLE
on_click event for all widgets, not just Button

### ISSUE THREAD

**Issue by HariniMadhi** [jupyter-widgets/ipywidgets#3744]
Currently there is no way to capture the click and activation of a Text Box (all widgets except Button). Is there any work around for that?

There has to be an internal function to note the click of the widget, because:
1. The text box is colored blue on clicking
2. Typing without clicking is not registered anywhere
3. Cursor is seen after clicking

Is it possible to expose this function for use?

The below is my motivation for such a use case. Feel free to suggest a straight-forward or an easier method for my original issue as well.

I want to make the dropdowns searchable, and have implemented it in a long way using Text and Dropdown widgets. But I don't want to show the Dropdown all the time - only when the Text widget is clicked, the dropdowns should appear.

**Comment by HariniMadhi** [comment]
Can someone help on this? To see if the internal function can be used?

**Comment by jasongrout** [comment]
There is not an on_click event for other widgets. However, you might be able to use ipyevents to register a click handler: https://ipyevents.readthedocs.io/en/latest/index.html

**Comment by jasongrout** [comment]
Note that there is an autocomplete widget, and I think there are also combobox widgets in ipyvuetify, ipymaterialui, etc.

**Comment by HariniMadhi** [comment]
Thank you!
