### ISSUE TITLE
matplotlib can not be used as a widget on Ubuntu

### ISSUE THREAD

**Issue by cdaly2** [jupyter-widgets/ipywidgets#3750]
## Description

A matplotlib plot is supposed to be able to be treated as a widget, however, this behaviour does not work on Ubuntu in Jupyter lab.
The expected behaviour is described in the last example at https://kapernikov.com/ipywidgets-with-matplotlib/
See https://github.com/Kapernikov/ipywidgets-tutorial/issues/2 for details of the problem.

This bug has been reproduced using:
1. vscode with its version of jupyterlab
2. docker jupyter/datascience-notebook using both firefox and Microsoft edge (running on Ubuntu
3. colab

## Reproduce
```
%matplotlib widget
import ipywidgets as widgets
import matplotlib.pyplot as plt
import matplotlib
import numpy as np

output = widgets.Output(layout={'border': '1px solid black'})
 
# create some x data
x = np.linspace(0, 2 * np.pi, 100)
 
# default line color
initial_color = '#FF00DD'
 
with output:
    print("output widget capture!")
    fig, ax = plt.subplots(constrained_layout=True, figsize=(6, 4))
     
# move the toolbar to the bottom
fig.canvas.toolbar_position = 'bottom'
ax.grid(True)
with output:
    line, = ax.plot(x, np.sin(x), initial_color)
```

## Expected behavior

The output should capture the plot, however, the plot is displayed immediately and when the output is displayed, it only contains the print message.

## Context
```
print(f'ipywidgets {widgets.__version__}, matplotlib {matplotlib.__version__}, numpy {np.__version__}')
ipywidgets 8.0.6, matplotlib 3.7.1, numpy 1.24.2
```

- Operating System and version: Ubuntu 20.04.6 LTS
- Browser and version: Firefox 111.0.1 (64-bit) and also MS Edge Version 111.0.1661.54 (Official build) (64-bit)

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/home/charlie/programs/python/jupyter/nostalgia/nostalgia/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/snap/bin

sys.path:
	/home/charlie/programs/python/jupyter/nostalgia/nostalgia/bin
	/usr/lib/python38.zip
	/usr/lib/python3.8
	/usr/lib/python3.8/lib-dynload
	/home/charlie/programs/python/jupyter/nostalgia/nostalgia/lib/python3.8/site-packages

sys.executable:
	/home/charlie/programs/python/jupyter/nostalgia/nostalgia/bin/python3

sys.version:
	3.8.10 (default, Mar 13 2023, 10:26:41) 
	[GCC 9.4.0]

platform.platform():
	Linux-5.15.0-69-generic-x86_64-with-glibc2.29

which -a jupyter:
	/home/charlie/programs/python/jupyter/nostalgia/nostalgia/bin/jupyter

pip list:
	Package                  Version 
	------------------------ --------
	anyio                    3.6.2   
	argon2-cffi              21.3.0  
	argon2-cffi-bindings     21.2.0  
	asttokens                2.2.1   
	attrs                    22.2.0  
	backcall                 0.2.0   
	beautifulsoup4           4.12.0  
	bleach                   6.0.0   
	branca                   0.6.0   
	cffi                     1.15.1  
	comm                     0.1.2   
	contourpy                1.0.7   
	cycler                   0.11.0  
	debugpy                  1.6.6   
	decorator                5.1.1   
	defusedxml               0.7.1   
	executing                1.2.0   
	fastjsonschema           2.16.3  
	fonttools                4.39.0  
	idna                     3.4     
	importlib-metadata       6.0.0   
	importlib-resources      5.12.0  
	ipykernel                6.21.3  
	ipyleaflet               0.17.2  
	ipympl                   0.9.3   
	ipython                  8.11.0  
	ipython-genutils         0.2.0   
	ipywidgets               8.0.6   
	jedi                     0.18.2  
	Jinja2                   3.1.2   
	jsonschema               4.17.3  
	jupyter-client           8.0.3   
	jupyter-core             5.2.0   
	jupyter-events           0.6.3   
	jupyter-server           2.5.0   
	jupyter-server-terminals 0.4.4   
	jupyterlab-pygments      0.2.2   
	jupyterlab-widgets       3.0.7   
	kiwisolver               1.4.4   
	MarkupSafe               2.1.2   
	matplotlib               3.7.1   
	matplotlib-inline        0.1.6   
	mistune                  2.0.5   
	nbclassic                0.5.3   
	nbclient                 0.7.2   
	nbconvert                7.2.10  
	nbformat                 5.8.0   
	nest-asyncio             1.5.6   
	notebook                 6.5.3   
	notebook-shim            0.2.2   
	numpy                    1.24.2  
	packaging                23.0    
	pandas                   1.5.3   
	pandocfilters            1.5.0   
	parso                    0.8.3   
	pexpect                  4.8.0   
	pickleshare              0.7.5   
	Pillow                   9.4.0   
	pip                      20.0.2  
	pkg-resources            0.0.0   
	pkgutil-resolve-name     1.3.10  
	platformdirs             3.1.1   
	prometheus-client        0.16.0  
	prompt-toolkit           3.0.38  
	psutil                   5.9.4   
	ptyprocess               0.7.0   
	pure-eval                0.2.2   
	pycparser                2.21    
	Pygments                 2.14.0  
	pyparsing                3.0.9   
	pyrsistent               0.19.3  
	python-dateutil          2.8.2   
	python-json-logger       2.0.7   
	pytz                     2022.7.1
	PyYAML                   6.0     
	pyzmq                    25.0.1  
	rfc3339-validator        0.1.4   
	rfc3986-validator        0.1.1   
	Send2Trash               1.8.0   
	setuptools               44.0.0  
	six                      1.16.0  
	sniffio                  1.3.0   
	soupsieve                2.4     
	stack-data               0.6.2   
	terminado                0.17.1  
	tinycss2                 1.2.1   
	tornado                  6.2     
	traitlets                5.9.0   
	traittypes               0.2.1   
	wcwidth                  0.2.6   
	webencodings             0.5.1   
	websocket-client         1.5.1   
	widgetsnbextension       4.0.7   
	xyzservices              2023.2.0
	zipp                     3.15.0
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` (or `jupyter notebook` if you use notebook) here, use `--debug` if possible.
[I 2023-03-29 21:45:30.165 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-03-29 21:45:30.169 ServerApp] jupyterlab | extension was successfully linked.
[W 2023-03-29 21:45:30.170 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-03-29 21:45:30.171 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2023-03-29 21:45:30.173 ServerApp] nbclassic | extension was successfully linked.
[I 2023-03-29 21:45:30.338 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-03-29 21:45:30.571 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-03-29 21:45:30.572 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-03-29 21:45:30.572 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.10/site-packages/jupyterlab
[I 2023-03-29 21:45:30.572 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2023-03-29 21:45:30.575 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-03-29 21:45:30.579 ServerApp] nbclassic | extension was successfully loaded.
[I 2023-03-29 21:45:30.579 ServerApp] The port 8888 is already in use, trying another port.
[I 2023-03-29 21:45:30.579 ServerApp] Serving notebooks from local directory: /home/jovyan/notebooks/main
[I 2023-03-29 21:45:30.580 ServerApp] Jupyter Server 2.1.0 is running at:
[I 2023-03-29 21:45:30.580 ServerApp] http://bf856a3bfd34:8889/lab?token=12c5ca092907814f2c348909659d29fca4742deddfb44974
[I 2023-03-29 21:45:30.580 ServerApp]  or http://127.0.0.1:8889/lab?token=12c5ca092907814f2c348909659d29fca4742deddfb44974</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
No errors.
</pre>
</details>

### If using JupyterLab

- JupyterLab version:

<details><summary>Installed Labextensions</summary>
<pre>
Paste the output from your command line running `jupyter labextension list`.
</pre>
</details>

**Comment by cdaly2** [comment]
Interestingly, a small variation will work:
```
from ipywidgets import Output, Tab
from matplotlib import pyplot as plt

out = Output()
t = Tab()
t.children = [out]
t
```
and then:
```
with out:
    plt.plot([1,2,3], [4,5,2])
    plt.show() # required in Google Colab
```
This will display the matplotlib output the tab, i.e. matplotlib is acting like a widget, but it doesn't work when the plot is created using plt.subplots

**Comment by cdaly2** [comment]
That last tab example from https://github.com/jupyter-widgets/ipywidgets/issues/1960#top

**Comment by jasongrout** [comment]
> plt.show() # required in Google Colab

This seems to be more of an ipympl issue. I'm not sure exactly how the subplots is displaying the widget, but I imagine the .show() call would be done in the output widget context handler to get it to show in the output widget.

Can you open this issue in the ipympl repo? https://github.com/matplotlib/ipympl
