### ISSUE TITLE
Explain how to set multiple values via observe on DOMWidget

### ISSUE THREAD

**Issue by paddymul** [jupyter-widgets/ipywidgets#3756]
### Problem

I want to observe a single trait, and based on that trait, set multiple other traits.
The python class has the values updated properly, but only the first set trait gets propagated to the frontend.

I assume there is some type of notify or other command to batch state changes.  I tried send_state, and that didn't work

My widget updates properly when I manually set the other dependent trait in a separate cell.

### Suggested Improvement

Document this behaviour and the best way to either structure your code around the problem (I'm putting the combined state into a single dictionary item) or another solution.

**Comment by ibdafna** [comment]
Hey @paddymul 👋🏼

Just so we can better understand what you are trying to achieve, would you be able to provide us with a small, reproducible code example of this issue? We will then be better equipped to help.

Thanks!

**Comment by paddymul** [comment]
This was failing because of some interaction between my previous typescript/react code and the traitlets widget.

I was able to create a working example here... based on @maartenbreddels ipyreact

adding for context in case someone ends up searching for the same thing.
https://github.com/paddymul/ipyreact/blob/feat/two-dependent/examples/TwoDependent.ipynb

**Comment by jasongrout** [comment]
Thanks for following up here. For the record for future readers, here's [your example](https://github.com/paddymul/ipyreact/blob/feat/two-dependent/examples/TwoDependent.ipynb) in this thread:

```python
import ipyreact
from traitlets import  Bool, Int, observe

class TwoDependentWidget(ipyreact.ReactWidget):
    #note that when we add these traitlets, they will automatically be made available to the react component
    is_even = Bool(True).tag(sync=True)
    is_odd = Bool(False).tag(sync=True)
    
    count = Int(0).tag(sync=True)

    #it is key that we also take the change argument, otherwise a hard to find python error will be thrown
    @observe('count')
    def _observe_count(self, change):
        new_val = self.count
        if new_val %2 == 0:
            self.is_even = True
            self.is_odd = False

        else:
            self.is_even = False
            self.is_odd = True

    
    _esm = """
    import confetti from "canvas-confetti";
    import * as React from "react";

    export default function({on_count, debug, count, is_even, is_odd}) {
        return <div><button onClick={() => confetti() && on_count(count + 1)}>
            {count} times confetti
        </button>
        <span>count is even == {is_even.toString()} </span>
        <span>count is odd == {is_odd.toString()} </span>
    </div>
    };"""
tdw = TwoDependentWidget()
tdw

```
