### ISSUE TITLE
Simplest way to bind a variable to a value in widget

### ISSUE THREAD

**Issue by gillsimu** [jupyter-widgets/ipywidgets#3757]
Hello!

What is the simplest way to bind a variable to a value in widget? 

For eg. 
`x = 3`
`from ipywidgets import widgets`  
`input_text = widgets.Text()`
`input_text`

Here in the text box, I need to refer to the variable x. Such that input_text.value = 3. How can I do it?

**Comment by jasongrout** [comment]
I'm not clear on what you are asking. Are you saying that a user might put some text in the widget like `Use the value $x`, and you need convert that to the string `Use the value 3`? In that case, you'll have to write code to parse the `input_text.value` and substitute in the values. Or are you imagining the workflow to be something different?

**Comment by gillsimu** [comment]
That's correct. How can I parse the input_text ?

**Comment by jasongrout** [comment]
> How can I parse the input_text ?

This is more of a python/computer science question than an ipywidgets question. One way is to use the Python string formatting functions (like https://docs.python.org/3.10/library/stdtypes.html#str.format), and have the user type in the string in that format. But this is really up to you how you do it.
