### ISSUE TITLE
Disabling Dropdowns or Selection Widget should still allow users to see the options, just not be able to select them

### ISSUE THREAD

**Issue by HariniMadhi** [jupyter-widgets/ipywidgets#3762]
I want to store the output of a series of operations, with the most recent visible to the users. But if they are clicking the dropdown, they should see the old values. But I don't want the users to change the value. I'm basically using dropdown not as input, but as a output widget.

Right now, I have a workaround, that I observe the change in dropdown, and check if the value is not the first option, I revert back. But it looks messy, as it changes the option after the user has selected.

Is there a way to prevent user from selecting value, but still display the options on clicking them?

**Comment by jasongrout** [comment]
The dropdown uses the OS control, which I think if you disable it, does not let them see the other options. It sounds like maybe the control is not a good fit for what you want to do. Perhaps an output widget or HTML widget is a better fit?

**Comment by HariniMadhi** [comment]
Hi, thanks for the suggestion.
I want to show only one value at all times, but when the user clicks the box, I want to show the previous values, but not allow them to change the shown value.
What might be the best widget for this?
