### ISSUE TITLE
Ipywidgets interact in Google Colab creates new plots instead of updating existing ones.

### ISSUE THREAD

**Issue by denbonte** [jupyter-widgets/ipywidgets#3766]
## Description

When using the Ipywidgets interact function in Google Colab, the intended behavior is to update existing plots. However, for a week or so, multiple users have reported that the function creates new plots instead of updating the existing ones (e.g., when using a slider to scroll through a stack of images).

Here's a screenshot with the starting point:
![image](https://user-images.githubusercontent.com/31729248/235611040-33c83768-6156-4eea-b792-f6b08c8fd3e6.png)

Here's a screenshot after scrolling:
![image](https://user-images.githubusercontent.com/31729248/235611126-21d034d0-6401-447f-9144-70eae9c9194d.png)

I'm using very simple custom widgets/functions that you can find here:
https://github.com/AIM-Harvard/pyplastimatch/blob/main/pyplastimatch/utils/viz.py

You're more than welcome to check I'm not doing anything strange - but as I mentioned above, it was working correctly until a week/a couple of weeks ago.

## Reproduce

We have several notebooks to demo this behavior. For instance:

https://github.com/ImagingDataCommons/IDC-Tutorials/blob/master/notebooks/IDC_segmentation_primer.ipynb

You can find a report from another user here:
https://stackoverflow.com/questions/76079118/ipywidgets-interact-function-in-google-colab-creates-new-plots-instead-of-updati

## Expected behavior

The intended behavior is for the widgets to update existing plots.

## Context

Google Colab is running `ipywidget==7.7.1`.

**Comment by jasongrout** [comment]
Issues in Colab should be reported in a colab repo (though I'm not sure which one: https://github.com/googlecolab).

CC @blois

**Comment by denbonte** [comment]
Hey @jasongrout!

Thanks for the swift reply and for the pointer, and sorry if opening an issue here wasn't the best thing to do!

I somehow concluded the change had to be linked to an Ipywidgets update, but it looks like it could very well be otherwise... I'll open an issue on one of the Colab repos and link it back here (in case other users have a similar problem and want to keep track of this!)

Thanks!

**Comment by jasongrout** [comment]
Thanks. Sometimes @blois checks in here as well (he's one of the colab devs). I'll close this for now, and if it turns out that it is something that needs fixing in ipywidgets, we can always reopen. Thanks!
