### ISSUE TITLE
Is ipywidgets broken?

### ISSUE THREAD

**Issue by HariniMadhi** [jupyter-widgets/ipywidgets#3769]
I've created a tool using ipywidgets.

Consider the below code:

```
import ipywidgets as widgets
import time

def func():
    time.sleep(5)
    
def onclick_button1(button):
    if button1.description == 'Load':
        button1.description = 'Loading'
        func()
        button1.description = 'Loaded'
    else:
        display('Already Loaded')
    
def onclick_button2(button):
    button1.description = 'Load'
    
button1 = widgets.Button(description = 'Load')
button2 = widgets.Button(description = 'Click')

button1.on_click(onclick_button1)
button2.on_click(onclick_button2)

display(button1, button2)
```

The description of button1 will be changed back to Load here due to click of button2. But in my tool, some other factors trigger the change. The func() is a bit more complicated and generates some results.

Now my issue is, sometimes the description is not changing, but the func() is getting executed. How is this possible?

**Comment by jgunstone** [comment]
your code 

```py
import ipywidgets as widgets
import time

def func():
    time.sleep(5)

def onclick_button1(button):
    if button1.description == 'Load':
        button1.description = 'Loading'
        func()
        button1.description = 'Loaded'
    else:
        display('Already Loaded')

def onclick_button2(button):
    button1.description = 'Load'

button1 = widgets.Button(description = 'Load')
button2 = widgets.Button(description = 'Click')

button1.on_click(onclick_button1)
button2.on_click(onclick_button2)

display(button1, button2)
```

works fine for me. 
because of you sleep function when clicking button2 after button1 it appears not to work, but then catches up when the sleep has finished

**Comment by HariniMadhi** [comment]
> 

Hey, thanks for replying. the func() I've used here is a dummy function - I'm having a more complex function, and it generally takes some time to complete (mimicked it with sleep)

But somehow the problem resolved the day after.
