### ISSUE TITLE
Upgrading extension for JupyterLab 4 compatibility

### ISSUE THREAD

**Issue by BarbarossaWang** [jupyter-widgets/ipywidgets#3781]
### Problem

Last week, JupyterLab release [v4.0.0](https://github.com/jupyterlab/jupyterlab/releases/tag/v4.0.0) that need upgrade existing extensions to use the new extesion systen and packaging.

Using current ipywidgets extesions in JupyterLab 4 that would throw `Error displaying widget`.

### Proposed Solution

Check JupyterLab [Extension Migration Guide](https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html#upgrading-extension-using-the-upgrade-script).

**Comment by ibdafna** [comment]
Hey @BarbarossaWang welcome to the ipywidgets community!

Would you be able to share more context on this problem, perhaps with steps to reproduce your issue? Are you trying to build a custom widget? If you are trying to use ipywidgets in Jupyterlab 4 and are seeing an error, a set of steps to reproduce would be great. Thanks!

**Comment by Yishai-s** [comment]
Hey @ibdafna,
I'm probably misunderstanding something, but I encountered a problem that may be the one @BarbarossaWang had.
With jupyterlab==4.0.1, ipywidgets==8.0.3, I start a jupyter lab and create a Tab:

`import ipywidgets as widgets<br>
 widgets.Tab(children=(widgets.IntSlider(), widgets.IntSlider()),
            titles=('Tab1', 'Tab2'))`

The Tab is indeed created, but it

**Comment by Yishai-s** [comment]
Great,
Thanks!
