### ISSUE TITLE
In JupyterLab 4.02, ipywidgets throws error in console on saving widget state.

### ISSUE THREAD

**Issue by kolibril13** [jupyter-widgets/ipywidgets#3790]
In JupyterLab 4.02 with the setting  "save widget state automatically" enabled, I get the following message in the console when saving the notebook (even if there's no widget present in the notebook):
```
TypeError: this._context.model.metadata.set is not a function at f._saveState
```
The error does not come when the "save widget state automatically" setting is not activated.

here is the environment that I've used:
```
python3.11 -m venv .venv
source .venv/bin/activate   
pip install jupyterlab   
pip install ipywidgets 
python -m jupyterlab
```
<img width="1235" alt="image" src="https://github.com/jupyter-widgets/ipywidgets/assets/44469195/c351521e-bab5-4fc9-aa59-576cdc1c09a1">

I've also tested this in an older version (pip install jupyterlab==3.6), and there it worked fine without the error.

Context: I've observed this error while working on this issue https://github.com/widgetti/ipyreact/issues/40

**Comment by martinRenou** [comment]
Thanks for opening an issue. This should be fixed by https://github.com/jupyter-widgets/ipywidgets/pull/3752
