### ISSUE TITLE
Binder uses incompatible version of yarn

### ISSUE THREAD

**Issue by gregfreeman** [jupyter-widgets/ipywidgets#3806]
## Description

When launching binder, the wrong version of yarn is loaded.   

Error message:
Installing and building all yarn packagesyarn install v1.21.1
[1/5] Validating package.json...
error @: The engine "yarn" is incompatible with this module. Expected version ">=3". Got "1.21.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Removing intermediate container 3125befe8fbb
The command '/bin/sh -c ./.binder/postBuild' returned a non-zero code: 1

## Reproduce

1. Create a PR
2. Click "Launch binder"button with text "Launch a binder notebook on branch <branch>"
3. Wait for binder to build ipywidgets 

## Expected behavior

Binder launches with example notebooks

## Context

Occurred when creating a PR
Using Chrome Version 114.0.5735.198

**Comment by martinRenou** [comment]
Thanks for reporting! 

This should have been fixed by https://github.com/jupyter-widgets/ipywidgets/pull/3795
