### ISSUE TITLE
docs(@jupyter-widgets/base):  `JUPYTER_WIDGETS_VERSION` meaning / out of date?

### ISSUE THREAD

**Issue by manzt** [jupyter-widgets/ipywidgets#3809]
### Problem

I'm trying to understand what `JUPYTER_WIDGETS_VERSION` is. The git blame shows that it was previously named `__jupyter_widgets_base_version__`, and if it is the version of `@jupyter-widgets/base` is it out of sync.

https://github.com/jupyter-widgets/ipywidgets/blob/39d3c5df684539830e2232ac9265abf4331555f1/packages/base/src/version.ts#L4

It would be useful to detect what version of `@jupyter-widgets/base` is used at runtime, since this is an external dependency for all custom widgets.

**Comment by manzt** [comment]
I see, these are protocol versions for each package.

**Comment by maartenbreddels** [comment]
> It would be useful to detect what version of `@jupyter-widgets/base` is used at runtime

curious, why do you need that?

**Comment by manzt** [comment]
All custom widgets rely on the `@jupyter-widgets/base`, but when you package your widget, the `@jupyter-widgets/base` package is left external to be provided by the front-end environment.

Only JupyterLab inspects the widget's `package.json` for metadata regarding the version and compatibility. If there are regressions, it would be useful to identify what version of `@jupyter-widgets/base` is provided by various notebook environments. Right now this information is completely obscured in the console.
