### ISSUE TITLE
Widget rendering in JupyterLab4 and JupyterNotebook7

### ISSUE THREAD

**Issue by kolibril13** [jupyter-widgets/ipywidgets#3823]
Today I was investigating how I can store the state of a widget with the latest Jupyter setups.

I wanted to know:
* Can I **save** the widget state?
* Is there an **indicator** that shows that the widget-kernel connection is lost?
* Does the widget render correctly **after restarting** the Jupyter server?
* Does the widget render correctly **on sphinx** with myst-nb?

And here is a summary of my findings:

<img width="2380" alt="image" src="https://github.com/jupyter-widgets/ipywidgets/assets/44469195/e29fa3ef-6b9d-44e1-893e-84454a863e64">

used code:
```py
import ipywidgets
ipywidgets.__version__

ipywidgets.widgets.Button(description="Hello World!")
```

Key findings from the above chart:

1. Jupyter Notebook 6.5.4 is a setup where everything works great and there's the option "*Save Notebook Widget State*".
2.  jlab4 and jn7 have the new option "*Save Widget State Automatically*". I couldn't find out if that actually works or no.
3. Jupyter VS Code cannot save widget states, and that's also not planned https://github.com/microsoft/vscode-jupyter/issues/4404 . 
4. When I shut down the jupyter server and restart it, the jlab4 and nb7 console says **"Error: widget model not found"**.  
I think making widget rendering possible after a notebook restart in the latest Jupyter environments would be a fantastic improvement. This could impact the widget ecosystem in a very positive way, especially since numerous people in the community have reported similar widget model not found errors: 
https://github.com/jupyter-widgets/ipywidgets/issues/3758,
https://github.com/jupyter-widgets/ipywidgets/issues/3773, 
https://github.com/jupyter-widgets/ipywidgets/issues/2628, 
https://github.com/jupyter-widgets/ipywidgets/issues/3183, 
https://github.com/jupyter-widgets/ipywidgets/issues/3790

https://discourse.jupyter.org/t/widgets-not-rendering-after-the-second-time-a-notebook-is-reopened/10631
https://discourse.jupyter.org/t/error-displaying-widget-model-not-found-geemap/11473

**Comment by jasongrout** [comment]
> jlab4 and jn7 have the new option "_Save Widget State Automatically_". I couldn't find out if that actually works or no.

FYI, turning this option on saves the widget state when you save the notebook. Turning the option off does not save the widget state when you save the notebook (and as a consequence, the notebook files are much smaller).

**Comment by kolibril13** [comment]
hi @ibdafna, I'm happy to see that you self-assigned to this issue!

I'm curious to understand this bug a bit better:

Currently, "Save Widget State Automatically" adds a lot of data like "ewogICJ2ZXJzaW9uIjogMywKICAic291..." into the  `"widgets": {` section of the notebook. 

That can increase the size of the notebook quite a bit (up to a few 100kBs) which is totally fine when there's actual information saved, but would be unnecessary clutter in case that it's just corrupted data that comes from a bug while saving the notebook.

So the question: Is this bug related to widget saving, or widget loading?

**Comment by gutow** [comment]
> So the question: Is this bug related to widget saving, or widget loading?

As noted in https://github.com/jupyter-widgets/ipywidgets/issues/3758, opening a notebook in NBClassic that was saved in JLab 4/Notebook 7 with automatic saving of widget states properly renders the widget state with the broken connection icons. This suggests the problem is a notebook parsing or internal JLab communications issue and not related to an error in the data saved.

**Comment by krassowski** [comment]
Since this looks like JupyterLab 4 issue, I would suggest opening an issue against https://github.com/jupyterlab/jupyterlab :)

**Comment by kolibril13** [comment]
@dinohsu1019 I can understand your frustration.
Passing the issue from one project to the next one is part of the process to investigate where this issue is coming from, and that takes time.
The Jupyter core-infrastructure is evolving quickly, and it's not every feature is immediately up-to-date.
If you want to use that feature, you can do so by downgrading to
```py
python3.11 -m venv .venv && source .venv/bin/activate
pip install notebook==6.5.6
```

**Comment by maartenbreddels** [comment]
Note that https://github.com/jupyter-widgets/ipywidgets/pull/3866 should fix this.

**Comment by kolibril13** [comment]
Really happy this is solved now, thanks everyone for making this possible!

**Comment by maartenbreddels** [comment]
Thank you for the feedback ❤️

**Comment by RKwork85** [comment]
> 我仍然面临： Error Displaying widget: model not found, with: jupyterlab: 4.0.9 ipywidgets: 8.1.1 jupyterlab-widgets: 3.0.9 我也找不到任何有效的降级。
> 
> 这方面有更新吗？我对这个问题很困扰，一些长时间运行的结果应该保留在 ipywidgets 对象中，包括 Output()。请作为一个整体帮助确定根本原因，无论是 jupyterlab、ipywidgets、ipython、javescript 文件还是其他文件，而不是互相推诿。再次感谢。



> 我仍然面临： Error Displaying widget: model not found, with: jupyterlab: 4.0.9 ipywidgets: 8.1.1 jupyterlab-widgets: 3.0.9 我也找不到任何有效的降级。
> 
> 这方面有更新吗？我对这个问题很困扰，一些长时间运行的结果应该保留在 ipywidgets 对象中，包括 Output()。请作为一个整体帮助确定根本原因，无论是 jupyterlab、ipywidgets、ipython、javescript 文件还是其他文件，而不是互相推诿。再次感谢。

Quite agree ！！！！！！！！！！！！！！！！！！！

**Comment by philibe** [comment]
Reading this issue /jupyter/jupyter_core/issues/283, it works with
- interactive CLI: `export JUPYTER_PREFER_ENV_PATH=1 && /home/my_name/anaconda3/bin/jupyterhub -f /home/my_name/jupyterhub-work/jupyterhub_config.py`
- or in  `systemd` : add `Environment="JUPYTER_PREFER_ENV_PATH=1"` in `/etc/systemd/system/jupyter-hub.service`

with
```
[Unit]
Description=Jupyterhub
After=syslog.target network.target

[Service]
TimeoutStartSec=15
# User=my_name
Environment="PATH=/home/my_name/anaconda3/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin"
Environment="JUPYTER_PREFER_ENV_PATH=1"

ExecStart=/home/my_name/anaconda3/bin/jupyterhub -f /home/my_name/jupyterhub-work/jupyterhub_config.py
WorkingDirectory=/home/my_name/jupyterhub-work/
RestartSec=1


[Install]
WantedBy=multi-user.target
```

with 
```
jupyterlab==4.4.10
ipywidgets==8.1.8
jupyterlab-widgets==3.0.16
```

**Comment by philibe** [comment]
I installed another ubuntu server yesterday  with jupyter+  lab + hub+ widgets  and I have randomly again `"Error displaying widget: model not found"`.

- in lab `http://my_server:8000/user/my_name/lab/tree/...../my_notebook.ipynb`

![Image](https://github.com/user-attachments/assets/f63671bf-1aa9-4486-b0ee-27c8ba3bbc3c)

But when I click on `Notebook[/>]` ie directly on the notebook, without I suppose lab, it works.
- `Notebook[/>]` ->out of lab `http://my_server:8000/user/my_name/notebooks/...../my_notebook.ipynb`

![Image](https://github.com/user-attachments/assets/1c601d14-d379-4513-bfc4-bbc79172e3e6)
