### ISSUE TITLE
ipywidgets 8.1.0 is broken in jupyterlite (with pyodide kernel)

### ISSUE THREAD

**Issue by mperreir** [jupyter-widgets/ipywidgets#3826]
## Description

importing ipywidget in jupyterlite with pyodide kernel does not work anymore and generates an exception

## Reproduce

Just run `import ipywidgets as widgets`

## Expected behavior

Should load ipywidgets without any error (as it does for version 8.0.7)

## Context

- ipywidgets version 8.1.0
- Operating System and version: Mac OS (but should be the same on other OS)
- Browser and version: Tested with latest Brave Firefox and Safari browsers

<details><summary>Import command output</summary>
<pre>
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 4
      2 import numpy as np
      3 import matplotlib.pyplot as plt
----> 4 import ipywidgets as widgets
      6 def plotSin( offset ):
      7     signal = np.sin(np.linspace(-np.pi+np.pi*offset/100, np.pi+np.pi*offset/100, 200))

File /lib/python3.11/site-packages/ipywidgets/__init__.py:54
     51         return
     52     register_comm_target()
---> 54 _handle_ipython()

File /lib/python3.11/site-packages/ipywidgets/__init__.py:52, in _handle_ipython()
     50 if ip is None:
     51     return
---> 52 register_comm_target()

File /lib/python3.11/site-packages/ipywidgets/__init__.py:41, in register_comm_target(kernel)
     39 """Register the jupyter.widget comm target"""
     40 from . import comm
---> 41 comm_manager = comm.get_comm_manager()
     42 if comm_manager is None:
     43     return

File /lib/python3.11/site-packages/ipywidgets/comm.py:18, in get_comm_manager()
     17 def get_comm_manager():
---> 18     if requires_ipykernel_shim():
     19         ip = get_ipython()
     21         if ip is not None and getattr(ip, "kernel", None) is not None:

File /lib/python3.11/site-packages/ipywidgets/comm.py:11, in requires_ipykernel_shim()
      8 if "ipykernel" in sys.modules:
      9     import ipykernel
---> 11     version = ipykernel.version_info
     12     return version < (6, 18)
     13 else:

AttributeError: module 'ipykernel' has no attribute 'version_info'
</pre>
</details>

### If using JupyterLab

- **JupyterLite** version: 0.1.2
- Pyodide kernel version: 0.1.1

<details><summary>Installed Labextensions</summary>
<pre>
jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        jupyter-matplotlib v0.11.3 enabled OK
        @deathbeds/jupyterlab-font-anonymous-pro v2.1.1 enabled OK (python, jupyterlab-fonts)
        @deathbeds/jupyterlab-font-dejavu-sans-mono v2.1.1 enabled OK (python, jupyterlab-fonts)
        @deathbeds/jupyterlab-fonts v2.1.1 enabled OK (python, jupyterlab-fonts)
        @deathbeds/jupyterlab-font-fira-code v2.1.1 enabled OK (python, jupyterlab-fonts)
        @deathbeds/jupyterlab-deck v0.1.3 enabled OK
        @jupyter-widgets/jupyterlab-manager v5.0.8 enabled OK (python, jupyterlab_widgets)
        @jupyterlite/pyodide-kernel-extension v0.1.1 enabled OK (python, jupyterlite_pyodide_kernel)
</pre>
</details>

**Comment by martinRenou** [comment]
Thanks for opening an issue. This should probably be transferred to the pyodide-kernel repository though.

This traceback looks odd. The ipykernel module shim does have a `version_info` attribute https://github.com/jupyterlite/pyodide-kernel/blob/main/packages/pyodide-kernel/py/ipykernel/ipykernel/__init__.py#L18C28-L18C28

Would you be able to provide a link to the deployment you are using?

**Comment by jtpio** [comment]
Also ipywidgets seems to be working fine with this deployment which is using the latest versions of `jupyterlite` and `jupyterlite-pyodide-kernel`: https://github.com/jupyter/try-jupyter

Available here: https://jupyter.org/try-jupyter/lab/?path=notebooks%2FIntro.ipynb

![image](https://github.com/jupyter-widgets/ipywidgets/assets/591645/d0b4f656-129d-49e5-bf86-35b3f1d18fb9)

**Comment by mperreir** [comment]
You are right, it works (even on my jupyterlite instances (both local and online). I suppose it was broken with the previous 0.1.0 jupyterlite version I was using and that some file remained in cache when I updated everything.

**Comment by jtpio** [comment]
Thanks @mperreir for checking :+1: 

Yes it's very likely an issue with the cache. There are a couple of issues about this on the jupyterlite repo, which are often happening when updating to a newer version (and should be fixed in JupyterLite).

**Comment by martinRenou** [comment]
Closing as resolved!
