### ISSUE TITLE
Embed doesn't work anymore? (e.g: Syncing error: no comm channel defined)

### ISSUE THREAD

**Issue by hainm** [jupyter-widgets/ipywidgets#3878]
Hi there,

I am trying to embed nglview-js-widgets 3.1.0 in my application but getting below error:
https://www.npmjs.com/package/nglview-js-widgets

<img width="1347" alt="image" src="https://github.com/jupyter-widgets/ipywidgets/assets/4451957/e872b0aa-0e8a-44b5-baad-0eb8e8c0d6a8">

You could try to download index.html.txt (-> index.html) and open it to see the error message
[index.html.txt](https://github.com/jupyter-widgets/ipywidgets/files/13894919/index.html.txt)

If I change the `nglview-js-widgets` version from 3.1.0 to 3.0.8 in the index.html, thing just work.

`3.1.0` version works fine in the notebook and lab.

Do you have idea how to resolve this? Thanks.

**Comment by hainm** [comment]
Another way to reproduce is

```
pip install nglview==3.1.0 # ipywidgets 8, notebook 7
```

And in notebook
```
# 1st cell
import nglview as nv
view = nv.demo()
view

# 2nd cell
nv.write_html("index.html", view)
!open index.html
```

**Comment by hai-schrodinger** [comment]
> Syncing error: no comm channel defined'

https://github.com/jupyter-widgets/ipywidgets/blob/b2531796d414b0970f18050d6819d932417b9953/packages/base/src/widget.ts#L478-L483

**Comment by hainm** [comment]
Seems like an issue with the NGL release instead: https://github.com/nglviewer/ngl/issues/1014
