### ISSUE TITLE
Compatibility issue on Windows with `requests` library

### ISSUE THREAD

**Issue by nanaeaubry** [jupyter-widgets/ipywidgets#3917]
We are building a custom widget and it uses the requests library. We noticed that for `requests>=2.32` there is an issue but only on Windows machines.

Are there any known issues or fixes for this?

When using requests version 2.31.0 the widget works.

**Comment by martinRenou** [comment]
Can you elaborate on the mentioned issue?

**Comment by nanaeaubry** [comment]
```
import requests
with requests.Session() as session:
   print(session.get("https://www.arcgis.com/sharing/rest/portals/self?f=json").text)

```

fails when your library is installed in our environment

**Comment by nanaeaubry** [comment]
@martinRenou Closing because we saw that the issue is within requests library. 
Thanks!
