### ISSUE TITLE
Implementing tooltips for all widgets

### ISSUE THREAD

**Issue by nlooije** [jupyter-widgets/ipywidgets#421]
I noticed that [ToggleButtons](https://github.com/ipython/ipywidgets/blob/master/ipywidgets/widgets/widget_bool.py#L46) have [tooltips](https://github.com/ipython/ipywidgets/blob/master/ipywidgets/widgets/widget_bool.py#L63) implemented where if hovering over the button a tooltip appears with some text specified in:

> widgets.Button(description='Button', width='10%', tooltip='This is the tooltip')

which results in:
![tooltip](https://cloud.githubusercontent.com/assets/3252193/13728721/93d1da6e-e921-11e5-81c1-449da4b5eb22.png)

Now this is quite useful because it gives the ability to provide more info than possible in text on the button if the width is small as in the above example.

It seems to me this is a useful feature on a number of other widgets aswell, e.g. the Text widget, Checkbox widget, etc. Often not a lot of textual information can be given through the 'description' attribute without making the widget excessively long:

> widgets.Text(description='Enter the name of this Text field')

![textfield](https://cloud.githubusercontent.com/assets/3252193/13728742/327ba582-e922-11e5-9c4e-d9d36eec24a0.PNG)

I have a couple of questions:
1. Is there a specific reason why `tooltips` aren't implemented on all widgets by default (it could ofcourse be disabled by default, e.g. using `tooltip=None`?
2. Are the devs and community at all interested in such a feature?
3. I would like to see this implemented and willing to do some work to get it done but i need some pointers. I made some [attempts](https://github.com/nlooije/ipywidgets/commit/1de745088a13c276f0eca86f05bb38771eba3fad) at implementing a tooltip on the label of a TextField. Unfortunately, it is not working at all which is probably the result of my limited understanding of Javascript. Is my approach at all correct? If not, how should i approach this?

**Comment by nlooije** [comment]
Regarding 3: Nevermind, i managed to [fix](https://github.com/nlooije/ipywidgets/commit/71d382da00e2e4c228459c18eec4b87d1b243ef5) the problem getting a tooltip on a label in a TextField.

![textfield](https://cloud.githubusercontent.com/assets/3252193/13737198/c28622d0-e9bb-11e5-9f3e-6bbbc65a1d84.PNG)

I would still like to know the answer to specifically question 2 before making a PR.

**Comment by ellisonbg** [comment]
I am open to us having tooltips on the widgets, but would recommend the tooltips text follow guidelines such as these:

https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/Assistance.html

**Comment by nlooije** [comment]
Ok that's great to know, i will start preparing a PR. Considering your recommendation; I distilled the  main points of a good tooltip according to those guidelines to 10 points:

1. For the best user experience, don’t create a custom help viewer.
2. Only display a Help button in a window when there is contextually relevant help available.
3. In general, don’t name the interface element in the tag. 
4. Describe only the element that the pointer is resting on. 
5. Describe controls that are unique to your app.
6. Focus on the action users can perform using the control. 
7. Use the fewest words possible. 
8. Use sentence-style capitalization. 
9. In general, use a sentence fragment.
10. Consider creating contextually sensitive help tags. 

We can of course limit the string length of the tooltip which would satisfy point 7. In my opinion, however, satisfying the other guidelines is up to the discretion of the person writing the tooltip. How do you propose to _enforce_ users to follow most of these guidelines?

**Comment by ellisonbg** [comment]
Two points:

* The guidelines should probably be enforced using code review.
* Thinking more about the actual content of the tooltips. In reality,
having a tooltip like "Enter text here" isn't very useful. What you want is
information that is domain specific like, "Enter your first and last name
here"

Because of this, would it make more sense to expose the tooltip text as an
attribute on the widgets themselves that users can set in python?

On Tue, Mar 15, 2016 at 3:25 AM, Niels Looije <notifications@github.com>
wrote:

> Ok that's great to know, i will start preparing a PR. Considering your
> recommendation; I distilled the main points of a good tooltip according to
> those guidelines to 10 points:
>
>    1. For the best user experience, don’t create a custom help viewer.
>    2. Only display a Help button in a window when there is contextually
>    relevant help available.
>    3. In general, don’t name the interface element in the tag.
>    4. Describe only the element that the pointer is resting on.
>    5. Describe controls that are unique to your app.
>    6. Focus on the action users can perform using the control.
>    7. Use the fewest words possible.
>    8. Use sentence-style capitalization.
>    9. In general, use a sentence fragment.
>    10. Consider creating contextually sensitive help tags.
>
> We can of course limit the string length of the tooltip which would
> satisfy point 7. In my opinion, however, satisfying the other guidelines is
> up to the discretion of the person writing the tooltip. How do you propose
> to *enforce* users to follow most of these guidelines?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/ipython/ipywidgets/issues/421#issuecomment-196756881
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by nlooije** [comment]
Maybe my example in my first post was badly chosen; i agree that the purpose of the tooltip should be to provide more useful info than 'Enter the name of the text field'. 
My aim with the tooltips is exactly that the `tooltip`, like e.g. `description`, should be an attribute the user can set.

**Comment by ellisonbg** [comment]
Ahh great!

On Tue, Mar 15, 2016 at 3:13 PM, Niels Looije <notifications@github.com>
wrote:

> Maybe my example in my first post was badly chosen; i agree that the
> purpose of the tooltip should be to provide more useful info than 'Enter
> the name of the text field'.
> My aim with the tooltips is exactly that the tooltip, like e.g.
> description, should be an attribute the user can set.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipywidgets/issues/421#issuecomment-197048710>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by hainm** [comment]
I am +1 for adding tooltip for Text and TextArea. Sometimes I don't want to use Description or Label to make the GUI nicer.

**Comment by jasongrout** [comment]
You might mention in docs that touch devices don't have a natural way to access tooltips, to help people understand the UI issues.

**Comment by DBO1790** [comment]
Is their now a possibility to adjust the tooltip for the SelectMultiple widget? 
If a set `widgets.SelectMultiple(options=['Just','a','test'], description='Select', tooltip='Nice tooltip!')` I will always see the description and not text I mention for the tooltip.

**Comment by jasongrout** [comment]
I don't think anyone has implemented this.

**Comment by jasongrout** [comment]
(If you would like to implement it, a PR would be welcome!)

**Comment by deeplook** [comment]
Anything one can do to make this happen more quickly?

**Comment by zerline** [comment]
Hello all
FYI, part of the job is done on PR #2342 : for Text input, if description is void.

**Comment by zerline** [comment]
> Anything one can do to make this happen more quickly?

@deeplook what exactly do you need?

**Comment by deeplook** [comment]
@zerline The title says it all, doesn't it? "Implementing tooltips for all widgets"

**Comment by zerline** [comment]
@deeplook do you have some use cases in particular?

**Comment by deeplook** [comment]
@zerline Ermmm, I have a textarea and I want it to show a tooltip. What else do you need?

**Comment by zerline** [comment]
@deeplook do you think, or not, that you could use _description_tooltip_?  and in case description_tooltip does not help, do you actually need a different tooltip when mouse _over the description_, compared to when mouse _over the textarea_ itself or should it be the same? I'm asking those questions because the core developers seem reluctant to introduce tooltips "everywhere", so I'm looking for a consensus

**Comment by deeplook** [comment]
@zerline I really don't see a reason for adding so much complexity here. People expect a single tooltip from a widget. I don't see why a textarea should have two tooltips? In a normal GUI widget library anybody would expect a Widget base class to have a tooltip attribute and the subclasses get it "for free". Why is this so much different for ipywidgets?

**Comment by monstrorivas** [comment]
> do you think, or not, that you could use _description_tooltip_?

@zerline A lot of times we don't want to show the description of the widget (it's hard to style it). Showing the tooltip for the widget makes more sense than having the tooltip attached to the description

**Comment by maartenbreddels** [comment]
A bit more work, but https://github.com/mariobuikhuizen/ipyvuetify can do it (see the binder link for an example)

**Comment by fingoldo** [comment]
> Regarding 3: Nevermind, i managed to [fix](https://github.com/nlooije/ipywidgets/commit/71d382da00e2e4c228459c18eec4b87d1b243ef5) the problem getting a tooltip on a label in a TextField. Issuing:
> 
> `widgets.Text(description='Name: ', tooltip='Enter the name of the Text field')`
> 
> gives:
> 
> ![textfield](https://cloud.githubusercontent.com/assets/3252193/13737198/c28622d0-e9bb-11e5-9f3e-6bbbc65a1d84.PNG)
> 
> I would still like to know the answer to specifically question 2 before making a PR.

In 7.5.1, tooltip on a text field is not showing. Should there be any specific conditions met before it's being displayed?

**Comment by marscher** [comment]
`Text(description="name:", tooltip="enter your name")` triggers a warning in traitlets (5.1.0).
``` python
ipywidgets/widgets/widget.py:412: DeprecationWarning: Passing unrecognized arguments to super(Text).__init__(tooltip='Target distance between the individual points of a profile').
  object.__init__() takes exactly one argument (the instance to initialize)
  This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
    super(Widget, self).__init__(**kwargs)
```

**Comment by jmk89** [comment]
PR https://github.com/jupyter-widgets/ipywidgets/pull/2680 seems to have resolved this. Can this be closed?

**Comment by jasongrout** [comment]
Yes, thanks!
