### ISSUE TITLE
`Image` does not accept URLs, only data

### ISSUE THREAD

**Issue by sotte** [jupyter-widgets/ipywidgets#435]
Hey,

I think I found a bug with `Image`.

The ipywidget version of `Image` does not display an image, i.e., you get the broken link image symbol.

``` python
from ipywidgets import Image
Image(url='http://history.nasa.gov/ap11ann/kippsphotos/5903.jpg')
```

Whereas the IPython `Image` version does work.

``` python
from IPython.display import Image
Image(url='http://history.nasa.gov/ap11ann/kippsphotos/5903.jpg')
```

I also have the same problem when showing local images `Image(filename="image.jpg")`.

I'm using the following version

``` python
>>> import ipywidgets
>>> ipywidgets.__version__
'4.1.1'
```

**Comment by nlooije** [comment]
I can confirm this bug. As a work around i have defined a HTML widget which shows the image using:

`widgets.HTML(value='<img src="path_to_image.png">')`
`

**Comment by sotte** [comment]
That workaround works! Thanks.

**Comment by jdfreder** [comment]
Yeah, I think this makes sense, to add this feature.  Right now the Image widget's value accepts image data, not an image URL.  I think we can reasonably make it handle both.

**Comment by sotte** [comment]
What do you mean with "image data"? A numpy array? `Image(filename="image.jpg")` is also not accepted.

If `url` is not an accepted argument then Image should throw an exception if `url` is specified.

**Comment by jdfreder** [comment]
https://github.com/ipython/ipywidgets/blob/master/ipywidgets/widgets/widget_image.py#L36

[Traitlet bytes](https://github.com/ipython/traitlets/blob/master/traitlets/traitlets.py#L1890-L1899), which means the value must be python `bytes`, the image data.  

The format can be specified via the format traitlet:

https://github.com/ipython/ipywidgets/blob/master/ipywidgets/widgets/widget_image.py#L31
