### ISSUE TITLE
Integrate declarative widget base components into ipywidgets and jupyter-js-widgets

### ISSUE THREAD

**Issue by jdfreder** [jupyter-widgets/ipywidgets#556]
Hi all,

I'd like to integrate the fundamentals of the declarative widget framework into this repository.  Before I open a PR, I think it makes sense to roughly map what should be moved over or not.  The following picture of my whiteboard illustrates my understanding of the relevant subset of folders in decl. widgets.  Green checkmarks mean some or all should be moved into ipywidgets, red crosses mean none should be moved.  Crosses and checkmarks only exist on leaf nodes.

![declwidgets](https://cloud.githubusercontent.com/assets/3292874/14994149/2553c4e2-1123-11e6-8f53-9d9877d71808.jpg)

Would love for some quick feedback before I get started, @lbustelo @parente @SylvainCorlay .

Thanks!
Jon

**Comment by jdfreder** [comment]
cc @ellisonbg

**Comment by jdfreder** [comment]
There are some misspellings on my whiteboard, i.e. "del widget model" was meant to be "decl widget model" short for declarative.

**Comment by jdfreder** [comment]
My current thinking is I'd map the contents like so:

![declwidgets2](https://cloud.githubusercontent.com/assets/3292874/14994605/9af43040-1125-11e6-82f8-566e0277ce62.jpg)

**Comment by jasongrout** [comment]
The declarative widget project is now unmaintained, so this is no longer feasible.
