### ISSUE TITLE
Non-jquery slider

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#630]
Looking at slider options, here is a simple slider that appears to satisfy our needs: http://refreshless.com/nouislider/ (basic typescript definitions here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/nouislider/nouislider.d.ts)

@SylvainCorlay, @jdfreder, @afshin - what do you guys think of moving to use nouislider?

Another possibility is to use the browser sliders (they are pretty much standardized now, though the UI customizations vary greatly: https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/. The problem there is that we wouldn't have range sliders, which would be a regression.

**Comment by SylvainCorlay** [comment]
👎 on native browser sliders because of absence of range sliders that are used a lot.

**Comment by SylvainCorlay** [comment]
nouislider seems to only be about range sliders.

**Comment by SylvainCorlay** [comment]
Re: the current jquery ui slider, I just wanted to communicate that there is no problem with having jquery-based widgets.
It just happens that the slider is the only core widget to make use of jquery and it is the only reason why jupyter-js-widgets depends on jquery.

**Comment by jasongrout** [comment]
and jquery-ui...

**Comment by jasongrout** [comment]
nouislider has range sliders, but it's not *only* about range sliders...

**Comment by afshin** [comment]
`noUiSlider` seems reasonable enough to me. I don't have any experience with it, but it doesn't seem bloated to me, which is my main concern about external libs.

It might seem silly to ask, but are we cool with [WTFPL](http://www.wtfpl.net/about/)?

**Comment by jasongrout** [comment]
I looked into the license a bit. Wikipedia has a bunch of links where the FSF acknowledges it, it seems that various people (whatever that's worth) say it is basically a public domain dedication. The license author even says you can relicense work ("The WTFPL lets you relicense the work under any other license." on http://www.wtfpl.net/faq/), so even if we're not happy with it, it seems we can change the license and maintain a fork.

**Comment by jasongrout** [comment]
This would also probably fix #655.

**Comment by dakoop** [comment]
Apparently, new HTML specs have a "multiple" attribute for range sliders, and there is a polyfill: http://leaverou.github.io/multirange/

**Comment by SylvainCorlay** [comment]
@jasongrout the one-value HTML5 sliders works well and seems to be pretty well supported across the board. I started working on this in the plane for Austin. 

However this will probably require us to have a well-separated view for the range...

**Comment by gnestor** [comment]
@SylvainCorlay Do you think it makes sense for me to try out this [multirange polyfill](http://leaverou.github.io/multirange/) for the native HTML slider? Another thing to consider: If we are going to replace the jQuery slider with a native one, should we not do the same for [Dropdowns](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) and [Progress](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress) widgets? If so, then I think it would make sense to address the

> Give the widgets a facelift. Maybe material-ui? Home spun design?

 roadmap item at the same time and implement a consistent style across both native and non-native elements.

**Comment by maxnoy** [comment]
Additional option -- [ion.rangeSlider|http://ionden.com/a/plugins/ion.rangeSlider/en.html]. Supports both single and range slider modes. More demos [here|https://shiny.rstudio.com/gallery/widget-gallery.html].

**Comment by jasongrout** [comment]
Just saw this announcement about changes in the jquery-ui infrastructure going forward: http://blog.jqueryui.com/2017/12/the-future-of-jquery-ui-and-jquery-mobile/

I think that's another thing in favor of finding an alternative.

**Comment by denfromufa** [comment]
I found few range sliders with more useful features, thanks to @vidartf for pointing to this issue:

https://github.com/jupyter-widgets/ipywidgets/issues/2249

**Comment by jasongrout** [comment]
> It might seem silly to ask, but are we cool with [WTFPL](http://www.wtfpl.net/about/)?

It looks like nouislider is now licensed MIT, as of about a month ago.

**Comment by jasongrout** [comment]
A brief search still turned up these viable alternatives:

1. https://github.com/leongersen/noUiSlider
2. https://github.com/IonDen/ion.rangeSlider
3. https://github.com/sghall/react-compound-slider
4. https://github.com/react-component/slider

plus there are libraries like blueprintjs, etc.

**Comment by ibdafna** [comment]
As a part of the January 2020 meeting (#2641), we discussed the alternatives listed above, in addition to building our own implementation. The main considerations were keeping the slider as simple as possible - with range slider support, and reducing dependencies such as JQuery and JQuery-UI.

We voted in favour of noUiSlider as it has no dependencies, and although it is quite feature-packed, we can expose only a part of the API which will keep functionality in line with what is currently available. 

We also agreed that, if needed, migration from noUiSlider to any custom implementation should be relatively simple in the future and won't require a major release.

**Comment by ibdafna** [comment]
@jasongrout @SylvainCorlay @jtpio @mbektasbbg @vidartf @pbugnion @martinRenou

**Comment by jasongrout** [comment]
@ibdafna - can you list the other alternatives we considered, perhaps with a brief summary of the discussion about each?

**Comment by ibdafna** [comment]
Thanks, @jasongrout - I have added this to my comment above!

**Comment by afshin** [comment]
Does anybody have an opinion re: `interact.js`? It seems attractive: it supports touch events and it works on DOM nodes so it can be used within a `Widget` lifecycle.
https://interactjs.io/
https://www.npmjs.com/package/interactjs/v/1.8.2

**Comment by jasongrout** [comment]
As far as I can tell, interact.js is not a slider per se, but a library unifying touch and mouse events on top of which a slider could be built. Are you asking if we've thought about building our own slider on top of something like interact.js?

**Comment by afshin** [comment]
> Are you asking if we've thought about building our own slider on top of something like interact.js?

Yes. One of their examples is how you would implement a slider. It seems a bit higher level than Lumino drag drop support.

**Comment by jasongrout** [comment]
> One of their examples is how you would implement a slider.

Can you point to that example? I can't find it.

**Comment by afshin** [comment]
It's the first example on their docs page: https://interactjs.io/docs/

The code is linked to on that page, so if you just want to see the example:
https://codepen.io/taye/pen/GgpxNq

**Comment by afshin** [comment]
<img width="1150" alt="Screen Shot 2020-01-25 at 13 17 20" src="https://user-images.githubusercontent.com/159529/73121723-12f52280-3f75-11ea-9fbd-ee932efa6ff5.png">

**Comment by afshin** [comment]
Ah I didn't realize @ibdafna was so far along in [his slider PR](https://github.com/jupyter-widgets/ipywidgets/pull/2712).

**Comment by jasongrout** [comment]
Interesting. That demo has a max slider value of 0.87 for me (Firefox, macOS), which seems odd.

Yes, we're working on getting @ibdafna's nouislider implementation in, which is what we decided on at the widgets sprint. Thanks for pointing out an alternative, though!

**Comment by afshin** [comment]
Oh interesting, it must be a bug. It has that same behavior for me in both Firefox and Chrome.
