### ISSUE TITLE
Interact slider widget on mobile device

### ISSUE THREAD

**Issue by psychemedia** [jupyter-widgets/ipywidgets#655]
# Summary

Either switch to a mobile-friendly slider, or use something like http://touchpunch.furf.com/ to enable touch events on the current jqueryui slider

---
# Original issue

I was trying to demo a simple notebook with interact widgets via Chrome on an Android device, and whilst the slider widget rendered and the slider bar could be highlighted, trying to slide it seemed to be interpreted by the browser as a swipe.

Which makes me wonder - is there a special theme for mobile devices, or would the actual widget handler code need tweaking to work on mobile browsers?

**Comment by jasongrout** [comment]
I'm about to switch the slider to a mobile friendly slider, probably
experimenting with it in the next week or so.

**Comment by SylvainCorlay** [comment]
Indeed, the native browser slider should work on mobile devices.

**Comment by Dommsko** [comment]
Hello everyone, is there any progress on or workaround for this issue yet?

Kind regards,
Dominik

**Comment by Dommsko** [comment]
Hello everyone, is there an easy fix for this issue yet? I don't understand how to "switch to a mobile-friendly slider" like mentioned in the summary or how to "enable touch events on the current jqueryui slider". The URL http://touchpunch.furf.com/ isn't working, either, so I am completely stuck here. Any help would be appreciated!

(tested on Huawei P8 and iPad Pro)

Kind regards,
Dominik

**Comment by martinRenou** [comment]
The widgets implementation should change a lot in the next release, it's not relying on the jQueryUI slider anymore but on https://refreshless.com/nouislider, it seems to work on my mobile phone using a Chromium-based browser. 

I guess it's safe to close this issue. We can reopen it later if it actually don't work in the next release.

**Comment by apgdjr** [comment]
Thank you. Where can I check when the next release is planned for?
