### ISSUE TITLE
adding autocompletion for Text?

### ISSUE THREAD

**Issue by hainm** [jupyter-widgets/ipywidgets#692]
What do you think? similar to Dropdown but user doesn't need to scroll down much.

This is similar to jQuery, need to specify `source`
https://jqueryui.com/autocomplete/

**Comment by akhmerov** [comment]
While this isn't supported yet, is it possible to hack it in? For the jquery snippet, it appears I'd need to specify the `id` of the `input` element, is that possible currently?

**Comment by jasongrout** [comment]
> While this isn't supported yet, is it possible to hack it in? For the jquery snippet, it appears I'd need to specify the id of the input element, is that possible currently?

It's not currently possible to set the id of an input for a text widget.

**Comment by jasongrout** [comment]
I think it makes a lot of sense to make a separate autocomplete widget.

**Comment by jasongrout** [comment]
Or maybe the standard thing is a combobox control (cross between text and dropdown).

**Comment by theocean154** [comment]
@jasongrout any plans for this

**Comment by jasongrout** [comment]
I don't know anyone that has started working on it, if that's what you mean. It's not slated for 7.0, but if someone does it for 7.0, we're happy to consider merging it.

**Comment by chaoukiiiii** [comment]
any update? this feature added to 7.4 version?

**Comment by jasongrout** [comment]
As far as I know, there is no one working on this, or has definite plans to work on this in the near future. Again, if anyone wants to work on this, let us know.

**Comment by maartenbreddels** [comment]
For future reference, we may get support for that in [ipymaterialui](https://github.com/maartenbreddels/ipymaterialui), there are examples for [autocomplete in MaterialUI](https://material-ui.com/demos/autocomplete/), but I'm not sure yet if this will be exposed in ipymaterialui

**Comment by vidartf** [comment]
As a note, I recently did https://github.com/vidartf/ipycombobox which is a simple widget based on the `<datalist>` HTML5 tag. I'll open a PR for getting this into core, as this maps very well the concept of a combobox to basic HTML.
