### ISSUE TITLE
Example tutorial on static widgets

### ISSUE THREAD

**Issue by ga7g08** [jupyter-widgets/ipywidgets#758]
I'd like to use the ipywidgets to generate static widgets for use in a HTML page (such as [Jake's static interactive examples](https://jakevdp.github.io/blog/2013/12/05/static-interactive-widgets/)). From what I understand, the [original source](https://github.com/jakevdp/ipywidgets-static) is now `ipywidgets`.

There is [this release note](http://blog.jupyter.org/2016/04/22/ipywidgets5/)  pointing to [this page](http://jupyter.org/embed-jupyter-widgets.html) which demos a live static widget. But, it doesn't explain how to generate the HTML. Can someone please add a tutorial on how to do this (if the functionality really exists)?

**Comment by SylvainCorlay** [comment]
Posting something soon. This is also how we generated http://jupyter.org/widgets.html

**Comment by rdipietro** [comment]
Any update on this? I have been roaming around various blogs / github issues, and it seems that static widgets are celebrated as being complete, but I can't find a single working example of such widgets being successfully converted to html via `nbconvert`.

(Exception: http://jakevdp.github.io/blog/2013/12/05/static-interactive-widgets/, but this is 'obsolete' and corresponds to an outdated API. For example `StaticInteract` is used, but does not currently exist in the API.)

Interactive widgets work just fine for me within Jupyter notebooks, but they are entirely absent in any generated html (via `nbconvert`). I have also seen some posts suggesting that this has to do with the `inline` backend, but I've tried various others, too, and the same problem holds (`notebook`, `agg`, `nbagg`).

My ipywidgets version is 7.0.5 and my Jupyter version is 4.4.

Thanks!

**Comment by rdipietro** [comment]
Here is an example of it not working:

http://ipywidgets.readthedocs.io/en/stable/examples/Using%20Interact.html

I visited this page with both Chrome and Safari; works in neither.

However my issue is even a bit more severe: the plot and the interactive widgets are missing entirely in the HTML (rather than just having a frozen plot which doesn't update with the widgets).

**Comment by jasongrout** [comment]
Here is what the page looks like for me. Notice I am seeing the rendered widgets, though of course they won't work since the page is not connected to a kernel.

**Comment by jasongrout** [comment]
![screenshot_20171208-110346](https://user-images.githubusercontent.com/192614/33780978-a26cabd2-dc07-11e7-8a27-c57a8d89de06.png)

**Comment by jasongrout** [comment]
Sorry. Accidentally hit the close button.

So you are not seeing those widgets? Does your JavaScript console have any errors logged?

**Comment by rdipietro** [comment]
> Notice I am seeing the rendered widgets, though of course they won't work since the page is not connected to a kernel.

I think I might be misinterpreting the point of "static widgets." I thought it was for widgets to be usable after nbconvert, via a caching / storage mechanism, as described here, https://github.com/jupyter-widgets/ipywidgets/issues/16, and here, http://jakevdp.github.io/blog/2013/12/05/static-interactive-widgets/

No?

**Comment by jasongrout** [comment]
> I think I might be misinterpreting the point of "static widgets." I thought it was for widgets to be usable after nbconvert, via a caching / storage mechanism, as described here, #16, and here, http://jakevdp.github.io/blog/2013/12/05/static-interactive-widgets/

You're correct - "static widgets" as we've used the term is just about rendering the widget on the page. We don't implement any caching or storage mechanism like Jake's experiments.

**Comment by jasongrout** [comment]
That said, "static widgets" *can* be hooked up to a kernel so that they are live, but that requires some extra programming, such as in https://github.com/jupyter-widgets/ipywidgets/tree/master/examples/web3

**Comment by rdipietro** [comment]
Oh I see. Sorry for the confusion then!

**Comment by jasongrout** [comment]
Thanks again for asking. Closing as answered.

**Comment by psychemedia** [comment]
nbinteract https://github.com/SamLau95/nbinteract pehaps offers some sort of workaround, with a way of managing interactive execution via mybinder/binderhub?
