### ISSUE TITLE
Dropdown hogs Return, Up and Down keys

### ISSUE THREAD

**Issue by rmenegaux** [jupyter-widgets/ipywidgets#952]
I could not unbind keyboard events from a `Dropdown`. If I interact with a `Dropdown`, then the Return, Up, and Down keys are locked to the `Dropdown` for the whole notebook

Here's how to reproduce this:
- Create a Dropdown 
```python
from ipywidgets import Dropdown
Dropdown(options=['carrots', 'turnips'])
```
- Click on the Dropdown
- Click another cell, or anywhere that should normally deactivate the Dropdown.
- Now try to press the Return key, it will jump to the Dropdown and display its options

**Comment by jasongrout** [comment]
We should write down the specific semantics we want out of the dropdown, and then make sure the code conforms to it. Right now the code has several places where it takes the handlers off, but in slightly different ways and for slightly different reasons.

What should the semantics be?

**Comment by SylvainCorlay** [comment]
Removing the 6.0 milestone since we are using a select tag.

**Comment by jasongrout** [comment]
Closing since we are using the select tag now.
