### ISSUE TITLE
Make an Output model and view for the embedded widget manager

### ISSUE THREAD

**Issue by stsievert** [jupyter-widgets/ipywidgets#986]
# Summary

Figure out how to save the state of the output widget (i.e., the output messages) and make an embedded widget manager output view.

---
# Original issue

#16 is much appreciated! Thanks for this :+1:

I have (tried) to embed a widget in a static webpage but haven't had any luck. I follow the documentation and select "Widgets > Embed widget" and copy that snippet into an HTML page. When I open that HTML page, I see a blank screen and can inspect to find a Javascript error:

<img width="791" alt="screen shot 2016-12-14 at 9 52 57 am" src="https://cloud.githubusercontent.com/assets/1320475/21189084/23d85c92-c1e3-11e6-8e67-aebd64f5c5f2.png">

This is with 1b9af7e0693756bb2cde8ca3b2e5acda2fff6f6c and `python setup.py install` in a virtualenv. It's with a simple widget:

``` python
from ipywidgets import interact

def(x):
    return x

interact(f, x=10)
```

**Comment by stsievert** [comment]
Issues shouldn't go on beta software, closing.

**Comment by SylvainCorlay** [comment]
@stsievert this feature requires the current state of master

**Comment by stsievert** [comment]
I am reopening this issue; I still can't embed widgets into a static HTML page (I am on beta6). My process for trying to embed widgets:

1. I define a (simple) function and develop a widget around it.
3. I click on "Embed Widgets" and copy/paste the HTML into `widget.html`.
4. I open `widget.html` in my browser. I expect to see the widget in the browser, however a blank screen shows (and the console shows no errors).

It's not clear from the documentation if I'm supposed to define my own HTML code for the widget. That's the reason the documentation goes into such detail on the JSON schema?

**Comment by SylvainCorlay** [comment]
Hi @stsievert Can you provide the generated html file?

**Comment by stsievert** [comment]
Here's a dropbox link: https://www.dropbox.com/s/b85fath9kiqxxv8/widget.html?dl=0

It implements the function above.

**Comment by SylvainCorlay** [comment]
You are missing the `<html>` and `<body>` tags. The snippet of code that is generated by the embed widgets is meant to be pasted in an already valid html file.

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Your Title</title>
  </head>
  <body>
    <!-- page content -->
  </body>
</html>
```

**Comment by stsievert** [comment]
D'oh.

I tried inserting the `script` tags at `<!-- page content -->` and it still shows a blank webpage (at the same dropbox link).

A checkbox would be a good idea. I expected standalone minimal widgets but it'd be a good idea to provide code to embed too.

**Comment by SylvainCorlay** [comment]
> I tried inserting the script tags at  and it still shows a blank webpage (at the same dropbox link).

This is where it should be inserted. However, the dropbox link does not work anymore.

**Comment by stsievert** [comment]
https://www.dropbox.com/s/i6tv27vtyyjuymj/widget.html?dl=0

**Comment by SylvainCorlay** [comment]
Thanks. There is a legitimate issue here with the Output widget.

**Comment by jasongrout** [comment]
To elaborate, it seems that the output widget model did not have state exposed (see below). However, even if it did have state, there would still likely be a problem since the output view is provided by the widget manager, and I'm not sure that the embedded widget manager has an output renderer.

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Your Title</title>
  </head>
  <body>
    <script src="https://unpkg.com/jupyter-js-widgets@~2.0.20/dist/embed.js"></script>
    <script type="application/vnd.jupyter.widget-state+json">
    {
        "version_major": 1,
        "version_minor": 0,
        "state": {
            "50427d04869a4f18a279eeb7c91bde3f": {
                "model_name": "LayoutModel",
                "model_module": "jupyter-js-widgets",
                "model_module_version": "*",
                "state": {}
            },
            "828fd92ce1424fed83a67f887f4854b8": {
                "model_name": "VBoxModel",
                "model_module": "jupyter-js-widgets",
                "model_module_version": "*",
                "state": {
                    "_dom_classes": [
                        "widget-interact"
                    ],
                    "layout": "IPY_MODEL_50427d04869a4f18a279eeb7c91bde3f",
                    "children": [
                        "IPY_MODEL_3c48f013af5e4eb199ad56737ea09e5e",
                        "IPY_MODEL_feb0e69b4b8f4f11aa89f42ead586dcf"
                    ]
                }
            },
            "8c71a8ac3b224bd08ea546ab3c057431": {
                "model_name": "LayoutModel",
                "model_module": "jupyter-js-widgets",
                "model_module_version": "*",
                "state": {}
            },
            "3c48f013af5e4eb199ad56737ea09e5e": {
                "model_name": "IntSliderModel",
                "model_module": "jupyter-js-widgets",
                "model_module_version": "*",
                "state": {
                    "min": -10,
                    "layout": "IPY_MODEL_8c71a8ac3b224bd08ea546ab3c057431",
                    "value": 24,
                    "max": 30,
                    "description": "x"
                }
            },
            "6a4ef29ac9804a36a0f43c7468821097": {
                "model_name": "LayoutModel",
                "model_module": "jupyter-js-widgets",
                "model_module_version": "*",
                "state": {}
            },
            "feb0e69b4b8f4f11aa89f42ead586dcf": {
                "model_name": "OutputModel",
                "model_module": "jupyter-js-widgets",
                "model_module_version": "*",
                "state": {
                    "_model_module_version": "*",
                    "layout": "IPY_MODEL_6a4ef29ac9804a36a0f43c7468821097",
                    "_dom_classes": [],
                    "_model_module": "jupyter-js-widgets",
                    "_view_module": "jupyter-js-widgets",
                    "_view_module_version": "*",
                    "msg_throttle": 1
                }
            }
        }
    }
    </script>
    <script type="application/vnd.jupyter.widget-view+json">
    {
        "model_id": "828fd92ce1424fed83a67f887f4854b8"
    }
    </script>
    <!-- page content -->
  </body>
</html>
```

**Comment by jasongrout** [comment]
I've updated the title to reflect what needs to be done.

**Comment by SylvainCorlay** [comment]
Now that we have the placeholder widget in case of missing model,, this will not crash pages with embedded widgets that include output widgets anymore. I removed the critical label.

**Comment by SylvainCorlay** [comment]
Pushing this forward to 6.1.

**Comment by ccordoba12** [comment]
Subscribing to this issue (sorry for the noise :-)

**Comment by kmallick2000** [comment]
I anxious to know when it is resolved as well. On hold on a few projects unless this is resolved.

**Comment by jasongrout** [comment]
Note to whoever does this: one way to do it without having to sync the output messages back to the kernel is to make a custom private field, say _output_messages, which is either null or the list of outputs. Generally, it will be null, but it has a custom serializer that puts in the output messages. Since we'll never save changes manually on this field, the output messages are never sent to the kernel. But saving the output widget state to the notebook will substitute in the output messages so they are persisted. On instantiation, the output widget will look at this field for an initial set of output messages, and then clear the field.

**Comment by kmallick2000** [comment]
You mean there is a temporary workaround? Can you please provide a tiny code example for us mere mortals who just want it to work? Really appreciate it!

**Comment by jasongrout** [comment]
No, there isn't a temporary work around. That was just me jotting down a few notes about how it could be implemented for whoever volunteers to fix this issue.

**Comment by jasongrout** [comment]
> one way to do it without having to sync the output messages back to the kernel

Note to self: I've been working on this, and maybe we shouldn't try to be so clever. It increases the sync bandwidth (quadratically, since each new message syncs *everything*), but makes the output widget *much* more understandable if the outputs are synced back to the server, and then we get saving and restoring for free.

And if we do try to be clever, we should probably also strip the output messages to just the information needed to render them. For example, we don't need the username in the header, nor do we need the parent_header. It looks like we need just the message type and the content fields.

**Comment by jasongrout** [comment]
> To elaborate, it seems that the output widget model did not have state exposed (see below).

This is fixed in #1294.

**Comment by jasongrout** [comment]
Note to whoever develops this: with #1294, we have the output messages being stored. To do the rendering, I'd suggest writing an output widget very similar to the JupyterLab output widget (we'll have to create a default renderer, though). That will likely be much easier to package up than the classic notebook output area.

In fact, we might be able to write a separate output widget package that can be used in both places, and just make an appropriate widget manager in each case (which would need context and rendermime attributes).

**Comment by jasongrout** [comment]
This is done in #1410. Thanks @pbugnion!
